CREATE PROC [dbo].[proc_d_udwcloudsync_club_master_roster] @current_dv_batch_id [bigint] AS
begin

set nocount on
set xact_abort on

--Start!
-- Get the @max_dv_batch_id from dimension/fact.  Use -2 if there aren't any records.
declare @max_dv_batch_id bigint = (select isnull(max(dv_batch_id),-2) from d_udwcloudsync_club_master_roster)

-- Find the PIT records with dv_batch_id > @max_dv_batch_id
-- and find the PIT records with dv_batch_id = @current_dv_batch_id since those need to be deleted in case of a retry
if object_id('tempdb..#p_udwcloudsync_club_master_roster_insert') is not null drop table #p_udwcloudsync_club_master_roster_insert
create table dbo.#p_udwcloudsync_club_master_roster_insert with(distribution=hash(bk_hash), location=user_db) as
select p_udwcloudsync_club_master_roster.p_udwcloudsync_club_master_roster_id,
       p_udwcloudsync_club_master_roster.bk_hash
  from dbo.p_udwcloudsync_club_master_roster
 where p_udwcloudsync_club_master_roster.dv_load_end_date_time = convert(datetime,'9999.12.31',102)
   and (p_udwcloudsync_club_master_roster.dv_batch_id > @max_dv_batch_id
        or p_udwcloudsync_club_master_roster.dv_batch_id = @current_dv_batch_id)

-- calculate all values of the records to be inserted to make the actual update go as fast as possible
if object_id('tempdb..#insert') is not null drop table #insert
create table dbo.#insert with(distribution=hash(bk_hash), location=user_db) as
select p_udwcloudsync_club_master_roster.bk_hash,
       p_udwcloudsync_club_master_roster.bk_hash dim_club_key,
       p_udwcloudsync_club_master_roster.mms_club_id mms_club_id,
       s_udwcloudsync_club_master_roster.access_type access_type,
       s_udwcloudsync_club_master_roster.activity_center activity_center,
       case when p_udwcloudsync_club_master_roster.bk_hash in ('-997','-998','-999') then 'N'
            when s_udwcloudsync_club_master_roster.allow_junior_check_in_flag = 1 then 'Y'
            else 'N'
        end allow_junior_check_in_flag,
       s_udwcloudsync_club_master_roster.aquatics_dh aquatics_dh,
       s_udwcloudsync_club_master_roster.aquatics_regional_manager aquatics_regional_manager,
       s_udwcloudsync_club_master_roster.area area,
       s_udwcloudsync_club_master_roster.area_director area_director,
       s_udwcloudsync_club_master_roster.asst_general_manager asst_general_manager,
       s_udwcloudsync_club_master_roster.athletic_lta athletic_lta,
       s_udwcloudsync_club_master_roster.basketball_courts basketball_courts,
       s_udwcloudsync_club_master_roster.basketball_trainer basketball_trainer,
       s_udwcloudsync_club_master_roster.bulding_engineer bulding_engineer,
       s_udwcloudsync_club_master_roster.business_administrator business_administrator,
       s_udwcloudsync_club_master_roster.cafe cafe,
       s_udwcloudsync_club_master_roster.center_type center_type,
       s_udwcloudsync_club_master_roster.child_center_kids_activities_dh child_center_kids_activities_dh,
       s_udwcloudsync_club_master_roster.cig_status cig_status,
       s_udwcloudsync_club_master_roster.clinic clinic,
       s_udwcloudsync_club_master_roster.club_master_roster_id club_master_roster_id,
       s_udwcloudsync_club_master_roster.club_master_roster_order club_master_roster_order,
       s_udwcloudsync_club_master_roster.cognos_name cognos_name,
       s_udwcloudsync_club_master_roster.current_operations_status current_operations_status,
       s_udwcloudsync_club_master_roster.cycle_studios cycle_studios,
       case when p_udwcloudsync_club_master_roster.bk_hash in ('-997','-998','-999') then p_udwcloudsync_club_master_roster.bk_hash
       when l_udwcloudsync_club_master_roster.spabiz_store_num is null then '-998'
       else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(l_udwcloudsync_club_master_roster.spabiz_store_num as decimal(26,6)) as varchar(500)),'z#@$k%&P'))),2)
       end dim_spabiz_store_key,
       case when p_udwcloudsync_club_master_roster.bk_hash in ('-997','-998','-999') then 'N'
            when s_udwcloudsync_club_master_roster.display_ui_flag = 1 then 'Y'
            else 'N'
        end display_ui_flag,
       s_udwcloudsync_club_master_roster.effective_permissions_mask effective_permissions_mask,
       s_udwcloudsync_club_master_roster.egroup_name egroup_name,
       s_udwcloudsync_club_master_roster.email_alert email_alert,
       s_udwcloudsync_club_master_roster.facility_operations_dh facility_operations_dh,
       s_udwcloudsync_club_master_roster.facility_technician facility_technician,
       s_udwcloudsync_club_master_roster.family_swim family_swim,
       s_udwcloudsync_club_master_roster.general_manager general_manager,
       s_udwcloudsync_club_master_roster.group_fitness_dh group_fitness_dh,
       s_udwcloudsync_club_master_roster.group_fitness_studios group_fitness_studios,
       s_udwcloudsync_club_master_roster.growth_type growth_type,
       s_udwcloudsync_club_master_roster.hyperion_planning hyperion_planning,
       s_udwcloudsync_club_master_roster.indoor_pool indoor_pool,
       s_udwcloudsync_club_master_roster.indoor_tennis_courts indoor_tennis_courts,
       s_udwcloudsync_club_master_roster.kids_regional_manager kids_regional_manager,
       s_udwcloudsync_club_master_roster.lap_pools lap_pools,
       s_udwcloudsync_club_master_roster.leases_owned leases_owned,
       s_udwcloudsync_club_master_roster.level level,
       s_udwcloudsync_club_master_roster.life_cafe_dh life_cafe_dh,
       s_udwcloudsync_club_master_roster.life_shop life_shop,
       s_udwcloudsync_club_master_roster.life_spa_dh life_spa_dh,
       s_udwcloudsync_club_master_roster.marketing_club_level marketing_club_level,
       s_udwcloudsync_club_master_roster.marketing_club_name marketing_club_name,
       s_udwcloudsync_club_master_roster.marketing_map_region marketing_map_region,
       s_udwcloudsync_club_master_roster.marketing_map_xml_state_name marketing_map_xml_state_name,
       s_udwcloudsync_club_master_roster.mca_studios mca_studios,
       s_udwcloudsync_club_master_roster.member_engagement_manager member_engagement_manager,
       s_udwcloudsync_club_master_roster.member_services_dh member_services_dh,
       s_udwcloudsync_club_master_roster.membership_level membership_level,
       s_udwcloudsync_club_master_roster.membership_level_needed_for_tennis membership_level_needed_for_tennis,
       s_udwcloudsync_club_master_roster.number_of_slides number_of_slides,
       s_udwcloudsync_club_master_roster.nutrition_coach nutrition_coach,
       s_udwcloudsync_club_master_roster.nutrition_regional_manager nutrition_regional_manager,
       s_udwcloudsync_club_master_roster.open_24_hours open_24_hours,
       s_udwcloudsync_club_master_roster.[open] open_status,
       s_udwcloudsync_club_master_roster.opened_date opened_date,
       s_udwcloudsync_club_master_roster.operationsregionalmanager operations_regional_manager,
       s_udwcloudsync_club_master_roster.ops_rcl_sr_dh ops_rcl_sr_dh,
       s_udwcloudsync_club_master_roster.outdoor_pool outdoor_pool,
       s_udwcloudsync_club_master_roster.outdoor_tennis_courts outdoor_tennis_courts,
       s_udwcloudsync_club_master_roster.parents_night_out parents_night_out,
       s_udwcloudsync_club_master_roster.personal_training_dh personal_training_dh,
       s_udwcloudsync_club_master_roster.personal_training_rcm personal_training_rcm,
       s_udwcloudsync_club_master_roster.personal_training_regional_manager personal_training_regional_manager,
       s_udwcloudsync_club_master_roster.pilates_studio pilates_studio,
       s_udwcloudsync_club_master_roster.pre_sale_address pre_sale_address,
       s_udwcloudsync_club_master_roster.property_bag property_bag,
       s_udwcloudsync_club_master_roster.racquet_ball_courts racquet_ball_courts,
       s_udwcloudsync_club_master_roster.racquet_regional_manager racquet_regional_manager,
       s_udwcloudsync_club_master_roster.region region,
       s_udwcloudsync_club_master_roster.regional_sales_manager regional_sales_manager,
       s_udwcloudsync_club_master_roster.regional_vice_president regional_vice_president,
       s_udwcloudsync_club_master_roster.restricted restricted,
       s_udwcloudsync_club_master_roster.salesregionalmanager sales_regional_manager,
       s_udwcloudsync_club_master_roster.school_break_camps school_break_camps,
       s_udwcloudsync_club_master_roster.senior_general_manager senior_general_manager,
       s_udwcloudsync_club_master_roster.spa spa,
       s_udwcloudsync_club_master_roster.square_footage square_footage,
       s_udwcloudsync_club_master_roster.squash_courts squash_courts,
       s_udwcloudsync_club_master_roster.squash_kids squash_kids,
       s_udwcloudsync_club_master_roster.summer_break_camps summer_break_camps,
       s_udwcloudsync_club_master_roster.tennis_courts tennis_courts,
       s_udwcloudsync_club_master_roster.tennis_dh tennis_dh,
       s_udwcloudsync_club_master_roster.three_story three_story,
       s_udwcloudsync_club_master_roster.turf_field turf_field,
       s_udwcloudsync_club_master_roster.unique_features unique_features,
       s_udwcloudsync_club_master_roster.unique_id unique_id,
       s_udwcloudsync_club_master_roster.water_slides water_slides,
       s_udwcloudsync_club_master_roster.whirpools whirpools,
       case when p_udwcloudsync_club_master_roster.bk_hash in ('-997','-998','-999') then p_udwcloudsync_club_master_roster.bk_hash
       when l_udwcloudsync_club_master_roster.workday_region_id is null then '-998'
       else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(cast(l_udwcloudsync_club_master_roster.workday_region_id as int) as int) as varchar(500)),'z#@$k%&P'))),2)
       end workday_region_key,
       s_udwcloudsync_club_master_roster.yoga_studios yoga_studios,
       s_udwcloudsync_club_master_roster.zero_depth_entry zero_depth_entry,
       h_udwcloudsync_club_master_roster.dv_deleted,
       p_udwcloudsync_club_master_roster.p_udwcloudsync_club_master_roster_id,
       p_udwcloudsync_club_master_roster.dv_batch_id,
       p_udwcloudsync_club_master_roster.dv_load_date_time,
       p_udwcloudsync_club_master_roster.dv_load_end_date_time
  from dbo.h_udwcloudsync_club_master_roster
  join dbo.p_udwcloudsync_club_master_roster
    on h_udwcloudsync_club_master_roster.bk_hash = p_udwcloudsync_club_master_roster.bk_hash
  join #p_udwcloudsync_club_master_roster_insert
    on p_udwcloudsync_club_master_roster.bk_hash = #p_udwcloudsync_club_master_roster_insert.bk_hash
   and p_udwcloudsync_club_master_roster.p_udwcloudsync_club_master_roster_id = #p_udwcloudsync_club_master_roster_insert.p_udwcloudsync_club_master_roster_id
  join dbo.l_udwcloudsync_club_master_roster
    on p_udwcloudsync_club_master_roster.bk_hash = l_udwcloudsync_club_master_roster.bk_hash
   and p_udwcloudsync_club_master_roster.l_udwcloudsync_club_master_roster_id = l_udwcloudsync_club_master_roster.l_udwcloudsync_club_master_roster_id
  join dbo.s_udwcloudsync_club_master_roster
    on p_udwcloudsync_club_master_roster.bk_hash = s_udwcloudsync_club_master_roster.bk_hash
   and p_udwcloudsync_club_master_roster.s_udwcloudsync_club_master_roster_id = s_udwcloudsync_club_master_roster.s_udwcloudsync_club_master_roster_id

-- do as a single transaction
--   delete records from the dimensional table where the business_key is in #p_*_insert temp table
--   insert records from all of the joins to the pit table and to #p_*_insert temp table
begin tran
  delete dbo.d_udwcloudsync_club_master_roster
   where d_udwcloudsync_club_master_roster.bk_hash in (select bk_hash from #p_udwcloudsync_club_master_roster_insert)

  insert dbo.d_udwcloudsync_club_master_roster(
             bk_hash,
             dim_club_key,
             mms_club_id,
             access_type,
             activity_center,
             allow_junior_check_in_flag,
             aquatics_dh,
             aquatics_regional_manager,
             area,
             area_director,
             asst_general_manager,
             athletic_lta,
             basketball_courts,
             basketball_trainer,
             bulding_engineer,
             business_administrator,
             cafe,
             center_type,
             child_center_kids_activities_dh,
             cig_status,
             clinic,
             club_master_roster_id,
             club_master_roster_order,
             cognos_name,
             current_operations_status,
             cycle_studios,
             dim_spabiz_store_key,
             display_ui_flag,
             effective_permissions_mask,
             egroup_name,
             email_alert,
             facility_operations_dh,
             facility_technician,
             family_swim,
             general_manager,
             group_fitness_dh,
             group_fitness_studios,
             growth_type,
             hyperion_planning,
             indoor_pool,
             indoor_tennis_courts,
             kids_regional_manager,
             lap_pools,
             leases_owned,
             level,
             life_cafe_dh,
             life_shop,
             life_spa_dh,
             marketing_club_level,
             marketing_club_name,
             marketing_map_region,
             marketing_map_xml_state_name,
             mca_studios,
             member_engagement_manager,
             member_services_dh,
             membership_level,
             membership_level_needed_for_tennis,
             number_of_slides,
             nutrition_coach,
             nutrition_regional_manager,
             open_24_hours,
             open_status,
             opened_date,
             operations_regional_manager,
             ops_rcl_sr_dh,
             outdoor_pool,
             outdoor_tennis_courts,
             parents_night_out,
             personal_training_dh,
             personal_training_rcm,
             personal_training_regional_manager,
             pilates_studio,
             pre_sale_address,
             property_bag,
             racquet_ball_courts,
             racquet_regional_manager,
             region,
             regional_sales_manager,
             regional_vice_president,
             restricted,
             sales_regional_manager,
             school_break_camps,
             senior_general_manager,
             spa,
             square_footage,
             squash_courts,
             squash_kids,
             summer_break_camps,
             tennis_courts,
             tennis_dh,
             three_story,
             turf_field,
             unique_features,
             unique_id,
             water_slides,
             whirpools,
             workday_region_key,
             yoga_studios,
             zero_depth_entry,
             deleted_flag,
             p_udwcloudsync_club_master_roster_id,
             dv_load_date_time,
             dv_load_end_date_time,
             dv_batch_id,
             dv_inserted_date_time,
             dv_insert_user)
  select bk_hash,
         dim_club_key,
         mms_club_id,
         access_type,
         activity_center,
         allow_junior_check_in_flag,
         aquatics_dh,
         aquatics_regional_manager,
         area,
         area_director,
         asst_general_manager,
         athletic_lta,
         basketball_courts,
         basketball_trainer,
         bulding_engineer,
         business_administrator,
         cafe,
         center_type,
         child_center_kids_activities_dh,
         cig_status,
         clinic,
         club_master_roster_id,
         club_master_roster_order,
         cognos_name,
         current_operations_status,
         cycle_studios,
         dim_spabiz_store_key,
         display_ui_flag,
         effective_permissions_mask,
         egroup_name,
         email_alert,
         facility_operations_dh,
         facility_technician,
         family_swim,
         general_manager,
         group_fitness_dh,
         group_fitness_studios,
         growth_type,
         hyperion_planning,
         indoor_pool,
         indoor_tennis_courts,
         kids_regional_manager,
         lap_pools,
         leases_owned,
         level,
         life_cafe_dh,
         life_shop,
         life_spa_dh,
         marketing_club_level,
         marketing_club_name,
         marketing_map_region,
         marketing_map_xml_state_name,
         mca_studios,
         member_engagement_manager,
         member_services_dh,
         membership_level,
         membership_level_needed_for_tennis,
         number_of_slides,
         nutrition_coach,
         nutrition_regional_manager,
         open_24_hours,
         open_status,
         opened_date,
         operations_regional_manager,
         ops_rcl_sr_dh,
         outdoor_pool,
         outdoor_tennis_courts,
         parents_night_out,
         personal_training_dh,
         personal_training_rcm,
         personal_training_regional_manager,
         pilates_studio,
         pre_sale_address,
         property_bag,
         racquet_ball_courts,
         racquet_regional_manager,
         region,
         regional_sales_manager,
         regional_vice_president,
         restricted,
         sales_regional_manager,
         school_break_camps,
         senior_general_manager,
         spa,
         square_footage,
         squash_courts,
         squash_kids,
         summer_break_camps,
         tennis_courts,
         tennis_dh,
         three_story,
         turf_field,
         unique_features,
         unique_id,
         water_slides,
         whirpools,
         workday_region_key,
         yoga_studios,
         zero_depth_entry,
         dv_deleted,
         p_udwcloudsync_club_master_roster_id,
         dv_load_date_time,
         dv_load_end_date_time,
         dv_batch_id,
         getdate(),
         suser_sname()
    from #insert
commit tran

--force replication
set @max_dv_batch_id = (select isnull(max(dv_batch_id),-2) from d_udwcloudsync_club_master_roster)
--Done!
end
