CREATE PROC [dbo].[proc_d_hybris_products] @current_dv_batch_id [bigint] AS
begin

set nocount on
set xact_abort on

--Start!
-- Get the @max_dv_batch_id from dimension/fact.  Use -2 if there aren't any records.
declare @max_dv_batch_id bigint = (select isnull(max(dv_batch_id),-2) from d_hybris_products)

-- Find the PIT records with dv_batch_id > @max_dv_batch_id
-- and find the PIT records with dv_batch_id = @current_dv_batch_id since those need to be deleted in case of a retry
if object_id('tempdb..#p_hybris_products_insert') is not null drop table #p_hybris_products_insert
create table dbo.#p_hybris_products_insert with(distribution=hash(bk_hash), location=user_db) as
select p_hybris_products.p_hybris_products_id,
       p_hybris_products.bk_hash
  from dbo.p_hybris_products
 where p_hybris_products.dv_load_end_date_time = convert(datetime,'9999.12.31',102)
   and (p_hybris_products.dv_batch_id > @max_dv_batch_id
        or p_hybris_products.dv_batch_id = @current_dv_batch_id)

-- calculate all values of the records to be inserted to make the actual update go as fast as possible
if object_id('tempdb..#insert') is not null drop table #insert
create table dbo.#insert with(distribution=hash(bk_hash), location=user_db) as
select p_hybris_products.bk_hash,
       p_hybris_products.bk_hash d_hybris_products_key,
       p_hybris_products.products_pk products_pk,
       s_hybris_products.code code,
       s_hybris_products.created_ts created_ts,
       s_hybris_products.hjmpts hjmpts,
       s_hybris_products.modified_ts modified_ts,
       l_hybris_products.owner_pk_string owner_pk_string,
       l_hybris_products.p_agreement p_agreement,
       s_hybris_products.p_allow_member_selection p_allow_member_selection,
       l_hybris_products.p_approval_status p_approval_status,
       l_hybris_products.p_article p_article,
       s_hybris_products.p_auto_shipflag p_auto_shipflag,
       s_hybris_products.p_auto_thumb_nails p_auto_thumb_nails,
       s_hybris_products.p_barcode p_barcode,
       l_hybris_products.p_base_product p_base_product,
       s_hybris_products.p_canadian_product p_canadian_product,
       l_hybris_products.p_card_type p_card_type,
       l_hybris_products.p_catalog p_catalog,
       l_hybris_products.p_catalog_version p_catalog_version,
       l_hybris_products.p_club p_club,
       l_hybris_products.p_content_unit p_content_unit,
       s_hybris_products.p_cost_center_id p_cost_center_id,
       s_hybris_products.p_data_sheet p_data_sheet,
       s_hybris_products.p_delivery_time p_delivery_time,
       s_hybris_products.p_denomination p_denomination,
       s_hybris_products.p_detail p_detail,
       s_hybris_products.p_display_number p_display_number,
       s_hybris_products.p_e_gift_card_flag p_e_gift_card_flag,
       s_hybris_products.p_e_gift_cards p_e_gift_cards,
       s_hybris_products.p_ean p_ean,
       s_hybris_products.p_electronic_shipping_flag p_electronic_shipping_flag,
       s_hybris_products.p_email_template_id p_email_template_id,
       s_hybris_products.p_end_line_number p_end_line_number,
       s_hybris_products.p_erp_group_buyer p_erp_group_buyer,
       s_hybris_products.p_erp_group_supplier p_erp_group_supplier,
       l_hybris_products.p_europe_1_price_factory_pdg p_europe_1_price_factory_pdg,
       l_hybris_products.p_europe_1_price_factory_ppg p_europe_1_price_factory_ppg,
       l_hybris_products.p_europe_1_price_factory_ptg p_europe_1_price_factory_ptg,
       s_hybris_products.p_external_redeem_flag p_external_redeem_flag,
       s_hybris_products.p_free_usps_shipping_flag p_free_usps_shipping_flag,
       l_hybris_products.p_fulfillment_partner p_fulfillment_partner,
       s_hybris_products.p_fulfillment_product_id p_fulfillment_product_id,
       s_hybris_products.p_gallery_images p_gallery_images,
       l_hybris_products.p_gender p_gender,
       s_hybris_products.p_genders p_genders,
       s_hybris_products.p_gift_card_flag p_gift_card_flag,
       s_hybris_products.p_is_giftable p_is_giftable,
       s_hybris_products.p_item_description p_item_description,
       s_hybris_products.p_logo p_logo,
       s_hybris_products.p_lt_bucks_amount p_lt_bucks_amount,
       s_hybris_products.p_lt_bucks_flag p_lt_bucks_flag,
       s_hybris_products.p_ltf_offer_flag p_ltf_offer_flag,
       s_hybris_products.p_ltf_only_product p_ltf_only_product,
       s_hybris_products.p_ma_local_flag p_ma_local_flag,
       s_hybris_products.p_manufacturer_aid p_manufacturer_aid,
       s_hybris_products.p_manufacturer_name p_manufacturer_name,
       s_hybris_products.p_max_order_quantity p_max_order_quantity,
       l_hybris_products.p_media p_media,
       l_hybris_products.p_media_container p_media_container,
       s_hybris_products.p_min_order_quantity p_min_order_quantity,
       s_hybris_products.p_mms_product_id p_mms_product_id,
       s_hybris_products.p_mms_recurrent p_mms_recurrent,
       s_hybris_products.p_mobile_product_flag p_mobile_product_flag,
       s_hybris_products.p_normal p_normal,
       s_hybris_products.p_number p_number,
       s_hybris_products.p_number_content_units p_number_content_units,
       s_hybris_products.p_occasions p_occasions,
       s_hybris_products.p_offer_external_link_flag p_offer_external_link_flag,
       s_hybris_products.p_offering_id p_offering_id,
       s_hybris_products.p_offline_date p_offline_date,
       s_hybris_products.p_online_date p_online_date,
       s_hybris_products.p_order p_order,
       s_hybris_products.p_order_quantity_interval p_order_quantity_interval,
       s_hybris_products.p_others p_others,
       l_hybris_products.p_personal_details p_personal_details,
       l_hybris_products.p_picture p_picture,
       l_hybris_products.p_previous_base_product p_previous_base_product,
       s_hybris_products.p_price_quantity p_price_quantity,
       s_hybris_products.p_product_cost p_product_cost,
       s_hybris_products.p_product_height p_product_height,
       s_hybris_products.p_product_length p_product_length,
       s_hybris_products.p_product_messages p_product_messages,
       l_hybris_products.p_product_order_limit p_product_order_limit,
       l_hybris_products.p_product_tag p_product_tag,
       s_hybris_products.p_product_width p_product_width,
       l_hybris_products.p_raw_asset p_raw_asset,
       s_hybris_products.p_region_id p_region_id,
       s_hybris_products.p_rev_category_id p_rev_category_id,
       s_hybris_products.p_searchable p_searchable,
       l_hybris_products.p_sequence_id p_sequence_id,
       l_hybris_products.p_simple_asset p_simple_asset,
       s_hybris_products.p_spend_category_id p_spend_category_id,
       s_hybris_products.p_start_line_number p_start_line_number,
       l_hybris_products.p_state p_state,
       s_hybris_products.p_supplier_alternative_aid p_supplier_alternative_aid,
       s_hybris_products.p_swatch_colour p_swatch_colour,
       l_hybris_products.p_thumb_nail p_thumb_nail,
       s_hybris_products.p_thumb_nails p_thumb_nails,
       l_hybris_products.p_training_session p_training_session,
       s_hybris_products.p_type_descriptor p_type_descriptor,
       l_hybris_products.p_variant_type p_variant_type,
       s_hybris_products.p_weight p_weight,
       s_hybris_products.prop_ts prop_ts,
       l_hybris_products.type_pk_string type_pk_string,
       l_hybris_products.unit_pk unit_pk,
       p_hybris_products.p_hybris_products_id,
       p_hybris_products.dv_batch_id,
       p_hybris_products.dv_load_date_time,
       p_hybris_products.dv_load_end_date_time
  from dbo.h_hybris_products
  join dbo.p_hybris_products
    on h_hybris_products.bk_hash = p_hybris_products.bk_hash  join #p_hybris_products_insert
    on p_hybris_products.bk_hash = #p_hybris_products_insert.bk_hash
   and p_hybris_products.p_hybris_products_id = #p_hybris_products_insert.p_hybris_products_id
  join dbo.l_hybris_products
    on p_hybris_products.bk_hash = l_hybris_products.bk_hash
   and p_hybris_products.l_hybris_products_id = l_hybris_products.l_hybris_products_id
  join dbo.s_hybris_products
    on p_hybris_products.bk_hash = s_hybris_products.bk_hash
   and p_hybris_products.s_hybris_products_id = s_hybris_products.s_hybris_products_id

-- do as a single transaction
--   delete records from the dimensional table where the business_key is in #p_*_insert temp table
--   insert records from all of the joins to the pit table and to #p_*_insert temp table
begin tran
  delete dbo.d_hybris_products
   where d_hybris_products.bk_hash in (select bk_hash from #p_hybris_products_insert)

  insert dbo.d_hybris_products(
             bk_hash,
             d_hybris_products_key,
             products_pk,
             code,
             created_ts,
             hjmpts,
             modified_ts,
             owner_pk_string,
             p_agreement,
             p_allow_member_selection,
             p_approval_status,
             p_article,
             p_auto_shipflag,
             p_auto_thumb_nails,
             p_barcode,
             p_base_product,
             p_canadian_product,
             p_card_type,
             p_catalog,
             p_catalog_version,
             p_club,
             p_content_unit,
             p_cost_center_id,
             p_data_sheet,
             p_delivery_time,
             p_denomination,
             p_detail,
             p_display_number,
             p_e_gift_card_flag,
             p_e_gift_cards,
             p_ean,
             p_electronic_shipping_flag,
             p_email_template_id,
             p_end_line_number,
             p_erp_group_buyer,
             p_erp_group_supplier,
             p_europe_1_price_factory_pdg,
             p_europe_1_price_factory_ppg,
             p_europe_1_price_factory_ptg,
             p_external_redeem_flag,
             p_free_usps_shipping_flag,
             p_fulfillment_partner,
             p_fulfillment_product_id,
             p_gallery_images,
             p_gender,
             p_genders,
             p_gift_card_flag,
             p_is_giftable,
             p_item_description,
             p_logo,
             p_lt_bucks_amount,
             p_lt_bucks_flag,
             p_ltf_offer_flag,
             p_ltf_only_product,
             p_ma_local_flag,
             p_manufacturer_aid,
             p_manufacturer_name,
             p_max_order_quantity,
             p_media,
             p_media_container,
             p_min_order_quantity,
             p_mms_product_id,
             p_mms_recurrent,
             p_mobile_product_flag,
             p_normal,
             p_number,
             p_number_content_units,
             p_occasions,
             p_offer_external_link_flag,
             p_offering_id,
             p_offline_date,
             p_online_date,
             p_order,
             p_order_quantity_interval,
             p_others,
             p_personal_details,
             p_picture,
             p_previous_base_product,
             p_price_quantity,
             p_product_cost,
             p_product_height,
             p_product_length,
             p_product_messages,
             p_product_order_limit,
             p_product_tag,
             p_product_width,
             p_raw_asset,
             p_region_id,
             p_rev_category_id,
             p_searchable,
             p_sequence_id,
             p_simple_asset,
             p_spend_category_id,
             p_start_line_number,
             p_state,
             p_supplier_alternative_aid,
             p_swatch_colour,
             p_thumb_nail,
             p_thumb_nails,
             p_training_session,
             p_type_descriptor,
             p_variant_type,
             p_weight,
             prop_ts,
             type_pk_string,
             unit_pk,
             p_hybris_products_id,
             dv_load_date_time,
             dv_load_end_date_time,
             dv_batch_id,
             dv_inserted_date_time,
             dv_insert_user)
  select bk_hash,
         d_hybris_products_key,
         products_pk,
         code,
         created_ts,
         hjmpts,
         modified_ts,
         owner_pk_string,
         p_agreement,
         p_allow_member_selection,
         p_approval_status,
         p_article,
         p_auto_shipflag,
         p_auto_thumb_nails,
         p_barcode,
         p_base_product,
         p_canadian_product,
         p_card_type,
         p_catalog,
         p_catalog_version,
         p_club,
         p_content_unit,
         p_cost_center_id,
         p_data_sheet,
         p_delivery_time,
         p_denomination,
         p_detail,
         p_display_number,
         p_e_gift_card_flag,
         p_e_gift_cards,
         p_ean,
         p_electronic_shipping_flag,
         p_email_template_id,
         p_end_line_number,
         p_erp_group_buyer,
         p_erp_group_supplier,
         p_europe_1_price_factory_pdg,
         p_europe_1_price_factory_ppg,
         p_europe_1_price_factory_ptg,
         p_external_redeem_flag,
         p_free_usps_shipping_flag,
         p_fulfillment_partner,
         p_fulfillment_product_id,
         p_gallery_images,
         p_gender,
         p_genders,
         p_gift_card_flag,
         p_is_giftable,
         p_item_description,
         p_logo,
         p_lt_bucks_amount,
         p_lt_bucks_flag,
         p_ltf_offer_flag,
         p_ltf_only_product,
         p_ma_local_flag,
         p_manufacturer_aid,
         p_manufacturer_name,
         p_max_order_quantity,
         p_media,
         p_media_container,
         p_min_order_quantity,
         p_mms_product_id,
         p_mms_recurrent,
         p_mobile_product_flag,
         p_normal,
         p_number,
         p_number_content_units,
         p_occasions,
         p_offer_external_link_flag,
         p_offering_id,
         p_offline_date,
         p_online_date,
         p_order,
         p_order_quantity_interval,
         p_others,
         p_personal_details,
         p_picture,
         p_previous_base_product,
         p_price_quantity,
         p_product_cost,
         p_product_height,
         p_product_length,
         p_product_messages,
         p_product_order_limit,
         p_product_tag,
         p_product_width,
         p_raw_asset,
         p_region_id,
         p_rev_category_id,
         p_searchable,
         p_sequence_id,
         p_simple_asset,
         p_spend_category_id,
         p_start_line_number,
         p_state,
         p_supplier_alternative_aid,
         p_swatch_colour,
         p_thumb_nail,
         p_thumb_nails,
         p_training_session,
         p_type_descriptor,
         p_variant_type,
         p_weight,
         prop_ts,
         type_pk_string,
         unit_pk,
         p_hybris_products_id,
         dv_load_date_time,
         dv_load_end_date_time,
         dv_batch_id,
         getdate(),
         suser_sname()
    from #insert
commit tran

--force replication
set @max_dv_batch_id = (select isnull(max(dv_batch_id),-2) from d_hybris_products)
--Done!
end
