CREATE PROC [dbo].[proc_d_crmcloudsync_lead] @current_dv_batch_id [bigint] AS
begin

set nocount on
set xact_abort on

--Start!
-- Get the @max_dv_batch_id from dimension/fact.  Use -2 if there aren't any records.
declare @max_dv_batch_id bigint = (select isnull(max(dv_batch_id),-2) from d_crmcloudsync_lead)

-- Find the PIT records with dv_batch_id > @max_dv_batch_id
-- and find the PIT records with dv_batch_id = @current_dv_batch_id since those need to be deleted in case of a retry
if object_id('tempdb..#p_crmcloudsync_lead_insert') is not null drop table #p_crmcloudsync_lead_insert
create table dbo.#p_crmcloudsync_lead_insert with(distribution=hash(bk_hash), location=user_db) as
select p_crmcloudsync_lead.p_crmcloudsync_lead_id,
       p_crmcloudsync_lead.bk_hash
  from dbo.p_crmcloudsync_lead
 where p_crmcloudsync_lead.dv_load_end_date_time = convert(datetime,'9999.12.31',102)
   and (p_crmcloudsync_lead.dv_batch_id > @max_dv_batch_id
        or p_crmcloudsync_lead.dv_batch_id = @current_dv_batch_id)

-- calculate all values of the records to be inserted to make the actual update go as fast as possible
if object_id('tempdb..#insert') is not null drop table #insert
create table dbo.#insert with(distribution=hash(bk_hash), location=user_db) as
select p_crmcloudsync_lead.bk_hash,
       p_crmcloudsync_lead.bk_hash dim_crm_lead_key,
       h_crmcloudsync_lead.lead_id lead_id,
       isnull(s_crmcloudsync_lead.address_1_address_type_code,'') address_1_address_type_code,
       isnull(s_crmcloudsync_lead.address_1_address_type_code_name,'') address_1_address_type_code_name,
       isnull(s_crmcloudsync_lead.address_1_city,'') address_1_city,
       isnull(s_crmcloudsync_lead.address_1_composite,'') address_1_composite,
       isnull(s_crmcloudsync_lead.address_1_country,'') address_1_country,
       s_crmcloudsync_lead.address_1_latitude address_1_latitude,
       isnull(s_crmcloudsync_lead.address_1_line_1,'') address_1_line_1,
       s_crmcloudsync_lead.address_1_longitude address_1_longitude,
       s_crmcloudsync_lead.address1_postal_code address_1_postal_code,
       isnull(s_crmcloudsync_lead.address_1_state_or_province,'') address_1_state_or_province,
       s_crmcloudsync_lead.address_1_telephone_1 address_1_telephone_1,
       s_crmcloudsync_lead.address_1_telephone_2 address_1_telephone_2,
       isnull(s_crmcloudsync_lead.campaign_id_name,'') campaign_id_name,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash 
           when l_crmcloudsync_lead.created_by is null then '-998'
        else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.created_by as varchar(36)),'z#@$k%&P'))),2) end  created_by_dim_crm_system_user_key,
       isnull(s_crmcloudsync_lead.created_by_name,'') created_by_name,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.created_on is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.created_on, 112)    end created_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.created_on is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.created_on,114), 1, 5),':','') end created_dim_time_key,
       s_crmcloudsync_lead.created_on created_on,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash 
           when l_crmcloudsync_lead.created_on_behalf_by is null then '-998'
        else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.created_on_behalf_by as varchar(36)),'z#@$k%&P'))),2)  end  created_on_behalf_by_dim_crm_system_user_key,
       isnull(s_crmcloudsync_lead.created_on_behalf_by_name,'') created_on_behalf_by_name,
       isnull(s_crmcloudsync_lead.customer_id_name,'') customer_id_name,
       s_crmcloudsync_lead.customer_id_type customer_id_type,
       isnull(s_crmcloudsync_lead.customer_id_yomi_name,'') customer_id_yomi_name,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash      when l_crmcloudsync_lead.ltf_mms_club_id is null then '-998'      else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(l_crmcloudsync_lead.ltf_mms_club_id as int) as varchar(500)),'z#@$k%&P'))),2) end dim_club_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.address1_address_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.address1_address_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_address_1_address_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.parent_contact_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.parent_contact_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_contact_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash      
           when l_crmcloudsync_lead.customer_id is null then '-998'      
        else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.customer_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_customer_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.campaign_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.campaign_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_ltf_campaign_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash       when l_crmcloudsync_lead.ltf_club_id is null then '-998'      else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_club_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_ltf_club_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_employer_id is null then '-998'
        when isnumeric(l_crmcloudsync_lead.ltf_employer_id) = 0  then '-999'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_employer_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_ltf_employer_key ,
         case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_primary_lead is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_primary_lead as varchar(36)),'z#@$k%&P'))),2) end dim_crm_ltf_primary_lead_key,
         case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_visitor_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_visitor_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_ltf_visitor_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.owner_id is null then '-998'
            else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.owner_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_owner_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.parent_account_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.parent_account_id as varchar(36)),'z#@$k%&P'))),2) end dim_crm_parent_account_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash    
         when l_crmcloudsync_lead.parent_contact_id is null then '-998'   
        else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.parent_contact_id as varchar(36)),'z#@$k%&P'))),2)   end dim_crm_parent_contact_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_member_id is null then '-998'
            else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(l_crmcloudsync_lead.ltf_member_id as int) as varchar(500)),'z#@$k%&P'))),2) end dim_mms_member_key,
       isnull(s_crmcloudsync_lead.do_not_send_marketing_material_name,'') do_not_send_marketing_material_name,
       isnull(s_crmcloudsync_lead.email_address_1,'') email_address_1,
       isnull(s_crmcloudsync_lead.email_address_2,'') email_address_2,
       isnull(s_crmcloudsync_lead.first_name,'') first_name,
       isnull(s_crmcloudsync_lead.full_name,'') full_name,
       isnull(s_crmcloudsync_lead.insert_user,'') insert_user,
       s_crmcloudsync_lead.inserted_date_time inserted_date_time,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.inserted_date_time is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.inserted_date_time, 112)    end inserted_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.inserted_date_time is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.inserted_date_time,114), 1, 5),':','') end inserted_dim_time_key,
       isnull(s_crmcloudsync_lead.last_name,'') last_name,
       s_crmcloudsync_lead.ltf_actual_appointment_scheduled ltf_actual_appointment_scheduled,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_actual_appointment_scheduled is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_actual_appointment_scheduled, 112)    end ltf_actual_appointment_scheduled_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_actual_appointment_scheduled is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_actual_appointment_scheduled,114), 1, 5),':','') end ltf_actual_appointment_scheduled_dim_time_key,
       s_crmcloudsync_lead.ltf_actual_first_response ltf_actual_first_response,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_actual_first_response is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_actual_first_response, 112)    end ltf_actual_first_response_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_actual_first_response is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_actual_first_response,114), 1, 5),':','') end ltf_actual_first_response_dim_time_key,
       s_crmcloudsync_lead.ltf_actual_initial_contact ltf_actual_initial_contact,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_actual_initial_contact is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_actual_initial_contact, 112)    end ltf_actual_initial_contact_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_actual_initial_contact is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_actual_initial_contact,114), 1, 5),':','') end ltf_actual_initial_contact_dim_time_key,
       s_crmcloudsync_lead.ltf_appointment_showed ltf_appointment_showed,
       case when s_crmcloudsync_lead.ltf_appointment_showed = 1 then 'Y' else 'N' end ltf_appointment_showed_flag,
       isnull(s_crmcloudsync_lead.ltf_appointment_showed_name,'') ltf_appointment_showed_name,
       s_crmcloudsync_lead.ltf_assigned_to_club_date ltf_assigned_to_club_date,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_assigned_to_club_date is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_assigned_to_club_date, 112)    end ltf_assigned_to_club_date_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_assigned_to_club_date is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_assigned_to_club_date,114), 1, 5),':','') end ltf_assigned_to_club_date_dim_time_key,
       s_crmcloudsync_lead.ltf_best_time_to_contact ltf_best_time_to_contact,
       isnull(s_crmcloudsync_lead.ltf_best_time_to_contact_name,'') ltf_best_time_to_contact_name,
       s_crmcloudsync_lead.ltf_birth_date ltf_birth_date,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_birth_date is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_birth_date, 112)    end ltf_birth_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_birth_date is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_birth_date,114), 1, 5),':','') end ltf_birth_dim_time_key,
       s_crmcloudsync_lead.ltf_birth_year ltf_birth_year,
       l_crmcloudsync_lead.ltf_business_unit ltf_business_unit,
       isnull(s_crmcloudsync_lead.ltf_business_unit_name,'') ltf_business_unit_name,
       s_crmcloudsync_lead.ltf_channel ltf_channel,
       s_crmcloudsync_lead.ltf_channel_name ltf_channel_name,
       isnull(s_crmcloudsync_lead.ltf_club_id_name,'') ltf_club_id_name,
       s_crmcloudsync_lead.ltf_communication_consent ltf_communication_consent,
       isnull(s_crmcloudsync_lead.ltf_communication_consent_name,'') ltf_communication_consent_name,
       s_crmcloudsync_lead.ltf_consent_date_time ltf_consent_date_time,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_consent_date_time is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_consent_date_time, 112)    end ltf_consent_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_consent_date_time is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_consent_date_time,114), 1, 5),':','') end ltf_consent_dim_time_key,
       s_crmcloudsync_lead.ltf_consent_ip_address ltf_consent_ip_address,
       isnull(s_crmcloudsync_lead.ltf_consent_text,'') ltf_consent_text,
       s_crmcloudsync_lead.ltf_current_member ltf_current_member,
       case when s_crmcloudsync_lead.ltf_current_member = 1 then 'Y' else 'N' end ltf_current_member_flag,
       isnull(s_crmcloudsync_lead.ltf_current_member_name,'') ltf_current_member_name,
       isnull(s_crmcloudsync_lead.ltf_device,'') ltf_device,
       s_crmcloudsync_lead.ltf_dnc_dne_update_triggered_by ltf_dnc_dne_update_triggered_by,
       isnull(s_crmcloudsync_lead.ltf_dnc_dne_update_triggered_by_name,'') ltf_dnc_dne_update_triggered_by_name,
       s_crmcloudsync_lead.ltf_dnc_override ltf_dnc_override,
       case when s_crmcloudsync_lead.ltf_dnc_override = 1 then 'Y' else 'N' end ltf_dnc_override_flag,
       isnull(s_crmcloudsync_lead.ltf_dnc_override_name,'') ltf_dnc_override_name,
       s_crmcloudsync_lead.ltf_dnc_temporary_release_expiration ltf_dnc_temporary_release_expiration,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_dnc_temporary_release_expiration is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_dnc_temporary_release_expiration, 112)    end ltf_dnc_temporary_release_expiration_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_dnc_temporary_release_expiration is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_dnc_temporary_release_expiration,114), 1, 5),':','') end ltf_dnc_temporary_release_expiration_dim_time_key,
       s_crmcloudsync_lead.ltf_dnd_override_expiration ltf_dnd_override_expiration,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_dnd_override_expiration is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_dnd_override_expiration, 112)    end ltf_dnd_override_expiration_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_dnd_override_expiration is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_dnd_override_expiration,114), 1, 5),':','') end ltf_dnd_override_expiration_dim_time_key,
       s_crmcloudsync_lead.ltf_do_not_email_address_1 ltf_do_not_email_address_1,
       case when s_crmcloudsync_lead.ltf_do_not_email_address_1 = 1 then 'Y' else 'N' end ltf_do_not_email_address_1_flag,
       isnull(s_crmcloudsync_lead.ltf_do_not_email_address_1_name,'') ltf_do_not_email_address_1_name,
       s_crmcloudsync_lead.ltf_do_not_email_address_2 ltf_do_not_email_address_2,
       case when s_crmcloudsync_lead.ltf_do_not_email_address_2 = 1 then 'Y' else 'N' end ltf_do_not_email_address_2_flag,
       isnull(s_crmcloudsync_lead.ltf_do_not_email_address_2_name,'') ltf_do_not_email_address_2_name,
       s_crmcloudsync_lead.ltf_do_not_phone_mobile_phone ltf_do_not_phone_mobile_phone,
       case when s_crmcloudsync_lead.ltf_do_not_phone_mobile_phone = 1 then 'Y' else 'N' end ltf_do_not_phone_mobile_phone_flag,
       isnull(s_crmcloudsync_lead.ltf_do_not_phone_mobile_phone_name,'') ltf_do_not_phone_mobile_phone_name,
       s_crmcloudsync_lead.ltf_do_not_phone_telephone_1 ltf_do_not_phone_telephone_1,
       case when s_crmcloudsync_lead.ltf_do_not_phone_telephone_1 = 1 then 'Y' else 'N' end ltf_do_not_phone_telephone_1_flag,
       isnull(s_crmcloudsync_lead.ltf_do_not_phone_telephone_1_name,'') ltf_do_not_phone_telephone_1_name,
       s_crmcloudsync_lead.ltf_do_not_phone_telephone_2 ltf_do_not_phone_telephone_2,
       case when s_crmcloudsync_lead.ltf_do_not_phone_telephone_2 = 1 then 'Y' else 'N' end ltf_do_not_phone_telephone_2_flag,
       isnull(s_crmcloudsync_lead.ltf_do_not_phone_telephone_2_name,'') ltf_do_not_phone_telephone_2_name,
       s_crmcloudsync_lead.ltf_duplicate_lead_count ltf_duplicate_lead_count,
       s_crmcloudsync_lead.ltf_duplicate_override ltf_duplicate_override,
       case when s_crmcloudsync_lead.ltf_duplicate_override = 1 then 'Y' else 'N' end ltf_duplicate_override_flag,
       isnull(s_crmcloudsync_lead.ltf_duplicate_override_name,'') ltf_duplicate_override_name,
       isnull(s_crmcloudsync_lead.ltf_email_address_1_umsk,'') ltf_email_address_1_umsk,
       isnull(s_crmcloudsync_lead.ltf_email_address_2_umsk,'') ltf_email_address_2_umsk,
       s_crmcloudsync_lead.ltf_email_template ltf_email_template,
       s_crmcloudsync_lead.ltf_employee_number ltf_employee_number,
       isnull(s_crmcloudsync_lead.ltf_employer,'') ltf_employer,
       isnull(s_crmcloudsync_lead.ltf_employer_id_name,'') ltf_employer_id_name,
       isnull(s_crmcloudsync_lead.ltf_employer_id_yomi_name,'') ltf_employer_id_yomi_name,
       s_crmcloudsync_lead.ltf_exact_target_email_sent ltf_exact_target_email_sent,
       case when s_crmcloudsync_lead.ltf_exact_target_email_sent = 1 then 'Y' else 'N' end ltf_exact_target_email_sent_flag,
       isnull(s_crmcloudsync_lead.ltf_exact_target_email_sent_name,'') ltf_exact_target_email_sent_name,
       s_crmcloudsync_lead.ltf_exclude_from_follow_up ltf_exclude_from_follow_up,
       case when s_crmcloudsync_lead.ltf_exclude_from_follow_up = 1 then 'Y' else 'N' end ltf_exclude_from_follow_up_flag,
       isnull(s_crmcloudsync_lead.ltf_exclude_from_follow_up_name,'') ltf_exclude_from_follow_up_name,
       s_crmcloudsync_lead.ltf_first_response_by ltf_first_response_by,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_first_response_by is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_first_response_by, 112)    end ltf_first_response_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_first_response_by is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_first_response_by,114), 1, 5),':','') end ltf_first_response_dim_time_key,
       s_crmcloudsync_lead.ltf_first_response_sent ltf_first_response_sent,
       isnull(s_crmcloudsync_lead.ltf_first_response_sent_name,'') ltf_first_response_sent_name,
       s_crmcloudsync_lead.ltf_first_response_status ltf_first_response_status,
       isnull(s_crmcloudsync_lead.ltf_first_response_status_name,'') ltf_first_response_status_name,
       isnull(s_crmcloudsync_lead.ltf_gcl_id,'') ltf_gcl_id,
       s_crmcloudsync_lead.ltf_gender_code ltf_gender_code,
       isnull(s_crmcloudsync_lead.ltf_gender_code_name,'') ltf_gender_code_name,
       s_crmcloudsync_lead.ltf_group ltf_group,
       isnull(s_crmcloudsync_lead.ltf_group_name,'') ltf_group_name,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_guest_to_lead_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_guest_to_lead_id as varchar(36)),'z#@$k%&P'))),2) end ltf_guest_to_lead_dim_crm_activity_key,
       isnull(s_crmcloudsync_lead.ltf_guest_to_lead_id_name,'') ltf_guest_to_lead_id_name,
       isnull(s_crmcloudsync_lead.ltf_ims_join_link,'') ltf_ims_join_link,
       s_crmcloudsync_lead.ltf_initial_contact_by ltf_initial_contact_by,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_initial_contact_by is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_initial_contact_by, 112)    end ltf_initial_contact_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_initial_contact_by is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_initial_contact_by,114), 1, 5),':','') end ltf_initial_contact_dim_time_key,
       s_crmcloudsync_lead.ltf_initial_contact_made ltf_initial_contact_made,
       isnull(s_crmcloudsync_lead.ltf_initial_contact_made_name,'') ltf_initial_contact_made_name,
       s_crmcloudsync_lead.ltf_initial_contact_status ltf_initial_contact_status,
       isnull(s_crmcloudsync_lead.ltf_initial_contact_status_name,'') ltf_initial_contact_status_name,
       isnull(s_crmcloudsync_lead.ltf_initial_email_subject,'') ltf_initial_email_subject,
       isnull(s_crmcloudsync_lead.ltf_inquiry_type,'') ltf_inquiry_type,
       s_crmcloudsync_lead.ltf_inserted_by_system ltf_inserted_by_system,
       case when s_crmcloudsync_lead.ltf_inserted_by_system = 1 then 'Y' else 'N' end ltf_inserted_by_system_flag,
       isnull(s_crmcloudsync_lead.ltf_inserted_by_system_name,'') ltf_inserted_by_system_name,
       s_crmcloudsync_lead.ltf_is_ims_join ltf_is_ims_join,
       case when s_crmcloudsync_lead.ltf_is_ims_join = 1 then 'Y' else 'N' end ltf_is_ims_join_flag,
       s_crmcloudsync_lead.ltf_is_life_time_close_to ltf_is_life_time_close_to,
       isnull(s_crmcloudsync_lead.ltf_is_life_time_close_to_name,'') ltf_is_life_time_close_to_name,
       isnull(s_crmcloudsync_lead.ltf_keywords,'') ltf_keywords,
       isnull(s_crmcloudsync_lead.ltf_landing_page,'') ltf_landing_page,
       s_crmcloudsync_lead.ltf_last_activity ltf_last_activity,
       s_crmcloudsync_lead.ltf_last_activity_lead ltf_last_activity_lead,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_last_activity_lead is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_last_activity_lead, 112)    end ltf_last_activity_lead_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_last_activity_lead is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_last_activity_lead,114), 1, 5),':','') end ltf_last_activity_lead_dim_time_key,
       s_crmcloudsync_lead.ltf_last_submission_date ltf_last_submission_date,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_last_submission_date is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_last_submission_date, 112)    end ltf_last_submission_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_last_submission_date is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_last_submission_date,114), 1, 5),':','') end ltf_last_submission_dim_time_key,
       s_crmcloudsync_lead.ltf_lead_initial_load ltf_lead_initial_load,
       case when s_crmcloudsync_lead.ltf_lead_initial_load = 1 then 'Y' else 'N' end ltf_lead_initial_load_flag,
       isnull(s_crmcloudsync_lead.ltf_lead_initial_load_name,'') ltf_lead_initial_load_name,
       s_crmcloudsync_lead.ltf_lead_source ltf_lead_source,
       isnull(s_crmcloudsync_lead.ltf_lead_source_name,'') ltf_lead_source_name,
       s_crmcloudsync_lead.ltf_lead_type ltf_lead_type,
       isnull(s_crmcloudsync_lead.ltf_lead_type_name,'') ltf_lead_type_name,
       isnull(s_crmcloudsync_lead.ltf_legacy,'') ltf_legacy,
       s_crmcloudsync_lead.ltf_line_of_business ltf_line_of_business,
       s_crmcloudsync_lead.ltf_line_of_business_name ltf_line_of_business_name,
       s_crmcloudsync_lead.ltf_managed_until ltf_managed_until,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_managed_until is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_managed_until, 112)    end ltf_managed_until_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_managed_until is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_managed_until,114), 1, 5),':','') end ltf_managed_until_dim_time_key,
       isnull(ltf_membership_info_requested,'') ltf_membership_info_requested,
       s_crmcloudsync_lead.ltf_membership_level ltf_membership_level,
       isnull(s_crmcloudsync_lead.ltf_membership_level_name,'') ltf_membership_level_name,
       isnull(s_crmcloudsync_lead.ltf_mobile_phone_umsk,'') ltf_mobile_phone_umsk,
       s_crmcloudsync_lead.ltf_most_recent_casl ltf_most_recent_casl,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_most_recent_casl is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_most_recent_casl, 112)    end ltf_most_recent_casl_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_most_recent_casl is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_most_recent_casl,114), 1, 5),':','') end ltf_most_recent_casl_dim_time_key,
       isnull(s_crmcloudsync_lead.ltf_nugget,'') ltf_nugget,
       isnull(s_crmcloudsync_lead.ltf_operating_system,'') ltf_operating_system,
       l_crmcloudsync_lead.ltf_originating_chat ltf_originating_chat,
       isnull(s_crmcloudsync_lead.ltf_originating_chat_name,'') ltf_originating_chat_name,
        case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_originating_guest_visit is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_originating_guest_visit as varchar(36)),'z#@$k%&P'))),2) end ltf_originating_guest_visit_dim_crm_ltf_guest_visit_key,
       isnull(s_crmcloudsync_lead.ltf_originating_guest_visit_name,'') ltf_originating_guest_visit_name,
       s_crmcloudsync_lead.ltf_park ltf_park,
       isnull(s_crmcloudsync_lead.ltf_park_comments,'') ltf_park_comments,
       case when s_crmcloudsync_lead.ltf_park = 1 then 'Y' else 'N' end ltf_park_flag,
       isnull(s_crmcloudsync_lead.ltf_park_name,'') ltf_park_name,
       s_crmcloudsync_lead.ltf_park_reason ltf_park_reason,
       isnull(s_crmcloudsync_lead.ltf_park_reason_name,'') ltf_park_reason_name,
       s_crmcloudsync_lead.ltf_park_until ltf_park_until,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_park_until is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_park_until, 112)    end ltf_park_until_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_park_until is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_park_until,114), 1, 5),':','') end ltf_park_until_dim_time_key,
       isnull(s_crmcloudsync_lead.ltf_primary_goal,'') ltf_primary_goal,
       isnull(s_crmcloudsync_lead.ltf_primary_lead_name,'') ltf_primary_lead_name,
       isnull(s_crmcloudsync_lead.ltf_promo_code,'') ltf_promocode,
       s_crmcloudsync_lead.ltf_reactivation_reason ltf_reactivation_reason,
       isnull(s_crmcloudsync_lead.ltf_reactivation_reason_name,'') ltf_reactivation_reason_name,
         case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.ltf_referring_contact_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.ltf_referring_contact_id as varchar(36)),'z#@$k%&P'))),2) end ltf_referring_contact_dim_crm_contact_key,
       isnull(s_crmcloudsync_lead.ltf_referring_contact_id_name,'') ltf_referring_contact_id_name,
       s_crmcloudsync_lead.ltf_referring_domain ltf_referring_domain,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
            when l_crmcloudsync_lead.ltf_referring_member_id is null then '-998'
            when isnumeric(l_crmcloudsync_lead.ltf_referring_member_id) = '0' or l_crmcloudsync_lead.ltf_referring_member_id is  null then '-999'
            else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(l_crmcloudsync_lead.ltf_referring_member_id as bigint) as varchar(500)),'z#@$k%&P'))),2) end ltf_referring_member_dim_crm_member_key,
       isnull(s_crmcloudsync_lead.ltf_referring_page,'') ltf_referring_page,
       isnull(s_crmcloudsync_lead.ltf_registration_code,'') ltf_registration_code,
       isnull(s_crmcloudsync_lead.ltf_request_type,'') ltf_request_type,
       s_crmcloudsync_lead.ltf_schedule_appt_by ltf_schedule_appt_by,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_schedule_appt_by is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_schedule_appt_by, 112)    end ltf_schedule_appt_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_schedule_appt_by is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_schedule_appt_by,114), 1, 5),':','') end ltf_schedule_appt_dim_time_key,
       s_crmcloudsync_lead.ltf_schedule_appt_sent ltf_schedule_appt_sent,
       isnull(s_crmcloudsync_lead.ltf_schedule_appt_sent_name,'') ltf_schedule_appt_sent_name,
       s_crmcloudsync_lead.ltf_schedule_appt_status ltf_schedule_appt_status,
       isnull(s_crmcloudsync_lead.ltf_schedule_appt_status_name,'') ltf_schedule_appt_status_name,
       s_crmcloudsync_lead.ltf_suffix ltf_suffix,
       s_crmcloudsync_lead.ltf_transferred_to_club_on ltf_transferred_to_club_on,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.ltf_transferred_to_club_on is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.ltf_transferred_to_club_on, 112)    end ltf_transferred_to_club_on_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.ltf_transferred_to_club_on is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.ltf_transferred_to_club_on,114), 1, 5),':','') end ltf_transferred_to_club_on_dim_time_key,
       l_crmcloudsync_lead.ltf_udw_id ltf_udw_id,
       s_crmcloudsync_lead.ltf_under_eighteen ltf_under_eighteen,
       case when s_crmcloudsync_lead.ltf_under_eighteen = 1 then 'Y' else 'N' end ltf_under_eighteen_flag,
       isnull(s_crmcloudsync_lead.ltf_under_eighteen_name,'') ltf_under_eighteen_name,
       s_crmcloudsync_lead.ltf_update_contact ltf_update_contact,
       case when s_crmcloudsync_lead.ltf_update_contact = 1 then 'Y' else 'N' end ltf_update_contact_flag,
       isnull(s_crmcloudsync_lead.ltf_update_contact_name,'') ltf_update_contact_name,
       isnull(s_crmcloudsync_lead.ltf_utm_audience,'') ltf_utm_audience,
       isnull(s_crmcloudsync_lead.ltf_utm_campaign,'') ltf_utm_campaign,
       isnull(s_crmcloudsync_lead.ltf_utm_content,'') ltf_utm_content,
       isnull(s_crmcloudsync_lead.ltf_utm_image,'') ltf_utm_image,
       isnull(s_crmcloudsync_lead.ltf_utm_medium,'') ltf_utm_medium,
       isnull(s_crmcloudsync_lead.ltf_utm_source,'') ltf_utm_source,
       isnull(s_crmcloudsync_lead.ltf_utm_term,'') ltf_utm_term,
       s_crmcloudsync_lead.ltf_visit_count ltf_visit_count,
       s_crmcloudsync_lead.ltf_volatile_contact ltf_volatile_contact,
       case when s_crmcloudsync_lead.ltf_volatile_contact = 1 then 'Y' else 'N' end ltf_volatile_contact_flag,
       isnull(s_crmcloudsync_lead.ltf_volatile_contact_name,'') ltf_volatile_contact_name,
       isnull(s_crmcloudsync_lead.ltf_web_team_email,'') ltf_web_team_email,
       l_crmcloudsync_lead.ltf_web_team_id ltf_web_team_id,
       isnull(s_crmcloudsync_lead.ltf_web_team_id_name,'') ltf_web_team_id_name,
       s_crmcloudsync_lead.ltf_web_team_phone ltf_web_team_phone,
       s_crmcloudsync_lead.ltf_web_transfer_method ltf_web_transfer_method,
       isnull(s_crmcloudsync_lead.ltf_web_transfer_method_name,'') ltf_web_transfer_method_name,
       s_crmcloudsync_lead.merged merged,
       case when s_crmcloudsync_lead.merged = 1 then 'Y' else 'N' end merged_flag,
       isnull(s_crmcloudsync_lead.ltf_web_transfer_method_name,'') middle_name,
       s_crmcloudsync_lead.mobile_phone mobile_phone,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash 
           when l_crmcloudsync_lead.modified_by is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.modified_by as varchar(36)),'z#@$k%&P'))),2) end modified_by_dim_crm_system_user_key,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.modified_on is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.modified_on, 112)    end modified_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.modified_on is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.modified_on,114), 1, 5),':','') end modified_dim_time_key,
       s_crmcloudsync_lead.modified_on modified_on,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash 
           when l_crmcloudsync_lead.modified_on_behalf_by is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.modified_on_behalf_by as varchar(36)),'z#@$k%&P'))),2) end modified_on_behalf_by_dim_crm_system_user_key,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.overridden_created_on is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.overridden_created_on, 112)    end overridden_created_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.overridden_created_on is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.overridden_created_on,114), 1, 5),':','') end overridden_created_dim_time_key,
       s_crmcloudsync_lead.overridden_created_on overridden_created_on,
       l_crmcloudsync_lead.owner_id owner_id,
       isnull(s_crmcloudsync_lead.ltf_web_transfer_method_name,'') owner_id_name,
       s_crmcloudsync_lead.owner_id_type owner_id_type,
       l_crmcloudsync_lead.owning_business_unit owning_business_unit,
       l_crmcloudsync_lead.owning_team owning_team,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.owning_user is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.owning_user as varchar(36)),'z#@$k%&P'))),2) end owning_user_dim_crm_system_user_key,
       isnull(s_crmcloudsync_lead.parent_account_id_name,'') parent_account_id_name,
       l_crmcloudsync_lead.parent_contact_id parent_contact_id,
       s_crmcloudsync_lead.preferred_contact_method_code preferred_contact_method_code,
       isnull(s_crmcloudsync_lead.preferred_contact_method_code_name,'') preferred_contact_method_code_name,
       case when p_crmcloudsync_lead.bk_hash in ('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
           when l_crmcloudsync_lead.qualifying_opportunity_id is null then '-998'
           else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(l_crmcloudsync_lead.qualifying_opportunity_id as varchar(36)),'z#@$k%&P'))),2) end qualifying_opportunity_dim_crm_opportunity_key,
       isnull(s_crmcloudsync_lead.qualifying_opportunity_id_name,'') qualifying_opportunity_id_name,
       s_crmcloudsync_lead.salutation salutation,
       s_crmcloudsync_lead.state_code state_code,
       isnull(s_crmcloudsync_lead.state_code_name,'') state_code_name,
       s_crmcloudsync_lead.status_code status_code,
       isnull(s_crmcloudsync_lead.status_code_name,'') status_code_name,
       s_crmcloudsync_lead.telephone_1 telephone_1,
       s_crmcloudsync_lead.telephone_2 telephone_2,
       s_crmcloudsync_lead.Update_User update_user,
       s_crmcloudsync_lead.Updated_Date_Time updated_date_time,
       case when p_crmcloudsync_lead.bk_hash in('-997', '-998', '-999') then p_crmcloudsync_lead.bk_hash
          when s_crmcloudsync_lead.updated_date_time is null then '-998'
       else convert(varchar, s_crmcloudsync_lead.updated_date_time, 112)    end updated_dim_date_key,
       case when p_crmcloudsync_lead.bk_hash in ('-997','-998','-999') then p_crmcloudsync_lead.bk_hash
       when s_crmcloudsync_lead.updated_date_time is null then '-998'
       else '1' + replace(substring(convert(varchar,s_crmcloudsync_lead.updated_date_time,114), 1, 5),':','') end updated_dim_time_key,
       s_crmcloudsync_lead.utc_conversion_time_zone_code utc_conversion_time_zone_code,
       isnull(h_crmcloudsync_lead.dv_deleted,0) dv_deleted,
       p_crmcloudsync_lead.p_crmcloudsync_lead_id,
       p_crmcloudsync_lead.dv_batch_id,
       p_crmcloudsync_lead.dv_load_date_time,
       p_crmcloudsync_lead.dv_load_end_date_time
  from dbo.h_crmcloudsync_lead
  join dbo.p_crmcloudsync_lead
    on h_crmcloudsync_lead.bk_hash = p_crmcloudsync_lead.bk_hash
  join #p_crmcloudsync_lead_insert
    on p_crmcloudsync_lead.bk_hash = #p_crmcloudsync_lead_insert.bk_hash
   and p_crmcloudsync_lead.p_crmcloudsync_lead_id = #p_crmcloudsync_lead_insert.p_crmcloudsync_lead_id
  join dbo.l_crmcloudsync_lead
    on p_crmcloudsync_lead.bk_hash = l_crmcloudsync_lead.bk_hash
   and p_crmcloudsync_lead.l_crmcloudsync_lead_id = l_crmcloudsync_lead.l_crmcloudsync_lead_id
  join dbo.s_crmcloudsync_lead
    on p_crmcloudsync_lead.bk_hash = s_crmcloudsync_lead.bk_hash
   and p_crmcloudsync_lead.s_crmcloudsync_lead_id = s_crmcloudsync_lead.s_crmcloudsync_lead_id

-- do as a single transaction
--   delete records from the dimensional table where the business_key is in #p_*_insert temp table
--   insert records from all of the joins to the pit table and to #p_*_insert temp table
begin tran
  delete dbo.d_crmcloudsync_lead
   where d_crmcloudsync_lead.bk_hash in (select bk_hash from #p_crmcloudsync_lead_insert)

  insert dbo.d_crmcloudsync_lead(
             bk_hash,
             dim_crm_lead_key,
             lead_id,
             address_1_address_type_code,
             address_1_address_type_code_name,
             address_1_city,
             address_1_composite,
             address_1_country,
             address_1_latitude,
             address_1_line_1,
             address_1_longitude,
             address_1_postal_code,
             address_1_state_or_province,
             address_1_telephone_1,
             address_1_telephone_2,
             campaign_id_name,
             created_by_dim_crm_system_user_key,
             created_by_name,
             created_dim_date_key,
             created_dim_time_key,
             created_on,
             created_on_behalf_by_dim_crm_system_user_key,
             created_on_behalf_by_name,
             customer_id_name,
             customer_id_type,
             customer_id_yomi_name,
             dim_club_key,
             dim_crm_address_1_address_key,
             dim_crm_contact_key,
             dim_crm_customer_key,
             dim_crm_ltf_campaign_key,
             dim_crm_ltf_club_key,
             dim_crm_ltf_employer_key ,
             dim_crm_ltf_primary_lead_key,
             dim_crm_ltf_visitor_key,
             dim_crm_owner_key,
             dim_crm_parent_account_key,
             dim_crm_parent_contact_key,
             dim_mms_member_key,
             do_not_send_marketing_material_name,
             email_address_1,
             email_address_2,
             first_name,
             full_name,
             insert_user,
             inserted_date_time,
             inserted_dim_date_key,
             inserted_dim_time_key,
             last_name,
             ltf_actual_appointment_scheduled,
             ltf_actual_appointment_scheduled_dim_date_key,
             ltf_actual_appointment_scheduled_dim_time_key,
             ltf_actual_first_response,
             ltf_actual_first_response_dim_date_key,
             ltf_actual_first_response_dim_time_key,
             ltf_actual_initial_contact,
             ltf_actual_initial_contact_dim_date_key,
             ltf_actual_initial_contact_dim_time_key,
             ltf_appointment_showed,
             ltf_appointment_showed_flag,
             ltf_appointment_showed_name,
             ltf_assigned_to_club_date,
             ltf_assigned_to_club_date_dim_date_key,
             ltf_assigned_to_club_date_dim_time_key,
             ltf_best_time_to_contact,
             ltf_best_time_to_contact_name,
             ltf_birth_date,
             ltf_birth_dim_date_key,
             ltf_birth_dim_time_key,
             ltf_birth_year,
             ltf_business_unit,
             ltf_business_unit_name,
             ltf_channel,
             ltf_channel_name,
             ltf_club_id_name,
             ltf_communication_consent,
             ltf_communication_consent_name,
             ltf_consent_date_time,
             ltf_consent_dim_date_key,
             ltf_consent_dim_time_key,
             ltf_consent_ip_address,
             ltf_consent_text,
             ltf_current_member,
             ltf_current_member_flag,
             ltf_current_member_name,
             ltf_device,
             ltf_dnc_dne_update_triggered_by,
             ltf_dnc_dne_update_triggered_by_name,
             ltf_dnc_override,
             ltf_dnc_override_flag,
             ltf_dnc_override_name,
             ltf_dnc_temporary_release_expiration,
             ltf_dnc_temporary_release_expiration_dim_date_key,
             ltf_dnc_temporary_release_expiration_dim_time_key,
             ltf_dnd_override_expiration,
             ltf_dnd_override_expiration_dim_date_key,
             ltf_dnd_override_expiration_dim_time_key,
             ltf_do_not_email_address_1,
             ltf_do_not_email_address_1_flag,
             ltf_do_not_email_address_1_name,
             ltf_do_not_email_address_2,
             ltf_do_not_email_address_2_flag,
             ltf_do_not_email_address_2_name,
             ltf_do_not_phone_mobile_phone,
             ltf_do_not_phone_mobile_phone_flag,
             ltf_do_not_phone_mobile_phone_name,
             ltf_do_not_phone_telephone_1,
             ltf_do_not_phone_telephone_1_flag,
             ltf_do_not_phone_telephone_1_name,
             ltf_do_not_phone_telephone_2,
             ltf_do_not_phone_telephone_2_flag,
             ltf_do_not_phone_telephone_2_name,
             ltf_duplicate_lead_count,
             ltf_duplicate_override,
             ltf_duplicate_override_flag,
             ltf_duplicate_override_name,
             ltf_email_address_1_umsk,
             ltf_email_address_2_umsk,
             ltf_email_template,
             ltf_employee_number,
             ltf_employer,
             ltf_employer_id_name,
             ltf_employer_id_yomi_name,
             ltf_exact_target_email_sent,
             ltf_exact_target_email_sent_flag,
             ltf_exact_target_email_sent_name,
             ltf_exclude_from_follow_up,
             ltf_exclude_from_follow_up_flag,
             ltf_exclude_from_follow_up_name,
             ltf_first_response_by,
             ltf_first_response_dim_date_key,
             ltf_first_response_dim_time_key,
             ltf_first_response_sent,
             ltf_first_response_sent_name,
             ltf_first_response_status,
             ltf_first_response_status_name,
             ltf_gcl_id,
             ltf_gender_code,
             ltf_gender_code_name,
             ltf_group,
             ltf_group_name,
             ltf_guest_to_lead_dim_crm_activity_key,
             ltf_guest_to_lead_id_name,
             ltf_ims_join_link,
             ltf_initial_contact_by,
             ltf_initial_contact_dim_date_key,
             ltf_initial_contact_dim_time_key,
             ltf_initial_contact_made,
             ltf_initial_contact_made_name,
             ltf_initial_contact_status,
             ltf_initial_contact_status_name,
             ltf_initial_email_subject,
             ltf_inquiry_type,
             ltf_inserted_by_system,
             ltf_inserted_by_system_flag,
             ltf_inserted_by_system_name,
             ltf_is_ims_join,
             ltf_is_ims_join_flag,
             ltf_is_life_time_close_to,
             ltf_is_life_time_close_to_name,
             ltf_keywords,
             ltf_landing_page,
             ltf_last_activity,
             ltf_last_activity_lead,
             ltf_last_activity_lead_dim_date_key,
             ltf_last_activity_lead_dim_time_key,
             ltf_last_submission_date,
             ltf_last_submission_dim_date_key,
             ltf_last_submission_dim_time_key,
             ltf_lead_initial_load,
             ltf_lead_initial_load_flag,
             ltf_lead_initial_load_name,
             ltf_lead_source,
             ltf_lead_source_name,
             ltf_lead_type,
             ltf_lead_type_name,
             ltf_legacy,
             ltf_line_of_business,
             ltf_line_of_business_name,
             ltf_managed_until,
             ltf_managed_until_dim_date_key,
             ltf_managed_until_dim_time_key,
             ltf_membership_info_requested,
             ltf_membership_level,
             ltf_membership_level_name,
             ltf_mobile_phone_umsk,
             ltf_most_recent_casl,
             ltf_most_recent_casl_dim_date_key,
             ltf_most_recent_casl_dim_time_key,
             ltf_nugget,
             ltf_operating_system,
             ltf_originating_chat,
             ltf_originating_chat_name,
             ltf_originating_guest_visit_dim_crm_ltf_guest_visit_key,
             ltf_originating_guest_visit_name,
             ltf_park,
             ltf_park_comments,
             ltf_park_flag,
             ltf_park_name,
             ltf_park_reason,
             ltf_park_reason_name,
             ltf_park_until,
             ltf_park_until_dim_date_key,
             ltf_park_until_dim_time_key,
             ltf_primary_goal,
             ltf_primary_lead_name,
             ltf_promocode,
             ltf_reactivation_reason,
             ltf_reactivation_reason_name,
             ltf_referring_contact_dim_crm_contact_key,
             ltf_referring_contact_id_name,
             ltf_referring_domain,
             ltf_referring_member_dim_crm_member_key,
             ltf_referring_page,
             ltf_registration_code,
             ltf_request_type,
             ltf_schedule_appt_by,
             ltf_schedule_appt_dim_date_key,
             ltf_schedule_appt_dim_time_key,
             ltf_schedule_appt_sent,
             ltf_schedule_appt_sent_name,
             ltf_schedule_appt_status,
             ltf_schedule_appt_status_name,
             ltf_suffix,
             ltf_transferred_to_club_on,
             ltf_transferred_to_club_on_dim_date_key,
             ltf_transferred_to_club_on_dim_time_key,
             ltf_udw_id,
             ltf_under_eighteen,
             ltf_under_eighteen_flag,
             ltf_under_eighteen_name,
             ltf_update_contact,
             ltf_update_contact_flag,
             ltf_update_contact_name,
             ltf_utm_audience,
             ltf_utm_campaign,
             ltf_utm_content,
             ltf_utm_image,
             ltf_utm_medium,
             ltf_utm_source,
             ltf_utm_term,
             ltf_visit_count,
             ltf_volatile_contact,
             ltf_volatile_contact_flag,
             ltf_volatile_contact_name,
             ltf_web_team_email,
             ltf_web_team_id,
             ltf_web_team_id_name,
             ltf_web_team_phone,
             ltf_web_transfer_method,
             ltf_web_transfer_method_name,
             merged,
             merged_flag,
             middle_name,
             mobile_phone,
             modified_by_dim_crm_system_user_key,
             modified_dim_date_key,
             modified_dim_time_key,
             modified_on,
             modified_on_behalf_by_dim_crm_system_user_key,
             overridden_created_dim_date_key,
             overridden_created_dim_time_key,
             overridden_created_on,
             owner_id,
             owner_id_name,
             owner_id_type,
             owning_business_unit,
             owning_team,
             owning_user_dim_crm_system_user_key,
             parent_account_id_name,
             parent_contact_id,
             preferred_contact_method_code,
             preferred_contact_method_code_name,
             qualifying_opportunity_dim_crm_opportunity_key,
             qualifying_opportunity_id_name,
             salutation,
             state_code,
             state_code_name,
             status_code,
             status_code_name,
             telephone_1,
             telephone_2,
             update_user,
             updated_date_time,
             updated_dim_date_key,
             updated_dim_time_key,
             utc_conversion_time_zone_code,
             deleted_flag,
             p_crmcloudsync_lead_id,
             dv_load_date_time,
             dv_load_end_date_time,
             dv_batch_id,
             dv_inserted_date_time,
             dv_insert_user)
  select bk_hash,
         dim_crm_lead_key,
         lead_id,
         address_1_address_type_code,
         address_1_address_type_code_name,
         address_1_city,
         address_1_composite,
         address_1_country,
         address_1_latitude,
         address_1_line_1,
         address_1_longitude,
         address_1_postal_code,
         address_1_state_or_province,
         address_1_telephone_1,
         address_1_telephone_2,
         campaign_id_name,
         created_by_dim_crm_system_user_key,
         created_by_name,
         created_dim_date_key,
         created_dim_time_key,
         created_on,
         created_on_behalf_by_dim_crm_system_user_key,
         created_on_behalf_by_name,
         customer_id_name,
         customer_id_type,
         customer_id_yomi_name,
         dim_club_key,
         dim_crm_address_1_address_key,
         dim_crm_contact_key,
         dim_crm_customer_key,
         dim_crm_ltf_campaign_key,
         dim_crm_ltf_club_key,
         dim_crm_ltf_employer_key ,
         dim_crm_ltf_primary_lead_key,
         dim_crm_ltf_visitor_key,
         dim_crm_owner_key,
         dim_crm_parent_account_key,
         dim_crm_parent_contact_key,
         dim_mms_member_key,
         do_not_send_marketing_material_name,
         email_address_1,
         email_address_2,
         first_name,
         full_name,
         insert_user,
         inserted_date_time,
         inserted_dim_date_key,
         inserted_dim_time_key,
         last_name,
         ltf_actual_appointment_scheduled,
         ltf_actual_appointment_scheduled_dim_date_key,
         ltf_actual_appointment_scheduled_dim_time_key,
         ltf_actual_first_response,
         ltf_actual_first_response_dim_date_key,
         ltf_actual_first_response_dim_time_key,
         ltf_actual_initial_contact,
         ltf_actual_initial_contact_dim_date_key,
         ltf_actual_initial_contact_dim_time_key,
         ltf_appointment_showed,
         ltf_appointment_showed_flag,
         ltf_appointment_showed_name,
         ltf_assigned_to_club_date,
         ltf_assigned_to_club_date_dim_date_key,
         ltf_assigned_to_club_date_dim_time_key,
         ltf_best_time_to_contact,
         ltf_best_time_to_contact_name,
         ltf_birth_date,
         ltf_birth_dim_date_key,
         ltf_birth_dim_time_key,
         ltf_birth_year,
         ltf_business_unit,
         ltf_business_unit_name,
         ltf_channel,
         ltf_channel_name,
         ltf_club_id_name,
         ltf_communication_consent,
         ltf_communication_consent_name,
         ltf_consent_date_time,
         ltf_consent_dim_date_key,
         ltf_consent_dim_time_key,
         ltf_consent_ip_address,
         ltf_consent_text,
         ltf_current_member,
         ltf_current_member_flag,
         ltf_current_member_name,
         ltf_device,
         ltf_dnc_dne_update_triggered_by,
         ltf_dnc_dne_update_triggered_by_name,
         ltf_dnc_override,
         ltf_dnc_override_flag,
         ltf_dnc_override_name,
         ltf_dnc_temporary_release_expiration,
         ltf_dnc_temporary_release_expiration_dim_date_key,
         ltf_dnc_temporary_release_expiration_dim_time_key,
         ltf_dnd_override_expiration,
         ltf_dnd_override_expiration_dim_date_key,
         ltf_dnd_override_expiration_dim_time_key,
         ltf_do_not_email_address_1,
         ltf_do_not_email_address_1_flag,
         ltf_do_not_email_address_1_name,
         ltf_do_not_email_address_2,
         ltf_do_not_email_address_2_flag,
         ltf_do_not_email_address_2_name,
         ltf_do_not_phone_mobile_phone,
         ltf_do_not_phone_mobile_phone_flag,
         ltf_do_not_phone_mobile_phone_name,
         ltf_do_not_phone_telephone_1,
         ltf_do_not_phone_telephone_1_flag,
         ltf_do_not_phone_telephone_1_name,
         ltf_do_not_phone_telephone_2,
         ltf_do_not_phone_telephone_2_flag,
         ltf_do_not_phone_telephone_2_name,
         ltf_duplicate_lead_count,
         ltf_duplicate_override,
         ltf_duplicate_override_flag,
         ltf_duplicate_override_name,
         ltf_email_address_1_umsk,
         ltf_email_address_2_umsk,
         ltf_email_template,
         ltf_employee_number,
         ltf_employer,
         ltf_employer_id_name,
         ltf_employer_id_yomi_name,
         ltf_exact_target_email_sent,
         ltf_exact_target_email_sent_flag,
         ltf_exact_target_email_sent_name,
         ltf_exclude_from_follow_up,
         ltf_exclude_from_follow_up_flag,
         ltf_exclude_from_follow_up_name,
         ltf_first_response_by,
         ltf_first_response_dim_date_key,
         ltf_first_response_dim_time_key,
         ltf_first_response_sent,
         ltf_first_response_sent_name,
         ltf_first_response_status,
         ltf_first_response_status_name,
         ltf_gcl_id,
         ltf_gender_code,
         ltf_gender_code_name,
         ltf_group,
         ltf_group_name,
         ltf_guest_to_lead_dim_crm_activity_key,
         ltf_guest_to_lead_id_name,
         ltf_ims_join_link,
         ltf_initial_contact_by,
         ltf_initial_contact_dim_date_key,
         ltf_initial_contact_dim_time_key,
         ltf_initial_contact_made,
         ltf_initial_contact_made_name,
         ltf_initial_contact_status,
         ltf_initial_contact_status_name,
         ltf_initial_email_subject,
         ltf_inquiry_type,
         ltf_inserted_by_system,
         ltf_inserted_by_system_flag,
         ltf_inserted_by_system_name,
         ltf_is_ims_join,
         ltf_is_ims_join_flag,
         ltf_is_life_time_close_to,
         ltf_is_life_time_close_to_name,
         ltf_keywords,
         ltf_landing_page,
         ltf_last_activity,
         ltf_last_activity_lead,
         ltf_last_activity_lead_dim_date_key,
         ltf_last_activity_lead_dim_time_key,
         ltf_last_submission_date,
         ltf_last_submission_dim_date_key,
         ltf_last_submission_dim_time_key,
         ltf_lead_initial_load,
         ltf_lead_initial_load_flag,
         ltf_lead_initial_load_name,
         ltf_lead_source,
         ltf_lead_source_name,
         ltf_lead_type,
         ltf_lead_type_name,
         ltf_legacy,
         ltf_line_of_business,
         ltf_line_of_business_name,
         ltf_managed_until,
         ltf_managed_until_dim_date_key,
         ltf_managed_until_dim_time_key,
         ltf_membership_info_requested,
         ltf_membership_level,
         ltf_membership_level_name,
         ltf_mobile_phone_umsk,
         ltf_most_recent_casl,
         ltf_most_recent_casl_dim_date_key,
         ltf_most_recent_casl_dim_time_key,
         ltf_nugget,
         ltf_operating_system,
         ltf_originating_chat,
         ltf_originating_chat_name,
         ltf_originating_guest_visit_dim_crm_ltf_guest_visit_key,
         ltf_originating_guest_visit_name,
         ltf_park,
         ltf_park_comments,
         ltf_park_flag,
         ltf_park_name,
         ltf_park_reason,
         ltf_park_reason_name,
         ltf_park_until,
         ltf_park_until_dim_date_key,
         ltf_park_until_dim_time_key,
         ltf_primary_goal,
         ltf_primary_lead_name,
         ltf_promocode,
         ltf_reactivation_reason,
         ltf_reactivation_reason_name,
         ltf_referring_contact_dim_crm_contact_key,
         ltf_referring_contact_id_name,
         ltf_referring_domain,
         ltf_referring_member_dim_crm_member_key,
         ltf_referring_page,
         ltf_registration_code,
         ltf_request_type,
         ltf_schedule_appt_by,
         ltf_schedule_appt_dim_date_key,
         ltf_schedule_appt_dim_time_key,
         ltf_schedule_appt_sent,
         ltf_schedule_appt_sent_name,
         ltf_schedule_appt_status,
         ltf_schedule_appt_status_name,
         ltf_suffix,
         ltf_transferred_to_club_on,
         ltf_transferred_to_club_on_dim_date_key,
         ltf_transferred_to_club_on_dim_time_key,
         ltf_udw_id,
         ltf_under_eighteen,
         ltf_under_eighteen_flag,
         ltf_under_eighteen_name,
         ltf_update_contact,
         ltf_update_contact_flag,
         ltf_update_contact_name,
         ltf_utm_audience,
         ltf_utm_campaign,
         ltf_utm_content,
         ltf_utm_image,
         ltf_utm_medium,
         ltf_utm_source,
         ltf_utm_term,
         ltf_visit_count,
         ltf_volatile_contact,
         ltf_volatile_contact_flag,
         ltf_volatile_contact_name,
         ltf_web_team_email,
         ltf_web_team_id,
         ltf_web_team_id_name,
         ltf_web_team_phone,
         ltf_web_transfer_method,
         ltf_web_transfer_method_name,
         merged,
         merged_flag,
         middle_name,
         mobile_phone,
         modified_by_dim_crm_system_user_key,
         modified_dim_date_key,
         modified_dim_time_key,
         modified_on,
         modified_on_behalf_by_dim_crm_system_user_key,
         overridden_created_dim_date_key,
         overridden_created_dim_time_key,
         overridden_created_on,
         owner_id,
         owner_id_name,
         owner_id_type,
         owning_business_unit,
         owning_team,
         owning_user_dim_crm_system_user_key,
         parent_account_id_name,
         parent_contact_id,
         preferred_contact_method_code,
         preferred_contact_method_code_name,
         qualifying_opportunity_dim_crm_opportunity_key,
         qualifying_opportunity_id_name,
         salutation,
         state_code,
         state_code_name,
         status_code,
         status_code_name,
         telephone_1,
         telephone_2,
         update_user,
         updated_date_time,
         updated_dim_date_key,
         updated_dim_time_key,
         utc_conversion_time_zone_code,
         dv_deleted,
         p_crmcloudsync_lead_id,
         dv_load_date_time,
         dv_load_end_date_time,
         dv_batch_id,
         getdate(),
         suser_sname()
    from #insert
commit tran

--force replication
set @max_dv_batch_id = (select isnull(max(dv_batch_id),-2) from d_crmcloudsync_lead)
--Done!
end
