CREATE PROC [dbo].[proc_d_udwcloudsync_enterprise_club_data] @current_dv_batch_id [bigint] AS
begin

set nocount on
set xact_abort on

--Start!
-- Get the @max_dv_batch_id from dimension/fact.  Use -2 if there aren't any records.
declare @max_dv_batch_id bigint = (select isnull(max(dv_batch_id),-2) from d_udwcloudsync_enterprise_club_data)

-- Find the PIT records with dv_batch_id > @max_dv_batch_id
-- and find the PIT records with dv_batch_id = @current_dv_batch_id since those need to be deleted in case of a retry
if object_id('tempdb..#p_udwcloudsync_enterprise_club_data_insert') is not null drop table #p_udwcloudsync_enterprise_club_data_insert
create table dbo.#p_udwcloudsync_enterprise_club_data_insert with(distribution=hash(bk_hash), location=user_db) as
select p_udwcloudsync_enterprise_club_data.p_udwcloudsync_enterprise_club_data_id,
       p_udwcloudsync_enterprise_club_data.bk_hash
  from dbo.p_udwcloudsync_enterprise_club_data
 where p_udwcloudsync_enterprise_club_data.dv_load_end_date_time = convert(datetime,'9999.12.31',102)
   and (p_udwcloudsync_enterprise_club_data.dv_batch_id > @max_dv_batch_id
        or p_udwcloudsync_enterprise_club_data.dv_batch_id = @current_dv_batch_id)

-- calculate all values of the records to be inserted to make the actual update go as fast as possible
if object_id('tempdb..#insert') is not null drop table #insert
create table dbo.#insert with(distribution=hash(bk_hash), location=user_db) as
select p_udwcloudsync_enterprise_club_data.bk_hash,
       p_udwcloudsync_enterprise_club_data.enterprise_club_data_id enterprise_club_data_id,
       case when s_udwcloudsync_enterprise_club_data.amenity_conditioner='Yes' then 'Y'        else 'N' end amenity_conditioner_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_cotton_balls='Yes' then 'Y'        else 'N' end amenity_cotton_balls_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_deodorant='Yes' then 'Y'        else 'N' end amenity_deodorant_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_free_lockers_and_towels='Yes' then 'Y'        else 'N' end amenity_free_lockers_and_towels_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_hairspray='Yes' then 'Y'        else 'N' end amenity_hairspray_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_mouthwash='Yes' then 'Y'        else 'N' end amenity_mouthwash_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_plasma_big_screen_tvs='Yes' then 'Y'        else 'N' end amenity_plasma_big_screen_tvs_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_razors='Yes' then 'Y'        else 'N' end amenity_razors_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_shampoo='Yes' then 'Y'        else 'N' end amenity_shampoo_flag,
       case when s_udwcloudsync_enterprise_club_data.amenity_wireless_internet_access='Yes' then 'Y'        else 'N' end amenity_wireless_internet_access_flag,
       s_udwcloudsync_enterprise_club_data.app_created_by app_created_by,
       s_udwcloudsync_enterprise_club_data.app_modified_by app_modified_by,
       s_udwcloudsync_enterprise_club_data.club_hours club_hours,
       s_udwcloudsync_enterprise_club_data.club_level club_level,
       s_udwcloudsync_enterprise_club_data.compliance_asset_id compliance_asset_id,
       s_udwcloudsync_enterprise_club_data.content_type content_type,
       s_udwcloudsync_enterprise_club_data.created_by created_by,
       case when p_udwcloudsync_enterprise_club_data.bk_hash in ('-997', '-998', '-999')             then p_udwcloudsync_enterprise_club_data.bk_hash        when s_udwcloudsync_enterprise_club_data.created is null then '-998'    	 else convert(char(8), s_udwcloudsync_enterprise_club_data.created, 112)  end created_dim_date_key,
       case when p_udwcloudsync_enterprise_club_data.bk_hash in ('-997', '-998', '-999')          then p_udwcloudsync_enterprise_club_data.bk_hash             when l_udwcloudsync_enterprise_club_data.mms_club_id is null then '-998'        else convert(char(32),hashbytes('md5',('P%#&z$@k'+isnull(cast(cast(l_udwcloudsync_enterprise_club_data.mms_club_id as int) as varchar(500)),'z#@$k%&P'))),2)   end dim_club_key,
       case when s_udwcloudsync_enterprise_club_data.feature_advanced_training_studio='Yes' then 'Y'        else 'N' end feature_advanced_training_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_alpha_field='Yes' then 'Y'        else 'N' end feature_alpha_field_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_bar='Yes' then 'Y'        else 'N' end feature_bar_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_basketball_courts='Yes' then 'Y'        else 'N' end feature_basketball_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_boxing_gym='Yes' then 'Y'        else 'N' end feature_boxing_gym_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_business_center='Yes' then 'Y'        else 'N' end feature_business_center_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_cardio_equipment='Yes' then 'Y'        else 'N' end feature_cardio_equipment_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_child_center='Yes' then 'Y'        else 'N' end feature_child_center_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_connected_technology='Yes' then 'Y'        else 'N' end feature_connected_technology_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_deluge='Yes' then 'Y'        else 'N' end feature_deluge_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_fitness_studios='Yes' then 'Y'        else 'N' end feature_fitness_studios_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_free_weights_and_equipment='Yes' then 'Y'        else 'N' end feature_free_weights_and_equipment_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_functional_training_area='Yes' then 'Y'        else 'N' end feature_functional_training_area_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_hamam='Yes' then 'Y'        else 'N' end feature_hamam_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_cycle_studio='Yes' then 'Y'        else 'N' end feature_indoor_cycle_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_golf_center='Yes' then 'Y'        else 'N' end feature_indoor_golf_center_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_lap_pool='Yes' then 'Y'        else 'N' end feature_indoor_lap_pool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_leisure_pool='Yes' then 'Y'        else 'N' end feature_indoor_leisure_pool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_tennis_courts='Yes' then 'Y'        else 'N' end feature_indoor_tennis_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_turf_field='Yes' then 'Y'        else 'N' end feature_indoor_turf_field_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_water_slides='Yes' then 'Y'        else 'N' end feature_indoor_water_slides_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_indoor_whirlpool='Yes' then 'Y'        else 'N' end feature_indoor_whirlpool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_infant_room='Yes' then 'Y'        else 'N' end feature_infant_room_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_academy='Yes' then 'Y'        else 'N' end feature_kids_academy_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_gym='Yes' then 'Y'        else 'N' end feature_kids_gym_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_language_arts_studio='Yes' then 'Y'        else 'N' end feature_kids_language_arts_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_learning_lab='Yes' then 'Y'        else 'N' end feature_kids_learning_lab_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_media_room='Yes' then 'Y'        else 'N' end feature_kids_media_room_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_movement_studio='Yes' then 'Y'        else 'N' end feature_kids_movement_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_outdoor_play_area='Yes' then 'Y'        else 'N' end feature_kids_outdoor_play_area_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_kids_tumbling_studio='Yes' then 'Y'        else 'N' end feature_kids_tumbling_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_lazy_river='Yes' then 'Y'        else 'N' end feature_lazy_river_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_lifecafe='Yes' then 'Y'        else 'N' end feature_lifecafe_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_lifecafe_poolside_bistro='Yes' then 'Y'        else 'N' end feature_lifecafe_poolside_bistro_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_lifespa='Yes' then 'Y'        else 'N' end feature_lifespa_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_mixed_combats_arts_studio='Yes' then 'Y'        else 'N' end feature_mixed_combats_arts_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_fitness_trail='Yes' then 'Y'        else 'N' end feature_outdoor_fitness_trail_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_lap_pool='Yes' then 'Y'        else 'N' end feature_outdoor_lap_pool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_swimming_pool='Yes' then 'Y'        else 'N' end feature_outdoor_swimming_pool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_tennis_courts='Yes' then 'Y'        else 'N' end feature_outdoor_tennis_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_turf_field='Yes' then 'Y'        else 'N' end feature_outdoor_turf_field_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_water_slides='Yes' then 'Y'        else 'N' end feature_outdoor_water_slides_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_outdoor_whirlpool='Yes' then 'Y'        else 'N' end feature_outdoor_whirlpool_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_pickleball_court='Yes' then 'Y'        else 'N' end feature_pickleball_court_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_pilates_studio='Yes' then 'Y'        else 'N' end feature_pilates_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_play_maze='Yes' then 'Y'        else 'N' end feature_play_maze_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_pre_school='Yes' then 'Y'        else 'N' end feature_pre_school_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_proactive_care_clinic='Yes' then 'Y'        else 'N' end feature_proactive_care_clinic_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_racquetball_courts='Yes' then 'Y'        else 'N' end feature_racquetball_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_rare='Yes' then 'Y'        else 'N' end feature_rare_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_rehabilitation_and_chiropractic_clinic='Yes' then 'Y'        else 'N' end feature_rehabilitation_and_chiropractic_clinic_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_resistance_training_area='Yes' then 'Y'        else 'N' end feature_resistance_training_area_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_retail_store='Yes' then 'Y'        else 'N' end feature_retail_store_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_rock_wall='Yes' then 'Y'        else 'N' end feature_rock_wall_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_rooftop_patio='Yes' then 'Y'        else 'N' end feature_rooftop_patio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_sand_volleyball_court='Yes' then 'Y'        else 'N' end feature_sand_volleyball_court_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_saunas='Yes' then 'Y'        else 'N' end feature_saunas_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_splash_pad='Yes' then 'Y'        else 'N' end feature_splash_pad_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_squash_courts='Yes' then 'Y'        else 'N' end feature_squash_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_steam_rooms='Yes' then 'Y'        else 'N' end feature_steam_rooms_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_volleyball_courts='Yes' then 'Y'        else 'N' end feature_volleyball_courts_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_walking_running_track='Yes' then 'Y'        else 'N' end feature_walking_running_track_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_weight_machines='Yes' then 'Y'        else 'N' end feature_weight_machines_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_yoga_studio='Yes' then 'Y'        else 'N' end feature_yoga_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.feature_zero_depth_entry_pool='Yes' then 'Y'        else 'N' end feature_zero_depth_entry_pool_flag,
       s_udwcloudsync_enterprise_club_data.folder_child_count folder_child_count,
       s_udwcloudsync_enterprise_club_data.general_manager general_manager,
       s_udwcloudsync_enterprise_club_data.general_manager_email general_manager_email,
       s_udwcloudsync_enterprise_club_data.general_manager_phone general_manager_phone,
       case when p_udwcloudsync_enterprise_club_data.bk_hash in ('-997', '-998', '-999')              
       then p_udwcloudsync_enterprise_club_data.bk_hash         
       when s_udwcloudsync_enterprise_club_data.inserted_date_time is null then '-998'     
        else convert(char(8), s_udwcloudsync_enterprise_club_data.inserted_date_time, 112)  end inserted_dim_date_key,
       s_udwcloudsync_enterprise_club_data.item_child_count item_child_count,
       s_udwcloudsync_enterprise_club_data.item_type item_type,
       s_udwcloudsync_enterprise_club_data.label_applied label_applied,
       s_udwcloudsync_enterprise_club_data.label_applied_by label_applied_by,
       s_udwcloudsync_enterprise_club_data.label_setting label_setting,
       s_udwcloudsync_enterprise_club_data.labels labels,
       s_udwcloudsync_enterprise_club_data.member_services_manager member_services_manager,
       s_udwcloudsync_enterprise_club_data.member_services_manager_email member_services_manager_email,
       s_udwcloudsync_enterprise_club_data.member_services_manager_phone member_services_manager_phone,
       l_udwcloudsync_enterprise_club_data.mms_club_id mms_club_id,
       s_udwcloudsync_enterprise_club_data.modified_by modified_by,
       case when p_udwcloudsync_enterprise_club_data.bk_hash in ('-997', '-998', '-999')             then p_udwcloudsync_enterprise_club_data.bk_hash        when s_udwcloudsync_enterprise_club_data.modified is null then '-998'    	 else convert(char(8), s_udwcloudsync_enterprise_club_data.modified, 112)  end modified_dim_date_key,
       case when s_udwcloudsync_enterprise_club_data.oms='Yes' then 'Y'        else 'N' end oms_flag,
       case when p_udwcloudsync_enterprise_club_data.bk_hash in ('-997', '-998', '-999')             then p_udwcloudsync_enterprise_club_data.bk_hash        when s_udwcloudsync_enterprise_club_data.open_date is null then '-998'    	 else convert(char(8), s_udwcloudsync_enterprise_club_data.open_date, 112)  end open_dim_date_key,
       s_udwcloudsync_enterprise_club_data.path path,
       s_udwcloudsync_enterprise_club_data.phone phone,
       case when s_udwcloudsync_enterprise_club_data.program_badminton='Yes' then 'Y'        else 'N' end program_badminton_flag,
       case when s_udwcloudsync_enterprise_club_data.program_barre='Yes' then 'Y'        else 'N' end program_barre_flag,
       case when s_udwcloudsync_enterprise_club_data.program_basketball='Yes' then 'Y'        else 'N' end program_basketball_flag,
       case when s_udwcloudsync_enterprise_club_data.program_birthday_parties='Yes' then 'Y'        else 'N' end program_birthday_parties_flag,
       case when s_udwcloudsync_enterprise_club_data.program_boxing='Yes' then 'Y'        else 'N' end program_boxing_flag,
       case when s_udwcloudsync_enterprise_club_data.program_golf='Yes' then 'Y'        else 'N' end program_golf_flag,
       case when s_udwcloudsync_enterprise_club_data.program_handball='Yes' then 'Y'        else 'N' end program_handball_flag,
       case when s_udwcloudsync_enterprise_club_data.program_indoor_cycle='Yes' then 'Y'        else 'N' end program_indoor_cycle_flag,
       case when s_udwcloudsync_enterprise_club_data.program_kids_academy='Yes' then 'Y'        else 'N' end program_kids_academy_flag,
       case when s_udwcloudsync_enterprise_club_data.program_kids_activities='Yes' then 'Y'        else 'N' end program_kids_activities_flag,
       case when s_udwcloudsync_enterprise_club_data.program_kids_camps='Yes' then 'Y'        else 'N' end program_kids_camps_flag,
       case when s_udwcloudsync_enterprise_club_data.program_kids_sports_and_fitness='Yes' then 'Y'        else 'N' end program_kids_sports_and_fitness_flag,
       case when s_udwcloudsync_enterprise_club_data.program_kids_swim='Yes' then 'Y'        else 'N' end program_kids_swim_flag,
       case when s_udwcloudsync_enterprise_club_data.program_mixed_combat_arts='Yes' then 'Y'        else 'N' end program_mixed_combat_arts_flag,
       case when s_udwcloudsync_enterprise_club_data.program_outdoor_cycle='Yes' then 'Y'        else 'N' end program_outdoor_cycle_flag,
       case when s_udwcloudsync_enterprise_club_data.program_personal_training='Yes' then 'Y'        else 'N' end program_personal_training_flag,
       case when s_udwcloudsync_enterprise_club_data.program_pickleball='Yes' then 'Y'        else 'N' end program_pickleball_flag,
       case when s_udwcloudsync_enterprise_club_data.program_pilates='Yes' then 'Y'        else 'N' end program_pilates_flag,
       case when s_udwcloudsync_enterprise_club_data.program_racquetball='Yes' then 'Y'        else 'N' end program_racquetball_flag,
       case when s_udwcloudsync_enterprise_club_data.program_rock_climbing='Yes' then 'Y'        else 'N' end program_rock_climbing_flag,
       case when s_udwcloudsync_enterprise_club_data.program_run_club='Yes' then 'Y'        else 'N' end program_run_club_flag,
       case when s_udwcloudsync_enterprise_club_data.program_soccer='Yes' then 'Y'        else 'N' end program_soccer_flag,
       case when s_udwcloudsync_enterprise_club_data.program_squash='Yes' then 'Y'        else 'N' end program_squash_flag,
       case when s_udwcloudsync_enterprise_club_data.program_studio='Yes' then 'Y'        else 'N' end program_studio_flag,
       case when s_udwcloudsync_enterprise_club_data.program_swimming='Yes' then 'Y'        else 'N' end program_swimming_flag,
       case when s_udwcloudsync_enterprise_club_data.program_table_tennis='Yes' then 'Y'        else 'N' end program_table_tennis_flag,
       case when s_udwcloudsync_enterprise_club_data.program_team_training='Yes' then 'Y'        else 'N' end program_team_training_flag,
       case when s_udwcloudsync_enterprise_club_data.program_tennis='Yes' then 'Y'        else 'N' end program_tennis_flag,
       case when s_udwcloudsync_enterprise_club_data.program_volleyball='Yes' then 'Y'        else 'N' end program_volleyball_flag,
       case when s_udwcloudsync_enterprise_club_data.program_weight_loss='Yes' then 'Y'        else 'N' end program_weight_loss_flag,
       case when s_udwcloudsync_enterprise_club_data.program_yoga='Yes' then 'Y'        else 'N' end program_yoga_flag,
       case when s_udwcloudsync_enterprise_club_data.service_bar='Yes' then 'Y'        else 'N' end service_bar_flag,
       case when s_udwcloudsync_enterprise_club_data.service_basketball_training='Yes' then 'Y'        else 'N' end service_basketball_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_child_center='Yes' then 'Y'        else 'N' end service_child_center_flag,
       case when s_udwcloudsync_enterprise_club_data.service_golf_instruction='Yes' then 'Y'        else 'N' end service_golf_instruction_flag,
       case when s_udwcloudsync_enterprise_club_data.service_hair='Yes' then 'Y'        else 'N' end service_hair_flag,
       case when s_udwcloudsync_enterprise_club_data.service_health_assessments='Yes' then 'Y'        else 'N' end service_health_assessments_flag,
       case when s_udwcloudsync_enterprise_club_data.service_kids_academy='Yes' then 'Y'        else 'N' end service_kids_academy_flag,
       case when s_udwcloudsync_enterprise_club_data.service_kids_birthday_parties='Yes' then 'Y'        else 'N' end service_kids_birthday_parties_flag,
       case when s_udwcloudsync_enterprise_club_data.service_kids_camps='Yes' then 'Y'        else 'N' end service_kids_camps_flag,
       case when s_udwcloudsync_enterprise_club_data.service_kids_swim_lessons='Yes' then 'Y'        else 'N' end service_kids_swim_lessons_flag,
       case when s_udwcloudsync_enterprise_club_data.service_lifecafe='Yes' then 'Y'        else 'N' end service_lifecafe_flag,
       case when s_udwcloudsync_enterprise_club_data.service_marathon_training='Yes' then 'Y'        else 'N' end service_marathon_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_massage='Yes' then 'Y'        else 'N' end service_massage_flag,
       case when s_udwcloudsync_enterprise_club_data.service_medi_spa='Yes' then 'Y'        else 'N' end service_medi_spa_flag,
       case when s_udwcloudsync_enterprise_club_data.service_nails='Yes' then 'Y'        else 'N' end service_nails_flag,
       case when s_udwcloudsync_enterprise_club_data.service_nutritional_coaching='Yes' then 'Y'        else 'N' end service_nutritional_coaching_flag,
       case when s_udwcloudsync_enterprise_club_data.service_proactive_care='Yes' then 'Y'        else 'N' end service_proactive_care_flag,
       case when s_udwcloudsync_enterprise_club_data.service_racquetball_lessons='Yes' then 'Y'        else 'N' end service_racquetball_lessons_flag,
       case when s_udwcloudsync_enterprise_club_data.service_rare='Yes' then 'Y'        else 'N' end service_rare_flag,
       case when s_udwcloudsync_enterprise_club_data.service_rehabilitation_chiropractic='Yes' then 'Y'        else 'N' end service_rehabilitation_chiropractic_flag,
       case when s_udwcloudsync_enterprise_club_data.service_run_training='Yes' then 'Y'        else 'N' end service_run_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_skin='Yes' then 'Y'        else 'N' end service_skin_flag,
       case when s_udwcloudsync_enterprise_club_data.service_soccer_training='Yes' then 'Y'        else 'N' end service_soccer_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_squash_lessons='Yes' then 'Y'        else 'N' end service_squash_lessons_flag,
       case when s_udwcloudsync_enterprise_club_data.service_swim_assessments='Yes' then 'Y'        else 'N' end service_swim_assessments_flag,
       case when s_udwcloudsync_enterprise_club_data.service_team_training='Yes' then 'Y'        else 'N' end service_team_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_tennis_lessons='Yes' then 'Y'        else 'N' end service_tennis_lessons_flag,
       case when s_udwcloudsync_enterprise_club_data.service_tri_training='Yes' then 'Y'        else 'N' end service_tri_training_flag,
       case when s_udwcloudsync_enterprise_club_data.service_weight_loss='Yes' then 'Y'        else 'N' end service_weight_loss_flag,
       s_udwcloudsync_enterprise_club_data.title title,
       s_udwcloudsync_enterprise_club_data.web_free_pass web_free_pass,
       case when s_udwcloudsync_enterprise_club_data.web_inquiry=1 then 'Y'        else 'N' end web_inquiry_flag,
       case when s_udwcloudsync_enterprise_club_data.web_presale_waitlist=1 then 'Y'        else 'N' end web_presale_waitlist_flag,
       case when s_udwcloudsync_enterprise_club_data.web_price_request=1 then 'Y'        else 'N' end web_price_request_flag,
       s_udwcloudsync_enterprise_club_data.zip zip,
       isnull(h_udwcloudsync_enterprise_club_data.dv_deleted,0) dv_deleted,
       p_udwcloudsync_enterprise_club_data.p_udwcloudsync_enterprise_club_data_id,
       p_udwcloudsync_enterprise_club_data.dv_batch_id,
       p_udwcloudsync_enterprise_club_data.dv_load_date_time,
       p_udwcloudsync_enterprise_club_data.dv_load_end_date_time
  from dbo.h_udwcloudsync_enterprise_club_data
  join dbo.p_udwcloudsync_enterprise_club_data
    on h_udwcloudsync_enterprise_club_data.bk_hash = p_udwcloudsync_enterprise_club_data.bk_hash
  join #p_udwcloudsync_enterprise_club_data_insert
    on p_udwcloudsync_enterprise_club_data.bk_hash = #p_udwcloudsync_enterprise_club_data_insert.bk_hash
   and p_udwcloudsync_enterprise_club_data.p_udwcloudsync_enterprise_club_data_id = #p_udwcloudsync_enterprise_club_data_insert.p_udwcloudsync_enterprise_club_data_id
  join dbo.l_udwcloudsync_enterprise_club_data
    on p_udwcloudsync_enterprise_club_data.bk_hash = l_udwcloudsync_enterprise_club_data.bk_hash
   and p_udwcloudsync_enterprise_club_data.l_udwcloudsync_enterprise_club_data_id = l_udwcloudsync_enterprise_club_data.l_udwcloudsync_enterprise_club_data_id
  join dbo.s_udwcloudsync_enterprise_club_data
    on p_udwcloudsync_enterprise_club_data.bk_hash = s_udwcloudsync_enterprise_club_data.bk_hash
   and p_udwcloudsync_enterprise_club_data.s_udwcloudsync_enterprise_club_data_id = s_udwcloudsync_enterprise_club_data.s_udwcloudsync_enterprise_club_data_id

-- do as a single transaction
--   delete records from the dimensional table where the business_key is in #p_*_insert temp table
--   insert records from all of the joins to the pit table and to #p_*_insert temp table
begin tran
  delete dbo.d_udwcloudsync_enterprise_club_data
   where d_udwcloudsync_enterprise_club_data.bk_hash in (select bk_hash from #p_udwcloudsync_enterprise_club_data_insert)

  insert dbo.d_udwcloudsync_enterprise_club_data(
             bk_hash,
             enterprise_club_data_id,
             amenity_conditioner_flag,
             amenity_cotton_balls_flag,
             amenity_deodorant_flag,
             amenity_free_lockers_and_towels_flag,
             amenity_hairspray_flag,
             amenity_mouthwash_flag,
             amenity_plasma_big_screen_tvs_flag,
             amenity_razors_flag,
             amenity_shampoo_flag,
             amenity_wireless_internet_access_flag,
             app_created_by,
             app_modified_by,
             club_hours,
             club_level,
             compliance_asset_id,
             content_type,
             created_by,
             created_dim_date_key,
             dim_club_key,
             feature_advanced_training_studio_flag,
             feature_alpha_field_flag,
             feature_bar_flag,
             feature_basketball_courts_flag,
             feature_boxing_gym_flag,
             feature_business_center_flag,
             feature_cardio_equipment_flag,
             feature_child_center_flag,
             feature_connected_technology_flag,
             feature_deluge_flag,
             feature_fitness_studios_flag,
             feature_free_weights_and_equipment_flag,
             feature_functional_training_area_flag,
             feature_hamam_flag,
             feature_indoor_cycle_studio_flag,
             feature_indoor_golf_center_flag,
             feature_indoor_lap_pool_flag,
             feature_indoor_leisure_pool_flag,
             feature_indoor_tennis_courts_flag,
             feature_indoor_turf_field_flag,
             feature_indoor_water_slides_flag,
             feature_indoor_whirlpool_flag,
             feature_infant_room_flag,
             feature_kids_academy_flag,
             feature_kids_gym_flag,
             feature_kids_language_arts_studio_flag,
             feature_kids_learning_lab_flag,
             feature_kids_media_room_flag,
             feature_kids_movement_studio_flag,
             feature_kids_outdoor_play_area_flag,
             feature_kids_tumbling_studio_flag,
             feature_lazy_river_flag,
             feature_lifecafe_flag,
             feature_lifecafe_poolside_bistro_flag,
             feature_lifespa_flag,
             feature_mixed_combats_arts_studio_flag,
             feature_outdoor_fitness_trail_flag,
             feature_outdoor_lap_pool_flag,
             feature_outdoor_swimming_pool_flag,
             feature_outdoor_tennis_courts_flag,
             feature_outdoor_turf_field_flag,
             feature_outdoor_water_slides_flag,
             feature_outdoor_whirlpool_flag,
             feature_pickleball_court_flag,
             feature_pilates_studio_flag,
             feature_play_maze_flag,
             feature_pre_school_flag,
             feature_proactive_care_clinic_flag,
             feature_racquetball_courts_flag,
             feature_rare_flag,
             feature_rehabilitation_and_chiropractic_clinic_flag,
             feature_resistance_training_area_flag,
             feature_retail_store_flag,
             feature_rock_wall_flag,
             feature_rooftop_patio_flag,
             feature_sand_volleyball_court_flag,
             feature_saunas_flag,
             feature_splash_pad_flag,
             feature_squash_courts_flag,
             feature_steam_rooms_flag,
             feature_volleyball_courts_flag,
             feature_walking_running_track_flag,
             feature_weight_machines_flag,
             feature_yoga_studio_flag,
             feature_zero_depth_entry_pool_flag,
             folder_child_count,
             general_manager,
             general_manager_email,
             general_manager_phone,
             inserted_dim_date_key,
             item_child_count,
             item_type,
             label_applied,
             label_applied_by,
             label_setting,
             labels,
             member_services_manager,
             member_services_manager_email,
             member_services_manager_phone,
             mms_club_id,
             modified_by,
             modified_dim_date_key,
             oms_flag,
             open_dim_date_key,
             path,
             phone,
             program_badminton_flag,
             program_barre_flag,
             program_basketball_flag,
             program_birthday_parties_flag,
             program_boxing_flag,
             program_golf_flag,
             program_handball_flag,
             program_indoor_cycle_flag,
             program_kids_academy_flag,
             program_kids_activities_flag,
             program_kids_camps_flag,
             program_kids_sports_and_fitness_flag,
             program_kids_swim_flag,
             program_mixed_combat_arts_flag,
             program_outdoor_cycle_flag,
             program_personal_training_flag,
             program_pickleball_flag,
             program_pilates_flag,
             program_racquetball_flag,
             program_rock_climbing_flag,
             program_run_club_flag,
             program_soccer_flag,
             program_squash_flag,
             program_studio_flag,
             program_swimming_flag,
             program_table_tennis_flag,
             program_team_training_flag,
             program_tennis_flag,
             program_volleyball_flag,
             program_weight_loss_flag,
             program_yoga_flag,
             service_bar_flag,
             service_basketball_training_flag,
             service_child_center_flag,
             service_golf_instruction_flag,
             service_hair_flag,
             service_health_assessments_flag,
             service_kids_academy_flag,
             service_kids_birthday_parties_flag,
             service_kids_camps_flag,
             service_kids_swim_lessons_flag,
             service_lifecafe_flag,
             service_marathon_training_flag,
             service_massage_flag,
             service_medi_spa_flag,
             service_nails_flag,
             service_nutritional_coaching_flag,
             service_proactive_care_flag,
             service_racquetball_lessons_flag,
             service_rare_flag,
             service_rehabilitation_chiropractic_flag,
             service_run_training_flag,
             service_skin_flag,
             service_soccer_training_flag,
             service_squash_lessons_flag,
             service_swim_assessments_flag,
             service_team_training_flag,
             service_tennis_lessons_flag,
             service_tri_training_flag,
             service_weight_loss_flag,
             title,
             web_free_pass,
             web_inquiry_flag,
             web_presale_waitlist_flag,
             web_price_request_flag,
             zip,
             deleted_flag,
             p_udwcloudsync_enterprise_club_data_id,
             dv_load_date_time,
             dv_load_end_date_time,
             dv_batch_id,
             dv_inserted_date_time,
             dv_insert_user)
  select bk_hash,
         enterprise_club_data_id,
         amenity_conditioner_flag,
         amenity_cotton_balls_flag,
         amenity_deodorant_flag,
         amenity_free_lockers_and_towels_flag,
         amenity_hairspray_flag,
         amenity_mouthwash_flag,
         amenity_plasma_big_screen_tvs_flag,
         amenity_razors_flag,
         amenity_shampoo_flag,
         amenity_wireless_internet_access_flag,
         app_created_by,
         app_modified_by,
         club_hours,
         club_level,
         compliance_asset_id,
         content_type,
         created_by,
         created_dim_date_key,
         dim_club_key,
         feature_advanced_training_studio_flag,
         feature_alpha_field_flag,
         feature_bar_flag,
         feature_basketball_courts_flag,
         feature_boxing_gym_flag,
         feature_business_center_flag,
         feature_cardio_equipment_flag,
         feature_child_center_flag,
         feature_connected_technology_flag,
         feature_deluge_flag,
         feature_fitness_studios_flag,
         feature_free_weights_and_equipment_flag,
         feature_functional_training_area_flag,
         feature_hamam_flag,
         feature_indoor_cycle_studio_flag,
         feature_indoor_golf_center_flag,
         feature_indoor_lap_pool_flag,
         feature_indoor_leisure_pool_flag,
         feature_indoor_tennis_courts_flag,
         feature_indoor_turf_field_flag,
         feature_indoor_water_slides_flag,
         feature_indoor_whirlpool_flag,
         feature_infant_room_flag,
         feature_kids_academy_flag,
         feature_kids_gym_flag,
         feature_kids_language_arts_studio_flag,
         feature_kids_learning_lab_flag,
         feature_kids_media_room_flag,
         feature_kids_movement_studio_flag,
         feature_kids_outdoor_play_area_flag,
         feature_kids_tumbling_studio_flag,
         feature_lazy_river_flag,
         feature_lifecafe_flag,
         feature_lifecafe_poolside_bistro_flag,
         feature_lifespa_flag,
         feature_mixed_combats_arts_studio_flag,
         feature_outdoor_fitness_trail_flag,
         feature_outdoor_lap_pool_flag,
         feature_outdoor_swimming_pool_flag,
         feature_outdoor_tennis_courts_flag,
         feature_outdoor_turf_field_flag,
         feature_outdoor_water_slides_flag,
         feature_outdoor_whirlpool_flag,
         feature_pickleball_court_flag,
         feature_pilates_studio_flag,
         feature_play_maze_flag,
         feature_pre_school_flag,
         feature_proactive_care_clinic_flag,
         feature_racquetball_courts_flag,
         feature_rare_flag,
         feature_rehabilitation_and_chiropractic_clinic_flag,
         feature_resistance_training_area_flag,
         feature_retail_store_flag,
         feature_rock_wall_flag,
         feature_rooftop_patio_flag,
         feature_sand_volleyball_court_flag,
         feature_saunas_flag,
         feature_splash_pad_flag,
         feature_squash_courts_flag,
         feature_steam_rooms_flag,
         feature_volleyball_courts_flag,
         feature_walking_running_track_flag,
         feature_weight_machines_flag,
         feature_yoga_studio_flag,
         feature_zero_depth_entry_pool_flag,
         folder_child_count,
         general_manager,
         general_manager_email,
         general_manager_phone,
         inserted_dim_date_key,
         item_child_count,
         item_type,
         label_applied,
         label_applied_by,
         label_setting,
         labels,
         member_services_manager,
         member_services_manager_email,
         member_services_manager_phone,
         mms_club_id,
         modified_by,
         modified_dim_date_key,
         oms_flag,
         open_dim_date_key,
         path,
         phone,
         program_badminton_flag,
         program_barre_flag,
         program_basketball_flag,
         program_birthday_parties_flag,
         program_boxing_flag,
         program_golf_flag,
         program_handball_flag,
         program_indoor_cycle_flag,
         program_kids_academy_flag,
         program_kids_activities_flag,
         program_kids_camps_flag,
         program_kids_sports_and_fitness_flag,
         program_kids_swim_flag,
         program_mixed_combat_arts_flag,
         program_outdoor_cycle_flag,
         program_personal_training_flag,
         program_pickleball_flag,
         program_pilates_flag,
         program_racquetball_flag,
         program_rock_climbing_flag,
         program_run_club_flag,
         program_soccer_flag,
         program_squash_flag,
         program_studio_flag,
         program_swimming_flag,
         program_table_tennis_flag,
         program_team_training_flag,
         program_tennis_flag,
         program_volleyball_flag,
         program_weight_loss_flag,
         program_yoga_flag,
         service_bar_flag,
         service_basketball_training_flag,
         service_child_center_flag,
         service_golf_instruction_flag,
         service_hair_flag,
         service_health_assessments_flag,
         service_kids_academy_flag,
         service_kids_birthday_parties_flag,
         service_kids_camps_flag,
         service_kids_swim_lessons_flag,
         service_lifecafe_flag,
         service_marathon_training_flag,
         service_massage_flag,
         service_medi_spa_flag,
         service_nails_flag,
         service_nutritional_coaching_flag,
         service_proactive_care_flag,
         service_racquetball_lessons_flag,
         service_rare_flag,
         service_rehabilitation_chiropractic_flag,
         service_run_training_flag,
         service_skin_flag,
         service_soccer_training_flag,
         service_squash_lessons_flag,
         service_swim_assessments_flag,
         service_team_training_flag,
         service_tennis_lessons_flag,
         service_tri_training_flag,
         service_weight_loss_flag,
         title,
         web_free_pass,
         web_inquiry_flag,
         web_presale_waitlist_flag,
         web_price_request_flag,
         zip,
         dv_deleted,
         p_udwcloudsync_enterprise_club_data_id,
         dv_load_date_time,
         dv_load_end_date_time,
         dv_batch_id,
         getdate(),
         suser_sname()
    from #insert
commit tran

--force replication
set @max_dv_batch_id = (select isnull(max(dv_batch_id),-2) from d_udwcloudsync_enterprise_club_data)
--Done!
end
