CREATE TABLE [dbo].[stage_mms_MembershipType_history] (
    [MMSMembershipTypeKey]            BIGINT        NOT NULL,
    [MembershipTypeID]                INT           NULL,
    [ProductID]                       INT           NULL,
    [AssessDueFlag]                   BIT           NULL,
    [ValMembershipTypeGroupID]        INT           NULL,
    [ValCheckInGroupID]               INT           NULL,
    [MMSInsertedDateTime]             DATETIME      NULL,
    [ValMembershipTypeFamilyStatusID] INT           NULL,
    [ShortTermMembershipFlag]         BIT           NULL,
    [ValEnrollmentTypeID]             INT           NULL,
    [ValUnitTypeID]                   INT           NULL,
    [MaxUnitType]                     INT           NULL,
    [MemberCardDesignID]              INT           NULL,
    [ExpressMembershipFlag]           BIT           NULL,
    [MMSUpdatedDateTime]              DATETIME      NULL,
    [InsertedDateTime]                DATETIME      NULL,
    [InsertUser]                      VARCHAR (50)  NULL,
    [batch_id]                        BIGINT        NOT NULL,
    [ETLSourceSystemKey]              INT           NULL,
    [UpdatedDateTime]                 DATETIME      NULL,
    [UpdateUser]                      VARCHAR (50)  NULL,
    [ValWelcomeKitTypeID]             INT           NULL,
    [DisplayName]                     VARCHAR (50)  NULL,
    [AssessJrMemberDuesFlag]          BIT           NULL,
    [WaiveAdminFeeFlag]               BIT           NULL,
    [GTASigOverride]                  VARCHAR (100) NULL,
    [AllowPartnerProgramFlag]         BIT           NULL,
    [MinUnitType]                     INT           NULL,
    [MinPrimaryAge]                   INT           NULL,
    [ValPricingRuleId]                INT           NULL,
    [ValRestrictedGroupId]            INT           NULL,
    [ValPricingMethodId]              INT           NULL,
    [WaiveEnrollmentFeeFlag]          BIT           NULL,
    [WaiveLateFeeFlag]                BIT           NULL,
    [SuppressMembershipCardFlag]      BIT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

