CREATE TABLE [dbo].[stage_mms_Club] (
    [stage_mms_Club_id]               BIGINT        NOT NULL,
    [ClubID]                          INT           NULL,
    [ValRegionID]                     INT           NULL,
    [StatementMessageID]              INT           NULL,
    [ValClubTypeID]                   INT           NULL,
    [DomainNamePrefix]                VARCHAR (10)  NULL,
    [ClubName]                        VARCHAR (50)  NULL,
    [ReceiptFooter]                   VARCHAR (100) NULL,
    [DisplayUIFlag]                   BIT           NULL,
    [CheckInGroupLevel]               INT           NULL,
    [ValStatementTypeID]              INT           NULL,
    [ChargeToAccountFlag]             BIT           NULL,
    [ValPreSaleID]                    INT           NULL,
    [ClubActivationDate]              DATETIME      NULL,
    [ValTimeZoneID]                   INT           NULL,
    [InsertedDateTime]                DATETIME      NULL,
    [ValCWRegionID]                   INT           NULL,
    [EFTGroupID]                      INT           NULL,
    [GLTaxID]                         INT           NULL,
    [GLClubID]                        INT           NULL,
    [CRMDivisionCode]                 VARCHAR (15)  NULL,
    [AssessJrMemberDuesFlag]          BIT           NULL,
    [SellJrMemberDuesFlag]            BIT           NULL,
    [UpdatedDateTime]                 DATETIME      NULL,
    [ClubCode]                        VARCHAR (3)   NULL,
    [SiteID]                          INT           NULL,
    [NewMemberCardFlag]               BIT           NULL,
    [ValMemberActivityRegionID]       INT           NULL,
    [IGStoreID]                       INT           NULL,
    [ChildCenterWeeklyLimit]          INT           NULL,
    [ValSalesAreaID]                  INT           NULL,
    [ValPTRCLAreaID]                  INT           NULL,
    [FormalClubName]                  VARCHAR (50)  NULL,
    [KronosForecastMapPath]           VARCHAR (15)  NULL,
    [ClubDeActivationDate]            DATETIME      NULL,
    [GLCashEntryAccount]              VARCHAR (4)   NULL,
    [GLReceivablesEntryAccount]       VARCHAR (4)   NULL,
    [GLCashEntryCashSubAccount]       VARCHAR (11)  NULL,
    [GLCashEntryCreditCardSubAccount] VARCHAR (11)  NULL,
    [GLReceivablesEntrySubAccount]    VARCHAR (11)  NULL,
    [GLCashEntryCompanyName]          VARCHAR (15)  NULL,
    [GLReceivablesEntryCompanyName]   VARCHAR (15)  NULL,
    [MarketingMapRegion]              VARCHAR (50)  NULL,
    [MarketingMapXmlStateName]        VARCHAR (50)  NULL,
    [MarketingClubLevel]              VARCHAR (50)  NULL,
    [ValCurrencyCodeID]               INT           NULL,
    [AllowMultipleCurrencyFlag]       BIT           NULL,
    [WorkdayRegion]                   VARCHAR (4)   NULL,
    [AllowJuniorCheckInFlag]          BIT           NULL,
    [LTFResourceID]                   INT           NULL,
    [HealthClubIdentifier]            VARCHAR (50)  NULL,
    [MaxJuniorAge]                    INT           NULL,
    [MaxSecondaryAge]                 INT           NULL,
    [ChargeNextMonthDate]             INT           NULL,
    [MinFrontDeskCheckinAge]          INT           NULL,
    [MaxChildCenterCheckinAge]        INT           NULL,
    [StateCancellationDays]           INT           NULL,
    [dv_batch_id]                     BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

