CREATE TABLE [dbo].[stage_spabiz_TICKETPAY] (
    [stage_spabiz_TICKETPAY_id] BIGINT          NOT NULL,
    [ID]                        DECIMAL (26, 6) NULL,
    [COUNTERID]                 DECIMAL (26, 6) NULL,
    [STOREID]                   DECIMAL (26, 6) NULL,
    [EDITTIME]                  DATETIME        NULL,
    [TICKETID]                  DECIMAL (26, 6) NULL,
    [Date]                      DATETIME        NULL,
    [PAYNUM]                    VARCHAR (150)   NULL,
    [PAYID]                     DECIMAL (26, 6) NULL,
    [PAYTYPE]                   DECIMAL (26, 6) NULL,
    [CUSTID]                    DECIMAL (26, 6) NULL,
    [STATUS]                    DECIMAL (26, 6) NULL,
    [SHIFTID]                   DECIMAL (26, 6) NULL,
    [DAYID]                     DECIMAL (26, 6) NULL,
    [PERIODID]                  DECIMAL (26, 6) NULL,
    [REFID]                     DECIMAL (26, 6) NULL,
    [OK]                        DECIMAL (26, 6) NULL,
    [AMOUNT]                    DECIMAL (26, 6) NULL,
    [APPROVAL]                  VARCHAR (150)   NULL,
    [STAFFID]                   DECIMAL (26, 6) NULL,
    [STORE_NUMBER]              DECIMAL (26, 6) NULL,
    [GLACCOUNT]                 VARCHAR (45)    NULL,
    [ACQ]                       VARCHAR (600)   NULL,
    [ADJUSTED]                  DECIMAL (26, 6) NULL,
    [CARDIS]                    DECIMAL (26, 6) NULL,
    [PAYCOUNTER]                DECIMAL (26, 6) NULL,
    [PROCESSDATA]               VARCHAR (600)   NULL,
    [REFNO]                     VARCHAR (150)   NULL,
    [TOKEN1]                    VARCHAR (600)   NULL,
    [TOKEN2]                    VARCHAR (600)   NULL,
    [TOKEN3]                    VARCHAR (600)   NULL,
    [SBCC]                      DECIMAL (26, 6) NULL,
    [dv_batch_id]               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

