CREATE TABLE [dbo].[stage_mms_Product_history] (
    [MMSProductKey]                     INT            NULL,
    [ProductID]                         INT            NULL,
    [DepartmentID]                      INT            NULL,
    [Name]                              VARCHAR (20)   NULL,
    [Description]                       VARCHAR (50)   NULL,
    [DisplayUIFlag]                     BIT            NULL,
    [SortOrder]                         INT            NULL,
    [MMSInsertedDateTime]               DATETIME       NULL,
    [TurnOffDateTime]                   DATETIME       NULL,
    [StartDate]                         DATETIME       NULL,
    [EndDate]                           DATETIME       NULL,
    [GLAccountNumber]                   VARCHAR (10)   NULL,
    [GLSubAccountNumber]                VARCHAR (7)    NULL,
    [GLOverRideClubID]                  INT            NULL,
    [ValGLGroupID]                      TINYINT        NULL,
    [ValRecurrentProductTypeID]         SMALLINT       NULL,
    [CompletePackageFlag]               BIT            NULL,
    [AllowZeroDollarFlag]               BIT            NULL,
    [PackageProductFlag]                BIT            NULL,
    [SoldNotServicedFlag]               BIT            NULL,
    [MMSUpdatedDateTime]                DATETIME       NULL,
    [InsertedDateTime]                  DATETIME       NULL,
    [InsertUser]                        VARCHAR (50)   NULL,
    [BatchID]                           INT            NULL,
    [ETLSourceSystemKey]                INT            NULL,
    [ValProductStatusID]                TINYINT        NULL,
    [TipAllowedFlag]                    BIT            NULL,
    [JrMemberDuesFlag]                  BIT            NULL,
    [ValAssessmentDayID]                SMALLINT       NULL,
    [EligibleForHoldFlag]               BIT            NULL,
    [ConfirmMemberDataFlag]             BIT            NULL,
    [UpdatedDateTime]                   DATETIME       NULL,
    [UpdateUser]                        VARCHAR (50)   NULL,
    [MedicalProductFlag]                BIT            NULL,
    [BundleProductFlag]                 BIT            NULL,
    [WorkdayAccount]                    VARCHAR (6)    NULL,
    [WorkdayCostCenter]                 VARCHAR (6)    NULL,
    [WorkdayOffering]                   VARCHAR (10)   NULL,
    [WorkdayOverRideRegion]             VARCHAR (4)    NULL,
    [WorkdayRevenueProductGroupAccount] VARCHAR (6)    NULL,
    [DeferredRevenueFlag]               BIT            NULL,
    [PriceLockedFlag]                   BIT            NULL,
    [RevenueCategory]                   VARCHAR (7)    NULL,
    [SpendCategory]                     VARCHAR (7)    NULL,
    [PayComponent]                      VARCHAR (50)   NULL,
    [AssessAsDuesFlag]                  BIT            NULL,
    [ValEmployeeLevelTypeID]            TINYINT        NULL,
    [LTBuckEligible]                    BIT            NULL,
    [LTBuckCostPercent]                 NUMERIC (4, 1) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

