CREATE TABLE [dbo].[stage_mms_Package] (
    [stage_mms_Package_id]    BIGINT          NOT NULL,
    [PackageID]               INT             NULL,
    [MemberID]                INT             NULL,
    [MembershipID]            INT             NULL,
    [ClubID]                  INT             NULL,
    [NumberOfSessions]        SMALLINT        NULL,
    [PricePerSession]         NUMERIC (9, 4)  NULL,
    [EmployeeID]              INT             NULL,
    [ValPackageStatusID]      SMALLINT        NULL,
    [MMSTranID]               INT             NULL,
    [ProductID]               INT             NULL,
    [TranItemID]              INT             NULL,
    [CreatedDateTime]         DATETIME        NULL,
    [UTCCreatedDateTime]      DATETIME        NULL,
    [CreatedDateTimeZone]     VARCHAR (4)     NULL,
    [SessionsLeft]            SMALLINT        NULL,
    [BalanceAmount]           NUMERIC (9, 4)  NULL,
    [InsertedDateTime]        DATETIME        NULL,
    [UpdatedDateTime]         DATETIME        NULL,
    [PackageEditedFlag]       BIT             NULL,
    [PackageEditDateTime]     DATETIME        NULL,
    [UTCPackageEditDateTime]  DATETIME        NULL,
    [PackageEditDateTimeZone] VARCHAR (4)     NULL,
    [ExpirationDateTime]      DATETIME        NULL,
    [UnexpireCount]           INT             NULL,
    [LastUnexpiredDateTime]   DATETIME        NULL,
    [TransactionSource]       VARCHAR (50)    NULL,
    [ExternalPackageID]       VARCHAR (50)    NULL,
    [OriginalBalanceAmount]   DECIMAL (26, 6) NULL,
    [dv_batch_id]             BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

