CREATE TABLE [dbo].[stage_spabiz_CUSTCARD] (
    [stage_spabiz_CUSTCARD_id]  BIGINT          NOT NULL,
    [ID]                        DECIMAL (26, 6) NULL,
    [COUNTERID]                 DECIMAL (26, 6) NULL,
    [STOREID]                   DECIMAL (26, 6) NULL,
    [EDITTIME]                  DATETIME        NULL,
    [TICKETID]                  DECIMAL (26, 6) NULL,
    [SERIALNUM]                 VARCHAR (150)   NULL,
    [Date]                      DATETIME        NULL,
    [CUSTCARDID]                DECIMAL (26, 6) NULL,
    [STAFFIDCREATE]             DECIMAL (26, 6) NULL,
    [STAFFID1]                  DECIMAL (26, 6) NULL,
    [STAFFID2]                  DECIMAL (26, 6) NULL,
    [DAYSGOOD]                  DECIMAL (26, 6) NULL,
    [EXPDATE]                   DATETIME        NULL,
    [BUY_CUSTID]                DECIMAL (26, 6) NULL,
    [CUSTID]                    DECIMAL (26, 6) NULL,
    [STATUS]                    DECIMAL (26, 6) NULL,
    [MESSAGE]                   VARCHAR (765)   NULL,
    [LASTUSED]                  DATETIME        NULL,
    [NOTE]                      VARCHAR (765)   NULL,
    [PRICE]                     DECIMAL (26, 6) NULL,
    [TOTALSALES]                DECIMAL (26, 6) NULL,
    [YTDSALES]                  DECIMAL (26, 6) NULL,
    [PRODUCTSALES]              DECIMAL (26, 6) NULL,
    [SERVICESALES]              DECIMAL (26, 6) NULL,
    [STORE_NUMBER]              DECIMAL (26, 6) NULL,
    [DELETED]                   DECIMAL (26, 6) NULL,
    [MEMTYPE]                   DECIMAL (26, 6) NULL,
    [NEXTBILLINGDATE]           DATETIME        NULL,
    [RECURRING]                 DECIMAL (26, 6) NULL,
    [RECURRING_DECLINED]        DECIMAL (26, 6) NULL,
    [RECURRING_DECLINED_REASON] VARCHAR (765)   NULL,
    [CURRENT_INSTALLMENT]       DECIMAL (26, 6) NULL,
    [RECURRING_AFTER_EXPIRE]    DECIMAL (26, 6) NULL,
    [PRORATED_AMOUNT]           DECIMAL (26, 6) NULL,
    [INITIAL_AMOUNT]            DECIMAL (26, 6) NULL,
    [CANCELLED]                 DECIMAL (26, 6) NULL,
    [CANCELID]                  DECIMAL (26, 6) NULL,
    [dv_batch_id]               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

