CREATE TABLE [dbo].[stage_spabiz_DISCOUNT] (
    [stage_spabiz_DISCOUNT_id] BIGINT          NOT NULL,
    [ID]                       DECIMAL (26, 6) NULL,
    [COUNTERID]                DECIMAL (26, 6) NULL,
    [STOREID]                  DECIMAL (26, 6) NULL,
    [EDITTIME]                 DATETIME        NULL,
    [Delete]                   DECIMAL (26, 6) NULL,
    [DELETEDATE]               DATETIME        NULL,
    [NAME]                     VARCHAR (180)   NULL,
    [QUICKID]                  VARCHAR (45)    NULL,
    [AMOUNT]                   DECIMAL (26, 6) NULL,
    [PAYRETAILCOMISH]          DECIMAL (26, 6) NULL,
    [PAYSERVICECOMISH]         DECIMAL (26, 6) NULL,
    [PAYCOMISH]                DECIMAL (26, 6) NULL,
    [ISPROMO]                  DECIMAL (26, 6) NULL,
    [USEDATERANGE]             DECIMAL (26, 6) NULL,
    [FROMDATE]                 DATETIME        NULL,
    [TODATE]                   DATETIME        NULL,
    [APPLYTO]                  DECIMAL (26, 6) NULL,
    [DISCOUNTFILTER]           DECIMAL (26, 6) NULL,
    [APPLYWHEN]                DECIMAL (26, 6) NULL,
    [DEPTCAT]                  DECIMAL (26, 6) NULL,
    [SEARCHCAT]                DECIMAL (26, 6) NULL,
    [Percent_Discount]         DECIMAL (26, 6) NULL,
    [Percent_Dollar]           DECIMAL (26, 6) NULL,
    [STORE_NUMBER]             DECIMAL (26, 6) NULL,
    [GLACCOUNT]                VARCHAR (60)    NULL,
    [DESCRIPTION]              VARCHAR (765)   NULL,
    [DESCRIPTITON]             VARCHAR (150)   NULL,
    [SECURITYLEVEL]            DECIMAL (26, 6) NULL,
    [ONETIME]                  DECIMAL (26, 6) NULL,
    [dv_batch_id]              BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

