CREATE TABLE [dbo].[stage_workday_employee] (
    [stage_workday_employee_id]  BIGINT          NOT NULL,
    [employee_id]                INT             NULL,
    [manager_id]                 INT             NULL,
    [mms_club_id]                NVARCHAR (4000) NULL,
    [first_name]                 NVARCHAR (255)  NULL,
    [middle_name]                NVARCHAR (255)  NULL,
    [last_name]                  NVARCHAR (255)  NULL,
    [preferred_first_name]       NVARCHAR (255)  NULL,
    [preferred_middle_name]      NVARCHAR (255)  NULL,
    [preferred_last_name]        NVARCHAR (255)  NULL,
    [primary_work_email]         NVARCHAR (255)  NULL,
    [phone_number]               NVARCHAR (255)  NULL,
    [hire_date]                  DATETIME        NULL,
    [termination_date]           DATETIME        NULL,
    [active_status]              NVARCHAR (255)  NULL,
    [job_levels]                 NVARCHAR (4000) NULL,
    [job_families]               NVARCHAR (4000) NULL,
    [job_sub_families]           NVARCHAR (4000) NULL,
    [job_profiles]               NVARCHAR (4000) NULL,
    [business_titles]            NVARCHAR (4000) NULL,
    [marketing_titles]           NVARCHAR (4000) NULL,
    [job_codes]                  NVARCHAR (4000) NULL,
    [subordinates]               NVARCHAR (255)  NULL,
    [category]                   NVARCHAR (255)  NULL,
    [certifications]             VARCHAR (8000)  NULL,
    [cf_nickname]                NVARCHAR (255)  NULL,
    [is_primary]                 NVARCHAR (255)  NULL,
    [cf_employment_status]       NVARCHAR (255)  NULL,
    [pay_rate_for_all_positions] NVARCHAR (4000) NULL,
    [three_digit_club_codes]     NVARCHAR (4000) NULL,
    [jan_one]                    DATETIME        NULL,
    [dv_batch_id]                BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

