CREATE TABLE [dbo].[stage_magento_sales_order_payment] (
    [stage_magento_sales_order_payment_id] BIGINT          NOT NULL,
    [entity_id]                            INT             NULL,
    [parent_id]                            INT             NULL,
    [base_shipping_captured]               DECIMAL (12, 4) NULL,
    [shipping_captured]                    DECIMAL (12, 4) NULL,
    [amount_refunded]                      DECIMAL (12, 4) NULL,
    [base_amount_paid]                     DECIMAL (12, 4) NULL,
    [amount_canceled]                      DECIMAL (12, 4) NULL,
    [base_amount_authorized]               DECIMAL (12, 4) NULL,
    [base_amount_paid_online]              DECIMAL (12, 4) NULL,
    [base_amount_refunded_online]          DECIMAL (12, 4) NULL,
    [base_shipping_amount]                 DECIMAL (12, 4) NULL,
    [shipping_amount]                      DECIMAL (12, 4) NULL,
    [amount_paid]                          DECIMAL (12, 4) NULL,
    [amount_authorized]                    DECIMAL (12, 4) NULL,
    [base_amount_ordered]                  DECIMAL (12, 4) NULL,
    [base_shipping_refunded]               DECIMAL (12, 4) NULL,
    [shipping_refunded]                    DECIMAL (12, 4) NULL,
    [base_amount_refunded]                 DECIMAL (12, 4) NULL,
    [amount_ordered]                       DECIMAL (12, 4) NULL,
    [base_amount_canceled]                 DECIMAL (12, 4) NULL,
    [quote_payment_id]                     INT             NULL,
    [additional_data]                      VARCHAR (8000)  NULL,
    [cc_exp_month]                         VARCHAR (12)    NULL,
    [cc_ss_start_year]                     VARCHAR (12)    NULL,
    [echeck_bank_name]                     VARCHAR (128)   NULL,
    [method]                               VARCHAR (128)   NULL,
    [cc_debug_request_body]                VARCHAR (32)    NULL,
    [cc_secure_verify]                     VARCHAR (32)    NULL,
    [protection_eligibility]               VARCHAR (32)    NULL,
    [cc_approval]                          VARCHAR (32)    NULL,
    [cc_last_4]                            VARCHAR (100)   NULL,
    [cc_status_description]                VARCHAR (32)    NULL,
    [echeck_type]                          VARCHAR (32)    NULL,
    [cc_debug_response_serialized]         VARCHAR (32)    NULL,
    [cc_ss_start_month]                    VARCHAR (128)   NULL,
    [echeck_account_type]                  VARCHAR (255)   NULL,
    [last_trans_id]                        VARCHAR (32)    NULL,
    [cc_cid_status]                        VARCHAR (32)    NULL,
    [cc_owner]                             VARCHAR (128)   NULL,
    [cc_type]                              VARCHAR (32)    NULL,
    [po_number]                            VARCHAR (32)    NULL,
    [cc_exp_year]                          VARCHAR (4)     NULL,
    [cc_status]                            VARCHAR (4)     NULL,
    [echeck_routing_number]                VARCHAR (32)    NULL,
    [account_status]                       VARCHAR (32)    NULL,
    [anet_trans_method]                    VARCHAR (32)    NULL,
    [cc_debug_response_body]               VARCHAR (32)    NULL,
    [cc_ss_issue]                          VARCHAR (32)    NULL,
    [echeck_account_name]                  VARCHAR (32)    NULL,
    [cc_avs_status]                        VARCHAR (32)    NULL,
    [cc_number_enc]                        VARCHAR (128)   NULL,
    [cc_trans_id]                          VARCHAR (32)    NULL,
    [address_status]                       VARCHAR (32)    NULL,
    [additional_information]               VARCHAR (8000)  NULL,
    [dummy_modified_date_time]             DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

