CREATE TABLE [dbo].[stage_magento_sales_order_address] (
    [stage_magento_sales_order_address_id] BIGINT         NOT NULL,
    [entity_id]                            INT            NULL,
    [parent_id]                            INT            NULL,
    [customer_address_id]                  INT            NULL,
    [quote_address_id]                     INT            NULL,
    [region_id]                            INT            NULL,
    [customer_id]                          INT            NULL,
    [fax]                                  VARCHAR (255)  NULL,
    [region]                               VARCHAR (255)  NULL,
    [postcode]                             VARCHAR (255)  NULL,
    [lastname]                             VARCHAR (255)  NULL,
    [street]                               VARCHAR (255)  NULL,
    [city]                                 VARCHAR (255)  NULL,
    [email]                                VARCHAR (255)  NULL,
    [telephone]                            VARCHAR (255)  NULL,
    [country_id]                           VARCHAR (2)    NULL,
    [firstname]                            VARCHAR (255)  NULL,
    [address_type]                         VARCHAR (255)  NULL,
    [prefix]                               VARCHAR (255)  NULL,
    [middlename]                           VARCHAR (255)  NULL,
    [suffix]                               VARCHAR (255)  NULL,
    [company]                              VARCHAR (255)  NULL,
    [vat_id]                               VARCHAR (8000) NULL,
    [vat_is_valid]                         INT            NULL,
    [vat_request_id]                       VARCHAR (8000) NULL,
    [vat_request_date]                     VARCHAR (8000) NULL,
    [vat_request_success]                  INT            NULL,
    [giftregistry_item_id]                 INT            NULL,
    [dummy_modified_date_time]             DATETIME       NULL,
    [dv_batch_id]                          BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

