CREATE TABLE [dbo].[stage_spabiz_VENDOR] (
    [stage_spabiz_VENDOR_id] BIGINT          NOT NULL,
    [ID]                     DECIMAL (26, 6) NULL,
    [COUNTERID]              DECIMAL (26, 6) NULL,
    [STOREID]                DECIMAL (26, 6) NULL,
    [EDITTIME]               DATETIME        NULL,
    [Delete]                 DECIMAL (26, 6) NULL,
    [DELETEDATE]             DATETIME        NULL,
    [NAME]                   VARCHAR (150)   NULL,
    [QUICKID]                VARCHAR (150)   NULL,
    [PHONE]                  VARCHAR (150)   NULL,
    [FAX]                    VARCHAR (150)   NULL,
    [CONTACT1]               VARCHAR (150)   NULL,
    [CONTACT1TITLE]          VARCHAR (90)    NULL,
    [CONTACT1TEL]            VARCHAR (45)    NULL,
    [CONTACT1EXT]            VARCHAR (12)    NULL,
    [CONTACT2]               VARCHAR (150)   NULL,
    [CONTACT2TITLE]          VARCHAR (90)    NULL,
    [CONTACT2TEL]            VARCHAR (45)    NULL,
    [CONTACT2EXT]            VARCHAR (12)    NULL,
    [ORDERFREQ]              DECIMAL (26, 6) NULL,
    [POMETHOD]               DECIMAL (26, 6) NULL,
    [ADDRESS1]               VARCHAR (765)   NULL,
    [ADDRESS2]               VARCHAR (150)   NULL,
    [CITY]                   VARCHAR (150)   NULL,
    [ST]                     VARCHAR (150)   NULL,
    [ZIP]                    VARCHAR (150)   NULL,
    [EMAIL]                  VARCHAR (150)   NULL,
    [CUSTOMERNUM]            VARCHAR (150)   NULL,
    [DAY1]                   DECIMAL (26, 6) NULL,
    [DAY2]                   DECIMAL (26, 6) NULL,
    [DAY3]                   DECIMAL (26, 6) NULL,
    [DAY4]                   DECIMAL (26, 6) NULL,
    [DAY5]                   DECIMAL (26, 6) NULL,
    [DAY6]                   DECIMAL (26, 6) NULL,
    [DAY7]                   DECIMAL (26, 6) NULL,
    [WEEKEND]                DECIMAL (26, 6) NULL,
    [MONTHEND]               DECIMAL (26, 6) NULL,
    [STORE_NUMBER]           DECIMAL (26, 6) NULL,
    [NEWID]                  DECIMAL (26, 6) NULL,
    [VENDORBACKUPID]         DECIMAL (26, 6) NULL,
    [dv_batch_id]            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

