CREATE TABLE [dbo].[stage_udwcloudsync_ClubMasterRoster] (
    [stage_udwcloudsync_ClubMasterRoster_id] BIGINT          NOT NULL,
    [TwentyFourHourGuard]                    NVARCHAR (4000) NULL,
    [ThreeStory]                             BIT             NULL,
    [AccessType]                             NVARCHAR (4000) NULL,
    [ActivityCenter]                         NVARCHAR (4000) NULL,
    [AllowJuniorCheckInFlag]                 INT             NULL,
    [AppCreatedBy]                           NVARCHAR (4000) NULL,
    [AppModifiedBy]                          NVARCHAR (4000) NULL,
    [ApprovalStatus]                         NVARCHAR (4000) NULL,
    [ApproverComments]                       VARCHAR (8000)  NULL,
    [AquaticsDH]                             NVARCHAR (4000) NULL,
    [Area]                                   NVARCHAR (4000) NULL,
    [AreaDirector]                           NVARCHAR (4000) NULL,
    [AsstGeneralManager]                     NVARCHAR (4000) NULL,
    [AthleticLTA]                            BIT             NULL,
    [Attachments]                            NVARCHAR (4000) NULL,
    [BasketballCourts]                       INT             NULL,
    [BasketballTrainer]                      NVARCHAR (4000) NULL,
    [BuldingEngineer]                        NVARCHAR (4000) NULL,
    [BusinessAdministrator]                  NVARCHAR (4000) NULL,
    [Cafe]                                   NVARCHAR (4000) NULL,
    [CenterType]                             NVARCHAR (4000) NULL,
    [CheckInGroupLevel]                      NVARCHAR (4000) NULL,
    [ChildCenter]                            NVARCHAR (4000) NULL,
    [ChildCenterKidsActivitiesDH]            NVARCHAR (4000) NULL,
    [ChildCenterWeeklyLimit]                 INT             NULL,
    [CIGEndDate]                             DATETIME        NULL,
    [CIGStartDate]                           DATETIME        NULL,
    [CIGStatus]                              NVARCHAR (4000) NULL,
    [ClassesOffered]                         NVARCHAR (4000) NULL,
    [ClientID]                               NVARCHAR (4000) NULL,
    [Clinic]                                 NVARCHAR (4000) NULL,
    [ClubAddress]                            NVARCHAR (4000) NULL,
    [ClubID]                                 NVARCHAR (4000) NULL,
    [ClubDeactivationDate]                   DATETIME        NULL,
    [CognosName]                             NVARCHAR (4000) NULL,
    [ContentType]                            NVARCHAR (4000) NULL,
    [ContentTypeID]                          NVARCHAR (4000) NULL,
    [CopySource]                             NVARCHAR (4000) NULL,
    [Created]                                DATETIME        NULL,
    [CreatedDate]                            NVARCHAR (4000) NULL,
    [CreatedBy]                              NVARCHAR (4000) NULL,
    [CurrentOperationsStatus]                NVARCHAR (4000) NULL,
    [CycleStudios]                           INT             NULL,
    [DisplayUIFlag]                          NVARCHAR (4000) NULL,
    [Edit]                                   NVARCHAR (4000) NULL,
    [EditMenuTableEnd]                       NVARCHAR (4000) NULL,
    [EditMenuTableStart]                     NVARCHAR (4000) NULL,
    [EffectivePermissionsMask]               NVARCHAR (4000) NULL,
    [EGroupName]                             NVARCHAR (4000) NULL,
    [EmailAlert]                             NVARCHAR (4000) NULL,
    [EncodedAbsoluteURL]                     NVARCHAR (4000) NULL,
    [EngRCL]                                 NVARCHAR (4000) NULL,
    [FacilityOperationsDH]                   NVARCHAR (4000) NULL,
    [FacilityTechnician]                     NVARCHAR (4000) NULL,
    [FamilySwim]                             BIT             NULL,
    [FileName]                               NVARCHAR (4000) NULL,
    [FileType]                               NVARCHAR (4000) NULL,
    [FolderChildCount]                       NVARCHAR (4000) NULL,
    [FormalClubName]                         NVARCHAR (4000) NULL,
    [GeneralManager]                         NVARCHAR (4000) NULL,
    [GLCashEntryAccount]                     NVARCHAR (4000) NULL,
    [GLCashEntryCashSubAccount]              NVARCHAR (4000) NULL,
    [GLCashEntryCompanyName]                 NVARCHAR (4000) NULL,
    [GLCashEntryCreditCardSubAccount]        NVARCHAR (4000) NULL,
    [GLReceivablesEntryAccount]              NVARCHAR (4000) NULL,
    [GLReceivablesEntryCompanyName]          NVARCHAR (4000) NULL,
    [GLReceivablesEntrySubAccount]           NVARCHAR (4000) NULL,
    [GrandPrixTourLocation]                  NVARCHAR (4000) NULL,
    [GroupFitnessDH]                         NVARCHAR (4000) NULL,
    [GroupFitnessStudios]                    INT             NULL,
    [GrowthType]                             NVARCHAR (4000) NULL,
    [GUID]                                   VARCHAR (4000)  NULL,
    [HasCompanyDestinations]                 BIT             NULL,
    [HealthClubIdentifier]                   NVARCHAR (4000) NULL,
    [HTMLFileType]                           NVARCHAR (4000) NULL,
    [HyperionPlanning]                       NVARCHAR (4000) NULL,
    [ID]                                     INT             NULL,
    [IGStoreID]                              INT             NULL,
    [IndoorPool]                             NVARCHAR (4000) NULL,
    [IndoorPoolCloseDate]                    DATETIME        NULL,
    [IndoorPoolOpenDate]                     DATETIME        NULL,
    [IndoorTennisCourts]                     INT             NULL,
    [InstanceID]                             INT             NULL,
    [IsCurrentVersion]                       BIT             NULL,
    [ITCode]                                 NVARCHAR (4000) NULL,
    [ItemChildCount]                         NVARCHAR (4000) NULL,
    [ItemType]                               NVARCHAR (4000) NULL,
    [KidsAcademy]                            NVARCHAR (4000) NULL,
    [LapPools]                               NVARCHAR (4000) NULL,
    [latitide]                               NUMERIC (20, 9) NULL,
    [LeasesOwned]                            NVARCHAR (4000) NULL,
    [Level]                                  INT             NULL,
    [LifeCafeDH]                             NVARCHAR (4000) NULL,
    [LifeShop]                               NVARCHAR (4000) NULL,
    [LifeSpaDH]                              NVARCHAR (4000) NULL,
    [Longitude]                              NUMERIC (20, 9) NULL,
    [MapCenterLatitude]                      NUMERIC (10, 4) NULL,
    [MapCenterLongitude]                     NUMERIC (10, 4) NULL,
    [MapZoomLevel]                           INT             NULL,
    [MarketingClubName]                      NVARCHAR (4000) NULL,
    [MarketingClubLevel]                     NVARCHAR (4000) NULL,
    [MarketingMapRegion]                     NVARCHAR (4000) NULL,
    [MarketingMapXMLStateName]               NVARCHAR (4000) NULL,
    [MCAStudios]                             INT             NULL,
    [Medi]                                   NVARCHAR (4000) NULL,
    [MemberEngagementManager]                NVARCHAR (4000) NULL,
    [MemberServicesDH]                       NVARCHAR (4000) NULL,
    [MembershipLevel]                        NVARCHAR (4000) NULL,
    [MembershipLevelNeededForTennis]         NVARCHAR (4000) NULL,
    [MMSClubID]                              INT             NULL,
    [MMSClubName]                            NVARCHAR (4000) NULL,
    [Modified]                               DATETIME        NULL,
    [LastModified]                           NVARCHAR (4000) NULL,
    [ModifiedBy]                             NVARCHAR (4000) NULL,
    [Name_FileLeafRef]                       NVARCHAR (4000) NULL,
    [Name_LinkFilenameNoMenu]                NVARCHAR (4000) NULL,
    [Name_LinkFileName]                      NVARCHAR (4000) NULL,
    [Name_LinkFileName2]                     NVARCHAR (4000) NULL,
    [NumberofSlides]                         INT             NULL,
    [NutritionCoach]                         NVARCHAR (4000) NULL,
    [OldKronosID]                            NVARCHAR (4000) NULL,
    [Open24Hours]                            BIT             NULL,
    [Open]                                   NVARCHAR (4000) NULL,
    [OpenedDate]                             DATETIME        NULL,
    [OpsRCLSrDH]                             NVARCHAR (4000) NULL,
    [Order]                                  INT             NULL,
    [OriginatorID]                           NVARCHAR (4000) NULL,
    [OutDoorPool]                            NVARCHAR (4000) NULL,
    [OutDoorPoolCloseDate]                   DATETIME        NULL,
    [OutDoorPoolOpenDate]                    DATETIME        NULL,
    [OutDoorTennisCourts]                    INT             NULL,
    [Owshiddenversion]                       INT             NULL,
    [ParentsNightOut]                        BIT             NULL,
    [Path]                                   NVARCHAR (4000) NULL,
    [PersonalTrainingDH]                     NVARCHAR (4000) NULL,
    [PersonalTrainingRCM]                    NVARCHAR (4000) NULL,
    [PilatesStudio]                          INT             NULL,
    [PreSaleAddress]                         NVARCHAR (4000) NULL,
    [PriorYearOperationsStatus]              NVARCHAR (4000) NULL,
    [ProactiveCare]                          NVARCHAR (4000) NULL,
    [ProgId]                                 NVARCHAR (4000) NULL,
    [PropertyBag]                            NVARCHAR (4000) NULL,
    [PTRCMRegion]                            NVARCHAR (4000) NULL,
    [RacquetballCourts]                      INT             NULL,
    [RacquetballLeagueEndDate]               DATETIME        NULL,
    [RacquetballLeagueStartDate]             DATETIME        NULL,
    [Region]                                 NVARCHAR (4000) NULL,
    [RegionalSalesManager]                   NVARCHAR (4000) NULL,
    [RegionalVicePresident]                  NVARCHAR (4000) NULL,
    [Restricted]                             NVARCHAR (4000) NULL,
    [RockWall]                               NVARCHAR (4000) NULL,
    [SalesCode]                              NVARCHAR (4000) NULL,
    [SchoolBreakCamps]                       BIT             NULL,
    [ScopeId]                                NVARCHAR (4000) NULL,
    [SelectTitle]                            NVARCHAR (4000) NULL,
    [SeniorGeneralManager]                   NVARCHAR (4000) NULL,
    [ServerRelativeURL]                      NVARCHAR (4000) NULL,
    [SortType]                               NVARCHAR (4000) NULL,
    [Spa]                                    NVARCHAR (4000) NULL,
    [SquareFootage]                          INT             NULL,
    [SquashCourts]                           INT             NULL,
    [SquashKids]                             BIT             NULL,
    [State]                                  NVARCHAR (4000) NULL,
    [StateAbbreviation]                      NVARCHAR (4000) NULL,
    [SubnetAddress]                          NVARCHAR (4000) NULL,
    [SummerBreakCamps]                       BIT             NULL,
    [TennisCourts]                           NVARCHAR (4000) NULL,
    [TennisDH]                               NVARCHAR (4000) NULL,
    [Title]                                  NVARCHAR (4000) NULL,
    [Title_LinkTitleNoMenu]                  NVARCHAR (4000) NULL,
    [Title_LinkTitle]                        NVARCHAR (4000) NULL,
    [Title_LinkTitle2]                       NVARCHAR (4000) NULL,
    [TurfField]                              INT             NULL,
    [Type]                                   NVARCHAR (4000) NULL,
    [UIVersion]                              INT             NULL,
    [UniqueFeatures]                         NVARCHAR (4000) NULL,
    [UniqueID]                               NVARCHAR (4000) NULL,
    [URLPath]                                NVARCHAR (4000) NULL,
    [ValActivityAreaIDLookup]                NVARCHAR (4000) NULL,
    [ValActivityAreaIDLookupDescription]     NVARCHAR (4000) NULL,
    [ValCheckInGroupIDLookup]                NVARCHAR (4000) NULL,
    [ValCheckInGroupIDLookupDescription]     NVARCHAR (4000) NULL,
    [ValClubTypeIDLookUp]                    NVARCHAR (4000) NULL,
    [ValClubTypeIDLookUpDescription]         NVARCHAR (4000) NULL,
    [ValCountryIDLookup]                     NVARCHAR (4000) NULL,
    [ValCountryIDLookupTitle]                NVARCHAR (4000) NULL,
    [ValCurrencyCodeIDLookup]                NVARCHAR (4000) NULL,
    [ValCurrencyCodeIDLookupCurrencyCode]    NVARCHAR (4000) NULL,
    [ValCWRegionIDLookup]                    NVARCHAR (4000) NULL,
    [ValCWRegionIDLookupDescription]         NVARCHAR (4000) NULL,
    [ValEnrollmentTypeIDLookup]              NVARCHAR (4000) NULL,
    [ValEnrollmentTypeIDLookupDescription]   NVARCHAR (4000) NULL,
    [ValMemberActivityRegionIDLookup]        NVARCHAR (4000) NULL,
    [ValMemberActivityRegionIDLookupTitle]   NVARCHAR (4000) NULL,
    [ValPreSaleIDlookup]                     NVARCHAR (4000) NULL,
    [ValPreSaleIDlookupDescription]          NVARCHAR (4000) NULL,
    [ValPTRCLAreaIDLookup]                   NVARCHAR (4000) NULL,
    [ValPTRCLAreaIDLookupTitle]              NVARCHAR (4000) NULL,
    [ValRegionIDLookup]                      NVARCHAR (4000) NULL,
    [ValRegionIDLookupDescription]           NVARCHAR (4000) NULL,
    [ValSalesAreaIDlookup]                   NVARCHAR (4000) NULL,
    [ValSalesAreaIDlookupDescription]        NVARCHAR (4000) NULL,
    [ValStateIDLookup]                       NVARCHAR (4000) NULL,
    [ValStateIDLookupDescription]            NVARCHAR (4000) NULL,
    [ValTimeZoneIDLookup]                    NVARCHAR (4000) NULL,
    [ValTimeZoneIDLookupDescription]         NVARCHAR (4000) NULL,
    [Version]                                NVARCHAR (4000) NULL,
    [WaterSlides]                            NVARCHAR (4000) NULL,
    [Whirpools]                              INT             NULL,
    [WorkDayRegionID]                        NVARCHAR (4000) NULL,
    [WorkflowInstanceID]                     NVARCHAR (4000) NULL,
    [WorkFlowVersion]                        INT             NULL,
    [YogaStudios]                            INT             NULL,
    [ZeroDepthEntry]                         NVARCHAR (4000) NULL,
    [EditMenuTableStart2]                    NVARCHAR (4000) NULL,
    [AquaticsRegionalManager]                NVARCHAR (4000) NULL,
    [CafeRegionalManager]                    NVARCHAR (4000) NULL,
    [SpaRegionalManager]                     NVARCHAR (4000) NULL,
    [RacquetRegionalManager]                 NVARCHAR (4000) NULL,
    [PersonalTrainingRegionalManager]        NVARCHAR (4000) NULL,
    [KidsRegionalManager]                    NVARCHAR (4000) NULL,
    [OperationsRegionalManager]              NVARCHAR (4000) NULL,
    [SalesRegionalManager]                   NVARCHAR (4000) NULL,
    [GroupFitnessRegionalManager]            NVARCHAR (4000) NULL,
    [MemberServicesRegionalManager]          NVARCHAR (4000) NULL,
    [NutritionRegionalManager]               NVARCHAR (4000) NULL,
    [SpaBiz_StoreNum]                        INT             NULL,
    [dv_batch_id]                            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

