CREATE TABLE [dbo].[stage_spabiz_USER_SCHEDULER_JOBS] (
    [stage_spabiz_USER_SCHEDULER_JOBS_id] BIGINT          NOT NULL,
    [job_name]                            VARCHAR (30)    NULL,
    [job_subname]                         VARCHAR (30)    NULL,
    [job_style]                           VARCHAR (11)    NULL,
    [job_creator]                         VARCHAR (30)    NULL,
    [client_id]                           VARCHAR (64)    NULL,
    [global_uid]                          VARCHAR (32)    NULL,
    [program_owner]                       VARCHAR (4000)  NULL,
    [program_name]                        VARCHAR (4000)  NULL,
    [job_type]                            VARCHAR (16)    NULL,
    [job_action]                          VARCHAR (4000)  NULL,
    [number_of_arguments]                 DECIMAL (26, 6) NULL,
    [schedule_owner]                      VARCHAR (4000)  NULL,
    [schedule_name]                       VARCHAR (4000)  NULL,
    [schedule_type]                       VARCHAR (12)    NULL,
    [start_date]                          DATETIME        NULL,
    [repeat_interval]                     VARCHAR (4000)  NULL,
    [event_queue_owner]                   VARCHAR (30)    NULL,
    [event_queue_name]                    VARCHAR (30)    NULL,
    [event_queue_agent]                   VARCHAR (256)   NULL,
    [event_condition]                     VARCHAR (4000)  NULL,
    [event_rule]                          VARCHAR (65)    NULL,
    [file_watcher_owner]                  VARCHAR (65)    NULL,
    [file_watcher_name]                   VARCHAR (65)    NULL,
    [end_date]                            DATETIME        NULL,
    [job_class]                           VARCHAR (30)    NULL,
    [enabled]                             VARCHAR (5)     NULL,
    [auto_drop]                           VARCHAR (5)     NULL,
    [restartable]                         VARCHAR (5)     NULL,
    [state]                               VARCHAR (15)    NULL,
    [job_priority]                        DECIMAL (26, 6) NULL,
    [run_count]                           DECIMAL (26, 6) NULL,
    [max_runs]                            DECIMAL (26, 6) NULL,
    [failure_count]                       DECIMAL (26, 6) NULL,
    [max_failures]                        DECIMAL (26, 6) NULL,
    [retry_count]                         DECIMAL (26, 6) NULL,
    [last_start_date]                     DATETIME        NULL,
    [last_run_duration]                   VARCHAR (50)    NULL,
    [next_run_date]                       DATETIME        NULL,
    [schedule_limit]                      VARCHAR (50)    NULL,
    [max_run_duration]                    VARCHAR (50)    NULL,
    [logging_level]                       VARCHAR (11)    NULL,
    [stop_on_window_close]                VARCHAR (5)     NULL,
    [instance_stickiness]                 VARCHAR (5)     NULL,
    [raise_events]                        VARCHAR (4000)  NULL,
    [system]                              VARCHAR (5)     NULL,
    [job_weight]                          DECIMAL (26, 6) NULL,
    [nls_env]                             VARCHAR (4000)  NULL,
    [source]                              VARCHAR (128)   NULL,
    [number_of_destinations]              DECIMAL (26, 6) NULL,
    [destination_owner]                   VARCHAR (128)   NULL,
    [destination]                         VARCHAR (128)   NULL,
    [credential_owner]                    VARCHAR (30)    NULL,
    [credential_name]                     VARCHAR (30)    NULL,
    [instance_id]                         DECIMAL (26, 6) NULL,
    [deferred_drop]                       VARCHAR (5)     NULL,
    [allow_runs_in_restricted_mode]       VARCHAR (5)     NULL,
    [comments]                            VARCHAR (240)   NULL,
    [flags]                               DECIMAL (26, 6) NULL,
    [dv_batch_id]                         BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([dv_batch_id]));

