CREATE TABLE [dbo].[stage_mms_Membership] (
    [stage_mms_Membership_id]             BIGINT          NOT NULL,
    [MembershipID]                        INT             NULL,
    [ClubID]                              INT             NULL,
    [PurchaserID]                         INT             NULL,
    [LegacyCode]                          VARCHAR (12)    NULL,
    [AdvisorEmployeeID]                   INT             NULL,
    [ActivationDate]                      DATETIME        NULL,
    [ExpirationDate]                      DATETIME        NULL,
    [TotalContractAmount]                 DECIMAL (26, 6) NULL,
    [CompanyID]                           INT             NULL,
    [Comments]                            VARCHAR (255)   NULL,
    [MandatoryCommentFlag]                BIT             NULL,
    [ValEFTOptionID]                      INT             NULL,
    [ValEnrollmentTypeID]                 INT             NULL,
    [ValTerminationReasonID]              INT             NULL,
    [MembershipTypeID]                    INT             NULL,
    [ValMembershipStatusID]               INT             NULL,
    [CancellationRequestDate]             DATETIME        NULL,
    [CreatedDateTime]                     DATETIME        NULL,
    [UTCCreatedDateTime]                  DATETIME        NULL,
    [CreatedDateTimeZone]                 VARCHAR (4)     NULL,
    [InsertedDateTime]                    DATETIME        NULL,
    [ValMembershipSourceID]               INT             NULL,
    [UpdatedDateTime]                     DATETIME        NULL,
    [PromotionID]                         INT             NULL,
    [JrMemberDuesProductID]               INT             NULL,
    [Salesforce_Prospect_ID]              VARCHAR (18)    NULL,
    [MoneyBackCancelPolicyDays]           INT             NULL,
    [LastUpdatedEmployeeID]               INT             NULL,
    [QualifiedSalesPromotionID]           INT             NULL,
    [JoinFeePaid]                         DECIMAL (26, 6) NULL,
    [Salesforce_Account_ID]               VARCHAR (18)    NULL,
    [Salesforce_Opportunity_ID]           VARCHAR (18)    NULL,
    [ChildCenterUnrestrictedCheckoutFlag] BIT             NULL,
    [ValTerminationReasonClubTypeID]      INT             NULL,
    [CRMOpportunityID]                    VARCHAR (36)    NULL,
    [CurrentPrice]                        DECIMAL (26, 6) NULL,
    [PriorPlusPrice]                      DECIMAL (26, 6) NULL,
    [PriorPlusMembershipTypeID]           INT             NULL,
    [CRMAccountID]                        VARCHAR (36)    NULL,
    [OverdueRecurrentProductBalanceFlag]  BIT             NULL,
    [BlockRecurrentProductRenewalFlag]    BIT             NULL,
    [ValEFTOptionProductID]               TINYINT         NULL,
    [UndiscountedPrice]                   DECIMAL (26, 6) NULL,
    [PriorPlusUndiscountedPrice]          DECIMAL (26, 6) NULL,
    [dv_batch_id]                         BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

