CREATE TABLE [dbo].[stage_spabiz_DBA_SCHEDULER_JOBS] (
    [stage_spabiz_DBA_SCHEDULER_JOBS_id] BIGINT          NOT NULL,
    [OWNER]                              VARCHAR (30)    NULL,
    [JOB_NAME]                           VARCHAR (30)    NULL,
    [JOB_SUBNAME]                        VARCHAR (30)    NULL,
    [JOB_STYLE]                          VARCHAR (11)    NULL,
    [JOB_CREATOR]                        VARCHAR (30)    NULL,
    [CLIENT_ID]                          VARCHAR (64)    NULL,
    [GLOBAL_UID]                         VARCHAR (32)    NULL,
    [PROGRAM_OWNER]                      VARCHAR (4000)  NULL,
    [PROGRAM_NAME]                       VARCHAR (4000)  NULL,
    [JOB_TYPE]                           VARCHAR (16)    NULL,
    [JOB_ACTION]                         VARCHAR (4000)  NULL,
    [NUMBER_OF_ARGUMENTS]                DECIMAL (26, 6) NULL,
    [SCHEDULE_OWNER]                     VARCHAR (4000)  NULL,
    [SCHEDULE_NAME]                      VARCHAR (4000)  NULL,
    [SCHEDULE_TYPE]                      VARCHAR (12)    NULL,
    [START_DATE]                         DATETIME        NULL,
    [REPEAT_INTERVAL]                    VARCHAR (4000)  NULL,
    [EVENT_QUEUE_OWNER]                  VARCHAR (30)    NULL,
    [EVENT_QUEUE_NAME]                   VARCHAR (30)    NULL,
    [EVENT_QUEUE_AGENT]                  VARCHAR (256)   NULL,
    [EVENT_CONDITION]                    VARCHAR (4000)  NULL,
    [EVENT_RULE]                         VARCHAR (65)    NULL,
    [FILE_WATCHER_OWNER]                 VARCHAR (65)    NULL,
    [FILE_WATCHER_NAME]                  VARCHAR (65)    NULL,
    [END_DATE]                           DATETIME        NULL,
    [JOB_CLASS]                          VARCHAR (30)    NULL,
    [ENABLED]                            VARCHAR (5)     NULL,
    [AUTO_DROP]                          VARCHAR (5)     NULL,
    [RESTARTABLE]                        VARCHAR (5)     NULL,
    [STATE]                              VARCHAR (15)    NULL,
    [JOB_PRIORITY]                       DECIMAL (26, 6) NULL,
    [RUN_COUNT]                          DECIMAL (26, 6) NULL,
    [MAX_RUNS]                           DECIMAL (26, 6) NULL,
    [FAILURE_COUNT]                      DECIMAL (26, 6) NULL,
    [MAX_FAILURES]                       DECIMAL (26, 6) NULL,
    [RETRY_COUNT]                        DECIMAL (26, 6) NULL,
    [LAST_START_DATE]                    DATETIME        NULL,
    [LAST_RUN_DURATION]                  VARCHAR (50)    NULL,
    [NEXT_RUN_DATE]                      DATETIME        NULL,
    [SCHEDULE_LIMIT]                     VARCHAR (50)    NULL,
    [MAX_RUN_DURATION]                   VARCHAR (50)    NULL,
    [LOGGING_LEVEL]                      VARCHAR (11)    NULL,
    [STOP_ON_WINDOW_CLOSE]               VARCHAR (5)     NULL,
    [INSTANCE_STICKINESS]                VARCHAR (5)     NULL,
    [RAISE_EVENTS]                       VARCHAR (4000)  NULL,
    [SYSTEM]                             VARCHAR (5)     NULL,
    [JOB_WEIGHT]                         DECIMAL (26, 6) NULL,
    [NLS_ENV]                            VARCHAR (4000)  NULL,
    [SOURCE]                             VARCHAR (128)   NULL,
    [NUMBER_OF_DESTINATIONS]             DECIMAL (26, 6) NULL,
    [DESTINATION_OWNER]                  VARCHAR (128)   NULL,
    [DESTINATION]                        VARCHAR (128)   NULL,
    [CREDENTIAL_OWNER]                   VARCHAR (30)    NULL,
    [CREDENTIAL_NAME]                    VARCHAR (30)    NULL,
    [INSTANCE_ID]                        DECIMAL (26, 6) NULL,
    [DEFERRED_DROP]                      VARCHAR (5)     NULL,
    [ALLOW_RUNS_IN_RESTRICTED_MODE]      VARCHAR (5)     NULL,
    [COMMENTS]                           VARCHAR (240)   NULL,
    [FLAGS]                              DECIMAL (26, 6) NULL,
    [dv_batch_id]                        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([dv_batch_id]));

