CREATE TABLE [dbo].[stage_magento_sales_invoice_item] (
    [stage_magento_sales_invoice_item_id]   BIGINT          NOT NULL,
    [entity_id]                             INT             NULL,
    [parent_id]                             INT             NULL,
    [base_price]                            DECIMAL (12, 4) NULL,
    [tax_amount]                            DECIMAL (12, 4) NULL,
    [base_row_total]                        DECIMAL (12, 4) NULL,
    [discount_amount]                       DECIMAL (12, 4) NULL,
    [row_total]                             DECIMAL (12, 4) NULL,
    [base_discount_amount]                  DECIMAL (12, 4) NULL,
    [price_incl_tax]                        DECIMAL (12, 4) NULL,
    [base_tax_amount]                       DECIMAL (12, 4) NULL,
    [base_price_incl_tax]                   DECIMAL (12, 4) NULL,
    [qty]                                   DECIMAL (12, 4) NULL,
    [base_cost]                             DECIMAL (12, 4) NULL,
    [price]                                 DECIMAL (12, 4) NULL,
    [base_row_total_incl_tax]               DECIMAL (12, 4) NULL,
    [row_total_incl_tax]                    DECIMAL (12, 4) NULL,
    [product_id]                            INT             NULL,
    [order_item_id]                         INT             NULL,
    [additional_data]                       VARCHAR (8000)  NULL,
    [description]                           VARCHAR (8000)  NULL,
    [sku]                                   VARCHAR (255)   NULL,
    [name]                                  VARCHAR (255)   NULL,
    [discount_tax_compensation_amount]      DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount] DECIMAL (12, 4) NULL,
    [tax_ratio]                             VARCHAR (8000)  NULL,
    [weee_tax_applied]                      VARCHAR (8000)  NULL,
    [weee_tax_applied_amount]               DECIMAL (12, 4) NULL,
    [weee_tax_applied_row_amount]           DECIMAL (12, 4) NULL,
    [weee_tax_disposition]                  DECIMAL (12, 4) NULL,
    [weee_tax_row_disposition]              DECIMAL (12, 4) NULL,
    [base_weee_tax_applied_amount]          DECIMAL (12, 4) NULL,
    [base_weee_tax_applied_row_amnt]        DECIMAL (12, 4) NULL,
    [base_weee_tax_disposition]             DECIMAL (12, 4) NULL,
    [base_weee_tax_row_disposition]         DECIMAL (12, 4) NULL,
    [dummy_modified_date_time]              DATETIME        NULL,
    [dv_batch_id]                           BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

