CREATE TABLE [dbo].[stage_spabiz_AP] (
    [stage_spabiz_AP_id] BIGINT          NOT NULL,
    [ID]                 DECIMAL (26, 6) NULL,
    [COUNTERID]          DECIMAL (26, 6) NULL,
    [STOREID]            DECIMAL (26, 6) NULL,
    [EDITTIME]           DATETIME        NULL,
    [CUSTID]             DECIMAL (26, 6) NULL,
    [Date]               DATETIME        NULL,
    [DATECUST]           VARCHAR (150)   NULL,
    [STATUS]             DECIMAL (26, 6) NULL,
    [DATESTATUS]         VARCHAR (150)   NULL,
    [CHECKINTIME]        DATETIME        NULL,
    [STAFFID]            DECIMAL (26, 6) NULL,
    [STARTTIME]          DATETIME        NULL,
    [LATE]               DECIMAL (26, 6) NULL,
    [TICKETID]           DECIMAL (26, 6) NULL,
    [STATUSOLD]          DECIMAL (26, 6) NULL,
    [BOOKSTAFFID]        DECIMAL (26, 6) NULL,
    [BOOKTIME]           DATETIME        NULL,
    [MEMO]               VARCHAR (3000)  NULL,
    [Delete]             DECIMAL (26, 6) NULL,
    [TIMEID]             DECIMAL (26, 6) NULL,
    [STANDING]           DECIMAL (26, 6) NULL,
    [ALTCUSTID]          VARCHAR (18)    NULL,
    [ALTSERVICEID]       VARCHAR (150)   NULL,
    [STORE_NUMBER]       DECIMAL (26, 6) NULL,
    [CONFIRMID]          DECIMAL (26, 6) NULL,
    [STARTBOOKING]       DATETIME        NULL,
    [STOPBOOKING]        DATETIME        NULL,
    [UPSELL]             DECIMAL (26, 6) NULL,
    [STOREID2]           DECIMAL (26, 6) NULL,
    [ACTIVITYID]         DECIMAL (26, 6) NULL,
    [NOSHOW]             DECIMAL (26, 6) NULL,
    [APPOINTMENTTYPE]    DECIMAL (26, 6) NULL,
    [dv_batch_id]        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

