CREATE EXTERNAL FILE FORMAT [Informatica_eaae31a1_e9c7_4eb4_bf82_33e6eba3d6d4FF]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'0x1e', ENCODING = N'UTF8')
    );

