CREATE EXTERNAL FILE FORMAT [Informatica_8e6239c3_d535_4bdf_bae2_dfd794ea4c88FF]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'0x1e', STRING_DELIMITER = N'0x1f', FIRST_ROW = 1, ENCODING = N'UTF8')
    );

