CREATE EXTERNAL FILE FORMAT [Informatica_7ef161c9_dedf_4500_a47e_f0e9ae7459c5FF]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'0x1e', STRING_DELIMITER = N'0x1f', FIRST_ROW = 1, ENCODING = N'UTF8')
    );

