CREATE TABLE [dbo].[s_athlinks_api_vw_athlete_non_member] (
    [s_athlinks_api_vw_athlete_non_member_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)      NOT NULL,
    [racer_id]                                INT            NULL,
    [f_name]                                  NVARCHAR (255) NULL,
    [l_name]                                  NVARCHAR (255) NULL,
    [display_name]                            NVARCHAR (255) NULL,
    [age]                                     INT            NULL,
    [gender]                                  CHAR (1)       NULL,
    [city]                                    NVARCHAR (255) NULL,
    [state_prov_id]                           NVARCHAR (255) NULL,
    [state_prov_name]                         NVARCHAR (255) NULL,
    [state_prov_abbrev]                       NVARCHAR (255) NULL,
    [country_id]                              CHAR (2)       NULL,
    [country_id_3]                            CHAR (3)       NULL,
    [country_name]                            NVARCHAR (255) NULL,
    [photo_path]                              VARCHAR (255)  NULL,
    [join_date]                               DATETIME       NULL,
    [notes]                                   VARCHAR (255)  NULL,
    [owner_id]                                INT            NULL,
    [is_member]                               VARCHAR (1)    NULL,
    [result_count]                            INT            NULL,
    [create_date]                             DATETIME       NULL,
    [dv_load_date_time]                       DATETIME       NOT NULL,
    [dv_r_load_source_id]                     BIGINT         NOT NULL,
    [dv_inserted_date_time]                   DATETIME       NOT NULL,
    [dv_insert_user]                          VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                    DATETIME       NULL,
    [dv_update_user]                          VARCHAR (50)   NULL,
    [dv_hash]                                 CHAR (32)      NOT NULL,
    [dv_deleted]                              BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                             BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

