CREATE TABLE [dbo].[s_athlinks_api_vw_master_event] (
    [s_athlinks_api_vw_master_event_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)       NOT NULL,
    [master_id]                         INT             NULL,
    [name]                              NVARCHAR (128)  NULL,
    [short_url]                         VARCHAR (128)   NULL,
    [race_count]                        INT             NULL,
    [result_count]                      INT             NULL,
    [logo_path]                         NVARCHAR (512)  NULL,
    [status]                            INT             NULL,
    [contact_name]                      NVARCHAR (256)  NULL,
    [phone]                             NVARCHAR (100)  NULL,
    [contact_address]                   NVARCHAR (1000) NULL,
    [longitude]                         DECIMAL (26, 6) NULL,
    [latitude]                          DECIMAL (26, 6) NULL,
    [geo]                               VARCHAR (4000)  NULL,
    [elevation]                         INT             NULL,
    [city]                              NVARCHAR (128)  NULL,
    [state_prov_id]                     NVARCHAR (8)    NULL,
    [company_name]                      NVARCHAR (50)   NULL,
    [state_prov_abbrev]                 NVARCHAR (8)    NULL,
    [country_id]                        CHAR (2)        NULL,
    [next_date]                         DATETIME        NULL,
    [prev_date]                         DATETIME        NULL,
    [curated_desc]                      NVARCHAR (1000) NULL,
    [featured]                          BIT             NULL,
    [create_date]                       DATETIME        NULL,
    [dv_load_date_time]                 DATETIME        NOT NULL,
    [dv_r_load_source_id]               BIGINT          NOT NULL,
    [dv_inserted_date_time]             DATETIME        NOT NULL,
    [dv_insert_user]                    VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]              DATETIME        NULL,
    [dv_update_user]                    VARCHAR (50)    NULL,
    [dv_hash]                           CHAR (32)       NOT NULL,
    [dv_deleted]                        BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

