CREATE TABLE [dbo].[s_athlinks_api_vw_race_ltf_data] (
    [s_athlinks_api_vw_race_ltf_data_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                            CHAR (32)       NOT NULL,
    [race_id]                            INT             NULL,
    [race_name]                          NVARCHAR (256)  NULL,
    [race_date]                          DATETIME        NULL,
    [race_end_date]                      DATETIME        NULL,
    [city]                               NVARCHAR (128)  NULL,
    [state_prov_id]                      NVARCHAR (8)    NULL,
    [state_prov_name]                    NVARCHAR (70)   NULL,
    [state_prov_abbrev]                  NVARCHAR (8)    NULL,
    [country_id]                         CHAR (2)        NULL,
    [country_id_3]                       CHAR (3)        NULL,
    [country_name]                       NVARCHAR (64)   NULL,
    [date_sort]                          VARCHAR (8)     NULL,
    [website]                            NVARCHAR (256)  NULL,
    [status]                             INT             NULL,
    [elevation]                          INT             NULL,
    [result_count]                       INT             NULL,
    [latitude]                           DECIMAL (26, 6) NULL,
    [longitude]                          DECIMAL (26, 6) NULL,
    [temperature]                        INT             NULL,
    [weather_notes]                      NVARCHAR (512)  NULL,
    [create_date]                        DATETIME        NULL,
    [dv_load_date_time]                  DATETIME        NOT NULL,
    [dv_r_load_source_id]                BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL,
    [dv_hash]                            CHAR (32)       NOT NULL,
    [dv_deleted]                         BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

