CREATE TABLE [dbo].[s_boss_asi_reserv] (
    [s_boss_asi_reserv_id]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]               CHAR (32)       NOT NULL,
    [reservation]           INT             NULL,
    [trainer_mbr_code]      CHAR (10)       NULL,
    [reserve_type]          CHAR (1)        NULL,
    [start_date]            SMALLDATETIME   NULL,
    [end_date]              SMALLDATETIME   NULL,
    [session_id]            CHAR (15)       NULL,
    [program_id]            CHAR (25)       NULL,
    [def_price]             DECIMAL (26, 6) NULL,
    [instructor]            CHAR (20)       NULL,
    [billing_count]         SMALLINT        NULL,
    [status]                CHAR (1)        NULL,
    [free_date]             SMALLDATETIME   NULL,
    [qoh]                   SMALLINT        NULL,
    [limit]                 SMALLINT        NULL,
    [recurring]             CHAR (1)        NULL,
    [color]                 INT             NULL,
    [shape]                 INT             NULL,
    [comment]               NCHAR (40)      NULL,
    [resource]              CHAR (25)       NULL,
    [create_date]           DATETIME        NULL,
    [min_limit]             INT             NULL,
    [non_mbr_price]         DECIMAL (26, 6) NULL,
    [ical_recur_rule]       VARCHAR (150)   NULL,
    [upc_desc]              CHAR (40)       NULL,
    [respect_holidays]      BIT             NULL,
    [origin]                CHAR (1)        NULL,
    [print_desc]            CHAR (40)       NULL,
    [day_plan_string]       VARCHAR (21)    NULL,
    [day_plan_ints]         VARCHAR (14)    NULL,
    [publish]               CHAR (1)        NULL,
    [web_register]          CHAR (1)        NULL,
    [target]                INT             NULL,
    [class_expense]         DECIMAL (26, 6) NULL,
    [instructor_expense]    DECIMAL (26, 6) NULL,
    [age_low]               INT             NULL,
    [age_high]              INT             NULL,
    [web_purchase]          CHAR (1)        NULL,
    [payment_freq]          VARCHAR (1)     NULL,
    [last_modified]         DATETIME        NULL,
    [waiver_reqd]           CHAR (1)        NULL,
    [deposit_amt]           DECIMAL (26, 6) NULL,
    [payment_reqd_days]     INT             NULL,
    [pre_assgn_instr_cnt]   INT             NULL,
    [grace_days]            INT             NULL,
    [continuous]            CHAR (1)        NULL,
    [allow_wait_list]       CHAR (1)        NULL,
    [use_for_LT_Bucks]      CHAR (1)        NULL,
    [cancel_dates]          CHAR (222)      NULL,
    [published_duration]    INT             NULL,
    [dv_load_date_time]     DATETIME        NOT NULL,
    [dv_r_load_source_id]   BIGINT          NOT NULL,
    [dv_inserted_date_time] DATETIME        NOT NULL,
    [dv_insert_user]        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]  DATETIME        NULL,
    [dv_update_user]        VARCHAR (50)    NULL,
    [dv_hash]               CHAR (32)       NOT NULL,
    [dv_deleted]            BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]           BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_boss_asi_reserv]([dv_batch_id] ASC);

