CREATE TABLE [dbo].[s_chronotrack_athlete] (
    [s_chronotrack_athlete_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                  CHAR (32)      NOT NULL,
    [athlete_id]               BIGINT         NULL,
    [first_name]               NVARCHAR (40)  NULL,
    [middle_name]              NVARCHAR (40)  NULL,
    [last_name]                NVARCHAR (40)  NULL,
    [name_pronunciation]       NVARCHAR (255) NULL,
    [sex]                      NCHAR (13)     NULL,
    [birth_date]               DATE           NULL,
    [age]                      TINYINT        NULL,
    [tshirt_size]              NVARCHAR (15)  NULL,
    [usat_num]                 NVARCHAR (36)  NULL,
    [home_phone]               NVARCHAR (20)  NULL,
    [mobile_phone]             NVARCHAR (20)  NULL,
    [email]                    NVARCHAR (255) NULL,
    [emerg_name]               NVARCHAR (50)  NULL,
    [emerg_phone]              NVARCHAR (20)  NULL,
    [emerg_relationship]       NVARCHAR (255) NULL,
    [medical_notes]            VARCHAR (4000) NULL,
    [create_time]              INT            NULL,
    [modified_time]            INT            NULL,
    [dummy_modified_date_time] DATETIME       NULL,
    [dv_load_date_time]        DATETIME       NOT NULL,
    [dv_r_load_source_id]      BIGINT         NOT NULL,
    [dv_inserted_date_time]    DATETIME       NOT NULL,
    [dv_insert_user]           VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]     DATETIME       NULL,
    [dv_update_user]           VARCHAR (50)   NULL,
    [dv_hash]                  CHAR (32)      NOT NULL,
    [dv_deleted]               BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]              BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

