CREATE TABLE [dbo].[s_crmcloudsync_ltf_club] (
    [s_crmcloudsync_ltf_club_id]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)       NOT NULL,
    [created_by_name]                         NVARCHAR (200)  NULL,
    [created_by_yomi_name]                    NVARCHAR (200)  NULL,
    [created_on]                              DATETIME        NULL,
    [created_on_behalf_by_name]               NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]          NVARCHAR (200)  NULL,
    [import_sequence_number]                  INT             NULL,
    [ltf_address_1_address_type_code]         INT             NULL,
    [ltf_address_1_address_type_code_name]    NVARCHAR (255)  NULL,
    [ltf_address_1_city]                      NVARCHAR (50)   NULL,
    [ltf_address_1_country]                   NVARCHAR (50)   NULL,
    [ltf_address_1_county]                    NVARCHAR (50)   NULL,
    [ltf_address_1_fax]                       NVARCHAR (50)   NULL,
    [ltf_address_1_latitude]                  DECIMAL (26, 6) NULL,
    [ltf_address_1_line_1]                    NVARCHAR (50)   NULL,
    [ltf_address_1_line_2]                    NVARCHAR (50)   NULL,
    [ltf_address_1_line_3]                    NVARCHAR (50)   NULL,
    [ltf_address_1_longitude]                 DECIMAL (26, 6) NULL,
    [ltf_address_1_name]                      INT             NULL,
    [ltf_address_1_name_name]                 NVARCHAR (255)  NULL,
    [ltf_address_1_postal_code]               NVARCHAR (20)   NULL,
    [ltf_address_1_post_office_box]           NVARCHAR (20)   NULL,
    [ltf_address_1_shipping_method_code]      INT             NULL,
    [ltf_address_1_shipping_method_code_name] NVARCHAR (255)  NULL,
    [ltf_address_1_state_or_province]         NVARCHAR (50)   NULL,
    [ltf_address_1_telephone_1]               NVARCHAR (50)   NULL,
    [ltf_address_1_telephone_2]               NVARCHAR (50)   NULL,
    [ltf_address_1_telephone_3]               NVARCHAR (50)   NULL,
    [ltf_address_1_ups_zone]                  NVARCHAR (4)    NULL,
    [ltf_address_1_utc_offset]                INT             NULL,
    [ltf_address_2_address_type_code]         INT             NULL,
    [ltf_address_2_address_type_code_name]    NVARCHAR (255)  NULL,
    [ltf_address_2_city]                      NVARCHAR (50)   NULL,
    [ltf_address_2_country]                   NVARCHAR (50)   NULL,
    [ltf_address_2_county]                    NVARCHAR (50)   NULL,
    [ltf_address_2_fax]                       NVARCHAR (50)   NULL,
    [ltf_address_2_latitude]                  DECIMAL (26, 6) NULL,
    [ltf_address_2_line_1]                    NVARCHAR (50)   NULL,
    [ltf_address_2_line_2]                    NVARCHAR (50)   NULL,
    [ltf_address_2_line_3]                    NVARCHAR (50)   NULL,
    [ltf_address_2_longitude]                 DECIMAL (26, 6) NULL,
    [ltf_address_2_name]                      INT             NULL,
    [ltf_address_2_name_name]                 NVARCHAR (255)  NULL,
    [ltf_address_2_postal_code]               NVARCHAR (20)   NULL,
    [ltf_address_2_post_office_box]           NVARCHAR (20)   NULL,
    [ltf_address_2_shipping_method_code]      INT             NULL,
    [ltf_address_2_shipping_method_code_name] NVARCHAR (255)  NULL,
    [ltf_address_2_state_or_province]         NVARCHAR (50)   NULL,
    [ltf_address_2_telephone_1]               NVARCHAR (50)   NULL,
    [ltf_address_2_telephone_2]               NVARCHAR (50)   NULL,
    [ltf_address_2_telephone_3]               NVARCHAR (50)   NULL,
    [ltf_address_2_ups_zone]                  NVARCHAR (4)    NULL,
    [ltf_address_2_utc_off_set]               INT             NULL,
    [ltf_buddy_referral]                      BIT             NULL,
    [ltf_buddy_referral_name]                 NVARCHAR (255)  NULL,
    [ltf_club_division_name]                  NVARCHAR (160)  NULL,
    [ltf_club_id]                             VARCHAR (36)    NULL,
    [ltf_club_regional_manager_name]          NVARCHAR (200)  NULL,
    [ltf_club_regional_manager_yomi_name]     NVARCHAR (200)  NULL,
    [ltf_club_regionname]                     NVARCHAR (160)  NULL,
    [ltf_clubs_id_name]                       NVARCHAR (160)  NULL,
    [ltf_club_team_id_name]                   NVARCHAR (160)  NULL,
    [ltf_club_team_id_yomi_name]              NVARCHAR (160)  NULL,
    [ltf_contact_us]                          BIT             NULL,
    [ltf_contact_us_name]                     NVARCHAR (255)  NULL,
    [ltf_email_address]                       NVARCHAR (100)  NULL,
    [ltf_enable_my_lt_referral]               BIT             NULL,
    [ltf_enable_my_lt_referral_name]          NVARCHAR (255)  NULL,
    [ltf_five_letter_club_code]               NVARCHAR (5)    NULL,
    [ltf_four_letter_club_code]               NVARCHAR (4)    NULL,
    [ltf_general_manager_name]                NVARCHAR (200)  NULL,
    [ltf_general_manager_yomi_name]           NVARCHAR (200)  NULL,
    [ltf_guest_pass_duration]                 INT             NULL,
    [ltf_guest_pass_duration_name]            NVARCHAR (255)  NULL,
    [ltf_lt_health_club]                      BIT             NULL,
    [ltf_lt_health_club_name]                 NVARCHAR (255)  NULL,
    [ltf_membership_levels_available]         INT             NULL,
    [ltf_membership_levels_available_name]    NVARCHAR (255)  NULL,
    [ltf_mem_name]                            NVARCHAR (200)  NULL,
    [ltf_mem_yomi_name]                       NVARCHAR (200)  NULL,
    [ltf_mms_club_name]                       NVARCHAR (50)   NULL,
    [ltf_name]                                NVARCHAR (100)  NULL,
    [ltf_npt_rep_name]                        NVARCHAR (200)  NULL,
    [ltf_npt_rep_yomi_name]                   NVARCHAR (200)  NULL,
    [ltf_pdth_name]                           NVARCHAR (200)  NULL,
    [ltf_pdth_yomi_name]                      NVARCHAR (200)  NULL,
    [ltf_price_request]                       BIT             NULL,
    [ltf_price_request_name]                  NVARCHAR (255)  NULL,
    [ltf_region_code]                         NVARCHAR (50)   NULL,
    [ltf_time_zone_code]                      INT             NULL,
    [ltf_web_inquiry]                         BIT             NULL,
    [ltf_web_inquiry_name]                    NVARCHAR (255)  NULL,
    [ltf_web_referral_pass]                   BIT             NULL,
    [ltf_web_referral_passname]               NVARCHAR (255)  NULL,
    [ltf_web_site_club_name]                  NVARCHAR (50)   NULL,
    [ltf_web_specialist_team_name]            NVARCHAR (160)  NULL,
    [ltf_web_specialist_team_yomi_name]       NVARCHAR (160)  NULL,
    [modified_by_name]                        NVARCHAR (200)  NULL,
    [modified_by_yominame]                    NVARCHAR (200)  NULL,
    [modified_on]                             DATETIME        NULL,
    [modified_on_behalf_by_name]              NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]         NVARCHAR (200)  NULL,
    [organization_id_name]                    NVARCHAR (160)  NULL,
    [overridden_created_on]                   DATETIME        NULL,
    [state_code]                              INT             NULL,
    [state_code_name]                         NVARCHAR (255)  NULL,
    [status_code]                             INT             NULL,
    [status_code_name]                        NVARCHAR (255)  NULL,
    [time_zone_rule_version_number]           INT             NULL,
    [utc_conversion_time_zone_code]           INT             NULL,
    [version_number]                          BIGINT          NULL,
    [inserted_date_time]                      DATETIME        NULL,
    [insert_user]                             VARCHAR (100)   NULL,
    [updated_date_time]                       DATETIME        NULL,
    [update_user]                             VARCHAR (50)    NULL,
    [ltf_accepting_presales_leads]            BIT             NULL,
    [ltf_area_director_name]                  NVARCHAR (200)  NULL,
    [ltf_area_director_yomi_name]             NVARCHAR (200)  NULL,
    [ltf_call_curents_ucle]                   INT             NULL,
    [ltf_call_curents_ucle_date]              DATETIME        NULL,
    [ltf_call_curents_ucle_state]             INT             NULL,
    [ltf_cig_user_name]                       NVARCHAR (200)  NULL,
    [ltf_cig_user_yomi_name]                  NVARCHAR (200)  NULL,
    [ltf_club_brand_name]                     NVARCHAR (100)  NULL,
    [ltf_club_marketing_name]                 NVARCHAR (100)  NULL,
    [ltf_disable_web_transfer]                BIT             NULL,
    [ltf_disable_web_transfer_name]           NVARCHAR (255)  NULL,
    [ltf_old_team_name]                       NVARCHAR (160)  NULL,
    [ltf_old_team_yomi_name]                  NVARCHAR (160)  NULL,
    [ltf_parent_territory_id_name]            NVARCHAR (200)  NULL,
    [ltf_pre_sale]                            BIT             NULL,
    [ltf_regional_sales_lead_name]            NVARCHAR (200)  NULL,
    [ltf_regional_sales_lead_yomi_name]       NVARCHAR (200)  NULL,
    [ltf_regional_vice_president_name]        NVARCHAR (200)  NULL,
    [ltf_regional_vice_president_yomi_name]   NVARCHAR (200)  NULL,
    [ltf_sr_mem_name]                         NVARCHAR (200)  NULL,
    [ltf_sr_mem_yomi_name]                    NVARCHAR (200)  NULL,
    [ltf_territory_id_name]                   NVARCHAR (200)  NULL,
    [ltf_web_team_line]                       NVARCHAR (20)   NULL,
    [ltf_accepting_presales_leads_name]       NVARCHAR (255)  NULL,
    [ltf_presale_name]                        NVARCHAR (255)  NULL,
    [ltf_buddy_reset_days]                    INT             NULL,
    [ltf_exclude_from_expiration]             BIT             NULL,
    [ltf_max_pass_days]                       INT             NULL,
    [ltf_passs_canner_active]                 BIT             NULL,
    [ltf_online_join_link]                    INT             NULL,
    [ltf_kid_memberships]                     BIT             NULL,
    [ltf_buddy_reset_period]                  INT             NULL,
    [ltf_restricted_guest_pass_policy]        BIT             NULL,
    [ltf_restricted_pass_reset_period]        BIT             NULL,
    [ltf_restricted_pass_reset_units]         INT             NULL,
    [ltf_restricted_pass_grace_period]        BIT             NULL,
    [ltf_restricted_pass_grace_units]         BIT             NULL,
    [ltf_web_guest_pass_process]              BIT             NULL,
    [ltf_lt_work_email]                       INT             NULL,
    [dv_load_date_time]                       DATETIME        NOT NULL,
    [dv_r_load_source_id]                     BIGINT          NOT NULL,
    [dv_inserted_date_time]                   DATETIME        NOT NULL,
    [dv_insert_user]                          VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                    DATETIME        NULL,
    [dv_update_user]                          VARCHAR (50)    NULL,
    [dv_hash]                                 CHAR (32)       NOT NULL,
    [dv_batch_id]                             BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_ltf_club]([dv_batch_id] ASC);

