CREATE TABLE [dbo].[s_crmcloudsync_ltf_do_not_contact_store] (
    [s_crmcloudsync_ltf_do_not_contact_store_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                    CHAR (32)      NOT NULL,
    [created_by_name]                            NVARCHAR (200) NULL,
    [created_by_yomi_name]                       NVARCHAR (200) NULL,
    [createdon]                                  DATETIME       NULL,
    [created_on_behalf_by]                       VARCHAR (36)   NULL,
    [created_on_behalf_by_name]                  NVARCHAR (200) NULL,
    [created_on_behalf_by_yomi_name]             NVARCHAR (200) NULL,
    [ltf_address1_city]                          NVARCHAR (80)  NULL,
    [ltf_address1_county]                        NVARCHAR (50)  NULL,
    [ltf_address1_line1]                         NVARCHAR (250) NULL,
    [ltf_address1_line1_country]                 NVARCHAR (80)  NULL,
    [ltf_address1_line2]                         NVARCHAR (250) NULL,
    [ltf_address1_line3]                         NVARCHAR (250) NULL,
    [ltf_address1_postal_code]                   NVARCHAR (20)  NULL,
    [ltf_address1_state_or_province]             NVARCHAR (50)  NULL,
    [ltf_contact_lookup]                         VARCHAR (36)   NULL,
    [ltf_contact_lookup_name]                    NVARCHAR (160) NULL,
    [ltf_contact_lookup_yomi_name]               NVARCHAR (160) NULL,
    [ltf_do_not_contact_store_id]                VARCHAR (36)   NULL,
    [ltf_email_address1]                         NVARCHAR (100) NULL,
    [ltf_email_address1_dncsource]               INT            NULL,
    [ltf_email_address1_dncsourcename]           NVARCHAR (255) NULL,
    [ltf_email_address2]                         NVARCHAR (100) NULL,
    [ltf_email_address2_dncsource]               INT            NULL,
    [ltf_email_address2_dncsourcename]           NVARCHAR (255) NULL,
    [ltf_lead_lookup]                            VARCHAR (36)   NULL,
    [ltf_lead_lookup_name]                       NVARCHAR (160) NULL,
    [ltf_lead_lookup_yomi_name]                  NVARCHAR (160) NULL,
    [ltf_mobile_phone]                           NVARCHAR (50)  NULL,
    [ltf_mobile_phone_dnc_source]                INT            NULL,
    [ltf_mobile_phone_dnc_source_name]           NVARCHAR (255) NULL,
    [ltf_name]                                   NVARCHAR (160) NULL,
    [ltf_telephone1]                             NVARCHAR (50)  NULL,
    [ltf_telephone1_dnc_source]                  INT            NULL,
    [ltf_telephone1_dnc_source_name]             NVARCHAR (255) NULL,
    [ltf_telephone2]                             NVARCHAR (50)  NULL,
    [ltf_telephone2_dnc_source]                  INT            NULL,
    [ltf_telephone2_dnc_source_name]             NVARCHAR (255) NULL,
    [ltf_telephone3]                             NVARCHAR (50)  NULL,
    [ltf_telephone3_dncsource]                   INT            NULL,
    [ltf_telephone3_dncsourcename]               NVARCHAR (255) NULL,
    [modified_by_name]                           NVARCHAR (200) NULL,
    [modified_by_yomi_name]                      NVARCHAR (200) NULL,
    [modifiedon]                                 DATETIME       NULL,
    [modified_on_behalf_by]                      VARCHAR (36)   NULL,
    [modified_on_behalf_by_name]                 NVARCHAR (200) NULL,
    [modified_on_behalf_by_yomi_name]            NVARCHAR (200) NULL,
    [organization_id_name]                       NVARCHAR (160) NULL,
    [overridden_created_on]                      DATETIME       NULL,
    [state_code]                                 INT            NULL,
    [state_code_name]                            NVARCHAR (255) NULL,
    [status_code]                                INT            NULL,
    [status_code_name]                           NVARCHAR (255) NULL,
    [time_zone_rule_version_number]              INT            NULL,
    [utc_conversion_time_zone_code]              INT            NULL,
    [version_number]                             BIGINT         NULL,
    [inserted_date_time]                         DATETIME       NULL,
    [insert_user]                                VARCHAR (100)  NULL,
    [updated_date_time]                          DATETIME       NULL,
    [update_user]                                VARCHAR (50)   NULL,
    [dv_load_date_time]                          DATETIME       NOT NULL,
    [dv_r_load_source_id]                        BIGINT         NOT NULL,
    [dv_inserted_date_time]                      DATETIME       NOT NULL,
    [dv_insert_user]                             VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                       DATETIME       NULL,
    [dv_update_user]                             VARCHAR (50)   NULL,
    [dv_hash]                                    CHAR (32)      NOT NULL,
    [dv_batch_id]                                BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_crmcloudsync_ltf_do_not_contact_store]
    ON [dbo].[s_crmcloudsync_ltf_do_not_contact_store]([bk_hash] ASC, [s_crmcloudsync_ltf_do_not_contact_store_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_ltf_do_not_contact_store]([dv_batch_id] ASC);

