CREATE TABLE [dbo].[s_crmcloudsync_system_user] (
    [s_crmcloudsync_system_user_id]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)       NOT NULL,
    [access_mode]                            INT             NULL,
    [address_1_address_type_code]            INT             NULL,
    [address_1_address_type_code_name]       NVARCHAR (255)  NULL,
    [address_1_city]                         NVARCHAR (128)  NULL,
    [address_1_composite]                    VARCHAR (8000)  NULL,
    [address_1_country]                      NVARCHAR (128)  NULL,
    [address_1_county]                       NVARCHAR (128)  NULL,
    [address_1_fax]                          NVARCHAR (64)   NULL,
    [address_1_latitude]                     DECIMAL (26, 6) NULL,
    [address_1_line_1]                       NVARCHAR (1024) NULL,
    [address_1_line_2]                       NVARCHAR (1024) NULL,
    [address_1_line_3]                       NVARCHAR (1024) NULL,
    [address_1_longitude]                    DECIMAL (26, 6) NULL,
    [address_1_name]                         NVARCHAR (100)  NULL,
    [address_1_postal_code]                  NVARCHAR (40)   NULL,
    [address_1_post_office_box]              NVARCHAR (40)   NULL,
    [address_1_shipping_method_code]         INT             NULL,
    [address_1_shipping_method_code_name]    NVARCHAR (255)  NULL,
    [address_1_state_or_province]            NVARCHAR (128)  NULL,
    [address_1_telephone_1]                  NVARCHAR (64)   NULL,
    [address_1_telephone_2]                  NVARCHAR (50)   NULL,
    [address_1_telephone_3]                  NVARCHAR (50)   NULL,
    [address_1_ups_zone]                     NVARCHAR (4)    NULL,
    [address_1_utc_offset]                   INT             NULL,
    [address_2_address_type_code]            INT             NULL,
    [address_2_address_type_code_name]       NVARCHAR (255)  NULL,
    [address_2_city]                         NVARCHAR (128)  NULL,
    [address_2_composite]                    VARCHAR (8000)  NULL,
    [address_2_country]                      NVARCHAR (128)  NULL,
    [address_2_county]                       NVARCHAR (128)  NULL,
    [address_2_fax]                          NVARCHAR (50)   NULL,
    [address_2_latitude]                     DECIMAL (26, 6) NULL,
    [address_2_line_1]                       NVARCHAR (1024) NULL,
    [address_2_line_2]                       NVARCHAR (1024) NULL,
    [address_2_line_3]                       NVARCHAR (1024) NULL,
    [address_2_longitude]                    DECIMAL (26, 6) NULL,
    [address_2_name]                         NVARCHAR (100)  NULL,
    [address_2_postal_code]                  NVARCHAR (40)   NULL,
    [address_2_post_office_box]              NVARCHAR (40)   NULL,
    [address_2_shipping_method_code]         INT             NULL,
    [address_2_shipping_method_code_name]    NVARCHAR (255)  NULL,
    [address_2_state_or_province]            NVARCHAR (128)  NULL,
    [address_2_telephone_1]                  NVARCHAR (50)   NULL,
    [address_2_telephone_2]                  NVARCHAR (50)   NULL,
    [address_2_telephone_3]                  NVARCHAR (50)   NULL,
    [address_2_ups_zone]                     NVARCHAR (4)    NULL,
    [address_2_utc_offset]                   INT             NULL,
    [business_unit_id_name]                  NVARCHAR (160)  NULL,
    [cal_type]                               INT             NULL,
    [cal_type_name]                          NVARCHAR (255)  NULL,
    [created_by_name]                        NVARCHAR (200)  NULL,
    [created_by_yomi_name]                   NVARCHAR (200)  NULL,
    [created_on]                             DATETIME        NULL,
    [created_on_behalf_by_name]              NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]         NVARCHAR (200)  NULL,
    [default_filters_populated]              BIT             NULL,
    [default_mail_box_name]                  NVARCHAR (200)  NULL,
    [disabled_reason]                        NVARCHAR (500)  NULL,
    [display_in_service_views]               BIT             NULL,
    [display_in_service_views_name]          NVARCHAR (255)  NULL,
    [domain_name]                            NVARCHAR (1024) NULL,
    [email_router_access_approval]           INT             NULL,
    [email_router_access_approval_name]      NVARCHAR (255)  NULL,
    [entity_image_timestamp]                 BIGINT          NULL,
    [entity_image_url]                       NVARCHAR (200)  NULL,
    [exchange_rate]                          DECIMAL (28)    NULL,
    [first_name]                             NVARCHAR (64)   NULL,
    [full_name]                              NVARCHAR (200)  NULL,
    [home_phone]                             NVARCHAR (50)   NULL,
    [import_sequence_number]                 INT             NULL,
    [incoming_email_delivery_method]         INT             NULL,
    [incoming_email_delivery_method_name]    NVARCHAR (255)  NULL,
    [internal_email_address]                 NVARCHAR (100)  NULL,
    [invite_status_code]                     INT             NULL,
    [invite_status_code_name]                NVARCHAR (255)  NULL,
    [is_disabled]                            BIT             NULL,
    [is_disabled_name]                       NVARCHAR (255)  NULL,
    [is_email_address_approved_by_o365admin] BIT             NULL,
    [is_integration_user]                    BIT             NULL,
    [is_integration_user_name]               NVARCHAR (255)  NULL,
    [is_licensed]                            BIT             NULL,
    [is_sync_with_directory]                 BIT             NULL,
    [job_title]                              NVARCHAR (100)  NULL,
    [last_name]                              NVARCHAR (64)   NULL,
    [ltf_club_id_name]                       NVARCHAR (100)  NULL,
    [middle_name]                            NVARCHAR (50)   NULL,
    [mobile_alert_email]                     NVARCHAR (100)  NULL,
    [mobile_phone]                           NVARCHAR (64)   NULL,
    [modified_by_name]                       NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                  NVARCHAR (200)  NULL,
    [modified_on]                            DATETIME        NULL,
    [modified_on_behalf_by_name]             NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]        NVARCHAR (200)  NULL,
    [nick_name]                              NVARCHAR (50)   NULL,
    [organization_id_name]                   NVARCHAR (100)  NULL,
    [outgoing_email_delivery_method]         INT             NULL,
    [outgoing_email_delivery_method_name]    NVARCHAR (255)  NULL,
    [overridden_created_on]                  DATETIME        NULL,
    [parent_system_user_id_name]             NVARCHAR (200)  NULL,
    [parent_system_user_id_yomi_name]        NVARCHAR (200)  NULL,
    [passport_hi]                            INT             NULL,
    [passport_lo]                            INT             NULL,
    [personal_email_address]                 NVARCHAR (100)  NULL,
    [photo_url]                              NVARCHAR (200)  NULL,
    [preferred_address_code]                 INT             NULL,
    [preferred_address_code_name]            NVARCHAR (255)  NULL,
    [preferred_email_code]                   INT             NULL,
    [preferred_email_code_name]              NVARCHAR (255)  NULL,
    [preferred_phone_code]                   INT             NULL,
    [preferred_phone_code_name]              NVARCHAR (255)  NULL,
    [queue_id_name]                          NVARCHAR (400)  NULL,
    [salutation]                             NVARCHAR (20)   NULL,
    [set_up_user]                            BIT             NULL,
    [set_up_user_name]                       NVARCHAR (255)  NULL,
    [site_id_name]                           NVARCHAR (160)  NULL,
    [skills]                                 NVARCHAR (100)  NULL,
    [system_user_id]                         VARCHAR (36)    NULL,
    [territory_id_name]                      NVARCHAR (200)  NULL,
    [time_zone_rule_version_number]          INT             NULL,
    [title]                                  NVARCHAR (128)  NULL,
    [transaction_currency_id_name]           NVARCHAR (100)  NULL,
    [user_license_type]                      INT             NULL,
    [utc_conversion_time_zone_code]          INT             NULL,
    [version_number]                         BIGINT          NULL,
    [windows_live_id]                        NVARCHAR (1024) NULL,
    [yammer_email_address]                   NVARCHAR (200)  NULL,
    [yomi_first_name]                        NVARCHAR (64)   NULL,
    [yomi_full_name]                         NVARCHAR (200)  NULL,
    [yomi_last_name]                         NVARCHAR (64)   NULL,
    [yomi_middle_name]                       NVARCHAR (50)   NULL,
    [inserted_date_time]                     DATETIME        NULL,
    [insert_user]                            VARCHAR (100)   NULL,
    [updated_date_time]                      DATETIME        NULL,
    [update_user]                            VARCHAR (50)    NULL,
    [default_odb_folder_name]                NVARCHAR (200)  NULL,
    [mobile_off_line_profile_id_name]        NVARCHAR (255)  NULL,
    [position_id_name]                       NVARCHAR (100)  NULL,
    [sharepoint_email_address]               NVARCHAR (1024) NULL,
    [traversed_path]                         NVARCHAR (1250) NULL,
    [dv_load_date_time]                      DATETIME        NOT NULL,
    [dv_r_load_source_id]                    BIGINT          NOT NULL,
    [dv_inserted_date_time]                  DATETIME        NOT NULL,
    [dv_insert_user]                         VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                   DATETIME        NULL,
    [dv_update_user]                         VARCHAR (50)    NULL,
    [dv_hash]                                CHAR (32)       NOT NULL,
    [dv_batch_id]                            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_crmcloudsync_system_user]
    ON [dbo].[s_crmcloudsync_system_user]([bk_hash] ASC, [s_crmcloudsync_system_user_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_system_user]([dv_batch_id] ASC);

