CREATE TABLE [dbo].[s_crmcloudsync_ltf_live_chat] (
    [s_crmcloudsync_ltf_live_chat_id]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                            CHAR (32)       NOT NULL,
    [activity_additional_params]         VARCHAR (8000)  NULL,
    [activity_id]                        VARCHAR (36)    NULL,
    [activity_type_code]                 NVARCHAR (64)   NULL,
    [activity_type_code_name]            NVARCHAR (255)  NULL,
    [actual_duration_minutes]            INT             NULL,
    [actual_end]                         DATETIME        NULL,
    [actual_start]                       DATETIME        NULL,
    [bcc]                                VARCHAR (8000)  NULL,
    [cc]                                 VARCHAR (8000)  NULL,
    [community]                          INT             NULL,
    [community_name]                     NVARCHAR (255)  NULL,
    [created_by_name]                    NVARCHAR (200)  NULL,
    [created_by_yomi_name]               NVARCHAR (200)  NULL,
    [created_on]                         DATETIME        NULL,
    [created_on_behalf_by_name]          NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]     NVARCHAR (200)  NULL,
    [delivery_last_attempted_on]         DATETIME        NULL,
    [delivery_priority_code_name]        NVARCHAR (255)  NULL,
    [description]                        VARCHAR (8000)  NULL,
    [exchange_rate]                      DECIMAL (28)    NULL,
    [exchange_web_link]                  NVARCHAR (1250) NULL,
    [from]                               VARCHAR (8000)  NULL,
    [import_sequence_number]             INT             NULL,
    [instance_type_code_name]            NVARCHAR (255)  NULL,
    [is_billed]                          VARCHAR (36)    NULL,
    [is_billed_name]                     NVARCHAR (255)  NULL,
    [is_mapi_private]                    VARCHAR (36)    NULL,
    [is_mapi_private_name]               NVARCHAR (255)  NULL,
    [is_regular_activity]                VARCHAR (36)    NULL,
    [is_regular_activity_name]           NVARCHAR (255)  NULL,
    [is_workflow_created]                VARCHAR (36)    NULL,
    [is_workflow_created_name]           NVARCHAR (255)  NULL,
    [last_on_hold_time]                  DATETIME        NULL,
    [left_voice_mail]                    VARCHAR (36)    NULL,
    [left_voice_mail_name]               NVARCHAR (255)  NULL,
    [ltf_appointment_start]              DATETIME        NULL,
    [ltf_appointment_subject]            NVARCHAR (200)  NULL,
    [ltf_chat_wrap_up]                   INT             NULL,
    [ltf_chat_wrap_up_name]              NVARCHAR (255)  NULL,
    [ltf_club_name]                      NVARCHAR (100)  NULL,
    [ltf_disqualify_reason]              INT             NULL,
    [ltf_disqualify_reason_name]         NVARCHAR (255)  NULL,
    [ltf_email_address_1]                NVARCHAR (100)  NULL,
    [ltf_first_name]                     NVARCHAR (50)   NULL,
    [ltf_ims_promo]                      NVARCHAR (50)   NULL,
    [ltf_last_name]                      NVARCHAR (50)   NULL,
    [ltf_membership_level]               INT             NULL,
    [ltf_membership_level_name]          NVARCHAR (255)  NULL,
    [ltf_notes]                          NVARCHAR (2000) NULL,
    [ltf_original_lead_name]             NVARCHAR (160)  NULL,
    [ltf_original_lead_yomi_name]        NVARCHAR (160)  NULL,
    [ltf_park_until]                     DATETIME        NULL,
    [ltf_phone]                          NVARCHAR (50)   NULL,
    [ltf_proactive_or_reactive]          INT             NULL,
    [ltf_proactive_or_reactive_name]     NVARCHAR (255)  NULL,
    [ltf_ready_to_process]               VARCHAR (36)    NULL,
    [ltf_ready_to_process_name]          NVARCHAR (255)  NULL,
    [ltf_recommended_membership_name]    NVARCHAR (255)  NULL,
    [ltf_referring_url]                  NVARCHAR (4000) NULL,
    [ltf_request_date]                   DATETIME        NULL,
    [ltf_routing_message]                NVARCHAR (512)  NULL,
    [ltf_routing_step]                   INT             NULL,
    [ltf_routing_step_name]              NVARCHAR (255)  NULL,
    [ltf_send_ims_join]                  VARCHAR (36)    NULL,
    [ltf_send_ims_join_name]             NVARCHAR (255)  NULL,
    [ltf_service_line]                   NVARCHAR (50)   NULL,
    [ltf_transcript]                     VARCHAR (8000)  NULL,
    [ltf_type]                           INT             NULL,
    [ltf_type_name]                      NVARCHAR (255)  NULL,
    [ltf_web_team_name]                  NVARCHAR (160)  NULL,
    [ltf_web_team_yomi_name]             NVARCHAR (160)  NULL,
    [modified_by_name]                   NVARCHAR (200)  NULL,
    [modified_by_yomi_name]              NVARCHAR (200)  NULL,
    [modified_on]                        DATETIME        NULL,
    [modified_on_behalf_by_name]         NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]    NVARCHAR (200)  NULL,
    [on_hold_time]                       INT             NULL,
    [optional_attendees]                 VARCHAR (8000)  NULL,
    [organizer]                          VARCHAR (8000)  NULL,
    [overridden_created_on]              DATETIME        NULL,
    [ownerid_name]                       NVARCHAR (200)  NULL,
    [owner_id_type]                      NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                 NVARCHAR (200)  NULL,
    [owning_business_unit]               VARCHAR (36)    NULL,
    [partners]                           VARCHAR (8000)  NULL,
    [postpone_activity_processing_until] DATETIME        NULL,
    [priority_code]                      INT             NULL,
    [priority_code_name]                 NVARCHAR (255)  NULL,
    [regarding_object_id_name]           NVARCHAR (4000) NULL,
    [regarding_object_id_yomi_name]      NVARCHAR (4000) NULL,
    [regarding_object_type_code]         NVARCHAR (64)   NULL,
    [required_attendees]                 VARCHAR (8000)  NULL,
    [resources]                          VARCHAR (8000)  NULL,
    [scheduled_duration_minutes]         INT             NULL,
    [scheduled_end]                      DATETIME        NULL,
    [scheduled_start]                    DATETIME        NULL,
    [sender_mail_box_id_name]            NVARCHAR (200)  NULL,
    [sent_on]                            DATETIME        NULL,
    [service_id_name]                    NVARCHAR (160)  NULL,
    [sla_invoked_id_name]                NVARCHAR (100)  NULL,
    [sla_name]                           NVARCHAR (100)  NULL,
    [sort_date]                          DATETIME        NULL,
    [state_code]                         INT             NULL,
    [state_code_name]                    NVARCHAR (255)  NULL,
    [status_code]                        INT             NULL,
    [status_code_name]                   NVARCHAR (255)  NULL,
    [subject]                            NVARCHAR (200)  NULL,
    [time_zone_rule_version_number]      INT             NULL,
    [to]                                 VARCHAR (8000)  NULL,
    [transaction_currency_id_name]       NVARCHAR (100)  NULL,
    [traversed_path]                     NVARCHAR (1250) NULL,
    [utc_conversion_time_zone_code]      INT             NULL,
    [version_number]                     BIGINT          NULL,
    [inserted_date_time]                 DATETIME        NULL,
    [insert_user]                        VARCHAR (50)    NULL,
    [updated_date_time]                  DATETIME        NULL,
    [update_user]                        VARCHAR (50)    NULL,
    [ltf_most_recent_casl]               DATETIME        NULL,
    [ltf_line_of_business]               INT             NULL,
    [ltf_line_of_business_name]          NVARCHAR (255)  NULL,
    [dv_load_date_time]                  DATETIME        NOT NULL,
    [dv_r_load_source_id]                BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL,
    [dv_hash]                            CHAR (32)       NOT NULL,
    [dv_deleted]                         BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

