CREATE TABLE [dbo].[s_crmcloudsync_campaign] (
    [s_crmcloudsync_campaign_id]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                  CHAR (32)       NOT NULL,
    [actual_end]                               DATETIME        NULL,
    [actual_start]                             DATETIME        NULL,
    [budgeted_cost]                            INT             NULL,
    [budgeted_cost_base]                       INT             NULL,
    [campaign_id]                              VARCHAR (36)    NULL,
    [code_name]                                NVARCHAR (32)   NULL,
    [created_by_name]                          NVARCHAR (200)  NULL,
    [created_by_yomi_name]                     NVARCHAR (200)  NULL,
    [created_on]                               DATETIME        NULL,
    [created_on_behalf_by]                     VARCHAR (36)    NULL,
    [created_on_behalf_by_name]                NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]           NVARCHAR (200)  NULL,
    [description]                              VARCHAR (8000)  NULL,
    [entity_image]                             VARCHAR (50)    NULL,
    [entity_image_timestamp]                   BIGINT          NULL,
    [entity_image_url]                         NVARCHAR (200)  NULL,
    [entity_imageid]                           VARCHAR (36)    NULL,
    [exchange_rate]                            DECIMAL (28)    NULL,
    [expected_response]                        INT             NULL,
    [expected_revenue]                         INT             NULL,
    [expected_revenue_base]                    INT             NULL,
    [import_sequence_number]                   INT             NULL,
    [is_template]                              BIT             NULL,
    [is_template_name]                         NVARCHAR (255)  NULL,
    [ltf_club_restriction_type]                INT             NULL,
    [ltf_club_restriction_type_name]           NVARCHAR (255)  NULL,
    [ltf_connect_with_am]                      BIT             NULL,
    [ltf_connect_with_am_name]                 NVARCHAR (255)  NULL,
    [ltf_display_on_form]                      BIT             NULL,
    [ltf_display_on_form_name]                 NVARCHAR (255)  NULL,
    [ltf_expiration_days]                      INT             NULL,
    [ltf_expiration_type]                      INT             NULL,
    [ltf_expiration_type_name]                 NVARCHAR (255)  NULL,
    [ltf_pass_days]                            INT             NULL,
    [ltf_targeted_record_type]                 INT             NULL,
    [ltf_targeted_record_type_name]            NVARCHAR (255)  NULL,
    [ltf_user_defined_dates]                   BIT             NULL,
    [ltf_user_defined_dates_name]              NVARCHAR (255)  NULL,
    [message]                                  NVARCHAR (256)  NULL,
    [modified_by_name]                         NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                    NVARCHAR (200)  NULL,
    [modified_on]                              DATETIME        NULL,
    [modified_on_behalf_by]                    VARCHAR (36)    NULL,
    [modified_on_behalf_by_name]               NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]          NVARCHAR (200)  NULL,
    [name]                                     NVARCHAR (128)  NULL,
    [objective]                                VARCHAR (8000)  NULL,
    [other_cost]                               INT             NULL,
    [other_cost_base]                          INT             NULL,
    [overridden_created_on]                    DATETIME        NULL,
    [owner_id_name]                            NVARCHAR (200)  NULL,
    [owner_id_type]                            NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                       NVARCHAR (200)  NULL,
    [owning_team]                              VARCHAR (36)    NULL,
    [price_list_name]                          NVARCHAR (100)  NULL,
    [process_id]                               VARCHAR (36)    NULL,
    [promotion_code_name]                      NVARCHAR (128)  NULL,
    [proposed_end]                             DATETIME        NULL,
    [proposed_start]                           DATETIME        NULL,
    [stage_id]                                 VARCHAR (36)    NULL,
    [state_code]                               INT             NULL,
    [state_code_name]                          NVARCHAR (255)  NULL,
    [status_code]                              INT             NULL,
    [status_code_name]                         NVARCHAR (255)  NULL,
    [time_zone_rule_version_number]            INT             NULL,
    [total_actual_cost]                        INT             NULL,
    [total_actual_cost_base]                   INT             NULL,
    [total_campaign_activity_actual_cost]      INT             NULL,
    [total_campaign_activity_actual_cost_base] INT             NULL,
    [transaction_currency_id_name]             NVARCHAR (100)  NULL,
    [traversed_path]                           NVARCHAR (1250) NULL,
    [type_code]                                INT             NULL,
    [type_code_name]                           NVARCHAR (255)  NULL,
    [utc_conversion_time_zone_code]            INT             NULL,
    [version_number]                           BIGINT          NULL,
    [inserted_date_time]                       DATETIME        NULL,
    [insert_user]                              VARCHAR (50)    NULL,
    [updated_date_time]                        DATETIME        NULL,
    [update_user]                              VARCHAR (50)    NULL,
    [ltf_issuance_method]                      INT             NULL,
    [ltf_qr_code_string]                       NVARCHAR (2000) NULL,
    [ltf_qr_code_url]                          NVARCHAR (2000) NULL,
    [ltf_targeted_prospects]                   INT             NULL,
    [ltf_targeted_issue_date]                  DATETIME        NULL,
    [ltf_send_id]                              NVARCHAR (50)   NULL,
    [ltf_member_referral]                      BIT             NULL,
    [ltf_guest_pass_type]                      INT             NULL,
    [ltf_reward_type]                          INT             NULL,
    [ltf_reward_lt_bucks]                      INT             NULL,
    [ltf_reward_wait_days]                     INT             NULL,
    [ltf_reward_club]                          VARCHAR (36)    NULL,
    [ltf_restricted_by_policy]                 BIT             NULL,
    [dv_load_date_time]                        DATETIME        NOT NULL,
    [dv_r_load_source_id]                      BIGINT          NOT NULL,
    [dv_inserted_date_time]                    DATETIME        NOT NULL,
    [dv_insert_user]                           VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                     DATETIME        NULL,
    [dv_update_user]                           VARCHAR (50)    NULL,
    [dv_hash]                                  CHAR (32)       NOT NULL,
    [dv_batch_id]                              BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_campaign]([dv_batch_id] ASC);

