CREATE TABLE [dbo].[s_crmcloudsync_lead] (
    [s_crmcloudsync_lead_id]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [account_idname]                       NVARCHAR (160)  NULL,
    [account_idyomi_name]                  NVARCHAR (160)  NULL,
    [address_1_address_type_code]          INT             NULL,
    [address_1_address_type_code_name]     NVARCHAR (255)  NULL,
    [address_1_city]                       NVARCHAR (50)   NULL,
    [address_1_composite]                  NVARCHAR (4000) NULL,
    [address_1_country]                    NVARCHAR (80)   NULL,
    [address1_county]                      NVARCHAR (50)   NULL,
    [address1_fax]                         NVARCHAR (50)   NULL,
    [address_1_latitude]                   DECIMAL (26, 6) NULL,
    [address_1_line_1]                     NVARCHAR (50)   NULL,
    [address_1_line_2]                     NVARCHAR (50)   NULL,
    [address_1_line_3]                     NVARCHAR (250)  NULL,
    [address_1_longitude]                  DECIMAL (26, 6) NULL,
    [address1_name]                        NVARCHAR (100)  NULL,
    [address1_postal_code]                 NVARCHAR (20)   NULL,
    [address1_post_office_box]             NVARCHAR (20)   NULL,
    [address_1_shipping_method_code]       INT             NULL,
    [address_1_shipping_method_code_name]  NVARCHAR (255)  NULL,
    [address_1_state_or_province]          NVARCHAR (3)    NULL,
    [address_1_telephone_1]                NVARCHAR (50)   NULL,
    [address_1_telephone_2]                NVARCHAR (50)   NULL,
    [address_1_telephone_3]                NVARCHAR (50)   NULL,
    [address_1_ups_zone]                   NVARCHAR (4)    NULL,
    [address1_utc_off_set]                 INT             NULL,
    [address_2_address_type_code]          INT             NULL,
    [address_2_address_type_code_name]     NVARCHAR (255)  NULL,
    [address_2_city]                       NVARCHAR (80)   NULL,
    [address_2_composite]                  NVARCHAR (4000) NULL,
    [address_2_country]                    NVARCHAR (80)   NULL,
    [address_2_county]                     NVARCHAR (50)   NULL,
    [address_2_fax]                        NVARCHAR (50)   NULL,
    [address_2_latitude]                   DECIMAL (26, 6) NULL,
    [address_2_line_1]                     NVARCHAR (250)  NULL,
    [address_2_line_2]                     NVARCHAR (250)  NULL,
    [address_2_line_3]                     NVARCHAR (250)  NULL,
    [address_2_longitude]                  DECIMAL (26, 6) NULL,
    [address_2_name]                       NVARCHAR (100)  NULL,
    [address_2_postal_code]                NVARCHAR (20)   NULL,
    [address_2_post_office_box]            NVARCHAR (20)   NULL,
    [address_2_shipping_method_code]       INT             NULL,
    [address_2_shipping_method_code_name]  NVARCHAR (255)  NULL,
    [address_2_state_or_province]          NVARCHAR (50)   NULL,
    [address_2_telephone_1]                NVARCHAR (50)   NULL,
    [address_2_telephone_2]                NVARCHAR (50)   NULL,
    [address_2_telephone_3]                NVARCHAR (50)   NULL,
    [address_2_ups_zone]                   NVARCHAR (4)    NULL,
    [address_2_utc_off_set]                INT             NULL,
    [budget_amount]                        DECIMAL (26, 6) NULL,
    [budget_amount_base]                   DECIMAL (26, 6) NULL,
    [budget_status]                        INT             NULL,
    [budget_status_name]                   NVARCHAR (255)  NULL,
    [campaign_id_name]                     NVARCHAR (128)  NULL,
    [company_name]                         NVARCHAR (100)  NULL,
    [confirm_interest]                     BIT             NULL,
    [confirm_interest_name]                NVARCHAR (255)  NULL,
    [contact_id_name]                      NVARCHAR (160)  NULL,
    [contact_id_yomi_name]                 NVARCHAR (160)  NULL,
    [created_by_name]                      NVARCHAR (200)  NULL,
    [created_by_yomi_name]                 NVARCHAR (200)  NULL,
    [created_on]                           DATETIME        NULL,
    [created_on_behalf_by_name]            NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]       NVARCHAR (200)  NULL,
    [customer_id_name]                     NVARCHAR (160)  NULL,
    [customer_id_type]                     NVARCHAR (64)   NULL,
    [customer_id_yomi_name]                NVARCHAR (450)  NULL,
    [decision_maker]                       BIT             NULL,
    [decision_maker_name]                  NVARCHAR (255)  NULL,
    [description]                          NVARCHAR (4000) NULL,
    [do_not_bulk_email]                    BIT             NULL,
    [do_not_bulk_email_name]               NVARCHAR (255)  NULL,
    [do_not_email]                         BIT             NULL,
    [do_not_email_name]                    NVARCHAR (255)  NULL,
    [do_not_fax]                           BIT             NULL,
    [do_not_fax_name]                      NVARCHAR (255)  NULL,
    [do_not_phone]                         BIT             NULL,
    [do_not_phone_name]                    NVARCHAR (255)  NULL,
    [do_not_postal_mail]                   BIT             NULL,
    [do_not_postal_mail_name]              NVARCHAR (255)  NULL,
    [do_not_send_marketing_material_name]  NVARCHAR (255)  NULL,
    [do_not_send_mm]                       BIT             NULL,
    [email_address_1]                      NVARCHAR (100)  NULL,
    [email_address_2]                      NVARCHAR (100)  NULL,
    [email_address_3]                      NVARCHAR (100)  NULL,
    [entity_image_time_stamp]              BIGINT          NULL,
    [entity_image_url]                     NVARCHAR (200)  NULL,
    [estimated_amount]                     DECIMAL (26, 6) NULL,
    [estimated_amount_base]                DECIMAL (26, 6) NULL,
    [estimated_close_date]                 DATETIME        NULL,
    [estimated_value]                      DECIMAL (26, 6) NULL,
    [evaluate_fit]                         BIT             NULL,
    [evaluate_fit_name]                    NVARCHAR (255)  NULL,
    [exchange_rate]                        DECIMAL (28)    NULL,
    [fax]                                  NVARCHAR (50)   NULL,
    [first_name]                           NVARCHAR (50)   NULL,
    [full_name]                            NVARCHAR (160)  NULL,
    [import_sequence_number]               INT             NULL,
    [industry_code]                        INT             NULL,
    [industry_code_name]                   NVARCHAR (255)  NULL,
    [initial_communication]                INT             NULL,
    [initial_communication_name]           NVARCHAR (255)  NULL,
    [is_private_name]                      NVARCHAR (255)  NULL,
    [job_title]                            NVARCHAR (100)  NULL,
    [last_name]                            NVARCHAR (50)   NULL,
    [last_used_in_campaign]                DATETIME        NULL,
    [lead_id]                              VARCHAR (36)    NULL,
    [lead_quality_code]                    INT             NULL,
    [lead_quality_code_name]               NVARCHAR (255)  NULL,
    [lead_source_code]                     INT             NULL,
    [lead_source_code_name]                NVARCHAR (255)  NULL,
    [ltf_birth_date]                       DATETIME        NULL,
    [ltf_birth_year]                       NVARCHAR (4)    NULL,
    [ltf_business_unit_name]               NVARCHAR (160)  NULL,
    [ltf_club_id_name]                     NVARCHAR (100)  NULL,
    [ltf_current_member]                   BIT             NULL,
    [ltf_current_member_name]              NVARCHAR (255)  NULL,
    [ltf_do_not_email_address_1]           BIT             NULL,
    [ltf_do_not_email_address_1_name]      NVARCHAR (255)  NULL,
    [ltf_do_not_email_address_2]           BIT             NULL,
    [ltf_do_not_email_address_2_name]      NVARCHAR (255)  NULL,
    [ltf_do_not_phone_mobile_phone]        BIT             NULL,
    [ltf_do_not_phone_mobile_phone_name]   NVARCHAR (255)  NULL,
    [ltf_do_not_phone_telephone_1]         BIT             NULL,
    [ltf_do_not_phone_telephone_1_name]    NVARCHAR (255)  NULL,
    [ltf_do_not_phone_telephone_2]         BIT             NULL,
    [ltf_do_not_phone_telephone_2_name]    NVARCHAR (255)  NULL,
    [ltf_employee_number]                  NVARCHAR (100)  NULL,
    [ltf_employer_id_name]                 NVARCHAR (160)  NULL,
    [ltf_employer_id_yomi_name]            NVARCHAR (160)  NULL,
    [ltf_gender_code]                      INT             NULL,
    [ltf_gender_code_name]                 NVARCHAR (255)  NULL,
    [ltf_guest_to_lead_id_name]            NVARCHAR (200)  NULL,
    [ltf_inserted_by_system]               BIT             NULL,
    [ltf_inserted_by_system_name]          NVARCHAR (255)  NULL,
    [ltf_last_activity]                    NVARCHAR (100)  NULL,
    [ltf_last_activity_lead]               DATETIME        NULL,
    [ltf_lead_source]                      INT             NULL,
    [ltf_lead_source_name]                 NVARCHAR (255)  NULL,
    [ltf_lead_type]                        INT             NULL,
    [ltf_lead_type_name]                   NVARCHAR (255)  NULL,
    [ltf_legacy]                           NVARCHAR (4000) NULL,
    [ltf_measurable_goal_id_name]          NVARCHAR (100)  NULL,
    [ltf_membership_info_requested]        NVARCHAR (50)   NULL,
    [ltf_membership_level]                 INT             NULL,
    [ltf_membership_level_name]            NVARCHAR (255)  NULL,
    [ltf_membership_type]                  INT             NULL,
    [ltf_membership_type_name]             NVARCHAR (255)  NULL,
    [ltf_nugget]                           NVARCHAR (4000) NULL,
    [ltf_park]                             BIT             NULL,
    [ltf_park_comments]                    NVARCHAR (400)  NULL,
    [ltf_park_name]                        NVARCHAR (255)  NULL,
    [ltf_park_reason]                      INT             NULL,
    [ltf_park_reason_name]                 NVARCHAR (255)  NULL,
    [ltf_park_until]                       DATETIME        NULL,
    [ltf_primary_objective_id_name]        NVARCHAR (100)  NULL,
    [ltf_referring_contact_id_name]        NVARCHAR (160)  NULL,
    [ltf_referring_contact_id_yomi_name]   NVARCHAR (160)  NULL,
    [ltf_registration_code]                NVARCHAR (100)  NULL,
    [ltf_specific_goal_id_name]            NVARCHAR (100)  NULL,
    [ltf_suffix]                           NVARCHAR (3)    NULL,
    [ltf_task_id_name]                     NVARCHAR (200)  NULL,
    [ltf_time_zone_code]                   INT             NULL,
    [ltf_volatile_contact]                 BIT             NULL,
    [ltf_volatile_contact_name]            NVARCHAR (255)  NULL,
    [ltf_web_team_id_name]                 NVARCHAR (160)  NULL,
    [ltf_web_team_id_yomi_name]            NVARCHAR (160)  NULL,
    [master_lead_id_name]                  NVARCHAR (160)  NULL,
    [master_lead_id_yomi_name]             NVARCHAR (160)  NULL,
    [merged]                               BIT             NULL,
    [merged_name]                          NVARCHAR (255)  NULL,
    [middle_name]                          NVARCHAR (50)   NULL,
    [mobile_phone]                         NVARCHAR (20)   NULL,
    [modified_by_name]                     NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                NVARCHAR (200)  NULL,
    [modified_on]                          DATETIME        NULL,
    [modified_on_behalf_by_name]           NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]      NVARCHAR (200)  NULL,
    [need]                                 INT             NULL,
    [need_name]                            NVARCHAR (255)  NULL,
    [number_of_employees]                  INT             NULL,
    [originating_case_id_name]             NVARCHAR (200)  NULL,
    [overridden_created_on]                DATETIME        NULL,
    [owner_id_name]                        NVARCHAR (200)  NULL,
    [owner_id_type]                        NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                   NVARCHAR (200)  NULL,
    [pager]                                NVARCHAR (20)   NULL,
    [parent_account_id_name]               NVARCHAR (160)  NULL,
    [parent_account_id_yomi_name]          NVARCHAR (160)  NULL,
    [parent_contact_id_name]               NVARCHAR (160)  NULL,
    [parent_contact_id_yomi_name]          NVARCHAR (160)  NULL,
    [participates_in_workflow]             BIT             NULL,
    [participates_in_workflow_name]        NVARCHAR (255)  NULL,
    [preferred_contact_method_code]        INT             NULL,
    [preferred_contact_method_code_name]   NVARCHAR (255)  NULL,
    [priority_code]                        INT             NULL,
    [priority_code_name]                   NVARCHAR (255)  NULL,
    [purchase_process]                     INT             NULL,
    [purchase_process_name]                NVARCHAR (255)  NULL,
    [purchase_time_frame]                  INT             NULL,
    [purchase_time_frame_name]             NVARCHAR (255)  NULL,
    [qualification_comments]               NVARCHAR (4000) NULL,
    [qualifying_opportunity_id_name]       NVARCHAR (300)  NULL,
    [revenue]                              DECIMAL (26, 6) NULL,
    [revenue_base]                         DECIMAL (26, 6) NULL,
    [sales_stage]                          INT             NULL,
    [sales_stage_code]                     INT             NULL,
    [sales_stage_code_name]                NVARCHAR (255)  NULL,
    [sales_stage_name]                     NVARCHAR (255)  NULL,
    [salutation]                           NVARCHAR (4)    NULL,
    [schedule_follow_up_prospect]          DATETIME        NULL,
    [schedule_follow_up_qualify]           DATETIME        NULL,
    [sic]                                  NVARCHAR (20)   NULL,
    [state_code]                           INT             NULL,
    [state_code_name]                      NVARCHAR (255)  NULL,
    [status_code]                          INT             NULL,
    [status_code_name]                     NVARCHAR (255)  NULL,
    [subject]                              NVARCHAR (300)  NULL,
    [telephone_1]                          NVARCHAR (50)   NULL,
    [telephone_2]                          NVARCHAR (50)   NULL,
    [telephone_3]                          NVARCHAR (50)   NULL,
    [time_zone_rule_version_number]        INT             NULL,
    [transaction_currency_id_name]         NVARCHAR (100)  NULL,
    [utc_conversion_time_zone_code]        INT             NULL,
    [version_number]                       BIGINT          NULL,
    [website_url]                          NVARCHAR (200)  NULL,
    [yomi_company_name]                    NVARCHAR (100)  NULL,
    [yomi_first_name]                      NVARCHAR (150)  NULL,
    [yomi_full_name]                       NVARCHAR (450)  NULL,
    [yomi_last_name]                       NVARCHAR (150)  NULL,
    [yomi_middle_name]                     NVARCHAR (150)  NULL,
    [inserted_date_time]                   DATETIME        NULL,
    [insert_user]                          VARCHAR (100)   NULL,
    [ltf_dnc_override]                     BIT             NULL,
    [ltf_dnc_override_name]                NVARCHAR (255)  NULL,
    [ltf_duplicate_override]               BIT             NULL,
    [ltf_duplicate_override_name]          NVARCHAR (255)  NULL,
    [ltf_inquiry_type]                     NVARCHAR (100)  NULL,
    [ltf_managed_until]                    DATETIME        NULL,
    [updated_date_time]                    DATETIME        NULL,
    [update_user]                          VARCHAR (50)    NULL,
    [ltf_web_transfer_method]              INT             NULL,
    [ltf_web_transfer_method_name]         NVARCHAR (255)  NULL,
    [ltf_actual_appointment_scheduled]     DATETIME        NULL,
    [ltf_actual_first_response]            DATETIME        NULL,
    [ltf_actual_initial_contact]           DATETIME        NULL,
    [ltf_appointment_showed]               BIT             NULL,
    [ltf_appointment_showed_name]          NVARCHAR (255)  NULL,
    [ltf_best_time_to_contact]             INT             NULL,
    [ltf_best_time_to_contact_name]        NVARCHAR (255)  NULL,
    [ltf_communication_consent]            INT             NULL,
    [ltf_communication_consent_name]       NVARCHAR (255)  NULL,
    [ltf_consent_date_time]                DATETIME        NULL,
    [ltf_consent_ip_address]               NVARCHAR (19)   NULL,
    [ltf_consent_text]                     NVARCHAR (300)  NULL,
    [ltf_dcmp]                             NVARCHAR (250)  NULL,
    [ltf_device]                           NVARCHAR (100)  NULL,
    [ltf_dnc_temporary_release_expiration] DATETIME        NULL,
    [ltf_dnd_override_expiration]          DATETIME        NULL,
    [ltf_duplicate_lead_count]             NVARCHAR (10)   NULL,
    [ltf_email_address_1_umsk]             NVARCHAR (100)  NULL,
    [ltf_email_address_2_umsk]             NVARCHAR (100)  NULL,
    [ltf_email_template]                   NVARCHAR (110)  NULL,
    [ltf_employer]                         NVARCHAR (50)   NULL,
    [ltf_exact_target_email_sent]          BIT             NULL,
    [ltf_exact_target_email_sent_name]     NVARCHAR (255)  NULL,
    [ltf_exclude_from_follow_up]           BIT             NULL,
    [ltf_exclude_from_follow_up_name]      NVARCHAR (255)  NULL,
    [ltf_first_response_by]                DATETIME        NULL,
    [ltf_first_response_sent]              INT             NULL,
    [ltf_first_response_sent_name]         NVARCHAR (255)  NULL,
    [ltf_first_response_status]            INT             NULL,
    [ltf_first_response_status_name]       NVARCHAR (255)  NULL,
    [ltf_gc_id]                            NVARCHAR (250)  NULL,
    [ltf_gcl_id]                           NVARCHAR (250)  NULL,
    [ltf_group]                            INT             NULL,
    [ltf_group_name]                       NVARCHAR (255)  NULL,
    [ltf_initial_contact_by]               DATETIME        NULL,
    [ltf_initial_contact_made]             INT             NULL,
    [ltf_initial_contact_made_name]        NVARCHAR (255)  NULL,
    [ltf_initial_contact_status]           INT             NULL,
    [ltf_initial_contact_status_name]      NVARCHAR (255)  NULL,
    [ltf_keywords]                         NVARCHAR (100)  NULL,
    [ltf_landing_page]                     NVARCHAR (100)  NULL,
    [ltf_last_submission_date]             DATETIME        NULL,
    [ltf_mobile_phone_umsk]                NVARCHAR (100)  NULL,
    [ltf_operating_system]                 NVARCHAR (100)  NULL,
    [ltf_primary_goal]                     NVARCHAR (100)  NULL,
    [ltf_primary_lead_name]                NVARCHAR (160)  NULL,
    [ltf_primary_lead_yomi_name]           NVARCHAR (160)  NULL,
    [ltf_reactivation_reason]              INT             NULL,
    [ltf_reactivation_reason_name]         NVARCHAR (255)  NULL,
    [ltf_recommended_membership]           INT             NULL,
    [ltf_recommended_membership_name]      NVARCHAR (255)  NULL,
    [ltf_referring_domain]                 NVARCHAR (100)  NULL,
    [ltf_referring_page]                   NVARCHAR (500)  NULL,
    [ltf_request_type]                     NVARCHAR (100)  NULL,
    [ltf_schedule_appt_by]                 DATETIME        NULL,
    [ltf_schedule_appt_status]             INT             NULL,
    [ltf_schedule_appt_status_name]        NVARCHAR (255)  NULL,
    [ltf_schedule_appt_sent]               INT             NULL,
    [ltf_schedule_appt_sent_name]          NVARCHAR (255)  NULL,
    [ltf_telephone_1_umsk]                 NVARCHAR (100)  NULL,
    [ltf_telephone_2_umsk]                 NVARCHAR (100)  NULL,
    [ltf_transferred_to_club_on]           DATETIME        NULL,
    [ltf_under_eighteen]                   BIT             NULL,
    [ltf_under_eighteen_name]              NVARCHAR (255)  NULL,
    [ltf_utm_audience]                     NVARCHAR (100)  NULL,
    [ltf_utm_campaign]                     NVARCHAR (100)  NULL,
    [ltf_utm_content]                      NVARCHAR (100)  NULL,
    [ltf_utm_image]                        NVARCHAR (100)  NULL,
    [ltf_utm_medium]                       NVARCHAR (100)  NULL,
    [ltf_utm_source]                       NVARCHAR (100)  NULL,
    [ltf_utm_term]                         NVARCHAR (100)  NULL,
    [ltf_visit_count]                      INT             NULL,
    [ltf_web_team_email]                   NVARCHAR (100)  NULL,
    [related_object_id_name]               NVARCHAR (200)  NULL,
    [traversed_path]                       NVARCHAR (1250) NULL,
    [ltf_promo_code]                       NVARCHAR (100)  NULL,
    [ltf_update_contact]                   BIT             NULL,
    [ltf_update_contact_name]              NVARCHAR (255)  NULL,
    [ltf_assigned_to_club_date]            DATETIME        NULL,
    [ltf_dnc_dne_update_triggered_by]      INT             NULL,
    [ltf_dnc_dne_update_triggered_by_name] NVARCHAR (255)  NULL,
    [ltf_ims_join_link]                    NVARCHAR (300)  NULL,
    [ltf_initial_email_subject]            NVARCHAR (250)  NULL,
    [ltf_is_ims_join]                      BIT             NULL,
    [ltf_is_life_time_close_to]            INT             NULL,
    [ltf_is_life_time_close_to_name]       NVARCHAR (255)  NULL,
    [ltf_lead_initial_load]                BIT             NULL,
    [ltf_lead_initial_load_name]           NVARCHAR (255)  NULL,
    [ltf_selected_interest_ids]            NVARCHAR (1000) NULL,
    [ltf_trigger_lead_qualify]             BIT             NULL,
    [ltf_trigger_lead_qualify_name]        NVARCHAR (255)  NULL,
    [ltf_web_team_phone]                   NVARCHAR (100)  NULL,
    [ltf_originating_guest_visit_name]     NVARCHAR (200)  NULL,
    [ltf_originating_chat_name]            NVARCHAR (2000) NULL,
    [ltf_most_recent_casl]                 DATETIME        NULL,
    [ltf_referring_corp_acct_id]           NVARCHAR (100)  NULL,
    [ltf_line_of_business]                 INT             NULL,
    [ltf_channel]                          INT             NULL,
    [ltf_line_of_business_name]            NVARCHAR (255)  NULL,
    [ltf_channel_name]                     NVARCHAR (255)  NULL,
    [dv_load_date_time]                    DATETIME        NOT NULL,
    [dv_r_load_source_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL,
    [dv_hash]                              CHAR (32)       NOT NULL,
    [dv_deleted]                           BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

