CREATE TABLE [dbo].[s_crmcloudsync_ltf_guest_visit] (
    [s_crmcloudsync_ltf_guest_visit_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                               CHAR (32)       NOT NULL,
    [activity_id]                           VARCHAR (36)    NULL,
    [activity_type_code]                    NVARCHAR (64)   NULL,
    [activity_type_code_name]               NVARCHAR (255)  NULL,
    [actual_duration_minutes]               INT             NULL,
    [actual_end]                            DATETIME        NULL,
    [actual_start]                          DATETIME        NULL,
    [bcc]                                   VARCHAR (8000)  NULL,
    [cc]                                    VARCHAR (8000)  NULL,
    [created_by_name]                       NVARCHAR (200)  NULL,
    [created_by_yomi_name]                  NVARCHAR (200)  NULL,
    [created_on]                            DATETIME        NULL,
    [created_on_behalf_by_name]             NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]        NVARCHAR (200)  NULL,
    [customers]                             VARCHAR (8000)  NULL,
    [delivery_last_attempted_on]            DATETIME        NULL,
    [delivery_priority_code]                INT             NULL,
    [delivery_priority_code_name]           NVARCHAR (255)  NULL,
    [description]                           VARCHAR (8000)  NULL,
    [exchange_rate]                         DECIMAL (28)    NULL,
    [from]                                  NVARCHAR (2000) NULL,
    [import_sequence_number]                INT             NULL,
    [instance_type_code]                    INT             NULL,
    [instance_type_code_name]               NVARCHAR (255)  NULL,
    [is_billed]                             BIT             NULL,
    [is_billed_name]                        NVARCHAR (255)  NULL,
    [is_mapi_private]                       BIT             NULL,
    [is_mapi_private_name]                  NVARCHAR (255)  NULL,
    [is_regular_activity]                   BIT             NULL,
    [is_regular_activity_name]              NVARCHAR (255)  NULL,
    [is_workflow_created]                   BIT             NULL,
    [is_workflow_created_name]              NVARCHAR (255)  NULL,
    [left_voice_mail]                       BIT             NULL,
    [left_voice_mail_name]                  NVARCHAR (255)  NULL,
    [ltf_address_1_address_type_code]       INT             NULL,
    [ltf_address_1_address_type_code_name]  NVARCHAR (255)  NULL,
    [ltf_address_1_city]                    NVARCHAR (50)   NULL,
    [ltf_address_1_country]                 NVARCHAR (50)   NULL,
    [ltf_address_1_county]                  NVARCHAR (50)   NULL,
    [ltf_address_1_line_1]                  NVARCHAR (50)   NULL,
    [ltf_address_1_line_2]                  NVARCHAR (50)   NULL,
    [ltf_address_1_line_3]                  NVARCHAR (50)   NULL,
    [ltf_address_1_postal_code]             NVARCHAR (20)   NULL,
    [ltf_address_1_post_office_box]         NVARCHAR (20)   NULL,
    [ltf_address_1_state_or_province]       NVARCHAR (50)   NULL,
    [ltf_business_unit_guest_visit_id_name] NVARCHAR (160)  NULL,
    [ltf_club_id_name]                      NVARCHAR (100)  NULL,
    [ltf_date_of_birth]                     DATETIME        NULL,
    [ltf_email_address_1]                   NVARCHAR (100)  NULL,
    [ltf_employer]                          NVARCHAR (200)  NULL,
    [ltf_first_name]                        NVARCHAR (50)   NULL,
    [ltf_gender]                            INT             NULL,
    [ltf_gender_name]                       NVARCHAR (255)  NULL,
    [ltf_guest_type]                        INT             NULL,
    [ltf_guest_type_name]                   NVARCHAR (255)  NULL,
    [ltf_last_name]                         NVARCHAR (50)   NULL,
    [ltf_middle_name]                       NVARCHAR (50)   NULL,
    [ltf_mobile_phone]                      NVARCHAR (50)   NULL,
    [ltf_pager]                             NVARCHAR (50)   NULL,
    [ltf_referred_by_name]                  NVARCHAR (160)  NULL,
    [ltf_referred_by_yomi_name]             NVARCHAR (160)  NULL,
    [ltf_telephone1]                        NVARCHAR (50)   NULL,
    [ltf_telephone2]                        NVARCHAR (50)   NULL,
    [ltf_telephone3]                        NVARCHAR (50)   NULL,
    [ltf_websiteurl]                        NVARCHAR (100)  NULL,
    [modified_by_name]                      NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                 NVARCHAR (200)  NULL,
    [modified_on]                           DATETIME        NULL,
    [modified_on_behalf_by_name]            NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]       NVARCHAR (200)  NULL,
    [new_club_name_name]                    NVARCHAR (100)  NULL,
    [optional_attendees]                    NVARCHAR (2000) NULL,
    [organizer]                             NVARCHAR (2000) NULL,
    [overridden_created_on]                 DATETIME        NULL,
    [owner_id_name]                         NVARCHAR (200)  NULL,
    [owner_id_type]                         NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                    NVARCHAR (200)  NULL,
    [partners]                              NVARCHAR (2000) NULL,
    [postpone_activity_processing_until]    DATETIME        NULL,
    [priority_code]                         INT             NULL,
    [priority_code_name]                    NVARCHAR (255)  NULL,
    [regarding_object_id_name]              VARCHAR (8000)  NULL,
    [regarding_object_id_yomi_name]         VARCHAR (8000)  NULL,
    [regarding_object_type_code]            NVARCHAR (64)   NULL,
    [required_attendees]                    NVARCHAR (2000) NULL,
    [resources]                             NVARCHAR (2000) NULL,
    [scheduled_duration_minutes]            INT             NULL,
    [scheduled_end]                         DATETIME        NULL,
    [scheduled_start]                       DATETIME        NULL,
    [sender_mail_box_id_name]               NVARCHAR (200)  NULL,
    [sent_on]                               DATETIME        NULL,
    [service_id_name]                       NVARCHAR (160)  NULL,
    [state_code]                            INT             NULL,
    [state_code_name]                       NVARCHAR (255)  NULL,
    [status_code]                           INT             NULL,
    [status_code_name]                      NVARCHAR (255)  NULL,
    [subject]                               NVARCHAR (200)  NULL,
    [timezone_rule_version_number]          INT             NULL,
    [to]                                    NVARCHAR (2000) NULL,
    [transaction_currency_id_name]          NVARCHAR (100)  NULL,
    [utc_conversion_timezone_code]          INT             NULL,
    [version_number]                        BIGINT          NULL,
    [inserted_date_time]                    DATETIME        NULL,
    [insert_user]                           VARCHAR (50)    NULL,
    [updated_date_time]                     DATETIME        NULL,
    [update_user]                           VARCHAR (50)    NULL,
    [activity_additional_params]            VARCHAR (8000)  NULL,
    [community]                             INT             NULL,
    [community_name]                        NVARCHAR (255)  NULL,
    [ltf_assigned_mea_name]                 NVARCHAR (200)  NULL,
    [ltf_assigned_mea_yomi_name]            NVARCHAR (200)  NULL,
    [traversed_path]                        NVARCHAR (1250) NULL,
    [ltf_appointment_id_name]               NVARCHAR (200)  NULL,
    [ltf_club_close_to]                     INT             NULL,
    [ltf_club_close_to_name]                NVARCHAR (255)  NULL,
    [ltf_interests]                         NVARCHAR (1000) NULL,
    [ltf_lead_id_name]                      NVARCHAR (160)  NULL,
    [ltf_matching_contact_count]            NVARCHAR (100)  NULL,
    [ltf_matching_lead_count]               NVARCHAR (100)  NULL,
    [ltf_membership_interest]               INT             NULL,
    [ltf_membership_interest_name]          NVARCHAR (255)  NULL,
    [ltf_online]                            INT             NULL,
    [ltf_online_name]                       NVARCHAR (255)  NULL,
    [ltf_out_of_area]                       INT             NULL,
    [ltf_out_of_area_name]                  NVARCHAR (255)  NULL,
    [ltf_referral_source]                   INT             NULL,
    [ltf_referral_source_name]              NVARCHAR (255)  NULL,
    [ltf_request_date]                      DATETIME        NULL,
    [ltf_same_day]                          INT             NULL,
    [ltf_same_day_name]                     NVARCHAR (255)  NULL,
    [ltf_agreement_signature]               VARCHAR (8000)  NULL,
    [ltf_campaign_instance_name]            NVARCHAR (100)  NULL,
    [ltf_deduct_guest_priv]                 BIT             NULL,
    [ltf_qr_code_used]                      BIT             NULL,
    [ltf_source]                            NVARCHAR (100)  NULL,
    [ltf_timeout]                           BIT             NULL,
    [ltf_timeout_service]                   NVARCHAR (100)  NULL,
    [ltf_most_recent_casl]                  DATETIME        NULL,
    [ltf_grace_visit]                       BIT             NULL,
    [ltf_line_of_business]                  INT             NULL,
    [ltf_line_of_business_name]             NVARCHAR (255)  NULL,
    [dv_load_date_time]                     DATETIME        NOT NULL,
    [dv_r_load_source_id]                   BIGINT          NOT NULL,
    [dv_inserted_date_time]                 DATETIME        NOT NULL,
    [dv_insert_user]                        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                  DATETIME        NULL,
    [dv_update_user]                        VARCHAR (50)    NULL,
    [dv_hash]                               CHAR (32)       NOT NULL,
    [dv_deleted]                            BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                           BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

