CREATE TABLE [dbo].[s_crmcloudsync_appointment] (
    [s_crmcloudsync_appointment_id]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)      NOT NULL,
    [activity_id]                     VARCHAR (36)   NULL,
    [activity_type_code]              VARCHAR (64)   NULL,
    [activity_type_code_name]         VARCHAR (255)  NULL,
    [actual_duration_minutes]         INT            NULL,
    [actual_end]                      DATETIME       NULL,
    [actual_start]                    DATETIME       NULL,
    [category]                        VARCHAR (250)  NULL,
    [created_by_name]                 VARCHAR (200)  NULL,
    [created_by_yomi_name]            VARCHAR (200)  NULL,
    [created_on]                      DATETIME       NULL,
    [created_on_behalf_by_name]       VARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]  VARCHAR (200)  NULL,
    [description]                     VARCHAR (8000) NULL,
    [exchange_rate]                   DECIMAL (28)   NULL,
    [global_object_id]                VARCHAR (300)  NULL,
    [import_sequence_number]          INT            NULL,
    [instance_type_code]              INT            NULL,
    [instance_type_code_name]         VARCHAR (255)  NULL,
    [is_all_day_event_name]           VARCHAR (255)  NULL,
    [is_billed_name]                  VARCHAR (255)  NULL,
    [is_mapi_private_name]            VARCHAR (255)  NULL,
    [is_regular_activity_name]        VARCHAR (255)  NULL,
    [is_workflow_created_name]        VARCHAR (255)  NULL,
    [location]                        VARCHAR (200)  NULL,
    [ltf_appointment_type]            INT            NULL,
    [ltf_appointment_type_name]       VARCHAR (255)  NULL,
    [ltf_club_appointment_sid_name]   VARCHAR (100)  NULL,
    [ltf_udw_id]                      VARCHAR (255)  NULL,
    [ltf_club_id_name]                VARCHAR (100)  NULL,
    [modified_by_name]                VARCHAR (200)  NULL,
    [modified_by_yomi_name]           VARCHAR (200)  NULL,
    [modified_fields_mask]            VARCHAR (8000) NULL,
    [modified_on]                     DATETIME       NULL,
    [modified_on_behalf_by_name]      VARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name] VARCHAR (200)  NULL,
    [optional_attendees]              VARCHAR (2000) NULL,
    [organizer]                       VARCHAR (2000) NULL,
    [original_start_date]             DATETIME       NULL,
    [over_ridden_created_on]          DATETIME       NULL,
    [owner_id_name]                   VARCHAR (200)  NULL,
    [owner_id_type]                   VARCHAR (64)   NULL,
    [owner_id_yomi_name]              VARCHAR (200)  NULL,
    [priority_code]                   INT            NULL,
    [priority_code_name]              VARCHAR (255)  NULL,
    [regarding_object_id_name]        VARCHAR (8000) NULL,
    [regarding_object_id_yomi_name]   VARCHAR (8000) NULL,
    [regarding_object_type_code]      VARCHAR (64)   NULL,
    [required_attendees]              VARCHAR (2000) NULL,
    [scheduled_duration_minutes]      INT            NULL,
    [scheduled_end]                   DATETIME       NULL,
    [scheduled_start]                 DATETIME       NULL,
    [state_code]                      INT            NULL,
    [state_code_name]                 VARCHAR (255)  NULL,
    [status_code]                     INT            NULL,
    [status_code_name]                VARCHAR (255)  NULL,
    [sub_category]                    VARCHAR (250)  NULL,
    [subject]                         VARCHAR (200)  NULL,
    [time_zone_rule_version_number]   INT            NULL,
    [transaction_currency_id_name]    VARCHAR (100)  NULL,
    [utc_conversion_time_zone_code]   INT            NULL,
    [version_number]                  BIGINT         NULL,
    [inserted_date_time]              DATETIME       NULL,
    [insert_user]                     VARCHAR (100)  NULL,
    [ltf_met_on_tour]                 VARCHAR (200)  NULL,
    [updated_date_time]               DATETIME       NULL,
    [update_user]                     VARCHAR (50)   NULL,
    [ltf_web_booking_source]          INT            NULL,
    [ltf_web_booking_source_name]     VARCHAR (255)  NULL,
    [ltf_check_in_flag]               INT            NULL,
    [ltf_check_in_flag_name]          VARCHAR (255)  NULL,
    [ltf_program]                     INT            NULL,
    [ltf_program_name]                VARCHAR (255)  NULL,
    [traversed_path]                  VARCHAR (1250) NULL,
    [ltf_qr_code]                     VARCHAR (8000) NULL,
    [dv_load_date_time]               DATETIME       NOT NULL,
    [dv_batch_id]                     BIGINT         NOT NULL,
    [dv_r_load_source_id]             BIGINT         NOT NULL,
    [dv_inserted_date_time]           DATETIME       NOT NULL,
    [dv_insert_user]                  VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]            DATETIME       NULL,
    [dv_update_user]                  VARCHAR (50)   NULL,
    [dv_hash]                         CHAR (32)      NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_crmcloudsync_appointment]
    ON [dbo].[s_crmcloudsync_appointment]([bk_hash] ASC, [s_crmcloudsync_appointment_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_appointment]([dv_batch_id] ASC);

