CREATE TABLE [dbo].[s_crmcloudsync_opportunity] (
    [s_crmcloudsync_opportunity_id]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)       NOT NULL,
    [account_id_name]                         NVARCHAR (160)  NULL,
    [account_id_yomi_name]                    NVARCHAR (160)  NULL,
    [actual_close_date]                       DATETIME        NULL,
    [actual_value]                            DECIMAL (26, 6) NULL,
    [actual_value_base]                       DECIMAL (26, 6) NULL,
    [budget_amount]                           DECIMAL (26, 6) NULL,
    [budget_amount_base]                      DECIMAL (26, 6) NULL,
    [budget_status]                           INT             NULL,
    [budget_type_name]                        NVARCHAR (255)  NULL,
    [campaign_id_name]                        NVARCHAR (128)  NULL,
    [capture_proposal_feedback]               BIT             NULL,
    [capture_proposal_feedback_name]          NVARCHAR (255)  NULL,
    [close_probability]                       INT             NULL,
    [complete_final_proposal]                 BIT             NULL,
    [complete_final_proposal_name]            NVARCHAR (255)  NULL,
    [complete_internal_review]                BIT             NULL,
    [complete_internal_review_name]           NVARCHAR (255)  NULL,
    [confirm_interest]                        BIT             NULL,
    [confirm_interest_name]                   NVARCHAR (255)  NULL,
    [contact_id_name]                         NVARCHAR (160)  NULL,
    [contact_id_yomi_name]                    NVARCHAR (160)  NULL,
    [created_by_name]                         NVARCHAR (200)  NULL,
    [created_by_yomi_name]                    NVARCHAR (200)  NULL,
    [created_on]                              DATETIME        NULL,
    [created_on_behalf_by_name]               NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]          NVARCHAR (200)  NULL,
    [current_situation]                       NVARCHAR (4000) NULL,
    [customer_id_name]                        NVARCHAR (160)  NULL,
    [customer_id_type]                        NVARCHAR (64)   NULL,
    [customer_id_yomi_name]                   NVARCHAR (450)  NULL,
    [customer_need]                           NVARCHAR (4000) NULL,
    [customer_pain_points]                    NVARCHAR (4000) NULL,
    [decision_maker]                          BIT             NULL,
    [decision_maker_name]                     NVARCHAR (255)  NULL,
    [description]                             NVARCHAR (4000) NULL,
    [develop_proposal]                        BIT             NULL,
    [develop_proposal_name]                   NVARCHAR (255)  NULL,
    [discount_amount]                         DECIMAL (26, 6) NULL,
    [discount_amount_base]                    DECIMAL (26, 6) NULL,
    [discount_percentage]                     DECIMAL (28)    NULL,
    [estimated_close_date]                    DATETIME        NULL,
    [estimated_value]                         DECIMAL (26, 6) NULL,
    [estimated_value_base]                    DECIMAL (26, 6) NULL,
    [evaluate_fit]                            BIT             NULL,
    [evaluate_fit_name]                       NVARCHAR (255)  NULL,
    [exchange_rate]                           DECIMAL (28)    NULL,
    [filede_brief]                            BIT             NULL,
    [filede_brief_name]                       NVARCHAR (255)  NULL,
    [final_decision_date]                     DATETIME        NULL,
    [freight_amount]                          DECIMAL (26, 6) NULL,
    [freight_amount_base]                     DECIMAL (26, 6) NULL,
    [identify_competitors]                    BIT             NULL,
    [identify_competitors_name]               NVARCHAR (255)  NULL,
    [identify_customer_contacts]              BIT             NULL,
    [identify_customer_contacts_name]         NVARCHAR (255)  NULL,
    [identify_pursuit_team]                   BIT             NULL,
    [identify_pursuit_team_name]              NVARCHAR (255)  NULL,
    [import_sequence_number]                  INT             NULL,
    [initial_communication]                   INT             NULL,
    [initial_communication_name]              NVARCHAR (255)  NULL,
    [is_private_name]                         NVARCHAR (255)  NULL,
    [is_revenue_system_calculated]            BIT             NULL,
    [is_revenuesystem_calculated_name]        NVARCHAR (255)  NULL,
    [ltf_best_time_to_contact]                INT             NULL,
    [ltf_best_time_to_contact_name]           NVARCHAR (255)  NULL,
    [ltf_club_id_name]                        NVARCHAR (100)  NULL,
    [ltf_club_proximity]                      INT             NULL,
    [ltf_club_proximity_name]                 NVARCHAR (255)  NULL,
    [ltf_commitment_level]                    INT             NULL,
    [ltf_commitment_level_name]               NVARCHAR (255)  NULL,
    [ltf_commitment_reason]                   NVARCHAR (4000) NULL,
    [ltf_employer_wellness_program]           INT             NULL,
    [ltf_employer_wellness_program_name]      NVARCHAR (255)  NULL,
    [ltf_exercise_history]                    INT             NULL,
    [ltf_exercise_history_name]               NVARCHAR (255)  NULL,
    [ltf_ims_join_link]                       NVARCHAR (300)  NULL,
    [ltf_injuries_or_limitations]             BIT             NULL,
    [ltf_injuries_or_limitations_description] NVARCHAR (4000) NULL,
    [ltf_injuries_or_limitations_name]        NVARCHAR (255)  NULL,
    [ltf_inquiry_type]                        NVARCHAR (100)  NULL,
    [ltf_last_activity]                       DATETIME        NULL,
    [ltf_lead_source]                         INT             NULL,
    [ltf_lead_source_name]                    NVARCHAR (255)  NULL,
    [ltf_lead_type]                           INT             NULL,
    [ltf_lead_type_name]                      NVARCHAR (255)  NULL,
    [ltf_managed_until]                       DATETIME        NULL,
    [ltf_measurable_goal]                     INT             NULL,
    [ltf_measurable_goal_id_name]             NVARCHAR (100)  NULL,
    [ltf_measurable_goal_name]                NVARCHAR (255)  NULL,
    [ltf_membership_info_requested]           NVARCHAR (50)   NULL,
    [ltf_membership_level]                    INT             NULL,
    [ltf_membership_level_name]               NVARCHAR (255)  NULL,
    [ltf_membership_type]                     INT             NULL,
    [ltf_membership_type_name]                NVARCHAR (255)  NULL,
    [ltf_nugget]                              NVARCHAR (4000) NULL,
    [ltf_park]                                BIT             NULL,
    [ltf_park_comments]                       NVARCHAR (400)  NULL,
    [ltf_park_name]                           NVARCHAR (255)  NULL,
    [ltf_park_reason]                         INT             NULL,
    [ltf_park_reason_name]                    NVARCHAR (255)  NULL,
    [ltf_park_until]                          DATETIME        NULL,
    [ltf_past_trainer_or_coach]               BIT             NULL,
    [ltf_past_trainer_or_coach_name]          NVARCHAR (255)  NULL,
    [ltf_primary_objective]                   INT             NULL,
    [ltf_primary_objective_id_name]           NVARCHAR (100)  NULL,
    [ltf_primary_objective_name]              NVARCHAR (255)  NULL,
    [ltf_promo_code]                          NVARCHAR (100)  NULL,
    [ltf_prospect_type]                       INT             NULL,
    [ltf_prospect_type_name]                  NVARCHAR (255)  NULL,
    [ltf_referring_contact_id_name]           NVARCHAR (160)  NULL,
    [ltf_referring_contact_id_yomi_name]      NVARCHAR (160)  NULL,
    [ltf_registration_code]                   NVARCHAR (100)  NULL,
    [ltf_request_type]                        NVARCHAR (100)  NULL,
    [ltf_specific_goal]                       INT             NULL,
    [ltf_specific_goal_id_name]               NVARCHAR (100)  NULL,
    [ltf_specific_goal_name]                  NVARCHAR (255)  NULL,
    [ltf_time_goal]                           DATETIME        NULL,
    [ltf_todays_action]                       INT             NULL,
    [ltf_todays_action_name]                  NVARCHAR (255)  NULL,
    [ltf_trainer_or_coach_preference]         INT             NULL,
    [ltf_trainer_or_coach_preference_name]    NVARCHAR (255)  NULL,
    [ltf_web_team_id_name]                    NVARCHAR (160)  NULL,
    [ltf_web_team_id_yomi_name]               NVARCHAR (160)  NULL,
    [ltf_workout_preference]                  INT             NULL,
    [ltf_workout_preference_name]             NVARCHAR (255)  NULL,
    [modified_by_name]                        NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                   NVARCHAR (200)  NULL,
    [modified_on]                             DATETIME        NULL,
    [modified_on_behalf_by_name]              NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]         NVARCHAR (200)  NULL,
    [name]                                    NVARCHAR (300)  NULL,
    [need]                                    INT             NULL,
    [need_name]                               NVARCHAR (255)  NULL,
    [opportunity_id]                          VARCHAR (36)    NULL,
    [opportunity_rating_code]                 INT             NULL,
    [opportunity_rating_code_name]            NVARCHAR (255)  NULL,
    [originating_lead_id_name]                NVARCHAR (160)  NULL,
    [originating_lead_id_yomi_name]           NVARCHAR (160)  NULL,
    [overridden_created_on]                   DATETIME        NULL,
    [owner_id_name]                           NVARCHAR (200)  NULL,
    [owner_id_type]                           NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                      NVARCHAR (200)  NULL,
    [parent_account_id_name]                  NVARCHAR (160)  NULL,
    [parent_account_id_yomi_name]             NVARCHAR (160)  NULL,
    [parent_contact_id_name]                  NVARCHAR (160)  NULL,
    [parent_contact_id_yomi_name]             NVARCHAR (160)  NULL,
    [participates_in_workflow]                BIT             NULL,
    [participates_in_workflow_name]           NVARCHAR (255)  NULL,
    [present_final_proposal]                  BIT             NULL,
    [present_final_proposal_name]             NVARCHAR (255)  NULL,
    [present_proposal]                        BIT             NULL,
    [present_proposal_name]                   NVARCHAR (255)  NULL,
    [price_level_id_name]                     NVARCHAR (100)  NULL,
    [pricing_error_code]                      INT             NULL,
    [pricing_error_code_name]                 NVARCHAR (255)  NULL,
    [priority_code]                           INT             NULL,
    [priority_code_name]                      NVARCHAR (255)  NULL,
    [proposed_solution]                       NVARCHAR (4000) NULL,
    [purchase_process]                        INT             NULL,
    [purchase_process_name]                   NVARCHAR (255)  NULL,
    [purchase_time_frame]                     INT             NULL,
    [purchase_time_frame_name]                NVARCHAR (255)  NULL,
    [pursuit_decision]                        BIT             NULL,
    [pursuit_decision_name]                   NVARCHAR (255)  NULL,
    [qualification_comments]                  NVARCHAR (4000) NULL,
    [quote_comments]                          NVARCHAR (4000) NULL,
    [resolve_feedback]                        BIT             NULL,
    [resolve_feedback_name]                   NVARCHAR (255)  NULL,
    [sales_stage]                             INT             NULL,
    [sales_stage_code]                        INT             NULL,
    [sales_stage_code_name]                   NVARCHAR (255)  NULL,
    [sales_stage_name]                        NVARCHAR (255)  NULL,
    [schedule_follow_up_prospect]             DATETIME        NULL,
    [schedule_follow_up_qualify]              DATETIME        NULL,
    [schedule_proposal_meeting]               DATETIME        NULL,
    [send_thank_you_note]                     BIT             NULL,
    [send_thank_you_note_name]                NVARCHAR (255)  NULL,
    [state_code]                              INT             NULL,
    [state_code_name]                         NVARCHAR (255)  NULL,
    [status_code]                             INT             NULL,
    [status_code_name]                        NVARCHAR (255)  NULL,
    [step_name]                               NVARCHAR (200)  NULL,
    [time_line]                               INT             NULL,
    [time_line_name]                          NVARCHAR (255)  NULL,
    [time_zone_rule_version_number]           INT             NULL,
    [total_amount]                            DECIMAL (26, 6) NULL,
    [total_amount_base]                       DECIMAL (26, 6) NULL,
    [total_amount_less_freight]               DECIMAL (26, 6) NULL,
    [total_amount_less_freight_base]          DECIMAL (26, 6) NULL,
    [total_discount_amount]                   DECIMAL (26, 6) NULL,
    [total_discount_amount_base]              DECIMAL (26, 6) NULL,
    [total_line_item_amount]                  DECIMAL (26, 6) NULL,
    [total_line_item_amount_base]             DECIMAL (26, 6) NULL,
    [total_line_item_discount_amount]         DECIMAL (26, 6) NULL,
    [total_line_item_discount_amount_base]    DECIMAL (26, 6) NULL,
    [total_tax]                               DECIMAL (26, 6) NULL,
    [total_tax_base]                          DECIMAL (26, 6) NULL,
    [transaction_currency_id_name]            NVARCHAR (100)  NULL,
    [utc_conversion_time_zone_code]           INT             NULL,
    [version_number]                          BIGINT          NULL,
    [inserted_date_time]                      DATETIME        NULL,
    [insert_user]                             VARCHAR (100)   NULL,
    [updated_date_time]                       DATETIME        NULL,
    [update_user]                             VARCHAR (50)    NULL,
    [ltf_profile_notes]                       NVARCHAR (4000) NULL,
    [ltf_programs_of_interest]                INT             NULL,
    [ltf_programs_of_interest_name]           NVARCHAR (255)  NULL,
    [ltf_want_to_do]                          INT             NULL,
    [ltf_want_to_do_name]                     NVARCHAR (255)  NULL,
    [ltf_why_want_to_do]                      INT             NULL,
    [ltf_why_want_to_do_name]                 NVARCHAR (255)  NULL,
    [ltf_who_met_with]                        NVARCHAR (100)  NULL,
    [ltf_recommended_membership]              INT             NULL,
    [ltf_recommended_membership_name]         NVARCHAR (255)  NULL,
    [ltf_resistance]                          INT             NULL,
    [ltf_resistance_name]                     NVARCHAR (255)  NULL,
    [traversed_path]                          NVARCHAR (1250) NULL,
    [ltf_web_transfer_method]                 INT             NULL,
    [ltf_web_transfer_method_name]            NVARCHAR (255)  NULL,
    [ltf_basket_ball]                         INT             NULL,
    [ltf_climbing]                            INT             NULL,
    [ltf_commitment]                          INT             NULL,
    [ltf_cycling]                             INT             NULL,
    [ltf_guest_pass_expiration_date]          DATETIME        NULL,
    [ltf_kids_club]                           BIT             NULL,
    [ltf_kids_club_name]                      NVARCHAR (255)  NULL,
    [ltf_next_follow_up]                      DATETIME        NULL,
    [ltf_personal_training]                   BIT             NULL,
    [ltf_personal_training_name]              NVARCHAR (255)  NULL,
    [ltf_ready_to_join]                       BIT             NULL,
    [ltf_ready_to_join_name]                  NVARCHAR (255)  NULL,
    [ltf_signature]                           VARCHAR (8000)  NULL,
    [ltf_swimming]                            BIT             NULL,
    [ltf_swimming_name]                       NVARCHAR (255)  NULL,
    [ltf_tennis_lessons]                      BIT             NULL,
    [ltf_tennis_lessons_name]                 NVARCHAR (255)  NULL,
    [ltf_yoga]                                INT             NULL,
    [ltf_assigned_by_app]                     INT             NULL,
    [ltf_assigned_by_app_name]                NVARCHAR (255)  NULL,
    [ltf_assigned_to_club_date]               DATETIME        NULL,
    [ltf_ims_join_send_date]                  DATETIME        NULL,
    [ltf_is_ims_join]                         BIT             NULL,
    [ltf_is_ims_join_name]                    NVARCHAR (255)  NULL,
    [ltf_number_over_14_list]                 INT             NULL,
    [ltf_number_over_14_list_name]            NVARCHAR (255)  NULL,
    [ltf_number_under_14_list]                INT             NULL,
    [ltf_number_under_14_list_name]           NVARCHAR (255)  NULL,
    [ltf_promo_quoted]                        NVARCHAR (100)  NULL,
    [ltf_selected_interest_ids]               NVARCHAR (1000) NULL,
    [ltf_originating_guest_visit_name]        NVARCHAR (200)  NULL,
    [ltf_assignment_request_date]             DATETIME        NULL,
    [ltf_assignment_request_id]               NVARCHAR (100)  NULL,
    [ltf_line_of_business]                    INT             NULL,
    [ltf_channel]                             INT             NULL,
    [ltf_line_of_business_name]               NVARCHAR (255)  NULL,
    [ltf_channel_name]                        NVARCHAR (255)  NULL,
    [dv_load_date_time]                       DATETIME        NOT NULL,
    [dv_r_load_source_id]                     BIGINT          NOT NULL,
    [dv_inserted_date_time]                   DATETIME        NOT NULL,
    [dv_insert_user]                          VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                    DATETIME        NULL,
    [dv_update_user]                          VARCHAR (50)    NULL,
    [dv_hash]                                 CHAR (32)       NOT NULL,
    [dv_deleted]                              BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                             BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

