CREATE TABLE [dbo].[s_crmcloudsync_task] (
    [s_crmcloudsync_task_id]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [activity_id]                          VARCHAR (36)    NULL,
    [activity_type_code]                   NVARCHAR (64)   NULL,
    [activity_type_code_name]              NVARCHAR (255)  NULL,
    [actual_duration_minutes]              INT             NULL,
    [actual_end]                           DATETIME        NULL,
    [actual_start]                         DATETIME        NULL,
    [category]                             NVARCHAR (250)  NULL,
    [created_by_name]                      NVARCHAR (200)  NULL,
    [created_by_yomi_name]                 NVARCHAR (200)  NULL,
    [created_on]                           DATETIME        NULL,
    [created_on_behalf_by_name]            NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]       NVARCHAR (200)  NULL,
    [description]                          NVARCHAR (4000) NULL,
    [exchange_rate]                        DECIMAL (28)    NULL,
    [import_sequence_number]               INT             NULL,
    [is_billed]                            BIT             NULL,
    [is_billed_name]                       NVARCHAR (255)  NULL,
    [is_regular_activity]                  BIT             NULL,
    [is_regular_activity_name]             NVARCHAR (255)  NULL,
    [is_workflow_created]                  BIT             NULL,
    [is_workflow_created_name]             NVARCHAR (255)  NULL,
    [ltf_my_health_score_scheduled_date]   DATETIME        NULL,
    [ltf_task_type]                        INT             NULL,
    [ltf_task_type_name]                   NVARCHAR (255)  NULL,
    [ltf_training_services_scheduled_date] DATETIME        NULL,
    [modified_by_name]                     NVARCHAR (200)  NULL,
    [modified_by_yomi_name]                NVARCHAR (200)  NULL,
    [modified_on]                          DATETIME        NULL,
    [modified_on_behalf_by_name]           NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]      NVARCHAR (200)  NULL,
    [overridden_created_on]                DATETIME        NULL,
    [owner_id_name]                        NVARCHAR (200)  NULL,
    [owner_id_type]                        NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                   NVARCHAR (200)  NULL,
    [percent_complete]                     INT             NULL,
    [priority_code]                        INT             NULL,
    [priority_code_name]                   NVARCHAR (255)  NULL,
    [regarding_object_id_name]             VARCHAR (8000)  NULL,
    [regarding_object_id_yomi_name]        VARCHAR (8000)  NULL,
    [regarding_object_type_code]           NVARCHAR (64)   NULL,
    [scheduled_duration_minutes]           INT             NULL,
    [scheduled_end]                        DATETIME        NULL,
    [scheduled_start]                      DATETIME        NULL,
    [state_code]                           INT             NULL,
    [state_code_name]                      NVARCHAR (255)  NULL,
    [status_code]                          INT             NULL,
    [status_code_name]                     NVARCHAR (255)  NULL,
    [sub_category]                         NVARCHAR (250)  NULL,
    [subject]                              NVARCHAR (200)  NULL,
    [timezone_rule_version_number]         INT             NULL,
    [transaction_currency_id_name]         NVARCHAR (100)  NULL,
    [utc_conversion_timezone_code]         INT             NULL,
    [version_number]                       BIGINT          NULL,
    [inserted_date_time]                   DATETIME        NULL,
    [insert_user]                          VARCHAR (100)   NULL,
    [ltf_health_score_scheduled_name]      NVARCHAR (200)  NULL,
    [ltf_training_services_scheduled_name] NVARCHAR (200)  NULL,
    [ltf_who_me_ton_tour]                  NVARCHAR (300)  NULL,
    [updated_date_time]                    DATETIME        NULL,
    [update_user]                          VARCHAR (50)    NULL,
    [traversed_path]                       NVARCHAR (1250) NULL,
    [dv_load_date_time]                    DATETIME        NOT NULL,
    [dv_r_load_source_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL,
    [dv_hash]                              CHAR (32)       NOT NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_task]([dv_batch_id] ASC);

