CREATE TABLE [dbo].[s_crmcloudsync_contact] (
    [s_crmcloudsync_contact_id]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)        NOT NULL,
    [account_id_name]                         NVARCHAR (160)   NULL,
    [account_id_yomi_name]                    NVARCHAR (160)   NULL,
    [account_role_code]                       INT              NULL,
    [account_role_code_name]                  NVARCHAR (255)   NULL,
    [address_1_address_type_code]             INT              NULL,
    [address_1_address_type_code_name]        NVARCHAR (255)   NULL,
    [address_1_city]                          NVARCHAR (80)    NULL,
    [address_1_composite]                     NVARCHAR (4000)  NULL,
    [address_1_country]                       NVARCHAR (80)    NULL,
    [address_1_county]                        NVARCHAR (50)    NULL,
    [address_1_fax]                           NVARCHAR (50)    NULL,
    [address_1_freight_terms_code]            INT              NULL,
    [address_1_freight_terms_code_name]       NVARCHAR (255)   NULL,
    [address_1_latitude]                      DECIMAL (26, 6)  NULL,
    [address_1_line_1]                        NVARCHAR (250)   NULL,
    [address_1_line_2]                        NVARCHAR (250)   NULL,
    [address_1_line_3]                        NVARCHAR (250)   NULL,
    [address_1_longitude]                     DECIMAL (26, 6)  NULL,
    [address_1_name]                          NVARCHAR (200)   NULL,
    [address_1_postal_code]                   NVARCHAR (20)    NULL,
    [address_1_post_office_box]               NVARCHAR (20)    NULL,
    [address_1_primary_contact_name]          NVARCHAR (100)   NULL,
    [address_1_shipping_method_code]          INT              NULL,
    [address_1_shipping_method_code_name]     NVARCHAR (255)   NULL,
    [address_1_state_or_province]             NVARCHAR (50)    NULL,
    [address_1_telephone_1]                   NVARCHAR (50)    NULL,
    [address_1_telephone_2]                   NVARCHAR (50)    NULL,
    [address_1_telephone_3]                   NVARCHAR (50)    NULL,
    [address_1_ups_zone]                      NVARCHAR (4)     NULL,
    [address_1_utc_offset]                    INT              NULL,
    [address_2_address_type_code]             INT              NULL,
    [address_2_address_type_code_name]        NVARCHAR (255)   NULL,
    [address_2_city]                          NVARCHAR (80)    NULL,
    [address_2_composite]                     NVARCHAR (4000)  NULL,
    [address_2_country]                       NVARCHAR (80)    NULL,
    [address_2_county]                        NVARCHAR (50)    NULL,
    [address_2_fax]                           NVARCHAR (50)    NULL,
    [address_2_freight_terms_code]            INT              NULL,
    [address_2_freight_terms_code_name]       NVARCHAR (255)   NULL,
    [address_2_latitude]                      DECIMAL (26, 6)  NULL,
    [address_2_line_1]                        NVARCHAR (250)   NULL,
    [address_2_line_2]                        NVARCHAR (250)   NULL,
    [address_2_line_3]                        NVARCHAR (250)   NULL,
    [address_2_longitude]                     DECIMAL (26, 6)  NULL,
    [address_2_name]                          NVARCHAR (100)   NULL,
    [address_2_postal_code]                   NVARCHAR (20)    NULL,
    [address_2_post_office_box]               NVARCHAR (20)    NULL,
    [address_2_primary_contact_name]          NVARCHAR (100)   NULL,
    [address_2_shipping_method_code]          INT              NULL,
    [address_2_shipping_method_code_name]     NVARCHAR (255)   NULL,
    [address_2_state_or_province]             NVARCHAR (50)    NULL,
    [address_2_telephone_1]                   NVARCHAR (50)    NULL,
    [address_2_telephone_2]                   NVARCHAR (50)    NULL,
    [address_2_telephone_3]                   NVARCHAR (50)    NULL,
    [address_2_ups_zone]                      NVARCHAR (4)     NULL,
    [address_2_utc_offset]                    INT              NULL,
    [aging_30]                                DECIMAL (26, 6)  NULL,
    [aging_30_base]                           DECIMAL (26, 6)  NULL,
    [aging_60]                                DECIMAL (26, 6)  NULL,
    [aging_60_base]                           DECIMAL (26, 6)  NULL,
    [aging_90]                                DECIMAL (26, 6)  NULL,
    [aging_90_base]                           DECIMAL (26, 6)  NULL,
    [anniversary]                             DATETIME         NULL,
    [annual_income]                           DECIMAL (26, 6)  NULL,
    [annual_income_base]                      DECIMAL (26, 6)  NULL,
    [assistant_name]                          NVARCHAR (100)   NULL,
    [assistant_phone]                         NVARCHAR (50)    NULL,
    [birth_date]                              DATETIME         NULL,
    [childrens_names]                         NVARCHAR (255)   NULL,
    [contact_id]                              VARCHAR (36)     NULL,
    [created_by_name]                         NVARCHAR (200)   NULL,
    [created_by_yomi_name]                    NVARCHAR (200)   NULL,
    [created_on]                              DATETIME         NULL,
    [created_on_behalf_by_name]               NVARCHAR (200)   NULL,
    [created_on_behalf_by_yomi_name]          NVARCHAR (200)   NULL,
    [credit_limit]                            DECIMAL (26, 6)  NULL,
    [credit_limit_base]                       DECIMAL (26, 6)  NULL,
    [credit_on_hold]                          BIT              NULL,
    [credit_on_hold_name]                     NVARCHAR (255)   NULL,
    [customer_size_code]                      INT              NULL,
    [customer_size_code_name]                 NVARCHAR (255)   NULL,
    [customer_type_code]                      INT              NULL,
    [customer_type_code_name]                 NVARCHAR (255)   NULL,
    [default_price_level_id_name]             NVARCHAR (100)   NULL,
    [department]                              NVARCHAR (100)   NULL,
    [description]                             NVARCHAR (4000)  NULL,
    [do_not_bulk_email]                       BIT              NULL,
    [do_not_bulk_email_name]                  NVARCHAR (255)   NULL,
    [do_not_bulk_postal_mail]                 BIT              NULL,
    [do_not_bulk_postal_mail_name]            NVARCHAR (255)   NULL,
    [do_not_email]                            BIT              NULL,
    [do_not_email_name]                       NVARCHAR (255)   NULL,
    [do_not_fax]                              BIT              NULL,
    [do_not_fax_name]                         NVARCHAR (255)   NULL,
    [do_not_phone]                            BIT              NULL,
    [do_not_phone_name]                       NVARCHAR (255)   NULL,
    [do_not_postal_mail]                      BIT              NULL,
    [do_not_postal_mail_name]                 NVARCHAR (255)   NULL,
    [do_not_send_marketing_material_name]     NVARCHAR (255)   NULL,
    [do_not_send_mm]                          BIT              NULL,
    [education_code]                          INT              NULL,
    [education_code_name]                     NVARCHAR (255)   NULL,
    [email_address_1]                         NVARCHAR (100)   NULL,
    [email_address_2]                         NVARCHAR (100)   NULL,
    [email_address_3]                         NVARCHAR (100)   NULL,
    [entity_image]                            VARBINARY (8000) NULL,
    [entity_image_timestamp]                  BIGINT           NULL,
    [entity_image_url]                        NVARCHAR (200)   NULL,
    [exchange_rate]                           DECIMAL (28)     NULL,
    [external_user_identifier]                NVARCHAR (50)    NULL,
    [family_status_code]                      INT              NULL,
    [family_status_code_name]                 NVARCHAR (255)   NULL,
    [fax]                                     NVARCHAR (50)    NULL,
    [first_name]                              NVARCHAR (50)    NULL,
    [ftp_site_url]                            NVARCHAR (200)   NULL,
    [full_name]                               NVARCHAR (160)   NULL,
    [gender_code]                             INT              NULL,
    [gender_code_name]                        NVARCHAR (255)   NULL,
    [has_children_code]                       INT              NULL,
    [has_children_code_name]                  NVARCHAR (255)   NULL,
    [import_sequence_number]                  INT              NULL,
    [is_back_office_customer]                 BIT              NULL,
    [is_back_office_customer_name]            NVARCHAR (255)   NULL,
    [is_private_name]                         NVARCHAR (255)   NULL,
    [job_title]                               NVARCHAR (100)   NULL,
    [last_name]                               NVARCHAR (50)    NULL,
    [last_used_in_campaign]                   DATETIME         NULL,
    [lead_source_code]                        INT              NULL,
    [lead_source_code_name]                   NVARCHAR (255)   NULL,
    [ltf_birth_year]                          NVARCHAR (4)     NULL,
    [ltf_club_id_name]                        NVARCHAR (100)   NULL,
    [ltf_club_proximity]                      INT              NULL,
    [ltf_club_proximity_name]                 NVARCHAR (255)   NULL,
    [ltf_commitment_level]                    INT              NULL,
    [ltf_commitment_level_name]               NVARCHAR (255)   NULL,
    [ltf_commitment_reason]                   NVARCHAR (4000)  NULL,
    [ltf_do_not_email_address_1]              BIT              NULL,
    [ltf_do_not_email_address_1_name]         NVARCHAR (255)   NULL,
    [ltf_do_not_email_address_2]              BIT              NULL,
    [ltf_do_not_email_address_2_name]         NVARCHAR (255)   NULL,
    [ltf_do_not_phone_mobile_phone]           BIT              NULL,
    [ltf_do_not_phone_mobile_phone_name]      NVARCHAR (255)   NULL,
    [ltf_do_not_phone_telephone_1]            BIT              NULL,
    [ltf_do_not_phone_telephone_1_name]       NVARCHAR (255)   NULL,
    [ltf_do_not_phone_telephone_2]            BIT              NULL,
    [ltf_do_not_phone_telephone_2_name]       NVARCHAR (255)   NULL,
    [ltf_employer_id_name]                    NVARCHAR (160)   NULL,
    [ltf_employer_id_yomi_name]               NVARCHAR (160)   NULL,
    [ltf_employer_wellness_program]           INT              NULL,
    [ltf_employer_wellness_program_name]      NVARCHAR (255)   NULL,
    [ltf_exercise_history]                    INT              NULL,
    [ltf_exercise_history_name]               NVARCHAR (255)   NULL,
    [ltf_injuries_or_limitations]             BIT              NULL,
    [ltf_injuries_or_limitations_description] NVARCHAR (4000)  NULL,
    [ltf_injuries_or_limitations_name]        NVARCHAR (255)   NULL,
    [ltf_inserted_by_system]                  BIT              NULL,
    [ltf_inserted_by_system_name]             NVARCHAR (255)   NULL,
    [ltf_is_employee]                         BIT              NULL,
    [ltf_is_employee_name]                    NVARCHAR (255)   NULL,
    [ltf_lead_source]                         INT              NULL,
    [ltf_lead_source_name]                    NVARCHAR (255)   NULL,
    [ltf_lead_type]                           INT              NULL,
    [ltf_lead_type_name]                      NVARCHAR (255)   NULL,
    [ltf_legacy]                              NVARCHAR (4000)  NULL,
    [ltf_measurable_goal_id_name]             NVARCHAR (100)   NULL,
    [ltf_nugget]                              NVARCHAR (4000)  NULL,
    [ltf_past_trainer_or_coach]               BIT              NULL,
    [ltf_past_trainer_or_coach_name]          NVARCHAR (255)   NULL,
    [ltf_primary_objective_id_name]           NVARCHAR (100)   NULL,
    [ltf_referring_contact_id_name]           NVARCHAR (160)   NULL,
    [ltf_referring_contact_id_yomi_name]      NVARCHAR (160)   NULL,
    [ltf_specific_goal_id_name]               NVARCHAR (100)   NULL,
    [ltf_time_goal]                           DATETIME         NULL,
    [ltf_todays_action]                       INT              NULL,
    [ltf_todays_action_name]                  NVARCHAR (255)   NULL,
    [ltf_trainer_or_coach_preference]         INT              NULL,
    [ltf_trainer_or_coach_preference_name]    NVARCHAR (255)   NULL,
    [ltf_volatile_contact]                    BIT              NULL,
    [ltf_volatile_contact_name]               NVARCHAR (255)   NULL,
    [ltf_workout_preference]                  INT              NULL,
    [ltf_workout_preference_name]             NVARCHAR (255)   NULL,
    [manager_name]                            NVARCHAR (100)   NULL,
    [manager_phone]                           NVARCHAR (50)    NULL,
    [master_contact_id_name]                  NVARCHAR (160)   NULL,
    [master_contact_id_yomi_name]             NVARCHAR (160)   NULL,
    [merged]                                  BIT              NULL,
    [merged_name]                             NVARCHAR (255)   NULL,
    [middle_name]                             NVARCHAR (50)    NULL,
    [mobile_phone]                            NVARCHAR (50)    NULL,
    [modified_by_name]                        NVARCHAR (200)   NULL,
    [modified_by_yomi_name]                   NVARCHAR (200)   NULL,
    [modified_on]                             DATETIME         NULL,
    [modified_on_behalf_by_name]              NVARCHAR (200)   NULL,
    [modified_on_behalf_by_yomi_name]         NVARCHAR (200)   NULL,
    [nick_name]                               NVARCHAR (50)    NULL,
    [number_of_children]                      INT              NULL,
    [originating_lead_id_name]                NVARCHAR (160)   NULL,
    [originating_lead_id_yomi_name]           NVARCHAR (160)   NULL,
    [over_ridden_created_on]                  DATETIME         NULL,
    [owner_id_name]                           NVARCHAR (200)   NULL,
    [owner_id_type]                           NVARCHAR (64)    NULL,
    [owner_id_yomi_name]                      NVARCHAR (200)   NULL,
    [pager]                                   NVARCHAR (50)    NULL,
    [parent_contact_id_name]                  NVARCHAR (160)   NULL,
    [parent_contact_id_yomi_name]             NVARCHAR (160)   NULL,
    [parent_customer_id_name]                 NVARCHAR (160)   NULL,
    [parent_customer_id_type]                 NVARCHAR (64)    NULL,
    [parent_customer_id_yomi_name]            NVARCHAR (450)   NULL,
    [participates_in_workflow]                BIT              NULL,
    [participates_in_workflow_name]           NVARCHAR (255)   NULL,
    [payment_terms_code]                      INT              NULL,
    [payment_terms_code_name]                 NVARCHAR (255)   NULL,
    [preferred_appointment_day_code]          INT              NULL,
    [preferred_appointment_day_code_name]     NVARCHAR (255)   NULL,
    [preferred_appointment_time_code]         INT              NULL,
    [preferred_appointment_time_code_name]    NVARCHAR (255)   NULL,
    [preferred_contact_method_code]           INT              NULL,
    [preferred_contact_method_code_name]      NVARCHAR (255)   NULL,
    [preferred_equipment_id_name]             NVARCHAR (160)   NULL,
    [preferred_service_id_name]               NVARCHAR (160)   NULL,
    [preferred_system_user_id_name]           NVARCHAR (200)   NULL,
    [preferred_system_user_id_yomi_name]      NVARCHAR (200)   NULL,
    [salutation]                              NVARCHAR (100)   NULL,
    [shipping_method_code]                    INT              NULL,
    [shipping_method_code_name]               NVARCHAR (255)   NULL,
    [spouses_name]                            NVARCHAR (100)   NULL,
    [state_code]                              INT              NULL,
    [state_code_name]                         NVARCHAR (255)   NULL,
    [status_code]                             INT              NULL,
    [status_code_name]                        NVARCHAR (255)   NULL,
    [suffix]                                  NVARCHAR (10)    NULL,
    [telephone_1]                             NVARCHAR (50)    NULL,
    [telephone_2]                             NVARCHAR (50)    NULL,
    [telephone_3]                             NVARCHAR (50)    NULL,
    [territory_code]                          INT              NULL,
    [territory_code_name]                     NVARCHAR (255)   NULL,
    [time_zone_rule_version_number]           INT              NULL,
    [transaction_currency_id_name]            NVARCHAR (100)   NULL,
    [utc_con_version_time_zone_code]          INT              NULL,
    [version_number]                          BIGINT           NULL,
    [web_site_url]                            NVARCHAR (200)   NULL,
    [yomi_first_name]                         NVARCHAR (150)   NULL,
    [yomi_full_name]                          NVARCHAR (450)   NULL,
    [yomi_last_name]                          NVARCHAR (150)   NULL,
    [yomi_middle_name]                        NVARCHAR (150)   NULL,
    [inserted_date_time]                      DATETIME         NULL,
    [insert_user]                             VARCHAR (100)    NULL,
    [ltf_measurable_goal]                     INT              NULL,
    [ltf_measurable_goal_name]                NVARCHAR (255)   NULL,
    [ltf_primary_objective]                   INT              NULL,
    [ltf_primary_objective_name]              NVARCHAR (255)   NULL,
    [ltf_specific_goal]                       INT              NULL,
    [ltf_specific_goal_name]                  NVARCHAR (255)   NULL,
    [ltf_dn_cover_ride]                       BIT              NULL,
    [ltf_dn_cover_ride_name]                  NVARCHAR (255)   NULL,
    [ltf_duplicate_over_ride]                 BIT              NULL,
    [ltf_duplicate_over_ride_name]            NVARCHAR (255)   NULL,
    [ltf_join_date]                           DATETIME         NULL,
    [ltf_member_type]                         NVARCHAR (100)   NULL,
    [ltf_risk_score]                          INT              NULL,
    [ltf_star_value]                          INT              NULL,
    [ltf_subscription_cancellation_date]      DATETIME         NULL,
    [ltf_subscription_create_date]            DATETIME         NULL,
    [ltf_subscription_product]                NVARCHAR (100)   NULL,
    [ltf_subscription_status]                 NVARCHAR (100)   NULL,
    [ltf_subscription_termination_date]       DATETIME         NULL,
    [updated_date_time]                       DATETIME         NULL,
    [update_user]                             VARCHAR (50)     NULL,
    [ltf_connect_member_id_name]              NVARCHAR (150)   NULL,
    [created_by_external_party_name]          NVARCHAR (300)   NULL,
    [ltf_last_contacted_by_name]              NVARCHAR (200)   NULL,
    [ltf_last_contacted_by_yomi_name]         NVARCHAR (200)   NULL,
    [ltf_lc_test]                             NVARCHAR (4000)  NULL,
    [ltf_lt_bucks]                            DECIMAL (18)     NULL,
    [ltf_member_type_list]                    INT              NULL,
    [ltf_member_type_list_name]               NVARCHAR (255)   NULL,
    [ltf_mobile_phone_umsk]                   NVARCHAR (100)   NULL,
    [ltf_telephone_1_umsk]                    NVARCHAR (100)   NULL,
    [ltf_telephone_2_umsk]                    NVARCHAR (100)   NULL,
    [ltf_years_of_membership]                 INT              NULL,
    [modified_by_external_party_name]         NVARCHAR (300)   NULL,
    [traversed_path]                          NVARCHAR (1250)  NULL,
    [business2]                               NVARCHAR (50)    NULL,
    [call_back]                               NVARCHAR (50)    NULL,
    [company]                                 NVARCHAR (50)    NULL,
    [home_2]                                  NVARCHAR (50)    NULL,
    [ltf_age]                                 NVARCHAR (3)     NULL,
    [ltf_alternate_full_name]                 NVARCHAR (110)   NULL,
    [ltf_anniversary_call]                    DATETIME         NULL,
    [ltf_bday_years_difference]               DATETIME         NULL,
    [ltf_days_since_join_date]                INT              NULL,
    [ltf_dnc_temporary_release_expiration]    DATETIME         NULL,
    [ltf_dnd_over_ride_expiration]            DATETIME         NULL,
    [ltf_email_address_1_umsk]                NVARCHAR (110)   NULL,
    [ltf_email_address_2_umsk]                NVARCHAR (110)   NULL,
    [address_3_address_type_code]             INT              NULL,
    [address_3_address_type_code_name]        NVARCHAR (255)   NULL,
    [address_3_city]                          NVARCHAR (80)    NULL,
    [address_3_composite]                     NVARCHAR (4000)  NULL,
    [address_3_country]                       NVARCHAR (80)    NULL,
    [address_3_county]                        NVARCHAR (50)    NULL,
    [address_3_fax]                           NVARCHAR (50)    NULL,
    [address_3_freight_terms_code]            INT              NULL,
    [address_3_freight_terms_code_name]       NVARCHAR (255)   NULL,
    [address_3_latitude]                      DECIMAL (26, 6)  NULL,
    [address_3_line_1]                        NVARCHAR (250)   NULL,
    [address_3_line_2]                        NVARCHAR (250)   NULL,
    [address_3_line_3]                        NVARCHAR (250)   NULL,
    [address_3_longitude]                     DECIMAL (26, 6)  NULL,
    [address_3_name]                          NVARCHAR (200)   NULL,
    [address_3_postal_code]                   NVARCHAR (20)    NULL,
    [address_3_post_office_box]               NVARCHAR (20)    NULL,
    [address_3_primary_contact_name]          NVARCHAR (100)   NULL,
    [address_3_shipping_method_code]          INT              NULL,
    [address_3_shipping_method_code_name]     NVARCHAR (255)   NULL,
    [address_3_state_or_province]             NVARCHAR (50)    NULL,
    [address_3_telephone_1]                   NVARCHAR (50)    NULL,
    [address_3_telephone_2]                   NVARCHAR (50)    NULL,
    [address_3_telephone_3]                   NVARCHAR (50)    NULL,
    [address_3_ups_zone]                      NVARCHAR (4)     NULL,
    [address_3_utc_offset]                    INT              NULL,
    [ltf_calculated_age]                      INT              NULL,
    [ltf_dnc_dne_update_triggered_by]         INT              NULL,
    [ltf_dnc_dne_update_triggered_by_name]    NVARCHAR (255)   NULL,
    [ltf_is_life_time_close_to]               INT              NULL,
    [ltf_is_life_time_close_to_name]          NVARCHAR (255)   NULL,
    [ltf_selected_interest_ids]               NVARCHAR (1000)  NULL,
    [dv_load_date_time]                       DATETIME         NOT NULL,
    [dv_r_load_source_id]                     BIGINT           NOT NULL,
    [dv_inserted_date_time]                   DATETIME         NOT NULL,
    [dv_insert_user]                          VARCHAR (50)     NOT NULL,
    [dv_updated_date_time]                    DATETIME         NULL,
    [dv_update_user]                          VARCHAR (50)     NULL,
    [dv_hash]                                 CHAR (32)        NOT NULL,
    [dv_batch_id]                             BIGINT           NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_crmcloudsync_contact]
    ON [dbo].[s_crmcloudsync_contact]([bk_hash] ASC, [s_crmcloudsync_contact_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_contact]([dv_batch_id] ASC);

