CREATE TABLE [dbo].[s_crmcloudsync_ltf_inquiry] (
    [s_crmcloudsync_ltf_inquiry_id]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                            CHAR (32)       NOT NULL,
    [activity_id]                        VARCHAR (36)    NULL,
    [activity_type_code]                 NVARCHAR (64)   NULL,
    [activity_type_code_name]            NVARCHAR (255)  NULL,
    [actual_duration_minutes]            INT             NULL,
    [actual_end]                         DATETIME        NULL,
    [actual_start]                       DATETIME        NULL,
    [bcc]                                VARCHAR (8000)  NULL,
    [cc]                                 VARCHAR (8000)  NULL,
    [created_by_name]                    NVARCHAR (200)  NULL,
    [created_by_yomi_name]               NVARCHAR (200)  NULL,
    [created_on]                         DATETIME        NULL,
    [created_on_behalf_by_name]          NVARCHAR (200)  NULL,
    [created_on_behalf_by_yomi_name]     NVARCHAR (200)  NULL,
    [customers]                          VARCHAR (8000)  NULL,
    [delivery_last_attempted_on]         DATETIME        NULL,
    [delivery_priority_code]             INT             NULL,
    [delivery_priority_code_name]        NVARCHAR (255)  NULL,
    [description]                        VARCHAR (8000)  NULL,
    [exchange_rate]                      DECIMAL (28)    NULL,
    [from]                               VARCHAR (8000)  NULL,
    [import_sequence_number]             INT             NULL,
    [instance_type_code]                 INT             NULL,
    [instance_type_code_name]            NVARCHAR (255)  NULL,
    [is_billed]                          BIT             NULL,
    [is_billed_name]                     NVARCHAR (255)  NULL,
    [is_mapi_private]                    BIT             NULL,
    [is_mapi_private_name]               NVARCHAR (255)  NULL,
    [is_regular_activity]                BIT             NULL,
    [is_regular_activity_name]           NVARCHAR (255)  NULL,
    [is_workflow_created]                BIT             NULL,
    [is_workflow_created_name]           NVARCHAR (255)  NULL,
    [left_voice_mail]                    BIT             NULL,
    [left_voice_mail_name]               NVARCHAR (255)  NULL,
    [ltf_address_1_city]                 NVARCHAR (50)   NULL,
    [ltf_address_1_country]              NVARCHAR (50)   NULL,
    [ltf_address_1_line_1]               NVARCHAR (50)   NULL,
    [ltf_address_1_line_2]               NVARCHAR (50)   NULL,
    [ltf_address_1_postal_code]          NVARCHAR (100)  NULL,
    [ltf_address_1_state_or_province]    NVARCHAR (25)   NULL,
    [ltf_age]                            INT             NULL,
    [ltf_best_time_to_contact]           NVARCHAR (40)   NULL,
    [ltf_birt_date]                      DATETIME        NULL,
    [ltf_birth_date]                     DATETIME        NULL,
    [ltf_birth_year]                     NVARCHAR (4)    NULL,
    [ltf_communication_consent]          INT             NULL,
    [ltf_communication_consent_name]     NVARCHAR (255)  NULL,
    [ltf_consent_date_time]              DATETIME        NULL,
    [ltf_consent_ip_address]             NVARCHAR (19)   NULL,
    [ltf_consent_text]                   NVARCHAR (300)  NULL,
    [ltf_current_member]                 BIT             NULL,
    [ltf_current_member_name]            NVARCHAR (255)  NULL,
    [ltf_cust_serve_mail]                NVARCHAR (100)  NULL,
    [ltf_dcmp]                           NVARCHAR (100)  NULL,
    [ltf_destination_queue]              NVARCHAR (100)  NULL,
    [ltf_duplicate_contact_found]        BIT             NULL,
    [ltf_duplicate_contact_found_name]   NVARCHAR (255)  NULL,
    [ltf_duplicate_lead_found]           BIT             NULL,
    [ltf_duplicate_lead_foundname]       NVARCHAR (255)  NULL,
    [ltf_email_address1]                 NVARCHAR (100)  NULL,
    [ltf_email_template]                 NVARCHAR (100)  NULL,
    [ltf_employee_number]                NVARCHAR (10)   NULL,
    [ltf_employer]                       NVARCHAR (50)   NULL,
    [ltf_exact_target_email_sent]        BIT             NULL,
    [ltf_exact_target_email_sent_name]   NVARCHAR (255)  NULL,
    [ltf_first_name]                     NVARCHAR (50)   NULL,
    [ltf_gender_code]                    INT             NULL,
    [ltf_gender_code_name]               NVARCHAR (255)  NULL,
    [ltf_group]                          NVARCHAR (100)  NULL,
    [ltf_inquiry_source]                 NVARCHAR (100)  NULL,
    [ltf_inquiry_type]                   NVARCHAR (100)  NULL,
    [ltf_interests]                      NVARCHAR (300)  NULL,
    [ltf_keywords]                       NVARCHAR (100)  NULL,
    [ltf_landing_page]                   NVARCHAR (100)  NULL,
    [ltf_last_name]                      NVARCHAR (50)   NULL,
    [ltf_latitude]                       DECIMAL (26, 6) NULL,
    [ltf_lead_type]                      NVARCHAR (100)  NULL,
    [ltf_longitude]                      DECIMAL (26, 6) NULL,
    [ltf_membership_info_requested]      NVARCHAR (50)   NULL,
    [ltf_primary_goal]                   NVARCHAR (100)  NULL,
    [ltf_referring_contactid_name]       NVARCHAR (160)  NULL,
    [ltf_referring_contact_id_yomi_name] NVARCHAR (160)  NULL,
    [ltf_registration_code]              NVARCHAR (100)  NULL,
    [ltf_request_type]                   NVARCHAR (100)  NULL,
    [ltf_telephone1]                     NVARCHAR (50)   NULL,
    [ltf_telephone2]                     NVARCHAR (50)   NULL,
    [ltf_under_eighteen]                 BIT             NULL,
    [ltf_under_eighteen_name]            NVARCHAR (255)  NULL,
    [ltf_utm_campaign]                   NVARCHAR (100)  NULL,
    [ltf_utm_content]                    NVARCHAR (100)  NULL,
    [ltf_utm_medium]                     NVARCHAR (100)  NULL,
    [ltf_utm_source]                     NVARCHAR (100)  NULL,
    [ltf_utm_term]                       NVARCHAR (100)  NULL,
    [ltf_visit_count]                    INT             NULL,
    [modified_by_name]                   NVARCHAR (200)  NULL,
    [modified_by_yomi_name]              NVARCHAR (200)  NULL,
    [modified_on]                        DATETIME        NULL,
    [modified_on_behalf_by_name]         NVARCHAR (200)  NULL,
    [modified_on_behalf_by_yomi_name]    NVARCHAR (200)  NULL,
    [optional_attendees]                 VARCHAR (8000)  NULL,
    [organizer]                          VARCHAR (8000)  NULL,
    [overridden_created_on]              DATETIME        NULL,
    [owner_id_name]                      NVARCHAR (200)  NULL,
    [owner_id_type]                      NVARCHAR (64)   NULL,
    [owner_id_yomi_name]                 NVARCHAR (200)  NULL,
    [partners]                           VARCHAR (8000)  NULL,
    [postpone_activity_processing_until] DATETIME        NULL,
    [priority_code]                      INT             NULL,
    [priority_code_name]                 NVARCHAR (255)  NULL,
    [regarding_object_id_name]           VARCHAR (8000)  NULL,
    [regarding_object_id_yomi_name]      VARCHAR (8000)  NULL,
    [regarding_object_type_code]         NVARCHAR (64)   NULL,
    [required_attendees]                 VARCHAR (8000)  NULL,
    [resources]                          VARCHAR (8000)  NULL,
    [scheduled_duration_minutes]         INT             NULL,
    [scheduled_end]                      DATETIME        NULL,
    [scheduled_start]                    DATETIME        NULL,
    [sender_mail_box_id_name]            NVARCHAR (200)  NULL,
    [senton]                             DATETIME        NULL,
    [service_id_name]                    NVARCHAR (160)  NULL,
    [state_code]                         INT             NULL,
    [state_code_name]                    NVARCHAR (255)  NULL,
    [status_code]                        INT             NULL,
    [status_code_name]                   NVARCHAR (255)  NULL,
    [subject]                            NVARCHAR (200)  NULL,
    [time_zone_rule_version_number]      INT             NULL,
    [to]                                 VARCHAR (8000)  NULL,
    [transaction_currency_id_name]       NVARCHAR (100)  NULL,
    [utc_conversion_time_zone_code]      INT             NULL,
    [version_number]                     BIGINT          NULL,
    [inserted_date_time]                 DATETIME        NULL,
    [insert_user]                        VARCHAR (100)   NULL,
    [updated_date_time]                  DATETIME        NULL,
    [update_user]                        VARCHAR (50)    NULL,
    [community]                          INT             NULL,
    [community_name]                     NVARCHAR (255)  NULL,
    [ltf_club_name_name]                 NVARCHAR (100)  NULL,
    [ltf_device]                         NVARCHAR (100)  NULL,
    [ltf_operating_system]               NVARCHAR (100)  NULL,
    [ltf_referring_domain]               NVARCHAR (100)  NULL,
    [ltf_referring_page]                 NVARCHAR (500)  NULL,
    [traversed_path]                     NVARCHAR (1250) NULL,
    [activity_additional_params]         VARCHAR (8000)  NULL,
    [ltf_utm_audience]                   NVARCHAR (100)  NULL,
    [ltf_utm_image]                      NVARCHAR (100)  NULL,
    [dv_load_date_time]                  DATETIME        NOT NULL,
    [dv_r_load_source_id]                BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL,
    [dv_hash]                            CHAR (32)       NOT NULL,
    [dv_batch_id]                        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_crmcloudsync_ltf_inquiry]
    ON [dbo].[s_crmcloudsync_ltf_inquiry]([bk_hash] ASC, [s_crmcloudsync_ltf_inquiry_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_crmcloudsync_ltf_inquiry]([dv_batch_id] ASC);

