CREATE TABLE [dbo].[s_ec_workout_histories] (
    [s_ec_workout_histories_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                       CHAR (32)       NOT NULL,
    [workout_history_id]            INT             NULL,
    [is_custom]                     BIT             NULL,
    [date_created]                  DATETIME        NULL,
    [date_started]                  DATETIME        NULL,
    [date_ended]                    DATETIME        NULL,
    [is_started]                    BIT             NULL,
    [completed]                     BIT             NULL,
    [comments]                      VARCHAR (8000)  NULL,
    [rating]                        INT             NULL,
    [key]                           VARCHAR (8000)  NULL,
    [type]                          VARCHAR (30)    NULL,
    [is_active]                     BIT             NULL,
    [fat_calories]                  INT             NULL,
    [total_calories]                INT             NULL,
    [source_name]                   VARCHAR (8000)  NULL,
    [description]                   VARCHAR (8000)  NULL,
    [activity_type]                 VARCHAR (8000)  NULL,
    [scheduled]                     BIT             NULL,
    [tracked]                       BIT             NULL,
    [source_workout_id]             VARCHAR (8000)  NULL,
    [heart_rate_zone_one_seconds]   INT             NULL,
    [heart_rate_zone_two_seconds]   INT             NULL,
    [heart_rate_zone_three_seconds] INT             NULL,
    [heart_rate_zone_four_seconds]  INT             NULL,
    [heart_rate_zone_five_seconds]  INT             NULL,
    [distance_in_miles]             DECIMAL (26, 6) NULL,
    [average_miles_per_hour]        DECIMAL (28, 8) NULL,
    [average_watts]                 DECIMAL (28, 8) NULL,
    [average_heart_rate]            DECIMAL (28, 8) NULL,
    [dv_load_date_time]             DATETIME        NOT NULL,
    [dv_r_load_source_id]           BIGINT          NOT NULL,
    [dv_inserted_date_time]         DATETIME        NOT NULL,
    [dv_insert_user]                VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]          DATETIME        NULL,
    [dv_update_user]                VARCHAR (50)    NULL,
    [dv_hash]                       CHAR (32)       NOT NULL,
    [dv_deleted]                    BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                   BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

