CREATE TABLE [dbo].[s_exerp_sale_log] (
    [s_exerp_sale_log_id]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                  CHAR (32)       NOT NULL,
    [sale_log_id]              VARCHAR (4000)  NULL,
    [sale_type]                VARCHAR (4000)  NULL,
    [is_company]               VARCHAR (10)    NULL,
    [entry_datetime]           DATETIME        NULL,
    [book_datetime]            DATETIME        NULL,
    [product_center]           INT             NULL,
    [product_type]             VARCHAR (4000)  NULL,
    [product_normal_price]     DECIMAL (26, 6) NULL,
    [quantity]                 INT             NULL,
    [net_amount]               DECIMAL (26, 6) NULL,
    [vat_amount]               DECIMAL (26, 6) NULL,
    [total_amount]             DECIMAL (26, 6) NULL,
    [gl_debit_account]         VARCHAR (4000)  NULL,
    [gl_credit_account]        VARCHAR (4000)  NULL,
    [sale_commission]          INT             NULL,
    [sale_units]               INT             NULL,
    [period_commission]        INT             NULL,
    [source_type]              VARCHAR (4000)  NULL,
    [tts]                      DATETIME        NULL,
    [ets]                      BIGINT          NULL,
    [flat_rate_commission]     DECIMAL (26, 6) NULL,
    [dummy_modified_date_time] DATETIME        NULL,
    [dv_load_date_time]        DATETIME        NOT NULL,
    [dv_r_load_source_id]      BIGINT          NOT NULL,
    [dv_inserted_date_time]    DATETIME        NOT NULL,
    [dv_insert_user]           VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]     DATETIME        NULL,
    [dv_update_user]           VARCHAR (50)    NULL,
    [dv_hash]                  CHAR (32)       NOT NULL,
    [dv_deleted]               BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]              BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

