CREATE TABLE [dbo].[s_exerp_subscription] (
    [s_exerp_subscription_id]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                    CHAR (32)       NOT NULL,
    [subscription_id]            VARCHAR (4000)  NULL,
    [state]                      VARCHAR (4000)  NULL,
    [sub_state]                  VARCHAR (4000)  NULL,
    [renewal_type]               VARCHAR (4000)  NULL,
    [start_date]                 DATETIME        NULL,
    [stop_datetime]              DATETIME        NULL,
    [end_date]                   DATETIME        NULL,
    [billed_until_date]          DATETIME        NULL,
    [binding_end_date]           DATETIME        NULL,
    [creation_datetime]          DATETIME        NULL,
    [price]                      DECIMAL (26, 6) NULL,
    [binding_price]              DECIMAL (26, 6) NULL,
    [requires_main]              BIT             NULL,
    [price_update_excluded]      BIT             NULL,
    [type_price_update_excluded] BIT             NULL,
    [period_unit]                VARCHAR (4000)  NULL,
    [period_count]               INT             NULL,
    [stop_cancel_datetime]       DATETIME        NULL,
    [ets]                        BIGINT          NULL,
    [dv_load_date_time]          DATETIME        NOT NULL,
    [dv_r_load_source_id]        BIGINT          NOT NULL,
    [dv_inserted_date_time]      DATETIME        NOT NULL,
    [dv_insert_user]             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]       DATETIME        NULL,
    [dv_update_user]             VARCHAR (50)    NULL,
    [dv_hash]                    CHAR (32)       NOT NULL,
    [dv_deleted]                 BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

