CREATE TABLE [dbo].[s_fitmetrix_api_appointment_id_statistics] (
    [s_fitmetrix_api_appointment_id_statistics_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)     NOT NULL,
    [profile_appointment_id]                       INT           NULL,
    [zone_1_time]                                  VARCHAR (255) NULL,
    [zone_1_calories]                              INT           NULL,
    [zone_2_time]                                  VARCHAR (255) NULL,
    [zone_2_calories]                              INT           NULL,
    [zone_3_time]                                  VARCHAR (255) NULL,
    [zone_3_calories]                              INT           NULL,
    [zone_4_time]                                  VARCHAR (255) NULL,
    [zone_4_calories]                              INT           NULL,
    [zone_0_time]                                  VARCHAR (255) NULL,
    [zone_0_calories]                              INT           NULL,
    [distance]                                     INT           NULL,
    [max_speed]                                    INT           NULL,
    [average_speed]                                INT           NULL,
    [max_power]                                    INT           NULL,
    [average_power]                                INT           NULL,
    [average_waits]                                INT           NULL,
    [max_waits]                                    INT           NULL,
    [max_heart_rate]                               INT           NULL,
    [min_heart_rate]                               INT           NULL,
    [average_heart_rate]                           INT           NULL,
    [total_calories]                               INT           NULL,
    [total_points]                                 INT           NULL,
    [appointment_name]                             VARCHAR (255) NULL,
    [start_date_time]                              VARCHAR (255) NULL,
    [first_name]                                   VARCHAR (255) NULL,
    [last_name]                                    VARCHAR (255) NULL,
    [heart_rate_breakdown]                         VARCHAR (255) NULL,
    [description]                                  VARCHAR (255) NULL,
    [rank]                                         INT           NULL,
    [total_rank]                                   INT           NULL,
    [class_duration]                               INT           NULL,
    [total_minutes]                                INT           NULL,
    [email]                                        VARCHAR (255) NULL,
    [name]                                         VARCHAR (255) NULL,
    [instructor_first_name]                        VARCHAR (255) NULL,
    [instructor_last_name]                         VARCHAR (255) NULL,
    [rpm_breakdown]                                VARCHAR (255) NULL,
    [watts_breakdown]                              VARCHAR (255) NULL,
    [speed_breakdown]                              VARCHAR (255) NULL,
    [weight]                                       VARCHAR (255) NULL,
    [gender]                                       VARCHAR (255) NULL,
    [ptp]                                          INT           NULL,
    [zone_1_ptp_time]                              INT           NULL,
    [zone_2_ptp_time]                              INT           NULL,
    [zone_3_ptp_time]                              INT           NULL,
    [zone_4_ptp_time]                              INT           NULL,
    [zone_0_ptp_time]                              INT           NULL,
    [zone_1_rpm_time]                              VARCHAR (255) NULL,
    [zone_1_rpm_calories]                          VARCHAR (255) NULL,
    [zone_2_rpm_time]                              VARCHAR (255) NULL,
    [zone_2_rpm_calories]                          VARCHAR (255) NULL,
    [zone_3_rpm_time]                              VARCHAR (255) NULL,
    [zone_3_rpm_calories]                          VARCHAR (255) NULL,
    [zone_4_rpm_time]                              VARCHAR (255) NULL,
    [zone_4_rpm_calories]                          VARCHAR (255) NULL,
    [zone_0_rpm_time]                              VARCHAR (255) NULL,
    [zone_0_rpm_calories]                          VARCHAR (255) NULL,
    [spot_number]                                  INT           NULL,
    [booking_priority]                             INT           NULL,
    [ptp_stored]                                   VARCHAR (255) NULL,
    [birthdate]                                    VARCHAR (255) NULL,
    [create_date]                                  VARCHAR (255) NULL,
    [waitlist]                                     VARCHAR (255) NULL,
    [checked_in]                                   VARCHAR (255) NULL,
    [waitlist_position]                            INT           NULL,
    [waitlist_date_time]                           VARCHAR (255) NULL,
    [dummy_modified_date_time]                     DATETIME      NULL,
    [dv_load_date_time]                            DATETIME      NOT NULL,
    [dv_r_load_source_id]                          BIGINT        NOT NULL,
    [dv_inserted_date_time]                        DATETIME      NOT NULL,
    [dv_insert_user]                               VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                         DATETIME      NULL,
    [dv_update_user]                               VARCHAR (50)  NULL,
    [dv_hash]                                      CHAR (32)     NOT NULL,
    [dv_batch_id]                                  BIGINT        NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_fitmetrix_api_appointment_id_statistics]([dv_batch_id] ASC);

