CREATE TABLE [dbo].[s_fitmetrix_api_facility_locations] (
    [s_fitmetrix_api_facility_locations_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                               CHAR (32)      NOT NULL,
    [facility_location_id]                  INT            NULL,
    [street_1]                              VARCHAR (255)  NULL,
    [city]                                  VARCHAR (255)  NULL,
    [state]                                 VARCHAR (255)  NULL,
    [zip]                                   VARCHAR (255)  NULL,
    [country]                               VARCHAR (255)  NULL,
    [phone]                                 VARCHAR (255)  NULL,
    [street_2]                              VARCHAR (255)  NULL,
    [hours]                                 VARCHAR (255)  NULL,
    [email]                                 VARCHAR (255)  NULL,
    [manager]                               VARCHAR (255)  NULL,
    [description]                           VARCHAR (255)  NULL,
    [latitude]                              VARCHAR (255)  NULL,
    [longitude]                             VARCHAR (255)  NULL,
    [server_time_offset]                    INT            NULL,
    [name]                                  VARCHAR (255)  NULL,
    [phone_ext]                             VARCHAR (255)  NULL,
    [booking_url]                           VARCHAR (255)  NULL,
    [check_out_url]                         VARCHAR (255)  NULL,
    [rating_url]                            VARCHAR (255)  NULL,
    [social_url]                            VARCHAR (255)  NULL,
    [class_detail_url]                      VARCHAR (255)  NULL,
    [location_url]                          VARCHAR (255)  NULL,
    [email_from_name]                       VARCHAR (255)  NULL,
    [hide_in_portal]                        VARCHAR (255)  NULL,
    [date_format]                           VARCHAR (255)  NULL,
    [location_booking_window]               INT            NULL,
    [display_order]                         INT            NULL,
    [ics_enabled]                           VARCHAR (255)  NULL,
    [booking_conversion]                    VARCHAR (255)  NULL,
    [purchase_conversion]                   VARCHAR (255)  NULL,
    [mail_chimp_api_key]                    VARCHAR (255)  NULL,
    [mail_chimp_enabled]                    VARCHAR (255)  NULL,
    [package_header]                        VARCHAR (255)  NULL,
    [package_footer]                        VARCHAR (255)  NULL,
    [sunday_hours]                          VARCHAR (255)  NULL,
    [monday_hours]                          VARCHAR (255)  NULL,
    [tuesday_hours]                         VARCHAR (255)  NULL,
    [wednesday_hours]                       VARCHAR (255)  NULL,
    [thursday_hours]                        VARCHAR (255)  NULL,
    [friday_hours]                          VARCHAR (255)  NULL,
    [saturday_hours]                        VARCHAR (255)  NULL,
    [twitter_url]                           VARCHAR (255)  NULL,
    [facebook_url]                          VARCHAR (255)  NULL,
    [check_out_header]                      VARCHAR (255)  NULL,
    [check_out_footer]                      VARCHAR (255)  NULL,
    [check_out_call_out]                    VARCHAR (255)  NULL,
    [pick_a_spot_header]                    VARCHAR (4000) NULL,
    [pick_a_spot_footer]                    VARCHAR (4000) NULL,
    [pick_a_spot_call_out]                  VARCHAR (255)  NULL,
    [announcement_title]                    VARCHAR (255)  NULL,
    [announcement_body]                     VARCHAR (255)  NULL,
    [announcement_link]                     VARCHAR (255)  NULL,
    [announcement_link_text]                VARCHAR (255)  NULL,
    [announcement]                          VARCHAR (255)  NULL,
    [booking_notes]                         VARCHAR (255)  NULL,
    [stripe_api_key]                        VARCHAR (255)  NULL,
    [instagram_url]                         VARCHAR (255)  NULL,
    [is_approval]                           VARCHAR (255)  NULL,
    [send_sub_text_messages]                VARCHAR (255)  NULL,
    [notify_participants]                   VARCHAR (255)  NULL,
    [notify_members_of_fav_instructor_sub]  VARCHAR (255)  NULL,
    [facility_location_activities]          VARCHAR (255)  NULL,
    [app_schedule_url]                      VARCHAR (255)  NULL,
    [guest_pass_limit]                      INT            NULL,
    [dummy_modified_date_time]              DATETIME       NULL,
    [dv_load_date_time]                     DATETIME       NOT NULL,
    [dv_r_load_source_id]                   BIGINT         NOT NULL,
    [dv_inserted_date_time]                 DATETIME       NOT NULL,
    [dv_insert_user]                        VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                  DATETIME       NULL,
    [dv_update_user]                        VARCHAR (50)   NULL,
    [dv_hash]                               CHAR (32)      NOT NULL,
    [dv_batch_id]                           BIGINT         NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_fitmetrix_api_facility_locations]([dv_batch_id] ASC);

