CREATE TABLE [dbo].[s_fitmetrix_api_appointments] (
    [s_fitmetrix_api_appointments_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)     NOT NULL,
    [appointment_id]                  INT           NULL,
    [name]                            VARCHAR (255) NULL,
    [active]                          VARCHAR (255) NULL,
    [description]                     VARCHAR (255) NULL,
    [start_date_time]                 VARCHAR (255) NULL,
    [end_date_time]                   VARCHAR (255) NULL,
    [is_available]                    VARCHAR (255) NULL,
    [hidden]                          VARCHAR (255) NULL,
    [is_cancelled]                    VARCHAR (255) NULL,
    [is_enrolled]                     VARCHAR (255) NULL,
    [is_wait_list_available]          VARCHAR (255) NULL,
    [max_capacity]                    INT           NULL,
    [total_booked]                    INT           NULL,
    [total_booked_wait_list]          INT           NULL,
    [web_booked]                      INT           NULL,
    [web_booked_capacity]             INT           NULL,
    [message]                         VARCHAR (255) NULL,
    [date_modified]                   VARCHAR (255) NULL,
    [date_added]                      VARCHAR (255) NULL,
    [date_completed]                  VARCHAR (255) NULL,
    [color_code]                      INT           NULL,
    [additional_notes]                VARCHAR (255) NULL,
    [started]                         VARCHAR (255) NULL,
    [is_enrollment]                   VARCHAR (255) NULL,
    [is_substitute]                   VARCHAR (255) NULL,
    [cancel_offset]                   INT           NULL,
    [ptp_completed]                   VARCHAR (255) NULL,
    [is_appointment]                  VARCHAR (255) NULL,
    [instructor_first_name]           VARCHAR (255) NULL,
    [instructor_last_name]            VARCHAR (255) NULL,
    [instructor_image]                VARCHAR (255) NULL,
    [instructor_gender]               VARCHAR (255) NULL,
    [open_spots]                      VARCHAR (255) NULL,
    [booked_spots]                    VARCHAR (255) NULL,
    [wait_list_size]                  VARCHAR (255) NULL,
    [pt_no_test]                      VARCHAR (255) NULL,
    [checked_in]                      INT           NULL,
    [app]                             VARCHAR (255) NULL,
    [app_icon]                        VARCHAR (255) NULL,
    [manual_capacity]                 VARCHAR (255) NULL,
    [is_editable]                     VARCHAR (255) NULL,
    [dummy_modified_date_time]        DATETIME      NULL,
    [dv_load_date_time]               DATETIME      NOT NULL,
    [dv_r_load_source_id]             BIGINT        NOT NULL,
    [dv_inserted_date_time]           DATETIME      NOT NULL,
    [dv_insert_user]                  VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]            DATETIME      NULL,
    [dv_update_user]                  VARCHAR (50)  NULL,
    [dv_hash]                         CHAR (32)     NOT NULL,
    [dv_batch_id]                     BIGINT        NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_fitmetrix_api_appointments]([dv_batch_id] ASC);

