CREATE TABLE [dbo].[s_humanity_schedule] (
    [s_humanity_schedule_id]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                  CHAR (32)     NOT NULL,
    [shift_id]                 BIGINT        NULL,
    [employee_id]              VARCHAR (255) NULL,
    [position_id]              VARCHAR (255) NULL,
    [ltf_file_name]            VARCHAR (255) NULL,
    [employee_eid]             VARCHAR (255) NULL,
    [employee_name]            VARCHAR (255) NULL,
    [location_id]              VARCHAR (255) NULL,
    [location_name]            VARCHAR (255) NULL,
    [workday_position_id]      VARCHAR (255) NULL,
    [position_name]            VARCHAR (255) NULL,
    [shift_start_date_utc]     VARCHAR (255) NULL,
    [shift_start_time]         VARCHAR (255) NULL,
    [shift_end_date_utc]       VARCHAR (255) NULL,
    [shift_end_time]           VARCHAR (255) NULL,
    [hours]                    VARCHAR (255) NULL,
    [wage]                     VARCHAR (255) NULL,
    [published]                VARCHAR (255) NULL,
    [published_datetime_utc]   VARCHAR (255) NULL,
    [shift_type]               VARCHAR (255) NULL,
    [employees_needed]         VARCHAR (255) NULL,
    [employees_working]        VARCHAR (255) NULL,
    [recurring_shift]          VARCHAR (255) NULL,
    [created_by_id]            VARCHAR (255) NULL,
    [created_by_eid]           VARCHAR (255) NULL,
    [created_by_name]          VARCHAR (255) NULL,
    [created_datetime_utc]     VARCHAR (255) NULL,
    [notes]                    VARCHAR (255) NULL,
    [is_deleted]               VARCHAR (255) NULL,
    [File_arrive_date]         VARCHAR (255) NULL,
    [updated_at_utc]           VARCHAR (255) NULL,
    [company_name]             VARCHAR (255) NULL,
    [dummy_modified_date_time] DATETIME      NULL,
    [dv_load_date_time]        DATETIME      NOT NULL,
    [dv_r_load_source_id]      BIGINT        NOT NULL,
    [dv_inserted_date_time]    DATETIME      NOT NULL,
    [dv_insert_user]           VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]     DATETIME      NULL,
    [dv_update_user]           VARCHAR (50)  NULL,
    [dv_hash]                  CHAR (32)     NOT NULL,
    [dv_deleted]               BIT           DEFAULT ((0)) NOT NULL,
    [dv_batch_id]              BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

