CREATE TABLE [dbo].[s_hybris_user_groups] (
    [s_hybris_user_groups_id]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)      NOT NULL,
    [hjmpts]                           BIGINT         NULL,
    [created_ts]                       DATETIME       NULL,
    [modified_ts]                      DATETIME       NULL,
    [user_groups_pk]                   BIGINT         NULL,
    [p_description]                    NVARCHAR (255) NULL,
    [p_name]                           NVARCHAR (255) NULL,
    [p_uid]                            NVARCHAR (255) NULL,
    [p_profile_picture]                BIGINT         NULL,
    [p_back_office_login_disabled]     TINYINT        NULL,
    [p_ldap_search_base]               NVARCHAR (255) NULL,
    [p_dn]                             VARCHAR (8000) NULL,
    [p_cn]                             NVARCHAR (255) NULL,
    [p_max_brute_force_login_attempts] INT            NULL,
    [p_writeable_languages]            VARCHAR (8000) NULL,
    [p_readable_languages]             VARCHAR (8000) NULL,
    [p_user_discount_group]            BIGINT         NULL,
    [p_user_price_group]               BIGINT         NULL,
    [p_user_tax_group]                 BIGINT         NULL,
    [p_hmc_login_disabled]             TINYINT        NULL,
    [acl_ts]                           BIGINT         NULL,
    [prop_ts]                          BIGINT         NULL,
    [p_duns_id]                        NVARCHAR (255) NULL,
    [p_iln_id]                         NVARCHAR (255) NULL,
    [p_buyer_specific_id]              NVARCHAR (255) NULL,
    [p_id]                             NVARCHAR (255) NULL,
    [p_supplier_specific_id]           NVARCHAR (255) NULL,
    [p_medias]                         VARCHAR (8000) NULL,
    [p_shipping_address]               BIGINT         NULL,
    [p_unloading_address]              BIGINT         NULL,
    [p_billing_address]                BIGINT         NULL,
    [p_contact_address]                BIGINT         NULL,
    [p_contact]                        BIGINT         NULL,
    [p_vat_id]                         NVARCHAR (255) NULL,
    [p_responsible_company]            BIGINT         NULL,
    [p_country]                        BIGINT         NULL,
    [p_line_of_buisness]               BIGINT         NULL,
    [p_buyer]                          TINYINT        NULL,
    [p_supplier]                       TINYINT        NULL,
    [p_manufacturer]                   TINYINT        NULL,
    [p_carrier]                        TINYINT        NULL,
    [p_active]                         TINYINT        NULL,
    [p_implementation_type]            NVARCHAR (255) NULL,
    [p_priority]                       INT            NULL,
    [p_store]                          BIGINT         NULL,
    [p_email_distribution_list]        NVARCHAR (255) NULL,
    [p_default_assignee]               BIGINT         NULL,
    [dv_load_date_time]                DATETIME       NOT NULL,
    [dv_r_load_source_id]              BIGINT         NOT NULL,
    [dv_inserted_date_time]            DATETIME       NOT NULL,
    [dv_insert_user]                   VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]             DATETIME       NULL,
    [dv_update_user]                   VARCHAR (50)   NULL,
    [dv_hash]                          CHAR (32)      NOT NULL,
    [dv_batch_id]                      BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_hybris_user_groups]
    ON [dbo].[s_hybris_user_groups]([bk_hash] ASC, [s_hybris_user_groups_id] ASC);

