CREATE TABLE [dbo].[s_ig_it_trn_terminal_shift_cash_BD] (
    [s_ig_it_trn_terminal_shift_cash_BD_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                               CHAR (32)       NOT NULL,
    [breakage_amt]                          DECIMAL (26, 6) NULL,
    [bus_day_id]                            INT             NULL,
    [cash_drop_amt]                         DECIMAL (26, 6) NULL,
    [cash_shift_id]                         INT             NULL,
    [change_amt]                            DECIMAL (26, 6) NULL,
    [loan_amt]                              DECIMAL (26, 6) NULL,
    [num_tendered_checks]                   INT             NULL,
    [paidout_amt]                           DECIMAL (26, 6) NULL,
    [received_curr_amt]                     DECIMAL (26, 6) NULL,
    [tender_amt]                            DECIMAL (26, 6) NULL,
    [tender_id]                             INT             NULL,
    [tender_qty]                            INT             NULL,
    [term_id]                               INT             NULL,
    [withdrawal_amt]                        DECIMAL (26, 6) NULL,
    [dummy_modified_date_time]              DATETIME        NULL,
    [dv_load_date_time]                     DATETIME        NOT NULL,
    [dv_r_load_source_id]                   BIGINT          NOT NULL,
    [dv_inserted_date_time]                 DATETIME        NOT NULL,
    [dv_insert_user]                        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                  DATETIME        NULL,
    [dv_update_user]                        VARCHAR (50)    NULL,
    [dv_hash]                               CHAR (32)       NOT NULL,
    [dv_deleted]                            BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                           BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

