CREATE TABLE [dbo].[s_ig_it_cfg_terminal_master] (
    [s_ig_it_cfg_terminal_master_id]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)     NOT NULL,
    [term_id]                          INT           NULL,
    [term_name]                        NVARCHAR (50) NULL,
    [ip_address]                       NVARCHAR (15) NULL,
    [term_active_flag]                 BIT           NULL,
    [first_table_no]                   INT           NULL,
    [num_tables]                       INT           NULL,
    [ga_file_load_flag]                BIT           NULL,
    [fol_file_load_flag]               BIT           NULL,
    [rms_file_load_flag]               BIT           NULL,
    [current_version]                  NVARCHAR (15) NULL,
    [default_table_layout_id]          INT           NULL,
    [virtual_term_flag]                BIT           NULL,
    [bargun_term_flag]                 BIT           NULL,
    [bargun_bump_override_flag]        BIT           NULL,
    [bargun_print_drinks_on_bump_flag] BIT           NULL,
    [ped_value]                        NVARCHAR (50) NULL,
    [term_receipt_info]                NVARCHAR (50) NULL,
    [receipt_printer_type]             TINYINT       NULL,
    [static_receipt_printer_id]        INT           NULL,
    [payment_device_id]                INT           NULL,
    [is_default_api_terminal]          BIT           NULL,
    [dummy_modified_date_time]         DATETIME      NULL,
    [dv_load_date_time]                DATETIME      NOT NULL,
    [dv_r_load_source_id]              BIGINT        NOT NULL,
    [dv_inserted_date_time]            DATETIME      NOT NULL,
    [dv_insert_user]                   VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]             DATETIME      NULL,
    [dv_update_user]                   VARCHAR (50)  NULL,
    [dv_hash]                          CHAR (32)     NOT NULL,
    [dv_deleted]                       BIT           DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                      BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

