CREATE TABLE [dbo].[s_magento_eav_attribute] (
    [s_magento_eav_attribute_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                    CHAR (32)      NOT NULL,
    [attribute_id]               INT            NULL,
    [attribute_code]             VARCHAR (255)  NULL,
    [attribute_model]            VARCHAR (255)  NULL,
    [backend_model]              VARCHAR (255)  NULL,
    [backend_type]               VARCHAR (8)    NULL,
    [backend_table]              VARCHAR (255)  NULL,
    [frontend_model]             VARCHAR (255)  NULL,
    [frontend_input]             VARCHAR (50)   NULL,
    [frontend_label]             VARCHAR (255)  NULL,
    [frontend_class]             VARCHAR (255)  NULL,
    [source_model]               VARCHAR (255)  NULL,
    [is_required]                INT            NULL,
    [is_user_defined]            INT            NULL,
    [default_value]              VARCHAR (8000) NULL,
    [is_unique]                  INT            NULL,
    [note]                       VARCHAR (255)  NULL,
    [dummy_modified_date_time]   DATETIME       NULL,
    [dv_load_date_time]          DATETIME       NOT NULL,
    [dv_r_load_source_id]        BIGINT         NOT NULL,
    [dv_inserted_date_time]      DATETIME       NOT NULL,
    [dv_insert_user]             VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]       DATETIME       NULL,
    [dv_update_user]             VARCHAR (50)   NULL,
    [dv_hash]                    CHAR (32)      NOT NULL,
    [dv_deleted]                 BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                BIGINT         NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

