CREATE TABLE [dbo].[s_magento_customer_entity] (
    [s_magento_customer_entity_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)     NOT NULL,
    [entity_id]                    INT           NULL,
    [email]                        VARCHAR (255) NULL,
    [created_at]                   DATETIME      NULL,
    [updated_at]                   DATETIME      NULL,
    [is_active]                    INT           NULL,
    [disable_auto_group_change]    INT           NULL,
    [created_in]                   VARCHAR (255) NULL,
    [prefix]                       VARCHAR (40)  NULL,
    [first_name]                   VARCHAR (255) NULL,
    [middle_name]                  VARCHAR (255) NULL,
    [last_name]                    VARCHAR (255) NULL,
    [suffix]                       VARCHAR (40)  NULL,
    [dob]                          DATE          NULL,
    [password_hash]                VARCHAR (128) NULL,
    [rp_token]                     VARCHAR (128) NULL,
    [rp_token_created_at]          DATETIME      NULL,
    [default_billing]              INT           NULL,
    [default_shipping]             INT           NULL,
    [taxvat]                       VARCHAR (50)  NULL,
    [confirmation]                 VARCHAR (64)  NULL,
    [gender]                       INT           NULL,
    [failures_num]                 INT           NULL,
    [first_failure]                DATETIME      NULL,
    [lock_expires]                 DATETIME      NULL,
    [dv_load_date_time]            DATETIME      NOT NULL,
    [dv_r_load_source_id]          BIGINT        NOT NULL,
    [dv_inserted_date_time]        DATETIME      NOT NULL,
    [dv_insert_user]               VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]         DATETIME      NULL,
    [dv_update_user]               VARCHAR (50)  NULL,
    [dv_hash]                      CHAR (32)     NOT NULL,
    [dv_deleted]                   BIT           DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                  BIGINT        NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

