CREATE TABLE [dbo].[s_magento_sales_order_address] (
    [s_magento_sales_order_address_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)      NOT NULL,
    [entity_id]                        INT            NULL,
    [fax]                              VARCHAR (255)  NULL,
    [region]                           VARCHAR (255)  NULL,
    [post_code]                        VARCHAR (255)  NULL,
    [last_name]                        VARCHAR (255)  NULL,
    [street]                           VARCHAR (255)  NULL,
    [city]                             VARCHAR (255)  NULL,
    [email]                            VARCHAR (255)  NULL,
    [telephone]                        VARCHAR (255)  NULL,
    [country_id]                       VARCHAR (2)    NULL,
    [first_name]                       VARCHAR (255)  NULL,
    [address_type]                     VARCHAR (255)  NULL,
    [prefix]                           VARCHAR (255)  NULL,
    [middle_name]                      VARCHAR (255)  NULL,
    [suffix]                           VARCHAR (255)  NULL,
    [company]                          VARCHAR (255)  NULL,
    [vat_id]                           VARCHAR (8000) NULL,
    [vat_is_valid]                     INT            NULL,
    [vat_request_id]                   VARCHAR (8000) NULL,
    [vat_request_date]                 VARCHAR (8000) NULL,
    [vat_request_success]              INT            NULL,
    [dummy_modified_date_time]         DATETIME       NULL,
    [dv_load_date_time]                DATETIME       NOT NULL,
    [dv_r_load_source_id]              BIGINT         NOT NULL,
    [dv_inserted_date_time]            DATETIME       NOT NULL,
    [dv_insert_user]                   VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]             DATETIME       NULL,
    [dv_update_user]                   VARCHAR (50)   NULL,
    [dv_hash]                          CHAR (32)      NOT NULL,
    [dv_deleted]                       BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                      BIGINT         NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

