CREATE TABLE [dbo].[s_magento_customer_address_entity] (
    [s_magento_customer_address_entity_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)      NOT NULL,
    [entity_id]                            INT            NULL,
    [increment_id]                         VARCHAR (50)   NULL,
    [created_at]                           DATETIME       NULL,
    [updated_at]                           DATETIME       NULL,
    [is_active]                            INT            NULL,
    [city]                                 VARCHAR (255)  NULL,
    [company]                              VARCHAR (255)  NULL,
    [country_id]                           VARCHAR (255)  NULL,
    [fax]                                  VARCHAR (255)  NULL,
    [first_name]                           VARCHAR (255)  NULL,
    [last_name]                            VARCHAR (255)  NULL,
    [middle_name]                          VARCHAR (255)  NULL,
    [post_code]                            VARCHAR (255)  NULL,
    [prefix]                               VARCHAR (40)   NULL,
    [region]                               VARCHAR (255)  NULL,
    [street]                               VARCHAR (8000) NULL,
    [suffix]                               VARCHAR (40)   NULL,
    [telephone]                            VARCHAR (255)  NULL,
    [vat_id]                               VARCHAR (255)  NULL,
    [vat_is_valid]                         INT            NULL,
    [vat_request_date]                     VARCHAR (255)  NULL,
    [vat_request_id]                       VARCHAR (255)  NULL,
    [vat_request_success]                  INT            NULL,
    [dv_load_date_time]                    DATETIME       NOT NULL,
    [dv_r_load_source_id]                  BIGINT         NOT NULL,
    [dv_inserted_date_time]                DATETIME       NOT NULL,
    [dv_insert_user]                       VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                 DATETIME       NULL,
    [dv_update_user]                       VARCHAR (50)   NULL,
    [dv_hash]                              CHAR (32)      NOT NULL,
    [dv_deleted]                           BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                          BIGINT         NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

