CREATE VIEW [sandbox].[v_mart_mms_val_state]
AS SELECT [val_state_id]
     , [description]
     , [sort_order]
     , [val_country_id]
     , [inserted_date_time]
     , [abbreviation]
     , [updated_date_time]
     , [dim_mms_val_state_key] = [bk_hash]
     , [bk_hash]
     , [r_mms_val_state_id]
     , [dv_load_date_time]
     , [dv_batch_id]
     , [dv_hash]
  FROM [dbo].[r_mms_val_state]
  WHERE [dv_load_end_date_time] = '9999-12-31 00:00:00.000';