CREATE VIEW [sandbox].[v_mart_mms_val_membership_message_type]
AS SELECT [val_membership_message_type_id]
     , [val_message_severity_id]
     , [abbreviation]
     , [auto_close_flag]
     , [description]
     , [eft_single_open_flag]
     , [sort_order]
     , [inserted_date_time]
     , [updated_date_time]
     , [dim_mms_val_membership_message_type_key] = [bk_hash]
     , [bk_hash]
     , [r_mms_val_membership_message_type_id]
     , [dv_load_date_time]
     , [dv_batch_id]
     , [dv_hash]
  FROM [dbo].[r_mms_val_membership_message_type]
  WHERE [dv_load_date_time] = '9999-12-31 00:00:00.000';