CREATE VIEW [marketing].[v_dim_chronotrack_athlete]
AS select d_chronotrack_athlete.athlete_id athlete_id,
       d_chronotrack_athlete.account_id account_id,
       d_chronotrack_athlete.age age,
       d_chronotrack_athlete.birth_date birth_date,
       d_chronotrack_athlete.birth_dim_date_key birth_dim_date_key,
       d_chronotrack_athlete.create_time create_time,
       d_chronotrack_athlete.d_chronotrack_location_bk_hash d_chronotrack_location_bk_hash,
       d_chronotrack_athlete.email email,
       d_chronotrack_athlete.emerg_name emerg_name,
       d_chronotrack_athlete.emerg_phone emerg_phone,
       d_chronotrack_athlete.emerg_relationship emerg_relationship,
       d_chronotrack_athlete.first_name first_name,
       d_chronotrack_athlete.home_phone home_phone,
       d_chronotrack_athlete.last_name last_name,
       d_chronotrack_athlete.location_id location_id,
       d_chronotrack_athlete.medical_notes medical_notes,
       d_chronotrack_athlete.middle_name middle_name,
       d_chronotrack_athlete.mobile_phone mobile_phone,
       d_chronotrack_athlete.modified_time modified_time,
       d_chronotrack_athlete.name_pronunciation name_pronunciation,
       d_chronotrack_athlete.sex sex,
       d_chronotrack_athlete.tshirt_size tshirt_size,
       d_chronotrack_athlete.usat_num usat_num
  from dbo.d_chronotrack_athlete;