CREATE VIEW [marketing].[v_dim_ec_free_programs]
AS select d_ec_free_programs.dim_ec_free_programs_keys dim_ec_free_programs_keys,
       d_ec_free_programs.free_program_id free_program_id,
       d_ec_free_programs.active_flag active_flag,
       d_ec_free_programs.created_date created_date,
       d_ec_free_programs.created_dim_date_key created_dim_date_key,
       d_ec_free_programs.created_dim_time_key created_dim_time_key,
       d_ec_free_programs.d_ec_programs_bk_hash d_ec_programs_bk_hash,
       d_ec_free_programs.duration duration,
       d_ec_free_programs.end_date end_date,
       d_ec_free_programs.end_dim_date_key end_dim_date_key,
       d_ec_free_programs.end_dim_time_key end_dim_time_key,
       d_ec_free_programs.equipment equipment,
       d_ec_free_programs.exercise exercise,
       d_ec_free_programs.featured_flag featured_flag,
       d_ec_free_programs.frequency frequency,
       d_ec_free_programs.goal goal,
       d_ec_free_programs.level level,
       d_ec_free_programs.priority priority,
       d_ec_free_programs.program_description program_description,
       d_ec_free_programs.program_id program_id,
       d_ec_free_programs.program_image program_image,
       d_ec_free_programs.program_name program_name,
       d_ec_free_programs.updated_date updated_date,
       d_ec_free_programs.updated_dim_date_key updated_dim_date_key,
       d_ec_free_programs.updated_dim_time_key updated_dim_time_key
  from dbo.d_ec_free_programs;