CREATE VIEW [marketing].[v_dim_mms_ltf_key_owner]
AS select d_mms_ltf_key_owner.ltf_key_owner_id ltf_key_owner_id,
       d_mms_ltf_key_owner.acquisition_id acquisition_id,
       d_mms_ltf_key_owner.d_ltf_key_bk_hash d_ltf_key_bk_hash,
       d_mms_ltf_key_owner.display_name display_name,
       d_mms_ltf_key_owner.inserted_date_time inserted_date_time,
       d_mms_ltf_key_owner.inserted_dim_date_key inserted_dim_date_key,
       d_mms_ltf_key_owner.inserted_dim_time_key inserted_dim_time_key,
       d_mms_ltf_key_owner.key_priority key_priority,
       d_mms_ltf_key_owner.ltf_key_acquisition_id ltf_key_acquisition_id,
       d_mms_ltf_key_owner.ltf_key_id ltf_key_id,
       d_mms_ltf_key_owner.ltf_key_owner_from_dim_date_key ltf_key_owner_from_dim_date_key,
       d_mms_ltf_key_owner.ltf_key_owner_from_dim_time_key ltf_key_owner_from_dim_time_key,
       d_mms_ltf_key_owner.ltf_key_owner_thru_dim_date_key ltf_key_owner_thru_dim_date_key,
       d_mms_ltf_key_owner.ltf_key_owner_thru_dim_time_key ltf_key_owner_thru_dim_time_key,
       d_mms_ltf_key_owner.party_id party_id,
       d_mms_ltf_key_owner.updated_date_time updated_date_time,
       d_mms_ltf_key_owner.updated_dim_date_key updated_dim_date_key,
       d_mms_ltf_key_owner.updated_dim_time_key updated_dim_time_key,
       d_mms_ltf_key_owner.usage_count usage_count,
       d_mms_ltf_key_owner.usage_limit usage_limit,
       d_mms_ltf_key_owner.val_acquisition_type_id val_acquisition_type_id,
       d_mms_ltf_key_owner.val_ownership_type_id val_ownership_type_id
  from dbo.d_mms_ltf_key_owner;