CREATE VIEW [marketing].[v_dim_athlinks_api_vw_master_event]
AS select d_athlinks_api_vw_master_event.master_id master_id,
       d_athlinks_api_vw_master_event.city city,
       d_athlinks_api_vw_master_event.company_id company_id,
       d_athlinks_api_vw_master_event.company_name company_name,
       d_athlinks_api_vw_master_event.contact_address contact_address,
       d_athlinks_api_vw_master_event.contact_name contact_name,
       d_athlinks_api_vw_master_event.country_id country_id,
       d_athlinks_api_vw_master_event.create_date create_date,
       d_athlinks_api_vw_master_event.create_dim_date_key create_dim_date_key,
       d_athlinks_api_vw_master_event.create_dim_time_key create_dim_time_key,
       d_athlinks_api_vw_master_event.curated_desc curated_desc,
       d_athlinks_api_vw_master_event.elevation elevation,
       d_athlinks_api_vw_master_event.featured_flag featured_flag,
       d_athlinks_api_vw_master_event.geo geo,
       d_athlinks_api_vw_master_event.latitude latitude,
       d_athlinks_api_vw_master_event.logo_path logo_path,
       d_athlinks_api_vw_master_event.longitude longitude,
       d_athlinks_api_vw_master_event.master_event_name master_event_name,
       d_athlinks_api_vw_master_event.next_d_athlinks_api_vw_race_ltf_data_bk_hash next_d_athlinks_api_vw_race_ltf_data_bk_hash,
       d_athlinks_api_vw_master_event.next_date next_date,
       d_athlinks_api_vw_master_event.next_dim_date_key next_dim_date_key,
       d_athlinks_api_vw_master_event.next_dim_time_key next_dim_time_key,
       d_athlinks_api_vw_master_event.next_race_id next_race_id,
       d_athlinks_api_vw_master_event.phone phone,
       d_athlinks_api_vw_master_event.prev_d_athlinks_api_vw_race_ltf_data_bk_hash prev_d_athlinks_api_vw_race_ltf_data_bk_hash,
       d_athlinks_api_vw_master_event.prev_date prev_date,
       d_athlinks_api_vw_master_event.prev_dim_date_key prev_dim_date_key,
       d_athlinks_api_vw_master_event.prev_dim_time_key prev_dim_time_key,
       d_athlinks_api_vw_master_event.prev_race_id prev_race_id,
       d_athlinks_api_vw_master_event.race_count race_count,
       d_athlinks_api_vw_master_event.result_count result_count,
       d_athlinks_api_vw_master_event.short_url short_url,
       d_athlinks_api_vw_master_event.state_prov_abbrev state_prov_abbrev,
       d_athlinks_api_vw_master_event.state_prov_id state_prov_id
from d_athlinks_api_vw_master_event where country_id in ('US','CA');