CREATE VIEW [marketing].[v_dim_location_hour]
AS select dim_location_hour.by_appointment_only_flag by_appointment_only_flag,
       dim_location_hour.closed_flag closed_flag,
       dim_location_hour.created_by created_by,
       dim_location_hour.created_date_time created_date_time,
       dim_location_hour.day_of_week day_of_week,
       dim_location_hour.deleted_by deleted_by,
       dim_location_hour.deleted_date_time deleted_date_time,
       dim_location_hour.deleted_flag deleted_flag,
       dim_location_hour.dim_location_hour_key dim_location_hour_key,
       dim_location_hour.dim_location_key dim_location_key,
       dim_location_hour.end_dim_time_key end_dim_time_key,
       dim_location_hour.end_time end_time,
       dim_location_hour.hour_24_flag hour_24_flag,
       dim_location_hour.hour_id hour_id,
       dim_location_hour.last_updated_by last_updated_by,
       dim_location_hour.last_updated_date_time last_updated_date_time,
       dim_location_hour.start_dim_time_key start_dim_time_key,
       dim_location_hour.start_time start_time,
       dim_location_hour.sunrise_flag sunrise_flag,
       dim_location_hour.sunset_flag sunset_flag,
       dim_location_hour.updated_dim_date_key updated_dim_date_key,
       dim_location_hour.updated_dim_time_key updated_dim_time_key,
       dim_location_hour.val_hour_type_display_name val_hour_type_display_name,
       dim_location_hour.val_hour_type_group_display_name val_hour_type_group_display_name,
       dim_location_hour.val_hour_type_group_name val_hour_type_group_name,
       dim_location_hour.val_hour_type_name val_hour_type_name
  from dbo.dim_location_hour;