CREATE VIEW [marketing].[v_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate] AS select d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate_key dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate_key,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.service_charge_tax_id service_charge_tax_id,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.store_number store_number,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate_id d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate_id,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.dim_spabiz_service_charge_type_key dim_spabiz_service_charge_type_key,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.dim_spabiz_store_key dim_spabiz_store_key,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.dim_spabiz_tax_rate_key dim_spabiz_tax_rate_key,
       d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate.edit_date_time edit_date_time
  from dbo.d_dim_spabiz_service_charge_type_bridge_dim_spabiz_tax_rate;