CREATE VIEW [marketing].[v_dim_crm_survey_response]
AS select d_crmcloudsync_ltf_survey_response.dim_crm_ltf_survey_response_key dim_crm_ltf_survey_response_key,
       d_crmcloudsync_ltf_survey_response.ltf_survey_response_id ltf_survey_response_id,
       d_crmcloudsync_ltf_survey_response.created_by_dim_crm_system_user_key created_by_dim_crm_system_user_key,
       d_crmcloudsync_ltf_survey_response.created_dim_date_key created_dim_date_key,
       d_crmcloudsync_ltf_survey_response.created_dim_time_key created_dim_time_key,
       d_crmcloudsync_ltf_survey_response.created_on created_on,
       d_crmcloudsync_ltf_survey_response.insert_user	 insert_user	,
       d_crmcloudsync_ltf_survey_response.inserted_date_time inserted_date_time,
       d_crmcloudsync_ltf_survey_response.inserted_dim_date_key inserted_dim_date_key,
       d_crmcloudsync_ltf_survey_response.inserted_dim_time_key inserted_dim_time_key,
       d_crmcloudsync_ltf_survey_response.ltf_question ltf_question,
       d_crmcloudsync_ltf_survey_response.ltf_response ltf_response,
       d_crmcloudsync_ltf_survey_response.ltf_sequence ltf_sequence,
       d_crmcloudsync_ltf_survey_response.ltf_survey ltf_survey,
       d_crmcloudsync_ltf_survey_response.ltf_survey_response ltf_survey_response,
       d_crmcloudsync_ltf_survey_response.modified_by_dim_crm_system_user_key modified_by_dim_crm_system_user_key,
       d_crmcloudsync_ltf_survey_response.modified_dim_date_key modified_dim_date_key,
       d_crmcloudsync_ltf_survey_response.modified_dim_time_key modified_dim_time_key,
       d_crmcloudsync_ltf_survey_response.modified_on modified_on,
       d_crmcloudsync_ltf_survey_response.state_code state_code,
       d_crmcloudsync_ltf_survey_response.status_code status_code,
       d_crmcloudsync_ltf_survey_response.update_user update_user,
       d_crmcloudsync_ltf_survey_response.updated_date_time updated_date_time,
       d_crmcloudsync_ltf_survey_response.updated_dim_date_key updated_dim_date_key,
       d_crmcloudsync_ltf_survey_response.updated_dim_time_key updated_dim_time_key
  from dbo.d_crmcloudsync_ltf_survey_response;