CREATE VIEW [marketing].[v_dim_mms_membership_type] AS select 
               dim_mms_membership_type.dim_mms_membership_type_key
               ,dim_mms_membership_type.membership_type_id
			   ,dim_mms_membership_type.access_by_price_paid_flag
               ,dim_mms_membership_type.allow_partner_program_flag
               ,dim_mms_membership_type.assess_dues_flag
               ,dim_mms_membership_type.assess_junior_member_dues_flag
               ,dim_mms_membership_type.attribute_26_and_under_flag
               ,dim_mms_membership_type.attribute_acquisition_flag
               ,dim_mms_membership_type.attribute_attrition_exclusion_flag
               ,dim_mms_membership_type.attribute_auto_ship_flag
               ,dim_mms_membership_type.attribute_corporate_flex_flag
               ,dim_mms_membership_type.attribute_dssr_group_description
               ,dim_mms_membership_type.attribute_employee_membership_flag
               ,dim_mms_membership_type.attribute_express_membership_flag
               ,dim_mms_membership_type.attribute_flexible_pass_flag
               ,dim_mms_membership_type.attribute_founders_flag
               ,dim_mms_membership_type.attribute_free_magazine_flag
               ,dim_mms_membership_type.attribute_junior_members_not_allowed_flag
               ,dim_mms_membership_type.attribute_life_time_health_flag
               ,dim_mms_membership_type.attribute_membership_status_summary_group_description
               ,dim_mms_membership_type.attribute_my_health_check_flag
               ,dim_mms_membership_type.attribute_non_access_flag
               ,dim_mms_membership_type.attribute_not_eligible_for_magazine_flag
               ,dim_mms_membership_type.attribute_pending_non_access_flag
               ,dim_mms_membership_type.attribute_short_term_membership_flag
               ,dim_mms_membership_type.attribute_student_flex_flag
               ,dim_mms_membership_type.attribute_trade_out_membership_flag
               ,dim_mms_membership_type.attribute_vip_flag
               ,dim_mms_membership_type.check_in_group_description
               ,dim_mms_membership_type.dim_mms_product_key
               ,dim_mms_membership_type.enrollment_type_description
               ,dim_mms_membership_type.express_membership_flag
               ,dim_mms_membership_type.family_status_description
               ,dim_mms_membership_type.gta_signature_override
               ,dim_mms_membership_type.membership_type
               ,dim_mms_membership_type.membership_type_group_description
               ,dim_mms_membership_type.pricing_method_description
               ,dim_mms_membership_type.pricing_rule_description
               ,dim_mms_membership_type.primary_age_minimum
               ,dim_mms_membership_type.product_description
               ,dim_mms_membership_type.product_house_account_flag
               ,dim_mms_membership_type.product_id
               ,dim_mms_membership_type.product_investor_flag
               ,dim_mms_membership_type.restricted_group_description
               ,dim_mms_membership_type.short_term_membership_flag
               ,dim_mms_membership_type.suppress_membership_card_flag
               ,dim_mms_membership_type.unit_type_description
               ,dim_mms_membership_type.unit_type_maximum
               ,dim_mms_membership_type.unit_type_minimum
               ,dim_mms_membership_type.val_check_in_group_id
               ,dim_mms_membership_type.val_enrollment_type_id
               ,dim_mms_membership_type.val_membership_type_family_status_id
               ,dim_mms_membership_type.val_membership_type_group_id
               ,dim_mms_membership_type.val_pricing_method_id
               ,dim_mms_membership_type.val_pricing_rule_id
               ,dim_mms_membership_type.val_restricted_group_id
               ,dim_mms_membership_type.val_unit_type_id
               ,dim_mms_membership_type.val_welcome_kit_type_id
               ,dim_mms_membership_type.waive_admin_fee_flag
               ,dim_mms_membership_type.waive_enrollment_fee_flag
               ,dim_mms_membership_type.waive_late_fee_flag
               ,dim_mms_membership_type.welcome_kit_type_description
	   from dbo.dim_mms_membership_type;