CREATE VIEW [marketing].[v_dim_exerp_clipcard]
AS select dim_exerp_clipcard.assigned_dim_employee_key assigned_dim_employee_key,
       dim_exerp_clipcard.blocked_flag blocked_flag,
       dim_exerp_clipcard.cancel_dim_date_key cancel_dim_date_key,
       dim_exerp_clipcard.cancel_dim_time_key cancel_dim_time_key,
       dim_exerp_clipcard.cancelled_flag cancelled_flag,
       dim_exerp_clipcard.clipcard_id clipcard_id,
       dim_exerp_clipcard.clips_initial clips_initial,
       dim_exerp_clipcard.clips_left clips_left,
       dim_exerp_clipcard.comment comment,
       dim_exerp_clipcard.dim_club_key dim_club_key,
       dim_exerp_clipcard.dim_exerp_clipcard_key dim_exerp_clipcard_key,
       dim_exerp_clipcard.dim_exerp_product_key dim_exerp_product_key,
       dim_exerp_clipcard.dim_mms_member_key dim_mms_member_key,
       dim_exerp_clipcard.fact_exerp_transaction_log_key fact_exerp_transaction_log_key,
       dim_exerp_clipcard.sale_entered_dim_employee_key sale_entered_dim_employee_key,
       dim_exerp_clipcard.sale_entry_dim_date_key sale_entry_dim_date_key,
       dim_exerp_clipcard.sale_entry_dim_time_key sale_entry_dim_time_key,
       dim_exerp_clipcard.sale_source_type sale_source_type,
       dim_exerp_clipcard.valid_from_dim_date_key valid_from_dim_date_key,
       dim_exerp_clipcard.valid_from_dim_time_key valid_from_dim_time_key,
       dim_exerp_clipcard.valid_until_dim_date_key valid_until_dim_date_key,
       dim_exerp_clipcard.valid_until_dim_time_key valid_until_dim_time_key
  from dbo.dim_exerp_clipcard;