CREATE VIEW [marketing].[v_dim_time] AS SELECT dim_time_key AS dim_time_key,
	hour ,
	half_hour ,
	hour_quarter,
	minute ,
	minutes_after_midnight ,
	display_12_hour_time ,
	display_12_hour_group ,
	display_12_hour_half_group ,
	display_12_hour_quarter_group ,
	display_24_hour_time ,
	display_24_hour_group ,
	display_24_hour_half_group ,
	display_24_hour_quarter_group ,
	member_usage_targeted_segment_period 
	--dv_load_date_time datetime NOT NULL,
	--dv_load_end_date_time datetime NOT NULL,
	--dv_batch_id bigint NOT NULL,
	--dv_r_load_source_id bigint NOT NULL,
	--dv_inserted_date_time datetime NOT NULL,
	--dv_insert_user varchar(50) NOT NULL,
	--dv_updated_date_time datetime NULL,
	--dv_update_user varchar(50) NULL,
	--dv_hash char(32) NOT NULL,
	--dv_deleted bit NOT NULL
FROM dim_time;