CREATE VIEW [marketing].[v_fact_spabiz_appointment_notifications] AS select d_spabiz_staff.staff_id staff_id,
       d_spabiz_ap_data.store_number store_number,
       d_spabiz_ap.created_date_time appointment_created_date_time,
       d_spabiz_ap.appointment_date_time appointment_date_time,
       d_spabiz_ap.deleted_flag appointment_deleted_flag,
       d_spabiz_ap.appointment_id appointment_id,
       d_spabiz_ap_data.deleted_flag appointment_item_deleted_flag,
       d_spabiz_ap_data.end_date_time appointment_item_end_date_time,
       d_spabiz_ap_data.start_date_time appointment_item_start_date_time,
       d_spabiz_ap.appointment_date_time appointment_start_time,
       d_spabiz_ap_data.status_id appointment_status_id,
       d_spabiz_ap_data.booked_on_web_flag booked_on_web_flag,
       dim_spabiz_service.category category,
       d_spabiz_customer.communicate_via_email_flag communicate_via_email_flag,
       d_spabiz_customer.customer_id customer_id,
       d_spabiz_customer.date_of_birth date_of_birth,
       d_spabiz_customer.email email,
       d_spabiz_customer.first_name first_name,
       d_spabiz_customer.gender_abbreviation gender,
       d_spabiz_customer.last_name last_name,
       d_spabiz_customer.member_id member_id,
       dim_spabiz_service.book_name service_book_name,
       dim_spabiz_service.service_id service_id,
       d_spabiz_staff.book_name staff_book_name,
       d_spabiz_staff.NAME staff_name,
       d_spabiz_ap.standing_appointment_flag standing_appointment_flag
from d_spabiz_ap_data join d_spabiz_ap on d_spabiz_ap_data.fact_spabiz_appointment_key = d_spabiz_ap.fact_spabiz_appointment_key join d_spabiz_customer on d_spabiz_ap_data.dim_spabiz_customer_key = d_spabiz_customer.dim_spabiz_customer_key join d_spabiz_staff on d_spabiz_ap.dim_spabiz_staff_key = d_spabiz_staff.dim_spabiz_staff_key join dim_spabiz_service on d_spabiz_ap_data.dim_spabiz_service_key = dim_spabiz_service.dim_spabiz_service_key where data_type_id = 5;