CREATE VIEW [marketing].[v_fact_member_usage_club_summary]
AS select fact_mms_member_usage_member_club_summary.club_id club_id,
sum(fact_mms_member_usage_member_club_summary.current_month_checkins) current_month_checkins, 
sum(fact_mms_member_usage_member_club_summary.all_checkins) all_checkins,
sum(fact_mms_member_usage_member_club_summary.current_week_checkins) current_week_checkins,
sum(fact_mms_member_usage_member_club_summary.today_checkins) today_checkins,
max(fact_mms_member_usage_member_club_summary.last_checkin_dim_date_key) last_checkin_dim_date_key,
max(fact_mms_member_usage_member_club_summary.last_checkin_date_time) last_checkin_date_time,
max(fact_mms_member_usage_member_club_summary.udw_inserted_date_time) udw_inserted_date_time
from marketing.v_fact_mms_member_usage_member_club_summary fact_mms_member_usage_member_club_summary
group by fact_mms_member_usage_member_club_summary.club_id;