CREATE VIEW [marketing].[v_fact_spabiz_ticket_tip] AS select d_spabiz_ticket_tip.fact_spabiz_ticket_tip_key fact_spabiz_ticket_tip_key,
       d_spabiz_ticket_tip.ticket_tip_id ticket_tip_id,
       d_spabiz_ticket_tip.store_number store_number,
       d_spabiz_ticket_tip.amount amount,
       d_spabiz_ticket_tip.created_date_time created_date_time,
       d_spabiz_ticket_tip.dim_spabiz_customer_key dim_spabiz_customer_key,
       d_spabiz_ticket_tip.dim_spabiz_shift_key dim_spabiz_shift_key,
       d_spabiz_ticket_tip.dim_spabiz_staff_key dim_spabiz_staff_key,
       d_spabiz_ticket_tip.dim_spabiz_store_key dim_spabiz_store_key,
       d_spabiz_ticket_tip.edit_date_time edit_date_time,
       d_spabiz_ticket_tip.fact_spabiz_ticket_key fact_spabiz_ticket_key,
       d_spabiz_ticket_tip.paid paid,
       d_spabiz_ticket_tip.split_flag split_flag,
       d_spabiz_ticket_tip.status_dim_description_key status_dim_description_key,
       d_spabiz_ticket_tip.status_id status_id
  from dbo.d_spabiz_ticket_tip;