CREATE VIEW [marketing].[v_fact_exerp_clipcard_usage]
AS select fact_exerp_clipcard_usage.access_privilege_usage_state access_privilege_usage_state,
       fact_exerp_clipcard_usage.cancelled_flag cancelled_flag,
       fact_exerp_clipcard_usage.clipcard_blocked_flag clipcard_blocked_flag,
       fact_exerp_clipcard_usage.clipcard_cancelled_flag clipcard_cancelled_flag,
       fact_exerp_clipcard_usage.clipcard_usage_entered_dim_employee_key clipcard_usage_entered_dim_employee_key,
       fact_exerp_clipcard_usage.clipcard_usage_id clipcard_usage_id,
       fact_exerp_clipcard_usage.clipcard_usage_state clipcard_usage_state,
       fact_exerp_clipcard_usage.clipcard_usage_type clipcard_usage_type,
       fact_exerp_clipcard_usage.clips clips,
       fact_exerp_clipcard_usage.clips_initial clips_initial,
       fact_exerp_clipcard_usage.commission_units commission_units,
       fact_exerp_clipcard_usage.delivered_dim_club_key delivered_dim_club_key,
       fact_exerp_clipcard_usage.delivered_dim_employee_key delivered_dim_employee_key,
       fact_exerp_clipcard_usage.dim_exerp_booking_key dim_exerp_booking_key,
       fact_exerp_clipcard_usage.dim_exerp_clipcard_key dim_exerp_clipcard_key,
       fact_exerp_clipcard_usage.dim_exerp_product_key dim_exerp_product_key,
       fact_exerp_clipcard_usage.dim_mms_member_key dim_mms_member_key,
       fact_exerp_clipcard_usage.fact_exerp_clipcard_usage_key fact_exerp_clipcard_usage_key,
       fact_exerp_clipcard_usage.participation_complete_flag participation_complete_flag,
       fact_exerp_clipcard_usage.sale_entered_dim_employee_key sale_entered_dim_employee_key,
       fact_exerp_clipcard_usage.sale_entry_dim_date_key sale_entry_dim_date_key,
       fact_exerp_clipcard_usage.sale_entry_dim_time_key sale_entry_dim_time_key,
       fact_exerp_clipcard_usage.sale_source_type sale_source_type,
       fact_exerp_clipcard_usage.usage_dim_date_key usage_dim_date_key,
       fact_exerp_clipcard_usage.usage_dim_time_key usage_dim_time_key
  from dbo.fact_exerp_clipcard_usage;