CREATE VIEW [marketing].[v_fact_exacttarget_clicks] AS select p_exacttarget_clicks.bk_hash fact_exacttarget_clicks_key,
       s_exacttarget_clicks.client_id client_id,
       s_exacttarget_clicks.send_id send_id,
       s_exacttarget_clicks.subscriber_id subscriber_id,
       s_exacttarget_clicks.list_id list_id,
       s_exacttarget_clicks.batch_id batch_id,
       s_exacttarget_clicks.alias alias,
       s_exacttarget_clicks.area_code area_code,
       s_exacttarget_clicks.browser browser,
       s_exacttarget_clicks.city city,
       s_exacttarget_clicks.country country,
       s_exacttarget_clicks.device device,
       s_exacttarget_clicks.email_address email_address,
       s_exacttarget_clicks.email_client email_client,
       s_exacttarget_clicks.event_date event_date,
       s_exacttarget_clicks.event_type event_type,
       s_exacttarget_clicks.ip_address ip_address,
       s_exacttarget_clicks.is_unique is_unique,
       s_exacttarget_clicks.is_unique_for_url is_unique_for_url,
       s_exacttarget_clicks.latitude latitude,
       s_exacttarget_clicks.longitude longitude,
       s_exacttarget_clicks.metro_code metro_code,
       s_exacttarget_clicks.operating_system operating_system,
       s_exacttarget_clicks.region region,
       s_exacttarget_clicks.send_url_id send_url_id,
       s_exacttarget_clicks.subscriber_key subscriber_key,
       s_exacttarget_clicks.triggered_send_external_key triggered_send_external_key,
       s_exacttarget_clicks.url url,
       s_exacttarget_clicks.url_id url_id,
       p_exacttarget_clicks.dv_batch_id dv_batch_id
  from dbo.p_exacttarget_clicks
  join dbo.s_exacttarget_clicks
    on p_exacttarget_clicks.bk_hash = s_exacttarget_clicks.bk_hash 
   and p_exacttarget_clicks.s_exacttarget_clicks_id = s_exacttarget_clicks.s_exacttarget_clicks_id;