CREATE VIEW [marketing].[v_fact_cafe_cumulative_tender]
AS select d_ig_it_trn_tender_cum_BD.fact_cafe_cumulative_tender_key fact_cafe_cumulative_tender_key,
       d_ig_it_trn_tender_cum_BD.void_type_id void_type_id,
       d_ig_it_trn_tender_cum_BD.bus_day_id bus_day_id,
       d_ig_it_trn_tender_cum_BD.check_type_id check_type_id,
       d_ig_it_trn_tender_cum_BD.meal_period_id meal_period_id,
       d_ig_it_trn_tender_cum_BD.cashier_emp_id cashier_emp_id,
       d_ig_it_trn_tender_cum_BD.PMS_post_code PMS_post_code,
       d_ig_it_trn_tender_cum_BD.profit_center_id profit_center_id,
       d_ig_it_trn_tender_cum_BD.tax_removed_code tax_removed_code,
       d_ig_it_trn_tender_cum_BD.tender_id tender_id,
       d_ig_it_trn_tender_cum_BD.base_tender_amount base_tender_amount,
       d_ig_it_trn_tender_cum_BD.breakage_amount breakage_amount,
       d_ig_it_trn_tender_cum_BD.cashier_dim_cafe_employee_key cashier_dim_cafe_employee_key,
       d_ig_it_trn_tender_cum_BD.change_amount change_amount,
       d_ig_it_trn_tender_cum_BD.dim_cafe_business_day_dates_key dim_cafe_business_day_dates_key,
       d_ig_it_trn_tender_cum_BD.dim_cafe_check_type_key dim_cafe_check_type_key,
       d_ig_it_trn_tender_cum_BD.dim_cafe_meal_period_key dim_cafe_meal_period_key,
       d_ig_it_trn_tender_cum_BD.dim_cafe_payment_type_key dim_cafe_payment_type_key,
       d_ig_it_trn_tender_cum_BD.dim_cafe_profit_center_key  dim_cafe_profit_center_key ,
       d_ig_it_trn_tender_cum_BD.net_tender_amount net_tender_amount,
       d_ig_it_trn_tender_cum_BD.received_curr_amount received_curr_amount,
       d_ig_it_trn_tender_cum_BD.tender_quantity tender_quantity,
       d_ig_it_trn_tender_cum_BD.tip_amount tip_amount
  from dbo.d_ig_it_trn_tender_cum_BD;