CREATE VIEW [marketing].[v_fact_magento_tran_item]
AS select fact_magento_tran_item.allocated_amount allocated_amount,
       fact_magento_tran_item.allocated_datetime allocated_datetime,
       fact_magento_tran_item.allocated_dim_club_key allocated_dim_club_key,
       fact_magento_tran_item.allocated_dim_date_key allocated_dim_date_key,
       fact_magento_tran_item.allocated_month_starting_dim_date_key allocated_month_starting_dim_date_key,
       fact_magento_tran_item.allocated_recalculate_through_datetime allocated_recalculate_through_datetime,
       fact_magento_tran_item.allocated_recalculate_through_dim_date_key allocated_recalculate_through_dim_date_key,
       fact_magento_tran_item.batch_number batch_number,
       fact_magento_tran_item.canceled_datetime canceled_datetime,
       fact_magento_tran_item.canceled_dim_date_key canceled_dim_date_key,
       fact_magento_tran_item.cc_last_4 cc_last_4,
       fact_magento_tran_item.credit_tran_id credit_tran_id,
       fact_magento_tran_item.dim_club_key dim_club_key,
       fact_magento_tran_item.dim_employee_key dim_employee_key,
       fact_magento_tran_item.dim_magento_customer_key dim_magento_customer_key,
       fact_magento_tran_item.dim_magento_product_key dim_magento_product_key,
       fact_magento_tran_item.dim_mms_member_key dim_mms_member_key,
       fact_magento_tran_item.dim_mms_membership_key dim_mms_membership_key,
       fact_magento_tran_item.employee_id employee_id,
       fact_magento_tran_item.unique_key fact_magento_transaction_item_key,
       case when fact_magento_tran_item.refund_flag ='N' then fact_magento_tran_item.allocated_datetime else null end invoice_datetime,
       case when fact_magento_tran_item.refund_flag ='N' then fact_magento_tran_item.allocated_dim_date_key else '-998' end invoice_dim_date_key,
       fact_magento_tran_item.member_id member_id,
       fact_magento_tran_item.order_datetime order_datetime,
       fact_magento_tran_item.order_dim_date_key order_dim_date_key,
       fact_magento_tran_item.order_id order_id,
       fact_magento_tran_item.order_item_id order_item_id,
       fact_magento_tran_item.order_number order_number,
       fact_magento_tran_item.order_status order_status,
       fact_magento_tran_item.original_currency_code original_currency_code,
       fact_magento_tran_item.payment_type payment_type,
       fact_magento_tran_item.payroll_amount payroll_amount,
       fact_magento_tran_item.payroll_dim_club_key payroll_dim_club_key,
       fact_magento_tran_item.product_cost product_cost,
       fact_magento_tran_item.product_price product_price,
       case when fact_magento_tran_item.refund_flag ='Y' then fact_magento_tran_item.allocated_datetime else null end refund_datetime,
       case when fact_magento_tran_item.refund_flag ='Y' then fact_magento_tran_item.allocated_dim_date_key else '-998' end refund_dim_date_key,
       fact_magento_tran_item.refund_flag refund_flag,
       fact_magento_tran_item.refund_number refund_number,
       fact_magento_tran_item.shipment_datetime shipment_datetime,
       fact_magento_tran_item.shipment_dim_date_key shipment_dim_date_key,
       fact_magento_tran_item.shipping_amount shipping_amount,
       fact_magento_tran_item.shipping_state shipping_state,
       fact_magento_tran_item.shipping_tax_amount shipping_tax_amount,
       fact_magento_tran_item.transaction_amount transaction_amount,
       fact_magento_tran_item.transaction_bucks_amount transaction_bucks_amount,
       fact_magento_tran_item.order_datetime transaction_datetime,
       fact_magento_tran_item.order_dim_date_key transaction_dim_date_key,
       fact_magento_tran_item.transaction_discount_amount transaction_discount_amount,
       fact_magento_tran_item.transaction_item_amount transaction_item_amount,
       fact_magento_tran_item.transaction_quantity transaction_quantity,
       fact_magento_tran_item.transaction_reporting_dim_club_key transaction_reporting_dim_club_key,
       fact_magento_tran_item.transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key,
       fact_magento_tran_item.transaction_tax_amount transaction_tax_amount,
       fact_magento_tran_item.udw_inserted_dim_date_key udw_inserted_dim_date_key,
       fact_magento_tran_item.unique_key unique_key,
       fact_magento_tran_item.usd_daily_dim_exchange_rate_key usd_daily_dim_exchange_rate_key,
       fact_magento_tran_item.usd_dim_plan_exchange_rate_key usd_dim_plan_exchange_rate_key,
       fact_magento_tran_item.usd_monthly_average_dim_exchange_rate_key usd_monthly_average_dim_exchange_rate_key
  from dbo.fact_magento_tran_item;