CREATE EXTERNAL TABLE [dbo].[ex_clickstream_raw_mobile] (
    [pandas_index] INT NULL,
    [accept_language] NVARCHAR (255) NULL,
    [browser] NVARCHAR (255) NULL,
    [browser_height] DECIMAL (2, 1) NULL,
    [browser_width] DECIMAL (2, 1) NULL,
    [carrier] NVARCHAR (MAX) NULL,
    [click_action_type] DECIMAL (2, 1) NULL,
    [click_context_type] DECIMAL (2, 1) NULL,
    [click_sourceid] NVARCHAR (MAX) NULL,
    [code_ver] NVARCHAR (MAX) NULL,
    [color] NVARCHAR (MAX) NULL,
    [connection_type] DECIMAL (2, 1) NULL,
    [cookies] NVARCHAR (MAX) NULL,
    [country] DECIMAL (4, 1) NULL,
    [curr_factor] NVARCHAR (MAX) NULL,
    [curr_rate] NVARCHAR (MAX) NULL,
    [cust_hit_time_gmt] NVARCHAR (MAX) NULL,
    [daily_visitor] DECIMAL (2, 1) NULL,
    [date_time] DATETIME2 (7) NULL,
    [domain] NVARCHAR (MAX) NULL,
    [duplicate_purchase] DECIMAL (2, 1) NULL,
    [exclude_hit] DECIMAL (4, 2) NULL,
    [first_hit_pagename] NVARCHAR (MAX) NULL,
    [first_hit_ref_type] DECIMAL (2, 1) NULL,
    [first_hit_time_gmt] NVARCHAR (MAX) NULL,
    [geo_city] NVARCHAR (MAX) NULL,
    [geo_country] NVARCHAR (MAX) NULL,
    [geo_dma] NVARCHAR (MAX) NULL,
    [geo_region] NVARCHAR (MAX) NULL,
    [geo_zip] NVARCHAR (MAX) NULL,
    [hit_source] DECIMAL (2, 1) NULL,
    [hit_time_gmt] DECIMAL (11, 1) NULL,
    [hitid_high] NVARCHAR (MAX) NULL,
    [hitid_low] NVARCHAR (MAX) NULL,
    [homepage] NVARCHAR (MAX) NULL,
    [hourly_visitor] DECIMAL (2, 1) NULL,
    [ip] VARCHAR (16) NULL,
    [java_enabled] VARCHAR (1) NULL,
    [javascript] NVARCHAR (MAX) NULL,
    [language] NVARCHAR (MAX) NULL,
    [last_hit_time_gmt] DECIMAL (13, 1) NULL,
    [last_purchase_num] DECIMAL (2, 1) NULL,
    [last_purchase_time_gmt] DECIMAL (2, 1) NULL,
    [mcvisid] DECIMAL (2, 1) NULL,
    [mobile_id] DECIMAL (12, 2) NULL,
    [monthly_visitor] DECIMAL (2, 1) NULL,
    [new_visit] DECIMAL (2, 1) NULL,
    [os] DECIMAL (12, 2) NULL,
    [page_event] DECIMAL (4, 1) NULL,
    [page_event_var2] NVARCHAR (MAX) NULL,
    [pagename] NVARCHAR (MAX) NULL,
    [paid_search] DECIMAL (2, 1) NULL,
    [persistent_cookie] VARCHAR (1) NULL,
    [post_browser_height] DECIMAL (2, 1) NULL,
    [post_browser_width] DECIMAL (2, 1) NULL,
    [post_cookies] VARCHAR (1) NULL,
    [post_currency] VARCHAR (3) NULL,
    [post_cust_hit_time_gmt] DECIMAL (12, 2) NULL,
    [post_evar1] DECIMAL (12, 2) NULL,
    [post_evar2] VARCHAR (6) NULL,
    [post_evar3] NVARCHAR (MAX) NULL,
    [post_evar4] NVARCHAR (MAX) NULL,
    [post_evar5] NVARCHAR (MAX) NULL,
    [post_evar7] NVARCHAR (MAX) NULL,
    [post_evar8] NVARCHAR (MAX) NULL,
    [post_evar9] NVARCHAR (MAX) NULL,
    [post_evar10] NVARCHAR (MAX) NULL,
    [post_evar11] NVARCHAR (MAX) NULL,
    [post_event_list] NVARCHAR (MAX) NULL,
    [post_java_enabled] VARCHAR (1) NULL,
    [post_mobileaction] NVARCHAR (MAX) NULL,
    [post_mobileappid] NVARCHAR (MAX) NULL,
    [post_mobiledayofweek] DECIMAL (2, 1) NULL,
    [post_mobiledayssincefirstuse] DECIMAL (6, 1) NULL,
    [post_mobiledayssincelastuse] DECIMAL (6, 1) NULL,
    [post_mobiledevice] NVARCHAR (MAX) NULL,
    [post_mobilehourofday] DECIMAL (3, 1) NULL,
    [post_mobileinstalldate] NVARCHAR (MAX) NULL,
    [post_mobilelaunchnumber] DECIMAL (7, 1) NULL,
    [post_mobileosversion] NVARCHAR (MAX) NULL,
    [post_mobileresolution] NVARCHAR (MAX) NULL,
    [post_page_event] DECIMAL (4, 1) NULL,
    [post_page_event_var2] NVARCHAR (MAX) NULL,
    [post_pagename] NVARCHAR (MAX) NULL,
    [post_pagename_no_url] NVARCHAR (MAX) NULL,
    [post_persistent_cookie] VARCHAR (1) NULL,
    [post_product_list] NVARCHAR (MAX) NULL,
    [post_prop1] NVARCHAR (MAX) NULL,
    [post_prop2] DECIMAL (3, 1) NULL,
    [post_prop3] DECIMAL (3, 1) NULL,
    [post_prop4] NVARCHAR (MAX) NULL,
    [post_prop5] NVARCHAR (MAX) NULL,
    [post_prop6] NVARCHAR (MAX) NULL,
    [post_prop7] NVARCHAR (MAX) NULL,
    [post_prop8] NVARCHAR (MAX) NULL,
    [post_search_engine] DECIMAL (3, 1) NULL,
    [post_t_time_info] NVARCHAR (MAX) NULL,
    [post_visid_high] NVARCHAR (MAX) NULL,
    [post_visid_low] NVARCHAR (MAX) NULL,
    [post_visid_type] DECIMAL (3, 1) NULL,
    [post_zip] NVARCHAR (MAX) NULL,
    [prev_page] DECIMAL (12, 1) NULL,
    [quarterly_visitor] DECIMAL (2, 1) NULL,
    [ref_type] DECIMAL (2, 1) NULL,
    [resolution] DECIMAL (2, 1) NULL,
    [sampled_hit] VARCHAR (1) NULL,
    [search_engine] DECIMAL (2, 1) NULL,
    [search_page_num] DECIMAL (5, 1) NULL,
    [secondary_hit] DECIMAL (8, 3) NULL,
    [service] VARCHAR (2) NULL,
    [sourceid] DECIMAL (12, 3) NULL,
    [stats_server] NVARCHAR (MAX) NULL,
    [t_time_info] NVARCHAR (MAX) NULL,
    [truncated_hit] VARCHAR (1) NULL,
    [user_agent] NVARCHAR (MAX) NULL,
    [user_hash] NVARCHAR (MAX) NULL,
    [userid] NVARCHAR (MAX) NULL,
    [username] NVARCHAR (MAX) NULL,
    [va_closer_id] DECIMAL (2, 1) NULL,
    [va_finder_id] DECIMAL (2, 1) NULL,
    [va_instance_event] DECIMAL (2, 1) NULL,
    [va_new_engagement] DECIMAL (2, 1) NULL,
    [visid_high] NVARCHAR (MAX) NULL,
    [visid_low] NVARCHAR (MAX) NULL,
    [visid_new] VARCHAR (1) NULL,
    [visid_timestamp] DECIMAL (12, 1) NULL,
    [visid_type] DECIMAL (2, 1) NULL,
    [visit_num] DECIMAL (5, 1) NULL,
    [visit_page_num] DECIMAL (5, 1) NULL,
    [visit_ref_type] DECIMAL (2, 1) NULL,
    [visit_search_engine] DECIMAL (2, 1) NULL,
    [visit_start_pagename] NVARCHAR (MAX) NULL,
    [visit_start_time_gmt] DECIMAL (12, 1) NULL,
    [weekly_visitor] DECIMAL (2, 1) NULL,
    [yearly_visitor] DECIMAL (2, 1) NULL
)
    WITH (
    DATA_SOURCE = [dl_ext_source_bidistributeddatablob_rawzone_clickstream],
    LOCATION = N'/mobile',
    FILE_FORMAT = [dl_file_format_clickstream_mobile],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

