CREATE TABLE [dbo].[d_athlinks_api_vw_athlete_non_member] (
    [d_athlinks_api_vw_athlete_non_member_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)      NOT NULL,
    [racer_id]                                INT            NULL,
    [age]                                     INT            NULL,
    [city]                                    NVARCHAR (255) NULL,
    [country_id]                              CHAR (2)       NULL,
    [country_id_3]                            CHAR (3)       NULL,
    [country_name]                            NVARCHAR (255) NULL,
    [create_date]                             DATETIME       NULL,
    [create_dim_date_key]                     VARCHAR (8)    NULL,
    [create_dim_time_key]                     INT            NULL,
    [display_name]                            NVARCHAR (255) NULL,
    [full_name]                               NVARCHAR (255) NULL,
    [gender]                                  CHAR (1)       NULL,
    [is_member]                               VARCHAR (1)    NULL,
    [join_date]                               DATETIME       NULL,
    [join_dim_date_key]                       VARCHAR (8)    NULL,
    [join_dim_time_key]                       INT            NULL,
    [last_name]                               NVARCHAR (255) NULL,
    [notes]                                   VARCHAR (255)  NULL,
    [owner_id]                                INT            NULL,
    [photo_path]                              VARCHAR (255)  NULL,
    [result_count]                            INT            NULL,
    [state_prov_abbrev]                       NVARCHAR (255) NULL,
    [state_prov_id]                           NVARCHAR (255) NULL,
    [state_prov_name]                         NVARCHAR (255) NULL,
    [p_athlinks_api_vw_athlete_non_member_id] BIGINT         NOT NULL,
    [deleted_flag]                            INT            NULL,
    [dv_load_date_time]                       DATETIME       NULL,
    [dv_load_end_date_time]                   DATETIME       NULL,
    [dv_batch_id]                             BIGINT         NOT NULL,
    [dv_inserted_date_time]                   DATETIME       NOT NULL,
    [dv_insert_user]                          VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                    DATETIME       NULL,
    [dv_update_user]                          VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

