CREATE TABLE [dbo].[d_athlinks_api_vw_master_event] (
    [d_athlinks_api_vw_master_event_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)       NOT NULL,
    [master_id]                                    INT             NULL,
    [city]                                         NVARCHAR (128)  NULL,
    [company_id]                                   INT             NULL,
    [company_name]                                 NVARCHAR (50)   NULL,
    [contact_address]                              NVARCHAR (1000) NULL,
    [contact_name]                                 NVARCHAR (256)  NULL,
    [country_id]                                   CHAR (2)        NULL,
    [create_date]                                  DATETIME        NULL,
    [create_dim_date_key]                          VARCHAR (8)     NULL,
    [create_dim_time_key]                          INT             NULL,
    [curated_desc]                                 NVARCHAR (1000) NULL,
    [elevation]                                    INT             NULL,
    [featured_flag]                                CHAR (1)        NULL,
    [geo]                                          VARCHAR (4000)  NULL,
    [latitude]                                     DECIMAL (26, 6) NULL,
    [logo_path]                                    NVARCHAR (512)  NULL,
    [longitude]                                    DECIMAL (26, 6) NULL,
    [master_event_name]                            NVARCHAR (128)  NULL,
    [next_d_athlinks_api_vw_race_ltf_data_bk_hash] VARCHAR (32)    NULL,
    [next_date]                                    DATETIME        NULL,
    [next_dim_date_key]                            VARCHAR (8)     NULL,
    [next_dim_time_key]                            INT             NULL,
    [next_race_id]                                 INT             NULL,
    [phone]                                        NVARCHAR (100)  NULL,
    [prev_d_athlinks_api_vw_race_ltf_data_bk_hash] VARCHAR (32)    NULL,
    [prev_date]                                    DATETIME        NULL,
    [prev_dim_date_key]                            VARCHAR (8)     NULL,
    [prev_dim_time_key]                            INT             NULL,
    [prev_race_id]                                 INT             NULL,
    [race_count]                                   INT             NULL,
    [result_count]                                 INT             NULL,
    [short_url]                                    VARCHAR (128)   NULL,
    [state_prov_abbrev]                            NVARCHAR (8)    NULL,
    [state_prov_id]                                NVARCHAR (8)    NULL,
    [p_athlinks_api_vw_master_event_id]            BIGINT          NOT NULL,
    [deleted_flag]                                 INT             NULL,
    [dv_load_date_time]                            DATETIME        NULL,
    [dv_load_end_date_time]                        DATETIME        NULL,
    [dv_batch_id]                                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                        DATETIME        NOT NULL,
    [dv_insert_user]                               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                         DATETIME        NULL,
    [dv_update_user]                               VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

