CREATE TABLE [dbo].[d_athlinks_api_vw_race_entry] (
    [d_athlinks_api_vw_race_entry_id]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)      NOT NULL,
    [entry_id]                                     INT            NULL,
    [age]                                          INT            NULL,
    [bib_num]                                      NVARCHAR (24)  NULL,
    [city]                                         NVARCHAR (128) NULL,
    [class_id]                                     INT            NULL,
    [class_name]                                   NVARCHAR (255) NULL,
    [course_id]                                    INT            NULL,
    [create_date]                                  DATETIME       NULL,
    [create_dim_date_key]                          VARCHAR (8)    NULL,
    [create_dim_time_key]                          INT            NULL,
    [d_athlinks_api_vw_athlete_non_member_bk_hash] VARCHAR (32)   NULL,
    [d_athlinks_api_vw_course_bk_hash]             VARCHAR (32)   NULL,
    [d_athlinks_api_vw_master_event_bk_hash]       VARCHAR (32)   NULL,
    [d_athlinks_api_vw_race_ltf_data_bk_hash]      VARCHAR (32)   NULL,
    [display_name]                                 NVARCHAR (50)  NULL,
    [entry_state_prov_id]                          NVARCHAR (8)   NULL,
    [event_course_id]                              INT            NULL,
    [event_d_athlinks_api_vw_course_bk_hash]       VARCHAR (32)   NULL,
    [gender]                                       CHAR (1)       NULL,
    [is_member_flag]                               CHAR (1)       NULL,
    [master_id]                                    INT            NULL,
    [master_name]                                  NVARCHAR (128) NULL,
    [photo_path]                                   VARCHAR (1)    NULL,
    [race_date]                                    DATETIME       NULL,
    [race_dim_date_key]                            VARCHAR (8)    NULL,
    [race_dim_time_key]                            INT            NULL,
    [race_id]                                      INT            NULL,
    [racer_id]                                     INT            NULL,
    [rank_a]                                       INT            NULL,
    [rank_g]                                       INT            NULL,
    [rank_o]                                       INT            NULL,
    [result_count]                                 INT            NULL,
    [results_date]                                 DATETIME       NULL,
    [results_dim_date_key]                         VARCHAR (8)    NULL,
    [results_dim_time_key]                         INT            NULL,
    [ticks]                                        BIGINT         NULL,
    [ticks_string]                                 VARCHAR (16)   NULL,
    [total_a]                                      INT            NULL,
    [total_g]                                      INT            NULL,
    [total_o]                                      INT            NULL,
    [p_athlinks_api_vw_race_entry_id]              BIGINT         NOT NULL,
    [deleted_flag]                                 INT            NULL,
    [dv_load_date_time]                            DATETIME       NULL,
    [dv_load_end_date_time]                        DATETIME       NULL,
    [dv_batch_id]                                  BIGINT         NOT NULL,
    [dv_inserted_date_time]                        DATETIME       NOT NULL,
    [dv_insert_user]                               VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                         DATETIME       NULL,
    [dv_update_user]                               VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

