CREATE TABLE [dbo].[d_athlinks_api_vw_course] (
    [d_athlinks_api_vw_course_id]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                               CHAR (32)       NOT NULL,
    [course_id]                                             INT             NULL,
    [course_name]                                           NVARCHAR (255)  NULL,
    [course_pattern]                                        NVARCHAR (260)  NULL,
    [course_pattern_d_athlinks_api_vw_course_bk_hash]       VARCHAR (32)    NULL,
    [course_pattern_id]                                     INT             NULL,
    [course_pattern_outer_d_athlinks_api_vw_course_bk_hash] VARCHAR (32)    NULL,
    [course_pattern_outer_id]                               INT             NULL,
    [course_pattern_outer_name]                             NVARCHAR (260)  NULL,
    [create_date]                                           DATETIME        NULL,
    [create_dim_date_key]                                   VARCHAR (8)     NULL,
    [create_dim_time_key]                                   INT             NULL,
    [d_athlinks_api_vw_race_ltf_data_bk_hash]               VARCHAR (32)    NULL,
    [dist_type_id]                                          INT             NULL,
    [dist_unit]                                             DECIMAL (18, 2) NULL,
    [event_course_d_athlinks_api_vw_course_bk_hash]         VARCHAR (32)    NULL,
    [event_course_id]                                       INT             NULL,
    [gallery_id]                                            INT             NULL,
    [overall_count]                                         INT             NULL,
    [race_cat_d_athlinks_api_vw_race_ltf_data_bk_hash]      VARCHAR (32)    NULL,
    [race_cat_desc]                                         NVARCHAR (50)   NULL,
    [race_cat_id]                                           INT             NULL,
    [race_id]                                               INT             NULL,
    [results_date]                                          DATETIME        NULL,
    [results_dim_date_key]                                  VARCHAR (8)     NULL,
    [results_dim_time_key]                                  INT             NULL,
    [results_user]                                          INT             NULL,
    [settings]                                              INT             NULL,
    [p_athlinks_api_vw_course_id]                           BIGINT          NOT NULL,
    [deleted_flag]                                          INT             NULL,
    [dv_load_date_time]                                     DATETIME        NULL,
    [dv_load_end_date_time]                                 DATETIME        NULL,
    [dv_batch_id]                                           BIGINT          NOT NULL,
    [dv_inserted_date_time]                                 DATETIME        NOT NULL,
    [dv_insert_user]                                        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                  DATETIME        NULL,
    [dv_update_user]                                        VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

