CREATE TABLE [dbo].[d_boss_employees] (
    [d_boss_employees_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                 CHAR (32)       NOT NULL,
    [employee_id]             INT             NULL,
    [cost]                    DECIMAL (26, 6) NULL,
    [d_boss_interest_bk_hash] CHAR (32)       NULL,
    [employee_url]            VARCHAR (80)    NULL,
    [employees_badge]         CHAR (10)       NULL,
    [employees_email]         VARCHAR (240)   NULL,
    [employees_first]         NCHAR (25)      NULL,
    [employees_last]          NCHAR (25)      NULL,
    [employees_nickname]      CHAR (30)       NULL,
    [employees_status]        CHAR (1)        NULL,
    [employees_user_profile]  VARCHAR (240)   NULL,
    [home_club]               INT             NULL,
    [id]                      INT             NULL,
    [interest_id]             INT             NULL,
    [member_ID]               CHAR (10)       NULL,
    [MI]                      CHAR (1)        NULL,
    [phone]                   VARCHAR (20)    NULL,
    [res_color]               INT             NULL,
    [role_id]                 INT             NULL,
    [p_boss_employees_id]     BIGINT          NOT NULL,
    [deleted_flag]            INT             NULL,
    [dv_load_date_time]       DATETIME        NULL,
    [dv_load_end_date_time]   DATETIME        NULL,
    [dv_batch_id]             BIGINT          NOT NULL,
    [dv_inserted_date_time]   DATETIME        NOT NULL,
    [dv_insert_user]          VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]    DATETIME        NULL,
    [dv_update_user]          VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

