CREATE TABLE [dbo].[d_chronotrack_entry] (
    [d_chronotrack_entry_id]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)      NOT NULL,
    [entry_id]                                BIGINT         NULL,
    [allow_tracking]                          TINYINT        NULL,
    [apply_wave_rule]                         INT            NULL,
    [athlete_id]                              BIGINT         NULL,
    [auto_bracket_policy]                     NCHAR (4)      NULL,
    [bib]                                     NVARCHAR (15)  NULL,
    [create_time]                             INT            NULL,
    [d_athlinks_api_vw_race_ltf_data_bk_hash] VARCHAR (32)   NULL,
    [d_chronotrack_athlete_bk_hash]           VARCHAR (32)   NULL,
    [external_id]                             NVARCHAR (255) NULL,
    [location_string]                         NVARCHAR (255) NULL,
    [modified_time]                           INT            NULL,
    [name]                                    NVARCHAR (255) NULL,
    [notes]                                   VARCHAR (4000) NULL,
    [override_bracket_rule]                   SMALLINT       NULL,
    [prefered_bracket_id]                     BIGINT         NULL,
    [primary_bracket_id]                      BIGINT         NULL,
    [race_age]                                INT            NULL,
    [race_id]                                 BIGINT         NULL,
    [reg_option_id]                           BIGINT         NULL,
    [reg_sms]                                 INT            NULL,
    [reg_soc_msg]                             TINYINT        NULL,
    [remove_bracket]                          NCHAR (48)     NULL,
    [search_result]                           NVARCHAR (255) NULL,
    [status]                                  NCHAR (12)     NULL,
    [team_id]                                 BIGINT         NULL,
    [trans_id]                                BIGINT         NULL,
    [type]                                    NCHAR (6)      NULL,
    [wave_id]                                 BIGINT         NULL,
    [p_chronotrack_entry_id]                  BIGINT         NOT NULL,
    [deleted_flag]                            INT            NULL,
    [dv_load_date_time]                       DATETIME       NULL,
    [dv_load_end_date_time]                   DATETIME       NULL,
    [dv_batch_id]                             BIGINT         NOT NULL,
    [dv_inserted_date_time]                   DATETIME       NOT NULL,
    [dv_insert_user]                          VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                    DATETIME       NULL,
    [dv_update_user]                          VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

