CREATE TABLE [dbo].[d_chronotrack_athlete] (
    [d_chronotrack_athlete_id]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                        CHAR (32)      NOT NULL,
    [athlete_id]                     BIGINT         NULL,
    [account_id]                     BIGINT         NULL,
    [age]                            TINYINT        NULL,
    [birth_date]                     DATETIME       NULL,
    [birth_dim_date_key]             VARCHAR (8)    NULL,
    [create_time]                    INT            NULL,
    [d_chronotrack_location_bk_hash] VARCHAR (32)   NULL,
    [email]                          NVARCHAR (255) NULL,
    [emerg_name]                     NVARCHAR (50)  NULL,
    [emerg_phone]                    NVARCHAR (20)  NULL,
    [emerg_relationship]             NVARCHAR (255) NULL,
    [first_name]                     NVARCHAR (40)  NULL,
    [home_phone]                     NVARCHAR (20)  NULL,
    [last_name]                      NVARCHAR (40)  NULL,
    [location_id]                    BIGINT         NULL,
    [medical_notes]                  VARCHAR (4000) NULL,
    [middle_name]                    NVARCHAR (40)  NULL,
    [mobile_phone]                   NVARCHAR (20)  NULL,
    [modified_time]                  INT            NULL,
    [name_pronunciation]             NVARCHAR (255) NULL,
    [sex]                            NCHAR (13)     NULL,
    [tshirt_size]                    NVARCHAR (15)  NULL,
    [usat_num]                       NVARCHAR (36)  NULL,
    [p_chronotrack_athlete_id]       BIGINT         NOT NULL,
    [deleted_flag]                   INT            NULL,
    [dv_load_date_time]              DATETIME       NULL,
    [dv_load_end_date_time]          DATETIME       NULL,
    [dv_batch_id]                    BIGINT         NOT NULL,
    [dv_inserted_date_time]          DATETIME       NOT NULL,
    [dv_insert_user]                 VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]           DATETIME       NULL,
    [dv_update_user]                 VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

