CREATE TABLE [dbo].[d_chronotrack_event] (
    [d_chronotrack_event_id]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)      NOT NULL,
    [event_id]                               BIGINT         NULL,
    [check_in_flag]                          CHAR (1)       NULL,
    [check_payable]                          NVARCHAR (255) NULL,
    [create_time]                            INT            NULL,
    [currency_id]                            NCHAR (3)      NULL,
    [d_chronotrack_location_bk_hash]         VARCHAR (32)   NULL,
    [date_format]                            NVARCHAR (5)   NULL,
    [description]                            NVARCHAR (512) NULL,
    [enable_teams_flag]                      CHAR (1)       NULL,
    [end_datetime]                           DATETIME       NULL,
    [end_dim_date_key]                       VARCHAR (8)    NULL,
    [end_dim_time_key]                       INT            NULL,
    [end_time]                               INT            NULL,
    [event_group_id]                         BIGINT         NULL,
    [event_name]                             NVARCHAR (255) NULL,
    [external_id]                            NVARCHAR (255) NULL,
    [is_membership_flag]                     CHAR (1)       NULL,
    [is_published_athlinks_flag]             CHAR (1)       NULL,
    [is_published_flag]                      CHAR (1)       NULL,
    [is_test_event_flag]                     CHAR (1)       NULL,
    [language_id]                            NCHAR (2)      NULL,
    [last_yrs_d_chronotrack_event_bk_hash]   VARCHAR (32)   NULL,
    [last_yrs_event_id]                      BIGINT         NULL,
    [location_id]                            BIGINT         NULL,
    [marketing_consent_question]             VARCHAR (4000) NULL,
    [marketing_consent_question_text]        VARCHAR (4000) NULL,
    [marketing_email_question]               TINYINT        NULL,
    [marketing_email_question_text]          VARCHAR (4000) NULL,
    [marketing_emails_event_name]            NVARCHAR (255) NULL,
    [max_races]                              SMALLINT       NULL,
    [max_reg_choices]                        INT            NULL,
    [min_interval_duration]                  BIGINT         NULL,
    [modified_time]                          INT            NULL,
    [name_prefix]                            NVARCHAR (255) NULL,
    [online_payee_id]                        BIGINT         NULL,
    [onsite_payee_id]                        BIGINT         NULL,
    [organizer_id]                           BIGINT         NULL,
    [parent_d_chronotrack_event_bk_hash]     VARCHAR (32)   NULL,
    [parent_event_id]                        BIGINT         NULL,
    [payee]                                  NVARCHAR (255) NULL,
    [payment_d_chronotrack_location_bk_hash] VARCHAR (32)   NULL,
    [payment_location_id]                    BIGINT         NULL,
    [series_id]                              BIGINT         NULL,
    [start_datetime]                         DATETIME       NULL,
    [start_dim_date_key]                     VARCHAR (8)    NULL,
    [start_dim_time_key]                     INT            NULL,
    [start_time]                             INT            NULL,
    [tag]                                    NVARCHAR (20)  NULL,
    [timer_id]                               BIGINT         NULL,
    [p_chronotrack_event_id]                 BIGINT         NOT NULL,
    [deleted_flag]                           INT            NULL,
    [dv_load_date_time]                      DATETIME       NULL,
    [dv_load_end_date_time]                  DATETIME       NULL,
    [dv_batch_id]                            BIGINT         NOT NULL,
    [dv_inserted_date_time]                  DATETIME       NOT NULL,
    [dv_insert_user]                         VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                   DATETIME       NULL,
    [dv_update_user]                         VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

