CREATE TABLE [dbo].[d_crmcloudsync_campaign] (
    [d_crmcloudsync_campaign_id]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)      NOT NULL,
    [dim_crm_campaign_key]                VARCHAR (32)   NULL,
    [campaign_id]                         VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]  VARCHAR (32)   NULL,
    [created_dim_date_key]                VARCHAR (8)    NULL,
    [created_dim_time_key]                INT            NULL,
    [created_on]                          DATETIME       NULL,
    [description]                         VARCHAR (8000) NULL,
    [ltf_expiration_type]                 INT            NULL,
    [ltf_issuance_method]                 INT            NULL,
    [ltf_job_id]                          NVARCHAR (100) NULL,
    [ltf_member_referral]                 INT            NULL,
    [ltf_pass_days]                       NVARCHAR (32)  NULL,
    [ltf_restricted_by_policy]            BIT            NULL,
    [ltf_restricted_by_policy_flag]       CHAR (1)       NULL,
    [ltf_reward_club]                     VARCHAR (36)   NULL,
    [ltf_reward_lt_bucks]                 INT            NULL,
    [ltf_reward_type]                     INT            NULL,
    [ltf_reward_wait_days]                INT            NULL,
    [ltf_targeted_prospects]              INT            NULL,
    [modified_by_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [modified_dim_date_key]               VARCHAR (8)    NULL,
    [modified_dim_time_key]               INT            NULL,
    [modified_on]                         DATETIME       NULL,
    [name]                                NVARCHAR (128) NULL,
    [proposed_end]                        DATETIME       NULL,
    [proposed_end_dim_date_key]           VARCHAR (8)    NULL,
    [proposed_end_dim_time_key]           INT            NULL,
    [proposed_start]                      DATETIME       NULL,
    [proposed_start_dim_date_key]         VARCHAR (8)    NULL,
    [proposed_start_dim_time_key]         INT            NULL,
    [state_code]                          INT            NULL,
    [state_code_name]                     NVARCHAR (255) NULL,
    [status_code]                         INT            NULL,
    [status_code_name]                    NVARCHAR (255) NULL,
    [type_code]                           INT            NULL,
    [type_code_name]                      NVARCHAR (255) NULL,
    [p_crmcloudsync_campaign_id]          BIGINT         NOT NULL,
    [deleted_flag]                        INT            NULL,
    [dv_load_date_time]                   DATETIME       NULL,
    [dv_load_end_date_time]               DATETIME       NULL,
    [dv_batch_id]                         BIGINT         NOT NULL,
    [dv_inserted_date_time]               DATETIME       NOT NULL,
    [dv_insert_user]                      VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                DATETIME       NULL,
    [dv_update_user]                      VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

