CREATE TABLE [dbo].[d_crmcloudsync_ltf_campaign_instance] (
    [d_crmcloudsync_ltf_campaign_instance_id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                         CHAR (32)      NOT NULL,
    [dim_crm_ltf_campaign_instance_key]               VARCHAR (32)   NULL,
    [ltf_campaign_instance_id]                        VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]              VARCHAR (32)   NULL,
    [created_by_name]                                 NVARCHAR (200) NULL,
    [created_dim_date_key]                            VARCHAR (8)    NULL,
    [created_dim_time_key]                            INT            NULL,
    [created_on]                                      DATETIME       NULL,
    [created_on_behalf_by_dim_crm_system_user_key]    VARCHAR (32)   NULL,
    [created_on_behalf_by_name]                       NVARCHAR (200) NULL,
    [dim_crm_contact_key]                             VARCHAR (32)   NULL,
    [dim_crm_ltf_club_key]                            VARCHAR (32)   NULL,
    [dim_mms_member_key]                              VARCHAR (32)   NULL,
    [insert_user]                                     VARCHAR (50)   NULL,
    [inserted_date_time]                              DATETIME       NULL,
    [inserted_dim_date_key]                           VARCHAR (8)    NULL,
    [inserted_dim_time_key]                           INT            NULL,
    [ltf_campaign_dim_crm_campaign_key]               VARCHAR (32)   NULL,
    [ltf_campaign_name]                               NVARCHAR (128) NULL,
    [ltf_club_name]                                   NVARCHAR (100) NULL,
    [ltf_connect_witham]                              BIT            NULL,
    [ltf_connect_witham_flag]                         CHAR (1)       NULL,
    [ltf_connect_witham_name]                         NVARCHAR (255) NULL,
    [ltf_expiration_date]                             DATETIME       NULL,
    [ltf_expiration_dim_date_key]                     VARCHAR (8)    NULL,
    [ltf_expiration_dim_time_key]                     INT            NULL,
    [ltf_initial_use_date]                            DATETIME       NULL,
    [ltf_initial_use_dim_date_key]                    VARCHAR (8)    NULL,
    [ltf_initial_use_dim_time_key]                    INT            NULL,
    [ltf_issued_by_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [ltf_issued_by_name]                              NVARCHAR (200) NULL,
    [ltf_issued_date]                                 DATETIME       NULL,
    [ltf_issued_days]                                 INT            NULL,
    [ltf_issued_dim_date_key]                         VARCHAR (8)    NULL,
    [ltf_issued_dim_time_key]                         INT            NULL,
    [ltf_issuing_contact_dim_crm_contact_key]         VARCHAR (32)   NULL,
    [ltf_issuing_contact_name]                        VARCHAR (160)  NULL,
    [ltf_issuing_lead_dim_crm_lead_key]               VARCHAR (32)   NULL,
    [ltf_issuing_lead_name]                           VARCHAR (160)  NULL,
    [ltf_issuing_opportunity_dim_crm_opportunity_key] VARCHAR (32)   NULL,
    [ltf_issuing_opportunity_name]                    VARCHAR (300)  NULL,
    [ltf_name]                                        VARCHAR (100)  NULL,
    [ltf_pass_begin_date]                             DATETIME       NULL,
    [ltf_pass_begin_dim_date_key]                     VARCHAR (8)    NULL,
    [ltf_pass_begin_dim_time_key]                     INT            NULL,
    [ltf_qr_code]                                     VARCHAR (8000) NULL,
    [ltf_referring_corpacct_id]                       NVARCHAR (100) NULL,
    [ltf_referring_member_dim_mms_member_key]         VARCHAR (32)   NULL,
    [ltf_remaining_days]                              INT            NULL,
    [ltf_send_id]                                     NVARCHAR (100) NULL,
    [modified_by_dim_crm_system_user_key]             VARCHAR (32)   NULL,
    [modified_by_name]                                NVARCHAR (200) NULL,
    [modified_dim_date_key]                           VARCHAR (8)    NULL,
    [modified_dim_time_key]                           INT            NULL,
    [modified_on]                                     DATETIME       NULL,
    [modified_on_behalf_by_dim_crm_system_user_key]   VARCHAR (32)   NULL,
    [modified_on_behalf_by_name]                      NVARCHAR (200) NULL,
    [state_code]                                      INT            NULL,
    [state_code_name]                                 NVARCHAR (255) NULL,
    [status_code]                                     INT            NULL,
    [status_code_name]                                NVARCHAR (255) NULL,
    [time_zone_rule_version_number]                   INT            NULL,
    [update_user]                                     VARCHAR (50)   NULL,
    [updated_date_time]                               DATETIME       NULL,
    [updated_dim_date_key]                            VARCHAR (8)    NULL,
    [updated_dim_time_key]                            INT            NULL,
    [utc_conversion_time_zone_code]                   INT            NULL,
    [p_crmcloudsync_ltf_campaign_instance_id]         BIGINT         NOT NULL,
    [deleted_flag]                                    INT            NULL,
    [dv_load_date_time]                               DATETIME       NULL,
    [dv_load_end_date_time]                           DATETIME       NULL,
    [dv_batch_id]                                     BIGINT         NOT NULL,
    [dv_inserted_date_time]                           DATETIME       NOT NULL,
    [dv_insert_user]                                  VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                            DATETIME       NULL,
    [dv_update_user]                                  VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

