CREATE TABLE [dbo].[d_crmcloudsync_ltf_subscription] (
    [d_crmcloudsync_ltf_subscription_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                       CHAR (32)       NOT NULL,
    [dim_crm_ltf_subscription_key]                  VARCHAR (32)    NULL,
    [ltf_subscription_id]                           VARCHAR (36)    NULL,
    [created_by_dim_crm_system_user_key]            VARCHAR (32)    NULL,
    [created_by_name]                               NVARCHAR (200)  NULL,
    [created_dim_date_key]                          VARCHAR (8)     NULL,
    [created_dim_time_key]                          INT             NULL,
    [created_on]                                    DATETIME        NULL,
    [dim_crm_ltf_account_key]                       VARCHAR (32)    NULL,
    [dim_crm_ltf_club_key]                          VARCHAR (32)    NULL,
    [dim_crm_owner_key]                             VARCHAR (32)    NULL,
    [dim_mms_membership_key]                        VARCHAR (32)    NULL,
    [exchange_rate]                                 DECIMAL (28)    NULL,
    [ltf_account_household]                         VARCHAR (36)    NULL,
    [ltf_account_household_name]                    NVARCHAR (160)  NULL,
    [ltf_account_id_name]                           NVARCHAR (160)  NULL,
    [ltf_activation_date]                           DATETIME        NULL,
    [ltf_activation_dim_date_key]                   VARCHAR (8)     NULL,
    [ltf_activation_dim_time_key]                   INT             NULL,
    [ltf_attrition_exclusion]                       BIT             NULL,
    [ltf_attrition_exclusion_flag]                  CHAR (1)        NULL,
    [ltf_attrition_exclusion_name]                  NVARCHAR (255)  NULL,
    [ltf_cancellation_date]                         DATETIME        NULL,
    [ltf_cancellation_dim_date_key]                 VARCHAR (8)     NULL,
    [ltf_cancellation_dim_time_key]                 INT             NULL,
    [ltf_club_id_name]                              NVARCHAR (100)  NULL,
    [ltf_club_portfolio_staffing_id]                VARCHAR (36)    NULL,
    [ltf_club_portfolio_staffing_id_name]           NVARCHAR (100)  NULL,
    [ltf_cost]                                      DECIMAL (26, 6) NULL,
    [ltf_cost_base]                                 DECIMAL (26, 6) NULL,
    [ltf_customer_company_code]                     NVARCHAR (100)  NULL,
    [ltf_lt_health_reactivation_date]               DATETIME        NULL,
    [ltf_lt_health_reactivation_dim_date_key]       VARCHAR (8)     NULL,
    [ltf_lt_health_reactivation_dim_time_key]       INT             NULL,
    [ltf_monthly_cost_of_membership]                DECIMAL (26, 6) NULL,
    [ltf_monthly_cost_of_membership_base]           DECIMAL (26, 6) NULL,
    [ltf_product_id]                                VARCHAR (36)    NULL,
    [ltf_product_id_name]                           NVARCHAR (100)  NULL,
    [ltf_referring_contact_dim_crm_contact_key]     VARCHAR (32)    NULL,
    [ltf_referring_contact_id_name]                 NVARCHAR (160)  NULL,
    [ltf_referring_member_dim_crm_member_key]       VARCHAR (32)    NULL,
    [ltf_revenue_unit]                              BIT             NULL,
    [ltf_revenue_unit_flag]                         CHAR (1)        NULL,
    [ltf_revenue_unit_name]                         NVARCHAR (255)  NULL,
    [ltf_subscription_number]                       NVARCHAR (100)  NULL,
    [ltf_termination_date]                          DATETIME        NULL,
    [ltf_termination_dim_date_key]                  VARCHAR (8)     NULL,
    [ltf_termination_dim_time_key]                  INT             NULL,
    [ltf_termination_reason]                        NVARCHAR (100)  NULL,
    [modified_on_behalf_by_dim_crm_system_user_key] VARCHAR (32)    NULL,
    [modified_on_behalf_by_name]                    NVARCHAR (200)  NULL,
    [overridden_created_dim_date_key]               VARCHAR (8)     NULL,
    [overridden_created_dim_time_key]               INT             NULL,
    [overridden_created_on]                         DATETIME        NULL,
    [owner_id_name]                                 NVARCHAR (200)  NULL,
    [owner_id_type]                                 NVARCHAR (64)   NULL,
    [owning_business_unit]                          VARCHAR (36)    NULL,
    [owning_team]                                   VARCHAR (36)    NULL,
    [owning_user_dim_crm_system_user_key]           VARCHAR (32)    NULL,
    [state_code]                                    INT             NULL,
    [state_code_name]                               NVARCHAR (255)  NULL,
    [status_code]                                   INT             NULL,
    [status_code_name]                              NVARCHAR (255)  NULL,
    [transaction_currency_id]                       VARCHAR (36)    NULL,
    [transaction_currency_id_name]                  NVARCHAR (100)  NULL,
    [version_number]                                BIGINT          NULL,
    [p_crmcloudsync_ltf_subscription_id]            BIGINT          NOT NULL,
    [deleted_flag]                                  INT             NULL,
    [dv_load_date_time]                             DATETIME        NULL,
    [dv_load_end_date_time]                         DATETIME        NULL,
    [dv_batch_id]                                   BIGINT          NOT NULL,
    [dv_inserted_date_time]                         DATETIME        NOT NULL,
    [dv_insert_user]                                VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                          DATETIME        NULL,
    [dv_update_user]                                VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

