CREATE TABLE [dbo].[d_crmcloudsync_ltf_guest_visit] (
    [d_crmcloudsync_ltf_guest_visit_id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                       CHAR (32)       NOT NULL,
    [dim_crm_ltf_guest_visit_key]                   VARCHAR (32)    NULL,
    [activity_id]                                   VARCHAR (36)    NULL,
    [activity_type_code]                            NVARCHAR (64)   NULL,
    [activity_type_code_name]                       NVARCHAR (255)  NULL,
    [created_by_dim_crm_system_user_key]            VARCHAR (32)    NULL,
    [created_dim_date_key]                          VARCHAR (8)     NULL,
    [created_dim_time_key]                          INT             NULL,
    [created_on]                                    DATETIME        NULL,
    [created_on_behalf_by_dim_crm_system_user_key]  VARCHAR (32)    NULL,
    [description]                                   VARCHAR (8000)  NULL,
    [dim_crm_lead_key]                              VARCHAR (32)    NULL,
    [dim_crm_ltf_campaign_instance_key]             VARCHAR (32)    NULL,
    [dim_crm_ltf_club_key]                          VARCHAR (32)    NULL,
    [dim_crm_owner_key]                             VARCHAR (32)    NULL,
    [insert_user]                                   VARCHAR (50)    NULL,
    [inserted_date_time]                            DATETIME        NULL,
    [inserted_dim_date_key]                         VARCHAR (8)     NULL,
    [inserted_dim_time_key]                         INT             NULL,
    [instance_type_code]                            INT             NULL,
    [instance_type_code_name]                       NVARCHAR (255)  NULL,
    [ltf_address_1_city]                            NVARCHAR (50)   NULL,
    [ltf_address_1_county]                          NVARCHAR (50)   NULL,
    [ltf_address_1_line_1]                          NVARCHAR (50)   NULL,
    [ltf_address_1_postal_code]                     NVARCHAR (100)  NULL,
    [ltf_address_1_state_or_province]               NVARCHAR (50)   NULL,
    [ltf_agreement_signature]                       VARCHAR (8000)  NULL,
    [ltf_appointment_dim_crm_activity_key]          VARCHAR (32)    NULL,
    [ltf_appointment_id_name]                       NVARCHAR (200)  NULL,
    [ltf_assigned_mea_dim_crm_account_manager_key]  VARCHAR (32)    NULL,
    [ltf_assigned_mea_name]                         NVARCHAR (200)  NULL,
    [ltf_campaign_instance_name]                    NVARCHAR (100)  NULL,
    [ltf_club_close_to]                             INT             NULL,
    [ltf_club_close_to_name]                        NVARCHAR (255)  NULL,
    [ltf_date_of_birth]                             DATETIME        NULL,
    [ltf_date_of_birth_dim_date_key]                VARCHAR (8)     NULL,
    [ltf_date_of_birth_dim_time_key]                INT             NULL,
    [ltf_deduct_guest_priv]                         BIT             NULL,
    [ltf_email_address_1]                           NVARCHAR (100)  NULL,
    [ltf_employer]                                  NVARCHAR (200)  NULL,
    [ltf_first_name]                                NVARCHAR (50)   NULL,
    [ltf_gender]                                    INT             NULL,
    [ltf_gender_name]                               NVARCHAR (255)  NULL,
    [ltf_guest_type]                                INT             NULL,
    [ltf_guest_type_name]                           NVARCHAR (255)  NULL,
    [ltf_interests]                                 NVARCHAR (1000) NULL,
    [ltf_last_name]                                 NVARCHAR (50)   NULL,
    [ltf_line_of_business]                          INT             NULL,
    [ltf_line_of_business_name]                     NVARCHAR (255)  NULL,
    [ltf_matching_contact_count]                    NVARCHAR (100)  NULL,
    [ltf_matching_lead_count]                       NVARCHAR (100)  NULL,
    [ltf_membership_interest]                       INT             NULL,
    [ltf_membership_interest_name]                  NVARCHAR (255)  NULL,
    [ltf_middle_name]                               NVARCHAR (50)   NULL,
    [ltf_mobile_phone]                              NVARCHAR (50)   NULL,
    [ltf_online]                                    INT             NULL,
    [ltf_online_name]                               NVARCHAR (255)  NULL,
    [ltf_out_of_area]                               INT             NULL,
    [ltf_out_of_area_name]                          NVARCHAR (255)  NULL,
    [ltf_party_dim_crm_ltf_party_key]               VARCHAR (32)    NULL,
    [ltf_qr_code_used]                              BIT             NULL,
    [ltf_referral_source]                           INT             NULL,
    [ltf_referral_source_name]                      NVARCHAR (255)  NULL,
    [ltf_referred_by_dim_crm_system_user_key]       VARCHAR (32)    NULL,
    [ltf_referred_by_name]                          NVARCHAR (160)  NULL,
    [ltf_request_id]                                NVARCHAR (100)  NULL,
    [ltf_same_day]                                  INT             NULL,
    [ltf_same_day_name]                             NVARCHAR (255)  NULL,
    [ltf_source]                                    NVARCHAR (100)  NULL,
    [ltf_telephone1]                                NVARCHAR (50)   NULL,
    [ltf_telephone2]                                NVARCHAR (50)   NULL,
    [modified_by_dim_crm_system_user_key]           VARCHAR (32)    NULL,
    [modified_dim_date_key]                         VARCHAR (8)     NULL,
    [modified_dim_time_key]                         INT             NULL,
    [modified_on]                                   DATETIME        NULL,
    [modified_on_behalf_by_dim_crm_system_user_key] VARCHAR (32)    NULL,
    [new_club_name_dim_crm_ltf_club_key]            VARCHAR (32)    NULL,
    [overridden_created_dim_date_key]               VARCHAR (8)     NULL,
    [overridden_created_dim_time_key]               INT             NULL,
    [overridden_created_on]                         DATETIME        NULL,
    [owner_id_name]                                 NVARCHAR (200)  NULL,
    [owner_id_type]                                 NVARCHAR (64)   NULL,
    [owning_business_unit]                          NVARCHAR (36)   NULL,
    [owning_team]                                   NVARCHAR (36)   NULL,
    [owning_user]                                   NVARCHAR (36)   NULL,
    [referring_dim_mms_member_key]                  VARCHAR (32)    NULL,
    [regarding_object_dim_crm_system_user_key]      VARCHAR (32)    NULL,
    [regarding_object_id]                           VARCHAR (36)    NULL,
    [regarding_object_id_name]                      NVARCHAR (4000) NULL,
    [regarding_object_type_code]                    NVARCHAR (64)   NULL,
    [state_code]                                    INT             NULL,
    [state_code_name]                               NVARCHAR (255)  NULL,
    [status_code]                                   INT             NULL,
    [status_code_name]                              NVARCHAR (255)  NULL,
    [subject]                                       NVARCHAR (500)  NULL,
    [update_user]                                   NVARCHAR (50)   NULL,
    [updated_date_time]                             DATETIME        NULL,
    [updated_dim_date_key]                          VARCHAR (8)     NULL,
    [updated_dim_time_key]                          INT             NULL,
    [p_crmcloudsync_ltf_guest_visit_id]             BIGINT          NOT NULL,
    [deleted_flag]                                  INT             NULL,
    [dv_load_date_time]                             DATETIME        NULL,
    [dv_load_end_date_time]                         DATETIME        NULL,
    [dv_batch_id]                                   BIGINT          NOT NULL,
    [dv_inserted_date_time]                         DATETIME        NOT NULL,
    [dv_insert_user]                                VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                          DATETIME        NULL,
    [dv_update_user]                                VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

