CREATE TABLE [dbo].[d_crmcloudsync_lead] (
    [d_crmcloudsync_lead_id]                                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                                 CHAR (32)       NOT NULL,
    [dim_crm_lead_key]                                        VARCHAR (32)    NULL,
    [lead_id]                                                 VARCHAR (36)    NULL,
    [address_1_address_type_code]                             INT             NULL,
    [address_1_address_type_code_name]                        NVARCHAR (255)  NULL,
    [address_1_city]                                          NVARCHAR (50)   NULL,
    [address_1_composite]                                     NVARCHAR (4000) NULL,
    [address_1_country]                                       NVARCHAR (80)   NULL,
    [address_1_latitude]                                      DECIMAL (26, 6) NULL,
    [address_1_line_1]                                        NVARCHAR (50)   NULL,
    [address_1_longitude]                                     DECIMAL (26, 6) NULL,
    [address_1_postal_code]                                   NVARCHAR (20)   NULL,
    [address_1_state_or_province]                             NVARCHAR (3)    NULL,
    [address_1_telephone_1]                                   NVARCHAR (50)   NULL,
    [address_1_telephone_2]                                   NVARCHAR (50)   NULL,
    [campaign_id_name]                                        NVARCHAR (128)  NULL,
    [created_by_dim_crm_system_user_key]                      VARCHAR (32)    NULL,
    [created_by_name]                                         NVARCHAR (200)  NULL,
    [created_dim_date_key]                                    VARCHAR (8)     NULL,
    [created_dim_time_key]                                    INT             NULL,
    [created_on]                                              DATETIME        NULL,
    [created_on_behalf_by_dim_crm_system_user_key]            VARCHAR (32)    NULL,
    [created_on_behalf_by_name]                               NVARCHAR (200)  NULL,
    [customer_id_name]                                        NVARCHAR (160)  NULL,
    [customer_id_type]                                        NVARCHAR (64)   NULL,
    [customer_id_yomi_name]                                   NVARCHAR (450)  NULL,
    [dim_club_key]                                            CHAR (32)       NULL,
    [dim_crm_address_1_address_key]                           VARCHAR (32)    NULL,
    [dim_crm_contact_key]                                     VARCHAR (32)    NULL,
    [dim_crm_customer_key]                                    VARCHAR (32)    NULL,
    [dim_crm_ltf_campaign_key]                                VARCHAR (32)    NULL,
    [dim_crm_ltf_club_key]                                    VARCHAR (32)    NULL,
    [dim_crm_ltf_employer_key]                                VARCHAR (32)    NULL,
    [dim_crm_ltf_primary_lead_key]                            VARCHAR (32)    NULL,
    [dim_crm_ltf_visitor_key]                                 VARCHAR (32)    NULL,
    [dim_crm_owner_key]                                       VARCHAR (32)    NULL,
    [dim_crm_parent_account_key]                              VARCHAR (32)    NULL,
    [dim_crm_parent_contact_key]                              VARCHAR (32)    NULL,
    [dim_mms_member_key]                                      CHAR (32)       NULL,
    [do_not_send_marketing_material_name]                     NVARCHAR (255)  NULL,
    [email_address_1]                                         NVARCHAR (100)  NULL,
    [email_address_2]                                         NVARCHAR (100)  NULL,
    [first_name]                                              NVARCHAR (50)   NULL,
    [full_name]                                               NVARCHAR (160)  NULL,
    [insert_user]                                             VARCHAR (100)   NULL,
    [inserted_date_time]                                      DATETIME        NULL,
    [inserted_dim_date_key]                                   VARCHAR (8)     NULL,
    [inserted_dim_time_key]                                   INT             NULL,
    [last_name]                                               NVARCHAR (50)   NULL,
    [ltf_actual_appointment_scheduled]                        DATETIME        NULL,
    [ltf_actual_appointment_scheduled_dim_date_key]           VARCHAR (8)     NULL,
    [ltf_actual_appointment_scheduled_dim_time_key]           INT             NULL,
    [ltf_actual_first_response]                               DATETIME        NULL,
    [ltf_actual_first_response_dim_date_key]                  VARCHAR (8)     NULL,
    [ltf_actual_first_response_dim_time_key]                  INT             NULL,
    [ltf_actual_initial_contact]                              DATETIME        NULL,
    [ltf_actual_initial_contact_dim_date_key]                 VARCHAR (8)     NULL,
    [ltf_actual_initial_contact_dim_time_key]                 INT             NULL,
    [ltf_appointment_showed]                                  BIT             NULL,
    [ltf_appointment_showed_flag]                             CHAR (1)        NULL,
    [ltf_appointment_showed_name]                             NVARCHAR (255)  NULL,
    [ltf_assigned_to_club_date]                               DATETIME        NULL,
    [ltf_assigned_to_club_date_dim_date_key]                  VARCHAR (8)     NULL,
    [ltf_assigned_to_club_date_dim_time_key]                  INT             NULL,
    [ltf_best_time_to_contact]                                INT             NULL,
    [ltf_best_time_to_contact_name]                           NVARCHAR (255)  NULL,
    [ltf_birth_date]                                          DATETIME        NULL,
    [ltf_birth_dim_date_key]                                  VARCHAR (8)     NULL,
    [ltf_birth_dim_time_key]                                  INT             NULL,
    [ltf_birth_year]                                          NVARCHAR (4)    NULL,
    [ltf_business_unit]                                       VARCHAR (36)    NULL,
    [ltf_business_unit_name]                                  NVARCHAR (160)  NULL,
    [ltf_channel]                                             INT             NULL,
    [ltf_channel_name]                                        NVARCHAR (255)  NULL,
    [ltf_club_id_name]                                        NVARCHAR (100)  NULL,
    [ltf_communication_consent]                               INT             NULL,
    [ltf_communication_consent_name]                          NVARCHAR (255)  NULL,
    [ltf_consent_date_time]                                   DATETIME        NULL,
    [ltf_consent_dim_date_key]                                VARCHAR (8)     NULL,
    [ltf_consent_dim_time_key]                                INT             NULL,
    [ltf_consent_ip_address]                                  NVARCHAR (19)   NULL,
    [ltf_consent_text]                                        NVARCHAR (300)  NULL,
    [ltf_current_member]                                      BIT             NULL,
    [ltf_current_member_flag]                                 CHAR (1)        NULL,
    [ltf_current_member_name]                                 NVARCHAR (255)  NULL,
    [ltf_device]                                              NVARCHAR (100)  NULL,
    [ltf_dnc_dne_update_triggered_by]                         INT             NULL,
    [ltf_dnc_dne_update_triggered_by_name]                    NVARCHAR (255)  NULL,
    [ltf_dnc_override]                                        BIT             NULL,
    [ltf_dnc_override_flag]                                   CHAR (1)        NULL,
    [ltf_dnc_override_name]                                   NVARCHAR (255)  NULL,
    [ltf_dnc_temporary_release_expiration]                    DATETIME        NULL,
    [ltf_dnc_temporary_release_expiration_dim_date_key]       VARCHAR (8)     NULL,
    [ltf_dnc_temporary_release_expiration_dim_time_key]       INT             NULL,
    [ltf_dnd_override_expiration]                             DATETIME        NULL,
    [ltf_dnd_override_expiration_dim_date_key]                VARCHAR (8)     NULL,
    [ltf_dnd_override_expiration_dim_time_key]                INT             NULL,
    [ltf_do_not_email_address_1]                              BIT             NULL,
    [ltf_do_not_email_address_1_flag]                         CHAR (1)        NULL,
    [ltf_do_not_email_address_1_name]                         NVARCHAR (255)  NULL,
    [ltf_do_not_email_address_2]                              BIT             NULL,
    [ltf_do_not_email_address_2_flag]                         CHAR (1)        NULL,
    [ltf_do_not_email_address_2_name]                         NVARCHAR (255)  NULL,
    [ltf_do_not_phone_mobile_phone]                           BIT             NULL,
    [ltf_do_not_phone_mobile_phone_flag]                      CHAR (1)        NULL,
    [ltf_do_not_phone_mobile_phone_name]                      NVARCHAR (255)  NULL,
    [ltf_do_not_phone_telephone_1]                            BIT             NULL,
    [ltf_do_not_phone_telephone_1_flag]                       CHAR (1)        NULL,
    [ltf_do_not_phone_telephone_1_name]                       NVARCHAR (255)  NULL,
    [ltf_do_not_phone_telephone_2]                            BIT             NULL,
    [ltf_do_not_phone_telephone_2_flag]                       CHAR (1)        NULL,
    [ltf_do_not_phone_telephone_2_name]                       NVARCHAR (255)  NULL,
    [ltf_duplicate_lead_count]                                NVARCHAR (10)   NULL,
    [ltf_duplicate_override]                                  BIT             NULL,
    [ltf_duplicate_override_flag]                             CHAR (1)        NULL,
    [ltf_duplicate_override_name]                             NVARCHAR (255)  NULL,
    [ltf_email_address_1_umsk]                                NVARCHAR (100)  NULL,
    [ltf_email_address_2_umsk]                                NVARCHAR (100)  NULL,
    [ltf_email_template]                                      NVARCHAR (110)  NULL,
    [ltf_employee_number]                                     NVARCHAR (100)  NULL,
    [ltf_employer]                                            NVARCHAR (50)   NULL,
    [ltf_employer_id_name]                                    NVARCHAR (160)  NULL,
    [ltf_employer_id_yomi_name]                               NVARCHAR (160)  NULL,
    [ltf_exact_target_email_sent]                             BIT             NULL,
    [ltf_exact_target_email_sent_flag]                        CHAR (1)        NULL,
    [ltf_exact_target_email_sent_name]                        NVARCHAR (255)  NULL,
    [ltf_exclude_from_follow_up]                              BIT             NULL,
    [ltf_exclude_from_follow_up_flag]                         CHAR (1)        NULL,
    [ltf_exclude_from_follow_up_name]                         NVARCHAR (255)  NULL,
    [ltf_first_response_by]                                   DATETIME        NULL,
    [ltf_first_response_dim_date_key]                         VARCHAR (8)     NULL,
    [ltf_first_response_dim_time_key]                         INT             NULL,
    [ltf_first_response_sent]                                 INT             NULL,
    [ltf_first_response_sent_name]                            NVARCHAR (255)  NULL,
    [ltf_first_response_status]                               INT             NULL,
    [ltf_first_response_status_name]                          NVARCHAR (255)  NULL,
    [ltf_gcl_id]                                              NVARCHAR (250)  NULL,
    [ltf_gender_code]                                         INT             NULL,
    [ltf_gender_code_name]                                    NVARCHAR (255)  NULL,
    [ltf_group]                                               INT             NULL,
    [ltf_group_name]                                          NVARCHAR (255)  NULL,
    [ltf_guest_to_lead_dim_crm_activity_key]                  VARCHAR (32)    NULL,
    [ltf_guest_to_lead_id_name]                               NVARCHAR (200)  NULL,
    [ltf_ims_join_link]                                       NVARCHAR (300)  NULL,
    [ltf_initial_contact_by]                                  DATETIME        NULL,
    [ltf_initial_contact_dim_date_key]                        VARCHAR (8)     NULL,
    [ltf_initial_contact_dim_time_key]                        INT             NULL,
    [ltf_initial_contact_made]                                INT             NULL,
    [ltf_initial_contact_made_name]                           NVARCHAR (255)  NULL,
    [ltf_initial_contact_status]                              INT             NULL,
    [ltf_initial_contact_status_name]                         NVARCHAR (255)  NULL,
    [ltf_initial_email_subject]                               NVARCHAR (250)  NULL,
    [ltf_inquiry_type]                                        NVARCHAR (100)  NULL,
    [ltf_inserted_by_system]                                  BIT             NULL,
    [ltf_inserted_by_system_flag]                             CHAR (1)        NULL,
    [ltf_inserted_by_system_name]                             NVARCHAR (255)  NULL,
    [ltf_is_ims_join]                                         BIT             NULL,
    [ltf_is_ims_join_flag]                                    CHAR (1)        NULL,
    [ltf_is_life_time_close_to]                               INT             NULL,
    [ltf_is_life_time_close_to_name]                          NVARCHAR (255)  NULL,
    [ltf_keywords]                                            NVARCHAR (100)  NULL,
    [ltf_landing_page]                                        NVARCHAR (100)  NULL,
    [ltf_last_activity]                                       NVARCHAR (100)  NULL,
    [ltf_last_activity_lead]                                  DATETIME        NULL,
    [ltf_last_activity_lead_dim_date_key]                     VARCHAR (8)     NULL,
    [ltf_last_activity_lead_dim_time_key]                     INT             NULL,
    [ltf_last_submission_date]                                DATETIME        NULL,
    [ltf_last_submission_dim_date_key]                        VARCHAR (8)     NULL,
    [ltf_last_submission_dim_time_key]                        INT             NULL,
    [ltf_lead_initial_load]                                   BIT             NULL,
    [ltf_lead_initial_load_flag]                              CHAR (1)        NULL,
    [ltf_lead_initial_load_name]                              NVARCHAR (255)  NULL,
    [ltf_lead_source]                                         INT             NULL,
    [ltf_lead_source_name]                                    NVARCHAR (255)  NULL,
    [ltf_lead_type]                                           INT             NULL,
    [ltf_lead_type_name]                                      NVARCHAR (255)  NULL,
    [ltf_legacy]                                              NVARCHAR (4000) NULL,
    [ltf_line_of_business]                                    INT             NULL,
    [ltf_line_of_business_name]                               NVARCHAR (255)  NULL,
    [ltf_managed_until]                                       DATETIME        NULL,
    [ltf_managed_until_dim_date_key]                          VARCHAR (8)     NULL,
    [ltf_managed_until_dim_time_key]                          INT             NULL,
    [ltf_membership_info_requested]                           NVARCHAR (50)   NULL,
    [ltf_membership_level]                                    INT             NULL,
    [ltf_membership_level_name]                               NVARCHAR (255)  NULL,
    [ltf_mobile_phone_umsk]                                   NVARCHAR (100)  NULL,
    [ltf_most_recent_casl]                                    DATETIME        NULL,
    [ltf_most_recent_casl_dim_date_key]                       VARCHAR (8)     NULL,
    [ltf_most_recent_casl_dim_time_key]                       INT             NULL,
    [ltf_nugget]                                              NVARCHAR (4000) NULL,
    [ltf_operating_system]                                    NVARCHAR (100)  NULL,
    [ltf_originating_chat]                                    VARCHAR (36)    NULL,
    [ltf_originating_chat_name]                               NVARCHAR (2000) NULL,
    [ltf_originating_guest_visit_dim_crm_ltf_guest_visit_key] VARCHAR (32)    NULL,
    [ltf_originating_guest_visit_name]                        NVARCHAR (200)  NULL,
    [ltf_park]                                                BIT             NULL,
    [ltf_park_comments]                                       NVARCHAR (400)  NULL,
    [ltf_park_flag]                                           CHAR (1)        NULL,
    [ltf_park_name]                                           NVARCHAR (255)  NULL,
    [ltf_park_reason]                                         INT             NULL,
    [ltf_park_reason_name]                                    NVARCHAR (255)  NULL,
    [ltf_park_until]                                          DATETIME        NULL,
    [ltf_park_until_dim_date_key]                             VARCHAR (8)     NULL,
    [ltf_park_until_dim_time_key]                             INT             NULL,
    [ltf_primary_goal]                                        NVARCHAR (100)  NULL,
    [ltf_primary_lead_name]                                   NVARCHAR (160)  NULL,
    [ltf_promocode]                                           NVARCHAR (100)  NULL,
    [ltf_reactivation_reason]                                 INT             NULL,
    [ltf_reactivation_reason_name]                            NVARCHAR (255)  NULL,
    [ltf_referring_contact_dim_crm_contact_key]               VARCHAR (32)    NULL,
    [ltf_referring_contact_id_name]                           NVARCHAR (160)  NULL,
    [ltf_referring_domain]                                    NVARCHAR (100)  NULL,
    [ltf_referring_member_dim_crm_member_key]                 VARCHAR (32)    NULL,
    [ltf_referring_page]                                      NVARCHAR (500)  NULL,
    [ltf_registration_code]                                   NVARCHAR (100)  NULL,
    [ltf_request_type]                                        NVARCHAR (100)  NULL,
    [ltf_schedule_appt_by]                                    DATETIME        NULL,
    [ltf_schedule_appt_dim_date_key]                          VARCHAR (8)     NULL,
    [ltf_schedule_appt_dim_time_key]                          INT             NULL,
    [ltf_schedule_appt_sent]                                  INT             NULL,
    [ltf_schedule_appt_sent_name]                             NVARCHAR (255)  NULL,
    [ltf_schedule_appt_status]                                INT             NULL,
    [ltf_schedule_appt_status_name]                           NVARCHAR (255)  NULL,
    [ltf_suffix]                                              NVARCHAR (3)    NULL,
    [ltf_transferred_to_club_on]                              DATETIME        NULL,
    [ltf_transferred_to_club_on_dim_date_key]                 VARCHAR (8)     NULL,
    [ltf_transferred_to_club_on_dim_time_key]                 INT             NULL,
    [ltf_udw_id]                                              BIGINT          NULL,
    [ltf_under_eighteen]                                      BIT             NULL,
    [ltf_under_eighteen_flag]                                 CHAR (1)        NULL,
    [ltf_under_eighteen_name]                                 NVARCHAR (255)  NULL,
    [ltf_update_contact]                                      BIT             NULL,
    [ltf_update_contact_flag]                                 CHAR (1)        NULL,
    [ltf_update_contact_name]                                 NVARCHAR (255)  NULL,
    [ltf_utm_audience]                                        NVARCHAR (100)  NULL,
    [ltf_utm_campaign]                                        NVARCHAR (100)  NULL,
    [ltf_utm_content]                                         NVARCHAR (100)  NULL,
    [ltf_utm_image]                                           NVARCHAR (100)  NULL,
    [ltf_utm_medium]                                          NVARCHAR (100)  NULL,
    [ltf_utm_source]                                          NVARCHAR (100)  NULL,
    [ltf_utm_term]                                            NVARCHAR (100)  NULL,
    [ltf_visit_count]                                         INT             NULL,
    [ltf_volatile_contact]                                    BIT             NULL,
    [ltf_volatile_contact_flag]                               CHAR (1)        NULL,
    [ltf_volatile_contact_name]                               NVARCHAR (255)  NULL,
    [ltf_web_team_email]                                      NVARCHAR (100)  NULL,
    [ltf_web_team_id]                                         VARCHAR (36)    NULL,
    [ltf_web_team_id_name]                                    NVARCHAR (160)  NULL,
    [ltf_web_team_phone]                                      NVARCHAR (100)  NULL,
    [ltf_web_transfer_method]                                 INT             NULL,
    [ltf_web_transfer_method_name]                            NVARCHAR (255)  NULL,
    [merged]                                                  BIT             NULL,
    [merged_flag]                                             CHAR (1)        NULL,
    [middle_name]                                             NVARCHAR (50)   NULL,
    [mobile_phone]                                            NVARCHAR (20)   NULL,
    [modified_by_dim_crm_system_user_key]                     VARCHAR (32)    NULL,
    [modified_dim_date_key]                                   VARCHAR (8)     NULL,
    [modified_dim_time_key]                                   INT             NULL,
    [modified_on]                                             DATETIME        NULL,
    [modified_on_behalf_by_dim_crm_system_user_key]           VARCHAR (32)    NULL,
    [overridden_created_dim_date_key]                         VARCHAR (8)     NULL,
    [overridden_created_dim_time_key]                         INT             NULL,
    [overridden_created_on]                                   DATETIME        NULL,
    [owner_id]                                                VARCHAR (36)    NULL,
    [owner_id_name]                                           NVARCHAR (200)  NULL,
    [owner_id_type]                                           NVARCHAR (64)   NULL,
    [owning_business_unit]                                    VARCHAR (36)    NULL,
    [owning_team]                                             VARCHAR (36)    NULL,
    [owning_user_dim_crm_system_user_key]                     VARCHAR (32)    NULL,
    [parent_account_id_name]                                  NVARCHAR (160)  NULL,
    [parent_contact_id]                                       VARCHAR (36)    NULL,
    [preferred_contact_method_code]                           INT             NULL,
    [preferred_contact_method_code_name]                      NVARCHAR (255)  NULL,
    [qualifying_opportunity_dim_crm_opportunity_key]          VARCHAR (32)    NULL,
    [qualifying_opportunity_id_name]                          NVARCHAR (300)  NULL,
    [salutation]                                              NVARCHAR (4)    NULL,
    [state_code]                                              INT             NULL,
    [state_code_name]                                         NVARCHAR (255)  NULL,
    [status_code]                                             INT             NULL,
    [status_code_name]                                        NVARCHAR (255)  NULL,
    [telephone_1]                                             NVARCHAR (50)   NULL,
    [telephone_2]                                             NVARCHAR (50)   NULL,
    [update_user]                                             VARCHAR (50)    NULL,
    [updated_date_time]                                       DATETIME        NULL,
    [updated_dim_date_key]                                    VARCHAR (8)     NULL,
    [updated_dim_time_key]                                    INT             NULL,
    [utc_conversion_time_zone_code]                           INT             NULL,
    [p_crmcloudsync_lead_id]                                  BIGINT          NOT NULL,
    [deleted_flag]                                            INT             NULL,
    [dv_load_date_time]                                       DATETIME        NULL,
    [dv_load_end_date_time]                                   DATETIME        NULL,
    [dv_batch_id]                                             BIGINT          NOT NULL,
    [dv_inserted_date_time]                                   DATETIME        NOT NULL,
    [dv_insert_user]                                          VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                    DATETIME        NULL,
    [dv_update_user]                                          VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

