CREATE TABLE [dbo].[d_crmcloudsync_annotation] (
    [d_crmcloudsync_annotation_id]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)      NOT NULL,
    [dim_crm_annotation_key]              VARCHAR (32)   NULL,
    [annotation_id]                       VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]  VARCHAR (32)   NULL,
    [created_by_name]                     NVARCHAR (200) NULL,
    [created_dim_date_key]                VARCHAR (8)    NULL,
    [created_dim_time_key]                INT            NULL,
    [created_on]                          DATETIME       NULL,
    [dim_crm_owner_key]                   VARCHAR (32)   NULL,
    [file_name]                           NVARCHAR (255) NULL,
    [file_size]                           INT            NULL,
    [is_document]                         INT            NULL,
    [is_document_name]                    NVARCHAR (255) NULL,
    [mime_type]                           NVARCHAR (256) NULL,
    [modified_by_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [modified_by_name]                    NVARCHAR (200) NULL,
    [modified_dim_date_key]               VARCHAR (8)    NULL,
    [modified_dim_time_key]               INT            NULL,
    [modified_on]                         DATETIME       NULL,
    [note_text]                           VARCHAR (8000) NULL,
    [object_id]                           VARCHAR (36)   NULL,
    [object_id_type_code]                 NVARCHAR (64)  NULL,
    [owner_id_name]                       NVARCHAR (200) NULL,
    [owner_id_type]                       NVARCHAR (64)  NULL,
    [owning_business_unit]                VARCHAR (36)   NULL,
    [owning_team]                         VARCHAR (36)   NULL,
    [owning_user_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [subject]                             NVARCHAR (500) NULL,
    [p_crmcloudsync_annotation_id]        BIGINT         NOT NULL,
    [deleted_flag]                        INT            NULL,
    [dv_load_date_time]                   DATETIME       NULL,
    [dv_load_end_date_time]               DATETIME       NULL,
    [dv_batch_id]                         BIGINT         NOT NULL,
    [dv_inserted_date_time]               DATETIME       NOT NULL,
    [dv_insert_user]                      VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                DATETIME       NULL,
    [dv_update_user]                      VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

