CREATE TABLE [dbo].[d_crmcloudsync_ltf_program_cycle] (
    [d_crmcloudsync_ltf_program_cycle_id]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                       CHAR (32)      NOT NULL,
    [dim_crm_ltf_program_cycle_key]                 VARCHAR (32)   NULL,
    [ltf_program_cycle_id]                          VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]            VARCHAR (32)   NULL,
    [created_by_name]                               NVARCHAR (200) NULL,
    [created_dim_date_key]                          VARCHAR (8)    NULL,
    [created_dim_time_key]                          INT            NULL,
    [created_on]                                    DATETIME       NULL,
    [created_on_behalf_by_dim_crm_system_user_key]  VARCHAR (32)   NULL,
    [created_on_behalf_by_name]                     NVARCHAR (200) NULL,
    [cycle_begin_dim_date_key]                      VARCHAR (8)    NULL,
    [cycle_begin_dim_time_key]                      INT            NULL,
    [cycle_end_dim_date_key]                        VARCHAR (8)    NULL,
    [cycle_end_dim_time_key]                        INT            NULL,
    [dim_crm_owner_key]                             VARCHAR (32)   NULL,
    [dim_crm_team_key]                              VARCHAR (32)   NULL,
    [insert_user]                                   VARCHAR (50)   NULL,
    [inserted_date_time]                            DATETIME       NULL,
    [inserted_dim_date_key]                         VARCHAR (8)    NULL,
    [inserted_dim_time_key]                         INT            NULL,
    [ltf_cancel_reason]                             NVARCHAR (250) NULL,
    [ltf_cycle_begin_date]                          DATETIME       NULL,
    [ltf_cycle_end_date]                            DATETIME       NULL,
    [ltf_cycle_name]                                NVARCHAR (50)  NULL,
    [ltf_program]                                   INT            NULL,
    [ltf_program_name]                              NVARCHAR (255) NULL,
    [modified_by_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [modified_by_name]                              NVARCHAR (200) NULL,
    [modified_dim_date_key]                         VARCHAR (8)    NULL,
    [modified_dim_time_key]                         INT            NULL,
    [modified_on]                                   DATETIME       NULL,
    [modified_on_behalf_by_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [modified_on_behalf_by_name]                    NVARCHAR (200) NULL,
    [owner_id_name]                                 NVARCHAR (200) NULL,
    [owner_id_type]                                 NVARCHAR (64)  NULL,
    [owning_business_unit]                          VARCHAR (36)   NULL,
    [owning_user_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [state_code]                                    INT            NULL,
    [state_code_name]                               NVARCHAR (255) NULL,
    [status_code]                                   INT            NULL,
    [status_code_name]                              NVARCHAR (255) NULL,
    [time_zone_rule_version_number]                 INT            NULL,
    [update_user]                                   VARCHAR (50)   NULL,
    [updated_date_time]                             DATETIME       NULL,
    [updated_dim_date_key]                          VARCHAR (8)    NULL,
    [updated_dim_time_key]                          INT            NULL,
    [utc_conversion_time_zone_code]                 INT            NULL,
    [p_crmcloudsync_ltf_program_cycle_id]           BIGINT         NOT NULL,
    [deleted_flag]                                  INT            NULL,
    [dv_load_date_time]                             DATETIME       NULL,
    [dv_load_end_date_time]                         DATETIME       NULL,
    [dv_batch_id]                                   BIGINT         NOT NULL,
    [dv_inserted_date_time]                         DATETIME       NOT NULL,
    [dv_insert_user]                                VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                          DATETIME       NULL,
    [dv_update_user]                                VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

