CREATE TABLE [dbo].[d_crmcloudsync_ltf_club] (
    [d_crmcloudsync_ltf_club_id]                      BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                         CHAR (32)     NOT NULL,
    [dim_crm_ltf_club_key]                            VARCHAR (32)  NULL,
    [ltf_club_id]                                     VARCHAR (36)  NULL,
    [address_line_1]                                  VARCHAR (50)  NULL,
    [area_director_dim_crm_system_user_key]           VARCHAR (32)  NULL,
    [city]                                            VARCHAR (50)  NULL,
    [club_id]                                         INT           NULL,
    [club_regional_manager_dim_crm_system_user_key]   VARCHAR (32)  NULL,
    [country]                                         VARCHAR (50)  NULL,
    [dim_club_key]                                    CHAR (32)     NULL,
    [dim_crm_team_key]                                VARCHAR (32)  NULL,
    [five_letter_club_code]                           VARCHAR (5)   NULL,
    [four_letter_club_code]                           VARCHAR (4)   NULL,
    [general_manager_dim_crm_system_user_key]         VARCHAR (32)  NULL,
    [ltf_lt_work_email]                               INT           NULL,
    [ltf_web_specialist_team]                         VARCHAR (36)  NULL,
    [marketing_name]                                  VARCHAR (100) NULL,
    [postal_code]                                     VARCHAR (50)  NULL,
    [regional_sales_lead_dim_crm_system_user_key]     VARCHAR (32)  NULL,
    [regional_vice_president_dim_crm_system_user_key] VARCHAR (32)  NULL,
    [state_or_province]                               VARCHAR (50)  NULL,
    [status_code]                                     INT           NULL,
    [telephone]                                       VARCHAR (50)  NULL,
    [web_specialist_dim_crm_team_key]                 VARCHAR (32)  NULL,
    [p_crmcloudsync_ltf_club_id]                      BIGINT        NOT NULL,
    [deleted_flag]                                    INT           NULL,
    [dv_load_date_time]                               DATETIME      NULL,
    [dv_load_end_date_time]                           DATETIME      NULL,
    [dv_batch_id]                                     BIGINT        NOT NULL,
    [dv_inserted_date_time]                           DATETIME      NOT NULL,
    [dv_insert_user]                                  VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                            DATETIME      NULL,
    [dv_update_user]                                  VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);

