CREATE TABLE [dbo].[d_crmcloudsync_ltf_related_interest] (
    [d_crmcloudsync_ltf_related_interest_id]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                       CHAR (32)      NOT NULL,
    [dim_crm_related_interest_key]                  VARCHAR (32)   NULL,
    [ltf_related_interest_id]                       VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]            VARCHAR (32)   NULL,
    [created_by_name]                               NVARCHAR (200) NULL,
    [created_dim_date_key]                          VARCHAR (8)    NULL,
    [created_dim_time_key]                          INT            NULL,
    [created_on]                                    DATETIME       NULL,
    [dim_crm_contact_key]                           VARCHAR (32)   NULL,
    [dim_crm_interest_key]                          VARCHAR (32)   NULL,
    [dim_crm_lead_key]                              VARCHAR (32)   NULL,
    [dim_crm_opportunity_key]                       VARCHAR (32)   NULL,
    [dim_crm_owner_key]                             VARCHAR (32)   NULL,
    [insert_user]                                   VARCHAR (100)  NULL,
    [inserted_date_time]                            DATETIME       NULL,
    [inserted_dim_date_key]                         VARCHAR (8)    NULL,
    [inserted_dim_time_key]                         INT            NULL,
    [ltf_add_by]                                    VARCHAR (36)   NULL,
    [ltf_add_date]                                  DATETIME       NULL,
    [ltf_add_dim_date_key]                          VARCHAR (8)    NULL,
    [ltf_add_dim_time_key]                          INT            NULL,
    [ltf_add_source]                                INT            NULL,
    [ltf_contact_id_name]                           NVARCHAR (160) NULL,
    [ltf_interest_id]                               VARCHAR (36)   NULL,
    [ltf_interest_id_name]                          NVARCHAR (100) NULL,
    [ltf_lead_id_name]                              NVARCHAR (160) NULL,
    [ltf_name]                                      NVARCHAR (100) NULL,
    [ltf_opportunity_id_name]                       NVARCHAR (300) NULL,
    [ltf_remove_by]                                 VARCHAR (36)   NULL,
    [ltf_remove_date]                               DATETIME       NULL,
    [ltf_remove_dim_date_key]                       VARCHAR (8)    NULL,
    [ltf_remove_dim_time_key]                       INT            NULL,
    [ltf_remove_source]                             INT            NULL,
    [modified_by_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [modified_by_name]                              NVARCHAR (200) NULL,
    [modified_dim_date_key]                         VARCHAR (8)    NULL,
    [modified_dim_time_key]                         INT            NULL,
    [modified_on]                                   DATETIME       NULL,
    [modified_on_behalf_by_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [modified_on_behalf_by_name]                    NVARCHAR (200) NULL,
    [owner_id_name]                                 NVARCHAR (200) NULL,
    [owner_id_type]                                 NVARCHAR (64)  NULL,
    [owning_business_unit]                          VARCHAR (36)   NULL,
    [owning_team]                                   VARCHAR (36)   NULL,
    [owning_user_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [primary_interest_flag]                         CHAR (1)       NULL,
    [state_code]                                    INT            NULL,
    [state_code_name]                               NVARCHAR (255) NULL,
    [status_code]                                   INT            NULL,
    [status_code_name]                              NVARCHAR (255) NULL,
    [update_user]                                   VARCHAR (50)   NULL,
    [updated_date_time]                             DATETIME       NULL,
    [updated_dim_date_key]                          VARCHAR (8)    NULL,
    [updated_dim_time_key]                          INT            NULL,
    [p_crmcloudsync_ltf_related_interest_id]        BIGINT         NOT NULL,
    [deleted_flag]                                  INT            NULL,
    [dv_load_date_time]                             DATETIME       NULL,
    [dv_load_end_date_time]                         DATETIME       NULL,
    [dv_batch_id]                                   BIGINT         NOT NULL,
    [dv_inserted_date_time]                         DATETIME       NOT NULL,
    [dv_insert_user]                                VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                          DATETIME       NULL,
    [dv_update_user]                                VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

