CREATE TABLE [dbo].[d_crmcloudsync_ltf_subscriber] (
    [d_crmcloudsync_ltf_subscriber_id]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                       CHAR (32)      NOT NULL,
    [dim_crm_ltf_subscriber_key]                    VARCHAR (32)   NULL,
    [ltf_subscriber_id]                             VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]            VARCHAR (32)   NULL,
    [created_by_name]                               NVARCHAR (200) NULL,
    [created_dim_date_key]                          VARCHAR (8)    NULL,
    [created_dim_time_key]                          INT            NULL,
    [created_on]                                    DATETIME       NULL,
    [dim_crm_ltf_subscription_key]                  VARCHAR (32)   NULL,
    [dim_crm_owner_key]                             VARCHAR (32)   NULL,
    [dim_mms_member_key]                            VARCHAR (32)   NULL,
    [ltf_connection_pref_source]                    INT            NULL,
    [ltf_connection_preference]                     INT            NULL,
    [ltf_contact_dim_crm_contact_key]               VARCHAR (32)   NULL,
    [ltf_contact_id_name]                           NVARCHAR (160) NULL,
    [ltf_join_date]                                 DATETIME       NULL,
    [ltf_join_dim_date_key]                         VARCHAR (8)    NULL,
    [ltf_join_dim_time_key]                         INT            NULL,
    [ltf_name]                                      NVARCHAR (100) NULL,
    [ltf_role]                                      INT            NULL,
    [ltf_role_name]                                 NVARCHAR (255) NULL,
    [ltf_subscription_id_name]                      NVARCHAR (100) NULL,
    [modified_by_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [modified_by_name]                              NVARCHAR (200) NULL,
    [modified_dim_date_key]                         VARCHAR (8)    NULL,
    [modified_dim_time_key]                         INT            NULL,
    [modified_on]                                   DATETIME       NULL,
    [modified_on_behalf_by_dim_crm_system_user_key] VARCHAR (32)   NULL,
    [modified_on_behalf_by_name]                    NVARCHAR (200) NULL,
    [overridden_created_dim_date_key]               VARCHAR (8)    NULL,
    [overridden_created_dim_time_key]               INT            NULL,
    [overridden_created_on]                         DATETIME       NULL,
    [owner_id_name]                                 NVARCHAR (200) NULL,
    [owner_id_type]                                 NVARCHAR (64)  NULL,
    [owning_business_unit]                          VARCHAR (36)   NULL,
    [owning_team]                                   VARCHAR (36)   NULL,
    [owning_user_dim_crm_system_user_key]           VARCHAR (32)   NULL,
    [state_code]                                    INT            NULL,
    [state_code_name]                               NVARCHAR (255) NULL,
    [status_code]                                   INT            NULL,
    [status_code_name]                              NVARCHAR (255) NULL,
    [time_zone_rule_version_number]                 INT            NULL,
    [version_number]                                BIGINT         NULL,
    [p_crmcloudsync_ltf_subscriber_id]              BIGINT         NOT NULL,
    [deleted_flag]                                  INT            NULL,
    [dv_load_date_time]                             DATETIME       NULL,
    [dv_load_end_date_time]                         DATETIME       NULL,
    [dv_batch_id]                                   BIGINT         NOT NULL,
    [dv_inserted_date_time]                         DATETIME       NOT NULL,
    [dv_insert_user]                                VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                          DATETIME       NULL,
    [dv_update_user]                                VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

