CREATE TABLE [dbo].[d_crmcloudsync_invoice] (
    [d_crmcloudsync_invoice_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [fact_crm_invoice_key]                 VARCHAR (32)    NULL,
    [invoice_id]                           VARCHAR (36)    NULL,
    [account_id_name]                      NVARCHAR (160)  NULL,
    [contact_id_name]                      NVARCHAR (160)  NULL,
    [created_by_dim_crm_system_user_key]   VARCHAR (32)    NULL,
    [created_by_name]                      NVARCHAR (200)  NULL,
    [created_dim_date_key]                 VARCHAR (8)     NULL,
    [created_dim_time_key]                 INT             NULL,
    [created_on]                           DATETIME        NULL,
    [customer_id_name]                     NVARCHAR (160)  NULL,
    [customer_id_type]                     NVARCHAR (64)   NULL,
    [description]                          VARCHAR (8000)  NULL,
    [dim_crm_account_key]                  VARCHAR (32)    NULL,
    [dim_crm_contact_key]                  VARCHAR (32)    NULL,
    [dim_crm_customer_key]                 VARCHAR (32)    NULL,
    [dim_crm_opportunity_key]              VARCHAR (32)    NULL,
    [dim_crm_owner_key]                    VARCHAR (32)    NULL,
    [dim_crm_transaction_currency_key]     VARCHAR (32)    NULL,
    [dim_mms_membership_key]               CHAR (32)       NULL,
    [insert_user]                          VARCHAR (100)   NULL,
    [inserted_date_time]                   DATETIME        NULL,
    [inserted_dim_date_key]                VARCHAR (8)     NULL,
    [inserted_dim_time_key]                INT             NULL,
    [invoice_number]                       NVARCHAR (100)  NULL,
    [ltf_club_id_name]                     NVARCHAR (100)  NULL,
    [ltf_membership_id]                    NVARCHAR (25)   NULL,
    [ltf_membership_source]                INT             NULL,
    [ltf_membership_source_name]           NVARCHAR (255)  NULL,
    [modified_by_dim_crm_system_user_key]  VARCHAR (32)    NULL,
    [modified_by_name]                     NVARCHAR (200)  NULL,
    [modified_dim_date_key]                VARCHAR (8)     NULL,
    [modified_dim_time_key]                INT             NULL,
    [modified_on]                          DATETIME        NULL,
    [name]                                 NVARCHAR (300)  NULL,
    [opportunity_id_name]                  NVARCHAR (300)  NULL,
    [owner_id_name]                        NVARCHAR (200)  NULL,
    [owner_id_type]                        NVARCHAR (64)   NULL,
    [owning_business_unit]                 VARCHAR (36)    NULL,
    [owning_team]                          VARCHAR (36)    NULL,
    [owning_user_dim_crm_system_user_key]  VARCHAR (32)    NULL,
    [state_code]                           INT             NULL,
    [state_code_name]                      NVARCHAR (255)  NULL,
    [status_code]                          INT             NULL,
    [status_code_name]                     NVARCHAR (255)  NULL,
    [time_zone_rule_version_number]        INT             NULL,
    [total_amount]                         DECIMAL (26, 3) NULL,
    [total_amount_base]                    DECIMAL (26, 3) NULL,
    [total_discount_amount]                DECIMAL (26, 3) NULL,
    [total_discount_amount_base]           DECIMAL (26, 3) NULL,
    [total_line_item_amount]               DECIMAL (26, 3) NULL,
    [total_line_item_amount_base]          DECIMAL (26, 3) NULL,
    [total_line_item_discount_amount]      DECIMAL (26, 3) NULL,
    [total_line_item_discount_amount_base] DECIMAL (26, 3) NULL,
    [total_tax]                            DECIMAL (26, 3) NULL,
    [total_tax_base]                       DECIMAL (26, 3) NULL,
    [transaction_currency_id_name]         NVARCHAR (100)  NULL,
    [update_user]                          VARCHAR (50)    NULL,
    [updated_date_time]                    DATETIME        NULL,
    [updated_dim_date_key]                 VARCHAR (8)     NULL,
    [updated_dim_time_key]                 INT             NULL,
    [p_crmcloudsync_invoice_id]            BIGINT          NOT NULL,
    [deleted_flag]                         INT             NULL,
    [dv_load_date_time]                    DATETIME        NULL,
    [dv_load_end_date_time]                DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

