CREATE TABLE [dbo].[d_crmcloudsync_ltf_connect_member] (
    [d_crmcloudsync_ltf_connect_member_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)      NOT NULL,
    [dim_crm_ltf_connect_member_key]       VARCHAR (32)   NULL,
    [ltf_connect_member_id]                VARCHAR (36)   NULL,
    [created_by_dim_crm_system_user_key]   VARCHAR (32)   NULL,
    [created_by_name]                      NVARCHAR (200) NULL,
    [created_dim_date_key]                 VARCHAR (8)    NULL,
    [created_dim_time_key]                 INT            NULL,
    [created_on]                           DATETIME       NULL,
    [dim_crm_ltf_subscriber_key]           VARCHAR (32)   NULL,
    [dim_crm_opportunity_key]              VARCHAR (32)   NULL,
    [inserted_date_time]                   DATETIME       NULL,
    [inserted_dim_date_key]                VARCHAR (8)    NULL,
    [inserted_dim_time_key]                INT            NULL,
    [ltf_move_it_scheduled_date]           DATETIME       NULL,
    [ltf_move_it_scheduled_dim_date_key]   VARCHAR (8)    NULL,
    [ltf_move_it_scheduled_dim_time_key]   INT            NULL,
    [ltf_move_it_scheduled_with]           NVARCHAR (100) NULL,
    [ltf_profile_notes]                    VARCHAR (8000) NULL,
    [ltf_programs_of_interest]             INT            NULL,
    [ltf_programs_of_interest_name]        NVARCHAR (255) NULL,
    [ltf_subscriber_id_name]               NVARCHAR (100) NULL,
    [ltf_want_to_do]                       INT            NULL,
    [ltf_want_to_do_name]                  NVARCHAR (255) NULL,
    [ltf_who_met_with]                     NVARCHAR (100) NULL,
    [ltf_why_want_to_do]                   INT            NULL,
    [ltf_why_want_to_do_name]              NVARCHAR (255) NULL,
    [modified_dim_date_key]                VARCHAR (8)    NULL,
    [modified_dim_time_key]                INT            NULL,
    [modified_on]                          DATETIME       NULL,
    [state_code]                           INT            NULL,
    [status_code]                          INT            NULL,
    [updated_date_time]                    DATETIME       NULL,
    [updated_dim_date_key]                 VARCHAR (8)    NULL,
    [updated_dim_time_key]                 INT            NULL,
    [p_crmcloudsync_ltf_connect_member_id] BIGINT         NOT NULL,
    [deleted_flag]                         INT            NULL,
    [dv_load_date_time]                    DATETIME       NULL,
    [dv_load_end_date_time]                DATETIME       NULL,
    [dv_batch_id]                          BIGINT         NOT NULL,
    [dv_inserted_date_time]                DATETIME       NOT NULL,
    [dv_insert_user]                       VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                 DATETIME       NULL,
    [dv_update_user]                       VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

