CREATE TABLE [dbo].[d_ec_notifications] (
    [d_ec_notifications_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)       NOT NULL,
    [fact_trainerize_notification_key] VARCHAR (32)    NULL,
    [notification_id]                  INT             NULL,
    [created_dim_date_key]             VARCHAR (8)     NULL,
    [created_dim_time_key]             INT             NULL,
    [message]                          NVARCHAR (4000) NULL,
    [message_type_flag]                CHAR (1)        NULL,
    [notifications_from]               INT             NULL,
    [notifications_to]                 INT             NULL,
    [received_dim_date_key]            VARCHAR (8)     NULL,
    [received_dim_time_key]            INT             NULL,
    [source_id]                        NVARCHAR (50)   NULL,
    [source_thread_id]                 NVARCHAR (50)   NULL,
    [source_type]                      INT             NULL,
    [status_flag]                      CHAR (1)        NULL,
    [subject]                          NVARCHAR (4000) NULL,
    [updated_dim_date_key]             VARCHAR (8)     NULL,
    [updated_dim_time_key]             INT             NULL,
    [p_ec_notifications_id]            BIGINT          NOT NULL,
    [deleted_flag]                     INT             NULL,
    [dv_load_date_time]                DATETIME        NULL,
    [dv_load_end_date_time]            DATETIME        NULL,
    [dv_batch_id]                      BIGINT          NOT NULL,
    [dv_inserted_date_time]            DATETIME        NOT NULL,
    [dv_insert_user]                   VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]             DATETIME        NULL,
    [dv_update_user]                   VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

