CREATE TABLE [dbo].[d_ec_measurement_recordings] (
    [d_ec_measurement_recordings_id]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)       NOT NULL,
    [measurement_recording_id]          VARCHAR (36)    NULL,
    [active_flag]                       CHAR (1)        NULL,
    [certified_flag]                    CHAR (1)        NULL,
    [created_by]                        INT             NULL,
    [created_dim_date_key]              VARCHAR (8)     NULL,
    [d_ltfeb_ltf_user_identity_bk_hash] CHAR (32)       NULL,
    [dim_club_key]                      CHAR (32)       NULL,
    [measurement_dim_date_key]          VARCHAR (8)     NULL,
    [measurement_dim_time_key]          INT             NULL,
    [metadata]                          NVARCHAR (4000) NULL,
    [modified_by]                       INT             NULL,
    [modified_dim_date_key]             VARCHAR (8)     NULL,
    [notes]                             NVARCHAR (500)  NULL,
    [party_id]                          VARCHAR (36)    NULL,
    [source]                            NVARCHAR (100)  NULL,
    [user_program_status_id]            VARCHAR (36)    NULL,
    [p_ec_measurement_recordings_id]    BIGINT          NOT NULL,
    [deleted_flag]                      INT             NULL,
    [dv_load_date_time]                 DATETIME        NULL,
    [dv_load_end_date_time]             DATETIME        NULL,
    [dv_batch_id]                       BIGINT          NOT NULL,
    [dv_inserted_date_time]             DATETIME        NOT NULL,
    [dv_insert_user]                    VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]              DATETIME        NULL,
    [dv_update_user]                    VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

