CREATE TABLE [dbo].[d_ec_free_programs] (
    [d_ec_free_programs_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                   CHAR (32)       NOT NULL,
    [dim_ec_free_programs_keys] VARCHAR (32)    NULL,
    [free_program_id]           INT             NULL,
    [active_flag]               CHAR (1)        NULL,
    [created_date]              DATETIME        NULL,
    [created_dim_date_key]      VARCHAR (8)     NULL,
    [created_dim_time_key]      INT             NULL,
    [d_ec_programs_bk_hash]     VARCHAR (32)    NULL,
    [duration]                  NVARCHAR (50)   NULL,
    [end_date]                  DATETIME        NULL,
    [end_dim_date_key]          VARCHAR (8)     NULL,
    [end_dim_time_key]          INT             NULL,
    [equipment]                 NVARCHAR (1000) NULL,
    [exercise]                  NVARCHAR (1000) NULL,
    [featured_flag]             CHAR (1)        NULL,
    [frequency]                 NVARCHAR (50)   NULL,
    [goal]                      NVARCHAR (50)   NULL,
    [level]                     NVARCHAR (50)   NULL,
    [priority]                  INT             NULL,
    [program_description]       NVARCHAR (4000) NULL,
    [program_id]                INT             NULL,
    [program_image]             NVARCHAR (2000) NULL,
    [program_name]              NVARCHAR (50)   NULL,
    [updated_date]              DATETIME        NULL,
    [updated_dim_date_key]      VARCHAR (8)     NULL,
    [updated_dim_time_key]      INT             NULL,
    [p_ec_free_programs_id]     BIGINT          NOT NULL,
    [deleted_flag]              INT             NULL,
    [dv_load_date_time]         DATETIME        NULL,
    [dv_load_end_date_time]     DATETIME        NULL,
    [dv_batch_id]               BIGINT          NOT NULL,
    [dv_inserted_date_time]     DATETIME        NOT NULL,
    [dv_insert_user]            VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]      DATETIME        NULL,
    [dv_update_user]            VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

