CREATE TABLE [dbo].[d_exerp_document] (
    [d_exerp_document_id]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)      NOT NULL,
    [document_id]                      INT            NULL,
    [center_id]                        INT            NULL,
    [company_id]                       VARCHAR (4000) NULL,
    [creation_dim_date_key]            CHAR (8)       NULL,
    [creation_dim_time_key]            CHAR (8)       NULL,
    [creator_person_id]                VARCHAR (4000) NULL,
    [d_exerp_center_bk_hash]           CHAR (32)      NULL,
    [d_exerp_person_bk_hash]           CHAR (32)      NULL,
    [d_mms_company_bk_hash]            CHAR (32)      NULL,
    [dim_mms_member_key]               VARCHAR (32)   NULL,
    [document_attached_file_name]      VARCHAR (4000) NULL,
    [document_details]                 VARCHAR (4000) NULL,
    [document_require_signature_flag]  CHAR (1)       NULL,
    [document_signatures_missing_flag] CHAR (1)       NULL,
    [document_signatures_signed_flag]  CHAR (1)       NULL,
    [document_subject]                 VARCHAR (4000) NULL,
    [document_type]                    VARCHAR (4000) NULL,
    [ets]                              BIGINT         NULL,
    [latest_signed_dim_date_key]       CHAR (8)       NULL,
    [latest_signed_dim_time_key]       CHAR (8)       NULL,
    [person_id]                        VARCHAR (4000) NULL,
    [p_exerp_document_id]              BIGINT         NOT NULL,
    [deleted_flag]                     INT            NULL,
    [dv_load_date_time]                DATETIME       NULL,
    [dv_load_end_date_time]            DATETIME       NULL,
    [dv_batch_id]                      BIGINT         NOT NULL,
    [dv_inserted_date_time]            DATETIME       NOT NULL,
    [dv_insert_user]                   VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]             DATETIME       NULL,
    [dv_update_user]                   VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

