CREATE TABLE [dbo].[d_exerp_freeze_period] (
    [d_exerp_freeze_period_id]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)      NOT NULL,
    [freeze_period_id]                    INT            NULL,
    [cancel_dim_date_key]                 VARCHAR (8)    NULL,
    [cancel_dim_time_key]                 INT            NULL,
    [center_id]                           INT            NULL,
    [d_exerp_subscription_center_bk_hash] VARCHAR (32)   NULL,
    [dim_club_key]                        VARCHAR (32)   NULL,
    [dim_exerp_subscription_key]          VARCHAR (32)   NULL,
    [end_dim_date_key]                    VARCHAR (8)    NULL,
    [end_dim_time_key]                    INT            NULL,
    [entry_dim_date_key]                  VARCHAR (8)    NULL,
    [entry_dim_time_key]                  INT            NULL,
    [ets]                                 BIGINT         NULL,
    [freeze_period_reason]                VARCHAR (4000) NULL,
    [freeze_period_state]                 VARCHAR (4000) NULL,
    [freeze_period_type]                  VARCHAR (4000) NULL,
    [start_dim_date_key]                  VARCHAR (8)    NULL,
    [start_dim_time_key]                  INT            NULL,
    [subscription_center_id]              INT            NULL,
    [subscription_id]                     VARCHAR (4000) NULL,
    [p_exerp_freeze_period_id]            BIGINT         NOT NULL,
    [deleted_flag]                        INT            NULL,
    [dv_load_date_time]                   DATETIME       NULL,
    [dv_load_end_date_time]               DATETIME       NULL,
    [dv_batch_id]                         BIGINT         NOT NULL,
    [dv_inserted_date_time]               DATETIME       NOT NULL,
    [dv_insert_user]                      VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                DATETIME       NULL,
    [dv_update_user]                      VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

