CREATE TABLE [dbo].[d_exerp_person_detail] (
    [d_exerp_person_detail_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                  CHAR (32)      NOT NULL,
    [person_id]                VARCHAR (4000) NULL,
    [address_1]                VARCHAR (4000) NULL,
    [address_2]                VARCHAR (4000) NULL,
    [address_3]                VARCHAR (4000) NULL,
    [center_id]                INT            NULL,
    [dim_club_key]             VARCHAR (32)   NULL,
    [dim_mms_member_key]       VARCHAR (32)   NULL,
    [email]                    VARCHAR (4000) NULL,
    [ets]                      VARCHAR (4000) NULL,
    [first_name]               VARCHAR (4000) NULL,
    [full_name]                VARCHAR (4000) NULL,
    [home_phone]               VARCHAR (4000) NULL,
    [last_name]                VARCHAR (4000) NULL,
    [mobile_phone]             VARCHAR (4000) NULL,
    [work_phone]               VARCHAR (4000) NULL,
    [p_exerp_person_detail_id] BIGINT         NOT NULL,
    [deleted_flag]             INT            NULL,
    [dv_load_date_time]        DATETIME       NULL,
    [dv_load_end_date_time]    DATETIME       NULL,
    [dv_batch_id]              BIGINT         NOT NULL,
    [dv_inserted_date_time]    DATETIME       NOT NULL,
    [dv_insert_user]           VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]     DATETIME       NULL,
    [dv_update_user]           VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

