CREATE TABLE [dbo].[d_exerp_access_privilege_usage] (
    [d_exerp_access_privilege_usage_id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                   CHAR (32)      NOT NULL,
    [dim_exerp_access_privilege_usage_key]      VARCHAR (32)   NULL,
    [access_privilege_usage_id]                 INT            NULL,
    [access_privilege_usage_state]              VARCHAR (4000) NULL,
    [deduction_fact_exerp_clipcard_usage_key]   VARCHAR (32)   NULL,
    [deduction_fact_exerp_transaction_log_key]  VARCHAR (32)   NULL,
    [deduction_key]                             VARCHAR (4000) NULL,
    [dim_club_key]                              VARCHAR (32)   NULL,
    [ets]                                       BIGINT         NULL,
    [punishment_fact_exerp_clipcard_usage_key]  VARCHAR (32)   NULL,
    [punishment_fact_exerp_transaction_log_key] VARCHAR (32)   NULL,
    [punishment_key]                            VARCHAR (4000) NULL,
    [source_dim_exerp_clipcard_key]             VARCHAR (32)   NULL,
    [source_dim_exerp_subscription_addon_key]   VARCHAR (32)   NULL,
    [source_dim_exerp_subscription_key]         VARCHAR (32)   NULL,
    [source_fact_exerp_transaction_log_key]     VARCHAR (32)   NULL,
    [source_id]                                 VARCHAR (4000) NULL,
    [source_type]                               VARCHAR (4000) NULL,
    [target_dim_exerp_booking_key]              VARCHAR (32)   NULL,
    [target_fact_exerp_attend_key]              VARCHAR (32)   NULL,
    [target_fact_exerp_participation_key]       VARCHAR (32)   NULL,
    [target_id]                                 VARCHAR (4000) NULL,
    [target_type]                               VARCHAR (4000) NULL,
    [p_exerp_access_privilege_usage_id]         BIGINT         NOT NULL,
    [deleted_flag]                              INT            NULL,
    [dv_load_date_time]                         DATETIME       NULL,
    [dv_load_end_date_time]                     DATETIME       NULL,
    [dv_batch_id]                               BIGINT         NOT NULL,
    [dv_inserted_date_time]                     DATETIME       NOT NULL,
    [dv_insert_user]                            VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                      DATETIME       NULL,
    [dv_update_user]                            VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

