CREATE TABLE [dbo].[d_exerp_daily_member_state] (
    [d_exerp_daily_member_state_id]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)      NOT NULL,
    [daily_member_state_id]                INT            NULL,
    [cancel_dim_date_key]                  CHAR (8)       NULL,
    [cancel_dim_time_key]                  CHAR (8)       NULL,
    [center_id]                            INT            NULL,
    [d_exerp_center_bk_hash]               CHAR (32)      NULL,
    [daily_member_state_change]            VARCHAR (4000) NULL,
    [daily_member_state_date_dim_date_key] CHAR (8)       NULL,
    [daily_member_state_date_dim_time_key] CHAR (8)       NULL,
    [dim_mms_member_key]                   VARCHAR (32)   NULL,
    [entry_dim_date_key]                   CHAR (8)       NULL,
    [entry_dim_time_key]                   CHAR (8)       NULL,
    [ets]                                  BIGINT         NULL,
    [extra_number_delta]                   INT            NULL,
    [home_center_person_id]                INT            NULL,
    [member_number_delta]                  INT            NULL,
    [person_id]                            VARCHAR (4000) NULL,
    [secondary_member_number_delta]        INT            NULL,
    [p_exerp_daily_member_state_id]        BIGINT         NOT NULL,
    [deleted_flag]                         INT            NULL,
    [dv_load_date_time]                    DATETIME       NULL,
    [dv_load_end_date_time]                DATETIME       NULL,
    [dv_batch_id]                          BIGINT         NOT NULL,
    [dv_inserted_date_time]                DATETIME       NOT NULL,
    [dv_insert_user]                       VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                 DATETIME       NULL,
    [dv_update_user]                       VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

