CREATE TABLE [dbo].[d_exerp_person] (
    [d_exerp_person_id]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                     CHAR (32)      NOT NULL,
    [person_id]                   VARCHAR (4000) NULL,
    [can_email_flag]              CHAR (1)       NULL,
    [can_sms_flag]                CHAR (1)       NULL,
    [city]                        VARCHAR (4000) NULL,
    [company_id]                  VARCHAR (4000) NULL,
    [country_id]                  VARCHAR (4000) NULL,
    [county]                      VARCHAR (4000) NULL,
    [creation_dim_date_key]       CHAR (8)       NULL,
    [d_exerp_center_bk_hash]      CHAR (32)      NULL,
    [date_of_birth_dim_date_key]  CHAR (8)       NULL,
    [dim_employee_key]            VARCHAR (32)   NULL,
    [dim_mms_member_key]          VARCHAR (32)   NULL,
    [duplicate_of_person_id]      VARCHAR (4000) NULL,
    [employee_title]              VARCHAR (4000) NULL,
    [ets]                         BIGINT         NULL,
    [gender]                      VARCHAR (4000) NULL,
    [home_center_person_id]       INT            NULL,
    [home_d_exerp_center_bk_hash] CHAR (32)      NULL,
    [payer_person_id]             VARCHAR (4000) NULL,
    [person_status]               VARCHAR (4000) NULL,
    [person_type]                 VARCHAR (4000) NULL,
    [postal_code]                 VARCHAR (4000) NULL,
    [staff_external_id]           VARCHAR (4000) NULL,
    [state]                       VARCHAR (4000) NULL,
    [title]                       VARCHAR (4000) NULL,
    [p_exerp_person_id]           BIGINT         NOT NULL,
    [deleted_flag]                INT            NULL,
    [dv_load_date_time]           DATETIME       NULL,
    [dv_load_end_date_time]       DATETIME       NULL,
    [dv_batch_id]                 BIGINT         NOT NULL,
    [dv_inserted_date_time]       DATETIME       NOT NULL,
    [dv_insert_user]              VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]        DATETIME       NULL,
    [dv_update_user]              VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

