CREATE TABLE [dbo].[d_exerp_product] (
    [d_exerp_product_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                       CHAR (32)       NOT NULL,
    [product_id]                    VARCHAR (4000)  NULL,
    [d_exerp_product_group_bk_hash] CHAR (32)       NULL,
    [dim_club_key]                  CHAR (32)       NULL,
    [dim_mms_product_key]           VARCHAR (32)    NULL,
    [ets]                           BIGINT          NULL,
    [external_id]                   VARCHAR (4000)  NULL,
    [master_dim_exerp_product_key]  CHAR (32)       NULL,
    [product_blocked_flag]          CHAR (1)        NULL,
    [product_cost_price]            DECIMAL (26, 6) NULL,
    [product_flat_rate_commission]  DECIMAL (26, 6) NULL,
    [product_group_id]              INT             NULL,
    [product_included_member_count] INT             NULL,
    [product_minimum_price]         DECIMAL (26, 6) NULL,
    [product_name]                  VARCHAR (4000)  NULL,
    [product_period_commission]     INT             NULL,
    [product_sales_commission]      INT             NULL,
    [product_sales_price]           DECIMAL (26, 6) NULL,
    [product_sales_units]           INT             NULL,
    [product_type]                  VARCHAR (4000)  NULL,
    [p_exerp_product_id]            BIGINT          NOT NULL,
    [deleted_flag]                  INT             NULL,
    [dv_load_date_time]             DATETIME        NULL,
    [dv_load_end_date_time]         DATETIME        NULL,
    [dv_batch_id]                   BIGINT          NOT NULL,
    [dv_inserted_date_time]         DATETIME        NOT NULL,
    [dv_insert_user]                VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]          DATETIME        NULL,
    [dv_update_user]                VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

