CREATE TABLE [dbo].[d_exerp_participation] (
    [d_exerp_participation_id]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)      NOT NULL,
    [fact_exerp_participation_key] VARCHAR (32)   NULL,
    [participation_id]             VARCHAR (4000) NULL,
    [cancel_dim_date_key]          CHAR (8)       NULL,
    [cancel_dim_time_key]          CHAR (8)       NULL,
    [cancel_interface_type]        VARCHAR (4000) NULL,
    [cancel_reason]                VARCHAR (4000) NULL,
    [creation_dim_date_key]        CHAR (8)       NULL,
    [creation_dim_time_key]        CHAR (8)       NULL,
    [dim_club_key]                 CHAR (32)      NULL,
    [dim_exerp_booking_key]        CHAR (32)      NULL,
    [dim_mms_member_key]           VARCHAR (32)   NULL,
    [ets]                          BIGINT         NULL,
    [participant_number]           INT            NULL,
    [participation_state]          VARCHAR (4000) NULL,
    [seat_id]                      VARCHAR (4000) NULL,
    [seat_obtained_datetime]       DATETIME       NULL,
    [seat_obtained_dim_date_key]   VARCHAR (8)    NULL,
    [seat_obtained_dim_time_key]   INT            NULL,
    [seat_state]                   VARCHAR (4000) NULL,
    [show_up_dim_date_key]         CHAR (8)       NULL,
    [show_up_dim_time_key]         CHAR (8)       NULL,
    [show_up_interface_type]       VARCHAR (4000) NULL,
    [show_up_using_card_flag]      CHAR (1)       NULL,
    [user_interface_type]          VARCHAR (4000) NULL,
    [was_on_waiting_list_flag]     CHAR (1)       NULL,
    [p_exerp_participation_id]     BIGINT         NOT NULL,
    [deleted_flag]                 INT            NULL,
    [dv_load_date_time]            DATETIME       NULL,
    [dv_load_end_date_time]        DATETIME       NULL,
    [dv_batch_id]                  BIGINT         NOT NULL,
    [dv_inserted_date_time]        DATETIME       NOT NULL,
    [dv_insert_user]               VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]         DATETIME       NULL,
    [dv_update_user]               VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

