CREATE TABLE [dbo].[d_exerp_time_configuration] (
    [d_exerp_time_configuration_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                       CHAR (32)      NOT NULL,
    [time_configuration_id]         INT            NULL,
    [cancel_sanc_start]             INT            NULL,
    [cancel_sanc_start_unit]        VARCHAR (4000) NULL,
    [cancel_stop_cust]              INT            NULL,
    [cancel_stop_cust_unit]         VARCHAR (4000) NULL,
    [cancel_stop_staff]             INT            NULL,
    [cancel_stop_staff_unit]        VARCHAR (4000) NULL,
    [course_sign_start]             INT            NULL,
    [course_sign_start_unit]        VARCHAR (4000) NULL,
    [course_stop]                   INT            NULL,
    [course_stop_unit]              VARCHAR (4000) NULL,
    [part_cust_stop]                INT            NULL,
    [part_cust_stop_unit]           VARCHAR (4000) NULL,
    [part_from]                     INT            NULL,
    [part_from_unit]                VARCHAR (4000) NULL,
    [part_staff_stop]               INT            NULL,
    [part_staff_stop_unit]          VARCHAR (4000) NULL,
    [recurrence_in_past]            INT            NULL,
    [recurrence_in_past_unit]       VARCHAR (4000) NULL,
    [time_configuration_name]       VARCHAR (4000) NULL,
    [p_exerp_time_configuration_id] BIGINT         NOT NULL,
    [deleted_flag]                  INT            NULL,
    [dv_load_date_time]             DATETIME       NULL,
    [dv_load_end_date_time]         DATETIME       NULL,
    [dv_batch_id]                   BIGINT         NOT NULL,
    [dv_inserted_date_time]         DATETIME       NOT NULL,
    [dv_insert_user]                VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]          DATETIME       NULL,
    [dv_update_user]                VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

