CREATE TABLE [dbo].[d_exerp_sale_log] (
    [d_exerp_sale_log_id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)       NOT NULL,
    [fact_exerp_transaction_log_key]         VARCHAR (32)    NULL,
    [sale_log_id]                            VARCHAR (4000)  NULL,
    [book_dim_date_key]                      VARCHAR (8)     NULL,
    [book_dim_time_key]                      INT             NULL,
    [cash_register_center_id]                INT             NULL,
    [cash_register_dim_club_key]             VARCHAR (32)    NULL,
    [company_id]                             VARCHAR (4000)  NULL,
    [credit_fact_exerp_transaction_log_key]  VARCHAR (32)    NULL,
    [dim_club_key]                           VARCHAR (32)    NULL,
    [dim_exerp_product_key]                  VARCHAR (32)    NULL,
    [dim_mms_member_key]                     VARCHAR (32)    NULL,
    [entry_dim_date_key]                     VARCHAR (8)     NULL,
    [entry_dim_time_key]                     INT             NULL,
    [ets]                                    BIGINT          NULL,
    [external_id]                            VARCHAR (4000)  NULL,
    [flat_rate_commission]                   DECIMAL (26, 6) NULL,
    [gl_credit_account]                      VARCHAR (4000)  NULL,
    [gl_debit_account]                       VARCHAR (4000)  NULL,
    [is_company_flag]                        CHAR (1)        NULL,
    [net_amount]                             DECIMAL (26, 6) NULL,
    [period_commission]                      INT             NULL,
    [product_dim_club_key]                   VARCHAR (32)    NULL,
    [product_normal_price]                   DECIMAL (26, 6) NULL,
    [product_type]                           VARCHAR (4000)  NULL,
    [quantity]                               INT             NULL,
    [sale_commission]                        INT             NULL,
    [sale_entered_dim_employee_key]          VARCHAR (32)    NULL,
    [sale_fact_exerp_transaction_log_key]    VARCHAR (32)    NULL,
    [sale_id]                                VARCHAR (4000)  NULL,
    [sale_type]                              VARCHAR (4000)  NULL,
    [sale_units]                             INT             NULL,
    [source_type]                            VARCHAR (4000)  NULL,
    [sponsor_fact_exerp_transaction_log_key] VARCHAR (32)    NULL,
    [total_amount]                           DECIMAL (26, 6) NULL,
    [vat_amount]                             DECIMAL (26, 6) NULL,
    [p_exerp_sale_log_id]                    BIGINT          NOT NULL,
    [deleted_flag]                           INT             NULL,
    [dv_load_date_time]                      DATETIME        NULL,
    [dv_load_end_date_time]                  DATETIME        NULL,
    [dv_batch_id]                            BIGINT          NOT NULL,
    [dv_inserted_date_time]                  DATETIME        NOT NULL,
    [dv_insert_user]                         VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                   DATETIME        NULL,
    [dv_update_user]                         VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

