CREATE TABLE [dbo].[d_healthcheckusa_transactions] (
    [d_healthcheckusa_transactions_id]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                    CHAR (32)       NOT NULL,
    [d_healthcheckusa_transactions_bk_hash]      CHAR (32)       NULL,
    [order_number]                               INT             NULL,
    [product_sku]                                VARCHAR (50)    NULL,
    [allocated_month_starting_dim_date_key]      VARCHAR (8)     NULL,
    [allocated_recalculate_through_datetime]     DATETIME        NULL,
    [allocated_recalculate_through_dim_date_key] VARCHAR (8)     NULL,
    [default_dim_reporting_hierarchy_key]        VARCHAR (32)    NULL,
    [dim_employee_key]                           CHAR (32)       NULL,
    [dim_healthcheckusa_product_key]             VARCHAR (32)    NULL,
    [employee_id]                                INT             NULL,
    [gl_club_id]                                 INT             NULL,
    [item_amount]                                DECIMAL (26, 6) NULL,
    [item_discount]                              DECIMAL (26, 6) NULL,
    [order_for_employee_flag]                    CHAR (1)        NULL,
    [quantity]                                   INT             NULL,
    [transaction_date]                           DATETIME        NULL,
    [transaction_post_dim_date_key]              VARCHAR (8)     NULL,
    [transaction_post_dim_time_key]              INT             NULL,
    [transaction_type]                           VARCHAR (100)   NULL,
    [p_healthcheckusa_transactions_id]           BIGINT          NOT NULL,
    [deleted_flag]                               INT             NULL,
    [dv_load_date_time]                          DATETIME        NULL,
    [dv_load_end_date_time]                      DATETIME        NULL,
    [dv_batch_id]                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                      DATETIME        NOT NULL,
    [dv_insert_user]                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                       DATETIME        NULL,
    [dv_update_user]                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

