CREATE TABLE [dbo].[d_humanity_schedule] (
    [d_humanity_schedule_id]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                 CHAR (32)     NOT NULL,
    [d_humanity_schedule_key] CHAR (32)     NULL,
    [shift_id]                BIGINT        NULL,
    [employee_id]             VARCHAR (255) NULL,
    [position_id]             VARCHAR (255) NULL,
    [ltf_file_name]           VARCHAR (255) NULL,
    [company_id]              VARCHAR (255) NULL,
    [company_name]            VARCHAR (255) NULL,
    [created_by_eid]          VARCHAR (255) NULL,
    [created_by_id]           VARCHAR (255) NULL,
    [created_by_name]         VARCHAR (255) NULL,
    [created_datetime_utc]    VARCHAR (255) NULL,
    [employee_eid]            VARCHAR (255) NULL,
    [employee_name]           VARCHAR (255) NULL,
    [employees_needed]        VARCHAR (255) NULL,
    [employees_working]       VARCHAR (255) NULL,
    [file_arrive_date]        DATE          NULL,
    [hours]                   VARCHAR (255) NULL,
    [is_deleted]              VARCHAR (255) NULL,
    [location_id]             VARCHAR (255) NULL,
    [location_name]           VARCHAR (255) NULL,
    [notes]                   VARCHAR (255) NULL,
    [position_name]           VARCHAR (255) NULL,
    [published]               VARCHAR (255) NULL,
    [published_datetime_utc]  VARCHAR (255) NULL,
    [recurring_shift]         VARCHAR (255) NULL,
    [shift_end_date_utc]      VARCHAR (255) NULL,
    [shift_end_time]          VARCHAR (255) NULL,
    [shift_start_date_utc]    VARCHAR (255) NULL,
    [shift_start_time]        VARCHAR (255) NULL,
    [shift_type]              VARCHAR (255) NULL,
    [updated_at_utc]          VARCHAR (255) NULL,
    [wage]                    VARCHAR (255) NULL,
    [workday_position_id]     VARCHAR (255) NULL,
    [p_humanity_schedule_id]  BIGINT        NOT NULL,
    [deleted_flag]            INT           NULL,
    [dv_load_date_time]       DATETIME      NULL,
    [dv_load_end_date_time]   DATETIME      NULL,
    [dv_batch_id]             BIGINT        NOT NULL,
    [dv_inserted_date_time]   DATETIME      NOT NULL,
    [dv_insert_user]          VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]    DATETIME      NULL,
    [dv_update_user]          VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

