CREATE TABLE [dbo].[d_hybris_stock_levels] (
    [d_hybris_stock_levels_id]        BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)     NOT NULL,
    [d_hybris_stock_levels_key]       CHAR (32)     NULL,
    [stock_levels_pk]                 BIGINT        NULL,
    [acl_ts]                          INT           NULL,
    [created_ts]                      DATETIME      NULL,
    [hjmpts]                          BIGINT        NULL,
    [modified_ts]                     DATETIME      NULL,
    [owner_pk_string]                 BIGINT        NULL,
    [p_available]                     INT           NULL,
    [p_in_stock_status]               BIGINT        NULL,
    [p_max_pre_order]                 INT           NULL,
    [p_max_stock_level_history_count] INT           NULL,
    [p_next_delivery_time]            DATETIME      NULL,
    [p_over_selling]                  INT           NULL,
    [p_pre_order]                     INT           NULL,
    [p_product_code]                  VARCHAR (255) NULL,
    [p_release_date]                  DATETIME      NULL,
    [p_reserved]                      INT           NULL,
    [p_treat_negative_as_zero]        INT           NULL,
    [p_warehouse]                     BIGINT        NULL,
    [prop_ts]                         INT           NULL,
    [type_pk_string]                  BIGINT        NULL,
    [p_hybris_stock_levels_id]        BIGINT        NOT NULL,
    [dv_load_date_time]               DATETIME      NULL,
    [dv_load_end_date_time]           DATETIME      NULL,
    [dv_batch_id]                     BIGINT        NOT NULL,
    [dv_inserted_date_time]           DATETIME      NOT NULL,
    [dv_insert_user]                  VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]            DATETIME      NULL,
    [dv_update_user]                  VARCHAR (50)  NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

