CREATE TABLE [dbo].[d_hybris_products] (
    [d_hybris_products_id]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)       NOT NULL,
    [d_hybris_products_key]        CHAR (32)       NULL,
    [products_pk]                  BIGINT          NULL,
    [code]                         NVARCHAR (255)  NULL,
    [created_ts]                   DATETIME        NULL,
    [hjmpts]                       BIGINT          NULL,
    [modified_ts]                  DATETIME        NULL,
    [owner_pk_string]              BIGINT          NULL,
    [p_agreement]                  BIGINT          NULL,
    [p_allow_member_selection]     TINYINT         NULL,
    [p_approval_status]            BIGINT          NULL,
    [p_article]                    BIGINT          NULL,
    [p_auto_shipflag]              TINYINT         NULL,
    [p_auto_thumb_nails]           VARCHAR (8000)  NULL,
    [p_barcode]                    TINYINT         NULL,
    [p_base_product]               BIGINT          NULL,
    [p_canadian_product]           TINYINT         NULL,
    [p_card_type]                  BIGINT          NULL,
    [p_catalog]                    BIGINT          NULL,
    [p_catalog_version]            BIGINT          NULL,
    [p_club]                       BIGINT          NULL,
    [p_content_unit]               BIGINT          NULL,
    [p_cost_center_id]             NVARCHAR (255)  NULL,
    [p_data_sheet]                 VARCHAR (8000)  NULL,
    [p_delivery_time]              DECIMAL (26, 6) NULL,
    [p_denomination]               INT             NULL,
    [p_detail]                     VARCHAR (8000)  NULL,
    [p_display_number]             INT             NULL,
    [p_e_gift_card_flag]           TINYINT         NULL,
    [p_e_gift_cards]               VARCHAR (8000)  NULL,
    [p_ean]                        NVARCHAR (255)  NULL,
    [p_electronic_shipping_flag]   TINYINT         NULL,
    [p_email_template_id]          NVARCHAR (255)  NULL,
    [p_end_line_number]            INT             NULL,
    [p_erp_group_buyer]            NVARCHAR (255)  NULL,
    [p_erp_group_supplier]         NVARCHAR (255)  NULL,
    [p_europe_1_price_factory_pdg] BIGINT          NULL,
    [p_europe_1_price_factory_ppg] BIGINT          NULL,
    [p_europe_1_price_factory_ptg] BIGINT          NULL,
    [p_external_redeem_flag]       TINYINT         NULL,
    [p_free_usps_shipping_flag]    TINYINT         NULL,
    [p_fulfillment_partner]        BIGINT          NULL,
    [p_fulfillment_product_id]     NVARCHAR (255)  NULL,
    [p_gallery_images]             VARCHAR (8000)  NULL,
    [p_gender]                     BIGINT          NULL,
    [p_genders]                    VARCHAR (8000)  NULL,
    [p_gift_card_flag]             TINYINT         NULL,
    [p_is_giftable]                TINYINT         NULL,
    [p_item_description]           NVARCHAR (255)  NULL,
    [p_logo]                       VARCHAR (8000)  NULL,
    [p_lt_bucks_amount]            DECIMAL (26, 6) NULL,
    [p_lt_bucks_flag]              TINYINT         NULL,
    [p_ltf_offer_flag]             TINYINT         NULL,
    [p_ltf_only_product]           TINYINT         NULL,
    [p_ma_local_flag]              TINYINT         NULL,
    [p_manufacturer_aid]           NVARCHAR (255)  NULL,
    [p_manufacturer_name]          NVARCHAR (255)  NULL,
    [p_max_order_quantity]         INT             NULL,
    [p_media]                      BIGINT          NULL,
    [p_media_container]            BIGINT          NULL,
    [p_min_order_quantity]         INT             NULL,
    [p_mms_product_id]             INT             NULL,
    [p_mms_recurrent]              TINYINT         NULL,
    [p_mobile_product_flag]        TINYINT         NULL,
    [p_normal]                     VARCHAR (8000)  NULL,
    [p_number]                     INT             NULL,
    [p_number_content_units]       DECIMAL (26, 6) NULL,
    [p_occasions]                  VARCHAR (8000)  NULL,
    [p_offer_external_link_flag]   TINYINT         NULL,
    [p_offering_id]                NVARCHAR (255)  NULL,
    [p_offline_date]               DATETIME        NULL,
    [p_online_date]                DATETIME        NULL,
    [p_order]                      INT             NULL,
    [p_order_quantity_interval]    INT             NULL,
    [p_others]                     VARCHAR (8000)  NULL,
    [p_personal_details]           BIGINT          NULL,
    [p_picture]                    BIGINT          NULL,
    [p_previous_base_product]      BIGINT          NULL,
    [p_price_quantity]             DECIMAL (26, 6) NULL,
    [p_product_cost]               DECIMAL (26, 6) NULL,
    [p_product_height]             DECIMAL (26, 6) NULL,
    [p_product_length]             DECIMAL (26, 6) NULL,
    [p_product_messages]           VARCHAR (8000)  NULL,
    [p_product_order_limit]        BIGINT          NULL,
    [p_product_tag]                BIGINT          NULL,
    [p_product_width]              DECIMAL (26, 6) NULL,
    [p_raw_asset]                  BIGINT          NULL,
    [p_region_id]                  NVARCHAR (255)  NULL,
    [p_rev_category_id]            NVARCHAR (255)  NULL,
    [p_searchable]                 TINYINT         NULL,
    [p_sequence_id]                BIGINT          NULL,
    [p_simple_asset]               BIGINT          NULL,
    [p_spend_category_id]          NVARCHAR (255)  NULL,
    [p_start_line_number]          INT             NULL,
    [p_state]                      BIGINT          NULL,
    [p_supplier_alternative_aid]   NVARCHAR (255)  NULL,
    [p_swatch_colour]              NVARCHAR (255)  NULL,
    [p_thumb_nail]                 BIGINT          NULL,
    [p_thumb_nails]                VARCHAR (8000)  NULL,
    [p_training_session]           BIGINT          NULL,
    [p_type_descriptor]            NVARCHAR (255)  NULL,
    [p_variant_type]               BIGINT          NULL,
    [p_weight]                     DECIMAL (26, 6) NULL,
    [prop_ts]                      INT             NULL,
    [type_pk_string]               BIGINT          NULL,
    [unit_pk]                      BIGINT          NULL,
    [p_hybris_products_id]         BIGINT          NOT NULL,
    [dv_load_date_time]            DATETIME        NULL,
    [dv_load_end_date_time]        DATETIME        NULL,
    [dv_batch_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]         DATETIME        NULL,
    [dv_update_user]               VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

