CREATE TABLE [dbo].[d_ig_it_cfg_terminal_master] (
    [d_ig_it_cfg_terminal_master_id]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)     NOT NULL,
    [dim_ig_it_cfg_terminal_master_key]            VARCHAR (32)  NULL,
    [term_id]                                      INT           NULL,
    [alt_bargun_dim_ig_it_cfg_terminal_master_key] VARCHAR (32)  NULL,
    [alt_bargun_term_id]                           INT           NULL,
    [alt_rcpt_dim_ig_it_cfg_terminal_master_key]   VARCHAR (32)  NULL,
    [alt_rcpt_term_id]                             INT           NULL,
    [bargun_bump_override_flag]                    CHAR (1)      NULL,
    [bargun_print_drinks_on_bump_flag]             CHAR (1)      NULL,
    [bargun_term_flag]                             CHAR (1)      NULL,
    [current_version]                              NVARCHAR (15) NULL,
    [default_table_layout_id]                      INT           NULL,
    [first_table_no]                               INT           NULL,
    [fol_file_load_flag]                           CHAR (1)      NULL,
    [ga_file_load_flag]                            CHAR (1)      NULL,
    [ip_address]                                   VARCHAR (15)  NULL,
    [is_default_api_terminal_flag]                 CHAR (1)      NULL,
    [last_ping_utc_date_time]                      DATETIME      NULL,
    [last_ping_utc_dim_date_key]                   VARCHAR (8)   NULL,
    [last_ping_utc_dim_time_key]                   INT           NULL,
    [num_tables]                                   INT           NULL,
    [payment_device_id]                            INT           NULL,
    [ped_value]                                    NVARCHAR (50) NULL,
    [primary_profit_center_id]                     INT           NULL,
    [profile_id]                                   INT           NULL,
    [receipt_printer_type]                         TINYINT       NULL,
    [rms_file_load_flag]                           CHAR (1)      NULL,
    [row_version]                                  BINARY (8)    NULL,
    [static_receipt_printer_id]                    INT           NULL,
    [term_active_flag]                             CHAR (1)      NULL,
    [term_grp_id]                                  INT           NULL,
    [term_name]                                    NVARCHAR (50) NULL,
    [term_option_grp_id]                           INT           NULL,
    [term_printer_grp_id]                          INT           NULL,
    [term_receipt_info]                            NVARCHAR (50) NULL,
    [term_service_grp_id]                          INT           NULL,
    [virtual_term_flag]                            CHAR (1)      NULL,
    [p_ig_it_cfg_terminal_master_id]               BIGINT        NOT NULL,
    [deleted_flag]                                 INT           NULL,
    [dv_load_date_time]                            DATETIME      NULL,
    [dv_load_end_date_time]                        DATETIME      NULL,
    [dv_batch_id]                                  BIGINT        NOT NULL,
    [dv_inserted_date_time]                        DATETIME      NOT NULL,
    [dv_insert_user]                               VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                         DATETIME      NULL,
    [dv_update_user]                               VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

