CREATE TABLE [dbo].[d_ig_it_trn_order_header] (
    [d_ig_it_trn_order_header_id]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)       NOT NULL,
    [order_hdr_id]                           INT             NULL,
    [check_number]                           INT             NULL,
    [d_ig_it_trn_business_day_dates_bk_hash] VARCHAR (32)    NULL,
    [dim_cafe_profit_center_key]             VARCHAR (32)    NULL,
    [order_close_dim_date_key]               CHAR (8)        NULL,
    [order_close_dim_time_key]               CHAR (8)        NULL,
    [order_close_month_ending_dim_date_key]  CHAR (8)        NULL,
    [order_closed_flag]                      CHAR (1)        NULL,
    [order_commissionable_dim_employee_key]  VARCHAR (32)    NULL,
    [order_discount_amount]                  DECIMAL (26, 6) NULL,
    [order_open_dim_date_key]                CHAR (8)        NULL,
    [order_open_dim_time_key]                CHAR (8)        NULL,
    [order_refund_flag]                      CHAR (1)        NULL,
    [order_sales_amount_gross]               DECIMAL (26, 6) NULL,
    [order_service_charge_amount]            DECIMAL (26, 6) NULL,
    [order_tax_amount]                       DECIMAL (26, 6) NULL,
    [order_tax_removed_flag]                 CHAR (1)        NULL,
    [order_tip_amount]                       DECIMAL (26, 6) NULL,
    [order_void_flag]                        CHAR (1)        NULL,
    [profit_center_id]                       INT             NULL,
    [p_ig_it_trn_order_header_id]            BIGINT          NOT NULL,
    [deleted_flag]                           INT             NULL,
    [dv_load_date_time]                      DATETIME        NULL,
    [dv_load_end_date_time]                  DATETIME        NULL,
    [dv_batch_id]                            BIGINT          NOT NULL,
    [dv_inserted_date_time]                  DATETIME        NOT NULL,
    [dv_insert_user]                         VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                   DATETIME        NULL,
    [dv_update_user]                         VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

