CREATE TABLE [dbo].[d_magento_sales_invoice_item] (
    [d_magento_sales_invoice_item_id]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                               CHAR (32)       NOT NULL,
    [sales_invoice_item_id]                 INT             NULL,
    [base_cost]                             DECIMAL (12, 4) NULL,
    [base_discount_amount]                  DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount] DECIMAL (12, 4) NULL,
    [base_price]                            DECIMAL (12, 4) NULL,
    [base_price_incl_tax]                   DECIMAL (12, 4) NULL,
    [base_row_total]                        DECIMAL (12, 4) NULL,
    [base_row_total_incl_tax]               DECIMAL (12, 4) NULL,
    [base_tax_amount]                       DECIMAL (12, 4) NULL,
    [d_magento_sales_invoice_bk_hash]       VARCHAR (32)    NULL,
    [description]                           VARCHAR (8000)  NULL,
    [dim_magento_order_item_bk_hash]        VARCHAR (32)    NULL,
    [dim_magento_product_key]               VARCHAR (32)    NULL,
    [discount_amount]                       DECIMAL (12, 4) NULL,
    [discount_tax_compensation_amount]      DECIMAL (12, 4) NULL,
    [fact_magento_invoice_key]              VARCHAR (32)    NULL,
    [fact_magento_order_item_key]           VARCHAR (32)    NULL,
    [name]                                  VARCHAR (255)   NULL,
    [price]                                 DECIMAL (12, 4) NULL,
    [price_incl_tax]                        DECIMAL (12, 4) NULL,
    [qty]                                   DECIMAL (12, 4) NULL,
    [row_total]                             DECIMAL (12, 4) NULL,
    [row_total_incl_tax]                    DECIMAL (12, 4) NULL,
    [sku]                                   VARCHAR (255)   NULL,
    [tax_amount]                            DECIMAL (12, 4) NULL,
    [tax_ratio]                             VARCHAR (8000)  NULL,
    [p_magento_sales_invoice_item_id]       BIGINT          NOT NULL,
    [deleted_flag]                          INT             NULL,
    [dv_load_date_time]                     DATETIME        NULL,
    [dv_load_end_date_time]                 DATETIME        NULL,
    [dv_batch_id]                           BIGINT          NOT NULL,
    [dv_inserted_date_time]                 DATETIME        NOT NULL,
    [dv_insert_user]                        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                  DATETIME        NULL,
    [dv_update_user]                        VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

