CREATE TABLE [dbo].[d_magento_catalog_category_flat_store_1] (
    [d_magento_catalog_category_flat_store_1_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                    CHAR (32)       NOT NULL,
    [catalog_category_flat_store_id]             INT             NULL,
    [all_children]                               VARCHAR (255)   NULL,
    [attribute_set_id]                           INT             NULL,
    [automatic_sorting]                          VARCHAR (255)   NULL,
    [available_sort_by]                          VARCHAR (255)   NULL,
    [children]                                   VARCHAR (255)   NULL,
    [children_count]                             INT             NULL,
    [created_at]                                 DATETIME        NULL,
    [created_dim_date_key]                       VARCHAR (8)     NULL,
    [created_dim_time_key]                       VARCHAR (8)     NULL,
    [created_in]                                 BIGINT          NULL,
    [custom_apply_to_products]                   INT             NULL,
    [custom_design]                              VARCHAR (255)   NULL,
    [custom_design_from]                         DATETIME        NULL,
    [custom_design_from_dim_date_key]            VARCHAR (8)     NULL,
    [custom_design_from_dim_time_key]            VARCHAR (8)     NULL,
    [custom_design_to]                           DATETIME        NULL,
    [custom_design_to_dim_date_key]              VARCHAR (8)     NULL,
    [custom_design_to_dim_time_key]              VARCHAR (8)     NULL,
    [custom_layout_update]                       VARCHAR (255)   NULL,
    [custom_use_parent_settings]                 INT             NULL,
    [default_sort_by]                            VARCHAR (255)   NULL,
    [description]                                VARCHAR (255)   NULL,
    [dim_magento_category_key]                   VARCHAR (32)    NULL,
    [display_mode]                               VARCHAR (255)   NULL,
    [featured_category]                          INT             NULL,
    [featured_image]                             VARCHAR (255)   NULL,
    [filter_price_range]                         DECIMAL (12, 4) NULL,
    [include_in_menu_flag]                       CHAR (1)        NULL,
    [is_active_flag]                             CHAR (1)        NULL,
    [is_anchor_flag]                             CHAR (1)        NULL,
    [is_virtual_category_flag]                   CHAR (1)        NULL,
    [landing_page]                               INT             NULL,
    [level]                                      INT             NULL,
    [meta_description]                           VARCHAR (255)   NULL,
    [meta_keywords]                              VARCHAR (255)   NULL,
    [meta_title]                                 VARCHAR (255)   NULL,
    [name]                                       VARCHAR (255)   NULL,
    [page_layout]                                VARCHAR (255)   NULL,
    [parent_id]                                  INT             NULL,
    [path]                                       VARCHAR (255)   NULL,
    [path_in_store]                              VARCHAR (255)   NULL,
    [position]                                   INT             NULL,
    [row_id]                                     INT             NULL,
    [short_description]                          VARCHAR (255)   NULL,
    [store_id]                                   INT             NULL,
    [thumbnail]                                  VARCHAR (255)   NULL,
    [updated_at]                                 DATETIME        NULL,
    [updated_dim_date_key]                       VARCHAR (8)     NULL,
    [updated_dim_time_key]                       VARCHAR (8)     NULL,
    [updated_in]                                 BIGINT          NULL,
    [url_key]                                    VARCHAR (255)   NULL,
    [url_path]                                   VARCHAR (255)   NULL,
    [use_name_in_product_search]                 INT             NULL,
    [virtual_category_root]                      INT             NULL,
    [virtual_rule]                               VARCHAR (255)   NULL,
    [p_magento_catalog_category_flat_store_1_id] BIGINT          NOT NULL,
    [deleted_flag]                               INT             NULL,
    [dv_load_date_time]                          DATETIME        NULL,
    [dv_load_end_date_time]                      DATETIME        NULL,
    [dv_batch_id]                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                      DATETIME        NOT NULL,
    [dv_insert_user]                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                       DATETIME        NULL,
    [dv_update_user]                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

