CREATE TABLE [dbo].[d_magento_sales_shipment] (
    [d_magento_sales_shipment_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                     CHAR (32)       NOT NULL,
    [sales_shipment_id]           INT             NULL,
    [billing_address_id]          INT             NULL,
    [created_at]                  DATETIME        NULL,
    [created_at_dim_date_key]     CHAR (8)        NULL,
    [created_at_dim_time_key]     CHAR (8)        NULL,
    [customer_note]               VARCHAR (8000)  NULL,
    [customer_note_notify]        INT             NULL,
    [dim_magento_customer_key]    CHAR (32)       NULL,
    [email_sent]                  INT             NULL,
    [fact_magento_order_key]      VARCHAR (32)    NULL,
    [m1_shipment_id]              INT             NULL,
    [sales_shipment_increment_id] VARCHAR (50)    NULL,
    [sales_shipment_total_qty]    DECIMAL (12, 4) NULL,
    [sales_shipment_total_weight] DECIMAL (12, 4) NULL,
    [send_email]                  INT             NULL,
    [shipment_status]             INT             NULL,
    [shipping_address_id]         INT             NULL,
    [store_id]                    INT             NULL,
    [updated_at]                  DATETIME        NULL,
    [updated_at_dim_date_key]     CHAR (8)        NULL,
    [updated_at_dim_time_key]     CHAR (8)        NULL,
    [p_magento_sales_shipment_id] BIGINT          NOT NULL,
    [deleted_flag]                INT             NULL,
    [dv_load_date_time]           DATETIME        NULL,
    [dv_load_end_date_time]       DATETIME        NULL,
    [dv_batch_id]                 BIGINT          NOT NULL,
    [dv_inserted_date_time]       DATETIME        NOT NULL,
    [dv_insert_user]              VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]        DATETIME        NULL,
    [dv_update_user]              VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

