CREATE TABLE [dbo].[d_magento_sales_order_address] (
    [d_magento_sales_order_address_id]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)     NOT NULL,
    [entity_id]                            INT           NULL,
    [address_type]                         VARCHAR (255) NULL,
    [city]                                 VARCHAR (255) NULL,
    [company]                              VARCHAR (255) NULL,
    [country_id]                           VARCHAR (2)   NULL,
    [customer_address_id]                  INT           NULL,
    [customer_id]                          INT           NULL,
    [d_magento_sales_order_parent_bk_hash] CHAR (32)     NULL,
    [email]                                VARCHAR (255) NULL,
    [fax]                                  VARCHAR (255) NULL,
    [first_name]                           VARCHAR (255) NULL,
    [last_name]                            VARCHAR (255) NULL,
    [middle_name]                          VARCHAR (255) NULL,
    [post_code]                            VARCHAR (255) NULL,
    [prefix]                               VARCHAR (255) NULL,
    [quote_address_id]                     INT           NULL,
    [region]                               VARCHAR (255) NULL,
    [region_id]                            INT           NULL,
    [street]                               VARCHAR (255) NULL,
    [suffix]                               VARCHAR (255) NULL,
    [telephone]                            VARCHAR (255) NULL,
    [p_magento_sales_order_address_id]     BIGINT        NOT NULL,
    [deleted_flag]                         INT           NULL,
    [dv_load_date_time]                    DATETIME      NULL,
    [dv_load_end_date_time]                DATETIME      NULL,
    [dv_batch_id]                          BIGINT        NOT NULL,
    [dv_inserted_date_time]                DATETIME      NOT NULL,
    [dv_insert_user]                       VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                 DATETIME      NULL,
    [dv_update_user]                       VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

