CREATE TABLE [dbo].[d_magento_sales_invoice] (
    [d_magento_sales_invoice_id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)       NOT NULL,
    [entity_id]                                    INT             NULL,
    [allocated_month_starting_dim_date_key]        VARCHAR (32)    NULL,
    [allocated_recalculate_through_datetime]       DATETIME        NULL,
    [allocated_recalculate_through_dim_date_key]   VARCHAR (8)     NULL,
    [base_currency_code]                           VARCHAR (3)     NULL,
    [base_customer_balance_amount]                 DECIMAL (12, 4) NULL,
    [base_discount_amount]                         DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount]        DECIMAL (12, 4) NULL,
    [base_gift_cards_amount]                       DECIMAL (12, 4) NULL,
    [base_grand_total]                             DECIMAL (12, 4) NULL,
    [base_reward_currency_amount]                  DECIMAL (12, 4) NULL,
    [base_shipping_amount]                         DECIMAL (12, 4) NULL,
    [base_shipping_discount_tax_compensation_amnt] DECIMAL (12, 4) NULL,
    [base_shipping_incl_tax]                       DECIMAL (12, 4) NULL,
    [base_shipping_tax_amount]                     DECIMAL (12, 4) NULL,
    [base_subtotal]                                DECIMAL (12, 4) NULL,
    [base_subtotal_incl_tax]                       DECIMAL (12, 4) NULL,
    [base_tax_amount]                              DECIMAL (12, 4) NULL,
    [base_to_global_rate]                          DECIMAL (12, 4) NULL,
    [base_to_order_rate]                           DECIMAL (12, 4) NULL,
    [base_total_refunded]                          DECIMAL (12, 4) NULL,
    [billing_address_id]                           INT             NULL,
    [can_void_flag]                                CHAR (1)        NULL,
    [created_at]                                   DATETIME        NULL,
    [created_dim_date_key]                         CHAR (8)        NULL,
    [created_dim_time_key]                         CHAR (8)        NULL,
    [customer_balance_amount]                      DECIMAL (12, 4) NULL,
    [customer_note_notify]                         INT             NULL,
    [d_magento_sales_order_bk_hash]                VARCHAR (32)    NULL,
    [discount_amount]                              DECIMAL (12, 4) NULL,
    [discount_description]                         VARCHAR (255)   NULL,
    [discount_tax_compensation_amount]             DECIMAL (12, 4) NULL,
    [email_sent]                                   INT             NULL,
    [fact_magento_order_key]                       VARCHAR (32)    NULL,
    [fact_magento_payment_key]                     VARCHAR (32)    NULL,
    [gift_cards_amount]                            DECIMAL (12, 4) NULL,
    [global_currency_code]                         VARCHAR (3)     NULL,
    [grand_total]                                  DECIMAL (12, 4) NULL,
    [increment_id]                                 VARCHAR (50)    NULL,
    [is_used_for_refund_flag]                      CHAR (1)        NULL,
    [m1_invoice_id]                                INT             NULL,
    [order_currency_code]                          VARCHAR (3)     NULL,
    [reward_currency_amount]                       DECIMAL (12, 4) NULL,
    [reward_points_balance]                        INT             NULL,
    [send_email]                                   INT             NULL,
    [shipping_address_id]                          INT             NULL,
    [shipping_amount]                              DECIMAL (12, 4) NULL,
    [shipping_discount_tax_compensation_amount]    DECIMAL (12, 4) NULL,
    [shipping_incl_tax]                            DECIMAL (12, 4) NULL,
    [shipping_tax_amount]                          DECIMAL (12, 4) NULL,
    [state]                                        INT             NULL,
    [store_currency_code]                          VARCHAR (3)     NULL,
    [store_id]                                     INT             NULL,
    [store_to_base_rate]                           DECIMAL (12, 4) NULL,
    [store_to_order_rate]                          DECIMAL (12, 4) NULL,
    [subtotal]                                     DECIMAL (12, 4) NULL,
    [subtotal_incl_tax]                            DECIMAL (12, 4) NULL,
    [tax_amount]                                   DECIMAL (12, 4) NULL,
    [total_qty]                                    DECIMAL (12, 4) NULL,
    [transaction_id]                               VARCHAR (255)   NULL,
    [updated_at]                                   DATETIME        NULL,
    [updated_dim_date_key]                         CHAR (8)        NULL,
    [updated_dim_time_key]                         CHAR (8)        NULL,
    [p_magento_sales_invoice_id]                   BIGINT          NOT NULL,
    [deleted_flag]                                 INT             NULL,
    [dv_load_date_time]                            DATETIME        NULL,
    [dv_load_end_date_time]                        DATETIME        NULL,
    [dv_batch_id]                                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                        DATETIME        NOT NULL,
    [dv_insert_user]                               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                         DATETIME        NULL,
    [dv_update_user]                               VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

