CREATE TABLE [dbo].[d_magento_sales_order_item] (
    [d_magento_sales_order_item_id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                         CHAR (32)       NOT NULL,
    [order_item_id]                                   INT             NULL,
    [agreement_id]                                    VARCHAR (8000)  NULL,
    [amount_refunded]                                 DECIMAL (12, 4) NULL,
    [applied_rule_ids]                                NVARCHAR (255)  NULL,
    [base_amount_refunded]                            DECIMAL (12, 4) NULL,
    [base_cost]                                       DECIMAL (12, 4) NULL,
    [base_discount_amount]                            DECIMAL (12, 4) NULL,
    [base_discount_invoiced]                          DECIMAL (12, 4) NULL,
    [base_discount_refunded]                          DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount]           DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_invoiced]         DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_refunded]         DECIMAL (12, 4) NULL,
    [base_original_price]                             DECIMAL (12, 4) NULL,
    [base_price]                                      DECIMAL (12, 4) NULL,
    [base_price_incl_tax]                             DECIMAL (12, 4) NULL,
    [base_row_invoiced]                               DECIMAL (12, 4) NULL,
    [base_row_total]                                  DECIMAL (12, 4) NULL,
    [base_row_total_incl_tax]                         DECIMAL (12, 4) NULL,
    [base_tax_amount]                                 DECIMAL (12, 4) NULL,
    [base_tax_before_discount]                        DECIMAL (12, 4) NULL,
    [base_tax_invoiced]                               DECIMAL (12, 4) NULL,
    [bucks_per_quantity]                              DECIMAL (16, 6) NULL,
    [created_at]                                      DATETIME        NULL,
    [created_dim_date_key]                            CHAR (8)        NULL,
    [created_dim_time_key]                            CHAR (8)        NULL,
    [d_magento_sales_order_bk_hash]                   CHAR (32)       NULL,
    [dim_club_key]                                    CHAR (32)       NULL,
    [dim_magento_product_key]                         CHAR (32)       NULL,
    [dim_mms_product_key]                             CHAR (32)       NULL,
    [discount_amount]                                 DECIMAL (12, 4) NULL,
    [discount_invoiced]                               DECIMAL (12, 4) NULL,
    [discount_percent]                                DECIMAL (12, 4) NULL,
    [discount_refunded]                               DECIMAL (12, 4) NULL,
    [discount_tax_compensation_amount]                DECIMAL (12, 4) NULL,
    [discount_tax_compensation_canceled]              DECIMAL (12, 4) NULL,
    [discount_tax_compensation_invoiced]              DECIMAL (12, 4) NULL,
    [discount_tax_compensation_refunded]              DECIMAL (12, 4) NULL,
    [email_template_id]                               INT             NULL,
    [event_id]                                        INT             NULL,
    [ext_order_item_id]                               NVARCHAR (255)  NULL,
    [fact_magento_order_key]                          VARCHAR (32)    NULL,
    [free_shipping]                                   INT             NULL,
    [gift_message_available]                          INT             NULL,
    [gift_message_id]                                 INT             NULL,
    [gift_registry_item_id]                           INT             NULL,
    [gw_id]                                           INT             NULL,
    [is_qty_decimal]                                  CHAR (1)        NULL,
    [is_virtual_flag]                                 CHAR (1)        NULL,
    [locked_do_invoice]                               INT             NULL,
    [locked_do_ship]                                  INT             NULL,
    [m1_order_item_id]                                INT             NULL,
    [name]                                            NVARCHAR (255)  NULL,
    [no_discount]                                     INT             NULL,
    [original_price]                                  DECIMAL (12, 4) NULL,
    [parent_fact_magento_order_item_key]              VARCHAR (32)    NULL,
    [parent_item_id]                                  INT             NULL,
    [price]                                           DECIMAL (12, 4) NULL,
    [price_incl_tax]                                  DECIMAL (12, 4) NULL,
    [qty_backordered]                                 DECIMAL (12, 4) NULL,
    [qty_invoiced]                                    DECIMAL (12, 4) NULL,
    [qty_ordered]                                     DECIMAL (12, 4) NULL,
    [qty_refunded]                                    DECIMAL (12, 4) NULL,
    [qty_returned]                                    DECIMAL (12, 4) NULL,
    [qty_shipped]                                     DECIMAL (12, 4) NULL,
    [quote_item_id]                                   INT             NULL,
    [refund_bucks_per_quantity]                       DECIMAL (16, 6) NULL,
    [row_invoiced]                                    DECIMAL (12, 4) NULL,
    [row_total]                                       DECIMAL (12, 4) NULL,
    [row_total_incl_tax]                              DECIMAL (12, 4) NULL,
    [row_weight]                                      DECIMAL (12, 4) NULL,
    [sales_order_item_agreement_api_status]           INT             NULL,
    [sales_order_item_agreement_status]               INT             NULL,
    [sales_order_item_base_tax_refunded]              DECIMAL (12, 4) NULL,
    [sales_order_item_base_weee_tax_applied_amount]   DECIMAL (12, 4) NULL,
    [sales_order_item_base_weee_tax_applied_row_amnt] DECIMAL (12, 4) NULL,
    [sales_order_item_base_weee_tax_disposition]      DECIMAL (12, 4) NULL,
    [sales_order_item_base_weee_tax_row_disposition]  DECIMAL (12, 4) NULL,
    [sales_order_item_lt_bucks_redeemed]              INT             NULL,
    [sales_order_item_lt_bucks_refunded]              INT             NULL,
    [sales_order_item_product_options]                NVARCHAR (255)  NULL,
    [sales_order_item_product_type]                   NVARCHAR (255)  NULL,
    [sales_order_item_qty_canceled]                   DECIMAL (12, 4) NULL,
    [sku]                                             NVARCHAR (255)  NULL,
    [store_id]                                        INT             NULL,
    [tax_amount]                                      DECIMAL (12, 4) NULL,
    [tax_before_discount]                             DECIMAL (12, 4) NULL,
    [tax_canceled]                                    DECIMAL (12, 4) NULL,
    [tax_invoiced]                                    DECIMAL (12, 4) NULL,
    [tax_percent]                                     DECIMAL (12, 4) NULL,
    [tax_refunded]                                    DECIMAL (12, 4) NULL,
    [updated_at]                                      DATETIME        NULL,
    [updated_dim_date_key]                            CHAR (8)        NULL,
    [updated_dim_time_key]                            CHAR (8)        NULL,
    [vendor]                                          INT             NULL,
    [wd_cost_center_id]                               INT             NULL,
    [wd_offering_id]                                  INT             NULL,
    [wd_region_id]                                    INT             NULL,
    [wd_revenue_id]                                   INT             NULL,
    [wd_spending_id]                                  INT             NULL,
    [weight]                                          DECIMAL (12, 4) NULL,
    [p_magento_sales_order_item_id]                   BIGINT          NOT NULL,
    [deleted_flag]                                    INT             NULL,
    [dv_load_date_time]                               DATETIME        NULL,
    [dv_load_end_date_time]                           DATETIME        NULL,
    [dv_batch_id]                                     BIGINT          NOT NULL,
    [dv_inserted_date_time]                           DATETIME        NOT NULL,
    [dv_insert_user]                                  VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                            DATETIME        NULL,
    [dv_update_user]                                  VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

