CREATE TABLE [dbo].[d_magento_sales_credit_memo] (
    [d_magento_sales_credit_memo_id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                        CHAR (32)       NOT NULL,
    [entity_id]                                      INT             NULL,
    [adjustment_positive]                            DECIMAL (12, 4) NULL,
    [allocated_month_starting_dim_date_key]          VARCHAR (32)    NULL,
    [allocated_recalculate_through_datetime]         DATETIME        NULL,
    [allocated_recalculate_through_dim_date_key]     VARCHAR (8)     NULL,
    [base_adjustment]                                DECIMAL (12, 4) NULL,
    [base_adjustment_negative]                       DECIMAL (12, 4) NULL,
    [base_discount_amount]                           DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount]          DECIMAL (12, 4) NULL,
    [base_shipping_amount]                           DECIMAL (12, 4) NULL,
    [base_shipping_discount_tax_compensation_amnt]   DECIMAL (12, 4) NULL,
    [base_shipping_incl_tax]                         DECIMAL (12, 4) NULL,
    [base_shipping_tax_amount]                       DECIMAL (12, 4) NULL,
    [base_subtotal]                                  DECIMAL (12, 4) NULL,
    [base_subtotal_incl_tax]                         DECIMAL (12, 4) NULL,
    [base_to_global_rate]                            DECIMAL (12, 4) NULL,
    [base_to_order_rate]                             DECIMAL (12, 4) NULL,
    [billing_address_id]                             INT             NULL,
    [bs_customer_bal_total_refunded]                 DECIMAL (12, 4) NULL,
    [created_at]                                     DATETIME        NULL,
    [created_dim_date_key]                           CHAR (8)        NULL,
    [created_dim_time_key]                           CHAR (8)        NULL,
    [d_magento_sales_order_entity_bk_hash]           CHAR (32)       NULL,
    [discount_amount]                                DECIMAL (12, 4) NULL,
    [discount_tax_compensation_amount]               DECIMAL (12, 4) NULL,
    [fact_magento_invoice_key]                       VARCHAR (32)    NULL,
    [fact_magento_order_key]                         VARCHAR (32)    NULL,
    [fact_magento_payment_key]                       VARCHAR (32)    NULL,
    [increment_id]                                   VARCHAR (50)    NULL,
    [invoice_id]                                     INT             NULL,
    [sales_credit_memo_adjustment]                   DECIMAL (12, 4) NULL,
    [sales_credit_memo_adjustment_negative]          DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_adjustment_positive]     DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_currency_code]           VARCHAR (3)     NULL,
    [sales_credit_memo_base_customer_balance_amount] DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_gift_cards_amount]       DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_grand_total]             DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_reward_currency_amount]  DECIMAL (12, 4) NULL,
    [sales_credit_memo_base_tax_amount]              DECIMAL (12, 4) NULL,
    [sales_credit_memo_credit_memo_status]           INT             NULL,
    [sales_credit_memo_customer_bal_total_refunded]  DECIMAL (12, 4) NULL,
    [sales_credit_memo_customer_balance_amount]      DECIMAL (12, 4) NULL,
    [sales_credit_memo_discount_description]         VARCHAR (255)   NULL,
    [sales_credit_memo_email_sent]                   INT             NULL,
    [sales_credit_memo_gift_cards_amount]            DECIMAL (12, 4) NULL,
    [sales_credit_memo_global_currency_code]         VARCHAR (3)     NULL,
    [sales_credit_memo_grand_total]                  DECIMAL (12, 4) NULL,
    [sales_credit_memo_order_currency_code]          VARCHAR (3)     NULL,
    [sales_credit_memo_reward_currency_amount]       DECIMAL (12, 4) NULL,
    [sales_credit_memo_reward_points_balance]        INT             NULL,
    [sales_credit_memo_reward_points_balance_refund] INT             NULL,
    [sales_credit_memo_send_email]                   INT             NULL,
    [sales_credit_memo_shipping_amount]              DECIMAL (12, 4) NULL,
    [sales_credit_memo_shipping_tax_amount]          DECIMAL (12, 4) NULL,
    [sales_credit_memo_state]                        INT             NULL,
    [sales_credit_memo_store_currency_code]          VARCHAR (3)     NULL,
    [sales_credit_memo_subtotal]                     DECIMAL (12, 4) NULL,
    [sales_credit_memo_subtotal_incl_tax]            DECIMAL (12, 4) NULL,
    [sales_credit_memo_tax_amount]                   DECIMAL (12, 4) NULL,
    [shipping_address_id]                            INT             NULL,
    [shipping_discount_tax_compensation_amount]      DECIMAL (12, 4) NULL,
    [shipping_incl_tax]                              DECIMAL (12, 4) NULL,
    [store_id]                                       INT             NULL,
    [store_to_base_rate]                             DECIMAL (12, 4) NULL,
    [store_to_order_rate]                            DECIMAL (12, 4) NULL,
    [transaction_id]                                 VARCHAR (255)   NULL,
    [updated_at]                                     DATETIME        NULL,
    [updated_dim_date_key]                           CHAR (8)        NULL,
    [updated_dim_time_key]                           CHAR (8)        NULL,
    [p_magento_sales_credit_memo_id]                 BIGINT          NOT NULL,
    [deleted_flag]                                   INT             NULL,
    [dv_load_date_time]                              DATETIME        NULL,
    [dv_load_end_date_time]                          DATETIME        NULL,
    [dv_batch_id]                                    BIGINT          NOT NULL,
    [dv_inserted_date_time]                          DATETIME        NOT NULL,
    [dv_insert_user]                                 VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                           DATETIME        NULL,
    [dv_update_user]                                 VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

