CREATE TABLE [dbo].[d_magento_sales_order_payment] (
    [d_magento_sales_order_payment_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [fact_magento_sales_order_payment_key] CHAR (32)       NULL,
    [entity_id]                            INT             NULL,
    [amount_authorized]                    DECIMAL (12, 4) NULL,
    [amount_canceled]                      DECIMAL (12, 4) NULL,
    [amount_ordered]                       DECIMAL (12, 4) NULL,
    [amount_paid]                          DECIMAL (12, 4) NULL,
    [amount_refunded]                      DECIMAL (12, 4) NULL,
    [base_amount_authorized]               DECIMAL (12, 4) NULL,
    [base_amount_canceled]                 DECIMAL (12, 4) NULL,
    [base_amount_ordered]                  DECIMAL (12, 4) NULL,
    [base_amount_paid]                     DECIMAL (12, 4) NULL,
    [base_amount_paid_online]              DECIMAL (12, 4) NULL,
    [base_amount_refunded]                 DECIMAL (12, 4) NULL,
    [base_amount_refunded_online]          DECIMAL (12, 4) NULL,
    [base_shipping_amount]                 DECIMAL (12, 4) NULL,
    [base_shipping_captured]               DECIMAL (12, 4) NULL,
    [base_shipping_refunded]               DECIMAL (12, 4) NULL,
    [batch_number]                         VARCHAR (50)    NULL,
    [cc_last_4]                            INT             NULL,
    [cc_type]                              VARCHAR (32)    NULL,
    [credit_tran_id]                       VARCHAR (50)    NULL,
    [fact_magento_sales_order_key]         CHAR (32)       NULL,
    [last_trans_id]                        VARCHAR (32)    NULL,
    [method]                               VARCHAR (128)   NULL,
    [quote_payment_id]                     INT             NULL,
    [shipping_captured]                    DECIMAL (12, 4) NULL,
    [shipping_refunded]                    DECIMAL (12, 4) NULL,
    [p_magento_sales_order_payment_id]     BIGINT          NOT NULL,
    [deleted_flag]                         INT             NULL,
    [dv_load_date_time]                    DATETIME        NULL,
    [dv_load_end_date_time]                DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

