CREATE TABLE [dbo].[d_magento_customer_address_entity] (
    [d_magento_customer_address_entity_id]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                  CHAR (32)      NOT NULL,
    [customer_address_id]                      INT            NULL,
    [city]                                     VARCHAR (255)  NULL,
    [company]                                  VARCHAR (255)  NULL,
    [country_id]                               VARCHAR (255)  NULL,
    [created_dim_date_key]                     CHAR (8)       NULL,
    [created_dim_time_key]                     CHAR (8)       NULL,
    [fax]                                      VARCHAR (255)  NULL,
    [first_name]                               VARCHAR (255)  NULL,
    [increment_id]                             VARCHAR (50)   NULL,
    [is_active_flag]                           CHAR (1)       NULL,
    [last_name]                                VARCHAR (255)  NULL,
    [m1_customer_address_id]                   INT            NULL,
    [middle_name]                              VARCHAR (255)  NULL,
    [parent_d_magento_customer_entity_bk_hash] CHAR (32)      NULL,
    [post_code]                                VARCHAR (255)  NULL,
    [prefix]                                   VARCHAR (40)   NULL,
    [region]                                   VARCHAR (255)  NULL,
    [region_id]                                INT            NULL,
    [street]                                   VARCHAR (8000) NULL,
    [suffix]                                   VARCHAR (40)   NULL,
    [telephone]                                VARCHAR (255)  NULL,
    [updated_dim_date_key]                     CHAR (8)       NULL,
    [updated_dim_time_key]                     CHAR (8)       NULL,
    [p_magento_customer_address_entity_id]     BIGINT         NOT NULL,
    [deleted_flag]                             INT            NULL,
    [dv_load_date_time]                        DATETIME       NULL,
    [dv_load_end_date_time]                    DATETIME       NULL,
    [dv_batch_id]                              BIGINT         NOT NULL,
    [dv_inserted_date_time]                    DATETIME       NOT NULL,
    [dv_insert_user]                           VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                     DATETIME       NULL,
    [dv_update_user]                           VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

