CREATE TABLE [dbo].[d_mms_membership_type_history] (
    [d_mms_membership_type_history_id]                  BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                           CHAR (32)     NOT NULL,
    [dim_mms_membership_type_key]                       VARCHAR (255) NULL,
    [membership_type_id]                                INT           NULL,
    [effective_date_time]                               DATETIME      NULL,
    [expiration_date_time]                              DATETIME      NULL,
    [allow_partner_program_flag]                        CHAR (1)      NULL,
    [assess_dues_flag]                                  CHAR (1)      NULL,
    [assess_junior_member_dues_flag]                    CHAR (1)      NULL,
    [check_in_group_dim_description_key]                VARCHAR (255) NULL,
    [dim_mms_product_key]                               VARCHAR (32)  NULL,
    [display_name]                                      VARCHAR (50)  NULL,
    [enrollment_type_dim_description_key]               VARCHAR (255) NULL,
    [express_membership_flag]                           CHAR (1)      NULL,
    [gta_signature_override]                            VARCHAR (100) NULL,
    [membership_type_family_status_dim_description_key] VARCHAR (255) NULL,
    [membership_type_group_dim_description_key]         VARCHAR (255) NULL,
    [pricing_method_dim_description_key]                VARCHAR (255) NULL,
    [pricing_rule_dim_description_key]                  VARCHAR (255) NULL,
    [primary_age_minimum]                               INT           NULL,
    [product_id]                                        INT           NULL,
    [restricted_group_dim_description_key]              VARCHAR (255) NULL,
    [short_term_membership_flag]                        CHAR (1)      NULL,
    [suppress_membership_card_flag]                     CHAR (1)      NULL,
    [unit_type_dim_description_key]                     VARCHAR (255) NULL,
    [unit_type_maximum]                                 INT           NULL,
    [unit_type_minimum]                                 INT           NULL,
    [val_check_in_group_id]                             INT           NULL,
    [val_enrollment_type_id]                            INT           NULL,
    [val_membership_type_family_status_id]              INT           NULL,
    [val_membership_type_group_id]                      INT           NULL,
    [val_pricing_method_id]                             INT           NULL,
    [val_pricing_rule_id]                               INT           NULL,
    [val_restricted_group_id]                           INT           NULL,
    [val_unit_type_id]                                  INT           NULL,
    [val_welcome_kit_type_id]                           INT           NULL,
    [waive_admin_fee_flag]                              CHAR (1)      NULL,
    [waive_late_fee_flag]                               CHAR (1)      NULL,
    [welcome_kit_type_dim_description_key]              VARCHAR (255) NULL,
    [p_mms_membership_type_id]                          BIGINT        NOT NULL,
    [deleted_flag]                                      INT           NULL,
    [dv_load_date_time]                                 DATETIME      NULL,
    [dv_load_end_date_time]                             DATETIME      NULL,
    [dv_batch_id]                                       BIGINT        NOT NULL,
    [dv_inserted_date_time]                             DATETIME      NOT NULL,
    [dv_insert_user]                                    VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                              DATETIME      NULL,
    [dv_update_user]                                    VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

