CREATE TABLE [dbo].[d_mms_membership_message_history] (
    [d_mms_membership_message_history_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)      NOT NULL,
    [membership_message_id]               INT            NULL,
    [close_club_id]                       INT            NULL,
    [close_date_time]                     DATETIME       NULL,
    [close_date_time_zone]                VARCHAR (4)    NULL,
    [close_employee_id]                   INT            NULL,
    [comment]                             VARCHAR (2000) NULL,
    [inserted_date_time]                  DATETIME       NULL,
    [membership_id]                       INT            NULL,
    [open_club_id]                        INT            NULL,
    [open_date_time]                      DATETIME       NULL,
    [open_date_time_zone]                 VARCHAR (4)    NULL,
    [open_employee_id]                    INT            NULL,
    [received_date_time]                  DATETIME       NULL,
    [received_date_time_zone]             VARCHAR (4)    NULL,
    [updated_date_time]                   DATETIME       NULL,
    [utc_close_date_time]                 DATETIME       NULL,
    [utc_open_date_time]                  DATETIME       NULL,
    [utc_received_date_time]              DATETIME       NULL,
    [val_membership_message_type_id]      INT            NULL,
    [val_message_status_id]               INT            NULL,
    [p_mms_membership_message_id]         BIGINT         NOT NULL,
    [deleted_flag]                        INT            NULL,
    [dv_load_date_time]                   DATETIME       NULL,
    [dv_load_end_date_time]               DATETIME       NULL,
    [dv_batch_id]                         BIGINT         NOT NULL,
    [dv_inserted_date_time]               DATETIME       NOT NULL,
    [dv_insert_user]                      VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                DATETIME       NULL,
    [dv_update_user]                      VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

