CREATE TABLE [dbo].[d_mms_package] (
    [d_mms_package_id]                    BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)      NOT NULL,
    [fact_mms_package_key]                CHAR (32)      NULL,
    [package_id]                          INT            NULL,
    [balance_amount]                      NUMERIC (9, 4) NULL,
    [club_id]                             INT            NULL,
    [created_date_time]                   DATETIME       NULL,
    [created_dim_date_key]                CHAR (8)       NULL,
    [created_dim_time_key]                CHAR (8)       NULL,
    [dim_club_key]                        CHAR (32)      NULL,
    [dim_mms_member_key]                  CHAR (32)      NULL,
    [dim_mms_membership_key]              CHAR (32)      NULL,
    [dim_mms_product_key]                 CHAR (32)      NULL,
    [employee_id]                         INT            NULL,
    [external_package_id]                 VARCHAR (50)   NULL,
    [fact_mms_sales_transaction_item_key] CHAR (32)      NULL,
    [fact_mms_sales_transaction_key]      CHAR (32)      NULL,
    [inserted_date_time]                  DATETIME       NULL,
    [inserted_dim_date_key]               CHAR (8)       NULL,
    [inserted_dim_time_key]               CHAR (8)       NULL,
    [mms_tran_id]                         INT            NULL,
    [number_of_sessions]                  SMALLINT       NULL,
    [package_edit_date_time]              DATETIME       NULL,
    [package_edit_dim_date_key]           CHAR (8)       NULL,
    [package_edit_dim_time_key]           CHAR (8)       NULL,
    [package_edited_flag]                 CHAR (1)       NULL,
    [package_entered_dim_employee_key]    CHAR (32)      NULL,
    [package_entered_dim_team_member_key] CHAR (32)      NULL,
    [package_status_dim_description_key]  VARCHAR (255)  NULL,
    [price_per_session]                   NUMERIC (9, 4) NULL,
    [sessions_remaining]                  INT            NULL,
    [tran_item_id]                        INT            NULL,
    [transaction_source]                  VARCHAR (50)   NULL,
    [updated_date_time]                   DATETIME       NULL,
    [updated_dim_date_key]                CHAR (8)       NULL,
    [updated_dim_time_key]                CHAR (8)       NULL,
    [val_package_status_id]               INT            NULL,
    [p_mms_package_id]                    BIGINT         NOT NULL,
    [deleted_flag]                        INT            NULL,
    [dv_load_date_time]                   DATETIME       NULL,
    [dv_load_end_date_time]               DATETIME       NULL,
    [dv_batch_id]                         BIGINT         NOT NULL,
    [dv_inserted_date_time]               DATETIME       NOT NULL,
    [dv_insert_user]                      VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                DATETIME       NULL,
    [dv_update_user]                      VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

