CREATE TABLE [dbo].[d_mms_mms_tran] (
    [d_mms_mms_tran_id]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)       NOT NULL,
    [fact_mms_sales_transaction_key]          CHAR (32)       NULL,
    [mms_tran_id]                             INT             NULL,
    [club_id]                                 INT             NULL,
    [dim_club_key]                            CHAR (32)       NULL,
    [dim_mms_drawer_activity_key]             VARCHAR (32)    NULL,
    [dim_mms_member_key]                      CHAR (32)       NULL,
    [dim_mms_membership_key]                  CHAR (32)       NULL,
    [dim_mms_reimbursement_program_key]       CHAR (32)       NULL,
    [dim_mms_transaction_reason_key]          CHAR (32)       NULL,
    [domain_name]                             VARCHAR (50)    NULL,
    [employee_id]                             INT             NULL,
    [inserted_dim_date_key]                   VARCHAR (8)     NULL,
    [inserted_dim_time_key]                   INT             NULL,
    [member_id]                               INT             NULL,
    [membership_adjustment_flag]              CHAR (1)        NULL,
    [membership_charge_flag]                  CHAR (1)        NULL,
    [membership_id]                           INT             NULL,
    [mms_tran_voided_bk_hash]                 CHAR (32)       NULL,
    [month_ending_post_dim_date_key]          CHAR (8)        NULL,
    [original_currency_code]                  CHAR (3)        NULL,
    [original_fact_mms_sales_transaction_key] CHAR (32)       NULL,
    [original_mms_tran_id]                    INT             NULL,
    [pos_amount]                              DECIMAL (26, 6) NULL,
    [pos_flag]                                CHAR (1)        NULL,
    [post_date_time]                          DATETIME        NULL,
    [post_dim_date_key]                       CHAR (8)        NULL,
    [post_dim_time_key]                       INT             NULL,
    [receipt_comment]                         VARCHAR (255)   NULL,
    [receipt_number]                          VARCHAR (50)    NULL,
    [refund_flag]                             CHAR (1)        NULL,
    [reversal_flag]                           CHAR (1)        NULL,
    [sales_entered_dim_employee_key]          CHAR (32)       NULL,
    [tran_amount]                             DECIMAL (26, 6) NULL,
    [tran_date]                               DATETIME        NULL,
    [tran_dim_date_key]                       CHAR (8)        NULL,
    [tran_voided_id]                          INT             NULL,
    [transaction_edited_flag]                 CHAR (1)        NULL,
    [transaction_entered_dim_employee_key]    CHAR (32)       NULL,
    [updated_date_time]                       DATETIME        NULL,
    [val_currency_code_id]                    INT             NULL,
    [val_tran_type_id]                        INT             NULL,
    [voided_flag]                             CHAR (1)        NULL,
    [p_mms_mms_tran_id]                       BIGINT          NOT NULL,
    [deleted_flag]                            INT             NULL,
    [dv_load_date_time]                       DATETIME        NULL,
    [dv_load_end_date_time]                   DATETIME        NULL,
    [dv_batch_id]                             BIGINT          NOT NULL,
    [dv_inserted_date_time]                   DATETIME        NOT NULL,
    [dv_insert_user]                          VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                    DATETIME        NULL,
    [dv_update_user]                          VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

