CREATE TABLE [dbo].[d_mms_membership] (
    [d_mms_membership_id]                              BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                          CHAR (32)       NOT NULL,
    [dim_mms_membership_key]                           CHAR (32)       NULL,
    [membership_id]                                    INT             NULL,
    [advisor_employee_id]                              INT             NULL,
    [club_id]                                          INT             NULL,
    [company_id]                                       INT             NULL,
    [created_date_time]                                DATETIME        NULL,
    [created_date_time_key]                            CHAR (8)        NULL,
    [crm_opportunity_id]                               VARCHAR (36)    NULL,
    [current_price]                                    DECIMAL (26, 6) NULL,
    [dim_crm_opportunity_key]                          CHAR (32)       NULL,
    [dim_mms_company_key]                              CHAR (32)       NULL,
    [dim_mms_membership_type_key]                      CHAR (32)       NULL,
    [eft_option_dim_description_key]                   VARCHAR (532)   NULL,
    [enrollment_type_dim_description_key]              VARCHAR (532)   NULL,
    [home_dim_club_key]                                CHAR (32)       NULL,
    [membership_activation_date]                       DATETIME        NULL,
    [membership_cancellation_request_date]             DATETIME        NULL,
    [membership_created_date_time]                     DATETIME        NULL,
    [membership_created_dim_date_key]                  INT             NULL,
    [membership_expiration_date]                       DATETIME        NULL,
    [membership_source_dim_description_key]            VARCHAR (532)   NULL,
    [membership_status_dim_description_key]            VARCHAR (532)   NULL,
    [membership_type_id]                               INT             NULL,
    [non_payment_termination_flag]                     CHAR (1)        NULL,
    [original_sales_dim_employee_key]                  CHAR (32)       NULL,
    [prior_plus_dim_membership_type_key]               CHAR (32)       NULL,
    [prior_plus_membership_type_id]                    INT             NULL,
    [prior_plus_price]                                 DECIMAL (26, 6) NULL,
    [prior_plus_undiscounted_price]                    DECIMAL (26, 6) NULL,
    [termination_reason_club_type_dim_description_key] VARCHAR (532)   NULL,
    [termination_reason_dim_description_key]           VARCHAR (532)   NULL,
    [undiscounted_price]                               DECIMAL (26, 6) NULL,
    [val_eft_option_id]                                INT             NULL,
    [val_enrollment_type_id]                           INT             NULL,
    [val_membership_source_id]                         INT             NULL,
    [val_membership_status_id]                         INT             NULL,
    [val_termination_reason_club_type_id]              INT             NULL,
    [val_termination_reason_id]                        INT             NULL,
    [p_mms_membership_id]                              BIGINT          NOT NULL,
    [deleted_flag]                                     INT             NULL,
    [dv_load_date_time]                                DATETIME        NULL,
    [dv_load_end_date_time]                            DATETIME        NULL,
    [dv_batch_id]                                      BIGINT          NOT NULL,
    [dv_inserted_date_time]                            DATETIME        NOT NULL,
    [dv_insert_user]                                   VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                             DATETIME        NULL,
    [dv_update_user]                                   VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

