CREATE TABLE [dbo].[d_mms_membership_recurrent_product] (
    [d_mms_membership_recurrent_product_id]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)       NOT NULL,
    [fact_mms_membership_recurrent_product_key]    CHAR (32)       NULL,
    [membership_recurrent_product_id]              INT             NULL,
    [activation_dim_date_key]                      CHAR (8)        NULL,
    [cancellation_request_dim_date_key]            CHAR (8)        NULL,
    [club_id]                                      INT             NULL,
    [comments]                                     VARCHAR (255)   NULL,
    [commission_dim_mms_employee_key]              VARCHAR (32)    NULL,
    [commission_employee_id]                       INT             NULL,
    [created_date_time_zone]                       VARCHAR (4)     NULL,
    [created_dim_date_key]                         VARCHAR (8)     NULL,
    [created_dim_time_key]                         INT             NULL,
    [dim_club_key]                                 CHAR (32)       NULL,
    [dim_mms_member_key]                           CHAR (32)       NULL,
    [dim_mms_pricing_discount_key]                 VARCHAR (32)    NULL,
    [dim_mms_product_key]                          CHAR (32)       NULL,
    [display_only_flag]                            CHAR (1)        NULL,
    [hold_end_dim_date_key]                        CHAR (8)        NULL,
    [hold_start_dim_date_key]                      CHAR (8)        NULL,
    [inserted_dim_date_key]                        VARCHAR (8)     NULL,
    [inserted_dim_time_key]                        INT             NULL,
    [last_assessment_dim_date_key]                 CHAR (8)        NULL,
    [last_updated_date_time_zone]                  VARCHAR (4)     NULL,
    [last_updated_dim_date_key]                    VARCHAR (8)     NULL,
    [last_updated_dim_employee_key]                VARCHAR (32)    NULL,
    [last_updated_dim_time_key]                    INT             NULL,
    [last_updated_employee_id]                     INT             NULL,
    [membership_id]                                INT             NULL,
    [number_of_sessions]                           INT             NULL,
    [price]                                        DECIMAL (26, 6) NULL,
    [price_per_session]                            NUMERIC (7, 2)  NULL,
    [pricing_discount_id]                          INT             NULL,
    [promotion_code]                               VARCHAR (50)    NULL,
    [recurrent_product_source_dim_description_key] VARCHAR (500)   NULL,
    [retail_price]                                 DECIMAL (26, 6) NULL,
    [retail_price_per_session]                     DECIMAL (26, 6) NULL,
    [sold_not_serviced_flag]                       CHAR (1)        NULL,
    [termination_dim_date_key]                     CHAR (8)        NULL,
    [termination_reason_dim_description_key]       VARCHAR (500)   NULL,
    [updated_dim_date_key]                         VARCHAR (8)     NULL,
    [updated_dim_time_key]                         INT             NULL,
    [utc_created_dim_date_key]                     VARCHAR (8)     NULL,
    [utc_created_dim_time_key]                     INT             NULL,
    [utc_last_updated_dim_date_key]                VARCHAR (8)     NULL,
    [utc_last_updated_dim_time_key]                INT             NULL,
    [val_assessment_day_id]                        INT             NULL,
    [val_discount_reason_id]                       SMALLINT        NULL,
    [val_recurrent_product_source_id]              INT             NULL,
    [val_recurrent_product_termination_reason_id]  INT             NULL,
    [p_mms_membership_recurrent_product_id]        BIGINT          NOT NULL,
    [deleted_flag]                                 INT             NULL,
    [dv_load_date_time]                            DATETIME        NULL,
    [dv_load_end_date_time]                        DATETIME        NULL,
    [dv_batch_id]                                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                        DATETIME        NOT NULL,
    [dv_insert_user]                               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                         DATETIME        NULL,
    [dv_update_user]                               VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

