CREATE TABLE [dbo].[d_mms_payment_refund] (
    [d_mms_payment_refund_id]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                            CHAR (32)     NOT NULL,
    [payment_refund_id]                  INT           NULL,
    [comment]                            VARCHAR (255) NULL,
    [fact_mms_payment_key]               VARCHAR (32)  NULL,
    [inserted_date_time]                 DATETIME      NULL,
    [inserted_dim_date_key]              VARCHAR (8)   NULL,
    [inserted_dim_time_key]              INT           NULL,
    [payment_id]                         INT           NULL,
    [payment_issued_date_time]           DATETIME      NULL,
    [payment_issued_dim_date_key]        VARCHAR (8)   NULL,
    [payment_issued_dim_time_key]        INT           NULL,
    [payment_status_dim_description_key] VARCHAR (255) NULL,
    [reference_number]                   VARCHAR (50)  NULL,
    [status_change_date_time]            DATETIME      NULL,
    [status_change_date_time_zone]       VARCHAR (4)   NULL,
    [status_change_dim_date_key]         VARCHAR (8)   NULL,
    [status_change_dim_employee_key]     VARCHAR (32)  NULL,
    [status_change_dim_time_key]         INT           NULL,
    [status_change_employee_id]          INT           NULL,
    [updated_date_time]                  DATETIME      NULL,
    [updated_dim_date_key]               VARCHAR (8)   NULL,
    [updated_dim_time_key]               INT           NULL,
    [utc_status_change_date_time]        DATETIME      NULL,
    [utc_status_change_dim_date_key]     VARCHAR (8)   NULL,
    [utc_status_change_dim_time_key]     INT           NULL,
    [val_payment_status_id]              INT           NULL,
    [p_mms_payment_refund_id]            BIGINT        NOT NULL,
    [deleted_flag]                       INT           NULL,
    [dv_load_date_time]                  DATETIME      NULL,
    [dv_load_end_date_time]              DATETIME      NULL,
    [dv_batch_id]                        BIGINT        NOT NULL,
    [dv_inserted_date_time]              DATETIME      NOT NULL,
    [dv_insert_user]                     VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]               DATETIME      NULL,
    [dv_update_user]                     VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

