CREATE TABLE [dbo].[d_mms_product_history] (
    [d_mms_product_history_id]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                  CHAR (32)      NOT NULL,
    [dim_mms_product_key]                      CHAR (32)      NULL,
    [product_id]                               INT            NULL,
    [effective_date_time]                      DATETIME       NULL,
    [expiration_date_time]                     DATETIME       NULL,
    [access_by_price_paid_flag]                CHAR (1)       NULL,
    [assess_as_dues_flag]                      CHAR (1)       NULL,
    [deferred_revenue_flag]                    CHAR (1)       NULL,
    [department_id]                            INT            NULL,
    [display_ui_flag]                          CHAR (1)       NULL,
    [exclude_from_club_POS_flag]               CHAR (1)       NULL,
    [gl_account_number]                        VARCHAR (10)   NULL,
    [gl_department_code]                       VARCHAR (7)    NULL,
    [gl_over_ride_club_id]                     INT            NULL,
    [gl_product_code]                          VARCHAR (10)   NULL,
    [junior_member_dues_flag]                  CHAR (1)       NULL,
    [lt_buck_cost_percent]                     NUMERIC (4, 1) NULL,
    [lt_buck_eligible_flag]                    CHAR (1)       NULL,
    [mms_department_bk_hash]                   CHAR (32)      NULL,
    [package_product_flag]                     CHAR (1)       NULL,
    [pay_component]                            VARCHAR (50)   NULL,
    [price_locked_flag]                        CHAR (1)       NULL,
    [product_description]                      VARCHAR (50)   NULL,
    [product_name]                             VARCHAR (20)   NULL,
    [r_mms_val_product_status_bk_hash]         CHAR (32)      NULL,
    [r_mms_val_recurrent_product_type_bk_hash] CHAR (32)      NULL,
    [revenue_category]                         VARCHAR (7)    NULL,
    [sales_quantity_factor]                    INT            NULL,
    [sku]                                      VARCHAR (50)   NULL,
    [spend_category]                           VARCHAR (7)    NULL,
    [tip_allowed_flag]                         CHAR (1)       NULL,
    [workday_account]                          VARCHAR (6)    NULL,
    [workday_cost_center]                      VARCHAR (6)    NULL,
    [workday_offering]                         VARCHAR (10)   NULL,
    [workday_over_ride_region]                 VARCHAR (4)    NULL,
    [workday_revenue_product_group_account]    VARCHAR (6)    NULL,
    [p_mms_product_id]                         BIGINT         NOT NULL,
    [deleted_flag]                             INT            NULL,
    [dv_load_date_time]                        DATETIME       NULL,
    [dv_load_end_date_time]                    DATETIME       NULL,
    [dv_batch_id]                              BIGINT         NOT NULL,
    [dv_inserted_date_time]                    DATETIME       NOT NULL,
    [dv_insert_user]                           VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                     DATETIME       NULL,
    [dv_update_user]                           VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

