CREATE TABLE [dbo].[d_mms_membership_modification_request] (
    [d_mms_membership_modification_request_id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                                    CHAR (32)       NOT NULL,
    [membership_modification_request_id]                         INT             NULL,
    [add_on_fee]                                                 DECIMAL (26, 6) NULL,
    [agreement_price]                                            DECIMAL (26, 6) NULL,
    [club_id]                                                    INT             NULL,
    [commisioned_dim_employee_key]                               VARCHAR (32)    NULL,
    [commisioned_employee_id]                                    INT             NULL,
    [deactivated_members]                                        VARCHAR (200)   NULL,
    [diamond_fee]                                                DECIMAL (26, 6) NULL,
    [dim_club_key]                                               VARCHAR (32)    NULL,
    [dim_employee_key]                                           VARCHAR (32)    NULL,
    [dim_mms_member_key]                                         VARCHAR (32)    NULL,
    [dim_mms_membership_key]                                     VARCHAR (32)    NULL,
    [dim_mms_membership_type_key]                                VARCHAR (32)    NULL,
    [effective_date]                                             DATETIME        NULL,
    [effective_dim_date_key]                                     VARCHAR (8)     NULL,
    [effective_dim_time_key]                                     INT             NULL,
    [employee_id]                                                INT             NULL,
    [first_months_dues]                                          DECIMAL (26, 6) NULL,
    [flex_reason_dim_description_key]                            VARCHAR (255)   NULL,
    [full_access_date_extension_flag]                            CHAR (1)        NULL,
    [future_membership_upgrade_flag]                             CHAR (1)        NULL,
    [inserted_date_time]                                         DATETIME        NULL,
    [inserted_dim_date_key]                                      VARCHAR (8)     NULL,
    [inserted_dim_time_key]                                      INT             NULL,
    [juniors_assessed]                                           INT             NULL,
    [last_eft_month]                                             VARCHAR (9)     NULL,
    [member_agreement_staging_id]                                INT             NULL,
    [member_freeze_flag]                                         CHAR (1)        NULL,
    [member_id]                                                  INT             NULL,
    [membership_id]                                              INT             NULL,
    [membership_modification_request_source_dim_description_key] VARCHAR (255)   NULL,
    [membership_modification_request_status_dim_description_key] VARCHAR (255)   NULL,
    [membership_modification_request_type_dim_description_key]   VARCHAR (255)   NULL,
    [membership_type_id]                                         INT             NULL,
    [membership_upgrade_date_range_dim_description_key]          VARCHAR (255)   NULL,
    [membership_upgrade_month_year]                              DATETIME        NULL,
    [new_members]                                                VARCHAR (200)   NULL,
    [new_primary_id]                                             INT             NULL,
    [previous_dim_mms_membership_type_key]                       VARCHAR (32)    NULL,
    [previous_membership_type_id]                                INT             NULL,
    [pro_rated_dues]                                             DECIMAL (26, 6) NULL,
    [request_date_time]                                          DATETIME        NULL,
    [request_date_time_zone]                                     VARCHAR (4)     NULL,
    [request_dim_date_key]                                       VARCHAR (8)     NULL,
    [request_dim_time_key]                                       INT             NULL,
    [service_fee]                                                DECIMAL (26, 6) NULL,
    [status_changed_date_time]                                   DATETIME        NULL,
    [status_changed_dim_date_key]                                VARCHAR (8)     NULL,
    [status_changed_dim_time_key]                                INT             NULL,
    [total_monthly_amount]                                       DECIMAL (26, 6) NULL,
    [undiscounted_price]                                         DECIMAL (26, 6) NULL,
    [updated_date_time]                                          DATETIME        NULL,
    [updated_dim_date_key]                                       VARCHAR (8)     NULL,
    [updated_dim_time_key]                                       INT             NULL,
    [utc_request_date_time]                                      DATETIME        NULL,
    [utc_request_dim_date_key]                                   VARCHAR (8)     NULL,
    [utc_request_dim_time_key]                                   INT             NULL,
    [val_flex_reason_id]                                         BIGINT          NULL,
    [val_membership_modification_request_source_id]              TINYINT         NULL,
    [val_membership_modification_request_status_id]              BIGINT          NULL,
    [val_membership_modification_request_type_id]                TINYINT         NULL,
    [val_membership_upgrade_date_range_id]                       BIGINT          NULL,
    [waive_service_fee_flag]                                     CHAR (1)        NULL,
    [p_mms_membership_modification_request_id]                   BIGINT          NOT NULL,
    [deleted_flag]                                               INT             NULL,
    [dv_load_date_time]                                          DATETIME        NULL,
    [dv_load_end_date_time]                                      DATETIME        NULL,
    [dv_batch_id]                                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                                      DATETIME        NOT NULL,
    [dv_insert_user]                                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                       DATETIME        NULL,
    [dv_update_user]                                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

