CREATE TABLE [dbo].[d_mms_eft_billing_request] (
    [d_mms_eft_billing_request_id]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                        CHAR (32)     NOT NULL,
    [eft_billing_request_id]         INT           NULL,
    [commission_employee]            VARCHAR (20)  NULL,
    [dim_club_key]                   VARCHAR (32)  NULL,
    [dim_exerp_subscription_key]     VARCHAR (32)  NULL,
    [dim_mms_member_key]             VARCHAR (32)  NULL,
    [dim_mms_product_key]            VARCHAR (32)  NULL,
    [external_item_id]               VARCHAR (20)  NULL,
    [external_package_id]            VARCHAR (50)  NULL,
    [fact_mms_package_key]           VARCHAR (32)  NULL,
    [fact_mms_sales_transaction_key] VARCHAR (32)  NULL,
    [file_name]                      VARCHAR (50)  NULL,
    [inserted_dim_date_key]          VARCHAR (8)   NULL,
    [inserted_dim_time_key]          INT           NULL,
    [message]                        VARCHAR (120) NULL,
    [original_external_item_id]      VARCHAR (20)  NULL,
    [payment_request_reference]      VARCHAR (50)  NULL,
    [product_price]                  VARCHAR (20)  NULL,
    [quantity]                       VARCHAR (20)  NULL,
    [response_code]                  VARCHAR (20)  NULL,
    [total_amount]                   VARCHAR (20)  NULL,
    [transaction_source]             VARCHAR (20)  NULL,
    [updated_dim_date_key]           VARCHAR (8)   NULL,
    [updated_dim_time_key]           INT           NULL,
    [p_mms_eft_billing_request_id]   BIGINT        NOT NULL,
    [deleted_flag]                   INT           NULL,
    [dv_load_date_time]              DATETIME      NULL,
    [dv_load_end_date_time]          DATETIME      NULL,
    [dv_batch_id]                    BIGINT        NOT NULL,
    [dv_inserted_date_time]          DATETIME      NOT NULL,
    [dv_insert_user]                 VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]           DATETIME      NULL,
    [dv_update_user]                 VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

