CREATE TABLE [dbo].[d_mms_sales_promotion_code] (
    [d_mms_sales_promotion_code_id]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)     NOT NULL,
    [sales_promotion_code_id]          INT           NULL,
    [dim_mms_member_key]               VARCHAR (32)  NULL,
    [dim_mms_sales_promotion_key]      VARCHAR (32)  NULL,
    [display_ui_flag]                  CHAR (1)      NULL,
    [expiration_dim_date_key]          VARCHAR (8)   NULL,
    [expiration_dim_time_key]          INT           NULL,
    [inserted_dim_date_key]            VARCHAR (8)   NULL,
    [inserted_dim_time_key]            INT           NULL,
    [member_id]                        INT           NULL,
    [notify_email_address]             VARCHAR (140) NULL,
    [number_of_code_recipients]        INT           NULL,
    [promotion_code]                   VARCHAR (50)  NULL,
    [sales_promotion_code_usage_limit] INT           NULL,
    [sales_promotion_id]               INT           NULL,
    [updated_dim_date_key]             VARCHAR (8)   NULL,
    [updated_dim_time_key]             INT           NULL,
    [p_mms_sales_promotion_code_id]    BIGINT        NOT NULL,
    [deleted_flag]                     INT           NULL,
    [dv_load_date_time]                DATETIME      NULL,
    [dv_load_end_date_time]            DATETIME      NULL,
    [dv_batch_id]                      BIGINT        NOT NULL,
    [dv_inserted_date_time]            DATETIME      NOT NULL,
    [dv_insert_user]                   VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]             DATETIME      NULL,
    [dv_update_user]                   VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

