CREATE TABLE [dbo].[d_mms_member_attribute] (
    [d_mms_member_attribute_id]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                   CHAR (32)     NOT NULL,
    [member_attribute_id]                       INT           NULL,
    [attribute_value]                           VARCHAR (50)  NULL,
    [dim_mms_member_key]                        VARCHAR (32)  NULL,
    [effective_from_date_time]                  DATETIME      NULL,
    [effective_from_dim_date_key]               VARCHAR (8)   NULL,
    [effective_from_dim_time_key]               INT           NULL,
    [effective_thru_date_time]                  DATETIME      NULL,
    [effective_thru_dim_date_key]               VARCHAR (8)   NULL,
    [effective_thru_dim_time_key]               INT           NULL,
    [expiration_date]                           DATETIME      NULL,
    [expiration_dim_date_key]                   VARCHAR (8)   NULL,
    [expiration_dim_time_key]                   INT           NULL,
    [inserted_date_time]                        DATETIME      NULL,
    [inserted_dim_date_key]                     VARCHAR (8)   NULL,
    [inserted_dim_time_key]                     INT           NULL,
    [member_attribute_type_dim_description_key] VARCHAR (255) NULL,
    [member_id]                                 INT           NULL,
    [updated_date_time]                         DATETIME      NULL,
    [updated_dim_date_key]                      VARCHAR (8)   NULL,
    [updated_dim_time_key]                      INT           NULL,
    [val_member_attribute_type_id]              INT           NULL,
    [p_mms_member_attribute_id]                 BIGINT        NOT NULL,
    [deleted_flag]                              INT           NULL,
    [dv_load_date_time]                         DATETIME      NULL,
    [dv_load_end_date_time]                     DATETIME      NULL,
    [dv_batch_id]                               BIGINT        NOT NULL,
    [dv_inserted_date_time]                     DATETIME      NOT NULL,
    [dv_insert_user]                            VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                      DATETIME      NULL,
    [dv_update_user]                            VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

