CREATE TABLE [dbo].[d_nmo_hub_task] (
    [d_nmo_hub_task_id]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)      NOT NULL,
    [dim_nmo_hub_task_key]            VARCHAR (32)   NULL,
    [hub_task_id]                     INT            NULL,
    [assignee_name]                   NVARCHAR (60)  NULL,
    [assignee_party_id]               INT            NULL,
    [created_date]                    DATETIME       NULL,
    [created_dim_date_key]            VARCHAR (8)    NULL,
    [created_dim_time_key]            INT            NULL,
    [creator_name]                    NVARCHAR (60)  NULL,
    [creator_party_id]                INT            NULL,
    [dim_club_key]                    VARCHAR (32)   NULL,
    [dim_nmo_hub_task_department_key] VARCHAR (32)   NULL,
    [dim_nmo_hub_task_status_key]     VARCHAR (32)   NULL,
    [dim_nmo_hub_task_type_key]       VARCHAR (32)   NULL,
    [due_date]                        DATETIME       NULL,
    [due_dim_date_key]                VARCHAR (8)    NULL,
    [due_dim_time_key]                INT            NULL,
    [party_id]                        INT            NULL,
    [priority]                        INT            NULL,
    [resolution_date]                 DATETIME       NULL,
    [resolution_dim_date_key]         VARCHAR (8)    NULL,
    [resolution_dim_time_key]         INT            NULL,
    [title]                           NVARCHAR (255) NULL,
    [updated_date]                    DATETIME       NULL,
    [updated_dim_date_key]            VARCHAR (8)    NULL,
    [updated_dim_time_key]            INT            NULL,
    [p_nmo_hub_task_id]               BIGINT         NOT NULL,
    [deleted_flag]                    INT            NULL,
    [dv_load_date_time]               DATETIME       NULL,
    [dv_load_end_date_time]           DATETIME       NULL,
    [dv_batch_id]                     BIGINT         NOT NULL,
    [dv_inserted_date_time]           DATETIME       NOT NULL,
    [dv_insert_user]                  VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]            DATETIME       NULL,
    [dv_update_user]                  VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

