CREATE TABLE [dbo].[d_qtest_jira] (
    [d_qtest_jira_id]                                                BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                                        CHAR (32)      NOT NULL,
    [dim_qtest_jira_key]                                             VARCHAR (32)   NULL,
    [test_case_id]                                                   VARCHAR (4000) NULL,
    [project_id]                                                     VARCHAR (4000) NULL,
    [release_id]                                                     VARCHAR (4000) NULL,
    [requirement_id]                                                 VARCHAR (4000) NULL,
    [project_automation]                                             VARCHAR (4000) NULL,
    [project_date_format]                                            VARCHAR (4000) NULL,
    [project_description]                                            VARCHAR (4000) NULL,
    [project_name]                                                   VARCHAR (4000) NULL,
    [project_sample]                                                 VARCHAR (4000) NULL,
    [project_start_date]                                             VARCHAR (4000) NULL,
    [project_start_dim_date_key]                                     VARCHAR (8)    NULL,
    [project_start_dim_time_key]                                     INT            NULL,
    [project_status_id]                                              VARCHAR (4000) NULL,
    [project_template_id]                                            VARCHAR (4000) NULL,
    [project_uuid]                                                   VARCHAR (4000) NULL,
    [project_x_explorer_access_level]                                VARCHAR (4000) NULL,
    [release_created_date]                                           VARCHAR (4000) NULL,
    [release_created_dim_date_key]                                   VARCHAR (8)    NULL,
    [release_created_dim_time_key]                                   INT            NULL,
    [release_end_date]                                               VARCHAR (4000) NULL,
    [release_end_dim_date_key]                                       VARCHAR (8)    NULL,
    [release_end_dim_time_key]                                       INT            NULL,
    [release_last_modified_date]                                     VARCHAR (4000) NULL,
    [release_last_modified_dim_date_key]                             VARCHAR (8)    NULL,
    [release_last_modified_dim_time_key]                             INT            NULL,
    [release_name]                                                   VARCHAR (4000) NULL,
    [release_order]                                                  VARCHAR (4000) NULL,
    [release_pid]                                                    VARCHAR (4000) NULL,
    [release_project_id]                                             VARCHAR (4000) NULL,
    [release_properties_end_date]                                    VARCHAR (4000) NULL,
    [release_properties_end_dim_date_key]                            VARCHAR (8)    NULL,
    [release_properties_end_dim_time_key]                            INT            NULL,
    [release_properties_start_date]                                  VARCHAR (4000) NULL,
    [release_properties_start_dim_date_key]                          VARCHAR (8)    NULL,
    [release_properties_start_dim_time_key]                          INT            NULL,
    [release_properties_status]                                      VARCHAR (4000) NULL,
    [release_start_date]                                             VARCHAR (4000) NULL,
    [release_start_dim_date_key]                                     VARCHAR (8)    NULL,
    [release_start_dim_time_key]                                     INT            NULL,
    [requirement_created_date]                                       VARCHAR (4000) NULL,
    [requirement_created_dim_date_key]                               VARCHAR (8)    NULL,
    [requirement_created_dim_time_key]                               INT            NULL,
    [requirement_jira_defect_id]                                     VARCHAR (4000) NULL,
    [requirement_jira_issue]                                         VARCHAR (4000) NULL,
    [requirement_jira_priority]                                      VARCHAR (4000) NULL,
    [requirement_jira_status]                                        VARCHAR (4000) NULL,
    [requirement_jira_story_point]                                   VARCHAR (4000) NULL,
    [requirement_last_modified_date]                                 VARCHAR (4000) NULL,
    [requirement_last_modified_dim_date_key]                         VARCHAR (8)    NULL,
    [requirement_last_modified_dim_time_key]                         INT            NULL,
    [requirement_name]                                               VARCHAR (4000) NULL,
    [requirement_parent_id]                                          VARCHAR (4000) NULL,
    [requirement_pid]                                                VARCHAR (4000) NULL,
    [requirement_project_id]                                         VARCHAR (4000) NULL,
    [test_case_created_date]                                         VARCHAR (4000) NULL,
    [test_case_created_dim_date_key]                                 VARCHAR (8)    NULL,
    [test_case_created_dim_time_key]                                 INT            NULL,
    [test_case_creator_id]                                           VARCHAR (4000) NULL,
    [test_case_description]                                          VARCHAR (4000) NULL,
    [test_case_last_modified_date]                                   VARCHAR (4000) NULL,
    [test_case_last_modified_dim_date_key]                           VARCHAR (8)    NULL,
    [test_case_last_modified_dim_time_key]                           INT            NULL,
    [test_case_name]                                                 VARCHAR (4000) NULL,
    [test_case_order]                                                VARCHAR (4000) NULL,
    [test_case_parent_id]                                            VARCHAR (4000) NULL,
    [test_case_pid]                                                  VARCHAR (4000) NULL,
    [test_case_project_id]                                           VARCHAR (4000) NULL,
    [test_case_properties_assigned_to_field_value_name]              VARCHAR (4000) NULL,
    [test_case_properties_automation_content_field_value]            VARCHAR (4000) NULL,
    [test_case_properties_automation_field_value_name]               VARCHAR (4000) NULL,
    [test_case_properties_candidate_for_automation_field_value_name] VARCHAR (4000) NULL,
    [test_case_properties_description_field_value]                   VARCHAR (4000) NULL,
    [test_case_properties_platform_field_value_name]                 VARCHAR (4000) NULL,
    [test_case_properties_precondition_field_value]                  VARCHAR (4000) NULL,
    [test_case_properties_shared_field_value]                        VARCHAR (4000) NULL,
    [test_case_properties_status_field_value_name]                   VARCHAR (4000) NULL,
    [test_case_properties_test_data_field_value]                     VARCHAR (4000) NULL,
    [test_case_properties_test_tier_field_value_name]                VARCHAR (4000) NULL,
    [test_case_properties_type_field_value_name]                     VARCHAR (4000) NULL,
    [test_case_properties_zephyr_issue_key_field_value]              VARCHAR (4000) NULL,
    [test_case_properties_zephyr_test_steps_field_value]             VARCHAR (4000) NULL,
    [test_case_test_case_version_id]                                 VARCHAR (4000) NULL,
    [test_case_version]                                              VARCHAR (4000) NULL,
    [p_qtest_jira_id]                                                BIGINT         NOT NULL,
    [deleted_flag]                                                   INT            NULL,
    [dv_load_date_time]                                              DATETIME       NULL,
    [dv_load_end_date_time]                                          DATETIME       NULL,
    [dv_batch_id]                                                    BIGINT         NOT NULL,
    [dv_inserted_date_time]                                          DATETIME       NOT NULL,
    [dv_insert_user]                                                 VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                                           DATETIME       NULL,
    [dv_update_user]                                                 VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

