CREATE TABLE [dbo].[d_spabiz_staff] (
    [d_spabiz_staff_id]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                            CHAR (32)       NOT NULL,
    [dim_spabiz_staff_key]               CHAR (32)       NULL,
    [staff_id]                           BIGINT          NULL,
    [store_number]                       BIGINT          NULL,
    [address_city]                       VARCHAR (60)    NULL,
    [address_line_1]                     VARCHAR (765)   NULL,
    [address_line_2]                     VARCHAR (90)    NULL,
    [adress_state]                       VARCHAR (6)     NULL,
    [anniversary]                        VARCHAR (30)    NULL,
    [appointment_cycle_count]            DECIMAL (26, 6) NULL,
    [birthday]                           VARCHAR (30)    NULL,
    [book_name]                          VARCHAR (150)   NULL,
    [can_use_system_flag]                CHAR (1)        NULL,
    [clock_in_request_flag]              CHAR (1)        NULL,
    [deleted_date_time]                  DATETIME        NULL,
    [deleted_flag]                       CHAR (1)        NULL,
    [dim_spabiz_assistant_comission_key] CHAR (32)       NULL,
    [dim_spabiz_category_key]            CHAR (32)       NULL,
    [dim_spabiz_primary_store_key]       CHAR (32)       NULL,
    [dim_spabiz_store_key]               CHAR (32)       NULL,
    [do_not_print_productivity_flag]     CHAR (1)        NULL,
    [edit_date_time]                     DATETIME        NULL,
    [employee_end_date_time]             DATETIME        NULL,
    [employee_start_date_time]           DATETIME        NULL,
    [first_initial_last_name]            VARCHAR (150)   NULL,
    [first_last_name]                    VARCHAR (150)   NULL,
    [first_name]                         VARCHAR (150)   NULL,
    [gender_dim_description_key]         VARCHAR (50)    NULL,
    [gender_id]                          VARCHAR (50)    NULL,
    [home_phone_number]                  VARCHAR (60)    NULL,
    [is_admin_flag]                      CHAR (1)        NULL,
    [last_name]                          VARCHAR (150)   NULL,
    [middle_initial]                     VARCHAR (3)     NULL,
    [mobile_phone_number]                VARCHAR (60)    NULL,
    [name]                               VARCHAR (150)   NULL,
    [neill_id]                           VARCHAR (75)    NULL,
    [pager_number]                       VARCHAR (60)    NULL,
    [pager_type]                         DECIMAL (26, 6) NULL,
    [pop_up_information]                 VARCHAR (3000)  NULL,
    [postal_code]                        VARCHAR (30)    NULL,
    [print_1_flag]                       CHAR (1)        NULL,
    [print_2_flag]                       CHAR (1)        NULL,
    [print_3_flag]                       CHAR (1)        NULL,
    [print_4_flag]                       CHAR (1)        NULL,
    [print_5_flag]                       CHAR (1)        NULL,
    [print_6_flag]                       CHAR (1)        NULL,
    [print_7_flag]                       CHAR (1)        NULL,
    [print_traveler_flag]                CHAR (1)        NULL,
    [quick_id]                           VARCHAR (150)   NULL,
    [resource_flag]                      CHAR (1)        NULL,
    [staff_flag]                         CHAR (1)        NULL,
    [start_appointment_cycle_date_time]  DATETIME        NULL,
    [wage]                               DECIMAL (26, 6) NULL,
    [wage_per_minute]                    DECIMAL (26, 6) NULL,
    [wage_type_dim_description_key]      VARCHAR (50)    NULL,
    [wage_type_id]                       VARCHAR (50)    NULL,
    [web_book_flag]                      CHAR (1)        NULL,
    [work_phone_number]                  VARCHAR (60)    NULL,
    [p_spabiz_staff_id]                  BIGINT          NOT NULL,
    [dv_load_date_time]                  DATETIME        NULL,
    [dv_load_end_date_time]              DATETIME        NULL,
    [dv_batch_id]                        BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[d_spabiz_staff]([dv_batch_id] ASC);

