CREATE TABLE [dbo].[d_spabiz_cust_card_type] (
    [d_spabiz_cust_card_type_id]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [cust_card_type_id]                    DECIMAL (26, 6) NULL,
    [store_number]                         DECIMAL (26, 6) NULL,
    [counter_id]                           DECIMAL (26, 6) NULL,
    [cust_card_type_delete_flag]           CHAR (1)        NULL,
    [d_spabiz_cust_card_type_discount_key] CHAR (32)       NULL,
    [days_good_for]                        DECIMAL (26, 6) NULL,
    [delete_dim_date_key]                  CHAR (8)        NULL,
    [disp_color]                           VARCHAR (60)    NULL,
    [edit_dim_time_key]                    CHAR (8)        NULL,
    [initial_price]                        DECIMAL (26, 6) NULL,
    [name]                                 VARCHAR (150)   NULL,
    [payment_interval]                     DECIMAL (26, 6) NULL,
    [prod_disc]                            VARCHAR (30)    NULL,
    [retail_price]                         DECIMAL (26, 6) NULL,
    [service_disc]                         VARCHAR (30)    NULL,
    [p_spabiz_cust_card_type_id]           BIGINT          NOT NULL,
    [deleted_flag]                         INT             NULL,
    [dv_load_date_time]                    DATETIME        NULL,
    [dv_load_end_date_time]                DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

