CREATE TABLE [dbo].[d_udwcloudsync_club_master_roster] (
    [d_udwcloudsync_club_master_roster_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [dim_club_key]                         CHAR (32)       NULL,
    [mms_club_id]                          INT             NULL,
    [access_type]                          NVARCHAR (4000) NULL,
    [activity_center]                      NVARCHAR (4000) NULL,
    [allow_junior_check_in_flag]           CHAR (1)        NULL,
    [aquatics_dh]                          NVARCHAR (4000) NULL,
    [aquatics_regional_manager]            NVARCHAR (4000) NULL,
    [area]                                 NVARCHAR (4000) NULL,
    [area_director]                        NVARCHAR (4000) NULL,
    [asst_general_manager]                 NVARCHAR (4000) NULL,
    [athletic_lta]                         BIT             NULL,
    [basketball_courts]                    INT             NULL,
    [basketball_trainer]                   NVARCHAR (4000) NULL,
    [bulding_engineer]                     NVARCHAR (4000) NULL,
    [business_administrator]               NVARCHAR (4000) NULL,
    [cafe]                                 NVARCHAR (4000) NULL,
    [center_type]                          NVARCHAR (4000) NULL,
    [child_center_kids_activities_dh]      NVARCHAR (4000) NULL,
    [cig_status]                           NVARCHAR (4000) NULL,
    [clinic]                               NVARCHAR (4000) NULL,
    [club_master_roster_id]                INT             NULL,
    [club_master_roster_order]             INT             NULL,
    [cognos_name]                          NVARCHAR (4000) NULL,
    [current_operations_status]            NVARCHAR (4000) NULL,
    [cycle_studios]                        INT             NULL,
    [dim_spabiz_store_key]                 CHAR (32)       NULL,
    [display_ui_flag]                      CHAR (1)        NULL,
    [effective_permissions_mask]           NVARCHAR (4000) NULL,
    [egroup_name]                          NVARCHAR (4000) NULL,
    [email_alert]                          NVARCHAR (4000) NULL,
    [facility_operations_dh]               NVARCHAR (4000) NULL,
    [facility_technician]                  NVARCHAR (4000) NULL,
    [family_swim]                          BIT             NULL,
    [general_manager]                      NVARCHAR (4000) NULL,
    [group_fitness_dh]                     NVARCHAR (4000) NULL,
    [group_fitness_studios]                INT             NULL,
    [growth_type]                          NVARCHAR (4000) NULL,
    [hyperion_planning]                    NVARCHAR (4000) NULL,
    [indoor_pool]                          NVARCHAR (4000) NULL,
    [indoor_tennis_courts]                 INT             NULL,
    [kids_regional_manager]                NVARCHAR (4000) NULL,
    [lap_pools]                            NVARCHAR (4000) NULL,
    [leases_owned]                         NVARCHAR (4000) NULL,
    [level]                                INT             NULL,
    [life_cafe_dh]                         NVARCHAR (4000) NULL,
    [life_shop]                            NVARCHAR (4000) NULL,
    [life_spa_dh]                          NVARCHAR (4000) NULL,
    [marketing_club_level]                 NVARCHAR (4000) NULL,
    [marketing_club_name]                  NVARCHAR (4000) NULL,
    [marketing_map_region]                 NVARCHAR (4000) NULL,
    [marketing_map_xml_state_name]         NVARCHAR (4000) NULL,
    [mca_studios]                          INT             NULL,
    [member_engagement_manager]            NVARCHAR (4000) NULL,
    [member_services_dh]                   NVARCHAR (4000) NULL,
    [membership_level]                     NVARCHAR (4000) NULL,
    [membership_level_needed_for_tennis]   NVARCHAR (4000) NULL,
    [number_of_slides]                     INT             NULL,
    [nutrition_coach]                      NVARCHAR (4000) NULL,
    [nutrition_regional_manager]           NVARCHAR (4000) NULL,
    [open_24_hours]                        BIT             NULL,
    [open_status]                          NVARCHAR (4000) NULL,
    [opened_date]                          DATETIME        NULL,
    [operations_regional_manager]          NVARCHAR (4000) NULL,
    [ops_rcl_sr_dh]                        NVARCHAR (4000) NULL,
    [outdoor_pool]                         NVARCHAR (4000) NULL,
    [outdoor_tennis_courts]                INT             NULL,
    [parents_night_out]                    BIT             NULL,
    [personal_training_dh]                 NVARCHAR (4000) NULL,
    [personal_training_rcm]                NVARCHAR (4000) NULL,
    [personal_training_regional_manager]   NVARCHAR (4000) NULL,
    [pilates_studio]                       INT             NULL,
    [pre_sale_address]                     NVARCHAR (4000) NULL,
    [property_bag]                         NVARCHAR (4000) NULL,
    [racquet_ball_courts]                  INT             NULL,
    [racquet_regional_manager]             NVARCHAR (4000) NULL,
    [region]                               NVARCHAR (4000) NULL,
    [regional_sales_manager]               NVARCHAR (4000) NULL,
    [regional_vice_president]              NVARCHAR (4000) NULL,
    [restricted]                           NVARCHAR (4000) NULL,
    [sales_regional_manager]               NVARCHAR (4000) NULL,
    [school_break_camps]                   BIT             NULL,
    [senior_general_manager]               NVARCHAR (4000) NULL,
    [spa]                                  NVARCHAR (4000) NULL,
    [square_footage]                       INT             NULL,
    [squash_courts]                        INT             NULL,
    [squash_kids]                          BIT             NULL,
    [summer_break_camps]                   BIT             NULL,
    [tennis_courts]                        NVARCHAR (4000) NULL,
    [tennis_dh]                            NVARCHAR (4000) NULL,
    [three_story]                          BIT             NULL,
    [turf_field]                           INT             NULL,
    [unique_features]                      NVARCHAR (4000) NULL,
    [unique_id]                            NVARCHAR (4000) NULL,
    [water_slides]                         NVARCHAR (4000) NULL,
    [whirpools]                            INT             NULL,
    [workday_region_key]                   CHAR (32)       NULL,
    [yoga_studios]                         INT             NULL,
    [zero_depth_entry]                     NVARCHAR (4000) NULL,
    [p_udwcloudsync_club_master_roster_id] BIGINT          NOT NULL,
    [deleted_flag]                         INT             NULL,
    [dv_load_date_time]                    DATETIME        NULL,
    [dv_load_end_date_time]                DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[d_udwcloudsync_club_master_roster]([dv_batch_id] ASC);

