CREATE TABLE [dbo].[d_udwcloudsync_product_master_history] (
    [d_udwcloudsync_product_master_history_id]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                   CHAR (32)       NOT NULL,
    [product_id]                                INT             NULL,
    [product_sku]                               VARCHAR (500)   NULL,
    [source_system]                             VARCHAR (500)   NULL,
    [effective_date_time]                       DATETIME        NULL,
    [expiration_date_time]                      DATETIME        NULL,
    [allocation_rule]                           VARCHAR (500)   NULL,
    [connectivity_lead_generator_flag]          CHAR (1)        NULL,
    [connectivity_primary_lead_generator_flag]  CHAR (1)        NULL,
    [corporate_transfer_flag]                   CHAR (1)        NULL,
    [corporate_transfer_multiplier]             DECIMAL (12, 2) NULL,
    [departmental_dssr_flag]                    CHAR (1)        NULL,
    [dim_cafe_product_key]                      CHAR (32)       NULL,
    [dim_healthcheckusa_product_key]            CHAR (32)       NULL,
    [dim_hybris_product_key]                    CHAR (32)       NULL,
    [dim_magento_product_key]                   CHAR (32)       NULL,
    [dim_mms_product_key]                       CHAR (32)       NULL,
    [dim_reporting_hierarchy_key]               CHAR (32)       NULL,
    [dssr_down_grade_other_enrollment_fee_flag] CHAR (1)        NULL,
    [dssr_if_admin_fee_flag]                    CHAR (1)        NULL,
    [experience_life_magazine_flag]             CHAR (1)        NULL,
    [mtd_average_delivered_session_price_flag]  CHAR (1)        NULL,
    [mtd_average_sale_price_flag]               CHAR (1)        NULL,
    [new_business_old_business_flag]            CHAR (1)        NULL,
    [payroll_description]                       VARCHAR (500)   NULL,
    [payroll_lt_bucks_group_description]        VARCHAR (500)   NULL,
    [payroll_lt_bucks_group_sort_order]         INT             NULL,
    [payroll_lt_bucks_product_group_flag]       CHAR (1)        NULL,
    [payroll_lt_bucks_sales_amount_flag]        CHAR (1)        NULL,
    [payroll_lt_bucks_service_amount_flag]      CHAR (1)        NULL,
    [payroll_lt_bucks_service_quantity_flag]    CHAR (1)        NULL,
    [payroll_region_type]                       VARCHAR (500)   NULL,
    [payroll_standard_group_description]        VARCHAR (500)   NULL,
    [payroll_standard_group_sort_order]         INT             NULL,
    [payroll_standard_product_group_flag]       CHAR (1)        NULL,
    [payroll_standard_sales_amount_flag]        CHAR (1)        NULL,
    [payroll_standard_service_amount_flag]      CHAR (1)        NULL,
    [payroll_standard_service_quantity_flag]    CHAR (1)        NULL,
    [payroll_track_sales_flag]                  CHAR (1)        NULL,
    [payroll_track_service_flag]                CHAR (1)        NULL,
    [product_description]                       VARCHAR (500)   NULL,
    [product_status]                            NVARCHAR (4000) NULL,
    [reporting_department]                      VARCHAR (500)   NULL,
    [reporting_division]                        VARCHAR (500)   NULL,
    [reporting_product_group]                   VARCHAR (500)   NULL,
    [reporting_product_group_gl_account]        INT             NULL,
    [reporting_product_group_sort_order]        INT             NULL,
    [reporting_region_type]                     VARCHAR (500)   NULL,
    [reporting_sub_division]                    VARCHAR (500)   NULL,
    [revenue_product_group_discount_gl_account] NVARCHAR (4000) NULL,
    [revenue_product_group_refund_gl_account]   NVARCHAR (4000) NULL,
    [sales_category_description]                VARCHAR (500)   NULL,
    [p_udwcloudsync_product_master_id]          BIGINT          NOT NULL,
    [deleted_flag]                              INT             NULL,
    [dv_load_date_time]                         DATETIME        NULL,
    [dv_load_end_date_time]                     DATETIME        NULL,
    [dv_batch_id]                               BIGINT          NOT NULL,
    [dv_inserted_date_time]                     DATETIME        NOT NULL,
    [dv_insert_user]                            VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                      DATETIME        NULL,
    [dv_update_user]                            VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

