CREATE TABLE [dbo].[d_workday_employee_history] (
    [d_workday_employee_history_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                       CHAR (32)       NOT NULL,
    [dim_employee_key]              CHAR (32)       NULL,
    [employee_id]                   INT             NULL,
    [effective_date_time]           DATETIME        NULL,
    [expiration_date_time]          DATETIME        NULL,
    [active_status]                 NVARCHAR (255)  NULL,
    [business_titles]               NVARCHAR (4000) NULL,
    [category]                      NVARCHAR (255)  NULL,
    [certifications]                VARCHAR (8000)  NULL,
    [cf_employment_status]          NVARCHAR (255)  NULL,
    [cf_nickname]                   NVARCHAR (255)  NULL,
    [first_name]                    NVARCHAR (255)  NULL,
    [hire_date]                     DATETIME        NULL,
    [is_primary]                    NVARCHAR (255)  NULL,
    [job_codes]                     NVARCHAR (4000) NULL,
    [job_families]                  NVARCHAR (4000) NULL,
    [job_levels]                    NVARCHAR (4000) NULL,
    [job_profiles]                  NVARCHAR (4000) NULL,
    [job_sub_families]              NVARCHAR (4000) NULL,
    [last_name]                     NVARCHAR (255)  NULL,
    [manager_dim_employee_key]      CHAR (32)       NULL,
    [manager_id]                    INT             NULL,
    [marketing_titles]              NVARCHAR (4000) NULL,
    [middle_name]                   NVARCHAR (255)  NULL,
    [mms_club_id]                   NVARCHAR (4000) NULL,
    [pay_rate_for_all_positions]    NVARCHAR (4000) NULL,
    [phone_number]                  NVARCHAR (255)  NULL,
    [preferred_first_name]          NVARCHAR (255)  NULL,
    [preferred_last_name]           NVARCHAR (255)  NULL,
    [preferred_middle_name]         NVARCHAR (255)  NULL,
    [primary_work_email]            NVARCHAR (255)  NULL,
    [subordinates]                  NVARCHAR (255)  NULL,
    [termination_date]              DATETIME        NULL,
    [workday_club_id]               NVARCHAR (4000) NULL,
    [p_workday_employee_id]         BIGINT          NOT NULL,
    [deleted_flag]                  INT             NULL,
    [dv_load_date_time]             DATETIME        NULL,
    [dv_load_end_date_time]         DATETIME        NULL,
    [dv_batch_id]                   BIGINT          NOT NULL,
    [dv_inserted_date_time]         DATETIME        NOT NULL,
    [dv_insert_user]                VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]          DATETIME        NULL,
    [dv_update_user]                VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

