CREATE TABLE [dbo].[dim_club] (
    [dim_club_id]                                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [dim_club_key]                                        CHAR (32)       NULL,
    [club_id]                                             INT             NULL,
    [access_type]                                         VARCHAR (4000)  NULL,
    [address_line_1]                                      VARCHAR (50)    NULL,
    [address_line_2]                                      VARCHAR (50)    NULL,
    [allow_junior_check_in_flag]                          CHAR (1)        NULL,
    [amenity_conditioner_flag]                            CHAR (1)        NULL,
    [amenity_cotton_balls_flag]                           CHAR (1)        NULL,
    [amenity_deodorant_flag]                              CHAR (1)        NULL,
    [amenity_free_lockers_and_towels_flag]                CHAR (1)        NULL,
    [amenity_hairspray_flag]                              CHAR (1)        NULL,
    [amenity_mouthwash_flag]                              CHAR (1)        NULL,
    [amenity_plasma_big_screen_tvs_flag]                  CHAR (1)        NULL,
    [amenity_razors_flag]                                 CHAR (1)        NULL,
    [amenity_shampoo_flag]                                CHAR (1)        NULL,
    [amenity_wireless_internet_access_flag]               CHAR (1)        NULL,
    [app_created_by]                                      NVARCHAR (4000) NULL,
    [app_modified_by]                                     NVARCHAR (4000) NULL,
    [area_director_dim_crm_system_user_key]               CHAR (32)       NULL,
    [assess_junior_member_dues_flag]                      CHAR (1)        NULL,
    [center_type]                                         VARCHAR (4000)  NULL,
    [check_in_group_level]                                INT             NULL,
    [child_center_weekly_limit]                           INT             NULL,
    [city]                                                VARCHAR (50)    NULL,
    [club_close_dim_date_key]                             INT             NULL,
    [club_code]                                           VARCHAR (18)    NULL,
    [club_hours]                                          NVARCHAR (4000) NULL,
    [club_membership_level]                               NVARCHAR (4000) NULL,
    [club_name]                                           VARCHAR (50)    NULL,
    [club_open_dim_date_key]                              INT             NULL,
    [club_regional_manager_dim_crm_system_user_key]       CHAR (32)       NULL,
    [club_status]                                         VARCHAR (25)    NULL,
    [club_type]                                           VARCHAR (21)    NULL,
    [compliance_asset_id]                                 NVARCHAR (4000) NULL,
    [content_type]                                        NVARCHAR (4000) NULL,
    [country]                                             VARCHAR (25)    NULL,
    [created_by]                                          NVARCHAR (4000) NULL,
    [created_dim_date_key]                                CHAR (8)        NULL,
    [dim_crm_team_key]                                    CHAR (32)       NULL,
    [domain_name_prefix]                                  VARCHAR (10)    NULL,
    [dst_offset]                                          INT             NULL,
    [fax_number]                                          VARCHAR (10)    NULL,
    [feature_advanced_training_studio_flag]               CHAR (1)        NULL,
    [feature_alpha_field_flag]                            CHAR (1)        NULL,
    [feature_bar_flag]                                    CHAR (1)        NULL,
    [feature_basketball_courts_flag]                      CHAR (1)        NULL,
    [feature_boxing_gym_flag]                             CHAR (1)        NULL,
    [feature_business_center_flag]                        CHAR (1)        NULL,
    [feature_cardio_equipment_flag]                       CHAR (1)        NULL,
    [feature_child_center_flag]                           CHAR (1)        NULL,
    [feature_connected_technology_flag]                   CHAR (1)        NULL,
    [feature_deluge_flag]                                 CHAR (1)        NULL,
    [feature_fitness_studios_flag]                        CHAR (1)        NULL,
    [feature_free_weights_and_equipment_flag]             CHAR (1)        NULL,
    [feature_functional_training_area_flag]               CHAR (1)        NULL,
    [feature_hamam_flag]                                  CHAR (1)        NULL,
    [feature_indoor_cycle_studio_flag]                    CHAR (1)        NULL,
    [feature_indoor_golf_center_flag]                     CHAR (1)        NULL,
    [feature_indoor_lap_pool_flag]                        CHAR (1)        NULL,
    [feature_indoor_leisure_pool_flag]                    CHAR (1)        NULL,
    [feature_indoor_tennis_courts_flag]                   CHAR (1)        NULL,
    [feature_indoor_turf_field_flag]                      CHAR (1)        NULL,
    [feature_indoor_water_slides_flag]                    CHAR (1)        NULL,
    [feature_indoor_whirlpool_flag]                       CHAR (1)        NULL,
    [feature_infant_room_flag]                            CHAR (1)        NULL,
    [feature_kids_academy_flag]                           CHAR (1)        NULL,
    [feature_kids_gym_flag]                               CHAR (1)        NULL,
    [feature_kids_language_arts_studio_flag]              CHAR (1)        NULL,
    [feature_kids_learning_lab_flag]                      CHAR (1)        NULL,
    [feature_kids_media_room_flag]                        CHAR (1)        NULL,
    [feature_kids_movement_studio_flag]                   CHAR (1)        NULL,
    [feature_kids_outdoor_play_area_flag]                 CHAR (1)        NULL,
    [feature_kids_tumbling_studio_flag]                   CHAR (1)        NULL,
    [feature_lazy_river_flag]                             CHAR (1)        NULL,
    [feature_lifecafe_flag]                               CHAR (1)        NULL,
    [feature_lifecafe_poolside_bistro_flag]               CHAR (1)        NULL,
    [feature_lifespa_flag]                                CHAR (1)        NULL,
    [feature_mixed_combats_arts_studio_flag]              CHAR (1)        NULL,
    [feature_outdoor_fitness_trail_flag]                  CHAR (1)        NULL,
    [feature_outdoor_lap_pool_flag]                       CHAR (1)        NULL,
    [feature_outdoor_swimming_pool_flag]                  CHAR (1)        NULL,
    [feature_outdoor_tennis_courts_flag]                  CHAR (1)        NULL,
    [feature_outdoor_turf_field_flag]                     CHAR (1)        NULL,
    [feature_outdoor_water_slides_flag]                   CHAR (1)        NULL,
    [feature_outdoor_whirlpool_flag]                      CHAR (1)        NULL,
    [feature_pickleball_court_flag]                       CHAR (1)        NULL,
    [feature_pilates_studio_flag]                         CHAR (1)        NULL,
    [feature_play_maze_flag]                              CHAR (1)        NULL,
    [feature_pre_school_flag]                             CHAR (1)        NULL,
    [feature_proactive_care_clinic_flag]                  CHAR (1)        NULL,
    [feature_racquetball_courts_flag]                     CHAR (1)        NULL,
    [feature_rare_flag]                                   CHAR (1)        NULL,
    [feature_rehabilitation_and_chiropractic_clinic_flag] CHAR (1)        NULL,
    [feature_resistance_training_area_flag]               CHAR (1)        NULL,
    [feature_retail_store_flag]                           CHAR (1)        NULL,
    [feature_rock_wall_flag]                              CHAR (1)        NULL,
    [feature_rooftop_patio_flag]                          CHAR (1)        NULL,
    [feature_sand_volleyball_court_flag]                  CHAR (1)        NULL,
    [feature_saunas_flag]                                 CHAR (1)        NULL,
    [feature_splash_pad_flag]                             CHAR (1)        NULL,
    [feature_squash_courts_flag]                          CHAR (1)        NULL,
    [feature_steam_rooms_flag]                            CHAR (1)        NULL,
    [feature_volleyball_courts_flag]                      CHAR (1)        NULL,
    [feature_walking_running_track_flag]                  CHAR (1)        NULL,
    [feature_weight_machines_flag]                        CHAR (1)        NULL,
    [feature_yoga_studio_flag]                            CHAR (1)        NULL,
    [feature_zero_depth_entry_pool_flag]                  CHAR (1)        NULL,
    [five_letter_club_code]                               VARCHAR (5)     NULL,
    [folder_child_count]                                  NVARCHAR (4000) NULL,
    [formal_club_name]                                    VARCHAR (50)    NULL,
    [four_letter_club_code]                               VARCHAR (4)     NULL,
    [general_manager]                                     NVARCHAR (4000) NULL,
    [general_manager_dim_crm_system_user_key]             CHAR (32)       NULL,
    [general_manager_email]                               NVARCHAR (4000) NULL,
    [general_manager_phone]                               NVARCHAR (4000) NULL,
    [gl_club_id]                                          INT             NULL,
    [growth_type]                                         VARCHAR (4000)  NULL,
    [info_genesis_store_id]                               INT             NULL,
    [item_child_count]                                    NVARCHAR (4000) NULL,
    [item_type]                                           NVARCHAR (4000) NULL,
    [label_applied]                                       NVARCHAR (4000) NULL,
    [label_applied_by]                                    NVARCHAR (4000) NULL,
    [label_setting]                                       NVARCHAR (4000) NULL,
    [labels]                                              NVARCHAR (4000) NULL,
    [latitude]                                            DECIMAL (20, 9) NULL,
    [local_currency_code]                                 VARCHAR (25)    NULL,
    [longitude]                                           DECIMAL (20, 9) NULL,
    [ltf_lt_work_email]                                   INT             NULL,
    [ltf_web_specialist_team]                             VARCHAR (36)    NULL,
    [marketing_club_level]                                VARCHAR (4000)  NULL,
    [marketing_map_region]                                VARCHAR (50)    NULL,
    [marketing_name]                                      VARCHAR (100)   NULL,
    [max_junior_age]                                      INT             NULL,
    [member_activities_region_dim_description_key]        VARCHAR (532)   NULL,
    [member_services_manager]                             NVARCHAR (4000) NULL,
    [member_services_manager_email]                       NVARCHAR (4000) NULL,
    [member_services_manager_phone]                       NVARCHAR (4000) NULL,
    [modified_by]                                         NVARCHAR (4000) NULL,
    [modified_dim_date_key]                               CHAR (8)        NULL,
    [oms_flag]                                            CHAR (1)        NULL,
    [open_dim_date_key]                                   CHAR (8)        NULL,
    [path]                                                NVARCHAR (4000) NULL,
    [phone_number]                                        VARCHAR (10)    NULL,
    [postal_code]                                         VARCHAR (11)    NULL,
    [program_badminton_flag]                              CHAR (1)        NULL,
    [program_barre_flag]                                  CHAR (1)        NULL,
    [program_basketball_flag]                             CHAR (1)        NULL,
    [program_birthday_parties_flag]                       CHAR (1)        NULL,
    [program_boxing_flag]                                 CHAR (1)        NULL,
    [program_golf_flag]                                   CHAR (1)        NULL,
    [program_handball_flag]                               CHAR (1)        NULL,
    [program_indoor_cycle_flag]                           CHAR (1)        NULL,
    [program_kids_academy_flag]                           CHAR (1)        NULL,
    [program_kids_activities_flag]                        CHAR (1)        NULL,
    [program_kids_camps_flag]                             CHAR (1)        NULL,
    [program_kids_sports_and_fitness_flag]                CHAR (1)        NULL,
    [program_kids_swim_flag]                              CHAR (1)        NULL,
    [program_mixed_combat_arts_flag]                      CHAR (1)        NULL,
    [program_outdoor_cycle_flag]                          CHAR (1)        NULL,
    [program_personal_training_flag]                      CHAR (1)        NULL,
    [program_pickleball_flag]                             CHAR (1)        NULL,
    [program_pilates_flag]                                CHAR (1)        NULL,
    [program_racquetball_flag]                            CHAR (1)        NULL,
    [program_rock_climbing_flag]                          CHAR (1)        NULL,
    [program_run_club_flag]                               CHAR (1)        NULL,
    [program_soccer_flag]                                 CHAR (1)        NULL,
    [program_squash_flag]                                 CHAR (1)        NULL,
    [program_studio_flag]                                 CHAR (1)        NULL,
    [program_swimming_flag]                               CHAR (1)        NULL,
    [program_table_tennis_flag]                           CHAR (1)        NULL,
    [program_team_training_flag]                          CHAR (1)        NULL,
    [program_tennis_flag]                                 CHAR (1)        NULL,
    [program_volleyball_flag]                             CHAR (1)        NULL,
    [program_weight_loss_flag]                            CHAR (1)        NULL,
    [program_yoga_flag]                                   CHAR (1)        NULL,
    [pt_rcl_area_dim_description_key]                     VARCHAR (532)   NULL,
    [region_dim_description_key]                          VARCHAR (532)   NULL,
    [regional_sales_lead_dim_crm_system_user_key]         CHAR (32)       NULL,
    [regional_vice_president_dim_crm_system_user_key]     CHAR (32)       NULL,
    [sales_area_dim_description_key]                      VARCHAR (532)   NULL,
    [sell_junior_member_dues_flag]                        CHAR (1)        NULL,
    [service_bar_flag]                                    CHAR (1)        NULL,
    [service_basketball_training_flag]                    CHAR (1)        NULL,
    [service_child_center_flag]                           CHAR (1)        NULL,
    [service_golf_instruction_flag]                       CHAR (1)        NULL,
    [service_hair_flag]                                   CHAR (1)        NULL,
    [service_health_assessments_flag]                     CHAR (1)        NULL,
    [service_kids_academy_flag]                           CHAR (1)        NULL,
    [service_kids_birthday_parties_flag]                  CHAR (1)        NULL,
    [service_kids_camps_flag]                             CHAR (1)        NULL,
    [service_kids_swim_lessons_flag]                      CHAR (1)        NULL,
    [service_lifecafe_flag]                               CHAR (1)        NULL,
    [service_marathon_training_flag]                      CHAR (1)        NULL,
    [service_massage_flag]                                CHAR (1)        NULL,
    [service_medi_spa_flag]                               CHAR (1)        NULL,
    [service_nails_flag]                                  CHAR (1)        NULL,
    [service_nutritional_coaching_flag]                   CHAR (1)        NULL,
    [service_proactive_care_flag]                         CHAR (1)        NULL,
    [service_racquetball_lessons_flag]                    CHAR (1)        NULL,
    [service_rare_flag]                                   CHAR (1)        NULL,
    [service_rehabilitation_chiropractic_flag]            CHAR (1)        NULL,
    [service_run_training_flag]                           CHAR (1)        NULL,
    [service_skin_flag]                                   CHAR (1)        NULL,
    [service_soccer_training_flag]                        CHAR (1)        NULL,
    [service_squash_lessons_flag]                         CHAR (1)        NULL,
    [service_swim_assessments_flag]                       CHAR (1)        NULL,
    [service_team_training_flag]                          CHAR (1)        NULL,
    [service_tennis_lessons_flag]                         CHAR (1)        NULL,
    [service_tri_training_flag]                           CHAR (1)        NULL,
    [service_weight_loss_flag]                            CHAR (1)        NULL,
    [square_footage]                                      INT             NULL,
    [st_offset]                                           INT             NULL,
    [state]                                               VARCHAR (25)    NULL,
    [state_or_province]                                   VARCHAR (50)    NULL,
    [telephone]                                           VARCHAR (50)    NULL,
    [title]                                               NVARCHAR (4000) NULL,
    [val_member_activity_region_id]                       INT             NULL,
    [val_pt_rcl_area_id]                                  INT             NULL,
    [val_region_id]                                       INT             NULL,
    [val_sales_area_id]                                   INT             NULL,
    [val_time_zone_id]                                    INT             NULL,
    [web_free_pass]                                       NVARCHAR (4000) NULL,
    [web_inquiry_flag]                                    CHAR (1)        NULL,
    [web_presale_waitlist_flag]                           CHAR (1)        NULL,
    [web_price_request_flag]                              CHAR (1)        NULL,
    [web_specialist_dim_crm_team_key]                     CHAR (32)       NULL,
    [workday_region]                                      VARCHAR (4)     NULL,
    [yoga_studios]                                        INT             NULL,
    [dv_load_date_time]                                   DATETIME        NULL,
    [dv_load_end_date_time]                               DATETIME        NULL,
    [dv_batch_id]                                         BIGINT          NOT NULL,
    [dv_inserted_date_time]                               DATETIME        NOT NULL,
    [dv_insert_user]                                      VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                DATETIME        NULL,
    [dv_update_user]                                      VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([dim_club_key]));

