CREATE TABLE [dbo].[dim_boss_product] (
    [dim_boss_product_id]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [category_id]                 INT          NULL,
    [color]                       VARCHAR (8)  NULL,
    [department_code]             INT          NULL,
    [department_description]      VARCHAR (30) NULL,
    [dim_boss_product_key]        VARCHAR (32) NULL,
    [dim_mms_product_key]         VARCHAR (32) NULL,
    [display_flag]                CHAR (1)     NULL,
    [product_description]         VARCHAR (50) NULL,
    [product_format_id]           INT          NULL,
    [product_format_long_desc]    CHAR (50)    NULL,
    [product_format_short_desc]   CHAR (50)    NULL,
    [product_hierarchy_level_1]   VARCHAR (30) NULL,
    [product_hierarchy_level_2]   VARCHAR (30) NULL,
    [product_hierarchy_level_3]   VARCHAR (30) NULL,
    [product_interest_id]         INT          NULL,
    [product_interest_long_desc]  CHAR (50)    NULL,
    [product_interest_short_desc] CHAR (15)    NULL,
    [product_line]                VARCHAR (30) NULL,
    [product_updated_timestamp]   DATETIME     NULL,
    [size]                        VARCHAR (8)  NULL,
    [sku]                         VARCHAR (18) NULL,
    [style]                       VARCHAR (8)  NULL,
    [upc_code]                    CHAR (15)    NULL,
    [dv_load_date_time]           DATETIME     NULL,
    [dv_load_end_date_time]       DATETIME     NULL,
    [dv_batch_id]                 BIGINT       NOT NULL,
    [dv_inserted_date_time]       DATETIME     NOT NULL,
    [dv_insert_user]              VARCHAR (50) NOT NULL,
    [dv_updated_date_time]        DATETIME     NULL,
    [dv_update_user]              VARCHAR (50) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([dim_boss_product_key]));

