CREATE TABLE [dbo].[dim_employee] (
    [dim_employee_id]                                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [dim_employee_key]                                   CHAR (32)       NULL,
    [employee_id]                                        INT             NULL,
    [active_status]                                      VARCHAR (400)   NULL,
    [assistant_department_head_sales_for_net_units_flag] CHAR (1)        NULL,
    [business_titles]                                    VARCHAR (400)   NULL,
    [category]                                           VARCHAR (400)   NULL,
    [cf_employment_status]                               NVARCHAR (255)  NULL,
    [cf_nickname]                                        NVARCHAR (255)  NULL,
    [department_head_sales_for_net_units_flag]           CHAR (1)        NULL,
    [dim_club_key]                                       CHAR (32)       NULL,
    [dim_crm_system_user_key]                            CHAR (32)       NULL,
    [employee_active_flag]                               CHAR (1)        NULL,
    [employee_name]                                      VARCHAR (200)   NULL,
    [employee_name_last_first]                           VARCHAR (200)   NULL,
    [first_name]                                         VARCHAR (50)    NULL,
    [full_name]                                          VARCHAR (400)   NULL,
    [hire_date]                                          DATETIME        NULL,
    [inserted_date_time]                                 DATETIME        NULL,
    [internal_email_address]                             VARCHAR (400)   NULL,
    [is_disabled]                                        CHAR (1)        NULL,
    [is_disabled_name]                                   VARCHAR (400)   NULL,
    [is_primary]                                         NVARCHAR (255)  NULL,
    [job_codes]                                          VARCHAR (400)   NULL,
    [job_families]                                       VARCHAR (400)   NULL,
    [job_levels]                                         VARCHAR (400)   NULL,
    [job_profiles]                                       VARCHAR (400)   NULL,
    [job_sub_families]                                   VARCHAR (400)   NULL,
    [job_title]                                          VARCHAR (400)   NULL,
    [last_name]                                          VARCHAR (50)    NULL,
    [ltf_club_id]                                        VARCHAR (36)    NULL,
    [ltf_club_id_name]                                   NVARCHAR (100)  NULL,
    [manager_dim_employee_key]                           CHAR (32)       NULL,
    [manager_id]                                         INT             NULL,
    [marketing_titles]                                   VARCHAR (400)   NULL,
    [member_id]                                          INT             NULL,
    [membership_sales_group_ind]                         CHAR (1)        NULL,
    [membership_sales_manager_ind]                       CHAR (1)        NULL,
    [middle_name]                                        NVARCHAR (50)   NULL,
    [mms_club_id]                                        VARCHAR (400)   NULL,
    [modified_by_name]                                   NVARCHAR (200)  NULL,
    [modified_on]                                        DATETIME        NULL,
    [overridden_created_on]                              DATETIME        NULL,
    [pay_rate_for_all_positions]                         NVARCHAR (4000) NULL,
    [phone_number]                                       VARCHAR (400)   NULL,
    [preferred_first_name]                               VARCHAR (400)   NULL,
    [preferred_last_name]                                VARCHAR (400)   NULL,
    [preferred_middle_name]                              VARCHAR (400)   NULL,
    [primary_work_email]                                 VARCHAR (400)   NULL,
    [queue_id]                                           VARCHAR (36)    NULL,
    [queue_id_name]                                      NVARCHAR (400)  NULL,
    [salutation]                                         NVARCHAR (20)   NULL,
    [subordinates]                                       VARCHAR (400)   NULL,
    [system_user_id]                                     VARCHAR (36)    NULL,
    [termination_date]                                   DATETIME        NULL,
    [title]                                              NVARCHAR (128)  NULL,
    [updated_date_time]                                  DATETIME        NULL,
    [utc_conversion_time_zone_code]                      INT             NULL,
    [workday_club_id]                                    NVARCHAR (4000) NULL,
    [dv_load_date_time]                                  DATETIME        NULL,
    [dv_load_end_date_time]                              DATETIME        NULL,
    [dv_batch_id]                                        BIGINT          NOT NULL,
    [dv_inserted_date_time]                              DATETIME        NOT NULL,
    [dv_insert_user]                                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                               DATETIME        NULL,
    [dv_update_user]                                     VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([dim_employee_key]));

