CREATE TABLE [dbo].[dim_spabiz_customer] (
    [dim_spabiz_customer_id]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [address_city]                 VARCHAR (150)   NULL,
    [address_country]              VARCHAR (150)   NULL,
    [address_line_1]               VARCHAR (765)   NULL,
    [address_line_2]               VARCHAR (360)   NULL,
    [address_postal_code]          VARCHAR (150)   NULL,
    [address_state_or_province]    VARCHAR (30)    NULL,
    [allergies]                    VARCHAR (300)   NULL,
    [balance]                      DECIMAL (26, 6) NULL,
    [call_days]                    INT             NULL,
    [communicate_via_email_flag]   CHAR (1)        NULL,
    [created_date_time]            DATETIME        NULL,
    [credit_limit]                 DECIMAL (26, 6) NULL,
    [cust_card_member_id_flag]     CHAR (1)        NULL,
    [customer_id]                  DECIMAL (26, 6) NULL,
    [customer_member_id]           BIGINT          NULL,
    [customer_type_id]             VARCHAR (50)    NULL,
    [date_of_birth]                VARCHAR (30)    NULL,
    [deleted_date_time]            DATETIME        NULL,
    [deleted_flag]                 CHAR (1)        NULL,
    [dim_mms_member_key]           CHAR (32)       NULL,
    [dim_mms_membership_key]       CHAR (32)       NULL,
    [dim_spabiz_customer_key]      CHAR (32)       NULL,
    [do_not_charge_tax_flag]       CHAR (1)        NULL,
    [do_not_print_note_flag]       CHAR (1)        NULL,
    [edit_date_time]               DATETIME        NULL,
    [email]                        VARCHAR (150)   NULL,
    [employer]                     VARCHAR (150)   NULL,
    [first_initial_last_name]      VARCHAR (150)   NULL,
    [first_name]                   VARCHAR (150)   NULL,
    [first_visit_date_time]        DATETIME        NULL,
    [gender_abbreviation]          CHAR (1)        NULL,
    [home_phone_number]            VARCHAR (42)    NULL,
    [last_appointment_date_time]   DATETIME        NULL,
    [last_called_date_time]        DATETIME        NULL,
    [last_name]                    VARCHAR (150)   NULL,
    [marital_status_id]            VARCHAR (50)    NULL,
    [medication]                   VARCHAR (300)   NULL,
    [member_id]                    VARCHAR (300)   NULL,
    [membership_id]                DECIMAL (26, 6) NULL,
    [middle_name]                  VARCHAR (150)   NULL,
    [mobile_phone_number]          VARCHAR (42)    NULL,
    [note]                         VARCHAR (4000)  NULL,
    [note_1]                       VARCHAR (1500)  NULL,
    [occupation]                   VARCHAR (150)   NULL,
    [pager_number]                 VARCHAR (42)    NULL,
    [primary_dim_spabiz_staff_key] CHAR (32)       NULL,
    [quick_id]                     VARCHAR (150)   NULL,
    [show_note_flag]               CHAR (1)        NULL,
    [store_number]                 BIGINT          NULL,
    [title]                        VARCHAR (150)   NULL,
    [total_late_show]              INT             NULL,
    [total_no_show]                INT             NULL,
    [total_products_purchased]     DECIMAL (26, 6) NULL,
    [total_services_purchased]     DECIMAL (26, 6) NULL,
    [total_visits]                 INT             NULL,
    [urgent_meesage_flag]          CHAR (1)        NULL,
    [work_fax]                     VARCHAR (42)    NULL,
    [work_phone_extension]         VARCHAR (12)    NULL,
    [work_phone_number]            VARCHAR (42)    NULL,
    [ytd_spent_on_products]        DECIMAL (26, 6) NULL,
    [ytd_spent_on_services]        DECIMAL (26, 6) NULL,
    [dv_load_date_time]            DATETIME        NULL,
    [dv_load_end_date_time]        DATETIME        NULL,
    [dv_batch_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]         DATETIME        NULL,
    [dv_update_user]               VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([dim_spabiz_customer_key]));

