CREATE TABLE [dbo].[dim_exerp_activity] (
    [dim_exerp_activity_id]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [access_group_id]                  INT            NULL,
    [activity_group_name]              VARCHAR (4000) NULL,
    [activity_group_state]             VARCHAR (4000) NULL,
    [activity_id]                      INT            NULL,
    [activity_name]                    VARCHAR (4000) NULL,
    [activity_state]                   VARCHAR (4000) NULL,
    [activity_type]                    VARCHAR (4000) NULL,
    [book_api_flag]                    CHAR (1)       NULL,
    [book_client_flag]                 CHAR (1)       NULL,
    [book_kiosk_flag]                  CHAR (1)       NULL,
    [book_mobile_api_flag]             CHAR (1)       NULL,
    [book_web_flag]                    CHAR (1)       NULL,
    [color]                            VARCHAR (4000) NULL,
    [course_schedule_type]             VARCHAR (4000) NULL,
    [department]                       VARCHAR (4000) NULL,
    [description]                      VARCHAR (4000) NULL,
    [dim_boss_product_key]             CHAR (32)      NULL,
    [dim_exerp_activity_group_key]     VARCHAR (32)   NULL,
    [dim_exerp_activity_key]           CHAR (32)      NULL,
    [dim_exerp_age_group_key]          VARCHAR (32)   NULL,
    [dim_exerp_time_configuration_key] VARCHAR (32)   NULL,
    [dim_mms_product_key]              VARCHAR (32)   NULL,
    [external_id]                      VARCHAR (4000) NULL,
    [max_participants]                 INT            NULL,
    [max_waiting_list_participants]    INT            NULL,
    [sku]                              VARCHAR (4000) NULL,
    [time_configuration_id]            INT            NULL,
    [dv_load_date_time]                DATETIME       NULL,
    [dv_load_end_date_time]            DATETIME       NULL,
    [dv_batch_id]                      BIGINT         NOT NULL,
    [dv_inserted_date_time]            DATETIME       NOT NULL,
    [dv_insert_user]                   VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]             DATETIME       NULL,
    [dv_update_user]                   VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([dim_exerp_activity_key]));

