CREATE TABLE [dbo].[etl_step_1] (
    [fact_mms_sales_transaction_item_key]       CHAR (32)       NULL,
    [tran_item_id]                              INT             NULL,
    [post_dim_date_key]                         CHAR (8)        NULL,
    [month_ending_post_dim_date_key]            CHAR (8)        NULL,
    [dim_club_key]                              CHAR (32)       NULL,
    [dim_mms_product_key]                       CHAR (32)       NULL,
    [dim_mms_member_key]                        CHAR (32)       NULL,
    [primary_sales_dim_employee_key]            VARCHAR (32)    NULL,
    [secondary_sales_dim_employee_key]          VARCHAR (32)    NULL,
    [dim_mms_transaction_reason_key]            CHAR (32)       NULL,
    [mms_tran_id]                               INT             NULL,
    [fact_mms_sales_transaction_key]            CHAR (32)       NOT NULL,
    [corporate_rate_count]                      INT             NOT NULL,
    [sales_dollar_amount]                       DECIMAL (26, 6) NULL,
    [sales_quantity]                            INT             NULL,
    [refund_flag]                               CHAR (1)        NULL,
    [voided_flag]                               CHAR (1)        NULL,
    [reversal_flag]                             CHAR (1)        NULL,
    [original_mms_tran_id]                      INT             NULL,
    [original_fact_mms_sales_transaction_key]   CHAR (32)       NULL,
    [transaction_edited_flag]                   CHAR (1)        NULL,
    [membership_charge_flag]                    CHAR (1)        NULL,
    [membership_adjustment_flag]                CHAR (1)        NULL,
    [pos_flag]                                  CHAR (1)        NULL,
    [step1_udw_inserted_dim_date_key]           CHAR (32)       NULL,
    [sales_entered_dim_employee_key]            CHAR (32)       NULL,
    [sales_discount_dollar_amount]              DECIMAL (26, 6) NULL,
    [post_dim_time_key]                         INT             NULL,
    [original_currency_code]                    CHAR (3)        NULL,
    [usd_monthly_average_dim_exchange_rate_key] CHAR (32)       NULL,
    [usd_dim_plan_exchange_rate_key]            CHAR (32)       NULL,
    [transaction_reporting_dim_club_key]        VARCHAR (32)    NULL,
    [dim_mms_drawer_activity_key]               VARCHAR (32)    NULL,
    [void_dim_date_key]                         VARCHAR (32)    NULL,
    [void_dim_time_key]                         INT             NULL,
    [void_dim_employee_key]                     VARCHAR (32)    NULL,
    [sales_channel_dim_description_key]         VARCHAR (65)    NULL,
    [dim_mms_reimbursement_program_key]         CHAR (32)       NULL,
    [void_comment]                              VARCHAR (50)    NULL,
    [receipt_number]                            VARCHAR (50)    NULL,
    [receipt_comment]                           VARCHAR (255)   NULL,
    [sales_tax_amount]                          DECIMAL (26, 6) NULL,
    [sold_not_serviced_flag]                    CHAR (1)        NULL,
    [automated_refund_flag]                     VARCHAR (1)     NOT NULL,
    [sales_amount_gross]                        DECIMAL (26, 6) NULL,
    [membership_id]                             INT             NULL,
    [dim_mms_membership_key]                    CHAR (32)       NULL,
    [active_transaction_flag]                   VARCHAR (1)     NOT NULL,
    [dv_load_date_time]                         DATETIME        NULL,
    [dv_load_end_date_time]                     VARCHAR (12)    NOT NULL,
    [dv_batch_id]                               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([fact_mms_sales_transaction_key]));

