CREATE TABLE [dbo].[fact_mms_payment] (
    [fact_mms_payment_id]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [approval_code]                      VARCHAR (50)    NULL,
    [automated_refund_flag]              CHAR (1)        NULL,
    [dim_club_key]                       CHAR (32)       NULL,
    [dim_mms_drawer_activity_key]        CHAR (32)       NULL,
    [dim_mms_member_key]                 CHAR (32)       NULL,
    [dim_mms_membership_key]             CHAR (32)       NULL,
    [dim_mms_transaction_reason_key]     CHAR (32)       NULL,
    [fact_mms_payment_key]               CHAR (32)       NULL,
    [mms_tran_id]                        INT             NULL,
    [payment_amount]                     NUMERIC (12, 2) NULL,
    [payment_dim_date_key]               CHAR (8)        NULL,
    [payment_dim_time_key]               CHAR (8)        NULL,
    [payment_flag]                       CHAR (1)        NULL,
    [payment_id]                         INT             NULL,
    [payment_status_dim_description_key] VARCHAR (255)   NULL,
    [payment_type_dim_description_key]   NVARCHAR (100)  NULL,
    [pos_flag]                           CHAR (1)        NULL,
    [refund_flag]                        CHAR (1)        NULL,
    [refunded_flag]                      CHAR (1)        NULL,
    [sales_entered_dim_employee_key]     CHAR (32)       NULL,
    [tip_amount]                         NUMERIC (12, 2) NULL,
    [transaction_reporting_dim_club_key] CHAR (32)       NULL,
    [voided_flag]                        CHAR (1)        NULL,
    [dv_load_date_time]                  DATETIME        NULL,
    [dv_load_end_date_time]              DATETIME        NULL,
    [dv_batch_id]                        BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_mms_payment_key]));

