CREATE TABLE [dbo].[fact_magento_transaction_item] (
    [fact_magento_transaction_item_id]                                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [allocated_amount]                                                           DECIMAL (12, 2) NULL,
    [allocated_dim_club_key]                                                     VARCHAR (32)    NULL,
    [allocated_month_starting_dim_date_key]                                      VARCHAR (8)     NULL,
    [allocated_recalculate_through_datetime]                                     DATETIME        NULL,
    [allocated_recalculate_through_dim_date_key]                                 VARCHAR (8)     NULL,
    [batch_number]                                                               INT             NULL,
    [bucks_change]                                                               DECIMAL (12, 2) NULL,
    [cc_last_4]                                                                  INT             NULL,
    [credit_tran_id]                                                             INT             NULL,
    [dim_club_key]                                                               VARCHAR (32)    NULL,
    [dim_employee_key]                                                           VARCHAR (32)    NULL,
    [dim_magento_customer_key]                                                   VARCHAR (32)    NULL,
    [dim_magento_product_key]                                                    VARCHAR (32)    NULL,
    [dim_mms_member_key]                                                         VARCHAR (32)    NULL,
    [dim_mms_membership_key]                                                     VARCHAR (32)    NULL,
    [employee_id]                                                                INT             NULL,
    [fact_magento_invoice_item_key]                                              VARCHAR (32)    NULL,
    [fact_magento_refund_item_key]                                               VARCHAR (32)    NULL,
    [fact_mms_transaction_key]                                                   VARCHAR (32)    NULL,
    [invoice_datetime]                                                           DATETIME        NULL,
    [invoice_dim_date_key]                                                       VARCHAR (8)     NULL,
    [member_id]                                                                  INT             NULL,
    [mms_tran_id]                                                                INT             NULL,
    [order_datetime]                                                             DATETIME        NULL,
    [order_dim_date_key]                                                         VARCHAR (8)     NULL,
    [order_id]                                                                   INT             NULL,
    [order_item_id]                                                              INT             NULL,
    [order_number]                                                               VARCHAR (32)    NULL,
    [original_currency_code]                                                     VARCHAR (3)     NULL,
    [payment_type]                                                               VARCHAR (50)    NULL,
    [payroll_dim_club_key]                                                       VARCHAR (32)    NULL,
    [product_cost]                                                               DECIMAL (12, 2) NULL,
    [product_price]                                                              DECIMAL (12, 2) NULL,
    [refund_datetime]                                                            DATETIME        NULL,
    [refund_dim_date_key]                                                        VARCHAR (8)     NULL,
    [refund_flag]                                                                CHAR (1)        NULL,
    [shipping_amount]                                                            DECIMAL (12, 2) NULL,
    [shipping_state]                                                             VARCHAR (50)    NULL,
    [shipping_tax_amount]                                                        DECIMAL (12, 2) NULL,
    [transaction_adjustment_amount]                                              DECIMAL (12, 2) NULL,
    [transaction_amount]                                                         DECIMAL (12, 2) NULL,
    [transaction_bucks_amount]                                                   DECIMAL (12, 2) NULL,
    [transaction_datetime]                                                       DATETIME        NULL,
    [transaction_dim_date_key]                                                   VARCHAR (8)     NULL,
    [transaction_discount_amount]                                                DECIMAL (12, 2) NULL,
    [transaction_item_amount]                                                    DECIMAL (12, 2) NULL,
    [transaction_quantity]                                                       INT             NULL,
    [transaction_reporting_dim_club_key]                                         VARCHAR (32)    NULL,
    [transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key] VARCHAR (32)    NULL,
    [transaction_tax_amount]                                                     DECIMAL (12, 2) NULL,
    [udw_inserted_dim_date_key]                                                  VARCHAR (8)     NULL,
    [usd_daily_dim_exchange_rate_key]                                            VARCHAR (32)    NULL,
    [usd_dim_plan_exchange_rate_key]                                             VARCHAR (32)    NULL,
    [usd_monthly_average_dim_exchange_rate_key]                                  VARCHAR (32)    NULL,
    [dv_load_date_time]                                                          DATETIME        NULL,
    [dv_load_end_date_time]                                                      DATETIME        NULL,
    [dv_batch_id]                                                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                                                      DATETIME        NOT NULL,
    [dv_insert_user]                                                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                                       DATETIME        NULL,
    [dv_update_user]                                                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);

