CREATE TABLE [dbo].[fact_exerp_subscription_sale] (
    [fact_exerp_subscription_sale_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [admin_fee_discount]                  DECIMAL (26, 6) NULL,
    [admin_fee_member]                    DECIMAL (26, 6) NULL,
    [admin_fee_normal_price]              DECIMAL (26, 6) NULL,
    [admin_fee_price]                     DECIMAL (26, 6) NULL,
    [admin_fee_sponsored]                 DECIMAL (26, 6) NULL,
    [binding_days]                        INT             NULL,
    [dim_club_key]                        VARCHAR (32)    NULL,
    [dim_exerp_product_key]               VARCHAR (32)    NULL,
    [dim_exerp_subscription_key]          VARCHAR (32)    NULL,
    [dim_mms_member_key]                  VARCHAR (32)    NULL,
    [end_dim_date_key]                    CHAR (8)        NULL,
    [fact_exerp_subscription_sale_key]    VARCHAR (32)    NULL,
    [init_contract_value]                 DECIMAL (26, 6) NULL,
    [init_period_discount]                DECIMAL (26, 6) NULL,
    [init_period_member]                  DECIMAL (26, 6) NULL,
    [init_period_normal_price]            DECIMAL (26, 6) NULL,
    [init_period_price]                   DECIMAL (26, 6) NULL,
    [init_period_sponsored]               DECIMAL (26, 6) NULL,
    [jf_discount]                         DECIMAL (26, 6) NULL,
    [jf_fact_exerp_transaction_log_key]   VARCHAR (32)    NULL,
    [jf_member]                           DECIMAL (26, 6) NULL,
    [jf_normal_price]                     DECIMAL (26, 6) NULL,
    [jf_price]                            DECIMAL (26, 6) NULL,
    [jf_sponsored]                        DECIMAL (26, 6) NULL,
    [previous_dim_exerp_subscription_key] VARCHAR (32)    NULL,
    [prorata_period_discount]             DECIMAL (26, 6) NULL,
    [prorata_period_member]               DECIMAL (26, 6) NULL,
    [prorata_period_normal_price]         DECIMAL (26, 6) NULL,
    [prorata_period_price]                DECIMAL (26, 6) NULL,
    [prorata_period_sponsored]            DECIMAL (26, 6) NULL,
    [sale_dim_date_key]                   CHAR (8)        NULL,
    [sale_dim_employee_key]               VARCHAR (32)    NULL,
    [sale_dim_time_key]                   CHAR (8)        NULL,
    [sale_id]                             VARCHAR (4000)  NULL,
    [start_dim_date_key]                  CHAR (8)        NULL,
    [subscription_dim_club_key]           VARCHAR (32)    NULL,
    [subscription_sale_id]                INT             NULL,
    [subscription_sale_state]             VARCHAR (4000)  NULL,
    [subscription_sale_type]              VARCHAR (4000)  NULL,
    [dv_load_date_time]                   DATETIME        NULL,
    [dv_load_end_date_time]               DATETIME        NULL,
    [dv_batch_id]                         BIGINT          NOT NULL,
    [dv_inserted_date_time]               DATETIME        NOT NULL,
    [dv_insert_user]                      VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                DATETIME        NULL,
    [dv_update_user]                      VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_exerp_subscription_sale_key]));

