CREATE TABLE [dbo].[fact_humanity_schedule] (
    [shift_id]               BIGINT        NOT NULL,
    [company_id]             VARCHAR (255) NULL,
    [company_name]           VARCHAR (255) NULL,
    [employee_id]            VARCHAR (255) NULL,
    [employee_eid]           VARCHAR (255) NULL,
    [employee_name]          VARCHAR (255) NULL,
    [location_id]            VARCHAR (255) NULL,
    [location_name]          VARCHAR (255) NULL,
    [position_id]            VARCHAR (255) NULL,
    [workday_position_id]    VARCHAR (255) NULL,
    [position_name]          VARCHAR (255) NULL,
    [shift_start_date_utc]   VARCHAR (255) NULL,
    [shift_start_time]       VARCHAR (255) NULL,
    [shift_end_date_utc]     VARCHAR (255) NULL,
    [shift_end_time]         VARCHAR (255) NULL,
    [hours]                  VARCHAR (255) NULL,
    [wage]                   VARCHAR (255) NULL,
    [published]              VARCHAR (255) NULL,
    [published_datetime_utc] VARCHAR (255) NULL,
    [shift_type]             VARCHAR (255) NULL,
    [employees_needed]       VARCHAR (255) NULL,
    [employees_working]      VARCHAR (255) NULL,
    [recurring_shift]        VARCHAR (255) NULL,
    [created_by_id]          VARCHAR (255) NULL,
    [created_by_eid]         VARCHAR (255) NULL,
    [created_by_name]        VARCHAR (255) NULL,
    [created_datetime_utc]   VARCHAR (255) NULL,
    [updated_at_utc]         VARCHAR (255) NULL,
    [notes]                  VARCHAR (255) NULL,
    [is_deleted]             VARCHAR (255) NULL,
    [dv_inserted_date_time]  DATETIME      NOT NULL,
    [dv_insert_user]         VARCHAR (100) NOT NULL,
    [file_arrive_date]       VARCHAR (255) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

