CREATE TABLE [dbo].[fact_magento_order_item] (
    [fact_magento_order_item_id]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [dim_club_key]                       VARCHAR (32)    NULL,
    [dim_employee_key]                   VARCHAR (32)    NULL,
    [dim_magento_customer_key]           VARCHAR (32)    NULL,
    [dim_magento_product_key]            VARCHAR (32)    NULL,
    [dim_mms_member_key]                 VARCHAR (32)    NULL,
    [fact_magento_order_item_key]        VARCHAR (32)    NULL,
    [fact_magento_order_key]             VARCHAR (32)    NULL,
    [item_base_price]                    DECIMAL (12, 2) NULL,
    [item_bucks_amount]                  INT             NULL,
    [item_bucks_per_quantity]            DECIMAL (16, 6) NULL,
    [item_discount_amount]               DECIMAL (12, 2) NULL,
    [item_quantity]                      INT             NULL,
    [item_refund_bucks_amount]           INT             NULL,
    [item_refund_bucks_per_quantity]     DECIMAL (16, 6) NULL,
    [item_tax_amount]                    DECIMAL (12, 2) NULL,
    [item_total_amount]                  DECIMAL (12, 2) NULL,
    [order_currency_code]                VARCHAR (3)     NULL,
    [order_datetime]                     DATETIME        NULL,
    [order_dim_date_key]                 VARCHAR (8)     NULL,
    [order_id]                           INT             NULL,
    [order_item_id]                      INT             NULL,
    [order_number]                       VARCHAR (32)    NULL,
    [order_shipping_amount]              DECIMAL (12, 2) NULL,
    [order_status]                       VARCHAR (32)    NULL,
    [parent_fact_magento_order_item_key] VARCHAR (32)    NULL,
    [shipping_state]                     VARCHAR (32)    NULL,
    [dv_load_date_time]                  DATETIME        NULL,
    [dv_load_end_date_time]              DATETIME        NULL,
    [dv_batch_id]                        BIGINT          NOT NULL,
    [dv_inserted_date_time]              DATETIME        NOT NULL,
    [dv_insert_user]                     VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]               DATETIME        NULL,
    [dv_update_user]                     VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_magento_order_item_key]));

