CREATE TABLE [dbo].[fact_spabiz_customer_summary] (
    [fact_spabiz_customer_summary_id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [dim_spabiz_customer_key]                           CHAR (32)       NULL,
    [latest_body_fact_spabiz_ticket_item_key]           CHAR (32)       NULL,
    [latest_body_ticket_item_date_time]                 DATETIME        NULL,
    [latest_hair_fact_spabiz_ticket_item_key]           CHAR (32)       NULL,
    [latest_hair_ticket_item_date_time]                 DATETIME        NULL,
    [latest_medi_fact_spabiz_ticket_item_key]           CHAR (32)       NULL,
    [latest_medi_ticket_item_date_time]                 DATETIME        NULL,
    [latest_nail_fact_spabiz_ticket_item_key]           CHAR (32)       NULL,
    [latest_nail_ticket_item_date_time]                 DATETIME        NULL,
    [latest_purchase_date_time]                         DATETIME        NULL,
    [latest_purchase_fact_spabiz_ticket_item_key]       CHAR (32)       NULL,
    [latest_skin_fact_spabiz_ticket_item_key]           CHAR (32)       NULL,
    [latest_skin_ticket_item_date_time]                 DATETIME        NULL,
    [next_appointment_date_time]                        DATETIME        NULL,
    [next_appointment_fact_spabiz_appointment_item_key] CHAR (32)       NULL,
    [next_body_appointment_date_time]                   DATETIME        NULL,
    [next_body_fact_spabiz_appointment_item_key]        CHAR (32)       NULL,
    [next_hair_appointment_date_time]                   DATETIME        NULL,
    [next_hair_fact_spabiz_appointment_item_key]        CHAR (32)       NULL,
    [next_medi_appointment_date_time]                   DATETIME        NULL,
    [next_medi_fact_spabiz_appointment_item_key]        CHAR (32)       NULL,
    [next_nail_appointment_date_time]                   DATETIME        NULL,
    [next_nail_fact_spabiz_appointment_item_key]        CHAR (32)       NULL,
    [next_skin_appointment_date_time]                   DATETIME        NULL,
    [next_skin_fact_spabiz_appointment_item_key]        CHAR (32)       NULL,
    [yearly_body_service_amount]                        DECIMAL (26, 6) NULL,
    [yearly_body_service_quantity]                      BIGINT          NULL,
    [yearly_hair_service_amount]                        DECIMAL (26, 6) NULL,
    [yearly_hair_service_quantity]                      BIGINT          NULL,
    [yearly_medi_service_amount]                        DECIMAL (26, 6) NULL,
    [yearly_medi_service_quantity]                      BIGINT          NULL,
    [yearly_nail_service_amount]                        DECIMAL (26, 6) NULL,
    [yearly_nail_service_quantity]                      BIGINT          NULL,
    [yearly_product_amount]                             DECIMAL (26, 6) NULL,
    [yearly_product_quantity]                           BIGINT          NULL,
    [yearly_service_amount]                             DECIMAL (26, 6) NULL,
    [yearly_service_quantity]                           BIGINT          NULL,
    [yearly_skin_service_amount]                        DECIMAL (26, 6) NULL,
    [yearly_skin_service_quantity]                      BIGINT          NULL,
    [dv_load_date_time]                                 DATETIME        NULL,
    [dv_load_end_date_time]                             DATETIME        NULL,
    [dv_batch_id]                                       BIGINT          NOT NULL,
    [dv_inserted_date_time]                             DATETIME        NOT NULL,
    [dv_insert_user]                                    VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                              DATETIME        NULL,
    [dv_update_user]                                    VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([dim_spabiz_customer_key]));

