CREATE TABLE [dbo].[fact_mms_sales_transaction_item_automated_refund] (
    [fact_mms_sales_transaction_item_automated_refund_id]                                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [fact_mms_sales_transaction_item_automated_refund_key]                                CHAR (32)       NULL,
    [item_lt_bucks_sales_tax]                                                             DECIMAL (26, 6) NULL,
    [original_dim_club_key]                                                               CHAR (32)       NULL,
    [original_dim_mms_reimbursement_program_key]                                          CHAR (32)       NULL,
    [original_fact_sales_transaction_edw_inserted_dim_date_key]                           CHAR (8)        NULL,
    [original_fact_sales_transaction_item_key]                                            CHAR (32)       NULL,
    [original_mms_tran_id]                                                                INT             NULL,
    [original_post_dim_date_key]                                                          CHAR (8)        NULL,
    [original_primary_sales_dim_employee_key]                                             CHAR (32)       NULL,
    [original_sales_channel_dim_description_key]                                          VARCHAR (255)   NULL,
    [original_secondary_sales_dim_employee_key]                                           CHAR (32)       NULL,
    [original_sold_not_serviced_flag]                                                     CHAR (1)        NULL,
    [original_tran_item_id]                                                               INT             NULL,
    [original_transaction_reporting_dim_club_key]                                         CHAR (32)       NULL,
    [original_transaction_reporting_local_currency_dim_plan_exchange_rate_key]            CHAR (32)       NULL,
    [original_transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key] CHAR (32)       NULL,
    [refund_amount_gross]                                                                 DECIMAL (26, 6) NULL,
    [refund_dim_club_key]                                                                 CHAR (32)       NULL,
    [refund_dim_mms_drawer_activity_key]                                                  CHAR (32)       NULL,
    [refund_dim_mms_member_key]                                                           CHAR (32)       NULL,
    [refund_dim_mms_product_key]                                                          CHAR (32)       NULL,
    [refund_dim_mms_reimbursement_program_key]                                            CHAR (32)       NULL,
    [refund_dim_mms_transaction_reason_key]                                               CHAR (32)       NULL,
    [refund_discount_dollar_amount]                                                       DECIMAL (26, 6) NULL,
    [refund_dollar_amount]                                                                DECIMAL (26, 6) NULL,
    [refund_entered_dim_employee_key]                                                     CHAR (32)       NULL,
    [refund_fact_mms_sales_transaction_item_key]                                          CHAR (32)       NULL,
    [refund_mms_tran_id]                                                                  INT             NULL,
    [refund_original_currency_code]                                                       CHAR (3)        NULL,
    [refund_post_dim_date_key]                                                            CHAR (32)       NULL,
    [refund_post_dim_time_key]                                                            CHAR (8)        NULL,
    [refund_quantity]                                                                     INT             NULL,
    [refund_receipt_comment]                                                              VARCHAR (255)   NULL,
    [refund_receipt_number]                                                               VARCHAR (50)    NULL,
    [refund_tax_amount]                                                                   DECIMAL (26, 6) NULL,
    [refund_tran_item_id]                                                                 INT             NULL,
    [refund_usd_dim_plan_exchange_rate_key]                                               CHAR (32)       NULL,
    [refund_usd_monthly_average_dim_exchange_rate_key]                                    CHAR (32)       NULL,
    [refund_void_comment]                                                                 VARCHAR (50)    NULL,
    [refund_void_dim_date_key]                                                            CHAR (8)        NULL,
    [refund_void_dim_employee_key]                                                        CHAR (32)       NULL,
    [refund_void_dim_time_key]                                                            CHAR (8)        NULL,
    [refund_void_flag]                                                                    CHAR (1)        NULL,
    [refund_voided_flag]                                                                  CHAR (1)        NULL,
    [tran_item_refund_id]                                                                 INT             NULL,
    [transaction_reporting_dim_club_key]                                                  CHAR (32)       NULL,
    [transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key]          CHAR (32)       NULL,
    [transaction_reporting_local_currency_monthly_average_dim_plan_exchange_rate_key]     CHAR (32)       NULL,
    [udw_inserted_dim_date_key]                                                           CHAR (32)       NULL,
    [dv_load_date_time]                                                                   DATETIME        NULL,
    [dv_load_end_date_time]                                                               DATETIME        NULL,
    [dv_batch_id]                                                                         BIGINT          NOT NULL,
    [dv_inserted_date_time]                                                               DATETIME        NOT NULL,
    [dv_insert_user]                                                                      VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                                                DATETIME        NULL,
    [dv_update_user]                                                                      VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_mms_sales_transaction_item_automated_refund_key]));

