CREATE TABLE [dbo].[fact_olo_order_detail] (
    [fact_olo_order_detail_id]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [batch_id]                    VARCHAR (50)    NULL,
    [company_id]                  VARCHAR (50)    NULL,
    [cost_center_id]              VARCHAR (50)    NULL,
    [currency_id]                 VARCHAR (50)    NULL,
    [deposit]                     VARCHAR (50)    NULL,
    [discount_amount]             DECIMAL (26, 2) NULL,
    [drawer_close_comments]       NVARCHAR (500)  NULL,
    [drawer_id]                   NVARCHAR (500)  NULL,
    [posted_date]                 DATETIME        NULL,
    [region_id]                   VARCHAR (50)    NULL,
    [shipping_amount]             DECIMAL (26, 2) NULL,
    [tender_type_id]              VARCHAR (50)    NULL,
    [transaction_amount]          DECIMAL (26, 2) NULL,
    [transaction_date]            DATETIME        NULL,
    [transaction_id]              NVARCHAR (500)  NULL,
    [transaction_line_amount]     DECIMAL (26, 2) NULL,
    [transaction_line_memo]       NVARCHAR (500)  NULL,
    [transaction_line_tax_amount] DECIMAL (26, 2) NULL,
    [transaction_memo]            VARCHAR (200)   NULL,
    [withdrawal]                  VARCHAR (50)    NULL,
    [dv_load_date_time]           DATETIME        NULL,
    [dv_load_end_date_time]       DATETIME        NULL,
    [dv_batch_id]                 BIGINT          NOT NULL,
    [dv_inserted_date_time]       DATETIME        NOT NULL,
    [dv_insert_user]              VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]        DATETIME        NULL,
    [dv_update_user]              VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = REPLICATE);

