CREATE TABLE [dbo].[fact_mms_credit_card_offline_transaction] (
    [fact_mms_credit_card_offline_transaction_id]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [fact_mms_credit_card_offline_transaction_key]             CHAR (32)       NULL,
    [third_party_pos_payment_id]                               INT             NULL,
    [card_on_file_flag]                                        CHAR (1)        NULL,
    [credit_card_type_dim_mms_description_key]                 CHAR (32)       NULL,
    [declined_or_error_flag]                                   CHAR (1)        NULL,
    [dim_mms_customer_key]                                     CHAR (32)       NULL,
    [dim_mms_location_key]                                     CHAR (32)       NULL,
    [dim_mms_member_key]                                       CHAR (32)       NULL,
    [local_currency_dim_plan_exchange_rate_key]                CHAR (32)       NULL,
    [local_currency_monthly_average_dim_mms_exchange_rate_key] CHAR (32)       NULL,
    [masked_credit_card_number]                                VARCHAR (20)    NULL,
    [original_currency_code]                                   VARCHAR (15)    NULL,
    [payment_status_dim_mms_description_key]                   CHAR (32)       NULL,
    [pos_tran_date_time]                                       DATETIME        NULL,
    [pos_unique_transaction_id]                                VARCHAR (20)    NULL,
    [pt_credit_card_rejected_transaction_id]                   INT             NULL,
    [rejected_transaction_date_time]                           DATETIME        NULL,
    [rejected_transaction_error_message]                       VARCHAR (50)    NULL,
    [timed_out_flag]                                           CHAR (1)        NULL,
    [transaction_amount]                                       DECIMAL (26, 6) NULL,
    [usd_dim_plan_exchange_rate_key]                           CHAR (32)       NULL,
    [usd_monthy_average_dim_exchange_rate_key]                 CHAR (32)       NULL,
    [dv_load_date_time]                                        DATETIME        NULL,
    [dv_load_end_date_time]                                    DATETIME        NULL,
    [dv_batch_id]                                              BIGINT          NULL,
    [dv_inserted_date_time]                                    DATETIME        NOT NULL,
    [dv_insert_user]                                           VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                     DATETIME        NULL,
    [dv_update_user]                                           VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = HASH([fact_mms_credit_card_offline_transaction_key]));

