CREATE TABLE [dbo].[fact_commprefs_user_preferences] (
    [fact_commprefs_user_preferences_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [ae_last_sent_date]                  DATETIME      NULL,
    [ae_total_sent]                      INT           NULL,
    [el_last_sent_date]                  DATETIME      NULL,
    [el_total_sent]                      INT           NULL,
    [email_address]                      VARCHAR (255) NULL,
    [first_sent_date]                    DATETIME      NULL,
    [flourish_opt_in]                    BIT           NULL,
    [global_opt_in]                      BIT           NULL,
    [global_opt_status_from_date]        DATETIME      NULL,
    [invalid_bounce]                     BIT           NULL,
    [invalid_bounce_date]                DATETIME      NULL,
    [last_bounce_date]                   DATETIME      NULL,
    [last_click_date]                    DATETIME      NULL,
    [last_engagement_date]               DATETIME      NULL,
    [last_open_date]                     DATETIME      NULL,
    [last_sent_date]                     DATETIME      NULL,
    [lt_insider_opt_in]                  BIT           NULL,
    [no_engagement_12_months]            BIT           NULL,
    [no_engagement_13_months]            BIT           NULL,
    [no_engagement_3_months]             BIT           NULL,
    [no_engagement_6_months]             BIT           NULL,
    [notifications_opt_in]               BIT           NULL,
    [promotional_opt_in]                 BIT           NULL,
    [total_hard_bounces]                 INT           NULL,
    [total_sent]                         INT           NULL,
    [total_sent_after_last_engage]       INT           NULL,
    [dv_load_date_time]                  DATETIME      NULL,
    [dv_load_end_date_time]              DATETIME      NULL,
    [dv_batch_id]                        BIGINT        NOT NULL,
    [dv_inserted_date_time]              DATETIME      NOT NULL,
    [dv_insert_user]                     VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]               DATETIME      NULL,
    [dv_update_user]                     VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);

