CREATE TABLE [dbo].[fact_hybris_transaction_item] (
    [fact_hybris_transaction_item_id]                                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [affiliate_id]                                                               VARCHAR (255)   NULL,
    [allocated_dim_club_key]                                                     VARCHAR (32)    NULL,
    [allocated_month_starting_dim_date_key]                                      VARCHAR (8)     NULL,
    [allocated_recalculate_through_datetime]                                     DATETIME        NULL,
    [allocated_recalculate_through_dim_date_key]                                 VARCHAR (8)     NULL,
    [amex_amount]                                                                DECIMAL (26, 6) NULL,
    [auto_ship_flag]                                                             CHAR (1)        NULL,
    [bucks_amount]                                                               DECIMAL (26, 6) NULL,
    [club_id]                                                                    INT             NULL,
    [customer_email]                                                             VARCHAR (255)   NULL,
    [customer_group]                                                             VARCHAR (255)   NULL,
    [customer_name]                                                              VARCHAR (255)   NULL,
    [dim_club_key]                                                               CHAR (32)       NULL,
    [dim_hybris_product_key]                                                     CHAR (32)       NULL,
    [dim_mms_member_key]                                                         CHAR (32)       NULL,
    [dim_mms_membership_key]                                                     VARCHAR (32)    NULL,
    [discount_amount]                                                            DECIMAL (26, 6) NULL,
    [discover_amount]                                                            DECIMAL (26, 6) NULL,
    [entry_number]                                                               INT             NULL,
    [fact_hybris_transaction_item_key]                                           CHAR (32)       NULL,
    [fact_mms_sales_transaction_key]                                             VARCHAR (32)    NULL,
    [fulfillment_partner]                                                        VARCHAR (255)   NULL,
    [lt_bucks_earned]                                                            DECIMAL (26, 6) NULL,
    [mastercard_amount]                                                          DECIMAL (26, 6) NULL,
    [order_code]                                                                 VARCHAR (255)   NULL,
    [order_dim_date_key]                                                         CHAR (8)        NULL,
    [original_currency_code]                                                     CHAR (3)        NULL,
    [original_unit_price]                                                        DECIMAL (26, 6) NULL,
    [paypal_amount]                                                              DECIMAL (26, 6) NULL,
    [purchase_unit_price]                                                        DECIMAL (26, 6) NULL,
    [refund_flag]                                                                CHAR (1)        NULL,
    [refund_reason]                                                              VARCHAR (255)   NULL,
    [sales_dim_employee_key]                                                     CHAR (32)       NULL,
    [settlement_dim_date_key]                                                    CHAR (8)        NULL,
    [settlement_dim_time_key]                                                    INT             NULL,
    [shipping_and_handling_amount]                                               DECIMAL (26, 6) NULL,
    [tax_amount]                                                                 DECIMAL (26, 6) NULL,
    [tracking_number]                                                            NVARCHAR (255)  NULL,
    [transaction_amount]                                                         DECIMAL (26, 6) NULL,
    [transaction_amount_gross]                                                   DECIMAL (26, 6) NULL,
    [transaction_quantity]                                                       INT             NULL,
    [transaction_reporting_dim_club_key]                                         CHAR (32)       NULL,
    [transaction_reporting_local_currency_dim_plan_exchange_rate_key]            CHAR (32)       NULL,
    [transaction_reporting_local_currency_monthly_average_dim_exchange_rate_key] CHAR (32)       NULL,
    [udw_inserted_dim_date_key]                                                  CHAR (8)        NULL,
    [usd_daily_dim_exchange_rate_key]                                            CHAR (32)       NULL,
    [usd_dim_plan_exchange_rate_key]                                             CHAR (32)       NULL,
    [usd_monthly_average_dim_exchange_rate_key]                                  CHAR (32)       NULL,
    [visa_amount]                                                                DECIMAL (26, 6) NULL,
    [dv_load_date_time]                                                          DATETIME        NULL,
    [dv_load_end_date_time]                                                      DATETIME        NULL,
    [dv_batch_id]                                                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                                                      DATETIME        NOT NULL,
    [dv_insert_user]                                                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                                       DATETIME        NULL,
    [dv_update_user]                                                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_hybris_transaction_item_key]));

