CREATE TABLE [dbo].[fact_cafe_sales_transaction_item] (
    [fact_cafe_sales_transaction_item_id]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [check_number]                               INT             NULL,
    [check_seq]                                  INT             NULL,
    [dim_cafe_discount_coupon_key]               CHAR (32)       NULL,
    [dim_cafe_product_key]                       CHAR (32)       NULL,
    [dim_cafe_profit_center_key]                 CHAR (32)       NULL,
    [dim_club_key]                               CHAR (32)       NULL,
    [dim_mms_member_key]                         CHAR (32)       NULL,
    [fact_cafe_sales_transaction_item_key]       CHAR (32)       NULL,
    [item_discount_amount]                       DECIMAL (26, 6) NULL,
    [item_quantity]                              INT             NULL,
    [item_refund_flag]                           CHAR (1)        NULL,
    [item_sales_amount_gross]                    DECIMAL (26, 6) NULL,
    [item_sales_dollar_amount_excluding_tax]     DECIMAL (26, 6) NULL,
    [item_tax_amount]                            DECIMAL (26, 6) NULL,
    [item_voided_flag]                           CHAR (1)        NULL,
    [order_close_dim_date_key]                   CHAR (8)        NULL,
    [order_close_dim_time_key]                   CHAR (8)        NULL,
    [order_close_month_ending_dim_date_key]      CHAR (8)        NULL,
    [order_closed_flag]                          CHAR (1)        NULL,
    [order_commissionable_dim_employee_key]      CHAR (32)       NULL,
    [order_discount_amount]                      DECIMAL (26, 6) NULL,
    [order_hdr_id]                               INT             NULL,
    [order_open_dim_date_key]                    CHAR (8)        NULL,
    [order_open_dim_time_key]                    CHAR (8)        NULL,
    [order_refund_flag]                          CHAR (1)        NULL,
    [order_sales_amount_gross]                   DECIMAL (26, 6) NULL,
    [order_service_charge_amount]                DECIMAL (26, 6) NULL,
    [order_tax_amount]                           DECIMAL (26, 6) NULL,
    [order_tax_removed_flag]                     CHAR (1)        NULL,
    [order_tip_amount]                           DECIMAL (26, 6) NULL,
    [order_void_flag]                            CHAR (1)        NULL,
    [original_currency_code]                     CHAR (3)        NULL,
    [posted_business_end_dim_date_key]           CHAR (8)        NULL,
    [posted_business_start_dim_date_key]         CHAR (8)        NULL,
    [udw_inserted_dim_date_key]                  CHAR (8)        NULL,
    [usd_dim_plan_exchange_rate]                 CHAR (32)       NULL,
    [usd_monthly_average_dim_exchange_rate_key]  CHAR (32)       NULL,
    [dv_load_date_time]                          DATETIME        NULL,
    [dv_load_end_date_time]                      DATETIME        NULL,
    [dv_batch_id]                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                      DATETIME        NOT NULL,
    [dv_insert_user]                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                       DATETIME        NULL,
    [dv_update_user]                             VARCHAR (50)    NULL,
    [allocated_recalculate_through_dim_date_key] VARCHAR (8)     NULL,
    [allocated_recalculate_through_datetime]     DATETIME        NULL,
    [allocated_month_starting_dim_date_key]      VARCHAR (8)     NULL
)
WITH (HEAP, DISTRIBUTION = HASH([fact_cafe_sales_transaction_item_key]));

