CREATE TABLE [dbo].[fact_boss_daily_roster] (
    [fact_boss_daily_roster_id]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [asi_player_id]                  INT           NULL,
    [attendance_checked_in_flag]     CHAR (1)      NULL,
    [check_in_dim_date_key]          CHAR (8)      NULL,
    [check_in_dim_time_key]          CHAR (8)      NULL,
    [dim_boss_reservation_key]       CHAR (32)     NULL,
    [dim_mms_member_key]             CHAR (32)     NULL,
    [fact_boss_daily_roster_key]     CHAR (32)     NULL,
    [fact_mms_sales_transaction_key] CHAR (32)     NULL,
    [instructor_type]                CHAR (1)      NULL,
    [meeting_dim_date_key]           CHAR (8)      NULL,
    [member_code]                    CHAR (10)     NULL,
    [member_flag]                    CHAR (1)      NULL,
    [mms_swipe_flag]                 CHAR (1)      NULL,
    [notes]                          VARCHAR (240) NULL,
    [paid]                           CHAR (1)      NULL,
    [player_cancel_dim_date_key]     CHAR (8)      NULL,
    [player_checked_in_flag]         CHAR (1)      NULL,
    [player_start_dim_date_key]      CHAR (8)      NULL,
    [primary_dim_employee_key]       CHAR (32)     NULL,
    [reservation_id]                 INT           NULL,
    [secondary_dim_employee_key]     CHAR (32)     NULL,
    [dv_load_date_time]              DATETIME      NULL,
    [dv_load_end_date_time]          DATETIME      NULL,
    [dv_batch_id]                    BIGINT        NOT NULL,
    [dv_inserted_date_time]          DATETIME      NOT NULL,
    [dv_insert_user]                 VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]           DATETIME      NULL,
    [dv_update_user]                 VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_boss_daily_roster_key]));

