CREATE TABLE [dbo].[fact_exerp_participation] (
    [fact_exerp_participation_id]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [billable_flag]                        CHAR (1)       NULL,
    [booking_cancelled_flag]               CHAR (1)       NULL,
    [booking_dim_date_key]                 VARCHAR (8)    NULL,
    [booking_dim_time_key]                 INT            NULL,
    [cancel_dim_date_key]                  VARCHAR (8)    NULL,
    [cancel_dim_time_key]                  INT            NULL,
    [cancel_interface_type]                VARCHAR (4000) NULL,
    [cancel_reason]                        VARCHAR (4000) NULL,
    [clipcard_flag]                        CHAR (1)       NULL,
    [creation_dim_date_key]                VARCHAR (8)    NULL,
    [creation_dim_time_key]                INT            NULL,
    [dim_club_key]                         VARCHAR (32)   NULL,
    [dim_exerp_activity_key]               VARCHAR (32)   NULL,
    [dim_exerp_booking_key]                VARCHAR (32)   NULL,
    [dim_exerp_clipcard_key]               VARCHAR (32)   NULL,
    [dim_exerp_product_key]                VARCHAR (32)   NULL,
    [dim_exerp_subscription_key]           VARCHAR (32)   NULL,
    [dim_exerp_subscription_period_key]    VARCHAR (32)   NULL,
    [dim_mms_member_key]                   VARCHAR (32)   NULL,
    [dim_mms_product_key]                  VARCHAR (32)   NULL,
    [ets]                                  BIGINT         NULL,
    [fact_exerp_participation_key]         VARCHAR (32)   NULL,
    [fact_exerp_transaction_log_key]       VARCHAR (32)   NULL,
    [participant_number]                   INT            NULL,
    [participated_flag]                    CHAR (1)       NULL,
    [participation_cancelled_flag]         CHAR (1)       NULL,
    [participation_cancelled_no_show_flag] CHAR (1)       NULL,
    [participation_id]                     VARCHAR (4000) NULL,
    [participation_state]                  VARCHAR (4000) NULL,
    [seat_id]                              VARCHAR (4000) NULL,
    [seat_obtained_dim_date_key]           VARCHAR (8)    NULL,
    [seat_obtained_dim_time_key]           INT            NULL,
    [seat_state]                           VARCHAR (4000) NULL,
    [show_up_dim_date_key]                 VARCHAR (8)    NULL,
    [show_up_dim_time_key]                 INT            NULL,
    [show_up_interface_type]               VARCHAR (4000) NULL,
    [show_up_using_card_flag]              CHAR (1)       NULL,
    [subscription_flag]                    CHAR (1)       NULL,
    [user_interface_type]                  VARCHAR (4000) NULL,
    [waitlist_flag]                        CHAR (1)       NULL,
    [was_on_waiting_list_flag]             CHAR (1)       NULL,
    [dv_load_date_time]                    DATETIME       NULL,
    [dv_load_end_date_time]                DATETIME       NULL,
    [dv_batch_id]                          BIGINT         NOT NULL,
    [dv_inserted_date_time]                DATETIME       NOT NULL,
    [dv_insert_user]                       VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                 DATETIME       NULL,
    [dv_update_user]                       VARCHAR (50)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_exerp_participation_key]));

