CREATE TABLE [dbo].[fact_mms_membership_modification_request] (
    [fact_mms_membership_modification_request_id]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [fact_mms_membership_modification_request_key]               CHAR (32)       NULL,
    [membership_modification_request_id]                         CHAR (32)       NULL,
    [dim_mms_membership_key]                                     CHAR (32)       NULL,
    [effective_date]                                             DATETIME        NULL,
    [effective_dim_date_key]                                     VARCHAR (8)     NULL,
    [effective_dim_time_key]                                     INT             NULL,
    [flex_downgrade_reason_dim_description_key]                  VARCHAR (255)   NULL,
    [membership_modification_request_source_dim_description_key] VARCHAR (255)   NULL,
    [membership_type_dim_mms_product_key]                        CHAR (32)       NULL,
    [modification_dim_employee_key]                              CHAR (32)       NULL,
    [new_primary_id]                                             INT             NULL,
    [request_date_time]                                          DATETIME        NULL,
    [request_dim_date_key]                                       CHAR (8)        NULL,
    [request_dim_time_key]                                       CHAR (5)        NULL,
    [request_status_changed_date_time]                           DATETIME        NULL,
    [request_status_changed_dim_date_key]                        CHAR (8)        NULL,
    [request_status_changed_dim_time_key]                        CHAR (5)        NULL,
    [request_status_dim_mms_description_key]                     VARCHAR (255)   NULL,
    [request_type_dim_description_key]                           VARCHAR (255)   NULL,
    [requesting_dim_mms_member_key]                              CHAR (32)       NULL,
    [undiscounted_price]                                         DECIMAL (26, 6) NULL,
    [val_membership_modification_request_source_id]              TINYINT         NULL,
    [dv_load_date_time]                                          DATETIME        NULL,
    [dv_load_end_date_time]                                      DATETIME        NULL,
    [dv_batch_id]                                                BIGINT          NOT NULL,
    [dv_inserted_date_time]                                      DATETIME        NOT NULL,
    [dv_insert_user]                                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                                       DATETIME        NULL,
    [dv_update_user]                                             VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([fact_mms_membership_modification_request_key]));

