CREATE TABLE [dbo].[fact_humanity_schedule_raas] (
    [shift_id]               BIGINT         NOT NULL,
    [company_id]             VARCHAR (255)  NULL,
    [company_name]           VARCHAR (255)  NULL,
    [employee_id]            VARCHAR (255)  NULL,
    [employee_eid]           VARCHAR (255)  NULL,
    [employee_name]          VARCHAR (255)  NULL,
    [location_id]            VARCHAR (255)  NULL,
    [location_name]          VARCHAR (255)  NULL,
    [position_id]            VARCHAR (255)  NULL,
    [workday_position_id]    VARCHAR (255)  NULL,
    [position_name]          VARCHAR (255)  NULL,
    [shift_start_date_utc]   DATE           NULL,
    [shift_start_time]       TIME (7)       NULL,
    [shift_end_date_utc]     DATE           NULL,
    [shift_end_time]         TIME (7)       NULL,
    [hours]                  DECIMAL (7, 2) NULL,
    [wage]                   VARCHAR (255)  NULL,
    [published]              VARCHAR (255)  NULL,
    [published_datetime_utc] DATETIME       NULL,
    [shift_type]             VARCHAR (255)  NULL,
    [employees_needed]       VARCHAR (255)  NULL,
    [employees_working]      VARCHAR (255)  NULL,
    [recurring_shift]        VARCHAR (255)  NULL,
    [created_by_id]          VARCHAR (255)  NULL,
    [created_by_eid]         VARCHAR (255)  NULL,
    [created_by_name]        VARCHAR (255)  NULL,
    [created_datetime_utc]   VARCHAR (255)  NULL,
    [updated_at_utc]         VARCHAR (255)  NULL,
    [is_deleted]             VARCHAR (255)  NULL,
    [notes]                  VARCHAR (255)  NULL,
    [inserted_date_time]     DATETIME       NULL,
    [inserted_user]          VARCHAR (255)  NULL,
    [adjusted_start_date]    DATE           NULL,
    [adjusted_start_time]    TIME (7)       NULL,
    [adjusted_end_date]      DATE           NULL,
    [adjusted_end_time]      TIME (7)       NULL,
    [cost_center]            VARCHAR (255)  NULL,
    [hourly_amount]          VARCHAR (255)  NULL,
    [job_code]               VARCHAR (255)  NULL,
    [offering]               VARCHAR (255)  NULL,
    [region]                 VARCHAR (255)  NULL,
    [effective_date_begin]   DATE           NULL,
    [effective_date_end]     DATE           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

