CREATE TABLE [dbo].[s_orbital_transaction_data_report] (
    [s_orbital_transaction_data_report_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [OriginalReferenceNumber]              VARCHAR (15)    NULL,
    [MerchantNumber]                       VARCHAR (20)    NULL,
    [BatchNumber]                          VARCHAR (15)    NULL,
    [TransactionSequenceNumber]            INT             NULL,
    [TransactionId]                        VARCHAR (15)    NULL,
    [Filler]                               VARCHAR (4)     NULL,
    [TranCode]                             VARCHAR (2)     NULL,
    [CardholderNumber]                     VARCHAR (20)    NULL,
    [Amount]                               DECIMAL (10, 2) NULL,
    [AuthorizationCode]                    VARCHAR (10)    NULL,
    [TransactionDate]                      VARCHAR (29)    NULL,
    [MOPCode]                              VARCHAR (2)     NULL,
    [MnemonicCode]                         VARCHAR (4)     NULL,
    [RejectReasonCode]                     VARCHAR (3)     NULL,
    [TranType]                             VARCHAR (2)     NULL,
    [EntryMode]                            VARCHAR (2)     NULL,
    [ServiceLevel]                         VARCHAR (1)     NULL,
    [Filler1]                              VARCHAR (1)     NULL,
    [ValidationCode]                       VARCHAR (5)     NULL,
    [DowngradeReason]                      VARCHAR (15)    NULL,
    [ProcessDate]                          VARCHAR (29)    NULL,
    [CustomerDefinedData]                  VARCHAR (30)    NULL,
    [ChasePayIndicator]                    VARCHAR (1)     NULL,
    [DigitalTokenMethod]                   VARCHAR (2)     NULL,
    [PIDCode]                              VARCHAR (10)    NULL,
    [RecordType]                           VARCHAR (2)     NULL,
    [dv_load_date_time]                    DATETIME        NOT NULL,
    [dv_r_load_source_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL,
    [dv_hash]                              CHAR (32)       NOT NULL,
    [dv_deleted]                           BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

