CREATE TABLE [dbo].[s_pivvit_financial_data] (
    [s_pivvit_financial_data_id]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)       NOT NULL,
    [transaction_id]               NVARCHAR (500)  NULL,
    [pivvit_order_number]          VARCHAR (10)    NULL,
    [pivvit_line_number]           VARCHAR (10)    NULL,
    [posted_date]                  VARCHAR (29)    NULL,
    [offering_id]                  VARCHAR (20)    NULL,
    [tender_type_id]               VARCHAR (20)    NULL,
    [transaction_amount]           DECIMAL (26, 2) NULL,
    [transaction_lineamount]       DECIMAL (26, 2) NULL,
    [tax_amount]                   DECIMAL (10, 2) NULL,
    [transaction_date]             VARCHAR (29)    NULL,
    [transaction_line_category_id] VARCHAR (50)    NULL,
    [transaction_memo]             VARCHAR (200)   NULL,
    [discount_amount]              DECIMAL (10, 2) NULL,
    [batch_id]                     INT             NULL,
    [dummy_modified_date_time]     DATETIME        NULL,
    [dv_load_date_time]            DATETIME        NOT NULL,
    [dv_r_load_source_id]          BIGINT          NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]         DATETIME        NULL,
    [dv_update_user]               VARCHAR (50)    NULL,
    [dv_hash]                      CHAR (32)       NOT NULL,
    [dv_deleted]                   BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                  BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

