CREATE TABLE [dbo].[s_pm_bkp] (
    [s_udwcloudsync_product_master_id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)       NOT NULL,
    [app_created_by]                               NVARCHAR (4000) NULL,
    [app_modified_by]                              NVARCHAR (4000) NULL,
    [assess_junior_dues_flag]                      NVARCHAR (4000) NULL,
    [attachments]                                  NVARCHAR (4000) NULL,
    [connectivity_lead_generator]                  NVARCHAR (4000) NULL,
    [connectivity_primary_lead_generator_flag]     NVARCHAR (4000) NULL,
    [content_type]                                 NVARCHAR (4000) NULL,
    [corporate_transfer_flag]                      NVARCHAR (4000) NULL,
    [corporate_transfer_multiplier]                NVARCHAR (4000) NULL,
    [created]                                      DATETIME        NULL,
    [created_by]                                   NVARCHAR (4000) NULL,
    [deferred_revenue_flag]                        NVARCHAR (4000) NULL,
    [departmental_dssr_flag]                       NVARCHAR (4000) NULL,
    [discount_1_description]                       NVARCHAR (4000) NULL,
    [discount_1_effective_from_date]               NVARCHAR (4000) NULL,
    [discount_1_effective_through_date]            NVARCHAR (4000) NULL,
    [discount_1_sales_commission_percent]          NVARCHAR (4000) NULL,
    [discount_1_service_commission_percent]        NVARCHAR (4000) NULL,
    [discount_2_description]                       NVARCHAR (4000) NULL,
    [discount_2_effective_from_date]               NVARCHAR (4000) NULL,
    [discount_2_effective_through_date]            NVARCHAR (4000) NULL,
    [discount_2_sales_commission_percent]          NVARCHAR (4000) NULL,
    [discount_2_service_commission_percent]        NVARCHAR (4000) NULL,
    [discount_3_description]                       NVARCHAR (4000) NULL,
    [discount_3_effective_from_date]               NVARCHAR (4000) NULL,
    [discount_3_effective_through_date]            NVARCHAR (4000) NULL,
    [discount_3_sales_commission_percent]          NVARCHAR (4000) NULL,
    [discount_3_service_commission_percent]        NVARCHAR (4000) NULL,
    [discount_4_description]                       NVARCHAR (4000) NULL,
    [discount_4_effective_from_date]               NVARCHAR (4000) NULL,
    [discount_4_effective_through_date]            NVARCHAR (4000) NULL,
    [discount_4_sales_commission_percent]          NVARCHAR (4000) NULL,
    [discount_4_service_commission_percent]        NVARCHAR (4000) NULL,
    [discount_5_description]                       NVARCHAR (4000) NULL,
    [discount_5_effective_from_date]               NVARCHAR (4000) NULL,
    [discount_5_effective_through_date]            NVARCHAR (4000) NULL,
    [discount_5_sales_commission_percent]          NVARCHAR (4000) NULL,
    [discount_5_service_commission_percent]        NVARCHAR (4000) NULL,
    [division]                                     NVARCHAR (4000) NULL,
    [dssr_down_grade_other_enrollment_fee_flag]    NVARCHAR (4000) NULL,
    [dssr_if_admin_fee_flag]                       NVARCHAR (4000) NULL,
    [ecommerce_offer_flag]                         NVARCHAR (4000) NULL,
    [edit]                                         NVARCHAR (4000) NULL,
    [experience_life_magazine_flag]                NVARCHAR (4000) NULL,
    [folder_child_count]                           NVARCHAR (4000) NULL,
    [Product_Master_id]                            INT             NULL,
    [item_child_count]                             NVARCHAR (4000) NULL,
    [mms_department]                               NVARCHAR (4000) NULL,
    [mms_package_product_flag]                     NVARCHAR (4000) NULL,
    [mms_productd_is_play_ui_flag]                 NVARCHAR (4000) NULL,
    [mms_product_gl_override_club_id]              NVARCHAR (4000) NULL,
    [mms_product_tip_allowed_flag]                 NVARCHAR (4000) NULL,
    [mms_recurrent_product_type_description]       NVARCHAR (4000) NULL,
    [modified]                                     DATETIME        NULL,
    [modified_by]                                  NVARCHAR (4000) NULL,
    [mtd_average_delivered_session_price]          NVARCHAR (4000) NULL,
    [mtd_average_sale_price]                       NVARCHAR (4000) NULL,
    [new_business_old_business]                    NVARCHAR (4000) NULL,
    [package_product_count_as_half_session_flag]   NVARCHAR (4000) NULL,
    [package_product_session_type]                 NVARCHAR (4000) NULL,
    [payroll_extract_description]                  NVARCHAR (4000) NULL,
    [payroll_extract_region_type]                  NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_product_group_description] NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_product_group_flag]        NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_product_group_sort_order]  NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_sales_amount_flag]         NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_service_amount_flag]       NVARCHAR (4000) NULL,
    [payroll_my_ltbucks_service_quantity_flag]     NVARCHAR (4000) NULL,
    [payroll_product_group_description]            NVARCHAR (4000) NULL,
    [payroll_product_group_sort_order]             NVARCHAR (4000) NULL,
    [payroll_sales_amount_flag]                    NVARCHAR (4000) NULL,
    [payroll_service_amount_flag]                  NVARCHAR (4000) NULL,
    [payroll_service_quantity_flag]                NVARCHAR (4000) NULL,
    [payroll_standard_product_group_flag]          NVARCHAR (4000) NULL,
    [payroll_track_sales_flag]                     NVARCHAR (4000) NULL,
    [payroll_track_service_flag]                   NVARCHAR (4000) NULL,
    [product_description]                          NVARCHAR (4000) NULL,
    [product_id]                                   NVARCHAR (4000) NULL,
    [product_sku]                                  NVARCHAR (4000) NULL,
    [product_status]                               NVARCHAR (4000) NULL,
    [product_workday_offering]                     NVARCHAR (4000) NULL,
    [product_workday_override_region]              NVARCHAR (4000) NULL,
    [reporting_dept]                               NVARCHAR (4000) NULL,
    [reporting_dept_for_non_commissioned_sales]    NVARCHAR (4000) NULL,
    [revenue_allocation_rule]                      NVARCHAR (4000) NULL,
    [revenue_product_group_description]            NVARCHAR (4000) NULL,
    [revenue_product_group_sort_order]             NVARCHAR (4000) NULL,
    [revenue_reporting_region_type]                NVARCHAR (4000) NULL,
    [sales_category_description]                   NVARCHAR (4000) NULL,
    [source_system_link_title]                     NVARCHAR (4000) NULL,
    [source_system_link_title_no_menu]             NVARCHAR (4000) NULL,
    [source_system_title]                          NVARCHAR (4000) NULL,
    [sub_division]                                 NVARCHAR (4000) NULL,
    [type]                                         NVARCHAR (4000) NULL,
    [version]                                      NVARCHAR (4000) NULL,
    [virtual_local_relative_path]                  NVARCHAR (4000) NULL,
    [dv_load_date_time]                            DATETIME        NOT NULL,
    [dv_r_load_source_id]                          BIGINT          NOT NULL,
    [dv_inserted_date_time]                        DATETIME        NOT NULL,
    [dv_insert_user]                               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                         DATETIME        NULL,
    [dv_update_user]                               VARCHAR (50)    NULL,
    [dv_hash]                                      CHAR (32)       NOT NULL,
    [dv_batch_id]                                  BIGINT          NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([bk_hash]));

