CREATE TABLE [dbo].[s_qtest_jira] (
    [s_qtest_jira_id]                                                BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                                        CHAR (32)      NOT NULL,
    [project_id]                                                     VARCHAR (4000) NULL,
    [project_name]                                                   VARCHAR (4000) NULL,
    [project_description]                                            VARCHAR (4000) NULL,
    [project_start_date]                                             VARCHAR (4000) NULL,
    [project_sample]                                                 VARCHAR (4000) NULL,
    [project_x_explorer_access_level]                                VARCHAR (4000) NULL,
    [project_automation]                                             VARCHAR (4000) NULL,
    [project_uuid]                                                   VARCHAR (4000) NULL,
    [release_id]                                                     VARCHAR (4000) NULL,
    [release_name]                                                   VARCHAR (4000) NULL,
    [release_order]                                                  VARCHAR (4000) NULL,
    [release_created_date]                                           VARCHAR (4000) NULL,
    [release_last_modified_date]                                     VARCHAR (4000) NULL,
    [release_start_date]                                             VARCHAR (4000) NULL,
    [release_end_date]                                               VARCHAR (4000) NULL,
    [release_properties_start_date]                                  VARCHAR (4000) NULL,
    [release_properties_end_date]                                    VARCHAR (4000) NULL,
    [requirement_jira_issue]                                         VARCHAR (4000) NULL,
    [requirement_jira_priority]                                      VARCHAR (4000) NULL,
    [requirement_jira_status]                                        VARCHAR (4000) NULL,
    [requirement_id]                                                 VARCHAR (4000) NULL,
    [requirement_jira_story_point]                                   VARCHAR (4000) NULL,
    [requirement_name]                                               VARCHAR (4000) NULL,
    [test_case_id]                                                   VARCHAR (4000) NULL,
    [requirement_created_date]                                       VARCHAR (4000) NULL,
    [test_case_name]                                                 VARCHAR (4000) NULL,
    [test_case_order]                                                VARCHAR (4000) NULL,
    [test_case_created_date]                                         VARCHAR (4000) NULL,
    [test_case_last_modified_date]                                   VARCHAR (4000) NULL,
    [test_case_version]                                              VARCHAR (4000) NULL,
    [test_case_description]                                          VARCHAR (4000) NULL,
    [test_case_properties_automation_field_value_name]               VARCHAR (4000) NULL,
    [test_case_properties_automation_content_field_value]            VARCHAR (4000) NULL,
    [test_case_properties_status_field_value_name]                   VARCHAR (4000) NULL,
    [test_case_properties_type_field_value_name]                     VARCHAR (4000) NULL,
    [test_case_properties_assigned_to_field_value_name]              VARCHAR (4000) NULL,
    [test_case_properties_description_field_value]                   VARCHAR (4000) NULL,
    [test_case_properties_precondition_field_value]                  VARCHAR (4000) NULL,
    [test_case_properties_test_tier_field_value_name]                VARCHAR (4000) NULL,
    [test_case_properties_zephyr_issue_key_field_value]              VARCHAR (4000) NULL,
    [test_case_properties_candidate_for_automation_field_value_name] VARCHAR (4000) NULL,
    [test_case_properties_platform_field_value_name]                 VARCHAR (4000) NULL,
    [test_case_properties_test_data_field_value]                     VARCHAR (4000) NULL,
    [test_case_properties_zephyr_test_steps_field_value]             VARCHAR (4000) NULL,
    [test_case_properties_shared_field_value]                        VARCHAR (4000) NULL,
    [dummy_modified_date_time]                                       DATETIME       NULL,
    [project_date_format]                                            VARCHAR (4000) NULL,
    [release_properties_status]                                      VARCHAR (4000) NULL,
    [requirement_last_modified_date]                                 VARCHAR (4000) NULL,
    [dv_load_date_time]                                              DATETIME       NOT NULL,
    [dv_r_load_source_id]                                            BIGINT         NOT NULL,
    [dv_inserted_date_time]                                          DATETIME       NOT NULL,
    [dv_insert_user]                                                 VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                                           DATETIME       NULL,
    [dv_update_user]                                                 VARCHAR (50)   NULL,
    [dv_hash]                                                        CHAR (32)      NOT NULL,
    [dv_deleted]                                                     BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                                                    BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

