CREATE TABLE [dbo].[s_spabiz_store] (
    [s_spabiz_store_id]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]               CHAR (32)       NOT NULL,
    [store_id]              DECIMAL (26, 6) NULL,
    [edit_time]             DATETIME        NULL,
    [quick_id]              CHAR (30)       NULL,
    [locked]                DECIMAL (26, 6) NULL,
    [store_delete]          DECIMAL (26, 6) NULL,
    [delete_date]           DATETIME        NULL,
    [name]                  VARCHAR (150)   NULL,
    [address_1]             VARCHAR (360)   NULL,
    [address_2]             VARCHAR (360)   NULL,
    [city]                  VARCHAR (60)    NULL,
    [store_state]           VARCHAR (6)     NULL,
    [zip]                   VARCHAR (30)    NULL,
    [country]               VARCHAR (150)   NULL,
    [store_backup]          VARCHAR (150)   NULL,
    [telephone]             VARCHAR (150)   NULL,
    [retail_tax_id]         VARCHAR (150)   NULL,
    [start_period]          DECIMAL (26, 6) NULL,
    [store_1_name]          VARCHAR (150)   NULL,
    [store_1_start]         VARCHAR (15)    NULL,
    [store_1_end]           VARCHAR (15)    NULL,
    [store_2_name]          VARCHAR (150)   NULL,
    [store_2_start]         VARCHAR (15)    NULL,
    [store_2_end]           VARCHAR (15)    NULL,
    [store_3_name]          VARCHAR (150)   NULL,
    [store_3_start]         VARCHAR (15)    NULL,
    [store_3_end]           VARCHAR (15)    NULL,
    [store_4_name]          VARCHAR (150)   NULL,
    [store_4_start]         VARCHAR (15)    NULL,
    [store_4_end]           VARCHAR (15)    NULL,
    [store_5_name]          VARCHAR (150)   NULL,
    [store_5_start]         VARCHAR (15)    NULL,
    [store_5_end]           VARCHAR (15)    NULL,
    [store_6_name]          VARCHAR (150)   NULL,
    [store_6_start]         VARCHAR (15)    NULL,
    [store_6_end]           VARCHAR (15)    NULL,
    [store_7_name]          VARCHAR (150)   NULL,
    [store_7_start]         VARCHAR (15)    NULL,
    [store_7_end]           VARCHAR (15)    NULL,
    [store_8_name]          VARCHAR (150)   NULL,
    [store_8_start]         VARCHAR (15)    NULL,
    [store_8_end]           VARCHAR (15)    NULL,
    [store_9_name]          VARCHAR (150)   NULL,
    [store_9_start]         VARCHAR (15)    NULL,
    [store_9_end]           VARCHAR (15)    NULL,
    [store_10_name]         VARCHAR (150)   NULL,
    [store_10_start]        VARCHAR (15)    NULL,
    [store_10_end]          VARCHAR (15)    NULL,
    [store_11_name]         VARCHAR (150)   NULL,
    [store_11_start]        VARCHAR (15)    NULL,
    [store_11_end]          VARCHAR (15)    NULL,
    [store_12_name]         VARCHAR (150)   NULL,
    [store_12_start]        VARCHAR (15)    NULL,
    [store_12_end]          VARCHAR (15)    NULL,
    [store_13_name]         VARCHAR (150)   NULL,
    [store_13_start]        VARCHAR (15)    NULL,
    [store_13_end]          VARCHAR (15)    NULL,
    [open_1]                DECIMAL (26, 6) NULL,
    [open_2]                DECIMAL (26, 6) NULL,
    [open_3]                DECIMAL (26, 6) NULL,
    [open_4]                DECIMAL (26, 6) NULL,
    [open_5]                DECIMAL (26, 6) NULL,
    [open_6]                DECIMAL (26, 6) NULL,
    [open_7]                DECIMAL (26, 6) NULL,
    [available]             DECIMAL (26, 6) NULL,
    [d_day]                 DATETIME        NULL,
    [rec_cnt]               VARCHAR (765)   NULL,
    [db_version]            DECIMAL (26, 6) NULL,
    [hq_path]               VARCHAR (765)   NULL,
    [cash_change]           DECIMAL (26, 6) NULL,
    [store_number]          DECIMAL (26, 6) NULL,
    [payment_tech]          DECIMAL (26, 6) NULL,
    [pager_port]            DECIMAL (26, 6) NULL,
    [store_info]            VARCHAR (4000)  NULL,
    [merchant_number]       VARCHAR (36)    NULL,
    [client_number]         VARCHAR (12)    NULL,
    [power_booking]         DECIMAL (26, 6) NULL,
    [s_blog_on_path]        VARCHAR (300)   NULL,
    [s_cat_storenum]        DECIMAL (26, 6) NULL,
    [web_book]              DECIMAL (26, 6) NULL,
    [counter_id]            DECIMAL (26, 6) NULL,
    [store_store_id]        DECIMAL (26, 6) NULL,
    [sqr_footage]           DECIMAL (26, 6) NULL,
    [web_view]              DECIMAL (26, 6) NULL,
    [is_master]             DECIMAL (26, 6) NULL,
    [dv_load_date_time]     DATETIME        NOT NULL,
    [dv_batch_id]           BIGINT          NOT NULL,
    [dv_r_load_source_id]   BIGINT          NOT NULL,
    [dv_inserted_date_time] DATETIME        NOT NULL,
    [dv_insert_user]        VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]  DATETIME        NULL,
    [dv_update_user]        VARCHAR (50)    NULL,
    [dv_hash]               CHAR (32)       NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_spabiz_store]
    ON [dbo].[s_spabiz_store]([bk_hash] ASC, [s_spabiz_store_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_spabiz_store]([dv_batch_id] ASC);

