CREATE TABLE [dbo].[s_udwcloudsync_club_master_roster] (
    [s_udwcloudsync_club_master_roster_id]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                    CHAR (32)       NOT NULL,
    [twenty_four_hour_guard]                     NVARCHAR (4000) NULL,
    [three_story]                                BIT             NULL,
    [access_type]                                NVARCHAR (4000) NULL,
    [activity_center]                            NVARCHAR (4000) NULL,
    [allow_junior_check_in_flag]                 INT             NULL,
    [app_created_by]                             NVARCHAR (4000) NULL,
    [app_modified_by]                            NVARCHAR (4000) NULL,
    [approval_status]                            NVARCHAR (4000) NULL,
    [approver_comments]                          VARCHAR (8000)  NULL,
    [aquatics_dh]                                NVARCHAR (4000) NULL,
    [area]                                       NVARCHAR (4000) NULL,
    [area_director]                              NVARCHAR (4000) NULL,
    [asst_general_manager]                       NVARCHAR (4000) NULL,
    [athletic_lta]                               BIT             NULL,
    [attachments]                                NVARCHAR (4000) NULL,
    [basketball_courts]                          INT             NULL,
    [basketball_trainer]                         NVARCHAR (4000) NULL,
    [bulding_engineer]                           NVARCHAR (4000) NULL,
    [business_administrator]                     NVARCHAR (4000) NULL,
    [cafe]                                       NVARCHAR (4000) NULL,
    [center_type]                                NVARCHAR (4000) NULL,
    [check_in_group_level]                       NVARCHAR (4000) NULL,
    [child_center]                               NVARCHAR (4000) NULL,
    [child_center_kids_activities_dh]            NVARCHAR (4000) NULL,
    [child_center_weekly_limit]                  INT             NULL,
    [cig_end_date]                               DATETIME        NULL,
    [cig_start_date]                             DATETIME        NULL,
    [cig_status]                                 NVARCHAR (4000) NULL,
    [classes_offered]                            NVARCHAR (4000) NULL,
    [clinic]                                     NVARCHAR (4000) NULL,
    [club_address]                               NVARCHAR (4000) NULL,
    [club_id]                                    NVARCHAR (4000) NULL,
    [club_deactivation_date]                     DATETIME        NULL,
    [cognos_name]                                NVARCHAR (4000) NULL,
    [content_type]                               NVARCHAR (4000) NULL,
    [content_type_id]                            NVARCHAR (4000) NULL,
    [copy_source]                                NVARCHAR (4000) NULL,
    [created]                                    DATETIME        NULL,
    [created_date]                               NVARCHAR (4000) NULL,
    [created_by]                                 NVARCHAR (4000) NULL,
    [current_operations_status]                  NVARCHAR (4000) NULL,
    [cycle_studios]                              INT             NULL,
    [display_ui_flag]                            NVARCHAR (4000) NULL,
    [edit]                                       NVARCHAR (4000) NULL,
    [edit_menu_table_end]                        NVARCHAR (4000) NULL,
    [edit_menu_table_start]                      NVARCHAR (4000) NULL,
    [effective_permissions_mask]                 NVARCHAR (4000) NULL,
    [egroup_name]                                NVARCHAR (4000) NULL,
    [email_alert]                                NVARCHAR (4000) NULL,
    [encoded_absolute_url]                       NVARCHAR (4000) NULL,
    [eng_rcl]                                    NVARCHAR (4000) NULL,
    [facility_operations_dh]                     NVARCHAR (4000) NULL,
    [facility_technician]                        NVARCHAR (4000) NULL,
    [family_swim]                                BIT             NULL,
    [file_name]                                  NVARCHAR (4000) NULL,
    [file_type]                                  NVARCHAR (4000) NULL,
    [folder_child_count]                         NVARCHAR (4000) NULL,
    [formal_club_name]                           NVARCHAR (4000) NULL,
    [general_manager]                            NVARCHAR (4000) NULL,
    [gl_cash_entry_account]                      NVARCHAR (4000) NULL,
    [gl_cash_entry_cash_sub_account]             NVARCHAR (4000) NULL,
    [gl_cash_entry_company_name]                 NVARCHAR (4000) NULL,
    [gl_cash_entry_credit_card_sub_account]      NVARCHAR (4000) NULL,
    [gl_receivables_entry_account]               NVARCHAR (4000) NULL,
    [gl_receivables_entry_company_name]          NVARCHAR (4000) NULL,
    [gl_receivables_entry_sub_account]           NVARCHAR (4000) NULL,
    [grand_prix_tour_location]                   NVARCHAR (4000) NULL,
    [group_fitness_dh]                           NVARCHAR (4000) NULL,
    [group_fitness_studios]                      INT             NULL,
    [growth_type]                                NVARCHAR (4000) NULL,
    [guid]                                       VARCHAR (4000)  NULL,
    [has_company_destinations]                   BIT             NULL,
    [health_club_identifier]                     NVARCHAR (4000) NULL,
    [html_file_type]                             NVARCHAR (4000) NULL,
    [hyperion_planning]                          NVARCHAR (4000) NULL,
    [club_master_roster_id]                      INT             NULL,
    [ig_store_id]                                INT             NULL,
    [indoor_pool]                                NVARCHAR (4000) NULL,
    [indoor_pool_close_date]                     DATETIME        NULL,
    [indoor_pool_open_date]                      DATETIME        NULL,
    [indoor_tennis_courts]                       INT             NULL,
    [instance_id]                                INT             NULL,
    [is_current_version]                         BIT             NULL,
    [item_child_count]                           NVARCHAR (4000) NULL,
    [item_type]                                  NVARCHAR (4000) NULL,
    [kids_academy]                               NVARCHAR (4000) NULL,
    [lap_pools]                                  NVARCHAR (4000) NULL,
    [latitide]                                   NUMERIC (20, 9) NULL,
    [leases_owned]                               NVARCHAR (4000) NULL,
    [level]                                      INT             NULL,
    [life_cafe_dh]                               NVARCHAR (4000) NULL,
    [life_shop]                                  NVARCHAR (4000) NULL,
    [life_spa_dh]                                NVARCHAR (4000) NULL,
    [longitude]                                  NUMERIC (20, 9) NULL,
    [map_center_latitude]                        NUMERIC (10, 4) NULL,
    [map_center_longitude]                       NUMERIC (10, 4) NULL,
    [map_zoom_level]                             INT             NULL,
    [marketing_club_name]                        NVARCHAR (4000) NULL,
    [marketing_club_level]                       NVARCHAR (4000) NULL,
    [marketing_map_region]                       NVARCHAR (4000) NULL,
    [marketing_map_xml_state_name]               NVARCHAR (4000) NULL,
    [mca_studios]                                INT             NULL,
    [medi]                                       NVARCHAR (4000) NULL,
    [member_engagement_manager]                  NVARCHAR (4000) NULL,
    [member_services_dh]                         NVARCHAR (4000) NULL,
    [membership_level]                           NVARCHAR (4000) NULL,
    [membership_level_needed_for_tennis]         NVARCHAR (4000) NULL,
    [mms_club_id]                                INT             NULL,
    [mms_club_name]                              NVARCHAR (4000) NULL,
    [modified]                                   DATETIME        NULL,
    [last_modified]                              NVARCHAR (4000) NULL,
    [modified_by]                                NVARCHAR (4000) NULL,
    [name_file_leaf_ref]                         NVARCHAR (4000) NULL,
    [name_link_file_name_no_menu]                NVARCHAR (4000) NULL,
    [name_link_file_name]                        NVARCHAR (4000) NULL,
    [name_link_file_name2]                       NVARCHAR (4000) NULL,
    [number_of_slides]                           INT             NULL,
    [nutrition_coach]                            NVARCHAR (4000) NULL,
    [open_24_hours]                              BIT             NULL,
    [open]                                       NVARCHAR (4000) NULL,
    [opened_date]                                DATETIME        NULL,
    [ops_rcl_sr_dh]                              NVARCHAR (4000) NULL,
    [club_master_roster_order]                   INT             NULL,
    [originator_id]                              NVARCHAR (4000) NULL,
    [outdoor_pool]                               NVARCHAR (4000) NULL,
    [outdoor_pool_close_date]                    DATETIME        NULL,
    [outdoor_pool_open_date]                     DATETIME        NULL,
    [outdoor_tennis_courts]                      INT             NULL,
    [ows_hidden_version]                         INT             NULL,
    [parents_night_out]                          BIT             NULL,
    [path]                                       NVARCHAR (4000) NULL,
    [personal_training_dh]                       NVARCHAR (4000) NULL,
    [personal_training_rcm]                      NVARCHAR (4000) NULL,
    [pilates_studio]                             INT             NULL,
    [pre_sale_address]                           NVARCHAR (4000) NULL,
    [prior_year_operations_status]               NVARCHAR (4000) NULL,
    [proactive_care]                             NVARCHAR (4000) NULL,
    [prog_id]                                    NVARCHAR (4000) NULL,
    [property_bag]                               NVARCHAR (4000) NULL,
    [ptrcm_region]                               NVARCHAR (4000) NULL,
    [racquet_ball_courts]                        INT             NULL,
    [racquet_ball_league_end_date]               DATETIME        NULL,
    [racquet_ball_league_start_date]             DATETIME        NULL,
    [region]                                     NVARCHAR (4000) NULL,
    [regional_sales_manager]                     NVARCHAR (4000) NULL,
    [regional_vice_president]                    NVARCHAR (4000) NULL,
    [restricted]                                 NVARCHAR (4000) NULL,
    [rock_wall]                                  NVARCHAR (4000) NULL,
    [school_break_camps]                         BIT             NULL,
    [scope_id]                                   NVARCHAR (4000) NULL,
    [select_title]                               NVARCHAR (4000) NULL,
    [senior_general_manager]                     NVARCHAR (4000) NULL,
    [server_relative_url]                        NVARCHAR (4000) NULL,
    [sort_type]                                  NVARCHAR (4000) NULL,
    [spa]                                        NVARCHAR (4000) NULL,
    [square_footage]                             INT             NULL,
    [squash_courts]                              INT             NULL,
    [squash_kids]                                BIT             NULL,
    [state]                                      NVARCHAR (4000) NULL,
    [state_abbreviation]                         NVARCHAR (4000) NULL,
    [sub_net_address]                            NVARCHAR (4000) NULL,
    [summer_break_camps]                         BIT             NULL,
    [tennis_courts]                              NVARCHAR (4000) NULL,
    [tennis_dh]                                  NVARCHAR (4000) NULL,
    [title]                                      NVARCHAR (4000) NULL,
    [title_link_title_no_menu]                   NVARCHAR (4000) NULL,
    [title_link_title]                           NVARCHAR (4000) NULL,
    [title_link_title2]                          NVARCHAR (4000) NULL,
    [turf_field]                                 INT             NULL,
    [type]                                       NVARCHAR (4000) NULL,
    [ui_version]                                 INT             NULL,
    [unique_features]                            NVARCHAR (4000) NULL,
    [unique_id]                                  NVARCHAR (4000) NULL,
    [url_path]                                   NVARCHAR (4000) NULL,
    [val_activity_area_id_lookup_description]    NVARCHAR (4000) NULL,
    [val_checkin_group_id_lookup_description]    NVARCHAR (4000) NULL,
    [val_club_type_id_lookup_description]        NVARCHAR (4000) NULL,
    [val_country_id_lookup_title]                NVARCHAR (4000) NULL,
    [val_cw_region_id_lookup_description]        NVARCHAR (4000) NULL,
    [val_enrollment_type_id_lookup_description]  NVARCHAR (4000) NULL,
    [val_member_activity_region_id_lookup_title] NVARCHAR (4000) NULL,
    [val_pre_sale_id_lookup_description]         NVARCHAR (4000) NULL,
    [val_ptrcl_area_id_lookup_title]             NVARCHAR (4000) NULL,
    [val_region_id_lookup_description]           NVARCHAR (4000) NULL,
    [val_sales_area_id_lookup_description]       NVARCHAR (4000) NULL,
    [val_state_id_lookup_description]            NVARCHAR (4000) NULL,
    [val_time_zone_id_lookup_description]        NVARCHAR (4000) NULL,
    [version]                                    NVARCHAR (4000) NULL,
    [water_slides]                               NVARCHAR (4000) NULL,
    [whirpools]                                  INT             NULL,
    [workflow_version]                           INT             NULL,
    [yoga_studios]                               INT             NULL,
    [zero_depth_entry]                           NVARCHAR (4000) NULL,
    [edit_menu_table_start2]                     NVARCHAR (4000) NULL,
    [aquatics_regional_manager]                  NVARCHAR (4000) NULL,
    [cafe_regional_manager]                      NVARCHAR (4000) NULL,
    [spa_regional_manager]                       NVARCHAR (4000) NULL,
    [racquet_regional_manager]                   NVARCHAR (4000) NULL,
    [personal_training_regional_manager]         NVARCHAR (4000) NULL,
    [kids_regional_manager]                      NVARCHAR (4000) NULL,
    [operationsregionalmanager]                  NVARCHAR (4000) NULL,
    [salesregionalmanager]                       NVARCHAR (4000) NULL,
    [groupfitnessregionalmanager]                NVARCHAR (4000) NULL,
    [member_services_regional_manager]           NVARCHAR (4000) NULL,
    [nutrition_regional_manager]                 NVARCHAR (4000) NULL,
    [dv_load_date_time]                          DATETIME        NOT NULL,
    [dv_r_load_source_id]                        BIGINT          NOT NULL,
    [dv_inserted_date_time]                      DATETIME        NOT NULL,
    [dv_insert_user]                             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                       DATETIME        NULL,
    [dv_update_user]                             VARCHAR (50)    NULL,
    [dv_hash]                                    CHAR (32)       NOT NULL,
    [dv_batch_id]                                BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));


GO
CREATE CLUSTERED INDEX [ci_s_udwcloudsync_club_master_roster]
    ON [dbo].[s_udwcloudsync_club_master_roster]([bk_hash] ASC, [s_udwcloudsync_club_master_roster_id] ASC);


GO
CREATE NONCLUSTERED INDEX [ix_dv_batch_id]
    ON [dbo].[s_udwcloudsync_club_master_roster]([dv_batch_id] ASC);

