CREATE TABLE [dbo].[s_workday_employee] (
    [s_workday_employee_id]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                    CHAR (32)       NOT NULL,
    [employee_id]                INT             NULL,
    [first_name]                 NVARCHAR (255)  NULL,
    [middle_name]                NVARCHAR (255)  NULL,
    [last_name]                  NVARCHAR (255)  NULL,
    [preferred_first_name]       NVARCHAR (255)  NULL,
    [preferred_middle_name]      NVARCHAR (255)  NULL,
    [preferred_last_name]        NVARCHAR (255)  NULL,
    [primary_work_email]         NVARCHAR (255)  NULL,
    [phone_number]               NVARCHAR (255)  NULL,
    [hire_date]                  DATETIME        NULL,
    [termination_date]           DATETIME        NULL,
    [active_status]              NVARCHAR (255)  NULL,
    [job_levels]                 NVARCHAR (4000) NULL,
    [job_families]               NVARCHAR (4000) NULL,
    [job_sub_families]           NVARCHAR (4000) NULL,
    [job_profiles]               NVARCHAR (4000) NULL,
    [business_titles]            NVARCHAR (4000) NULL,
    [marketing_titles]           NVARCHAR (4000) NULL,
    [job_codes]                  NVARCHAR (4000) NULL,
    [subordinates]               NVARCHAR (255)  NULL,
    [category]                   NVARCHAR (255)  NULL,
    [certifications]             VARCHAR (8000)  NULL,
    [cf_nickname]                NVARCHAR (255)  NULL,
    [is_primary]                 NVARCHAR (255)  NULL,
    [cf_employment_status]       NVARCHAR (255)  NULL,
    [pay_rate_for_all_positions] NVARCHAR (4000) NULL,
    [jan_one]                    DATETIME        NULL,
    [dv_load_date_time]          DATETIME        NOT NULL,
    [dv_r_load_source_id]        BIGINT          NOT NULL,
    [dv_inserted_date_time]      DATETIME        NOT NULL,
    [dv_insert_user]             VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]       DATETIME        NULL,
    [dv_update_user]             VARCHAR (50)    NULL,
    [dv_hash]                    CHAR (32)       NOT NULL,
    [dv_deleted]                 BIT             DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

