CREATE TABLE [dbo].[stage_hash_ec_WorkoutHistories] (
    [stage_hash_ec_WorkoutHistories_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)       NOT NULL,
    [WorkoutHistoryId]                  INT             NULL,
    [WorkoutId]                         INT             NULL,
    [PartyId]                           INT             NULL,
    [IsCustom]                          BIT             NULL,
    [DateCreated]                       DATETIME        NULL,
    [DateStarted]                       DATETIME        NULL,
    [DateEnded]                         DATETIME        NULL,
    [IsStarted]                         BIT             NULL,
    [Completed]                         BIT             NULL,
    [Comments]                          VARCHAR (8000)  NULL,
    [Rating]                            INT             NULL,
    [key]                               VARCHAR (8000)  NULL,
    [Type]                              VARCHAR (30)    NULL,
    [IsActive]                          BIT             NULL,
    [FatCalories]                       INT             NULL,
    [TotalCalories]                     INT             NULL,
    [SourceName]                        VARCHAR (8000)  NULL,
    [Description]                       VARCHAR (8000)  NULL,
    [ActivityType]                      VARCHAR (8000)  NULL,
    [Scheduled]                         BIT             NULL,
    [Tracked]                           BIT             NULL,
    [SourceWorkoutId]                   VARCHAR (8000)  NULL,
    [HeartRateZoneOneSeconds]           INT             NULL,
    [HeartRateZoneTwoSeconds]           INT             NULL,
    [HeartRateZoneThreeSeconds]         INT             NULL,
    [HeartRateZoneFourSeconds]          INT             NULL,
    [HeartRateZoneFiveSeconds]          INT             NULL,
    [DistanceInMiles]                   DECIMAL (26, 6) NULL,
    [AverageMilesPerHour]               DECIMAL (28, 8) NULL,
    [AverageWatts]                      DECIMAL (28, 8) NULL,
    [AverageHeartRate]                  DECIMAL (28, 8) NULL,
    [dv_load_date_time]                 DATETIME        NOT NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

