CREATE TABLE [dbo].[stage_ig_it_cfg_Profit_Center_Master] (
    [stage_ig_it_cfg_Profit_Center_Master_id] BIGINT        NOT NULL,
    [profit_center_id]                        INT           NULL,
    [profit_center_name]                      NVARCHAR (30) NULL,
    [profit_ctr_abbr1]                        NVARCHAR (7)  NULL,
    [profit_ctr_abbr2]                        NVARCHAR (7)  NULL,
    [chk_hdr_line1]                           NVARCHAR (30) NULL,
    [chk_hdr_line2]                           NVARCHAR (30) NULL,
    [chk_hdr_line3]                           NVARCHAR (30) NULL,
    [chk_ftr_line1]                           NVARCHAR (30) NULL,
    [chk_ftr_line2]                           NVARCHAR (30) NULL,
    [chk_ftr_line3]                           NVARCHAR (30) NULL,
    [doc_lines_advance]                       SMALLINT      NULL,
    [max_doc_lines_page]                      SMALLINT      NULL,
    [min_rcpt_lines_page]                     SMALLINT      NULL,
    [sales_tippable_flag]                     CHAR (1)      NULL,
    [print_by_rev_cat_flag]                   CHAR (1)      NULL,
    [data_control_group_id]                   INT           NULL,
    [ent_id]                                  INT           NULL,
    [store_id]                                INT           NULL,
    [default_table_layout_id]                 INT           NULL,
    [merchant_id]                             NVARCHAR (50) NULL,
    [bypass_CC_agency_threshold_amount]       MONEY         NULL,
    [bypass_CC_voice_auth_threshold_amount]   MONEY         NULL,
    [bypass_CC_printing_threshold_amount]     MONEY         NULL,
    [primary_language_id]                     NVARCHAR (9)  NULL,
    [secondary_language_id]                   NVARCHAR (9)  NULL,
    [tip_max_percent]                         SMALLINT      NULL,
    [tip_enforcement_code_id]                 SMALLINT      NULL,
    [profit_center_desc]                      NVARCHAR (50) NULL,
    [source_property_code]                    NVARCHAR (6)  NULL,
    [pole_display_open]                       NVARCHAR (20) NULL,
    [pole_display_closed]                     NVARCHAR (20) NULL,
    [row_version]                             BINARY (8)    NULL,
    [track_id]                                BIGINT        NULL,
    [track_action]                            NVARCHAR (1)  NULL,
    [inserted_date_time]                      DATETIME      NULL,
    [updated_date_time]                       DATETIME      NULL,
    [dv_batch_id]                             BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

