CREATE TABLE [dbo].[stage_hybris_users] (
    [stage_hybris_users_id]     BIGINT         NOT NULL,
    [hjmpTS]                    BIGINT         NULL,
    [createdTS]                 DATETIME       NULL,
    [modifiedTS]                DATETIME       NULL,
    [TypePkString]              BIGINT         NULL,
    [OwnerPkString]             BIGINT         NULL,
    [PK]                        BIGINT         NULL,
    [p_description]             NVARCHAR (255) NULL,
    [p_name]                    NVARCHAR (255) NULL,
    [p_uid]                     NVARCHAR (255) NULL,
    [p_profilepicture]          BIGINT         NULL,
    [p_backofficelogindisabled] TINYINT        NULL,
    [p_ldapsearchbase]          NVARCHAR (255) NULL,
    [p_dn]                      VARCHAR (8000) NULL,
    [p_cn]                      NVARCHAR (255) NULL,
    [p_defaultpaymentaddress]   BIGINT         NULL,
    [p_defaultshipmentaddress]  BIGINT         NULL,
    [p_sessionlanguage]         BIGINT         NULL,
    [p_sessioncurrency]         BIGINT         NULL,
    [p_logindisabled]           TINYINT        NULL,
    [p_lastlogin]               DATETIME       NULL,
    [p_hmclogindisabled]        TINYINT        NULL,
    [p_userprofile]             BIGINT         NULL,
    [p_europe1pricefactory_udg] BIGINT         NULL,
    [p_europe1pricefactory_upg] BIGINT         NULL,
    [p_europe1pricefactory_utg] BIGINT         NULL,
    [p_ldapaccount]             TINYINT        NULL,
    [p_domain]                  NVARCHAR (255) NULL,
    [p_ldaplogin]               NVARCHAR (255) NULL,
    [p_authorizedtounlockpages] TINYINT        NULL,
    [p_ltfpartyid]              INT            NULL,
    [p_memberid]                INT            NULL,
    [p_membershipid]            INT            NULL,
    [aCLTS]                     BIGINT         NULL,
    [propTS]                    BIGINT         NULL,
    [p_customerid]              NVARCHAR (255) NULL,
    [p_previewcatalogversions]  VARCHAR (8000) NULL,
    [p_title]                   BIGINT         NULL,
    [p_defaultpaymentinfo]      BIGINT         NULL,
    [p_token]                   VARCHAR (8000) NULL,
    [p_originaluid]             NVARCHAR (255) NULL,
    [p_type]                    BIGINT         NULL,
    [dv_batch_id]               BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

