CREATE TABLE [dbo].[stage_hash_spabiz_TICKETDATA] (
    [stage_hash_spabiz_TICKETDATA_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)       NOT NULL,
    [ID]                              DECIMAL (26, 6) NULL,
    [COUNTERID]                       DECIMAL (26, 6) NULL,
    [STOREID]                         DECIMAL (26, 6) NULL,
    [EDITTIME]                        DATETIME        NULL,
    [TICKETID]                        DECIMAL (26, 6) NULL,
    [LINENUM]                         DECIMAL (26, 6) NULL,
    [ITEMID]                          DECIMAL (26, 6) NULL,
    [DATATYPE]                        DECIMAL (26, 6) NULL,
    [GROUPID]                         DECIMAL (26, 6) NULL,
    [CUSTID]                          DECIMAL (26, 6) NULL,
    [STAFFID1]                        DECIMAL (26, 6) NULL,
    [STAFFID2]                        DECIMAL (26, 6) NULL,
    [QTY]                             DECIMAL (26, 6) NULL,
    [RETAILPRICE]                     DECIMAL (26, 6) NULL,
    [COST]                            DECIMAL (26, 6) NULL,
    [DISCOUNTAMOUNT]                  DECIMAL (26, 6) NULL,
    [DISCOUNTPER]                     DECIMAL (26, 6) NULL,
    [DISCOUNTID]                      DECIMAL (26, 6) NULL,
    [Date]                            DATETIME        NULL,
    [STATUS]                          DECIMAL (26, 6) NULL,
    [RETURNWHERE]                     DECIMAL (26, 6) NULL,
    [EXTPRICE]                        DECIMAL (26, 6) NULL,
    [SHIFTID]                         DECIMAL (26, 6) NULL,
    [DAYID]                           DECIMAL (26, 6) NULL,
    [PERIODID]                        DECIMAL (26, 6) NULL,
    [TICKETDISAMT]                    DECIMAL (26, 6) NULL,
    [TAXABLE]                         DECIMAL (26, 6) NULL,
    [RETENTION]                       DECIMAL (26, 6) NULL,
    [SUBGROUPID]                      DECIMAL (26, 6) NULL,
    [PACKAGEID]                       DECIMAL (26, 6) NULL,
    [SERVICEAMT]                      DECIMAL (26, 6) NULL,
    [SERVICEQTY]                      DECIMAL (26, 6) NULL,
    [PRODUCTAMT]                      DECIMAL (26, 6) NULL,
    [PRODUCTQTY]                      DECIMAL (26, 6) NULL,
    [OTHERAMT]                        DECIMAL (26, 6) NULL,
    [OTHERQTY]                        DECIMAL (26, 6) NULL,
    [TIMEID]                          DECIMAL (26, 6) NULL,
    [PROMOID]                         DECIMAL (26, 6) NULL,
    [STORE_NUMBER]                    DECIMAL (26, 6) NULL,
    [GLACCOUNT]                       VARCHAR (45)    NULL,
    [SALESGLACCOUNT]                  VARCHAR (60)    NULL,
    [DISCOUNTGLACCOUNT]               VARCHAR (60)    NULL,
    [COSTGLACCOUNT]                   VARCHAR (60)    NULL,
    [STARTTIME]                       DATETIME        NULL,
    [ENDTIME]                         DATETIME        NULL,
    [MASTERTICKET]                    DECIMAL (26, 6) NULL,
    [MERGEDITEM]                      DECIMAL (26, 6) NULL,
    [SHIP_TO]                         VARCHAR (1500)  NULL,
    [SHIP_STATUS]                     DECIMAL (26, 6) NULL,
    [RETURNREASON]                    DECIMAL (26, 6) NULL,
    [SERVICECHARGEPARENTID]           DECIMAL (26, 6) NULL,
    [dv_load_date_time]               DATETIME        NOT NULL,
    [dv_inserted_date_time]           DATETIME        NOT NULL,
    [dv_insert_user]                  VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]            DATETIME        NULL,
    [dv_update_user]                  VARCHAR (50)    NULL,
    [dv_batch_id]                     BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

