CREATE TABLE [dbo].[stage_hash_ltfmart_EmployeeGoals] (
    [stage_hash_ltfmart_EmployeeGoals_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                             CHAR (32)       NOT NULL,
    [ID]                                  INT             NULL,
    [EmployeeID]                          INT             NULL,
    [ClubID]                              INT             NULL,
    [ValCompensationPlanID]               INT             NULL,
    [GoalDate]                            DATETIME        NULL,
    [NewHireTypeID]                       INT             NULL,
    [MALevelID]                           INT             NULL,
    [SDHTypeID]                           INT             NULL,
    [AppointmentShowGoal]                 INT             NULL,
    [MembershipGoal]                      INT             NULL,
    [VIPReferralGoal]                     INT             NULL,
    [HoursWorked]                         INT             NULL,
    [UnitQuota]                           INT             NULL,
    [UnitQuotaOverride]                   INT             NULL,
    [NDTQuota]                            DECIMAL (26, 6) NULL,
    [HasGoal]                             BIT             NULL,
    [IsASDH]                              BIT             NULL,
    [IsDeptHead]                          BIT             NULL,
    [IsNewHire]                           BIT             NULL,
    [IsPartTime]                          BIT             NULL,
    [OverrideUnitQuota]                   BIT             NULL,
    [SalesCompException]                  BIT             NULL,
    [OverrideUserRole]                    BIT             NULL,
    [InactiveDate]                        DATETIME        NULL,
    [CreateEmpID]                         INT             NULL,
    [CreateDateTime]                      DATETIME        NULL,
    [ModifyEmpID]                         INT             NULL,
    [ModifyDateTime]                      DATETIME        NULL,
    [RowVersion]                          BINARY (8)      NULL,
    [dv_load_date_time]                   DATETIME        NOT NULL,
    [dv_inserted_date_time]               DATETIME        NOT NULL,
    [dv_insert_user]                      VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                DATETIME        NULL,
    [dv_update_user]                      VARCHAR (50)    NULL,
    [dv_batch_id]                         BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

