CREATE TABLE [dbo].[stage_hash_olo_order_detail] (
    [stage_hash_olo_order_detail_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                        CHAR (32)       NOT NULL,
    [Messageid]                      VARCHAR (255)   NULL,
    [Orderid]                        INT             NULL,
    [EventType]                      VARCHAR (255)   NULL,
    [TimeCancelled]                  VARCHAR (29)    NULL,
    [CancelReason]                   VARCHAR (255)   NULL,
    [ExternalReference]              VARCHAR (255)   NULL,
    [StoreNumber]                    VARCHAR (255)   NULL,
    [TimePlaced]                     VARCHAR (29)    NULL,
    [TimeWanted]                     VARCHAR (29)    NULL,
    [TimeReady]                      VARCHAR (29)    NULL,
    [SubTotal]                       DECIMAL (26, 2) NULL,
    [SalesTax]                       DECIMAL (26, 2) NULL,
    [Tip]                            DECIMAL (26, 2) NULL,
    [Delivery]                       DECIMAL (26, 2) NULL,
    [Discount]                       DECIMAL (26, 2) NULL,
    [Total]                          DECIMAL (26, 2) NULL,
    [CustomerDelivery]               DECIMAL (26, 2) NULL,
    [PaymentType]                    VARCHAR (255)   NULL,
    [PaymentDescription]             VARCHAR (255)   NULL,
    [Amount]                         DECIMAL (26, 2) NULL,
    [TimeAdjusted]                   VARCHAR (29)    NULL,
    [AdjustmentAmount]               DECIMAL (26, 2) NULL,
    [AdjustmentType]                 VARCHAR (255)   NULL,
    [AdjustmentReason]               VARCHAR (255)   NULL,
    [Timeclosed]                     VARCHAR (29)    NULL,
    [jan_one]                        DATETIME        NULL,
    [dv_load_date_time]              DATETIME        NOT NULL,
    [dv_inserted_date_time]          DATETIME        NOT NULL,
    [dv_insert_user]                 VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]           DATETIME        NULL,
    [dv_update_user]                 VARCHAR (50)    NULL,
    [dv_batch_id]                    BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

