CREATE TABLE [dbo].[stage_hash_spabiz_PODATA] (
    [stage_hash_spabiz_PODATA_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                     CHAR (32)       NOT NULL,
    [ID]                          DECIMAL (26, 6) NULL,
    [COUNTERID]                   DECIMAL (26, 6) NULL,
    [STOREID]                     DECIMAL (26, 6) NULL,
    [EDITTIME]                    DATETIME        NULL,
    [Date]                        DATETIME        NULL,
    [POID]                        DECIMAL (26, 6) NULL,
    [TYPE]                        DECIMAL (26, 6) NULL,
    [VENDORID]                    DECIMAL (26, 6) NULL,
    [LINENUM]                     DECIMAL (26, 6) NULL,
    [PRODUCTID]                   DECIMAL (26, 6) NULL,
    [NORMALCOST]                  DECIMAL (26, 6) NULL,
    [COST]                        DECIMAL (26, 6) NULL,
    [EXTCOST]                     DECIMAL (26, 6) NULL,
    [QTYORD]                      DECIMAL (26, 6) NULL,
    [QTYREC]                      DECIMAL (26, 6) NULL,
    [STATUS]                      DECIMAL (26, 6) NULL,
    [CATID]                       DECIMAL (26, 6) NULL,
    [MARGIN]                      DECIMAL (26, 6) NULL,
    [RETAILPRICE]                 DECIMAL (26, 6) NULL,
    [NAME]                        VARCHAR (150)   NULL,
    [STORE_NUMBER]                DECIMAL (26, 6) NULL,
    [dv_load_date_time]           DATETIME        NOT NULL,
    [dv_inserted_date_time]       DATETIME        NOT NULL,
    [dv_insert_user]              VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]        DATETIME        NULL,
    [dv_update_user]              VARCHAR (50)    NULL,
    [dv_batch_id]                 BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

