CREATE TABLE [dbo].[stage_hash_ig_it_trn_Order_Tender] (
    [stage_hash_ig_it_trn_Order_Tender_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [adtl_info]                            NVARCHAR (32)   NULL,
    [auth_acct_no]                         NVARCHAR (32)   NULL,
    [breakage_amt]                         DECIMAL (26, 6) NULL,
    [change_amt]                           DECIMAL (26, 6) NULL,
    [change_tender_id]                     INT             NULL,
    [charges_to_date_amt]                  DECIMAL (26, 6) NULL,
    [curr_dec_places]                      SMALLINT        NULL,
    [customer_name]                        NVARCHAR (32)   NULL,
    [exchange_rate]                        DECIMAL (26, 6) NULL,
    [order_hdr_id]                         INT             NULL,
    [PMS_post_flag]                        BIT             NULL,
    [post_acct_no]                         NVARCHAR (32)   NULL,
    [post_system1_flag]                    BIT             NULL,
    [post_system2_flag]                    BIT             NULL,
    [post_system3_flag]                    BIT             NULL,
    [post_system4_flag]                    BIT             NULL,
    [post_system5_flag]                    BIT             NULL,
    [post_system6_flag]                    BIT             NULL,
    [post_system7_flag]                    BIT             NULL,
    [post_system8_flag]                    BIT             NULL,
    [prorata_discount_amt]                 DECIMAL (26, 6) NULL,
    [prorata_grat_amt]                     DECIMAL (26, 6) NULL,
    [prorata_sales_amt_gross]              DECIMAL (26, 6) NULL,
    [prorata_svc_chg_amt]                  DECIMAL (26, 6) NULL,
    [prorata_tax_amt]                      DECIMAL (26, 6) NULL,
    [received_curr_amt]                    DECIMAL (26, 6) NULL,
    [remaining_balance_amt]                DECIMAL (26, 6) NULL,
    [sales_tippable_flag]                  BIT             NULL,
    [subtender_id]                         INT             NULL,
    [subtender_qty]                        INT             NULL,
    [tax_removed_code]                     SMALLINT        NULL,
    [tender_amt]                           DECIMAL (26, 6) NULL,
    [tender_id]                            INT             NULL,
    [tender_seq]                           SMALLINT        NULL,
    [tender_type_id]                       INT             NULL,
    [tip_amt]                              DECIMAL (26, 6) NULL,
    [jan_one]                              DATETIME        NULL,
    [dv_load_date_time]                    DATETIME        NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

