CREATE TABLE [dbo].[stage_chronotrack_event] (
    [stage_chronotrack_event_id]      BIGINT          NOT NULL,
    [id]                              BIGINT          NULL,
    [event_group_id]                  BIGINT          NULL,
    [tag]                             NVARCHAR (20)   NULL,
    [name_prefix]                     NVARCHAR (255)  NULL,
    [name]                            NVARCHAR (255)  NULL,
    [description]                     NVARCHAR (512)  NULL,
    [extended_description]            NVARCHAR (1500) NULL,
    [start_datetime]                  DATETIME        NULL,
    [start_time]                      INT             NULL,
    [end_datetime]                    DATETIME        NULL,
    [end_time]                        INT             NULL,
    [date_format]                     NVARCHAR (5)    NULL,
    [location_id]                     BIGINT          NULL,
    [event_closed_message]            NVARCHAR (255)  NULL,
    [organizer_id]                    BIGINT          NULL,
    [additional_info]                 NVARCHAR (512)  NULL,
    [timer_id]                        BIGINT          NULL,
    [site_uri]                        NVARCHAR (512)  NULL,
    [results_url]                     NVARCHAR (512)  NULL,
    [results_theme]                   NVARCHAR (40)   NULL,
    [facebook_url]                    NVARCHAR (512)  NULL,
    [reader_config]                   NVARCHAR (4000) NULL,
    [messaging_lock]                  TINYINT         NULL,
    [live_video]                      NVARCHAR (1024) NULL,
    [mute_video]                      TINYINT         NULL,
    [photo_price]                     DECIMAL (26, 6) NULL,
    [entry_photo_price]               DECIMAL (26, 6) NULL,
    [is_published]                    TINYINT         NULL,
    [is_published_athlinks]           TINYINT         NULL,
    [current_gen_id]                  BIGINT          NULL,
    [wants_photo_purchasing]          TINYINT         NULL,
    [photo_purchasing_help]           NVARCHAR (384)  NULL,
    [photo_service_type]              NVARCHAR (255)  NULL,
    [photo_service_name]              NVARCHAR (255)  NULL,
    [photo_service_url]               NVARCHAR (512)  NULL,
    [show_athlete_names]              TINYINT         NULL,
    [currency_id]                     NCHAR (3)       NULL,
    [reg_version]                     NCHAR (1)       NULL,
    [auto_recalc]                     TINYINT         NULL,
    [ctime]                           INT             NULL,
    [mtime]                           INT             NULL,
    [exp_photo_count]                 INT             NULL,
    [actual_photo_count]              INT             NULL,
    [device_protocol]                 NCHAR (11)      NULL,
    [chip_disambiguation_policy]      NCHAR (7)       NULL,
    [bazu_services]                   NCHAR (232)     NULL,
    [max_races]                       SMALLINT        NULL,
    [max_reg_choices]                 INT             NULL,
    [wants_cim]                       TINYINT         NULL,
    [wants_just_others]               TINYINT         NULL,
    [wants_emergency_group]           NCHAR (10)      NULL,
    [results_age_information]         NVARCHAR (255)  NULL,
    [results_photo_tab]               TINYINT         NULL,
    [results_video_tab]               TINYINT         NULL,
    [payment_location_id]             BIGINT          NULL,
    [check_payable]                   NVARCHAR (255)  NULL,
    [payee]                           NVARCHAR (255)  NULL,
    [results_timer_name]              NVARCHAR (255)  NULL,
    [results_timer_contact]           NVARCHAR (255)  NULL,
    [results_remove_contact]          TINYINT         NULL,
    [enable_kiosk_forms]              INT             NULL,
    [enable_web_forms]                INT             NULL,
    [kiosk_form_settings]             NCHAR (12)      NULL,
    [results_view]                    NCHAR (6)       NULL,
    [results_ranking_columns]         NVARCHAR (255)  NULL,
    [expected_entry]                  INT             NULL,
    [penalties_view]                  NCHAR (8)       NULL,
    [is_test_event]                   TINYINT         NULL,
    [min_interval_duration]           BIGINT          NULL,
    [bib_assignment]                  INT             NULL,
    [enable_teams]                    INT             NULL,
    [last_yrs_event_id]               BIGINT          NULL,
    [on_site_mode]                    NVARCHAR (17)   NULL,
    [onsite_server_form_redirect]     NCHAR (7)       NULL,
    [org_fee_allocation]              DECIMAL (26, 6) NULL,
    [parent_event_id]                 BIGINT          NULL,
    [max_reg_count]                   INT             NULL,
    [external_id]                     NVARCHAR (255)  NULL,
    [check_in]                        TINYINT         NULL,
    [by_proxy]                        TINYINT         NULL,
    [wants_add_address]               TINYINT         NULL,
    [is_membership]                   TINYINT         NULL,
    [volt_recalc]                     TINYINT         NULL,
    [event_google_tag_manager_key]    NVARCHAR (90)   NULL,
    [online_payee_id]                 BIGINT          NULL,
    [bib_lock]                        TINYINT         NULL,
    [ask_for_tag]                     TINYINT         NULL,
    [location_info]                   TINYINT         NULL,
    [date_and_time_info]              TINYINT         NULL,
    [series_id]                       BIGINT          NULL,
    [language_id]                     NCHAR (2)       NULL,
    [bib_validation_option]           NCHAR (16)      NULL,
    [hide_old_form_url]               TINYINT         NULL,
    [twitter_handle]                  NVARCHAR (200)  NULL,
    [third_party_reg_link]            NVARCHAR (200)  NULL,
    [has_hero_image]                  TINYINT         NULL,
    [instagram_handle]                NVARCHAR (200)  NULL,
    [use_email_header]                TINYINT         NULL,
    [hide_from_profile_page]          TINYINT         NULL,
    [clone_inventory]                 TINYINT         NULL,
    [hide_results_claim_button]       TINYINT         NULL,
    [online_payee_change_timestamp]   INT             NULL,
    [onsite_payee_id]                 BIGINT          NULL,
    [onsite_payee_change_timestamp]   INT             NULL,
    [policy_agree]                    TINYINT         NULL,
    [policy_url]                      NVARCHAR (255)  NULL,
    [marketing_email_question]        TINYINT         NULL,
    [marketing_email_question_text]   VARCHAR (4000)  NULL,
    [marketing_emails_event_name]     NVARCHAR (255)  NULL,
    [marketing_consent_question]      TINYINT         NULL,
    [marketing_consent_question_text] VARCHAR (4000)  NULL,
    [unarchive_time]                  INT             NULL,
    [enable_logo_overlay]             TINYINT         NULL,
    [auto_sync_athlinks]              TINYINT         NULL,
    [time_sync_athlinks]              INT             NULL,
    [auto_sync_athlinks_error]        NVARCHAR (4000) NULL,
    [dummy_modified_date_time]        DATETIME        NULL,
    [dv_batch_id]                     BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

