CREATE TABLE [dbo].[stage_hybris_orders] (
    [stage_hybris_orders_id]         BIGINT          NOT NULL,
    [hjmpTS]                         BIGINT          NULL,
    [createdTS]                      DATETIME        NULL,
    [modifiedTS]                     DATETIME        NULL,
    [TypePkString]                   BIGINT          NULL,
    [OwnerPkString]                  BIGINT          NULL,
    [PK]                             BIGINT          NULL,
    [p_calculated]                   TINYINT         NULL,
    [p_code]                         NVARCHAR (255)  NULL,
    [p_currency]                     BIGINT          NULL,
    [p_deliveryaddress]              BIGINT          NULL,
    [p_deliverycost]                 DECIMAL (30, 8) NULL,
    [p_deliverymode]                 BIGINT          NULL,
    [p_deliverystatus]               BIGINT          NULL,
    [p_globaldiscountvaluesinternal] VARCHAR (8000)  NULL,
    [p_net]                          TINYINT         NULL,
    [p_paymentaddress]               BIGINT          NULL,
    [p_paymentcost]                  DECIMAL (30, 8) NULL,
    [p_paymentinfo]                  BIGINT          NULL,
    [p_paymentmode]                  BIGINT          NULL,
    [p_paymentstatus]                BIGINT          NULL,
    [p_status]                       BIGINT          NULL,
    [p_exportstatus]                 BIGINT          NULL,
    [p_statusinfo]                   NVARCHAR (255)  NULL,
    [p_totalprice]                   DECIMAL (30, 8) NULL,
    [p_totaldiscounts]               DECIMAL (30, 8) NULL,
    [p_totaltax]                     DECIMAL (30, 8) NULL,
    [p_totaltaxvaluesinternal]       VARCHAR (8000)  NULL,
    [p_user]                         BIGINT          NULL,
    [p_subtotal]                     DECIMAL (30, 8) NULL,
    [p_discountsincludedeliverycost] TINYINT         NULL,
    [p_discountsincludepaymentcost]  TINYINT         NULL,
    [p_europe1pricefactory_udg]      BIGINT          NULL,
    [p_europe1pricefactory_upg]      BIGINT          NULL,
    [p_europe1pricefactory_utg]      BIGINT          NULL,
    [p_previousdeliverymode]         BIGINT          NULL,
    [p_site]                         BIGINT          NULL,
    [p_store]                        BIGINT          NULL,
    [p_guid]                         NVARCHAR (255)  NULL,
    [p_billingtime]                  BIGINT          NULL,
    [p_parent]                       BIGINT          NULL,
    [p_versionid]                    NVARCHAR (255)  NULL,
    [p_originalversion]              BIGINT          NULL,
    [p_fraudulent]                   TINYINT         NULL,
    [p_potentiallyfraudulent]        TINYINT         NULL,
    [p_salesapplication]             BIGINT          NULL,
    [p_language]                     BIGINT          NULL,
    [p_placedby]                     BIGINT          NULL,
    [aCLTS]                          BIGINT          NULL,
    [propTS]                         BIGINT          NULL,
    [p_fulfilmentstatus]             BIGINT          NULL,
    [p_notes]                        NVARCHAR (255)  NULL,
    [p_fraudpreventionsessionid]     NVARCHAR (255)  NULL,
    [p_commissionemployeeid]         NVARCHAR (255)  NULL,
    [dv_batch_id]                    BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

