CREATE TABLE [dbo].[stage_crmcloudsync_Appointment] (
    [stage_crmcloudsync_Appointment_id] BIGINT         NOT NULL,
    [activityid]                        VARCHAR (36)   NULL,
    [activitytypecode]                  VARCHAR (64)   NULL,
    [activitytypecodename]              VARCHAR (255)  NULL,
    [actualdurationminutes]             INT            NULL,
    [actualend]                         DATETIME       NULL,
    [actualstart]                       DATETIME       NULL,
    [category]                          VARCHAR (250)  NULL,
    [createdby]                         VARCHAR (36)   NULL,
    [createdbyname]                     VARCHAR (200)  NULL,
    [createdbyyominame]                 VARCHAR (200)  NULL,
    [createdon]                         DATETIME       NULL,
    [createdonbehalfby]                 VARCHAR (36)   NULL,
    [createdonbehalfbyname]             VARCHAR (200)  NULL,
    [createdonbehalfbyyominame]         VARCHAR (200)  NULL,
    [description]                       VARCHAR (8000) NULL,
    [exchangerate]                      DECIMAL (28)   NULL,
    [globalobjectid]                    VARCHAR (300)  NULL,
    [importsequencenumber]              INT            NULL,
    [instancetypecode]                  INT            NULL,
    [instancetypecodename]              VARCHAR (255)  NULL,
    [isalldayevent]                     VARCHAR (36)   NULL,
    [isalldayeventname]                 VARCHAR (255)  NULL,
    [isbilled]                          VARCHAR (36)   NULL,
    [isbilledname]                      VARCHAR (255)  NULL,
    [ismapiprivate]                     VARCHAR (36)   NULL,
    [ismapiprivatename]                 VARCHAR (255)  NULL,
    [isregularactivity]                 VARCHAR (36)   NULL,
    [isregularactivityname]             VARCHAR (255)  NULL,
    [isworkflowcreated]                 VARCHAR (36)   NULL,
    [isworkflowcreatedname]             VARCHAR (255)  NULL,
    [location]                          VARCHAR (200)  NULL,
    [ltf_appointmenttype]               INT            NULL,
    [ltf_appointmenttypename]           VARCHAR (255)  NULL,
    [ltf_clubappointmentsid]            VARCHAR (36)   NULL,
    [ltf_clubappointmentsidname]        VARCHAR (100)  NULL,
    [ltf_clubid]                        VARCHAR (36)   NULL,
    [ltf_clubidname]                    VARCHAR (100)  NULL,
    [ltf_udwid]                         VARCHAR (255)  NULL,
    [modifiedby]                        VARCHAR (36)   NULL,
    [modifiedbyname]                    VARCHAR (200)  NULL,
    [modifiedbyyominame]                VARCHAR (200)  NULL,
    [modifiedfieldsmask]                VARCHAR (8000) NULL,
    [modifiedon]                        DATETIME       NULL,
    [modifiedonbehalfby]                VARCHAR (36)   NULL,
    [modifiedonbehalfbyname]            VARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]        VARCHAR (200)  NULL,
    [optionalattendees]                 VARCHAR (2000) NULL,
    [organizer]                         VARCHAR (2000) NULL,
    [originalstartdate]                 DATETIME       NULL,
    [outlookownerapptid]                INT            NULL,
    [overriddencreatedon]               DATETIME       NULL,
    [ownerid]                           VARCHAR (36)   NULL,
    [owneridname]                       VARCHAR (200)  NULL,
    [owneridtype]                       VARCHAR (64)   NULL,
    [owneridyominame]                   VARCHAR (200)  NULL,
    [owningbusinessunit]                VARCHAR (36)   NULL,
    [owningteam]                        VARCHAR (36)   NULL,
    [owninguser]                        VARCHAR (36)   NULL,
    [prioritycode]                      INT            NULL,
    [prioritycodename]                  VARCHAR (255)  NULL,
    [processid]                         VARCHAR (36)   NULL,
    [regardingobjectid]                 VARCHAR (36)   NULL,
    [regardingobjectidname]             VARCHAR (36)   NULL,
    [regardingobjectidyominame]         VARCHAR (36)   NULL,
    [regardingobjecttypecode]           VARCHAR (64)   NULL,
    [requiredattendees]                 VARCHAR (2000) NULL,
    [scheduleddurationminutes]          INT            NULL,
    [scheduledend]                      DATETIME       NULL,
    [scheduledstart]                    DATETIME       NULL,
    [seriesid]                          VARCHAR (36)   NULL,
    [serviceid]                         VARCHAR (36)   NULL,
    [stageid]                           VARCHAR (36)   NULL,
    [statecode]                         INT            NULL,
    [statecodename]                     VARCHAR (255)  NULL,
    [statuscode]                        INT            NULL,
    [statuscodename]                    VARCHAR (255)  NULL,
    [subcategory]                       VARCHAR (250)  NULL,
    [subject]                           VARCHAR (200)  NULL,
    [timezoneruleversionnumber]         INT            NULL,
    [transactioncurrencyid]             VARCHAR (36)   NULL,
    [transactioncurrencyidname]         VARCHAR (100)  NULL,
    [utcconversiontimezonecode]         INT            NULL,
    [versionnumber]                     BIGINT         NULL,
    [InsertedDateTime]                  DATETIME       NULL,
    [InsertUser]                        VARCHAR (100)  NULL,
    [ltf_metontour]                     VARCHAR (200)  NULL,
    [UpdatedDateTime]                   DATETIME       NULL,
    [UpdateUser]                        VARCHAR (50)   NULL,
    [ltf_webbookingsource]              INT            NULL,
    [ltf_webbookingsourcename]          VARCHAR (255)  NULL,
    [ltf_checkinflag]                   INT            NULL,
    [ltf_checkinflagname]               VARCHAR (255)  NULL,
    [ltf_program]                       INT            NULL,
    [ltf_programname]                   VARCHAR (255)  NULL,
    [traversedpath]                     VARCHAR (1250) NULL,
    [ltf_qrcode]                        VARCHAR (8000) NULL,
    [dv_batch_id]                       BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

