CREATE TABLE [dbo].[stage_hash_humanity_trades] (
    [stage_hash_humanity_trades_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                       CHAR (32)     NOT NULL,
    [shift_id]                      BIGINT        NULL,
    [company_id]                    VARCHAR (255) NULL,
    [company_name]                  VARCHAR (255) NULL,
    [trade_requested_employee_id]   VARCHAR (255) NULL,
    [trade_requested_employee_eid]  VARCHAR (255) NULL,
    [trade_requested_employee_name] VARCHAR (255) NULL,
    [traded_to_employee_id]         VARCHAR (255) NULL,
    [traded_to_employee_eid]        VARCHAR (255) NULL,
    [traded_to_employee_name]       VARCHAR (255) NULL,
    [trade_reason]                  VARCHAR (255) NULL,
    [trade_requested_datetime_utc]  VARCHAR (255) NULL,
    [trade_status]                  VARCHAR (255) NULL,
    [swap]                          VARCHAR (255) NULL,
    [shift_start_datetime_utc]      VARCHAR (255) NULL,
    [shift_end_datetime_utc]        VARCHAR (255) NULL,
    [hours]                         VARCHAR (255) NULL,
    [shift_type]                    VARCHAR (255) NULL,
    [position_id]                   VARCHAR (255) NULL,
    [workday_position_id]           VARCHAR (255) NULL,
    [position_name]                 VARCHAR (255) NULL,
    [location_id]                   VARCHAR (255) NULL,
    [location_name]                 VARCHAR (255) NULL,
    [ltf_file_name]                 VARCHAR (255) NULL,
    [file_arrive_date]              VARCHAR (255) NULL,
    [dummy_modified_date_time]      DATETIME      NULL,
    [dv_load_date_time]             DATETIME      NOT NULL,
    [dv_batch_id]                   BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

