CREATE TABLE [dbo].[stage_hash_mms_Product] (
    [stage_hash_mms_Product_id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)      NOT NULL,
    [ProductID]                         INT            NULL,
    [DepartmentID]                      INT            NULL,
    [Name]                              VARCHAR (20)   NULL,
    [Description]                       VARCHAR (50)   NULL,
    [DisplayUIFlag]                     BIT            NULL,
    [SortOrder]                         INT            NULL,
    [InsertedDateTime]                  DATETIME       NULL,
    [TurnOffDateTime]                   DATETIME       NULL,
    [StartDate]                         DATETIME       NULL,
    [EndDate]                           DATETIME       NULL,
    [GLAccountNumber]                   VARCHAR (10)   NULL,
    [GLSubAccountNumber]                VARCHAR (7)    NULL,
    [GLOverRideClubID]                  INT            NULL,
    [ValGLGroupID]                      INT            NULL,
    [ValRecurrentProductTypeID]         INT            NULL,
    [CompletePackageFlag]               BIT            NULL,
    [AllowZeroDollarFlag]               BIT            NULL,
    [PackageProductFlag]                BIT            NULL,
    [SoldNotServicedFlag]               BIT            NULL,
    [UpdatedDateTime]                   DATETIME       NULL,
    [ValProductStatusID]                INT            NULL,
    [TipAllowedFlag]                    BIT            NULL,
    [JrMemberDuesFlag]                  BIT            NULL,
    [ValAssessmentDayID]                INT            NULL,
    [EligibleForHoldFlag]               BIT            NULL,
    [ConfirmMemberDataFlag]             BIT            NULL,
    [MedicalProductFlag]                BIT            NULL,
    [BundleProductFlag]                 BIT            NULL,
    [WorkdayAccount]                    VARCHAR (6)    NULL,
    [WorkdayCostCenter]                 VARCHAR (6)    NULL,
    [WorkdayOffering]                   VARCHAR (10)   NULL,
    [WorkdayOverRideRegion]             VARCHAR (4)    NULL,
    [WorkdayRevenueProductGroupAccount] VARCHAR (6)    NULL,
    [DeferredRevenueFlag]               BIT            NULL,
    [PriceLockedFlag]                   BIT            NULL,
    [RevenueCategory]                   VARCHAR (7)    NULL,
    [SpendCategory]                     VARCHAR (7)    NULL,
    [PayComponent]                      VARCHAR (50)   NULL,
    [AssessAsDuesFlag]                  BIT            NULL,
    [ValEmployeeLevelTypeID]            INT            NULL,
    [SKU]                               VARCHAR (50)   NULL,
    [LTBuckEligible]                    BIT            NULL,
    [LTBuckCostPercent]                 NUMERIC (4, 1) NULL,
    [ExcludeFromClubPOSFlag]            BIT            NULL,
    [AccessByPricePaidFlag]             BIT            NULL,
    [dv_load_date_time]                 DATETIME       NOT NULL,
    [dv_batch_id]                       BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

