CREATE TABLE [dbo].[stage_crmcloudsync_LTF_RelatedInterest] (
    [stage_crmcloudsync_LTF_RelatedInterest_id] BIGINT         NOT NULL,
    [createdby]                                 VARCHAR (36)   NULL,
    [createdbyname]                             NVARCHAR (200) NULL,
    [createdbyyominame]                         NVARCHAR (200) NULL,
    [createdon]                                 DATETIME       NULL,
    [createdonbehalfby]                         VARCHAR (36)   NULL,
    [createdonbehalfbyname]                     NVARCHAR (200) NULL,
    [createdonbehalfbyyominame]                 NVARCHAR (200) NULL,
    [importsequencenumber]                      INT            NULL,
    [ltf_contactid]                             VARCHAR (36)   NULL,
    [ltf_contactidname]                         NVARCHAR (160) NULL,
    [ltf_contactidyominame]                     NVARCHAR (160) NULL,
    [ltf_interestid]                            VARCHAR (36)   NULL,
    [ltf_interestidname]                        NVARCHAR (100) NULL,
    [ltf_leadid]                                VARCHAR (36)   NULL,
    [ltf_leadidname]                            NVARCHAR (160) NULL,
    [ltf_leadidyominame]                        NVARCHAR (160) NULL,
    [ltf_name]                                  NVARCHAR (100) NULL,
    [ltf_opportunityid]                         VARCHAR (36)   NULL,
    [ltf_opportunityidname]                     NVARCHAR (300) NULL,
    [ltf_relatedinterestid]                     VARCHAR (36)   NULL,
    [modifiedby]                                VARCHAR (36)   NULL,
    [modifiedbyname]                            NVARCHAR (200) NULL,
    [modifiedbyyominame]                        NVARCHAR (200) NULL,
    [modifiedon]                                DATETIME       NULL,
    [modifiedonbehalfby]                        VARCHAR (36)   NULL,
    [modifiedonbehalfbyname]                    NVARCHAR (200) NULL,
    [modifiedonbehalfbyyominame]                NVARCHAR (200) NULL,
    [overriddencreatedon]                       DATETIME       NULL,
    [ownerid]                                   VARCHAR (36)   NULL,
    [owneridname]                               NVARCHAR (200) NULL,
    [owneridtype]                               NVARCHAR (64)  NULL,
    [owneridyominame]                           NVARCHAR (200) NULL,
    [owningbusinessunit]                        VARCHAR (36)   NULL,
    [owningteam]                                VARCHAR (36)   NULL,
    [owninguser]                                VARCHAR (36)   NULL,
    [statecode]                                 INT            NULL,
    [statecodename]                             NVARCHAR (255) NULL,
    [statuscode]                                INT            NULL,
    [statuscodename]                            NVARCHAR (255) NULL,
    [timezoneruleversionnumber]                 INT            NULL,
    [utcconversiontimezonecode]                 INT            NULL,
    [versionnumber]                             BIGINT         NULL,
    [InsertedDateTime]                          DATETIME       NULL,
    [InsertUser]                                VARCHAR (100)  NULL,
    [UpdatedDateTime]                           DATETIME       NULL,
    [UpdateUser]                                VARCHAR (50)   NULL,
    [ltf_adddate]                               DATETIME       NULL,
    [ltf_addby]                                 VARCHAR (36)   NULL,
    [ltf_addsource]                             INT            NULL,
    [ltf_removedate]                            DATETIME       NULL,
    [ltf_removeby]                              VARCHAR (36)   NULL,
    [ltf_removesource]                          INT            NULL,
    [ltf_primaryinterest]                       BIT            NULL,
    [dv_batch_id]                               BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

