CREATE TABLE [dbo].[stage_hash_hybris_fulfillmentpartner] (
    [stage_hash_hybris_fulfillmentpartner_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)      NOT NULL,
    [hjmpTS]                                  BIGINT         NULL,
    [TypePkString]                            BIGINT         NULL,
    [PK]                                      BIGINT         NULL,
    [createdTS]                               DATETIME       NULL,
    [modifiedTS]                              DATETIME       NULL,
    [OwnerPkString]                           BIGINT         NULL,
    [aCLTS]                                   INT            NULL,
    [propTS]                                  INT            NULL,
    [p_displayname]                           NVARCHAR (255) NULL,
    [p_code]                                  NVARCHAR (255) NULL,
    [p_ftpto]                                 NVARCHAR (255) NULL,
    [p_exportfileformat]                      BIGINT         NULL,
    [p_ftpfrom]                               NVARCHAR (255) NULL,
    [p_importfileformat]                      BIGINT         NULL,
    [p_workdaysupplierid]                     NVARCHAR (255) NULL,
    [p_inventoryto]                           NVARCHAR (255) NULL,
    [p_inventoryfileformat]                   NVARCHAR (255) NULL,
    [p_receivercodeid]                        NVARCHAR (255) NULL,
    [p_receiverid]                            NVARCHAR (255) NULL,
    [p_senderqualifier]                       NVARCHAR (255) NULL,
    [p_receiverqualifier]                     NVARCHAR (255) NULL,
    [p_senderid]                              NVARCHAR (255) NULL,
    [dv_load_date_time]                       DATETIME       NOT NULL,
    [dv_inserted_date_time]                   DATETIME       NOT NULL,
    [dv_insert_user]                          VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]                    DATETIME       NULL,
    [dv_update_user]                          VARCHAR (50)   NULL,
    [dv_batch_id]                             BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

