CREATE TABLE [dbo].[stage_hash_crmcloudsync_LTF_ConnectMember] (
    [stage_hash_crmcloudsync_LTF_ConnectMember_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                      CHAR (32)      NOT NULL,
    [createdby]                                    VARCHAR (38)   NULL,
    [createdbyname]                                NVARCHAR (200) NULL,
    [createdbyyominame]                            NVARCHAR (200) NULL,
    [createdon]                                    DATETIME       NULL,
    [createdonbehalfby]                            VARCHAR (38)   NULL,
    [createdonbehalfbyname]                        NVARCHAR (200) NULL,
    [createdonbehalfbyyominame]                    NVARCHAR (200) NULL,
    [importsequencenumber]                         INT            NULL,
    [ltf_connectmemberid]                          VARCHAR (38)   NULL,
    [ltf_connectnotes]                             VARCHAR (8000) NULL,
    [ltf_linkdescription]                          NVARCHAR (150) NULL,
    [ltf_moveitscheduleddate]                      DATETIME       NULL,
    [ltf_moveitscheduledwith]                      NVARCHAR (100) NULL,
    [ltf_opportunityid]                            VARCHAR (38)   NULL,
    [ltf_opportunityidname]                        NVARCHAR (300) NULL,
    [ltf_profilenotes]                             VARCHAR (8000) NULL,
    [ltf_programsofinterest]                       INT            NULL,
    [ltf_programsofinterestname]                   NVARCHAR (255) NULL,
    [ltf_subscriberid]                             VARCHAR (38)   NULL,
    [ltf_subscriberidname]                         NVARCHAR (100) NULL,
    [ltf_wanttodo]                                 INT            NULL,
    [ltf_wanttodoname]                             NVARCHAR (255) NULL,
    [ltf_whometwith]                               NVARCHAR (100) NULL,
    [ltf_whywanttodo]                              INT            NULL,
    [ltf_whywanttodoname]                          NVARCHAR (255) NULL,
    [modifiedby]                                   VARCHAR (38)   NULL,
    [modifiedbyname]                               NVARCHAR (200) NULL,
    [modifiedbyyominame]                           NVARCHAR (200) NULL,
    [modifiedon]                                   DATETIME       NULL,
    [modifiedonbehalfby]                           VARCHAR (38)   NULL,
    [modifiedonbehalfbyname]                       NVARCHAR (200) NULL,
    [modifiedonbehalfbyyominame]                   NVARCHAR (200) NULL,
    [overriddencreatedon]                          DATETIME       NULL,
    [ownerid]                                      VARCHAR (38)   NULL,
    [owneridname]                                  NVARCHAR (200) NULL,
    [owneridtype]                                  NVARCHAR (64)  NULL,
    [owneridyominame]                              NVARCHAR (200) NULL,
    [owningbusinessunit]                           VARCHAR (38)   NULL,
    [owningteam]                                   VARCHAR (38)   NULL,
    [owninguser]                                   VARCHAR (38)   NULL,
    [statecode]                                    INT            NULL,
    [statecodename]                                NVARCHAR (255) NULL,
    [statuscode]                                   INT            NULL,
    [statuscodename]                               NVARCHAR (255) NULL,
    [timezoneruleversionnumber]                    INT            NULL,
    [utcconversiontimezonecode]                    INT            NULL,
    [versionnumber]                                BIGINT         NULL,
    [InsertedDateTime]                             DATETIME       NULL,
    [InsertUser]                                   VARCHAR (100)  NULL,
    [UpdatedDateTime]                              DATETIME       NULL,
    [UpdateUser]                                   VARCHAR (50)   NULL,
    [dv_load_date_time]                            DATETIME       NOT NULL,
    [dv_updated_date_time]                         DATETIME       NULL,
    [dv_update_user]                               VARCHAR (50)   NULL,
    [dv_batch_id]                                  BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

