CREATE TABLE [dbo].[stage_crmcloudsync_Annotation] (
    [stage_crmcloudsync_Annotation_id] BIGINT          NOT NULL,
    [annotationid]                     VARCHAR (36)    NULL,
    [createdby]                        VARCHAR (36)    NULL,
    [createdbyname]                    NVARCHAR (200)  NULL,
    [createdbyyominame]                NVARCHAR (200)  NULL,
    [createdon]                        DATETIME        NULL,
    [createdonbehalfby]                VARCHAR (36)    NULL,
    [createdonbehalfbyname]            NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]        NVARCHAR (200)  NULL,
    [documentbody]                     NVARCHAR (4000) NULL,
    [filename]                         NVARCHAR (255)  NULL,
    [filesize]                         INT             NULL,
    [importsequencenumber]             INT             NULL,
    [isdocument]                       INT             NULL,
    [isdocumentname]                   NVARCHAR (255)  NULL,
    [isprivatename]                    NVARCHAR (255)  NULL,
    [langid]                           NVARCHAR (2)    NULL,
    [mimetype]                         NVARCHAR (256)  NULL,
    [modifiedby]                       VARCHAR (36)    NULL,
    [modifiedbyname]                   NVARCHAR (200)  NULL,
    [modifiedbyyominame]               NVARCHAR (200)  NULL,
    [modifiedon]                       DATETIME        NULL,
    [modifiedonbehalfby]               VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]           NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]       NVARCHAR (200)  NULL,
    [notetext]                         NVARCHAR (4000) NULL,
    [objectid]                         VARCHAR (36)    NULL,
    [objectidtypecode]                 NVARCHAR (64)   NULL,
    [objecttypecode]                   NVARCHAR (64)   NULL,
    [objecttypecodename]               NVARCHAR (255)  NULL,
    [overriddencreatedon]              DATETIME        NULL,
    [ownerid]                          VARCHAR (36)    NULL,
    [owneridname]                      NVARCHAR (200)  NULL,
    [owneridtype]                      NVARCHAR (64)   NULL,
    [owneridyominame]                  NVARCHAR (200)  NULL,
    [owningbusinessunit]               VARCHAR (36)    NULL,
    [owningteam]                       VARCHAR (36)    NULL,
    [owninguser]                       VARCHAR (36)    NULL,
    [stepid]                           NVARCHAR (32)   NULL,
    [subject]                          NVARCHAR (500)  NULL,
    [versionnumber]                    BIGINT          NULL,
    [InsertedDateTime]                 DATETIME        NULL,
    [InsertUser]                       VARCHAR (100)   NULL,
    [UpdatedDateTime]                  DATETIME        NULL,
    [UpdateUser]                       VARCHAR (50)    NULL,
    [dv_batch_id]                      BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

