CREATE TABLE [dbo].[stage_hash_hybris_promotion] (
    [stage_hash_hybris_promotion_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                        CHAR (32)       NOT NULL,
    [hjmpTS]                         BIGINT          NULL,
    [createdTS]                      DATETIME        NULL,
    [modifiedTS]                     DATETIME        NULL,
    [TypePkString]                   BIGINT          NULL,
    [OwnerPkString]                  BIGINT          NULL,
    [PK]                             BIGINT          NULL,
    [p_code]                         NVARCHAR (255)  NULL,
    [p_title]                        NVARCHAR (255)  NULL,
    [p_description]                  VARCHAR (8000)  NULL,
    [p_startdate]                    DATETIME        NULL,
    [p_enddate]                      DATETIME        NULL,
    [p_detailsurl]                   NVARCHAR (255)  NULL,
    [p_enabled]                      TINYINT         NULL,
    [p_priority]                     INT             NULL,
    [p_immutablekeyhash]             NVARCHAR (255)  NULL,
    [p_immutablekey]                 VARCHAR (8000)  NULL,
    [p_promotiongroup]               BIGINT          NULL,
    [aCLTS]                          BIGINT          NULL,
    [propTS]                         BIGINT          NULL,
    [p_productbanner]                BIGINT          NULL,
    [p_productfixedunitprice]        VARCHAR (8000)  NULL,
    [p_percentagediscount]           DECIMAL (26, 6) NULL,
    [p_qualifyingcount]              INT             NULL,
    [p_freecount]                    INT             NULL,
    [p_bundleprices]                 VARCHAR (8000)  NULL,
    [p_qualifyingcountsandbundlepri] VARCHAR (8000)  NULL,
    [p_partnerproducts]              VARCHAR (8000)  NULL,
    [p_partnerprices]                VARCHAR (8000)  NULL,
    [p_partnerproduct]               BIGINT          NULL,
    [p_thresholdtotals]              VARCHAR (8000)  NULL,
    [p_discountproduct]              BIGINT          NULL,
    [p_productprices]                VARCHAR (8000)  NULL,
    [p_includediscountedpriceinthre] TINYINT         NULL,
    [p_discountprices]               VARCHAR (8000)  NULL,
    [p_giftproduct]                  BIGINT          NULL,
    [p_freevoucher]                  BIGINT          NULL,
    [p_deliverymode]                 BIGINT          NULL,
    [p_rule]                         BIGINT          NULL,
    [dv_load_date_time]              DATETIME        NOT NULL,
    [dv_inserted_date_time]          DATETIME        NOT NULL,
    [dv_insert_user]                 VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]           DATETIME        NULL,
    [dv_update_user]                 VARCHAR (50)    NULL,
    [dv_batch_id]                    BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

