CREATE TABLE [dbo].[stage_hybris_products] (
    [stage_hybris_products_id]  BIGINT          NOT NULL,
    [hjmpTS]                    BIGINT          NULL,
    [TypePkString]              BIGINT          NULL,
    [PK]                        BIGINT          NULL,
    [createdTS]                 DATETIME        NULL,
    [modifiedTS]                DATETIME        NULL,
    [OwnerPkString]             BIGINT          NULL,
    [aCLTS]                     INT             NULL,
    [propTS]                    INT             NULL,
    [p_varianttype]             BIGINT          NULL,
    [p_manufactureraid]         NVARCHAR (255)  NULL,
    [p_normal]                  VARCHAR (8000)  NULL,
    [p_state]                   BIGINT          NULL,
    [p_number]                  INT             NULL,
    [p_autothumbnails]          VARCHAR (8000)  NULL,
    [p_erpgroupsupplier]        NVARCHAR (255)  NULL,
    [p_catalogversion]          BIGINT          NULL,
    [code]                      NVARCHAR (255)  NULL,
    [p_productwidth]            DECIMAL (26, 6) NULL,
    [p_offlinedate]             DATETIME        NULL,
    [p_detail]                  VARCHAR (8000)  NULL,
    [p_electronicshippingflag]  TINYINT         NULL,
    [p_order]                   INT             NULL,
    [p_mediacontainer]          BIGINT          NULL,
    [p_offerexternallinkflag]   TINYINT         NULL,
    [p_swatchcolour]            NVARCHAR (255)  NULL,
    [p_simpleasset]             BIGINT          NULL,
    [p_giftcardflag]            TINYINT         NULL,
    [p_startlinenumber]         INT             NULL,
    [p_numbercontentunits]      DECIMAL (26, 6) NULL,
    [p_data_sheet]              VARCHAR (8000)  NULL,
    [p_europe1pricefactory_pdg] BIGINT          NULL,
    [p_fulfillmentpartner]      BIGINT          NULL,
    [p_baseproduct]             BIGINT          NULL,
    [p_denomination]            INT             NULL,
    [unitpk]                    BIGINT          NULL,
    [p_deliverytime]            DECIMAL (26, 6) NULL,
    [p_mobileproductflag]       TINYINT         NULL,
    [p_previousbaseproduct]     BIGINT          NULL,
    [p_maxorderquantity]        INT             NULL,
    [p_thumbnail]               BIGINT          NULL,
    [p_productlength]           DECIMAL (26, 6) NULL,
    [p_manufacturername]        NVARCHAR (255)  NULL,
    [p_endlinenumber]           INT             NULL,
    [p_thumbnails]              VARCHAR (8000)  NULL,
    [p_minorderquantity]        INT             NULL,
    [p_productheight]           DECIMAL (26, 6) NULL,
    [p_freeuspsshippingflag]    TINYINT         NULL,
    [p_ean]                     NVARCHAR (255)  NULL,
    [p_egiftcards]              VARCHAR (8000)  NULL,
    [p_club]                    BIGINT          NULL,
    [p_logo]                    VARCHAR (8000)  NULL,
    [p_autoshipflag]            TINYINT         NULL,
    [p_orderquantityinterval]   INT             NULL,
    [p_others]                  VARCHAR (8000)  NULL,
    [p_egiftcardflag]           TINYINT         NULL,
    [p_galleryimages]           VARCHAR (8000)  NULL,
    [p_onlinedate]              DATETIME        NULL,
    [p_media]                   BIGINT          NULL,
    [p_contentunit]             BIGINT          NULL,
    [p_ltfofferflag]            TINYINT         NULL,
    [p_genders]                 VARCHAR (8000)  NULL,
    [p_rawasset]                BIGINT          NULL,
    [p_europe1pricefactory_ptg] BIGINT          NULL,
    [p_productcost]             DECIMAL (26, 6) NULL,
    [p_pricequantity]           DECIMAL (26, 6) NULL,
    [p_weight]                  DECIMAL (26, 6) NULL,
    [p_picture]                 BIGINT          NULL,
    [p_approvalstatus]          BIGINT          NULL,
    [p_europe1pricefactory_ppg] BIGINT          NULL,
    [p_erpgroupbuyer]           NVARCHAR (255)  NULL,
    [p_ltfonlyproduct]          TINYINT         NULL,
    [p_catalog]                 BIGINT          NULL,
    [p_supplieralternativeaid]  NVARCHAR (255)  NULL,
    [p_productorderlimit]       BIGINT          NULL,
    [p_sequenceid]              BIGINT          NULL,
    [p_ltbucksamount]           DECIMAL (26, 6) NULL,
    [p_ltbucksflag]             TINYINT         NULL,
    [p_canadianproduct]         TINYINT         NULL,
    [p_externalredeemflag]      TINYINT         NULL,
    [p_mmsproductid]            INT             NULL,
    [p_emailtemplateid]         NVARCHAR (255)  NULL,
    [p_cardtype]                BIGINT          NULL,
    [p_personaldetails]         BIGINT          NULL,
    [p_trainingsession]         BIGINT          NULL,
    [p_displaynumber]           INT             NULL,
    [p_regionid]                NVARCHAR (255)  NULL,
    [p_revcategoryid]           NVARCHAR (255)  NULL,
    [p_costcenterid]            NVARCHAR (255)  NULL,
    [p_itemdescription]         NVARCHAR (255)  NULL,
    [p_offeringid]              NVARCHAR (255)  NULL,
    [p_linecompany]             NVARCHAR (255)  NULL,
    [p_spendcategoryid]         NVARCHAR (255)  NULL,
    [p_malocalflag]             TINYINT         NULL,
    [p_article]                 BIGINT          NULL,
    [p_agreement]               BIGINT          NULL,
    [p_gender]                  BIGINT          NULL,
    [p_fulfillmentproductid]    NVARCHAR (255)  NULL,
    [p_typedescriptor]          NVARCHAR (255)  NULL,
    [p_barcode]                 TINYINT         NULL,
    [p_producttag]              BIGINT          NULL,
    [p_searchable]              TINYINT         NULL,
    [p_productmessages]         VARCHAR (8000)  NULL,
    [p_occasions]               VARCHAR (8000)  NULL,
    [p_isgiftable]              TINYINT         NULL,
    [p_mmsrecurrent]            TINYINT         NULL,
    [p_allowmemberselection]    TINYINT         NULL,
    [dv_batch_id]               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

