CREATE TABLE [dbo].[stage_crmcloudsync_ltfoutreachmembersummary] (
    [stage_crmcloudsync_ltfoutreachmembersummary_id] BIGINT         NOT NULL,
    [createdby]                                      VARCHAR (36)   NULL,
    [createdbyname]                                  NVARCHAR (200) NULL,
    [createdbyyominame]                              NVARCHAR (200) NULL,
    [createdon]                                      DATETIME       NULL,
    [createdonbehalfby]                              VARCHAR (36)   NULL,
    [createdonbehalfbyname]                          NVARCHAR (200) NULL,
    [createdonbehalfbyyominame]                      NVARCHAR (200) NULL,
    [importsequencenumber]                           INT            NULL,
    [ltf_activationdate]                             DATETIME       NULL,
    [ltf_claimedby]                                  VARCHAR (36)   NULL,
    [ltf_claimedbyname]                              NVARCHAR (200) NULL,
    [ltf_claimedbyyominame]                          DATETIME       NULL,
    [ltf_claimexpiration]                            DATETIME       NULL,
    [ltf_clubid]                                     VARCHAR (36)   NULL,
    [ltf_clubidname]                                 NVARCHAR (100) NULL,
    [ltf_contact]                                    VARCHAR (36)   NULL,
    [ltf_contactname]                                NVARCHAR (160) NULL,
    [ltf_contactyominame]                            NVARCHAR (160) NULL,
    [ltf_daysincejoin]                               INT            NULL,
    [ltf_description]                                NVARCHAR (250) NULL,
    [ltf_enrolledby]                                 VARCHAR (36)   NULL,
    [ltf_enrolledbyname]                             NVARCHAR (200) NULL,
    [ltf_enrolledbyyominame]                         NVARCHAR (200) NULL,
    [ltf_initialcontactbycycle]                      VARCHAR (36)   NULL,
    [ltf_initialcontactbycyclename]                  NVARCHAR (200) NULL,
    [ltf_initialcontactbycycleyominame]              NVARCHAR (200) NULL,
    [ltf_initialcontactdatecycle]                    DATETIME       NULL,
    [ltf_initialcontacttypecycle]                    INT            NULL,
    [ltf_initialcontacttypecyclename]                NVARCHAR (255) NULL,
    [ltf_interceptattemptscycle]                     INT            NULL,
    [ltf_interceptcontactscycle]                     INT            NULL,
    [ltf_joindate]                                   DATETIME       NULL,
    [ltf_juniorcount]                                INT            NULL,
    [ltf_lastattemptby]                              VARCHAR (36)   NULL,
    [ltf_lastattemptbyname]                          NVARCHAR (200) NULL,
    [ltf_lastattemptbyyominame]                      NVARCHAR (200) NULL,
    [ltf_lastattemptdate]                            DATETIME       NULL,
    [ltf_lastattempttype]                            INT            NULL,
    [ltf_lastattempttypename]                        NVARCHAR (255) NULL,
    [ltf_lastcontactby]                              VARCHAR (36)   NULL,
    [ltf_lastcontactbyname]                          NVARCHAR (200) NULL,
    [ltf_lastcontactbyyominame]                      NVARCHAR (200) NULL,
    [ltf_lastcontactdate]                            DATETIME       NULL,
    [ltf_lastcontacttype]                            INT            NULL,
    [ltf_lastcontacttypename]                        NVARCHAR (255) NULL,
    [ltf_ltfemployee]                                INT            NULL,
    [ltf_ltfemployeename]                            NVARCHAR (255) NULL,
    [ltf_lthealth]                                   INT            NULL,
    [ltf_lthealthname]                               NVARCHAR (255) NULL,
    [ltf_meetingattemptscycle]                       INT            NULL,
    [ltf_meetingcontactscycle]                       INT            NULL,
    [ltf_membernumber]                               NVARCHAR (100) NULL,
    [ltf_membershipproduct]                          NVARCHAR (250) NULL,
    [ltf_nextanniversary]                            DATETIME       NULL,
    [ltf_outreach_member_summaryid]                  VARCHAR (36)   NULL,
    [ltf_outreachrank]                               INT            NULL,
    [ltf_phoneattemptscycle]                         INT            NULL,
    [ltf_phonecontactscycle]                         INT            NULL,
    [ltf_product]                                    VARCHAR (36)   NULL,
    [ltf_productname]                                NVARCHAR (100) NULL,
    [ltf_programcyclereference]                      VARCHAR (36)   NULL,
    [ltf_programcyclereferencename]                  NVARCHAR (100) NULL,
    [ltf_riskscore]                                  INT            NULL,
    [ltf_role]                                       INT            NULL,
    [ltf_rolename]                                   NVARCHAR (255) NULL,
    [ltf_segment]                                    INT            NULL,
    [ltf_segmentname]                                NVARCHAR (255) NULL,
    [ltf_starvalue]                                  INT            NULL,
    [ltf_subscribercreateddate]                      DATETIME       NULL,
    [ltf_subscriptioncreateddate]                    DATETIME       NULL,
    [ltf_subscriptionid]                             VARCHAR (36)   NULL,
    [ltf_subscriptionidname]                         NVARCHAR (100) NULL,
    [ltf_subsegment_1]                               INT            NULL,
    [ltf_subsegment_10]                              INT            NULL,
    [ltf_subsegment_10name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_11]                              INT            NULL,
    [ltf_subsegment_11name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_12]                              INT            NULL,
    [ltf_subsegment_12name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_13]                              INT            NULL,
    [ltf_subsegment_13name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_14]                              INT            NULL,
    [ltf_subsegment_14name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_15]                              INT            NULL,
    [ltf_subsegment_15name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_16]                              INT            NULL,
    [ltf_subsegment_16name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_17]                              INT            NULL,
    [ltf_subsegment_17name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_18]                              INT            NULL,
    [ltf_subsegment_18name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_19]                              INT            NULL,
    [ltf_subsegment_19name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_1name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_2]                               INT            NULL,
    [ltf_subsegment_20]                              INT            NULL,
    [ltf_subsegment_20name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_21]                              INT            NULL,
    [ltf_subsegment_21name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_22]                              INT            NULL,
    [ltf_subsegment_22name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_23]                              INT            NULL,
    [ltf_subsegment_23name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_24]                              INT            NULL,
    [ltf_subsegment_24name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_25]                              INT            NULL,
    [ltf_subsegment_25name]                          NVARCHAR (255) NULL,
    [ltf_subsegment_2name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_3]                               INT            NULL,
    [ltf_subsegment_3name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_4]                               INT            NULL,
    [ltf_subsegment_4name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_5]                               INT            NULL,
    [ltf_subsegment_5name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_6]                               INT            NULL,
    [ltf_subsegment_6name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_7]                               INT            NULL,
    [ltf_subsegment_7name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_8]                               INT            NULL,
    [ltf_subsegment_8name]                           NVARCHAR (255) NULL,
    [ltf_subsegment_9]                               INT            NULL,
    [ltf_subsegment_9name]                           NVARCHAR (255) NULL,
    [ltf_talkingpoints]                              VARCHAR (8000) NULL,
    [ltf_targeted]                                   BIT            NULL,
    [ltf_targetedname]                               NVARCHAR (255) NULL,
    [ltf_totalattemptscycle]                         INT            NULL,
    [ltf_totalcontactscycle]                         INT            NULL,
    [ltf_yearsofmembership]                          INT            NULL,
    [modifiedby]                                     VARCHAR (36)   NULL,
    [modifiedbyname]                                 NVARCHAR (200) NULL,
    [modifiedbyyominame]                             NVARCHAR (200) NULL,
    [modifiedon]                                     DATETIME       NULL,
    [modifiedonbehalfby]                             VARCHAR (36)   NULL,
    [modifiedonbehalfbyname]                         NVARCHAR (200) NULL,
    [modifiedonbehalfbyyominame]                     NVARCHAR (200) NULL,
    [overriddencreatedon]                            DATETIME       NULL,
    [ownerid]                                        VARCHAR (36)   NULL,
    [owneridname]                                    NVARCHAR (200) NULL,
    [owneridtype]                                    NVARCHAR (64)  NULL,
    [owneridyominame]                                NVARCHAR (200) NULL,
    [owningbusinessunit]                             VARCHAR (36)   NULL,
    [owningteam]                                     VARCHAR (36)   NULL,
    [owninguser]                                     VARCHAR (36)   NULL,
    [statecode]                                      INT            NULL,
    [statecodename]                                  NVARCHAR (255) NULL,
    [statuscode]                                     INT            NULL,
    [statuscodename]                                 NVARCHAR (255) NULL,
    [timezoneruleversionnumber]                      INT            NULL,
    [utcconversiontimezonecode]                      INT            NULL,
    [versionnumber]                                  BIGINT         NULL,
    [InsertedDateTime]                               DATETIME       NULL,
    [InsertUser]                                     VARCHAR (100)  NULL,
    [UpdatedDateTime]                                DATETIME       NULL,
    [UpdateUser]                                     VARCHAR (50)   NULL,
    [dv_batch_id]                                    BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

