CREATE TABLE [dbo].[stage_ltfmart_EmployeeGoals] (
    [stage_ltfmart_EmployeeGoals_id] BIGINT          NOT NULL,
    [ID]                             INT             NULL,
    [EmployeeID]                     INT             NULL,
    [ClubID]                         INT             NULL,
    [ValCompensationPlanID]          INT             NULL,
    [GoalDate]                       DATETIME        NULL,
    [NewHireTypeID]                  INT             NULL,
    [MALevelID]                      INT             NULL,
    [SDHTypeID]                      INT             NULL,
    [AppointmentShowGoal]            INT             NULL,
    [MembershipGoal]                 INT             NULL,
    [VIPReferralGoal]                INT             NULL,
    [HoursWorked]                    INT             NULL,
    [UnitQuota]                      INT             NULL,
    [UnitQuotaOverride]              INT             NULL,
    [NDTQuota]                       DECIMAL (26, 6) NULL,
    [HasGoal]                        BIT             NULL,
    [IsASDH]                         BIT             NULL,
    [IsDeptHead]                     BIT             NULL,
    [IsNewHire]                      BIT             NULL,
    [IsPartTime]                     BIT             NULL,
    [OverrideUnitQuota]              BIT             NULL,
    [SalesCompException]             BIT             NULL,
    [OverrideUserRole]               BIT             NULL,
    [InactiveDate]                   DATETIME        NULL,
    [CreateEmpID]                    INT             NULL,
    [CreateDateTime]                 DATETIME        NULL,
    [ModifyEmpID]                    INT             NULL,
    [ModifyDateTime]                 DATETIME        NULL,
    [RowVersion]                     BINARY (8)      NULL,
    [dv_batch_id]                    BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

