CREATE TABLE [dbo].[stage_hybris_SEVEN_DAY_ORDERS] (
    [stage_hybris_SEVEN_DAY_ORDERS_id] BIGINT          NOT NULL,
    [OrderCode]                        NVARCHAR (255)  NULL,
    [OrderEntryEntryNumber]            INT             NULL,
    [OrderEntryTrackingNumber]         NVARCHAR (255)  NULL,
    [OrderEntrySettlementDatetime]     DATETIME        NULL,
    [OrderDatetime]                    DATETIME        NULL,
    [OrderEntryShippingCost]           DECIMAL (8, 2)  NULL,
    [OrderEntryTotalTax]               DECIMAL (8, 2)  NULL,
    [OrderLtfPartyId]                  NVARCHAR (255)  NULL,
    [OrderCommisionEmployeeId]         NVARCHAR (255)  NULL,
    [OrderAutoshipFlag]                TINYINT         NULL,
    [OrderEntryProductCode]            NVARCHAR (258)  NULL,
    [OrderEntryProductName]            NVARCHAR (255)  NULL,
    [OrderEntryProductDescription]     NVARCHAR (4000) NULL,
    [OrderEntryQuantity]               INT             NULL,
    [OrderEntryBasePrice]              DECIMAL (8, 2)  NULL,
    [OrderEntryTotalPrice]             DECIMAL (8, 2)  NULL,
    [OrderEntryTotalDiscounts]         DECIMAL (8, 2)  NULL,
    [OrderEntryRefundStatus]           NVARCHAR (255)  NULL,
    [OrderEntryRefundDatetime]         DATETIME        NULL,
    [OrderEntryRefundAmount]           DECIMAL (8, 2)  NULL,
    [RefundReason]                     NVARCHAR (255)  NULL,
    [CustomerName]                     NVARCHAR (255)  NULL,
    [CustomerEmail]                    NVARCHAR (255)  NULL,
    [CustomerGroup]                    NVARCHAR (255)  NULL,
    [MethodOfPay]                      NVARCHAR (255)  NULL,
    [FulfillmentPartner]               NVARCHAR (255)  NULL,
    [AffiliateID]                      NVARCHAR (255)  NULL,
    [mmsTransactionID]                 NVARCHAR (255)  NULL,
    [mmsPackageID]                     INT             NULL,
    [SelectedClub]                     NVARCHAR (255)  NULL,
    [LTBUCKSearned]                    DECIMAL (26, 6) NULL,
    [Capture_LTBUCKS]                  DECIMAL (26, 6) NULL,
    [Capture_amex]                     DECIMAL (26, 6) NULL,
    [Capture_discover]                 DECIMAL (26, 6) NULL,
    [Capture_master]                   DECIMAL (26, 6) NULL,
    [Capture_visa]                     DECIMAL (26, 6) NULL,
    [Capture_PAYPAL]                   DECIMAL (26, 6) NULL,
    [Refund_LTBUCKS]                   DECIMAL (26, 6) NULL,
    [Refund_amex]                      DECIMAL (26, 6) NULL,
    [Refund_discover]                  DECIMAL (26, 6) NULL,
    [Refund_master]                    DECIMAL (26, 6) NULL,
    [Refund_visa]                      DECIMAL (26, 6) NULL,
    [Refund_PAYPAL]                    DECIMAL (26, 6) NULL,
    [Ordstat]                          NVARCHAR (255)  NULL,
    [OEstat]                           NVARCHAR (255)  NULL,
    [OEsettlementFlag]                 TINYINT         NULL,
    [dv_batch_id]                      BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

