CREATE TABLE [dbo].[stage_hash_mms_MembershipModificationRequest] (
    [stage_hash_mms_MembershipModificationRequest_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                         CHAR (32)       NOT NULL,
    [MembershipModificationRequestID]                 INT             NULL,
    [MembershipID]                                    INT             NULL,
    [MemberID]                                        INT             NULL,
    [RequestDateTime]                                 DATETIME        NULL,
    [UTCRequestDateTime]                              DATETIME        NULL,
    [RequestDateTimeZone]                             VARCHAR (4)     NULL,
    [EffectiveDate]                                   DATETIME        NULL,
    [ValMembershipModificationRequestTypeID]          TINYINT         NULL,
    [ValFlexReasonID]                                 BIGINT          NULL,
    [MembershipTypeID]                                INT             NULL,
    [InsertedDateTime]                                DATETIME        NULL,
    [UpdatedDateTime]                                 DATETIME        NULL,
    [ValMembershipModificationRequestStatusID]        BIGINT          NULL,
    [StatusChangedDateTime]                           DATETIME        NULL,
    [EmployeeID]                                      INT             NULL,
    [LastEFTMonth]                                    VARCHAR (9)     NULL,
    [FutureMembershipUpgradeFlag]                     BIT             NULL,
    [ValMembershipUpgradeDateRangeID]                 BIGINT          NULL,
    [ClubID]                                          INT             NULL,
    [CommisionedEmployeeID]                           INT             NULL,
    [FirstMonthsDues]                                 DECIMAL (26, 6) NULL,
    [TotalMonthlyAmount]                              DECIMAL (26, 6) NULL,
    [MemberAgreementStagingID]                        INT             NULL,
    [MembershipUpgradeMonthYear]                      DATETIME        NULL,
    [AgreementPrice]                                  DECIMAL (26, 6) NULL,
    [WaiveServiceFeeFlag]                             BIT             NULL,
    [FullAccessDateExtensionFlag]                     BIT             NULL,
    [NewMembers]                                      VARCHAR (200)   NULL,
    [AddOnFee]                                        DECIMAL (26, 6) NULL,
    [ServiceFee]                                      DECIMAL (26, 6) NULL,
    [DiamondFee]                                      DECIMAL (26, 6) NULL,
    [ProratedDues]                                    DECIMAL (26, 6) NULL,
    [DeactivatedMembers]                              VARCHAR (200)   NULL,
    [JuniorsAssessed]                                 INT             NULL,
    [PreviousMembershipTypeID]                        INT             NULL,
    [MemberFreezeFlag]                                BIT             NULL,
    [NewPrimaryID]                                    INT             NULL,
    [UndiscountedPrice]                               DECIMAL (26, 6) NULL,
    [ValMembershipModificationRequestSourceID]        TINYINT         NULL,
    [dv_load_date_time]                               DATETIME        NOT NULL,
    [dv_batch_id]                                     BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

