CREATE TABLE [dbo].[stage_crmcloudsync_Task] (
    [stage_crmcloudsync_Task_id]        BIGINT          NOT NULL,
    [activityid]                        VARCHAR (36)    NULL,
    [activitytypecode]                  NVARCHAR (64)   NULL,
    [activitytypecodename]              NVARCHAR (255)  NULL,
    [actualdurationminutes]             INT             NULL,
    [actualend]                         DATETIME        NULL,
    [actualstart]                       DATETIME        NULL,
    [category]                          NVARCHAR (250)  NULL,
    [createdby]                         VARCHAR (36)    NULL,
    [createdbyname]                     NVARCHAR (200)  NULL,
    [createdbyyominame]                 NVARCHAR (200)  NULL,
    [createdon]                         DATETIME        NULL,
    [createdonbehalfby]                 VARCHAR (36)    NULL,
    [createdonbehalfbyname]             NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]         NVARCHAR (200)  NULL,
    [description]                       NVARCHAR (4000) NULL,
    [exchangerate]                      DECIMAL (28)    NULL,
    [importsequencenumber]              INT             NULL,
    [isbilled]                          BIT             NULL,
    [isbilledname]                      NVARCHAR (255)  NULL,
    [isregularactivity]                 BIT             NULL,
    [isregularactivityname]             NVARCHAR (255)  NULL,
    [isworkflowcreated]                 BIT             NULL,
    [isworkflowcreatedname]             NVARCHAR (255)  NULL,
    [ltf_myhealthscorescheduleddate]    DATETIME        NULL,
    [ltf_tasktype]                      INT             NULL,
    [ltf_tasktypename]                  NVARCHAR (255)  NULL,
    [ltf_trainingservicesscheduleddate] DATETIME        NULL,
    [ltf_udwid]                         NVARCHAR (255)  NULL,
    [modifiedby]                        VARCHAR (36)    NULL,
    [modifiedbyname]                    NVARCHAR (200)  NULL,
    [modifiedbyyominame]                NVARCHAR (200)  NULL,
    [modifiedon]                        DATETIME        NULL,
    [modifiedonbehalfby]                VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]            NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]        NVARCHAR (200)  NULL,
    [overriddencreatedon]               DATETIME        NULL,
    [ownerid]                           VARCHAR (36)    NULL,
    [owneridname]                       NVARCHAR (200)  NULL,
    [owneridtype]                       NVARCHAR (64)   NULL,
    [owneridyominame]                   NVARCHAR (200)  NULL,
    [owningbusinessunit]                VARCHAR (36)    NULL,
    [owningteam]                        VARCHAR (36)    NULL,
    [owninguser]                        VARCHAR (36)    NULL,
    [percentcomplete]                   INT             NULL,
    [prioritycode]                      INT             NULL,
    [prioritycodename]                  NVARCHAR (255)  NULL,
    [processid]                         VARCHAR (36)    NULL,
    [regardingobjectid]                 VARCHAR (36)    NULL,
    [regardingobjectidname]             VARCHAR (8000)  NULL,
    [regardingobjectidyominame]         VARCHAR (8000)  NULL,
    [regardingobjecttypecode]           NVARCHAR (64)   NULL,
    [scheduleddurationminutes]          INT             NULL,
    [scheduledend]                      DATETIME        NULL,
    [scheduledstart]                    DATETIME        NULL,
    [serviceid]                         VARCHAR (36)    NULL,
    [stageid]                           VARCHAR (36)    NULL,
    [statecode]                         INT             NULL,
    [statecodename]                     NVARCHAR (255)  NULL,
    [statuscode]                        INT             NULL,
    [statuscodename]                    NVARCHAR (255)  NULL,
    [subcategory]                       NVARCHAR (250)  NULL,
    [subject]                           NVARCHAR (200)  NULL,
    [timezoneruleversionnumber]         INT             NULL,
    [transactioncurrencyid]             VARCHAR (36)    NULL,
    [transactioncurrencyidname]         NVARCHAR (100)  NULL,
    [utcconversiontimezonecode]         INT             NULL,
    [versionnumber]                     BIGINT          NULL,
    [InsertedDateTime]                  DATETIME        NULL,
    [InsertUser]                        VARCHAR (100)   NULL,
    [ltf_healthscorescheduledname]      NVARCHAR (200)  NULL,
    [ltf_trainingservicesscheduledname] NVARCHAR (200)  NULL,
    [ltf_whometontour]                  NVARCHAR (300)  NULL,
    [UpdatedDateTime]                   DATETIME        NULL,
    [UpdateUser]                        VARCHAR (50)    NULL,
    [traversedpath]                     NVARCHAR (1250) NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

