CREATE TABLE [dbo].[stage_hash_hybris_orderentries] (
    [stage_hash_hybris_orderentries_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)       NOT NULL,
    [hjmpTS]                            BIGINT          NULL,
    [createdTS]                         DATETIME        NULL,
    [modifiedTS]                        DATETIME        NULL,
    [TypePkString]                      BIGINT          NULL,
    [OwnerPkString]                     BIGINT          NULL,
    [PK]                                BIGINT          NULL,
    [p_baseprice]                       DECIMAL (30, 8) NULL,
    [p_calculated]                      TINYINT         NULL,
    [p_discountvaluesinternal]          VARCHAR (8000)  NULL,
    [p_entrynumber]                     INT             NULL,
    [p_info]                            VARCHAR (8000)  NULL,
    [p_product]                         BIGINT          NULL,
    [p_quantity]                        DECIMAL (30, 8) NULL,
    [p_taxvaluesinternal]               NVARCHAR (255)  NULL,
    [p_totalprice]                      DECIMAL (30, 8) NULL,
    [p_unit]                            BIGINT          NULL,
    [p_giveaway]                        TINYINT         NULL,
    [p_rejected]                        TINYINT         NULL,
    [p_order]                           BIGINT          NULL,
    [p_europe1pricefactory_ppg]         BIGINT          NULL,
    [p_europe1pricefactory_ptg]         BIGINT          NULL,
    [p_europe1pricefactory_pdg]         BIGINT          NULL,
    [p_chosenvendor]                    BIGINT          NULL,
    [p_deliveryaddress]                 BIGINT          NULL,
    [p_deliverymode]                    BIGINT          NULL,
    [p_nameddeliverydate]               DATETIME        NULL,
    [p_quantitystatus]                  BIGINT          NULL,
    [p_deliverypointofservice]          BIGINT          NULL,
    [p_xmlproduct]                      VARCHAR (8000)  NULL,
    [p_originalsubscriptionid]          NVARCHAR (255)  NULL,
    [p_originalorderentry]              BIGINT          NULL,
    [p_masterentry]                     BIGINT          NULL,
    [p_bundleno]                        INT             NULL,
    [p_bundletemplate]                  BIGINT          NULL,
    [aCLTS]                             BIGINT          NULL,
    [propTS]                            BIGINT          NULL,
    [dv_load_date_time]                 DATETIME        NOT NULL,
    [dv_inserted_date_time]             DATETIME        NOT NULL,
    [dv_insert_user]                    VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]              DATETIME        NULL,
    [dv_update_user]                    VARCHAR (50)    NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

