CREATE TABLE [dbo].[stage_hash_hybris_promotionaction] (
    [stage_hash_hybris_promotionaction_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                              CHAR (32)       NOT NULL,
    [hjmpTS]                               BIGINT          NULL,
    [createdTS]                            DATETIME        NULL,
    [modifiedTS]                           DATETIME        NULL,
    [TypePkString]                         BIGINT          NULL,
    [OwnerPkString]                        BIGINT          NULL,
    [PK]                                   BIGINT          NULL,
    [p_markedapplied]                      TINYINT         NULL,
    [p_guid]                               NVARCHAR (255)  NULL,
    [p_promotionresult]                    BIGINT          NULL,
    [aCLTS]                                BIGINT          NULL,
    [propTS]                               BIGINT          NULL,
    [p_amount]                             DECIMAL (26, 6) NULL,
    [p_orderentryproduct]                  BIGINT          NULL,
    [p_orderentryquantity]                 BIGINT          NULL,
    [p_orderentrynumber]                   INT             NULL,
    [p_freeproduct]                        BIGINT          NULL,
    [p_deliverymode]                       BIGINT          NULL,
    [p_rule]                               BIGINT          NULL,
    [p_strategyid]                         NVARCHAR (255)  NULL,
    [p_amoun0]                             DECIMAL (30, 8) NULL,
    [p_product]                            BIGINT          NULL,
    [p_quantity]                           BIGINT          NULL,
    [p_deliverycost]                       DECIMAL (30, 8) NULL,
    [p_replaceddeliverymode]               BIGINT          NULL,
    [p_replaceddeliverycost]               DECIMAL (30, 8) NULL,
    [p_parameters]                         NVARCHAR (4000) NULL,
    [p_couponid]                           NVARCHAR (255)  NULL,
    [p_couponcode]                         NVARCHAR (255)  NULL,
    [dv_load_date_time]                    DATETIME        NOT NULL,
    [dv_inserted_date_time]                DATETIME        NOT NULL,
    [dv_insert_user]                       VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]                 DATETIME        NULL,
    [dv_update_user]                       VARCHAR (50)    NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

