CREATE TABLE [dbo].[stage_exerp_sale_log] (
    [stage_exerp_sale_log_id]  BIGINT          NOT NULL,
    [id]                       VARCHAR (4000)  NULL,
    [center_id]                INT             NULL,
    [sale_type]                VARCHAR (4000)  NULL,
    [person_id]                VARCHAR (4000)  NULL,
    [company_id]               VARCHAR (4000)  NULL,
    [is_company]               VARCHAR (10)    NULL,
    [sale_person_id]           VARCHAR (4000)  NULL,
    [entry_datetime]           DATETIME        NULL,
    [book_datetime]            DATETIME        NULL,
    [product_center]           INT             NULL,
    [product_id]               VARCHAR (4000)  NULL,
    [product_type]             VARCHAR (4000)  NULL,
    [product_normal_price]     DECIMAL (26, 6) NULL,
    [quantity]                 INT             NULL,
    [net_amount]               DECIMAL (26, 6) NULL,
    [vat_amount]               DECIMAL (26, 6) NULL,
    [total_amount]             DECIMAL (26, 6) NULL,
    [sponsor_sale_log_id]      VARCHAR (4000)  NULL,
    [gl_debit_account]         VARCHAR (4000)  NULL,
    [gl_credit_account]        VARCHAR (4000)  NULL,
    [sale_commission]          INT             NULL,
    [sale_units]               INT             NULL,
    [period_commission]        INT             NULL,
    [source_type]              VARCHAR (4000)  NULL,
    [credit_sale_log_id]       VARCHAR (4000)  NULL,
    [sale_id]                  VARCHAR (4000)  NULL,
    [cash_register_center_id]  INT             NULL,
    [tts]                      DATETIME        NULL,
    [ets]                      BIGINT          NULL,
    [flat_rate_commission]     DECIMAL (26, 6) NULL,
    [external_id]              VARCHAR (4000)  NULL,
    [dummy_modified_date_time] DATETIME        NULL,
    [dv_batch_id]              BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

