CREATE TABLE [dbo].[stage_hash_magento_cataloginventory_stock_item] (
    [stage_hash_magento_cataloginventory_stock_item_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                           CHAR (32)       NOT NULL,
    [item_id]                                           INT             NULL,
    [product_id]                                        INT             NULL,
    [stock_id]                                          INT             NULL,
    [qty]                                               DECIMAL (12, 4) NULL,
    [min_qty]                                           DECIMAL (12, 4) NULL,
    [use_config_min_qty]                                INT             NULL,
    [is_qty_decimal]                                    INT             NULL,
    [backorders]                                        INT             NULL,
    [use_config_backorders]                             INT             NULL,
    [min_sale_qty]                                      DECIMAL (12, 4) NULL,
    [use_config_min_sale_qty]                           INT             NULL,
    [max_sale_qty]                                      DECIMAL (12, 4) NULL,
    [use_config_max_sale_qty]                           INT             NULL,
    [is_in_stock]                                       INT             NULL,
    [low_stock_date]                                    DATETIME        NULL,
    [notify_stock_qty]                                  DECIMAL (12, 4) NULL,
    [use_config_notify_stock_qty]                       INT             NULL,
    [manage_stock]                                      INT             NULL,
    [use_config_manage_stock]                           INT             NULL,
    [stock_status_changed_auto]                         INT             NULL,
    [use_config_qty_increments]                         INT             NULL,
    [qty_increments]                                    DECIMAL (12, 4) NULL,
    [use_config_enable_qty_inc]                         INT             NULL,
    [enable_qty_increments]                             INT             NULL,
    [is_decimal_divided]                                INT             NULL,
    [website_id]                                        INT             NULL,
    [deferred_stock_update]                             INT             NULL,
    [use_config_deferred_stock_update]                  INT             NULL,
    [dummy_modified_date_time]                          DATETIME        NULL,
    [dv_load_date_time]                                 DATETIME        NOT NULL,
    [dv_batch_id]                                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

