CREATE TABLE [dbo].[stage_crmcloudsync_campaign] (
    [stage_crmcloudsync_campaign_id]       BIGINT          NOT NULL,
    [actualend]                            DATETIME        NULL,
    [actualstart]                          DATETIME        NULL,
    [budgetedcost]                         INT             NULL,
    [budgetedcost_base]                    INT             NULL,
    [campaignid]                           VARCHAR (36)    NULL,
    [codename]                             NVARCHAR (32)   NULL,
    [createdby]                            VARCHAR (36)    NULL,
    [createdbyname]                        NVARCHAR (200)  NULL,
    [createdbyyominame]                    NVARCHAR (200)  NULL,
    [createdon]                            DATETIME        NULL,
    [createdonbehalfby]                    VARCHAR (36)    NULL,
    [createdonbehalfbyname]                NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]            NVARCHAR (200)  NULL,
    [description]                          VARCHAR (8000)  NULL,
    [entityimage]                          VARCHAR (50)    NULL,
    [entityimage_timestamp]                BIGINT          NULL,
    [entityimage_url]                      NVARCHAR (200)  NULL,
    [entityimageid]                        VARCHAR (36)    NULL,
    [exchangerate]                         DECIMAL (28)    NULL,
    [expectedresponse]                     INT             NULL,
    [expectedrevenue]                      INT             NULL,
    [expectedrevenue_base]                 INT             NULL,
    [importsequencenumber]                 INT             NULL,
    [istemplate]                           BIT             NULL,
    [istemplatename]                       NVARCHAR (255)  NULL,
    [ltf_clubrestrictiontype]              INT             NULL,
    [ltf_clubrestrictiontypename]          NVARCHAR (255)  NULL,
    [ltf_connectwitham]                    BIT             NULL,
    [ltf_connectwithamname]                NVARCHAR (255)  NULL,
    [ltf_displayonform]                    BIT             NULL,
    [ltf_displayonformname]                NVARCHAR (255)  NULL,
    [ltf_expirationdays]                   INT             NULL,
    [ltf_expirationtype]                   INT             NULL,
    [ltf_expirationtypename]               NVARCHAR (255)  NULL,
    [ltf_passdays]                         INT             NULL,
    [ltf_targetedrecordtype]               INT             NULL,
    [ltf_targetedrecordtypename]           NVARCHAR (255)  NULL,
    [ltf_userdefineddates]                 BIT             NULL,
    [ltf_userdefineddatesname]             NVARCHAR (255)  NULL,
    [message]                              NVARCHAR (256)  NULL,
    [modifiedby]                           VARCHAR (36)    NULL,
    [modifiedbyname]                       NVARCHAR (200)  NULL,
    [modifiedbyyominame]                   NVARCHAR (200)  NULL,
    [modifiedon]                           DATETIME        NULL,
    [modifiedonbehalfby]                   VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]               NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]           NVARCHAR (200)  NULL,
    [name]                                 NVARCHAR (128)  NULL,
    [objective]                            VARCHAR (8000)  NULL,
    [othercost]                            INT             NULL,
    [othercost_base]                       INT             NULL,
    [overriddencreatedon]                  DATETIME        NULL,
    [ownerid]                              VARCHAR (36)    NULL,
    [owneridname]                          NVARCHAR (200)  NULL,
    [owneridtype]                          NVARCHAR (64)   NULL,
    [owneridyominame]                      NVARCHAR (200)  NULL,
    [owningbusinessunit]                   VARCHAR (36)    NULL,
    [owningteam]                           VARCHAR (36)    NULL,
    [owninguser]                           VARCHAR (36)    NULL,
    [pricelistid]                          VARCHAR (36)    NULL,
    [pricelistname]                        NVARCHAR (100)  NULL,
    [processid]                            VARCHAR (36)    NULL,
    [promotioncodename]                    NVARCHAR (128)  NULL,
    [proposedend]                          DATETIME        NULL,
    [proposedstart]                        DATETIME        NULL,
    [stageid]                              VARCHAR (36)    NULL,
    [statecode]                            INT             NULL,
    [statecodename]                        NVARCHAR (255)  NULL,
    [statuscode]                           INT             NULL,
    [statuscodename]                       NVARCHAR (255)  NULL,
    [timezoneruleversionnumber]            INT             NULL,
    [totalactualcost]                      INT             NULL,
    [totalactualcost_base]                 INT             NULL,
    [totalcampaignactivityactualcost]      INT             NULL,
    [totalcampaignactivityactualcost_base] INT             NULL,
    [transactioncurrencyid]                VARCHAR (36)    NULL,
    [transactioncurrencyidname]            NVARCHAR (100)  NULL,
    [traversedpath]                        NVARCHAR (1250) NULL,
    [typecode]                             INT             NULL,
    [typecodename]                         NVARCHAR (255)  NULL,
    [utcconversiontimezonecode]            INT             NULL,
    [versionnumber]                        BIGINT          NULL,
    [InsertedDateTime]                     DATETIME        NULL,
    [InsertUser]                           VARCHAR (50)    NULL,
    [UpdatedDateTime]                      DATETIME        NULL,
    [UpdateUser]                           VARCHAR (50)    NULL,
    [ltf_issuancemethod]                   INT             NULL,
    [ltf_jobid]                            NVARCHAR (100)  NULL,
    [ltf_qrcodestring]                     NVARCHAR (2000) NULL,
    [ltf_qrcodeurl]                        NVARCHAR (2000) NULL,
    [ltf_targetedprospects]                INT             NULL,
    [ltf_targetedissuedate]                DATETIME        NULL,
    [ltf_sendid]                           NVARCHAR (50)   NULL,
    [ltf_memberreferral]                   BIT             NULL,
    [ltf_guestpasstype]                    INT             NULL,
    [ltf_rewardtype]                       INT             NULL,
    [ltf_rewardltbucks]                    INT             NULL,
    [ltf_rewardwaitdays]                   INT             NULL,
    [ltf_rewardclub]                       VARCHAR (36)    NULL,
    [ltf_restrictedbypolicy]               BIT             NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

