CREATE TABLE [dbo].[stage_magento_catalog_category_flat_store_1] (
    [stage_magento_catalog_category_flat_store_1_id] BIGINT          NOT NULL,
    [entity_id]                                      INT             NULL,
    [row_id]                                         INT             NULL,
    [created_in]                                     BIGINT          NULL,
    [updated_in]                                     BIGINT          NULL,
    [attribute_set_id]                               INT             NULL,
    [parent_id]                                      INT             NULL,
    [created_at]                                     DATETIME        NULL,
    [updated_at]                                     DATETIME        NULL,
    [path]                                           VARCHAR (255)   NULL,
    [position]                                       INT             NULL,
    [level]                                          INT             NULL,
    [children_count]                                 INT             NULL,
    [store_id]                                       INT             NULL,
    [all_children]                                   VARCHAR (255)   NULL,
    [automatic_sorting]                              VARCHAR (255)   NULL,
    [available_sort_by]                              VARCHAR (255)   NULL,
    [children]                                       VARCHAR (255)   NULL,
    [custom_apply_to_products]                       INT             NULL,
    [custom_design]                                  VARCHAR (255)   NULL,
    [custom_design_from]                             DATETIME        NULL,
    [custom_design_to]                               DATETIME        NULL,
    [custom_layout_update]                           VARCHAR (255)   NULL,
    [custom_use_parent_settings]                     INT             NULL,
    [default_sort_by]                                VARCHAR (255)   NULL,
    [description]                                    VARCHAR (255)   NULL,
    [display_mode]                                   VARCHAR (255)   NULL,
    [featured_category]                              INT             NULL,
    [featured_image]                                 VARCHAR (255)   NULL,
    [filter_price_range]                             DECIMAL (12, 4) NULL,
    [include_in_menu]                                INT             NULL,
    [is_active]                                      INT             NULL,
    [is_anchor]                                      INT             NULL,
    [is_virtual_category]                            INT             NULL,
    [landing_page]                                   INT             NULL,
    [meta_description]                               VARCHAR (255)   NULL,
    [meta_keywords]                                  VARCHAR (255)   NULL,
    [meta_title]                                     VARCHAR (255)   NULL,
    [name]                                           VARCHAR (255)   NULL,
    [page_layout]                                    VARCHAR (255)   NULL,
    [path_in_store]                                  VARCHAR (255)   NULL,
    [short_description]                              VARCHAR (255)   NULL,
    [thumbnail]                                      VARCHAR (255)   NULL,
    [url_key]                                        VARCHAR (255)   NULL,
    [url_path]                                       VARCHAR (255)   NULL,
    [use_name_in_product_search]                     INT             NULL,
    [virtual_category_root]                          INT             NULL,
    [virtual_rule]                                   VARCHAR (255)   NULL,
    [dv_batch_id]                                    BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

