CREATE TABLE [dbo].[stage_hash_fitmetrix_api_instructor] (
    [stage_hash_fitmetrix_api_instructor_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)     NOT NULL,
    [INSTRUCTORID]                           INT           NULL,
    [FACILITYID]                             INT           NULL,
    [FIRSTNAME]                              VARCHAR (255) NULL,
    [LASTNAME]                               VARCHAR (255) NULL,
    [DESCRIPTION]                            VARCHAR (255) NULL,
    [IMAGE]                                  VARCHAR (255) NULL,
    [EMAIL]                                  VARCHAR (255) NULL,
    [STREET1]                                VARCHAR (255) NULL,
    [STREET2]                                VARCHAR (255) NULL,
    [CITY]                                   VARCHAR (255) NULL,
    [STATE]                                  VARCHAR (255) NULL,
    [ZIP]                                    VARCHAR (255) NULL,
    [COUNTRY]                                VARCHAR (255) NULL,
    [BIO]                                    VARCHAR (255) NULL,
    [HOMEPHONE]                              VARCHAR (255) NULL,
    [WORKPHONE]                              VARCHAR (255) NULL,
    [EXTERNALID]                             VARCHAR (255) NULL,
    [GENDER]                                 VARCHAR (255) NULL,
    [QUOTE]                                  VARCHAR (255) NULL,
    [SHOWONLINE]                             VARCHAR (255) NULL,
    [FACILITYLOCATIONID]                     INT           NULL,
    [ACTIVE]                                 VARCHAR (255) NULL,
    [DISPLAYORDER]                           INT           NULL,
    [FACEBOOKURL]                            VARCHAR (255) NULL,
    [TWITTERURL]                             VARCHAR (255) NULL,
    [INSTAGRAMURL]                           VARCHAR (255) NULL,
    [SOUNDCLOUDURL]                          VARCHAR (255) NULL,
    [SPOTIFYURL]                             VARCHAR (255) NULL,
    [DELETED]                                VARCHAR (255) NULL,
    [EXTRAFIELD1]                            VARCHAR (255) NULL,
    [EXTRAFIELD2]                            VARCHAR (255) NULL,
    [EXTRAFIELD3]                            VARCHAR (255) NULL,
    [RECEIVECANCELANDREGISTEREMAIL]          VARCHAR (255) NULL,
    [dummy_modified_date_time]               DATETIME      NULL,
    [dv_load_date_time]                      DATETIME      NOT NULL,
    [dv_inserted_date_time]                  DATETIME      NOT NULL,
    [dv_insert_user]                         VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]                   DATETIME      NULL,
    [dv_update_user]                         VARCHAR (50)  NULL,
    [dv_batch_id]                            BIGINT        NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

