CREATE TABLE [dbo].[stage_hash_magento_sales_order_item] (
    [stage_hash_magento_sales_order_item_id]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)       NOT NULL,
    [item_id]                                 INT             NULL,
    [order_id]                                INT             NULL,
    [parent_item_id]                          INT             NULL,
    [quote_item_id]                           INT             NULL,
    [store_id]                                INT             NULL,
    [created_at]                              DATETIME        NULL,
    [updated_at]                              DATETIME        NULL,
    [product_id]                              INT             NULL,
    [product_type]                            NVARCHAR (255)  NULL,
    [product_options]                         NVARCHAR (255)  NULL,
    [weight]                                  DECIMAL (12, 4) NULL,
    [is_virtual]                              INT             NULL,
    [sku]                                     NVARCHAR (255)  NULL,
    [name]                                    NVARCHAR (255)  NULL,
    [description]                             NVARCHAR (255)  NULL,
    [applied_rule_ids]                        NVARCHAR (255)  NULL,
    [additional_data]                         NVARCHAR (255)  NULL,
    [is_qty_decimal]                          INT             NULL,
    [no_discount]                             INT             NULL,
    [qty_backordered]                         DECIMAL (12, 4) NULL,
    [qty_canceled]                            DECIMAL (12, 4) NULL,
    [qty_invoiced]                            DECIMAL (12, 4) NULL,
    [qty_ordered]                             DECIMAL (12, 4) NULL,
    [qty_refunded]                            DECIMAL (12, 4) NULL,
    [qty_shipped]                             DECIMAL (12, 4) NULL,
    [base_cost]                               DECIMAL (12, 4) NULL,
    [price]                                   DECIMAL (12, 4) NULL,
    [base_price]                              DECIMAL (12, 4) NULL,
    [original_price]                          DECIMAL (12, 4) NULL,
    [base_original_price]                     DECIMAL (12, 4) NULL,
    [tax_percent]                             DECIMAL (12, 4) NULL,
    [tax_amount]                              DECIMAL (12, 4) NULL,
    [base_tax_amount]                         DECIMAL (12, 4) NULL,
    [tax_invoiced]                            DECIMAL (12, 4) NULL,
    [base_tax_invoiced]                       DECIMAL (12, 4) NULL,
    [discount_percent]                        DECIMAL (12, 4) NULL,
    [discount_amount]                         DECIMAL (12, 4) NULL,
    [base_discount_amount]                    DECIMAL (12, 4) NULL,
    [discount_invoiced]                       DECIMAL (12, 4) NULL,
    [base_discount_invoiced]                  DECIMAL (12, 4) NULL,
    [amount_refunded]                         DECIMAL (12, 4) NULL,
    [base_amount_refunded]                    DECIMAL (12, 4) NULL,
    [row_total]                               DECIMAL (12, 4) NULL,
    [base_row_total]                          DECIMAL (12, 4) NULL,
    [row_invoiced]                            DECIMAL (12, 4) NULL,
    [base_row_invoiced]                       DECIMAL (12, 4) NULL,
    [row_weight]                              DECIMAL (12, 4) NULL,
    [base_tax_before_discount]                DECIMAL (12, 4) NULL,
    [tax_before_discount]                     DECIMAL (12, 4) NULL,
    [ext_order_item_id]                       NVARCHAR (255)  NULL,
    [locked_do_invoice]                       INT             NULL,
    [locked_do_ship]                          INT             NULL,
    [price_incl_tax]                          DECIMAL (12, 4) NULL,
    [base_price_incl_tax]                     DECIMAL (12, 4) NULL,
    [row_total_incl_tax]                      DECIMAL (12, 4) NULL,
    [base_row_total_incl_tax]                 DECIMAL (12, 4) NULL,
    [discount_tax_compensation_amount]        DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_amount]   DECIMAL (12, 4) NULL,
    [discount_tax_compensation_invoiced]      DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_invoiced] DECIMAL (12, 4) NULL,
    [discount_tax_compensation_refunded]      DECIMAL (12, 4) NULL,
    [base_discount_tax_compensation_refunded] DECIMAL (12, 4) NULL,
    [tax_canceled]                            DECIMAL (12, 4) NULL,
    [discount_tax_compensation_canceled]      DECIMAL (12, 4) NULL,
    [tax_refunded]                            DECIMAL (12, 4) NULL,
    [base_tax_refunded]                       DECIMAL (12, 4) NULL,
    [discount_refunded]                       DECIMAL (12, 4) NULL,
    [base_discount_refunded]                  DECIMAL (12, 4) NULL,
    [free_shipping]                           INT             NULL,
    [qty_returned]                            DECIMAL (12, 4) NULL,
    [gift_message_id]                         INT             NULL,
    [gift_message_available]                  INT             NULL,
    [weee_tax_applied]                        NVARCHAR (255)  NULL,
    [weee_tax_applied_amount]                 DECIMAL (12, 4) NULL,
    [weee_tax_applied_row_amount]             DECIMAL (12, 4) NULL,
    [weee_tax_disposition]                    DECIMAL (12, 4) NULL,
    [weee_tax_row_disposition]                DECIMAL (12, 4) NULL,
    [base_weee_tax_applied_amount]            DECIMAL (12, 4) NULL,
    [base_weee_tax_applied_row_amnt]          DECIMAL (12, 4) NULL,
    [base_weee_tax_disposition]               DECIMAL (12, 4) NULL,
    [base_weee_tax_row_disposition]           DECIMAL (12, 4) NULL,
    [gw_id]                                   INT             NULL,
    [gw_base_price]                           DECIMAL (12, 4) NULL,
    [gw_price]                                DECIMAL (12, 4) NULL,
    [gw_base_tax_amount]                      DECIMAL (12, 4) NULL,
    [gw_tax_amount]                           DECIMAL (12, 4) NULL,
    [gw_base_price_invoiced]                  DECIMAL (12, 4) NULL,
    [gw_price_invoiced]                       DECIMAL (12, 4) NULL,
    [gw_base_tax_amount_invoiced]             DECIMAL (12, 4) NULL,
    [gw_tax_amount_invoiced]                  DECIMAL (12, 4) NULL,
    [gw_base_price_refunded]                  DECIMAL (12, 4) NULL,
    [gw_price_refunded]                       DECIMAL (12, 4) NULL,
    [gw_base_tax_amount_refunded]             DECIMAL (12, 4) NULL,
    [gw_tax_amount_refunded]                  DECIMAL (12, 4) NULL,
    [event_id]                                INT             NULL,
    [giftregistry_item_id]                    INT             NULL,
    [m1_order_item_id]                        INT             NULL,
    [wd_region_id]                            INT             NULL,
    [wd_costcenter_id]                        INT             NULL,
    [wd_offering_id]                          INT             NULL,
    [wd_spending_id]                          INT             NULL,
    [wd_revenue_id]                           INT             NULL,
    [email_template_id]                       INT             NULL,
    [agreement_id]                            VARCHAR (8000)  NULL,
    [agreement_status]                        INT             NULL,
    [agreement_api_status]                    INT             NULL,
    [mms_id]                                  VARCHAR (8000)  NULL,
    [mms_club_id]                             VARCHAR (8000)  NULL,
    [lt_bucks_redeemed]                       INT             NULL,
    [lt_bucks_refunded]                       INT             NULL,
    [vendor]                                  INT             NULL,
    [dv_load_date_time]                       DATETIME        NOT NULL,
    [dv_batch_id]                             BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

