CREATE TABLE [dbo].[stage_hash_hybris_stocklevels] (
    [stage_hash_hybris_stocklevels_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                          CHAR (32)      NOT NULL,
    [hjmpTS]                           BIGINT         NULL,
    [TypePkString]                     BIGINT         NULL,
    [PK]                               BIGINT         NULL,
    [createdTS]                        DATETIME       NULL,
    [modifiedTS]                       DATETIME       NULL,
    [OwnerPkString]                    BIGINT         NULL,
    [aCLTS]                            INT            NULL,
    [propTS]                           INT            NULL,
    [p_preorder]                       INT            NULL,
    [p_treatnegativeaszero]            TINYINT        NULL,
    [p_overselling]                    INT            NULL,
    [p_maxstocklevelhistorycount]      INT            NULL,
    [p_instockstatus]                  BIGINT         NULL,
    [p_available]                      INT            NULL,
    [p_productcode]                    NVARCHAR (255) NULL,
    [p_reserved]                       INT            NULL,
    [p_warehouse]                      BIGINT         NULL,
    [p_maxpreorder]                    INT            NULL,
    [p_releasedate]                    DATETIME       NULL,
    [p_nextdeliverytime]               DATETIME       NULL,
    [dv_load_date_time]                DATETIME       NOT NULL,
    [dv_inserted_date_time]            DATETIME       NOT NULL,
    [dv_insert_user]                   VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]             DATETIME       NULL,
    [dv_update_user]                   VARCHAR (50)   NULL,
    [dv_batch_id]                      BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

