CREATE TABLE [dbo].[stage_ig_it_trn_Order_Header] (
    [stage_ig_it_trn_Order_Header_id] BIGINT        NOT NULL,
    [assoc_check_no]                  INT           NULL,
    [bus_day_id]                      INT           NULL,
    [cashier_emp_id]                  INT           NULL,
    [check_no]                        INT           NULL,
    [check_status]                    SMALLINT      NULL,
    [check_type_id]                   INT           NULL,
    [close_dttime]                    DATETIME      NULL,
    [close_term_id]                   INT           NULL,
    [discount_amt]                    MONEY         NULL,
    [drawer_no]                       SMALLINT      NULL,
    [grat_amt]                        MONEY         NULL,
    [meal_period_id]                  INT           NULL,
    [num_covers]                      SMALLINT      NULL,
    [open_dttime]                     DATETIME      NULL,
    [open_term_id]                    INT           NULL,
    [order_hdr_id]                    INT           NULL,
    [order_process_dttime]            DATETIME      NULL,
    [pretender_flag]                  BIT           NULL,
    [print_count]                     SMALLINT      NULL,
    [profit_center_id]                INT           NULL,
    [refund_flag]                     BIT           NULL,
    [sales_amt_gross]                 MONEY         NULL,
    [sales_tippable_flag]             BIT           NULL,
    [server_emp_id]                   INT           NULL,
    [service_charge_amt]              MONEY         NULL,
    [table_alpha_no]                  NVARCHAR (30) NULL,
    [table_no]                        SMALLINT      NULL,
    [tax_amt]                         MONEY         NULL,
    [tax_removd_flag]                 BIT           NULL,
    [tender_amt_gross]                MONEY         NULL,
    [tender_id]                       INT           NULL,
    [tip_amt]                         MONEY         NULL,
    [tran_data_tag_text]              NVARCHAR (30) NULL,
    [void_reason_id]                  INT           NULL,
    [jan_one]                         DATETIME      NULL,
    [dv_batch_id]                     BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

