CREATE TABLE [dbo].[stage_hash_spabiz_SERVICE] (
    [stage_hash_spabiz_SERVICE_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)       NOT NULL,
    [ID]                           DECIMAL (26, 6) NULL,
    [COUNTERID]                    DECIMAL (26, 6) NULL,
    [STOREID]                      DECIMAL (26, 6) NULL,
    [EDITTIME]                     DATETIME        NULL,
    [Delete]                       DECIMAL (26, 6) NULL,
    [DELETEDATE]                   DATETIME        NULL,
    [NAME]                         VARCHAR (150)   NULL,
    [QUICKID]                      VARCHAR (90)    NULL,
    [BOOKNAME]                     VARCHAR (150)   NULL,
    [RETAILPRICE]                  DECIMAL (26, 6) NULL,
    [DATECREATED]                  DATETIME        NULL,
    [ACTIVE]                       DECIMAL (26, 6) NULL,
    [COST]                         DECIMAL (26, 6) NULL,
    [TIME]                         VARCHAR (15)    NULL,
    [PROCESS]                      VARCHAR (15)    NULL,
    [FINISH]                       VARCHAR (15)    NULL,
    [DEPTCAT]                      DECIMAL (26, 6) NULL,
    [SEARCHCAT]                    DECIMAL (26, 6) NULL,
    [COSTTYPE]                     DECIMAL (26, 6) NULL,
    [CALLAFTERXDAYS]               DECIMAL (26, 6) NULL,
    [PAYCOMISH]                    DECIMAL (26, 6) NULL,
    [DESCRIPTION]                  VARCHAR (3000)  NULL,
    [POPUP]                        VARCHAR (765)   NULL,
    [TAXABLE]                      DECIMAL (26, 6) NULL,
    [RESOURCECOUNT]                DECIMAL (26, 6) NULL,
    [NEWEXTRATIME]                 VARCHAR (30)    NULL,
    [REQUIRESTAFF]                 DECIMAL (26, 6) NULL,
    [Date]                         DATETIME        NULL,
    [STORE_NUMBER]                 DECIMAL (26, 6) NULL,
    [GLACCOUNT]                    VARCHAR (45)    NULL,
    [PAYTIP]                       DECIMAL (26, 6) NULL,
    [TIP]                          DECIMAL (26, 6) NULL,
    [WEBBOOK]                      DECIMAL (26, 6) NULL,
    [NEWID]                        DECIMAL (26, 6) NULL,
    [SERVICEBACKUPID]              DECIMAL (26, 6) NULL,
    [WEBVIEW]                      DECIMAL (26, 6) NULL,
    [HEADMAPSERVICE]               DECIMAL (26, 6) NULL,
    [HAIRLENGTH]                   VARCHAR (30)    NULL,
    [ISHILITEPROCEDURE]            DECIMAL (26, 6) NULL,
    [ISCOLORBALANCE]               DECIMAL (26, 6) NULL,
    [SERVICELEVEL]                 DECIMAL (26, 6) NULL,
    [SERVICE_CLASS]                VARCHAR (9)     NULL,
    [ALLOWPOWERBOOKING]            DECIMAL (26, 6) NULL,
    [REQCC]                        DECIMAL (26, 6) NULL,
    [EXCLUDEAPPTGAUR]              DECIMAL (26, 6) NULL,
    [dv_load_date_time]            DATETIME        NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]         DATETIME        NULL,
    [dv_update_user]               VARCHAR (50)    NULL,
    [dv_batch_id]                  BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

