CREATE TABLE [dbo].[stage_crmcloudsync_LTF_DNCDNETempRelease] (
    [stage_crmcloudsync_LTF_DNCDNETempRelease_id] BIGINT         NOT NULL,
    [createdby]                                   VARCHAR (36)   NULL,
    [createdbyname]                               NVARCHAR (200) NULL,
    [createdbyyominame]                           NVARCHAR (200) NULL,
    [createdon]                                   DATETIME       NULL,
    [createdonbehalfby]                           VARCHAR (36)   NULL,
    [createdonbehalfbyname]                       NVARCHAR (200) NULL,
    [createdonbehalfbyyominame]                   NVARCHAR (200) NULL,
    [importsequencenumber]                        INT            NULL,
    [ltf_dncdnetempreleaseid]                     VARCHAR (36)   NULL,
    [ltf_expirationdate]                          DATETIME       NULL,
    [ltf_value]                                   NVARCHAR (100) NULL,
    [modifiedby]                                  VARCHAR (36)   NULL,
    [modifiedbyname]                              NVARCHAR (200) NULL,
    [modifiedbyyominame]                          NVARCHAR (200) NULL,
    [modifiedon]                                  DATETIME       NULL,
    [modifiedonbehalfby]                          VARCHAR (36)   NULL,
    [modifiedonbehalfbyname]                      NVARCHAR (200) NULL,
    [modifiedonbehalfbyyominame]                  NVARCHAR (200) NULL,
    [organizationid]                              VARCHAR (36)   NULL,
    [organizationidname]                          NVARCHAR (160) NULL,
    [overriddencreatedon]                         DATETIME       NULL,
    [statecode]                                   INT            NULL,
    [statecodename]                               NVARCHAR (255) NULL,
    [statuscode]                                  INT            NULL,
    [statuscodename]                              NVARCHAR (255) NULL,
    [timezoneruleversionnumber]                   INT            NULL,
    [utcconversiontimezonecode]                   INT            NULL,
    [versionnumber]                               BIGINT         NULL,
    [InsertedDateTime]                            DATETIME       NULL,
    [InsertUser]                                  VARCHAR (100)  NULL,
    [UpdatedDateTime]                             DATETIME       NULL,
    [UpdateUser]                                  VARCHAR (50)   NULL,
    [dv_batch_id]                                 BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

