CREATE TABLE [dbo].[stage_crmcloudsync_LTF_Subscription] (
    [stage_crmcloudsync_LTF_Subscription_id] BIGINT          NOT NULL,
    [createdby]                              VARCHAR (36)    NULL,
    [createdbyname]                          NVARCHAR (200)  NULL,
    [createdbyyominame]                      NVARCHAR (200)  NULL,
    [createdon]                              DATETIME        NULL,
    [createdonbehalfby]                      VARCHAR (36)    NULL,
    [createdonbehalfbyname]                  NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]              NVARCHAR (200)  NULL,
    [exchangerate]                           DECIMAL (28)    NULL,
    [importsequencenumber]                   INT             NULL,
    [ltf_accountid]                          VARCHAR (36)    NULL,
    [ltf_accountidname]                      NVARCHAR (160)  NULL,
    [ltf_accountidyominame]                  NVARCHAR (160)  NULL,
    [ltf_activationdate]                     DATETIME        NULL,
    [ltf_cancellationdate]                   DATETIME        NULL,
    [ltf_clubid]                             VARCHAR (36)    NULL,
    [ltf_clubidname]                         NVARCHAR (100)  NULL,
    [ltf_cost]                               DECIMAL (26, 6) NULL,
    [ltf_cost_base]                          DECIMAL (26, 6) NULL,
    [ltf_customercompanycode]                NVARCHAR (100)  NULL,
    [ltf_productid]                          VARCHAR (36)    NULL,
    [ltf_productidname]                      NVARCHAR (100)  NULL,
    [ltf_referringcontactid]                 VARCHAR (36)    NULL,
    [ltf_referringcontactidname]             NVARCHAR (160)  NULL,
    [ltf_referringcontactidyominame]         NVARCHAR (160)  NULL,
    [ltf_referringmemberid]                  NVARCHAR (10)   NULL,
    [ltf_subscriptionid]                     VARCHAR (36)    NULL,
    [ltf_subscriptionnumber]                 NVARCHAR (100)  NULL,
    [ltf_terminationdate]                    DATETIME        NULL,
    [ltf_terminationreason]                  NVARCHAR (100)  NULL,
    [ltf_udwid]                              NVARCHAR (255)  NULL,
    [modifiedby]                             VARCHAR (36)    NULL,
    [modifiedbyname]                         NVARCHAR (200)  NULL,
    [modifiedbyyominame]                     NVARCHAR (200)  NULL,
    [modifiedon]                             DATETIME        NULL,
    [modifiedonbehalfby]                     VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]                 NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]             NVARCHAR (200)  NULL,
    [overriddencreatedon]                    DATETIME        NULL,
    [ownerid]                                VARCHAR (36)    NULL,
    [owneridname]                            NVARCHAR (200)  NULL,
    [owneridtype]                            NVARCHAR (64)   NULL,
    [owneridyominame]                        NVARCHAR (200)  NULL,
    [owningbusinessunit]                     VARCHAR (36)    NULL,
    [owningteam]                             VARCHAR (36)    NULL,
    [owninguser]                             VARCHAR (36)    NULL,
    [statecode]                              INT             NULL,
    [statecodename]                          NVARCHAR (255)  NULL,
    [statuscode]                             INT             NULL,
    [statuscodename]                         NVARCHAR (255)  NULL,
    [timezoneruleversionnumber]              INT             NULL,
    [transactioncurrencyid]                  VARCHAR (36)    NULL,
    [transactioncurrencyidname]              NVARCHAR (100)  NULL,
    [utcconversiontimezonecode]              INT             NULL,
    [versionnumber]                          BIGINT          NULL,
    [InsertedDateTime]                       DATETIME        NULL,
    [InsertUser]                             VARCHAR (100)   NULL,
    [UpdatedDateTime]                        DATETIME        NULL,
    [UpdateUser]                             VARCHAR (50)    NULL,
    [ltf_clubportfoliostaffingid]            VARCHAR (36)    NULL,
    [ltf_clubportfoliostaffingidname]        NVARCHAR (100)  NULL,
    [ltf_lthealthreactivationdate]           DATETIME        NULL,
    [ltf_monthlycostofmembership]            DECIMAL (26, 6) NULL,
    [ltf_attritionexclusion]                 BIT             NULL,
    [ltf_attritionexclusionname]             NVARCHAR (255)  NULL,
    [ltf_accounthousehold]                   VARCHAR (36)    NULL,
    [ltf_accounthouseholdname]               NVARCHAR (160)  NULL,
    [ltf_accounthouseholyomidname]           NVARCHAR (160)  NULL,
    [ltf_monthlycostofmembership_base]       DECIMAL (26, 6) NULL,
    [ltf_revenueunit]                        BIT             NULL,
    [ltf_revenueunitname]                    NVARCHAR (255)  NULL,
    [dv_batch_id]                            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

