CREATE TABLE [dbo].[stage_boss_asiinvtr] (
    [stage_boss_asiinvtr_id] BIGINT          NOT NULL,
    [invtr_upccode]          CHAR (15)       NULL,
    [invtr_dept]             INT             NULL,
    [invtr_class]            INT             NULL,
    [invtr_vendor]           CHAR (18)       NULL,
    [invtr_desc]             CHAR (50)       NULL,
    [invtr_size]             CHAR (8)        NULL,
    [invtr_color]            CHAR (8)        NULL,
    [invtr_style]            CHAR (8)        NULL,
    [invtr_price]            DECIMAL (10, 3) NULL,
    [invtr_cost]             DECIMAL (10, 2) NULL,
    [invtr_promo_part]       CHAR (1)        NULL,
    [invtr_suggestion]       CHAR (48)       NULL,
    [invtr_active_promo]     INT             NULL,
    [invtr_sku]              CHAR (18)       NULL,
    [invtr_created]          DATETIME        NULL,
    [invtr_last_sold]        DATETIME        NULL,
    [invtr_display]          CHAR (1)        NULL,
    [invtr_legacy_prod_id]   INT             NULL,
    [invtr_class_id]         INT             NULL,
    [invtr_vendor_prod_id]   CHAR (15)       NULL,
    [invtr_target]           INT             NULL,
    [invtr_limit]            INT             NULL,
    [invtr_iskit]            CHAR (1)        NULL,
    [invtr_category_id]      INT             NULL,
    [invtr_can_reorder]      CHAR (1)        NULL,
    [waiver_file_id]         INT             NULL,
    [invtr_updated_at]       DATETIME        NULL,
    [invtr_id]               INT             NULL,
    [use_for_LTBucks]        CHAR (1)        NULL,
    [dv_batch_id]            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

