CREATE TABLE [dbo].[stage_hash_ig_it_cfg_Terminal_Master] (
    [stage_hash_ig_it_cfg_Terminal_Master_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)     NOT NULL,
    [term_id]                                 INT           NULL,
    [term_name]                               NVARCHAR (50) NULL,
    [IP_address]                              NVARCHAR (15) NULL,
    [term_grp_id]                             INT           NULL,
    [term_printer_grp_id]                     INT           NULL,
    [term_service_grp_id]                     INT           NULL,
    [term_option_grp_id]                      INT           NULL,
    [primary_profit_center_id]                INT           NULL,
    [term_active_flag]                        BIT           NULL,
    [first_table_no]                          INT           NULL,
    [num_tables]                              INT           NULL,
    [alt_rcpt_term_id]                        INT           NULL,
    [GA_file_load_flag]                       BIT           NULL,
    [FOL_file_load_flag]                      BIT           NULL,
    [RMS_file_load_flag]                      BIT           NULL,
    [current_version]                         NVARCHAR (15) NULL,
    [default_table_layout_id]                 INT           NULL,
    [profile_id]                              INT           NULL,
    [alt_bargun_term_id]                      INT           NULL,
    [virtual_term_flag]                       BIT           NULL,
    [bargun_term_flag]                        BIT           NULL,
    [bargun_bump_override_flag]               BIT           NULL,
    [bargun_print_drinks_on_bump_flag]        BIT           NULL,
    [ped_value]                               NVARCHAR (50) NULL,
    [term_receipt_info]                       NVARCHAR (50) NULL,
    [row_version]                             BINARY (8)    NULL,
    [receipt_printer_type]                    TINYINT       NULL,
    [static_receipt_printer_id]               INT           NULL,
    [last_ping_utc_date_time]                 DATETIME      NULL,
    [payment_device_id]                       INT           NULL,
    [is_default_api_terminal]                 BIT           NULL,
    [dummy_modified_date_time]                DATETIME      NULL,
    [dv_load_date_time]                       DATETIME      NOT NULL,
    [dv_batch_id]                             BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

