CREATE TABLE [dbo].[stage_crmcloudsync_LTF_Club] (
    [stage_crmcloudsync_LTF_Club_id]      BIGINT          NOT NULL,
    [createdby]                           VARCHAR (36)    NULL,
    [createdbyname]                       NVARCHAR (200)  NULL,
    [createdbyyominame]                   NVARCHAR (200)  NULL,
    [createdon]                           DATETIME        NULL,
    [createdonbehalfby]                   VARCHAR (36)    NULL,
    [createdonbehalfbyname]               NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]           NVARCHAR (200)  NULL,
    [importsequencenumber]                INT             NULL,
    [ltf_address1_addresstypecode]        INT             NULL,
    [ltf_address1_addresstypecodename]    NVARCHAR (255)  NULL,
    [ltf_address1_city]                   NVARCHAR (50)   NULL,
    [ltf_address1_country]                NVARCHAR (50)   NULL,
    [ltf_address1_county]                 NVARCHAR (50)   NULL,
    [ltf_address1_fax]                    NVARCHAR (50)   NULL,
    [ltf_address1_latitude]               DECIMAL (26, 6) NULL,
    [ltf_address1_line1]                  NVARCHAR (50)   NULL,
    [ltf_address1_line2]                  NVARCHAR (50)   NULL,
    [ltf_address1_line3]                  NVARCHAR (50)   NULL,
    [ltf_address1_longitude]              DECIMAL (26, 6) NULL,
    [ltf_address1_name]                   INT             NULL,
    [ltf_address1_namename]               NVARCHAR (255)  NULL,
    [ltf_address1_postalcode]             NVARCHAR (20)   NULL,
    [ltf_address1_postofficebox]          NVARCHAR (20)   NULL,
    [ltf_address1_shippingmethodcode]     INT             NULL,
    [ltf_address1_shippingmethodcodename] NVARCHAR (255)  NULL,
    [ltf_address1_stateorprovince]        NVARCHAR (50)   NULL,
    [ltf_address1_telephone1]             NVARCHAR (50)   NULL,
    [ltf_address1_telephone2]             NVARCHAR (50)   NULL,
    [ltf_address1_telephone3]             NVARCHAR (50)   NULL,
    [ltf_address1_upszone]                NVARCHAR (4)    NULL,
    [ltf_address1_utcoffset]              INT             NULL,
    [ltf_address2_addresstypecode]        INT             NULL,
    [ltf_address2_addresstypecodename]    NVARCHAR (255)  NULL,
    [ltf_address2_city]                   NVARCHAR (50)   NULL,
    [ltf_address2_country]                NVARCHAR (50)   NULL,
    [ltf_address2_county]                 NVARCHAR (50)   NULL,
    [ltf_address2_fax]                    NVARCHAR (50)   NULL,
    [ltf_address2_latitude]               DECIMAL (26, 6) NULL,
    [ltf_address2_line1]                  NVARCHAR (50)   NULL,
    [ltf_address2_line2]                  NVARCHAR (50)   NULL,
    [ltf_address2_line3]                  NVARCHAR (50)   NULL,
    [ltf_address2_longitude]              DECIMAL (26, 6) NULL,
    [ltf_address2_name]                   INT             NULL,
    [ltf_address2_namename]               NVARCHAR (255)  NULL,
    [ltf_address2_postalcode]             NVARCHAR (20)   NULL,
    [ltf_address2_postofficebox]          NVARCHAR (20)   NULL,
    [ltf_address2_shippingmethodcode]     INT             NULL,
    [ltf_address2_shippingmethodcodename] NVARCHAR (255)  NULL,
    [ltf_address2_stateorprovince]        NVARCHAR (50)   NULL,
    [ltf_address2_telephone1]             NVARCHAR (50)   NULL,
    [ltf_address2_telephone2]             NVARCHAR (50)   NULL,
    [ltf_address2_telephone3]             NVARCHAR (50)   NULL,
    [ltf_address2_upszone]                NVARCHAR (4)    NULL,
    [ltf_address2_utcoffset]              INT             NULL,
    [ltf_buddyreferral]                   BIT             NULL,
    [ltf_buddyreferralname]               NVARCHAR (255)  NULL,
    [ltf_clubdivision]                    VARCHAR (36)    NULL,
    [ltf_clubdivisionname]                NVARCHAR (160)  NULL,
    [ltf_clubid]                          VARCHAR (36)    NULL,
    [ltf_clubregion]                      VARCHAR (36)    NULL,
    [ltf_clubregionalmanager]             VARCHAR (36)    NULL,
    [ltf_clubregionalmanagername]         NVARCHAR (200)  NULL,
    [ltf_clubregionalmanageryominame]     NVARCHAR (200)  NULL,
    [ltf_clubregionname]                  NVARCHAR (160)  NULL,
    [ltf_clubsid]                         VARCHAR (36)    NULL,
    [ltf_clubsidname]                     NVARCHAR (160)  NULL,
    [ltf_clubteamid]                      VARCHAR (36)    NULL,
    [ltf_clubteamidname]                  NVARCHAR (160)  NULL,
    [ltf_clubteamidyominame]              NVARCHAR (160)  NULL,
    [ltf_contactus]                       BIT             NULL,
    [ltf_contactusname]                   NVARCHAR (255)  NULL,
    [ltf_emailaddress]                    NVARCHAR (100)  NULL,
    [ltf_enablemyltreferral]              BIT             NULL,
    [ltf_enablemyltreferralname]          NVARCHAR (255)  NULL,
    [ltf_fiveletterclubcode]              NVARCHAR (5)    NULL,
    [ltf_fourletterclubcode]              NVARCHAR (4)    NULL,
    [ltf_generalmanager]                  VARCHAR (36)    NULL,
    [ltf_generalmanagername]              NVARCHAR (200)  NULL,
    [ltf_generalmanageryominame]          NVARCHAR (200)  NULL,
    [ltf_guestpassduration]               INT             NULL,
    [ltf_guestpassdurationname]           NVARCHAR (255)  NULL,
    [ltf_lthealthclub]                    BIT             NULL,
    [ltf_lthealthclubname]                NVARCHAR (255)  NULL,
    [ltf_mem]                             VARCHAR (36)    NULL,
    [ltf_membershiplevelsavailable]       INT             NULL,
    [ltf_membershiplevelsavailablename]   NVARCHAR (255)  NULL,
    [ltf_memname]                         NVARCHAR (200)  NULL,
    [ltf_memyominame]                     NVARCHAR (200)  NULL,
    [ltf_mmsclubid]                       NVARCHAR (10)   NULL,
    [ltf_mmsclubname]                     NVARCHAR (50)   NULL,
    [ltf_name]                            NVARCHAR (100)  NULL,
    [ltf_nptrep]                          VARCHAR (36)    NULL,
    [ltf_nptrepname]                      NVARCHAR (200)  NULL,
    [ltf_nptrepyominame]                  NVARCHAR (200)  NULL,
    [ltf_pdth]                            VARCHAR (36)    NULL,
    [ltf_pdthname]                        NVARCHAR (200)  NULL,
    [ltf_pdthyominame]                    NVARCHAR (200)  NULL,
    [ltf_pricerequest]                    BIT             NULL,
    [ltf_pricerequestname]                NVARCHAR (255)  NULL,
    [ltf_regioncode]                      NVARCHAR (50)   NULL,
    [ltf_timezonecode]                    INT             NULL,
    [ltf_udwid]                           NVARCHAR (255)  NULL,
    [ltf_webinquiry]                      BIT             NULL,
    [ltf_webinquiryname]                  NVARCHAR (255)  NULL,
    [ltf_webreferralpass]                 BIT             NULL,
    [ltf_webreferralpassname]             NVARCHAR (255)  NULL,
    [ltf_websiteclubname]                 NVARCHAR (50)   NULL,
    [ltf_webspecialistteam]               VARCHAR (36)    NULL,
    [ltf_webspecialistteamname]           NVARCHAR (160)  NULL,
    [ltf_webspecialistteamyominame]       NVARCHAR (160)  NULL,
    [modifiedby]                          VARCHAR (36)    NULL,
    [modifiedbyname]                      NVARCHAR (200)  NULL,
    [modifiedbyyominame]                  NVARCHAR (200)  NULL,
    [modifiedon]                          DATETIME        NULL,
    [modifiedonbehalfby]                  VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]              NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]          NVARCHAR (200)  NULL,
    [organizationid]                      VARCHAR (36)    NULL,
    [organizationidname]                  NVARCHAR (160)  NULL,
    [overriddencreatedon]                 DATETIME        NULL,
    [statecode]                           INT             NULL,
    [statecodename]                       NVARCHAR (255)  NULL,
    [statuscode]                          INT             NULL,
    [statuscodename]                      NVARCHAR (255)  NULL,
    [timezoneruleversionnumber]           INT             NULL,
    [utcconversiontimezonecode]           INT             NULL,
    [versionnumber]                       BIGINT          NULL,
    [InsertedDateTime]                    DATETIME        NULL,
    [InsertUser]                          VARCHAR (100)   NULL,
    [UpdatedDateTime]                     DATETIME        NULL,
    [UpdateUser]                          VARCHAR (50)    NULL,
    [ltf_territoryid]                     VARCHAR (36)    NULL,
    [ltf_parentterritoryid]               VARCHAR (36)    NULL,
    [ltf_acceptingpresalesleads]          BIT             NULL,
    [ltf_areadirector]                    VARCHAR (36)    NULL,
    [ltf_areadirectorname]                NVARCHAR (200)  NULL,
    [ltf_areadirectoryominame]            NVARCHAR (200)  NULL,
    [ltf_callcurentsucle]                 INT             NULL,
    [ltf_callcurentsucle_date]            DATETIME        NULL,
    [ltf_callcurentsucle_state]           INT             NULL,
    [ltf_ciguser]                         VARCHAR (36)    NULL,
    [ltf_cigusername]                     NVARCHAR (200)  NULL,
    [ltf_ciguseryominame]                 NVARCHAR (200)  NULL,
    [ltf_clubbrandname]                   NVARCHAR (100)  NULL,
    [ltf_clubmarketingname]               NVARCHAR (100)  NULL,
    [ltf_disablewebtransfer]              BIT             NULL,
    [ltf_disablewebtransfername]          NVARCHAR (255)  NULL,
    [ltf_oldteam]                         VARCHAR (36)    NULL,
    [ltf_oldteamname]                     NVARCHAR (160)  NULL,
    [ltf_oldteamyominame]                 NVARCHAR (160)  NULL,
    [ltf_parentterritoryidname]           NVARCHAR (200)  NULL,
    [ltf_presale]                         BIT             NULL,
    [ltf_regionalsaleslead]               VARCHAR (36)    NULL,
    [ltf_regionalsalesleadname]           NVARCHAR (200)  NULL,
    [ltf_regionalsalesleadyominame]       NVARCHAR (200)  NULL,
    [ltf_regionalvicepresident]           VARCHAR (36)    NULL,
    [ltf_regionalvicepresidentname]       NVARCHAR (200)  NULL,
    [ltf_regionalvicepresidentyominame]   NVARCHAR (200)  NULL,
    [ltf_srmem]                           VARCHAR (36)    NULL,
    [ltf_srmemname]                       NVARCHAR (200)  NULL,
    [ltf_srmemyominame]                   NVARCHAR (200)  NULL,
    [ltf_territoryidname]                 NVARCHAR (200)  NULL,
    [ltf_webteamline]                     NVARCHAR (20)   NULL,
    [ltf_acceptingpresalesleadsname]      NVARCHAR (255)  NULL,
    [ltf_presalename]                     NVARCHAR (255)  NULL,
    [ltf_buddyresetdays]                  INT             NULL,
    [ltf_excludefromexpiration]           BIT             NULL,
    [ltf_maxpassdays]                     INT             NULL,
    [ltf_passscanneractive]               BIT             NULL,
    [ltf_onlinejoinlink]                  INT             NULL,
    [ltf_kidmemberships]                  BIT             NULL,
    [ltf_buddyresetperiod]                INT             NULL,
    [ltf_restrictedguestpasspolicy]       BIT             NULL,
    [ltf_restrictedpassresetperiod]       BIT             NULL,
    [ltf_restrictedpassresetunits]        INT             NULL,
    [ltf_restrictedpassgraceperiod]       BIT             NULL,
    [ltf_restrictedpassgraceunits]        BIT             NULL,
    [ltf_webguestpassprocess]             BIT             NULL,
    [ltf_ltworkemail]                     INT             NULL,
    [dv_batch_id]                         BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

