CREATE TABLE [dbo].[stage_exerp_subscription_sale] (
    [stage_exerp_subscription_sale_id] BIGINT          NOT NULL,
    [id]                               INT             NULL,
    [subscription_id]                  VARCHAR (4000)  NULL,
    [subscription_center]              INT             NULL,
    [product_id]                       VARCHAR (4000)  NULL,
    [type]                             VARCHAR (4000)  NULL,
    [sale_datetime]                    DATETIME        NULL,
    [start_date]                       DATETIME        NULL,
    [end_date]                         DATETIME        NULL,
    [sale_person_id]                   VARCHAR (4000)  NULL,
    [jf_normal_price]                  DECIMAL (26, 6) NULL,
    [jf_discount]                      DECIMAL (26, 6) NULL,
    [jf_price]                         DECIMAL (26, 6) NULL,
    [jf_sponsored]                     DECIMAL (26, 6) NULL,
    [jf_member]                        DECIMAL (26, 6) NULL,
    [prorata_period_normal_price]      DECIMAL (26, 6) NULL,
    [prorata_period_discount]          DECIMAL (26, 6) NULL,
    [prorata_period_price]             DECIMAL (26, 6) NULL,
    [prorata_period_sponsored]         DECIMAL (26, 6) NULL,
    [prorata_period_member]            DECIMAL (26, 6) NULL,
    [init_period_normal_price]         DECIMAL (26, 6) NULL,
    [init_period_discount]             DECIMAL (26, 6) NULL,
    [init_period_price]                DECIMAL (26, 6) NULL,
    [init_period_sponsored]            DECIMAL (26, 6) NULL,
    [init_period_member]               DECIMAL (26, 6) NULL,
    [admin_fee_normal_price]           DECIMAL (26, 6) NULL,
    [admin_fee_discount]               DECIMAL (26, 6) NULL,
    [admin_fee_price]                  DECIMAL (26, 6) NULL,
    [admin_fee_sponsored]              DECIMAL (26, 6) NULL,
    [admin_fee_member]                 DECIMAL (26, 6) NULL,
    [binding_days]                     INT             NULL,
    [sale_id]                          VARCHAR (4000)  NULL,
    [init_contract_value]              DECIMAL (26, 6) NULL,
    [state]                            VARCHAR (4000)  NULL,
    [jf_sale_log_id]                   VARCHAR (4000)  NULL,
    [previous_subscription_id]         VARCHAR (4000)  NULL,
    [center_id]                        INT             NULL,
    [ets]                              BIGINT          NULL,
    [dummy_modified_date_time]         DATETIME        NULL,
    [dv_batch_id]                      BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

