CREATE TABLE [dbo].[stage_hash_spabiz_PRODUCT] (
    [stage_hash_spabiz_PRODUCT_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                      CHAR (32)       NOT NULL,
    [ID]                           DECIMAL (26, 6) NULL,
    [COUNTERID]                    DECIMAL (26, 6) NULL,
    [STOREID]                      DECIMAL (26, 6) NULL,
    [EDITTIME]                     DATETIME        NULL,
    [Delete]                       DECIMAL (26, 6) NULL,
    [DELETEDATE]                   DATETIME        NULL,
    [NAME]                         VARCHAR (195)   NULL,
    [QUICKID]                      VARCHAR (90)    NULL,
    [VENDORID]                     DECIMAL (26, 6) NULL,
    [VENDORCODE]                   VARCHAR (150)   NULL,
    [MANID]                        DECIMAL (26, 6) NULL,
    [MANCODE]                      VARCHAR (150)   NULL,
    [COST]                         DECIMAL (26, 6) NULL,
    [CURRENTCOST]                  DECIMAL (26, 6) NULL,
    [CURRENTLAYER]                 DECIMAL (26, 6) NULL,
    [RETAILPRICE]                  DECIMAL (26, 6) NULL,
    [COMMISSIONID]                 DECIMAL (26, 6) NULL,
    [TAXABLE]                      DECIMAL (26, 6) NULL,
    [TYPE]                         DECIMAL (26, 6) NULL,
    [PURCHASETAX]                  DECIMAL (26, 6) NULL,
    [DATECREATED]                  DATETIME        NULL,
    [WIDTH]                        DECIMAL (26, 6) NULL,
    [HEIGHT]                       DECIMAL (26, 6) NULL,
    [DEPTH]                        DECIMAL (26, 6) NULL,
    [WEIGHT]                       DECIMAL (26, 6) NULL,
    [ORDERFREQ]                    DECIMAL (26, 6) NULL,
    [CASEQTY]                      DECIMAL (26, 6) NULL,
    [DEPTCAT]                      DECIMAL (26, 6) NULL,
    [SEARCHCAT]                    DECIMAL (26, 6) NULL,
    [LOCATION]                     VARCHAR (150)   NULL,
    [EOQ]                          DECIMAL (26, 6) NULL,
    [SEASONAL]                     DECIMAL (26, 6) NULL,
    [MIN]                          DECIMAL (26, 6) NULL,
    [MAX]                          DECIMAL (26, 6) NULL,
    [LABELNAME]                    VARCHAR (150)   NULL,
    [PRINTLABELS]                  DECIMAL (26, 6) NULL,
    [COST2]                        DECIMAL (26, 6) NULL,
    [COST2QTY]                     DECIMAL (26, 6) NULL,
    [COST3]                        DECIMAL (26, 6) NULL,
    [COST3QTY]                     DECIMAL (26, 6) NULL,
    [CURRENTQTY]                   DECIMAL (26, 6) NULL,
    [PRINTONTICKET]                VARCHAR (765)   NULL,
    [STATUS]                       VARCHAR (150)   NULL,
    [LABELS]                       DECIMAL (26, 6) NULL,
    [ONORDER]                      DECIMAL (26, 6) NULL,
    [NOTE]                         VARCHAR (3000)  NULL,
    [LASTSOLD]                     DATETIME        NULL,
    [LASTCOUNT]                    DATETIME        NULL,
    [STORERANK]                    DECIMAL (26, 6) NULL,
    [MINMAXID]                     DECIMAL (26, 6) NULL,
    [STOCKLEVEL]                   DECIMAL (26, 6) NULL,
    [QUARTERSALES]                 DECIMAL (26, 6) NULL,
    [MINDAYS]                      DECIMAL (26, 6) NULL,
    [MAXDAYS]                      DECIMAL (26, 6) NULL,
    [LASTPURCHASE]                 DATETIME        NULL,
    [AVGCOST]                      DECIMAL (26, 6) NULL,
    [DEFAULTSTAFFID]               DECIMAL (26, 6) NULL,
    [ACTIVE]                       DECIMAL (26, 6) NULL,
    [STORE_NUMBER]                 DECIMAL (26, 6) NULL,
    [GLACCOUNT]                    VARCHAR (45)    NULL,
    [ENTERID]                      DECIMAL (26, 6) NULL,
    [LINKID]                       DECIMAL (26, 6) NULL,
    [GUID_LINK]                    VARCHAR (300)   NULL,
    [GUID_SOURCEID]                VARCHAR (300)   NULL,
    [PRODUCTLEVEL]                 DECIMAL (26, 6) NULL,
    [PARENTID]                     DECIMAL (26, 6) NULL,
    [NEWID]                        DECIMAL (26, 6) NULL,
    [PRODUCTBACKUPID]              DECIMAL (26, 6) NULL,
    [BACKUPPRODID]                 DECIMAL (26, 6) NULL,
    [dv_load_date_time]            DATETIME        NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]         DATETIME        NULL,
    [dv_update_user]               VARCHAR (50)    NULL,
    [dv_batch_id]                  BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

