CREATE TABLE [dbo].[stage_hash_mms_Company] (
    [stage_hash_mms_Company_id]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                     CHAR (32)      NOT NULL,
    [CompanyID]                   INT            NULL,
    [AccountRepInitials]          VARCHAR (5)    NULL,
    [CompanyName]                 VARCHAR (50)   NULL,
    [PrintUsageReportFlag]        BIT            NULL,
    [CorporateCode]               VARCHAR (50)   NULL,
    [InsertedDateTime]            DATETIME       NULL,
    [StartDate]                   DATETIME       NULL,
    [EndDate]                     DATETIME       NULL,
    [AccountRepName]              VARCHAR (50)   NULL,
    [InitiationFee]               NUMERIC (8, 4) NULL,
    [UpdatedDateTime]             DATETIME       NULL,
    [EnrollmentDiscPercentage]    NUMERIC (7, 4) NULL,
    [MACEnrollmentDiscPercentage] NUMERIC (7, 4) NULL,
    [InvoiceFlag]                 BIT            NULL,
    [DollarDiscount]              NUMERIC (8, 4) NULL,
    [AdminFee]                    NUMERIC (8, 4) NULL,
    [OverridePercentage]          NUMERIC (7, 4) NULL,
    [EFTAccountNumber]            VARCHAR (4)    NULL,
    [UsageReportFlag]             BIT            NULL,
    [ReportToEmailAddress]        VARCHAR (150)  NULL,
    [UsageReportMemberType]       VARCHAR (50)   NULL,
    [SmallBusinessFlag]           BIT            NULL,
    [AccountOwner]                VARCHAR (100)  NULL,
    [SubsidyMeasurement]          VARCHAR (30)   NULL,
    [OpportunityRecordType]       VARCHAR (50)   NULL,
    [dv_load_date_time]           DATETIME       NOT NULL,
    [dv_inserted_date_time]       DATETIME       NOT NULL,
    [dv_insert_user]              VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]        DATETIME       NULL,
    [dv_update_user]              VARCHAR (50)   NULL,
    [dv_batch_id]                 BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

