CREATE TABLE [dbo].[stage_hybris_usergroups] (
    [stage_hybris_usergroups_id]   BIGINT         NOT NULL,
    [hjmpTS]                       BIGINT         NULL,
    [createdTS]                    DATETIME       NULL,
    [modifiedTS]                   DATETIME       NULL,
    [TypePkString]                 BIGINT         NULL,
    [OwnerPkString]                BIGINT         NULL,
    [PK]                           BIGINT         NULL,
    [p_description]                NVARCHAR (255) NULL,
    [p_name]                       NVARCHAR (255) NULL,
    [p_uid]                        NVARCHAR (255) NULL,
    [p_profilepicture]             BIGINT         NULL,
    [p_backofficelogindisabled]    TINYINT        NULL,
    [p_ldapsearchbase]             NVARCHAR (255) NULL,
    [p_dn]                         VARCHAR (8000) NULL,
    [p_cn]                         NVARCHAR (255) NULL,
    [p_maxbruteforceloginattempts] INT            NULL,
    [p_writeablelanguages]         VARCHAR (8000) NULL,
    [p_readablelanguages]          VARCHAR (8000) NULL,
    [p_userdiscountgroup]          BIGINT         NULL,
    [p_userpricegroup]             BIGINT         NULL,
    [p_usertaxgroup]               BIGINT         NULL,
    [p_hmclogindisabled]           TINYINT        NULL,
    [aCLTS]                        BIGINT         NULL,
    [propTS]                       BIGINT         NULL,
    [p_dunsid]                     NVARCHAR (255) NULL,
    [p_ilnid]                      NVARCHAR (255) NULL,
    [p_buyerspecificid]            NVARCHAR (255) NULL,
    [p_id]                         NVARCHAR (255) NULL,
    [p_supplierspecificid]         NVARCHAR (255) NULL,
    [p_medias]                     VARCHAR (8000) NULL,
    [p_shippingaddress]            BIGINT         NULL,
    [p_unloadingaddress]           BIGINT         NULL,
    [p_billingaddress]             BIGINT         NULL,
    [p_contactaddress]             BIGINT         NULL,
    [p_contact]                    BIGINT         NULL,
    [p_vatid]                      NVARCHAR (255) NULL,
    [p_responsiblecompany]         BIGINT         NULL,
    [p_country]                    BIGINT         NULL,
    [p_lineofbuisness]             BIGINT         NULL,
    [p_buyer]                      TINYINT        NULL,
    [p_supplier]                   TINYINT        NULL,
    [p_manufacturer]               TINYINT        NULL,
    [p_carrier]                    TINYINT        NULL,
    [p_active]                     TINYINT        NULL,
    [p_implementationtype]         NVARCHAR (255) NULL,
    [p_priority]                   INT            NULL,
    [p_store]                      BIGINT         NULL,
    [p_emaildistributionlist]      NVARCHAR (255) NULL,
    [p_defaultassignee]            BIGINT         NULL,
    [dv_batch_id]                  BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

