CREATE TABLE [dbo].[stage_hash_magento_payment_breakdown] (
    [stage_hash_magento_payment_breakdown_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                 CHAR (32)       NOT NULL,
    [AccountSet]                              VARCHAR (255)   NULL,
    [LineCompany]                             VARCHAR (255)   NULL,
    [LedgerAccount]                           VARCHAR (255)   NULL,
    [WorkdayRegion]                           VARCHAR (4)     NULL,
    [ClubID]                                  INT             NULL,
    [CostCenter]                              VARCHAR (255)   NULL,
    [OfferingID]                              VARCHAR (255)   NULL,
    [SpendCategory]                           VARCHAR (255)   NULL,
    [RevenueCategory]                         VARCHAR (255)   NULL,
    [MerchantLocation]                        VARCHAR (255)   NULL,
    [OrderNum]                                VARCHAR (255)   NULL,
    [OENum]                                   INT             NULL,
    [SubCatName]                              VARCHAR (255)   NULL,
    [ProductID]                               VARCHAR (255)   NULL,
    [ProductName]                             VARCHAR (255)   NULL,
    [MMSProductID]                            INT             NULL,
    [DeliveryState]                           VARCHAR (255)   NULL,
    [Tax]                                     DECIMAL (26, 6) NULL,
    [OrderShippingAmount]                     DECIMAL (26, 6) NULL,
    [OrdDate]                                 VARCHAR (29)    NULL,
    [TranDate]                                VARCHAR (29)    NULL,
    [ShipDate]                                VARCHAR (29)    NULL,
    [MMSTransactionID]                        VARCHAR (255)   NULL,
    [MMSPackageID]                            INT             NULL,
    [MemberID]                                VARCHAR (255)   NULL,
    [Capture_LTBUCKS]                         DECIMAL (10, 2) NULL,
    [Capture_amex]                            DECIMAL (10, 2) NULL,
    [Capture_discover]                        DECIMAL (10, 2) NULL,
    [Capture_master]                          DECIMAL (10, 2) NULL,
    [Capture_visa]                            DECIMAL (10, 2) NULL,
    [Capture_PAYPAL]                          DECIMAL (10, 2) NULL,
    [Refund_LTBUCKS]                          DECIMAL (10, 2) NULL,
    [Refund_amex]                             DECIMAL (10, 2) NULL,
    [Refund_discover]                         DECIMAL (10, 2) NULL,
    [Refund_master]                           DECIMAL (10, 2) NULL,
    [Refund_visa]                             DECIMAL (10, 2) NULL,
    [Refund_PAYPAL]                           DECIMAL (10, 2) NULL,
    [ReportRunDateTime]                       VARCHAR (50)    NULL,
    [ReportStartDate]                         DATETIME        NULL,
    [ReportEndDate]                           DATETIME        NULL,
    [TransactionAmount]                       DECIMAL (10, 2) NULL,
    [jan_one]                                 DATETIME        NULL,
    [dv_load_date_time]                       DATETIME        NOT NULL,
    [dv_batch_id]                             BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

