CREATE TABLE [dbo].[stage_crmcloudsync_Contact] (
    [stage_crmcloudsync_Contact_id]        BIGINT           NOT NULL,
    [accountid]                            VARCHAR (36)     NULL,
    [accountidname]                        NVARCHAR (160)   NULL,
    [accountidyominame]                    NVARCHAR (160)   NULL,
    [accountrolecode]                      INT              NULL,
    [accountrolecodename]                  NVARCHAR (255)   NULL,
    [address1_addressid]                   VARCHAR (36)     NULL,
    [address1_addresstypecode]             INT              NULL,
    [address1_addresstypecodename]         NVARCHAR (255)   NULL,
    [address1_city]                        NVARCHAR (80)    NULL,
    [address1_composite]                   NVARCHAR (4000)  NULL,
    [address1_country]                     NVARCHAR (80)    NULL,
    [address1_county]                      NVARCHAR (50)    NULL,
    [address1_fax]                         NVARCHAR (50)    NULL,
    [address1_freighttermscode]            INT              NULL,
    [address1_freighttermscodename]        NVARCHAR (255)   NULL,
    [address1_latitude]                    DECIMAL (26, 6)  NULL,
    [address1_line1]                       NVARCHAR (250)   NULL,
    [address1_line2]                       NVARCHAR (250)   NULL,
    [address1_line3]                       NVARCHAR (250)   NULL,
    [address1_longitude]                   DECIMAL (26, 6)  NULL,
    [address1_name]                        NVARCHAR (200)   NULL,
    [address1_postalcode]                  NVARCHAR (20)    NULL,
    [address1_postofficebox]               NVARCHAR (20)    NULL,
    [address1_primarycontactname]          NVARCHAR (100)   NULL,
    [address1_shippingmethodcode]          INT              NULL,
    [address1_shippingmethodcodename]      NVARCHAR (255)   NULL,
    [address1_stateorprovince]             NVARCHAR (50)    NULL,
    [address1_telephone1]                  NVARCHAR (50)    NULL,
    [address1_telephone2]                  NVARCHAR (50)    NULL,
    [address1_telephone3]                  NVARCHAR (50)    NULL,
    [address1_upszone]                     NVARCHAR (4)     NULL,
    [address1_utcoffset]                   INT              NULL,
    [address2_addressid]                   VARCHAR (36)     NULL,
    [address2_addresstypecode]             INT              NULL,
    [address2_addresstypecodename]         NVARCHAR (255)   NULL,
    [address2_city]                        NVARCHAR (80)    NULL,
    [address2_composite]                   NVARCHAR (4000)  NULL,
    [address2_country]                     NVARCHAR (80)    NULL,
    [address2_county]                      NVARCHAR (50)    NULL,
    [address2_fax]                         NVARCHAR (50)    NULL,
    [address2_freighttermscode]            INT              NULL,
    [address2_freighttermscodename]        NVARCHAR (255)   NULL,
    [address2_latitude]                    DECIMAL (26, 6)  NULL,
    [address2_line1]                       NVARCHAR (250)   NULL,
    [address2_line2]                       NVARCHAR (250)   NULL,
    [address2_line3]                       NVARCHAR (250)   NULL,
    [address2_longitude]                   DECIMAL (26, 6)  NULL,
    [address2_name]                        NVARCHAR (100)   NULL,
    [address2_postalcode]                  NVARCHAR (20)    NULL,
    [address2_postofficebox]               NVARCHAR (20)    NULL,
    [address2_primarycontactname]          NVARCHAR (100)   NULL,
    [address2_shippingmethodcode]          INT              NULL,
    [address2_shippingmethodcodename]      NVARCHAR (255)   NULL,
    [address2_stateorprovince]             NVARCHAR (50)    NULL,
    [address2_telephone1]                  NVARCHAR (50)    NULL,
    [address2_telephone2]                  NVARCHAR (50)    NULL,
    [address2_telephone3]                  NVARCHAR (50)    NULL,
    [address2_upszone]                     NVARCHAR (4)     NULL,
    [address2_utcoffset]                   INT              NULL,
    [aging30]                              DECIMAL (26, 6)  NULL,
    [aging30_base]                         DECIMAL (26, 6)  NULL,
    [aging60]                              DECIMAL (26, 6)  NULL,
    [aging60_base]                         DECIMAL (26, 6)  NULL,
    [aging90]                              DECIMAL (26, 6)  NULL,
    [aging90_base]                         DECIMAL (26, 6)  NULL,
    [anniversary]                          DATETIME         NULL,
    [annualincome]                         DECIMAL (26, 6)  NULL,
    [annualincome_base]                    DECIMAL (26, 6)  NULL,
    [assistantname]                        NVARCHAR (100)   NULL,
    [assistantphone]                       NVARCHAR (50)    NULL,
    [birthdate]                            DATETIME         NULL,
    [childrensnames]                       NVARCHAR (255)   NULL,
    [contactid]                            VARCHAR (36)     NULL,
    [createdby]                            VARCHAR (36)     NULL,
    [createdbyname]                        NVARCHAR (200)   NULL,
    [createdbyyominame]                    NVARCHAR (200)   NULL,
    [createdon]                            DATETIME         NULL,
    [createdonbehalfby]                    VARCHAR (36)     NULL,
    [createdonbehalfbyname]                NVARCHAR (200)   NULL,
    [createdonbehalfbyyominame]            NVARCHAR (200)   NULL,
    [creditlimit]                          DECIMAL (26, 6)  NULL,
    [creditlimit_base]                     DECIMAL (26, 6)  NULL,
    [creditonhold]                         BIT              NULL,
    [creditonholdname]                     NVARCHAR (255)   NULL,
    [customersizecode]                     INT              NULL,
    [customersizecodename]                 NVARCHAR (255)   NULL,
    [customertypecode]                     INT              NULL,
    [customertypecodename]                 NVARCHAR (255)   NULL,
    [defaultpricelevelid]                  VARCHAR (36)     NULL,
    [defaultpricelevelidname]              NVARCHAR (100)   NULL,
    [department]                           NVARCHAR (100)   NULL,
    [description]                          NVARCHAR (4000)  NULL,
    [donotbulkemail]                       BIT              NULL,
    [donotbulkemailname]                   NVARCHAR (255)   NULL,
    [donotbulkpostalmail]                  BIT              NULL,
    [donotbulkpostalmailname]              NVARCHAR (255)   NULL,
    [donotemail]                           BIT              NULL,
    [donotemailname]                       NVARCHAR (255)   NULL,
    [donotfax]                             BIT              NULL,
    [donotfaxname]                         NVARCHAR (255)   NULL,
    [donotphone]                           BIT              NULL,
    [donotphonename]                       NVARCHAR (255)   NULL,
    [donotpostalmail]                      BIT              NULL,
    [donotpostalmailname]                  NVARCHAR (255)   NULL,
    [donotsendmarketingmaterialname]       NVARCHAR (255)   NULL,
    [donotsendmm]                          BIT              NULL,
    [educationcode]                        INT              NULL,
    [educationcodename]                    NVARCHAR (255)   NULL,
    [emailaddress1]                        NVARCHAR (100)   NULL,
    [emailaddress2]                        NVARCHAR (100)   NULL,
    [emailaddress3]                        NVARCHAR (100)   NULL,
    [employeeid]                           NVARCHAR (50)    NULL,
    [entityimage]                          VARBINARY (8000) NULL,
    [entityimage_timestamp]                BIGINT           NULL,
    [entityimage_url]                      NVARCHAR (200)   NULL,
    [entityimageid]                        VARCHAR (36)     NULL,
    [exchangerate]                         DECIMAL (28)     NULL,
    [externaluseridentifier]               NVARCHAR (50)    NULL,
    [familystatuscode]                     INT              NULL,
    [familystatuscodename]                 NVARCHAR (255)   NULL,
    [fax]                                  NVARCHAR (50)    NULL,
    [firstname]                            NVARCHAR (50)    NULL,
    [ftpsiteurl]                           NVARCHAR (200)   NULL,
    [fullname]                             NVARCHAR (160)   NULL,
    [gendercode]                           INT              NULL,
    [gendercodename]                       NVARCHAR (255)   NULL,
    [governmentid]                         NVARCHAR (50)    NULL,
    [haschildrencode]                      INT              NULL,
    [haschildrencodename]                  NVARCHAR (255)   NULL,
    [importsequencenumber]                 INT              NULL,
    [isbackofficecustomer]                 BIT              NULL,
    [isbackofficecustomername]             NVARCHAR (255)   NULL,
    [isprivatename]                        NVARCHAR (255)   NULL,
    [jobtitle]                             NVARCHAR (100)   NULL,
    [lastname]                             NVARCHAR (50)    NULL,
    [lastusedincampaign]                   DATETIME         NULL,
    [leadsourcecode]                       INT              NULL,
    [leadsourcecodename]                   NVARCHAR (255)   NULL,
    [ltf_birthyear]                        NVARCHAR (4)     NULL,
    [ltf_clubid]                           VARCHAR (36)     NULL,
    [ltf_clubidname]                       NVARCHAR (100)   NULL,
    [ltf_clubproximity]                    INT              NULL,
    [ltf_clubproximityname]                NVARCHAR (255)   NULL,
    [ltf_commitmentlevel]                  INT              NULL,
    [ltf_commitmentlevelname]              NVARCHAR (255)   NULL,
    [ltf_commitmentreason]                 NVARCHAR (4000)  NULL,
    [ltf_donotemail_address1]              BIT              NULL,
    [ltf_donotemail_address1name]          NVARCHAR (255)   NULL,
    [ltf_donotemail_address2]              BIT              NULL,
    [ltf_donotemail_address2name]          NVARCHAR (255)   NULL,
    [ltf_donotphone_mobilephone]           BIT              NULL,
    [ltf_donotphone_mobilephonename]       NVARCHAR (255)   NULL,
    [ltf_donotphone_telephone1]            BIT              NULL,
    [ltf_donotphone_telephone1name]        NVARCHAR (255)   NULL,
    [ltf_donotphone_telephone2]            BIT              NULL,
    [ltf_donotphone_telephone2name]        NVARCHAR (255)   NULL,
    [ltf_employerid]                       VARCHAR (36)     NULL,
    [ltf_employeridname]                   NVARCHAR (160)   NULL,
    [ltf_employeridyominame]               NVARCHAR (160)   NULL,
    [ltf_employerwellnessprogram]          INT              NULL,
    [ltf_employerwellnessprogramname]      NVARCHAR (255)   NULL,
    [ltf_exercisehistory]                  INT              NULL,
    [ltf_exercisehistoryname]              NVARCHAR (255)   NULL,
    [ltf_injuriesorlimitations]            BIT              NULL,
    [ltf_injuriesorlimitationsdescription] NVARCHAR (4000)  NULL,
    [ltf_injuriesorlimitationsname]        NVARCHAR (255)   NULL,
    [ltf_insertedbysystem]                 BIT              NULL,
    [ltf_insertedbysystemname]             NVARCHAR (255)   NULL,
    [ltf_isemployee]                       BIT              NULL,
    [ltf_isemployeename]                   NVARCHAR (255)   NULL,
    [ltf_leadsource]                       INT              NULL,
    [ltf_leadsourcename]                   NVARCHAR (255)   NULL,
    [ltf_leadtype]                         INT              NULL,
    [ltf_leadtypename]                     NVARCHAR (255)   NULL,
    [ltf_legacy]                           NVARCHAR (4000)  NULL,
    [ltf_measurablegoalid]                 VARCHAR (36)     NULL,
    [ltf_measurablegoalidname]             NVARCHAR (100)   NULL,
    [ltf_nugget]                           NVARCHAR (4000)  NULL,
    [ltf_pasttrainerorcoach]               BIT              NULL,
    [ltf_pasttrainerorcoachname]           NVARCHAR (255)   NULL,
    [ltf_primaryobjectiveid]               VARCHAR (36)     NULL,
    [ltf_primaryobjectiveidname]           NVARCHAR (100)   NULL,
    [ltf_referringcontactid]               VARCHAR (36)     NULL,
    [ltf_referringcontactidname]           NVARCHAR (160)   NULL,
    [ltf_referringcontactidyominame]       NVARCHAR (160)   NULL,
    [ltf_referringmemberid]                NVARCHAR (10)    NULL,
    [ltf_specificgoalid]                   VARCHAR (36)     NULL,
    [ltf_specificgoalidname]               NVARCHAR (100)   NULL,
    [ltf_timegoal]                         DATETIME         NULL,
    [ltf_todaysaction]                     INT              NULL,
    [ltf_todaysactionname]                 NVARCHAR (255)   NULL,
    [ltf_trainerorcoachpreference]         INT              NULL,
    [ltf_trainerorcoachpreferencename]     NVARCHAR (255)   NULL,
    [ltf_udwid]                            NVARCHAR (255)   NULL,
    [ltf_volatilecontact]                  BIT              NULL,
    [ltf_volatilecontactname]              NVARCHAR (255)   NULL,
    [ltf_workoutpreference]                INT              NULL,
    [ltf_workoutpreferencename]            NVARCHAR (255)   NULL,
    [managername]                          NVARCHAR (100)   NULL,
    [managerphone]                         NVARCHAR (50)    NULL,
    [mastercontactidname]                  NVARCHAR (160)   NULL,
    [mastercontactidyominame]              NVARCHAR (160)   NULL,
    [masterid]                             VARCHAR (36)     NULL,
    [merged]                               BIT              NULL,
    [mergedname]                           NVARCHAR (255)   NULL,
    [middlename]                           NVARCHAR (50)    NULL,
    [mobilephone]                          NVARCHAR (50)    NULL,
    [modifiedby]                           VARCHAR (36)     NULL,
    [modifiedbyname]                       NVARCHAR (200)   NULL,
    [modifiedbyyominame]                   NVARCHAR (200)   NULL,
    [modifiedon]                           DATETIME         NULL,
    [modifiedonbehalfby]                   VARCHAR (36)     NULL,
    [modifiedonbehalfbyname]               NVARCHAR (200)   NULL,
    [modifiedonbehalfbyyominame]           NVARCHAR (200)   NULL,
    [nickname]                             NVARCHAR (50)    NULL,
    [numberofchildren]                     INT              NULL,
    [originatingleadid]                    VARCHAR (36)     NULL,
    [originatingleadidname]                NVARCHAR (160)   NULL,
    [originatingleadidyominame]            NVARCHAR (160)   NULL,
    [overriddencreatedon]                  DATETIME         NULL,
    [ownerid]                              VARCHAR (36)     NULL,
    [owneridname]                          NVARCHAR (200)   NULL,
    [owneridtype]                          NVARCHAR (64)    NULL,
    [owneridyominame]                      NVARCHAR (200)   NULL,
    [owningbusinessunit]                   VARCHAR (36)     NULL,
    [owningteam]                           VARCHAR (36)     NULL,
    [owninguser]                           VARCHAR (36)     NULL,
    [pager]                                NVARCHAR (50)    NULL,
    [parentcontactid]                      VARCHAR (36)     NULL,
    [parentcontactidname]                  NVARCHAR (160)   NULL,
    [parentcontactidyominame]              NVARCHAR (160)   NULL,
    [parentcustomerid]                     VARCHAR (36)     NULL,
    [parentcustomeridname]                 NVARCHAR (160)   NULL,
    [parentcustomeridtype]                 NVARCHAR (64)    NULL,
    [parentcustomeridyominame]             NVARCHAR (450)   NULL,
    [participatesinworkflow]               VARCHAR (36)     NULL,
    [participatesinworkflowname]           NVARCHAR (255)   NULL,
    [paymenttermscode]                     INT              NULL,
    [paymenttermscodename]                 NVARCHAR (255)   NULL,
    [preferredappointmentdaycode]          INT              NULL,
    [preferredappointmentdaycodename]      NVARCHAR (255)   NULL,
    [preferredappointmenttimecode]         INT              NULL,
    [preferredappointmenttimecodename]     NVARCHAR (255)   NULL,
    [preferredcontactmethodcode]           INT              NULL,
    [preferredcontactmethodcodename]       NVARCHAR (255)   NULL,
    [preferredequipmentid]                 VARCHAR (36)     NULL,
    [preferredequipmentidname]             NVARCHAR (160)   NULL,
    [preferredserviceid]                   VARCHAR (36)     NULL,
    [preferredserviceidname]               NVARCHAR (160)   NULL,
    [preferredsystemuserid]                VARCHAR (36)     NULL,
    [preferredsystemuseridname]            NVARCHAR (200)   NULL,
    [preferredsystemuseridyominame]        NVARCHAR (200)   NULL,
    [processid]                            VARCHAR (36)     NULL,
    [salutation]                           NVARCHAR (100)   NULL,
    [shippingmethodcode]                   INT              NULL,
    [shippingmethodcodename]               NVARCHAR (255)   NULL,
    [spousesname]                          NVARCHAR (100)   NULL,
    [stageid]                              VARCHAR (36)     NULL,
    [statecode]                            INT              NULL,
    [statecodename]                        NVARCHAR (255)   NULL,
    [statuscode]                           INT              NULL,
    [statuscodename]                       NVARCHAR (255)   NULL,
    [suffix]                               NVARCHAR (10)    NULL,
    [telephone1]                           NVARCHAR (50)    NULL,
    [telephone2]                           NVARCHAR (50)    NULL,
    [telephone3]                           NVARCHAR (50)    NULL,
    [territorycode]                        INT              NULL,
    [territorycodename]                    NVARCHAR (255)   NULL,
    [timezoneruleversionnumber]            INT              NULL,
    [transactioncurrencyid]                VARCHAR (36)     NULL,
    [transactioncurrencyidname]            NVARCHAR (100)   NULL,
    [utcconversiontimezonecode]            INT              NULL,
    [versionnumber]                        BIGINT           NULL,
    [websiteurl]                           NVARCHAR (200)   NULL,
    [yomifirstname]                        NVARCHAR (150)   NULL,
    [yomifullname]                         NVARCHAR (450)   NULL,
    [yomilastname]                         NVARCHAR (150)   NULL,
    [yomimiddlename]                       NVARCHAR (150)   NULL,
    [InsertedDateTime]                     DATETIME         NULL,
    [InsertUser]                           VARCHAR (100)    NULL,
    [ltf_measurablegoal]                   INT              NULL,
    [ltf_measurablegoalname]               NVARCHAR (255)   NULL,
    [ltf_primaryobjective]                 INT              NULL,
    [ltf_primaryobjectivename]             NVARCHAR (255)   NULL,
    [ltf_specificgoal]                     INT              NULL,
    [ltf_specificgoalname]                 NVARCHAR (255)   NULL,
    [ltf_dncoverride]                      BIT              NULL,
    [ltf_dncoverridename]                  NVARCHAR (255)   NULL,
    [ltf_duplicateoverride]                BIT              NULL,
    [ltf_duplicateoverridename]            NVARCHAR (255)   NULL,
    [ltf_joindate]                         DATETIME         NULL,
    [ltf_memberid]                         NVARCHAR (10)    NULL,
    [ltf_membertype]                       NVARCHAR (100)   NULL,
    [ltf_riskscore]                        INT              NULL,
    [ltf_starvalue]                        INT              NULL,
    [ltf_subscriptioncancellationdate]     DATETIME         NULL,
    [ltf_subscriptioncreatedate]           DATETIME         NULL,
    [ltf_subscriptionproduct]              NVARCHAR (100)   NULL,
    [ltf_subscriptionstatus]               NVARCHAR (100)   NULL,
    [ltf_subscriptionterminationdate]      DATETIME         NULL,
    [UpdatedDateTime]                      DATETIME         NULL,
    [UpdateUser]                           VARCHAR (50)     NULL,
    [ltf_connectmemberid]                  VARCHAR (36)     NULL,
    [ltf_connectmemberidname]              NVARCHAR (150)   NULL,
    [createdbyexternalparty]               VARCHAR (36)     NULL,
    [createdbyexternalpartyname]           NVARCHAR (300)   NULL,
    [createdbyexternalpartyyominame]       NVARCHAR (300)   NULL,
    [ltf_lastcontactedby]                  VARCHAR (36)     NULL,
    [ltf_lastcontactedbyname]              NVARCHAR (200)   NULL,
    [ltf_lastcontactedbyyominame]          NVARCHAR (200)   NULL,
    [ltf_lctest]                           NVARCHAR (4000)  NULL,
    [ltf_ltbucks]                          DECIMAL (18)     NULL,
    [ltf_membertypelist]                   INT              NULL,
    [ltf_membertypelistname]               NVARCHAR (255)   NULL,
    [ltf_mobilephone_umsk]                 NVARCHAR (100)   NULL,
    [ltf_mostrecentmemberid]               NVARCHAR (9)     NULL,
    [ltf_telephone1_umsk]                  NVARCHAR (100)   NULL,
    [ltf_telephone2_umsk]                  NVARCHAR (100)   NULL,
    [ltf_yearsofmembership]                INT              NULL,
    [modifiedbyexternalparty]              VARCHAR (36)     NULL,
    [modifiedbyexternalpartyname]          NVARCHAR (300)   NULL,
    [modifiedbyexternalpartyyominame]      NVARCHAR (300)   NULL,
    [traversedpath]                        NVARCHAR (1250)  NULL,
    [business2]                            NVARCHAR (50)    NULL,
    [callback]                             NVARCHAR (50)    NULL,
    [company]                              NVARCHAR (50)    NULL,
    [home2]                                NVARCHAR (50)    NULL,
    [ltf_age]                              NVARCHAR (3)     NULL,
    [ltf_alternatefullname]                NVARCHAR (110)   NULL,
    [ltf_anniversarycall]                  DATETIME         NULL,
    [ltf_bdayyearsdifference]              DATETIME         NULL,
    [ltf_dayssincejoindate]                INT              NULL,
    [ltf_dnctemporaryreleaseexpiration]    DATETIME         NULL,
    [ltf_dndoverrideexpiration]            DATETIME         NULL,
    [ltf_emailaddress1_umsk]               NVARCHAR (110)   NULL,
    [ltf_emailaddress2_umsk]               NVARCHAR (110)   NULL,
    [address3_addressid]                   VARCHAR (36)     NULL,
    [address3_addresstypecode]             INT              NULL,
    [address3_addresstypecodename]         NVARCHAR (255)   NULL,
    [address3_city]                        NVARCHAR (80)    NULL,
    [address3_composite]                   NVARCHAR (4000)  NULL,
    [address3_country]                     NVARCHAR (80)    NULL,
    [address3_county]                      NVARCHAR (50)    NULL,
    [address3_fax]                         NVARCHAR (50)    NULL,
    [address3_freighttermscode]            INT              NULL,
    [address3_freighttermscodename]        NVARCHAR (255)   NULL,
    [address3_latitude]                    DECIMAL (26, 6)  NULL,
    [address3_line1]                       NVARCHAR (250)   NULL,
    [address3_line2]                       NVARCHAR (250)   NULL,
    [address3_line3]                       NVARCHAR (250)   NULL,
    [address3_longitude]                   DECIMAL (26, 6)  NULL,
    [address3_name]                        NVARCHAR (200)   NULL,
    [address3_postalcode]                  NVARCHAR (20)    NULL,
    [address3_postofficebox]               NVARCHAR (20)    NULL,
    [address3_primarycontactname]          NVARCHAR (100)   NULL,
    [address3_shippingmethodcode]          INT              NULL,
    [address3_shippingmethodcodename]      NVARCHAR (255)   NULL,
    [address3_stateorprovince]             NVARCHAR (50)    NULL,
    [address3_telephone1]                  NVARCHAR (50)    NULL,
    [address3_telephone2]                  NVARCHAR (50)    NULL,
    [address3_telephone3]                  NVARCHAR (50)    NULL,
    [address3_upszone]                     NVARCHAR (4)     NULL,
    [address3_utcoffset]                   INT              NULL,
    [ltf_calculatedage]                    INT              NULL,
    [ltf_dncdneupdatetriggeredby]          INT              NULL,
    [ltf_dncdneupdatetriggeredbyname]      NVARCHAR (255)   NULL,
    [ltf_islifetimecloseto]                INT              NULL,
    [ltf_islifetimeclosetoname]            NVARCHAR (255)   NULL,
    [ltf_ltfpartyid]                       NVARCHAR (10)    NULL,
    [ltf_selectedinterestids]              NVARCHAR (1000)  NULL,
    [dv_batch_id]                          BIGINT           NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

