CREATE TABLE [dbo].[stage_crmcloudsync_Opportunity] (
    [stage_crmcloudsync_Opportunity_id]    BIGINT          NOT NULL,
    [accountid]                            VARCHAR (36)    NULL,
    [accountidname]                        NVARCHAR (160)  NULL,
    [accountidyominame]                    NVARCHAR (160)  NULL,
    [actualclosedate]                      DATETIME        NULL,
    [actualvalue]                          DECIMAL (26, 6) NULL,
    [actualvalue_base]                     DECIMAL (26, 6) NULL,
    [budgetamount]                         DECIMAL (26, 6) NULL,
    [budgetamount_base]                    DECIMAL (26, 6) NULL,
    [budgetstatus]                         INT             NULL,
    [budgettypename]                       NVARCHAR (255)  NULL,
    [campaignid]                           VARCHAR (36)    NULL,
    [campaignidname]                       NVARCHAR (128)  NULL,
    [captureproposalfeedback]              BIT             NULL,
    [captureproposalfeedbackname]          NVARCHAR (255)  NULL,
    [closeprobability]                     INT             NULL,
    [completefinalproposal]                BIT             NULL,
    [completefinalproposalname]            NVARCHAR (255)  NULL,
    [completeinternalreview]               BIT             NULL,
    [completeinternalreviewname]           NVARCHAR (255)  NULL,
    [confirminterest]                      BIT             NULL,
    [confirminterestname]                  NVARCHAR (255)  NULL,
    [contactid]                            VARCHAR (36)    NULL,
    [contactidname]                        NVARCHAR (160)  NULL,
    [contactidyominame]                    NVARCHAR (160)  NULL,
    [createdby]                            VARCHAR (36)    NULL,
    [createdbyname]                        NVARCHAR (200)  NULL,
    [createdbyyominame]                    NVARCHAR (200)  NULL,
    [createdon]                            DATETIME        NULL,
    [createdonbehalfby]                    VARCHAR (36)    NULL,
    [createdonbehalfbyname]                NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]            NVARCHAR (200)  NULL,
    [currentsituation]                     NVARCHAR (4000) NULL,
    [customerid]                           VARCHAR (36)    NULL,
    [customeridname]                       NVARCHAR (160)  NULL,
    [customeridtype]                       NVARCHAR (64)   NULL,
    [customeridyominame]                   NVARCHAR (450)  NULL,
    [customerneed]                         NVARCHAR (4000) NULL,
    [customerpainpoints]                   NVARCHAR (4000) NULL,
    [decisionmaker]                        BIT             NULL,
    [decisionmakername]                    NVARCHAR (255)  NULL,
    [description]                          NVARCHAR (4000) NULL,
    [developproposal]                      BIT             NULL,
    [developproposalname]                  NVARCHAR (255)  NULL,
    [discountamount]                       DECIMAL (26, 6) NULL,
    [discountamount_base]                  DECIMAL (26, 6) NULL,
    [discountpercentage]                   DECIMAL (28)    NULL,
    [estimatedclosedate]                   DATETIME        NULL,
    [estimatedvalue]                       DECIMAL (26, 6) NULL,
    [estimatedvalue_base]                  DECIMAL (26, 6) NULL,
    [evaluatefit]                          BIT             NULL,
    [evaluatefitname]                      NVARCHAR (255)  NULL,
    [exchangerate]                         DECIMAL (28)    NULL,
    [filedebrief]                          BIT             NULL,
    [filedebriefname]                      NVARCHAR (255)  NULL,
    [finaldecisiondate]                    DATETIME        NULL,
    [freightamount]                        DECIMAL (26, 6) NULL,
    [freightamount_base]                   DECIMAL (26, 6) NULL,
    [identifycompetitors]                  BIT             NULL,
    [identifycompetitorsname]              NVARCHAR (255)  NULL,
    [identifycustomercontacts]             BIT             NULL,
    [identifycustomercontactsname]         NVARCHAR (255)  NULL,
    [identifypursuitteam]                  BIT             NULL,
    [identifypursuitteamname]              NVARCHAR (255)  NULL,
    [importsequencenumber]                 INT             NULL,
    [initialcommunication]                 INT             NULL,
    [initialcommunicationname]             NVARCHAR (255)  NULL,
    [isprivatename]                        NVARCHAR (255)  NULL,
    [isrevenuesystemcalculated]            BIT             NULL,
    [isrevenuesystemcalculatedname]        NVARCHAR (255)  NULL,
    [ltf_besttimetocontact]                INT             NULL,
    [ltf_besttimetocontactname]            NVARCHAR (255)  NULL,
    [ltf_clubid]                           VARCHAR (36)    NULL,
    [ltf_clubidname]                       NVARCHAR (100)  NULL,
    [ltf_clubproximity]                    INT             NULL,
    [ltf_clubproximityname]                NVARCHAR (255)  NULL,
    [ltf_commitmentlevel]                  INT             NULL,
    [ltf_commitmentlevelname]              NVARCHAR (255)  NULL,
    [ltf_commitmentreason]                 NVARCHAR (4000) NULL,
    [ltf_employerwellnessprogram]          INT             NULL,
    [ltf_employerwellnessprogramname]      NVARCHAR (255)  NULL,
    [ltf_exercisehistory]                  INT             NULL,
    [ltf_exercisehistoryname]              NVARCHAR (255)  NULL,
    [ltf_imsjoinlink]                      NVARCHAR (300)  NULL,
    [ltf_injuriesorlimitations]            BIT             NULL,
    [ltf_injuriesorlimitationsdescription] NVARCHAR (4000) NULL,
    [ltf_injuriesorlimitationsname]        NVARCHAR (255)  NULL,
    [ltf_inquirytype]                      NVARCHAR (100)  NULL,
    [ltf_lastactivity]                     DATETIME        NULL,
    [ltf_leadsource]                       INT             NULL,
    [ltf_leadsourcename]                   NVARCHAR (255)  NULL,
    [ltf_leadtype]                         INT             NULL,
    [ltf_leadtypename]                     NVARCHAR (255)  NULL,
    [ltf_manageduntil]                     DATETIME        NULL,
    [ltf_measurablegoal]                   INT             NULL,
    [ltf_measurablegoalid]                 VARCHAR (36)    NULL,
    [ltf_measurablegoalidname]             NVARCHAR (100)  NULL,
    [ltf_measurablegoalname]               NVARCHAR (255)  NULL,
    [ltf_membershipinforequested]          NVARCHAR (50)   NULL,
    [ltf_membershiplevel]                  INT             NULL,
    [ltf_membershiplevelname]              NVARCHAR (255)  NULL,
    [ltf_membershiptype]                   INT             NULL,
    [ltf_membershiptypename]               NVARCHAR (255)  NULL,
    [ltf_nugget]                           NVARCHAR (4000) NULL,
    [ltf_park]                             BIT             NULL,
    [ltf_parkcomments]                     NVARCHAR (400)  NULL,
    [ltf_parkname]                         NVARCHAR (255)  NULL,
    [ltf_parkreason]                       INT             NULL,
    [ltf_parkreasonname]                   NVARCHAR (255)  NULL,
    [ltf_parkuntil]                        DATETIME        NULL,
    [ltf_pasttrainerorcoach]               BIT             NULL,
    [ltf_pasttrainerorcoachname]           NVARCHAR (255)  NULL,
    [ltf_primaryobjective]                 INT             NULL,
    [ltf_primaryobjectiveid]               VARCHAR (36)    NULL,
    [ltf_primaryobjectiveidname]           NVARCHAR (100)  NULL,
    [ltf_primaryobjectivename]             NVARCHAR (255)  NULL,
    [ltf_promocode]                        NVARCHAR (100)  NULL,
    [ltf_prospecttype]                     INT             NULL,
    [ltf_prospecttypename]                 NVARCHAR (255)  NULL,
    [ltf_referringcontactid]               VARCHAR (36)    NULL,
    [ltf_referringcontactidname]           NVARCHAR (160)  NULL,
    [ltf_referringcontactidyominame]       NVARCHAR (160)  NULL,
    [ltf_referringmemberid]                NVARCHAR (10)   NULL,
    [ltf_registrationcode]                 NVARCHAR (100)  NULL,
    [ltf_requesttype]                      NVARCHAR (100)  NULL,
    [ltf_specificgoal]                     INT             NULL,
    [ltf_specificgoalid]                   VARCHAR (36)    NULL,
    [ltf_specificgoalidname]               NVARCHAR (100)  NULL,
    [ltf_specificgoalname]                 NVARCHAR (255)  NULL,
    [ltf_timegoal]                         DATETIME        NULL,
    [ltf_todaysaction]                     INT             NULL,
    [ltf_todaysactionname]                 NVARCHAR (255)  NULL,
    [ltf_trainerorcoachpreference]         INT             NULL,
    [ltf_trainerorcoachpreferencename]     NVARCHAR (255)  NULL,
    [ltf_webteamid]                        VARCHAR (36)    NULL,
    [ltf_webteamidname]                    NVARCHAR (160)  NULL,
    [ltf_webteamidyominame]                NVARCHAR (160)  NULL,
    [ltf_workoutpreference]                INT             NULL,
    [ltf_workoutpreferencename]            NVARCHAR (255)  NULL,
    [modifiedby]                           VARCHAR (36)    NULL,
    [modifiedbyname]                       NVARCHAR (200)  NULL,
    [modifiedbyyominame]                   NVARCHAR (200)  NULL,
    [modifiedon]                           DATETIME        NULL,
    [modifiedonbehalfby]                   VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]               NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]           NVARCHAR (200)  NULL,
    [name]                                 NVARCHAR (300)  NULL,
    [need]                                 INT             NULL,
    [needname]                             NVARCHAR (255)  NULL,
    [opportunityid]                        VARCHAR (36)    NULL,
    [opportunityratingcode]                INT             NULL,
    [opportunityratingcodename]            NVARCHAR (255)  NULL,
    [originatingleadid]                    VARCHAR (36)    NULL,
    [originatingleadidname]                NVARCHAR (160)  NULL,
    [originatingleadidyominame]            NVARCHAR (160)  NULL,
    [overriddencreatedon]                  DATETIME        NULL,
    [ownerid]                              VARCHAR (36)    NULL,
    [owneridname]                          NVARCHAR (200)  NULL,
    [owneridtype]                          NVARCHAR (64)   NULL,
    [owneridyominame]                      NVARCHAR (200)  NULL,
    [owningbusinessunit]                   VARCHAR (36)    NULL,
    [owningteam]                           VARCHAR (36)    NULL,
    [owninguser]                           VARCHAR (36)    NULL,
    [parentaccountid]                      VARCHAR (36)    NULL,
    [parentaccountidname]                  NVARCHAR (160)  NULL,
    [parentaccountidyominame]              NVARCHAR (160)  NULL,
    [parentcontactid]                      VARCHAR (36)    NULL,
    [parentcontactidname]                  NVARCHAR (160)  NULL,
    [parentcontactidyominame]              NVARCHAR (160)  NULL,
    [participatesinworkflow]               BIT             NULL,
    [participatesinworkflowname]           NVARCHAR (255)  NULL,
    [presentfinalproposal]                 BIT             NULL,
    [presentfinalproposalname]             NVARCHAR (255)  NULL,
    [presentproposal]                      BIT             NULL,
    [presentproposalname]                  NVARCHAR (255)  NULL,
    [pricelevelid]                         VARCHAR (36)    NULL,
    [pricelevelidname]                     NVARCHAR (100)  NULL,
    [pricingerrorcode]                     INT             NULL,
    [pricingerrorcodename]                 NVARCHAR (255)  NULL,
    [prioritycode]                         INT             NULL,
    [prioritycodename]                     NVARCHAR (255)  NULL,
    [processid]                            VARCHAR (36)    NULL,
    [proposedsolution]                     NVARCHAR (4000) NULL,
    [purchaseprocess]                      INT             NULL,
    [purchaseprocessname]                  NVARCHAR (255)  NULL,
    [purchasetimeframe]                    INT             NULL,
    [purchasetimeframename]                NVARCHAR (255)  NULL,
    [pursuitdecision]                      BIT             NULL,
    [pursuitdecisionname]                  NVARCHAR (255)  NULL,
    [qualificationcomments]                NVARCHAR (4000) NULL,
    [quotecomments]                        NVARCHAR (4000) NULL,
    [resolvefeedback]                      BIT             NULL,
    [resolvefeedbackname]                  NVARCHAR (255)  NULL,
    [salesstage]                           INT             NULL,
    [salesstagecode]                       INT             NULL,
    [salesstagecodename]                   NVARCHAR (255)  NULL,
    [salesstagename]                       NVARCHAR (255)  NULL,
    [schedulefollowup_prospect]            DATETIME        NULL,
    [schedulefollowup_qualify]             DATETIME        NULL,
    [scheduleproposalmeeting]              DATETIME        NULL,
    [sendthankyounote]                     BIT             NULL,
    [sendthankyounotename]                 NVARCHAR (255)  NULL,
    [stageid]                              VARCHAR (36)    NULL,
    [statecode]                            INT             NULL,
    [statecodename]                        NVARCHAR (255)  NULL,
    [statuscode]                           INT             NULL,
    [statuscodename]                       NVARCHAR (255)  NULL,
    [stepid]                               VARCHAR (36)    NULL,
    [stepname]                             NVARCHAR (200)  NULL,
    [timeline]                             INT             NULL,
    [timelinename]                         NVARCHAR (255)  NULL,
    [timezoneruleversionnumber]            INT             NULL,
    [totalamount]                          DECIMAL (26, 6) NULL,
    [totalamount_base]                     DECIMAL (26, 6) NULL,
    [totalamountlessfreight]               DECIMAL (26, 6) NULL,
    [totalamountlessfreight_base]          DECIMAL (26, 6) NULL,
    [totaldiscountamount]                  DECIMAL (26, 6) NULL,
    [totaldiscountamount_base]             DECIMAL (26, 6) NULL,
    [totallineitemamount]                  DECIMAL (26, 6) NULL,
    [totallineitemamount_base]             DECIMAL (26, 6) NULL,
    [totallineitemdiscountamount]          DECIMAL (26, 6) NULL,
    [totallineitemdiscountamount_base]     DECIMAL (26, 6) NULL,
    [totaltax]                             DECIMAL (26, 6) NULL,
    [totaltax_base]                        DECIMAL (26, 6) NULL,
    [transactioncurrencyid]                VARCHAR (36)    NULL,
    [transactioncurrencyidname]            NVARCHAR (100)  NULL,
    [utcconversiontimezonecode]            INT             NULL,
    [versionnumber]                        BIGINT          NULL,
    [InsertedDateTime]                     DATETIME        NULL,
    [InsertUser]                           VARCHAR (100)   NULL,
    [UpdatedDateTime]                      DATETIME        NULL,
    [UpdateUser]                           VARCHAR (50)    NULL,
    [ltf_profilenotes]                     NVARCHAR (4000) NULL,
    [ltf_Programsofinterest]               INT             NULL,
    [ltf_Programsofinterestname]           NVARCHAR (255)  NULL,
    [ltf_visitorid]                        NVARCHAR (100)  NULL,
    [ltf_wanttodo]                         INT             NULL,
    [ltf_wanttodoname]                     NVARCHAR (255)  NULL,
    [ltf_whywanttodo]                      INT             NULL,
    [ltf_whywanttodoname]                  NVARCHAR (255)  NULL,
    [ltf_whometwith]                       NVARCHAR (100)  NULL,
    [ltf_recommendedmembership]            INT             NULL,
    [ltf_recommendedmembershipname]        NVARCHAR (255)  NULL,
    [ltf_resistance]                       INT             NULL,
    [ltf_resistancename]                   NVARCHAR (255)  NULL,
    [traversedpath]                        NVARCHAR (1250) NULL,
    [ltf_webtransfermethod]                INT             NULL,
    [ltf_webtransfermethodname]            NVARCHAR (255)  NULL,
    [ltf_basketball]                       INT             NULL,
    [ltf_climbing]                         INT             NULL,
    [ltf_commitment]                       INT             NULL,
    [ltf_cycling]                          INT             NULL,
    [ltf_guestpassexpirationdate]          DATETIME        NULL,
    [ltf_kidsclub]                         BIT             NULL,
    [ltf_kidsclubname]                     NVARCHAR (255)  NULL,
    [ltf_nextfollowup]                     DATETIME        NULL,
    [ltf_personaltraining]                 BIT             NULL,
    [ltf_personaltrainingname]             NVARCHAR (255)  NULL,
    [ltf_readytojoin]                      BIT             NULL,
    [ltf_readytojoinname]                  NVARCHAR (255)  NULL,
    [ltf_signature]                        VARCHAR (8000)  NULL,
    [ltf_swimming]                         BIT             NULL,
    [ltf_swimmingname]                     NVARCHAR (255)  NULL,
    [ltf_tennislessons]                    BIT             NULL,
    [ltf_tennislessonsname]                NVARCHAR (255)  NULL,
    [ltf_yoga]                             INT             NULL,
    [ltf_assignedbyapp]                    INT             NULL,
    [ltf_assignedbyappname]                NVARCHAR (255)  NULL,
    [ltf_assignedtoclubdate]               DATETIME        NULL,
    [ltf_imsjoinsenddate]                  DATETIME        NULL,
    [ltf_isimsjoin]                        BIT             NULL,
    [ltf_isimsjoinname]                    NVARCHAR (255)  NULL,
    [ltf_numberover14list]                 INT             NULL,
    [ltf_numberover14listname]             NVARCHAR (255)  NULL,
    [ltf_numberunder14list]                INT             NULL,
    [ltf_numberunder14listname]            NVARCHAR (255)  NULL,
    [ltf_promoquoted]                      NVARCHAR (100)  NULL,
    [ltf_selectedinterestids]              NVARCHAR (1000) NULL,
    [ltf_originatingguestvisit]            VARCHAR (36)    NULL,
    [ltf_originatingguestvisitname]        NVARCHAR (200)  NULL,
    [ltf_assignmentrequestdate]            DATETIME        NULL,
    [ltf_assignmentrequestid]              NVARCHAR (100)  NULL,
    [ltf_lineofbusiness]                   INT             NULL,
    [ltf_channel]                          INT             NULL,
    [ltf_lineofbusinessname]               NVARCHAR (255)  NULL,
    [ltf_channelname]                      NVARCHAR (255)  NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

