CREATE TABLE [dbo].[stage_hybris_ECommercePaymentBreakdown] (
    [stage_hybris_ECommercePaymentBreakdown_id] BIGINT          NOT NULL,
    [AccountSet]                                VARCHAR (255)   NULL,
    [LineCompany]                               VARCHAR (255)   NULL,
    [LedgerAccount]                             VARCHAR (255)   NULL,
    [WorkdayRegion]                             VARCHAR (4)     NULL,
    [ClubID]                                    INT             NULL,
    [CostCenter]                                VARCHAR (255)   NULL,
    [OfferingID]                                VARCHAR (255)   NULL,
    [SpendCategory]                             VARCHAR (255)   NULL,
    [RevenueCategory]                           VARCHAR (255)   NULL,
    [MerchantLocation]                          VARCHAR (255)   NULL,
    [order_num]                                 VARCHAR (255)   NULL,
    [oe_num]                                    INT             NULL,
    [SubCatName]                                VARCHAR (255)   NULL,
    [ProductID]                                 VARCHAR (255)   NULL,
    [ProductName]                               VARCHAR (255)   NULL,
    [MMSProductID]                              INT             NULL,
    [DeliveryState]                             VARCHAR (255)   NULL,
    [Tax]                                       DECIMAL (26, 6) NULL,
    [Shipping]                                  DECIMAL (26, 6) NULL,
    [OrdDate]                                   VARCHAR (29)    NULL,
    [tran_date]                                 VARCHAR (29)    NULL,
    [ShipDate]                                  VARCHAR (29)    NULL,
    [MMSTransactionID]                          VARCHAR (255)   NULL,
    [MMSPackageID]                              INT             NULL,
    [MemberID]                                  VARCHAR (255)   NULL,
    [Capture_LTBUCKS]                           DECIMAL (10, 2) NULL,
    [Capture_amex]                              DECIMAL (10, 2) NULL,
    [Capture_discover]                          DECIMAL (10, 2) NULL,
    [Capture_master]                            DECIMAL (10, 2) NULL,
    [Capture_visa]                              DECIMAL (10, 2) NULL,
    [Capture_PAYPAL]                            DECIMAL (10, 2) NULL,
    [Refund_LTBUCKS]                            DECIMAL (10, 2) NULL,
    [Refund_amex]                               DECIMAL (10, 2) NULL,
    [Refund_discover]                           DECIMAL (10, 2) NULL,
    [Refund_master]                             DECIMAL (10, 2) NULL,
    [Refund_visa]                               DECIMAL (10, 2) NULL,
    [Refund_PAYPAL]                             DECIMAL (10, 2) NULL,
    [ReportStartDate]                           DATETIME        NULL,
    [ReportEndDate]                             DATETIME        NULL,
    [jan_one]                                   DATETIME        NULL,
    [dv_batch_id]                               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

