CREATE TABLE [dbo].[stage_hash_sfmc_content_details_log] (
    [stage_hash_sfmc_content_details_log_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)      NOT NULL,
    [ContentID]                              VARCHAR (4000) NULL,
    [Section]                                VARCHAR (4000) NULL,
    [Priority]                               VARCHAR (4000) NULL,
    [SubjectLine]                            VARCHAR (4000) NULL,
    [Headline]                               VARCHAR (4000) NULL,
    [Body]                                   VARCHAR (4000) NULL,
    [ImageURL]                               VARCHAR (4000) NULL,
    [CTA_Text]                               VARCHAR (4000) NULL,
    [CTA_URL]                                VARCHAR (4000) NULL,
    [MembershipType]                         VARCHAR (4000) NULL,
    [ClubIDs]                                VARCHAR (4000) NULL,
    [Interests]                              VARCHAR (4000) NULL,
    [LTBucks]                                VARCHAR (4000) NULL,
    [WLChallenge]                            VARCHAR (4000) NULL,
    [KidsChoice]                             VARCHAR (4000) NULL,
    [AdditionalLogic]                        VARCHAR (4000) NULL,
    [ContentType]                            VARCHAR (4000) NULL,
    [ET_InsertedDateTime]                    DATETIME       NULL,
    [ContentGUID]                            VARCHAR (4000) NULL,
    [EventDate]                              DATETIME       NULL,
    [CompanyInside]                          VARCHAR (4000) NULL,
    [Subhead]                                VARCHAR (4000) NULL,
    [interest_id]                            VARCHAR (4000) NULL,
    [NotificationType]                       VARCHAR (4000) NULL,
    [NotificationTypeID]                     VARCHAR (4000) NULL,
    [Channel]                                VARCHAR (4000) NULL,
    [Gender]                                 VARCHAR (4000) NULL,
    [CreatedBy]                              VARCHAR (4000) NULL,
    [UpdatedBy]                              VARCHAR (4000) NULL,
    [InternalNotes]                          VARCHAR (4000) NULL,
    [CreatedDateTime]                        DATETIME       NULL,
    [LastUpdatedDateTime]                    DATETIME       NULL,
    [PublishDateTime]                        DATETIME       NULL,
    [SwipeStartDate]                         DATETIME       NULL,
    [ActiveJuniorFlag]                       VARCHAR (4000) NULL,
    [ChildCenterSwipedFlag]                  VARCHAR (4000) NULL,
    [MessageActiveFlag]                      VARCHAR (4000) NULL,
    [ExpirationDateTime]                     DATETIME       NULL,
    [Category]                               VARCHAR (4000) NULL,
    [dv_load_date_time]                      DATETIME       NOT NULL,
    [dv_batch_id]                            BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

