CREATE TABLE [dbo].[stage_hash_hybris_ALL_PRODUCTS] (
    [stage_hash_hybris_ALL_PRODUCTS_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                           CHAR (32)       NOT NULL,
    [createdTS]                         DATETIME        NULL,
    [creationTime]                      DATETIME        NULL,
    [code]                              NVARCHAR (258)  NULL,
    [name]                              NVARCHAR (1545) NULL,
    [onlineDatetime]                    DATETIME        NULL,
    [offlineDatetime]                   DATETIME        NULL,
    [summary]                           NVARCHAR (4000) NULL,
    [description]                       NVARCHAR (4000) NULL,
    [weight]                            DECIMAL (26, 6) NULL,
    [modifiedTime]                      DATETIME        NULL,
    [caption]                           NVARCHAR (255)  NULL,
    [ean]                               NVARCHAR (255)  NULL,
    [productCost]                       DECIMAL (26, 6) NULL,
    [productHeight]                     DECIMAL (26, 6) NULL,
    [productWidth]                      DECIMAL (26, 6) NULL,
    [productLength]                     DECIMAL (26, 6) NULL,
    [autoShipFlag]                      TINYINT         NULL,
    [electronicShippingFlag]            TINYINT         NULL,
    [fulfillmentPartner]                NVARCHAR (255)  NULL,
    [ltfOnlyProduct]                    TINYINT         NULL,
    [ltfOfferFlag]                      TINYINT         NULL,
    [offerExternalLinkFlag]             TINYINT         NULL,
    [eGiftCardFlag]                     TINYINT         NULL,
    [offerLink]                         NVARCHAR (1000) NULL,
    [catalogVersion]                    BIGINT          NULL,
    [activeCatalogVersion]              BIGINT          NULL,
    [catalogName]                       NVARCHAR (200)  NULL,
    [catalogVersionName]                NVARCHAR (255)  NULL,
    [productCategory]                   NVARCHAR (1545) NULL,
    [productSubCategory]                NVARCHAR (1545) NULL,
    [productType]                       VARCHAR (18)    NULL,
    [productStockLevel]                 INT             NULL,
    [productStockStatus]                NVARCHAR (255)  NULL,
    [LTBUCKSearned]                     DECIMAL (26, 6) NULL,
    [AcceptLTBUCKSflag]                 TINYINT         NULL,
    [dv_load_date_time]                 DATETIME        NOT NULL,
    [dv_updated_date_time]              DATETIME        NULL,
    [dv_update_user]                    VARCHAR (50)    NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

