CREATE TABLE [dbo].[stage_crmcloudsync_ltf_livechat] (
    [stage_crmcloudsync_ltf_livechat_id] BIGINT          NOT NULL,
    [activityadditionalparams]           VARCHAR (8000)  NULL,
    [activityid]                         VARCHAR (36)    NULL,
    [activitytypecode]                   NVARCHAR (64)   NULL,
    [activitytypecodename]               NVARCHAR (255)  NULL,
    [actualdurationminutes]              INT             NULL,
    [actualend]                          DATETIME        NULL,
    [actualstart]                        DATETIME        NULL,
    [bcc]                                VARCHAR (8000)  NULL,
    [cc]                                 VARCHAR (8000)  NULL,
    [community]                          INT             NULL,
    [communityname]                      NVARCHAR (255)  NULL,
    [createdby]                          VARCHAR (36)    NULL,
    [createdbyname]                      NVARCHAR (200)  NULL,
    [createdbyyominame]                  NVARCHAR (200)  NULL,
    [createdon]                          DATETIME        NULL,
    [createdonbehalfby]                  VARCHAR (36)    NULL,
    [createdonbehalfbyname]              NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]          NVARCHAR (200)  NULL,
    [customers]                          VARCHAR (8000)  NULL,
    [deliverylastattemptedon]            DATETIME        NULL,
    [deliveryprioritycode]               INT             NULL,
    [deliveryprioritycodename]           NVARCHAR (255)  NULL,
    [description]                        VARCHAR (8000)  NULL,
    [exchangeitemid]                     NVARCHAR (200)  NULL,
    [exchangerate]                       DECIMAL (28)    NULL,
    [exchangeweblink]                    NVARCHAR (1250) NULL,
    [from]                               VARCHAR (8000)  NULL,
    [importsequencenumber]               INT             NULL,
    [instancetypecode]                   INT             NULL,
    [instancetypecodename]               NVARCHAR (255)  NULL,
    [isbilled]                           VARCHAR (36)    NULL,
    [isbilledname]                       NVARCHAR (255)  NULL,
    [ismapiprivate]                      VARCHAR (36)    NULL,
    [ismapiprivatename]                  NVARCHAR (255)  NULL,
    [isregularactivity]                  VARCHAR (36)    NULL,
    [isregularactivityname]              NVARCHAR (255)  NULL,
    [isworkflowcreated]                  VARCHAR (36)    NULL,
    [isworkflowcreatedname]              NVARCHAR (255)  NULL,
    [lastonholdtime]                     DATETIME        NULL,
    [leftvoicemail]                      VARCHAR (36)    NULL,
    [leftvoicemailname]                  NVARCHAR (255)  NULL,
    [ltf_appointmentstart]               DATETIME        NULL,
    [ltf_appointmentsubject]             NVARCHAR (200)  NULL,
    [ltf_chatwrapup]                     INT             NULL,
    [ltf_chatwrapupname]                 NVARCHAR (255)  NULL,
    [ltf_club]                           VARCHAR (36)    NULL,
    [ltf_clubname]                       NVARCHAR (100)  NULL,
    [ltf_disqualifyreason]               INT             NULL,
    [ltf_disqualifyreasonname]           NVARCHAR (255)  NULL,
    [ltf_emailaddress1]                  NVARCHAR (100)  NULL,
    [ltf_employeeid]                     NVARCHAR (50)   NULL,
    [ltf_firstname]                      NVARCHAR (50)   NULL,
    [ltf_imspromo]                       NVARCHAR (50)   NULL,
    [ltf_lastname]                       NVARCHAR (50)   NULL,
    [ltf_membershiplevel]                INT             NULL,
    [ltf_membershiplevelname]            NVARCHAR (255)  NULL,
    [ltf_mmsclubid]                      NVARCHAR (50)   NULL,
    [ltf_notes]                          NVARCHAR (2000) NULL,
    [ltf_originallead]                   VARCHAR (36)    NULL,
    [ltf_originalleadname]               NVARCHAR (160)  NULL,
    [ltf_originalleadyominame]           NVARCHAR (160)  NULL,
    [ltf_parkuntil]                      DATETIME        NULL,
    [ltf_phone]                          NVARCHAR (50)   NULL,
    [ltf_proactiveorreactive]            INT             NULL,
    [ltf_proactiveorreactivename]        NVARCHAR (255)  NULL,
    [ltf_readytoprocess]                 VARCHAR (36)    NULL,
    [ltf_readytoprocessname]             NVARCHAR (255)  NULL,
    [ltf_recommendedmembership]          INT             NULL,
    [ltf_recommendedmembershipname]      NVARCHAR (255)  NULL,
    [ltf_referringurl]                   NVARCHAR (4000) NULL,
    [ltf_requestdate]                    DATETIME        NULL,
    [ltf_requestid]                      NVARCHAR (100)  NULL,
    [ltf_routingmessage]                 NVARCHAR (512)  NULL,
    [ltf_routingstep]                    INT             NULL,
    [ltf_routingstepname]                NVARCHAR (255)  NULL,
    [ltf_sendimsjoin]                    VARCHAR (36)    NULL,
    [ltf_sendimsjoinname]                NVARCHAR (255)  NULL,
    [ltf_serviceline]                    NVARCHAR (50)   NULL,
    [ltf_transcript]                     VARCHAR (8000)  NULL,
    [ltf_type]                           INT             NULL,
    [ltf_typename]                       NVARCHAR (255)  NULL,
    [ltf_webteam]                        VARCHAR (36)    NULL,
    [ltf_webteamname]                    NVARCHAR (160)  NULL,
    [ltf_webteamyominame]                NVARCHAR (160)  NULL,
    [modifiedby]                         VARCHAR (36)    NULL,
    [modifiedbyname]                     NVARCHAR (200)  NULL,
    [modifiedbyyominame]                 NVARCHAR (200)  NULL,
    [modifiedon]                         DATETIME        NULL,
    [modifiedonbehalfby]                 VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]             NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]         NVARCHAR (200)  NULL,
    [onholdtime]                         INT             NULL,
    [optionalattendees]                  VARCHAR (8000)  NULL,
    [organizer]                          VARCHAR (8000)  NULL,
    [overriddencreatedon]                DATETIME        NULL,
    [ownerid]                            VARCHAR (36)    NULL,
    [owneridname]                        NVARCHAR (200)  NULL,
    [owneridtype]                        NVARCHAR (64)   NULL,
    [owneridyominame]                    NVARCHAR (200)  NULL,
    [owningbusinessunit]                 VARCHAR (36)    NULL,
    [owningteam]                         VARCHAR (36)    NULL,
    [owninguser]                         VARCHAR (36)    NULL,
    [partners]                           VARCHAR (8000)  NULL,
    [postponeactivityprocessinguntil]    DATETIME        NULL,
    [prioritycode]                       INT             NULL,
    [prioritycodename]                   NVARCHAR (255)  NULL,
    [processid]                          VARCHAR (36)    NULL,
    [regardingobjectid]                  VARCHAR (36)    NULL,
    [regardingobjectidname]              NVARCHAR (4000) NULL,
    [regardingobjectidyominame]          NVARCHAR (4000) NULL,
    [regardingobjecttypecode]            NVARCHAR (64)   NULL,
    [requiredattendees]                  VARCHAR (8000)  NULL,
    [resources]                          VARCHAR (8000)  NULL,
    [scheduleddurationminutes]           INT             NULL,
    [scheduledend]                       DATETIME        NULL,
    [scheduledstart]                     DATETIME        NULL,
    [sendermailboxid]                    VARCHAR (36)    NULL,
    [sendermailboxidname]                NVARCHAR (200)  NULL,
    [senton]                             DATETIME        NULL,
    [seriesid]                           VARCHAR (36)    NULL,
    [serviceid]                          VARCHAR (36)    NULL,
    [serviceidname]                      NVARCHAR (160)  NULL,
    [slaid]                              VARCHAR (36)    NULL,
    [slainvokedid]                       VARCHAR (36)    NULL,
    [slainvokedidname]                   NVARCHAR (100)  NULL,
    [slaname]                            NVARCHAR (100)  NULL,
    [sortdate]                           DATETIME        NULL,
    [stageid]                            VARCHAR (36)    NULL,
    [statecode]                          INT             NULL,
    [statecodename]                      NVARCHAR (255)  NULL,
    [statuscode]                         INT             NULL,
    [statuscodename]                     NVARCHAR (255)  NULL,
    [subject]                            NVARCHAR (200)  NULL,
    [timezoneruleversionnumber]          INT             NULL,
    [to]                                 VARCHAR (8000)  NULL,
    [transactioncurrencyid]              VARCHAR (36)    NULL,
    [transactioncurrencyidname]          NVARCHAR (100)  NULL,
    [traversedpath]                      NVARCHAR (1250) NULL,
    [utcconversiontimezonecode]          INT             NULL,
    [versionnumber]                      BIGINT          NULL,
    [InsertedDateTime]                   DATETIME        NULL,
    [InsertUser]                         VARCHAR (50)    NULL,
    [UpdatedDateTime]                    DATETIME        NULL,
    [UpdateUser]                         VARCHAR (50)    NULL,
    [ltf_mostrecentcasl]                 DATETIME        NULL,
    [ltf_lineofbusiness]                 INT             NULL,
    [ltf_lineofbusinessname]             NVARCHAR (255)  NULL,
    [dv_batch_id]                        BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

