CREATE TABLE [dbo].[stage_ig_it_cfg_menu_item_master] (
    [stage_ig_it_cfg_menu_item_master_id] BIGINT          NOT NULL,
    [ent_id]                              INT             NULL,
    [menu_item_id]                        INT             NULL,
    [menu_item_name]                      NVARCHAR (50)   NULL,
    [menu_item_abbr1]                     NVARCHAR (20)   NULL,
    [menu_item_abbr2]                     NVARCHAR (20)   NULL,
    [mi_kp_label]                         NVARCHAR (16)   NULL,
    [prod_class_id]                       INT             NULL,
    [rev_cat_id]                          INT             NULL,
    [tax_grp_id]                          INT             NULL,
    [rpt_cat_id]                          INT             NULL,
    [mi_sec_id]                           INT             NULL,
    [open_modifier_flag]                  BIT             NULL,
    [mi_open_price_prompt]                BIT             NULL,
    [mi_not_active_flag]                  BIT             NULL,
    [mi_weight_flag]                      BIT             NULL,
    [mi_weight_tare]                      DECIMAL (26, 6) NULL,
    [mi_discountable_flag]                BIT             NULL,
    [mi_emp_discountable_flag]            BIT             NULL,
    [mi_voidable_flag]                    BIT             NULL,
    [mi_print_flag]                       BIT             NULL,
    [sku_no]                              NVARCHAR (30)   NULL,
    [mi_tax_incl_flag]                    BIT             NULL,
    [mi_cost_amt]                         DECIMAL (26, 6) NULL,
    [bargun_id]                           SMALLINT        NULL,
    [menu_item_group_id]                  INT             NULL,
    [mi_receipt_label]                    NVARCHAR (16)   NULL,
    [mi_price_override_flag]              BIT             NULL,
    [data_control_group_id]               INT             NULL,
    [store_id]                            INT             NULL,
    [store_created_id]                    INT             NULL,
    [covers]                              SMALLINT        NULL,
    [row_version]                         BINARY (8)      NULL,
    [kds_video_label]                     NVARCHAR (20)   NULL,
    [kds_video_id]                        INT             NULL,
    [kds_category_id]                     INT             NULL,
    [kds_cook_time]                       INT             NULL,
    [default_image_id]                    INT             NULL,
    [track_id]                            BIGINT          NULL,
    [inserted_date_time]                  DATETIME        NULL,
    [updated_date_time]                   DATETIME        NULL,
    [track_action]                        NVARCHAR (1)    NULL,
    [dv_batch_id]                         BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

