CREATE TABLE [dbo].[stage_boss_asireserv] (
    [stage_boss_asireserv_id] BIGINT        NOT NULL,
    [reservation]             INT           NULL,
    [trainer_cust_code]       CHAR (10)     NULL,
    [trainer_mbr_code]        CHAR (10)     NULL,
    [upccode]                 CHAR (15)     NULL,
    [reserve_type]            CHAR (1)      NULL,
    [start_date]              SMALLDATETIME NULL,
    [end_date]                SMALLDATETIME NULL,
    [session_id]              CHAR (15)     NULL,
    [program_id]              CHAR (25)     NULL,
    [def_price]               MONEY         NULL,
    [instructor]              CHAR (20)     NULL,
    [billing_count]           SMALLINT      NULL,
    [status]                  CHAR (1)      NULL,
    [free_date]               SMALLDATETIME NULL,
    [qoh]                     SMALLINT      NULL,
    [limit]                   SMALLINT      NULL,
    [recurring]               CHAR (1)      NULL,
    [color]                   INT           NULL,
    [shape]                   INT           NULL,
    [comment]                 NCHAR (40)    NULL,
    [club]                    INT           NULL,
    [resource_id]             INT           NULL,
    [resource]                CHAR (25)     NULL,
    [create_date]             DATETIME      NULL,
    [link_to]                 INT           NULL,
    [min_limit]               INT           NULL,
    [non_mbr_price]           MONEY         NULL,
    [ical_recur_rule]         VARCHAR (150) NULL,
    [upc_desc]                CHAR (40)     NULL,
    [respect_holidays]        BIT           NULL,
    [interest_id]             INT           NULL,
    [origin]                  CHAR (1)      NULL,
    [print_desc]              CHAR (40)     NULL,
    [day_plan_string]         VARCHAR (21)  NULL,
    [day_plan_ints]           VARCHAR (14)  NULL,
    [publish]                 CHAR (1)      NULL,
    [published_duration]      INT           NULL,
    [format_id]               INT           NULL,
    [mms_product_id]          CHAR (15)     NULL,
    [web_register]            CHAR (1)      NULL,
    [target]                  INT           NULL,
    [class_expense]           MONEY         NULL,
    [instructor_expense]      MONEY         NULL,
    [age_low]                 INT           NULL,
    [age_high]                INT           NULL,
    [web_purchase]            CHAR (1)      NULL,
    [payment_freq]            VARCHAR (1)   NULL,
    [last_modified]           DATETIME      NULL,
    [waiver_reqd]             CHAR (1)      NULL,
    [deposit_amt]             MONEY         NULL,
    [payment_reqd_days]       INT           NULL,
    [pre_assgn_instr_cnt]     INT           NULL,
    [grace_days]              INT           NULL,
    [continuous]              CHAR (1)      NULL,
    [allow_waitlist]          CHAR (1)      NULL,
    [use_for_LTBucks]         CHAR (1)      NULL,
    [cancel_dates]            VARCHAR (222) NULL,
    [dv_batch_id]             BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

