CREATE TABLE [dbo].[stage_hash_crmcloudsync_Appointment] (
    [stage_hash_crmcloudsync_Appointment_id] BIGINT          IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)       NOT NULL,
    [activityid]                             VARCHAR (38)    NULL,
    [activitytypecode]                       NVARCHAR (64)   NULL,
    [activitytypecodename]                   NVARCHAR (255)  NULL,
    [actualdurationminutes]                  INT             NULL,
    [actualend]                              DATETIME        NULL,
    [actualstart]                            DATETIME        NULL,
    [category]                               NVARCHAR (250)  NULL,
    [createdby]                              VARCHAR (38)    NULL,
    [createdbyname]                          NVARCHAR (200)  NULL,
    [createdbyyominame]                      NVARCHAR (200)  NULL,
    [createdon]                              DATETIME        NULL,
    [createdonbehalfby]                      VARCHAR (38)    NULL,
    [createdonbehalfbyname]                  NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]              NVARCHAR (200)  NULL,
    [description]                            VARCHAR (8000)  NULL,
    [exchangerate]                           DECIMAL (28)    NULL,
    [globalobjectid]                         NVARCHAR (300)  NULL,
    [importsequencenumber]                   INT             NULL,
    [instancetypecode]                       INT             NULL,
    [instancetypecodename]                   NVARCHAR (255)  NULL,
    [isalldayevent]                          VARCHAR (38)    NULL,
    [isalldayeventname]                      NVARCHAR (255)  NULL,
    [isbilled]                               VARCHAR (38)    NULL,
    [isbilledname]                           NVARCHAR (255)  NULL,
    [ismapiprivate]                          VARCHAR (38)    NULL,
    [ismapiprivatename]                      NVARCHAR (255)  NULL,
    [isregularactivity]                      VARCHAR (38)    NULL,
    [isregularactivityname]                  NVARCHAR (255)  NULL,
    [isworkflowcreated]                      VARCHAR (38)    NULL,
    [isworkflowcreatedname]                  NVARCHAR (255)  NULL,
    [location]                               NVARCHAR (200)  NULL,
    [ltf_appointmenttype]                    INT             NULL,
    [ltf_appointmenttypename]                NVARCHAR (255)  NULL,
    [ltf_clubappointmentsid]                 VARCHAR (38)    NULL,
    [ltf_clubappointmentsidname]             NVARCHAR (100)  NULL,
    [ltf_clubid]                             VARCHAR (38)    NULL,
    [ltf_clubidname]                         NVARCHAR (100)  NULL,
    [ltf_udwid]                              NVARCHAR (255)  NULL,
    [modifiedby]                             VARCHAR (38)    NULL,
    [modifiedbyname]                         NVARCHAR (200)  NULL,
    [modifiedbyyominame]                     NVARCHAR (200)  NULL,
    [modifiedfieldsmask]                     VARCHAR (8000)  NULL,
    [modifiedon]                             DATETIME        NULL,
    [modifiedonbehalfby]                     VARCHAR (38)    NULL,
    [modifiedonbehalfbyname]                 NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]             NVARCHAR (200)  NULL,
    [optionalattendees]                      NVARCHAR (2000) NULL,
    [organizer]                              NVARCHAR (2000) NULL,
    [originalstartdate]                      DATETIME        NULL,
    [outlookownerapptid]                     INT             NULL,
    [overriddencreatedon]                    DATETIME        NULL,
    [ownerid]                                VARCHAR (38)    NULL,
    [owneridname]                            NVARCHAR (200)  NULL,
    [owneridtype]                            NVARCHAR (64)   NULL,
    [owneridyominame]                        NVARCHAR (200)  NULL,
    [owningbusinessunit]                     VARCHAR (38)    NULL,
    [owningteam]                             VARCHAR (38)    NULL,
    [owninguser]                             VARCHAR (38)    NULL,
    [prioritycode]                           INT             NULL,
    [prioritycodename]                       NVARCHAR (255)  NULL,
    [processid]                              VARCHAR (38)    NULL,
    [regardingobjectid]                      VARCHAR (38)    NULL,
    [regardingobjectidname]                  VARCHAR (38)    NULL,
    [regardingobjectidyominame]              VARCHAR (38)    NULL,
    [regardingobjecttypecode]                NVARCHAR (64)   NULL,
    [requiredattendees]                      NVARCHAR (2000) NULL,
    [scheduleddurationminutes]               INT             NULL,
    [scheduledend]                           DATETIME        NULL,
    [scheduledstart]                         DATETIME        NULL,
    [seriesid]                               VARCHAR (38)    NULL,
    [serviceid]                              VARCHAR (38)    NULL,
    [stageid]                                VARCHAR (38)    NULL,
    [statecode]                              INT             NULL,
    [statecodename]                          NVARCHAR (255)  NULL,
    [statuscode]                             INT             NULL,
    [statuscodename]                         NVARCHAR (255)  NULL,
    [subcategory]                            NVARCHAR (250)  NULL,
    [subject]                                NVARCHAR (200)  NULL,
    [timezoneruleversionnumber]              INT             NULL,
    [transactioncurrencyid]                  VARCHAR (38)    NULL,
    [transactioncurrencyidname]              NVARCHAR (100)  NULL,
    [utcconversiontimezonecode]              INT             NULL,
    [versionnumber]                          BIGINT          NULL,
    [InsertedDateTime]                       DATETIME        NULL,
    [InsertUser]                             VARCHAR (100)   NULL,
    [ltf_metontour]                          NVARCHAR (200)  NULL,
    [UpdatedDateTime]                        DATETIME        NULL,
    [UpdateUser]                             VARCHAR (50)    NULL,
    [ltf_webbookingsource]                   INT             NULL,
    [ltf_webbookingsourcename]               NVARCHAR (255)  NULL,
    [ltf_checkinflag]                        INT             NULL,
    [ltf_checkinflagname]                    NVARCHAR (255)  NULL,
    [ltf_program]                            INT             NULL,
    [ltf_programname]                        NVARCHAR (255)  NULL,
    [traversedpath]                          NVARCHAR (1250) NULL,
    [ltf_qrcode]                             VARCHAR (8000)  NULL,
    [dv_load_date_time]                      DATETIME        NOT NULL,
    [dv_updated_date_time]                   DATETIME        NULL,
    [dv_update_user]                         VARCHAR (50)    NULL,
    [dv_batch_id]                            BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

