CREATE TABLE [dbo].[stage_crmcloudsync_SystemUser] (
    [stage_crmcloudsync_SystemUser_id]  BIGINT          NOT NULL,
    [accessmode]                        INT             NULL,
    [accessmodename]                    NVARCHAR (255)  NULL,
    [address1_addressid]                VARCHAR (36)    NULL,
    [address1_addresstypecode]          INT             NULL,
    [address1_addresstypecodename]      NVARCHAR (255)  NULL,
    [address1_city]                     NVARCHAR (128)  NULL,
    [address1_composite]                VARCHAR (8000)  NULL,
    [address1_country]                  NVARCHAR (128)  NULL,
    [address1_county]                   NVARCHAR (128)  NULL,
    [address1_fax]                      NVARCHAR (64)   NULL,
    [address1_latitude]                 DECIMAL (26, 6) NULL,
    [address1_line1]                    NVARCHAR (1024) NULL,
    [address1_line2]                    NVARCHAR (1024) NULL,
    [address1_line3]                    NVARCHAR (1024) NULL,
    [address1_longitude]                DECIMAL (26, 6) NULL,
    [address1_name]                     NVARCHAR (100)  NULL,
    [address1_postalcode]               NVARCHAR (40)   NULL,
    [address1_postofficebox]            NVARCHAR (40)   NULL,
    [address1_shippingmethodcode]       INT             NULL,
    [address1_shippingmethodcodename]   NVARCHAR (255)  NULL,
    [address1_stateorprovince]          NVARCHAR (128)  NULL,
    [address1_telephone1]               NVARCHAR (64)   NULL,
    [address1_telephone2]               NVARCHAR (50)   NULL,
    [address1_telephone3]               NVARCHAR (50)   NULL,
    [address1_upszone]                  NVARCHAR (4)    NULL,
    [address1_utcoffset]                INT             NULL,
    [address2_addressid]                VARCHAR (36)    NULL,
    [address2_addresstypecode]          INT             NULL,
    [address2_addresstypecodename]      NVARCHAR (255)  NULL,
    [address2_city]                     NVARCHAR (128)  NULL,
    [address2_composite]                VARCHAR (8000)  NULL,
    [address2_country]                  NVARCHAR (128)  NULL,
    [address2_county]                   NVARCHAR (128)  NULL,
    [address2_fax]                      NVARCHAR (50)   NULL,
    [address2_latitude]                 DECIMAL (26, 6) NULL,
    [address2_line1]                    NVARCHAR (1024) NULL,
    [address2_line2]                    NVARCHAR (1024) NULL,
    [address2_line3]                    NVARCHAR (1024) NULL,
    [address2_longitude]                DECIMAL (26, 6) NULL,
    [address2_name]                     NVARCHAR (100)  NULL,
    [address2_postalcode]               NVARCHAR (40)   NULL,
    [address2_postofficebox]            NVARCHAR (40)   NULL,
    [address2_shippingmethodcode]       INT             NULL,
    [address2_shippingmethodcodename]   NVARCHAR (255)  NULL,
    [address2_stateorprovince]          NVARCHAR (128)  NULL,
    [address2_telephone1]               NVARCHAR (50)   NULL,
    [address2_telephone2]               NVARCHAR (50)   NULL,
    [address2_telephone3]               NVARCHAR (50)   NULL,
    [address2_upszone]                  NVARCHAR (4)    NULL,
    [address2_utcoffset]                INT             NULL,
    [businessunitid]                    VARCHAR (36)    NULL,
    [businessunitidname]                NVARCHAR (160)  NULL,
    [calendarid]                        VARCHAR (36)    NULL,
    [caltype]                           INT             NULL,
    [caltypename]                       NVARCHAR (255)  NULL,
    [createdby]                         VARCHAR (36)    NULL,
    [createdbyname]                     NVARCHAR (200)  NULL,
    [createdbyyominame]                 NVARCHAR (200)  NULL,
    [createdon]                         DATETIME        NULL,
    [createdonbehalfby]                 VARCHAR (36)    NULL,
    [createdonbehalfbyname]             NVARCHAR (200)  NULL,
    [createdonbehalfbyyominame]         NVARCHAR (200)  NULL,
    [defaultfilterspopulated]           BIT             NULL,
    [defaultmailbox]                    VARCHAR (36)    NULL,
    [defaultmailboxname]                NVARCHAR (200)  NULL,
    [disabledreason]                    NVARCHAR (500)  NULL,
    [displayinserviceviews]             BIT             NULL,
    [displayinserviceviewsname]         NVARCHAR (255)  NULL,
    [domainname]                        NVARCHAR (1024) NULL,
    [emailrouteraccessapproval]         INT             NULL,
    [emailrouteraccessapprovalname]     NVARCHAR (255)  NULL,
    [employeeid]                        NVARCHAR (100)  NULL,
    [entityimage_timestamp]             BIGINT          NULL,
    [entityimage_url]                   NVARCHAR (200)  NULL,
    [entityimageid]                     VARCHAR (36)    NULL,
    [exchangerate]                      DECIMAL (28)    NULL,
    [firstname]                         NVARCHAR (64)   NULL,
    [fullname]                          NVARCHAR (200)  NULL,
    [governmentid]                      NVARCHAR (100)  NULL,
    [homephone]                         NVARCHAR (50)   NULL,
    [importsequencenumber]              INT             NULL,
    [incomingemaildeliverymethod]       INT             NULL,
    [incomingemaildeliverymethodname]   NVARCHAR (255)  NULL,
    [internalemailaddress]              NVARCHAR (100)  NULL,
    [invitestatuscode]                  INT             NULL,
    [invitestatuscodename]              NVARCHAR (255)  NULL,
    [isdisabled]                        BIT             NULL,
    [isdisabledname]                    NVARCHAR (255)  NULL,
    [isemailaddressapprovedbyo365admin] BIT             NULL,
    [isintegrationuser]                 BIT             NULL,
    [isintegrationusername]             NVARCHAR (255)  NULL,
    [islicensed]                        BIT             NULL,
    [issyncwithdirectory]               BIT             NULL,
    [jobtitle]                          NVARCHAR (100)  NULL,
    [lastname]                          NVARCHAR (64)   NULL,
    [ltf_clubid]                        VARCHAR (36)    NULL,
    [ltf_clubidname]                    NVARCHAR (100)  NULL,
    [middlename]                        NVARCHAR (50)   NULL,
    [mobilealertemail]                  NVARCHAR (100)  NULL,
    [mobilephone]                       NVARCHAR (64)   NULL,
    [modifiedby]                        VARCHAR (36)    NULL,
    [modifiedbyname]                    NVARCHAR (200)  NULL,
    [modifiedbyyominame]                NVARCHAR (200)  NULL,
    [modifiedon]                        DATETIME        NULL,
    [modifiedonbehalfby]                VARCHAR (36)    NULL,
    [modifiedonbehalfbyname]            NVARCHAR (200)  NULL,
    [modifiedonbehalfbyyominame]        NVARCHAR (200)  NULL,
    [nickname]                          NVARCHAR (50)   NULL,
    [organizationid]                    VARCHAR (36)    NULL,
    [organizationidname]                NVARCHAR (100)  NULL,
    [outgoingemaildeliverymethod]       INT             NULL,
    [outgoingemaildeliverymethodname]   NVARCHAR (255)  NULL,
    [overriddencreatedon]               DATETIME        NULL,
    [parentsystemuserid]                VARCHAR (36)    NULL,
    [parentsystemuseridname]            NVARCHAR (200)  NULL,
    [parentsystemuseridyominame]        NVARCHAR (200)  NULL,
    [passporthi]                        INT             NULL,
    [passportlo]                        INT             NULL,
    [personalemailaddress]              NVARCHAR (100)  NULL,
    [photourl]                          NVARCHAR (200)  NULL,
    [preferredaddresscode]              INT             NULL,
    [preferredaddresscodename]          NVARCHAR (255)  NULL,
    [preferredemailcode]                INT             NULL,
    [preferredemailcodename]            NVARCHAR (255)  NULL,
    [preferredphonecode]                INT             NULL,
    [preferredphonecodename]            NVARCHAR (255)  NULL,
    [processid]                         VARCHAR (36)    NULL,
    [queueid]                           VARCHAR (36)    NULL,
    [queueidname]                       NVARCHAR (400)  NULL,
    [salutation]                        NVARCHAR (20)   NULL,
    [setupuser]                         BIT             NULL,
    [setupusername]                     NVARCHAR (255)  NULL,
    [siteid]                            VARCHAR (36)    NULL,
    [siteidname]                        NVARCHAR (160)  NULL,
    [skills]                            NVARCHAR (100)  NULL,
    [stageid]                           VARCHAR (36)    NULL,
    [systemuserid]                      VARCHAR (36)    NULL,
    [territoryid]                       VARCHAR (36)    NULL,
    [territoryidname]                   NVARCHAR (200)  NULL,
    [timezoneruleversionnumber]         INT             NULL,
    [title]                             NVARCHAR (128)  NULL,
    [transactioncurrencyid]             VARCHAR (36)    NULL,
    [transactioncurrencyidname]         NVARCHAR (100)  NULL,
    [userlicensetype]                   INT             NULL,
    [utcconversiontimezonecode]         INT             NULL,
    [versionnumber]                     BIGINT          NULL,
    [windowsliveid]                     NVARCHAR (1024) NULL,
    [yammeremailaddress]                NVARCHAR (200)  NULL,
    [yammeruserid]                      NVARCHAR (128)  NULL,
    [yomifirstname]                     NVARCHAR (64)   NULL,
    [yomifullname]                      NVARCHAR (200)  NULL,
    [yomilastname]                      NVARCHAR (64)   NULL,
    [yomimiddlename]                    NVARCHAR (50)   NULL,
    [InsertedDateTime]                  DATETIME        NULL,
    [InsertUser]                        VARCHAR (100)   NULL,
    [UpdatedDateTime]                   DATETIME        NULL,
    [UpdateUser]                        VARCHAR (50)    NULL,
    [defaultodbfoldername]              NVARCHAR (200)  NULL,
    [mobileofflineprofileid]            VARCHAR (36)    NULL,
    [mobileofflineprofileidname]        NVARCHAR (255)  NULL,
    [positionid]                        VARCHAR (36)    NULL,
    [positionidname]                    NVARCHAR (100)  NULL,
    [sharepointemailaddress]            NVARCHAR (1024) NULL,
    [traversedpath]                     NVARCHAR (1250) NULL,
    [dv_batch_id]                       BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

