CREATE TABLE [dbo].[stage_crmcloudsync_ltf_do_not_contact_store] (
    [stage_crmcloudsync_ltf_do_not_contact_store_id] BIGINT         NOT NULL,
    [createdby]                                      VARCHAR (36)   NULL,
    [createdbyname]                                  NVARCHAR (200) NULL,
    [createdbyyominame]                              NVARCHAR (200) NULL,
    [createdon]                                      DATETIME       NULL,
    [createdonbehalfby]                              VARCHAR (36)   NULL,
    [createdonbehalfbyname]                          NVARCHAR (200) NULL,
    [createdonbehalfbyyominame]                      NVARCHAR (200) NULL,
    [importsequencenumber]                           INT            NULL,
    [ltf_address1_city]                              NVARCHAR (80)  NULL,
    [ltf_address1_county]                            NVARCHAR (50)  NULL,
    [ltf_address1_line1]                             NVARCHAR (250) NULL,
    [ltf_address1_line1_country]                     NVARCHAR (80)  NULL,
    [ltf_address1_line2]                             NVARCHAR (250) NULL,
    [ltf_address1_line3]                             NVARCHAR (250) NULL,
    [ltf_address1_postalcode]                        NVARCHAR (20)  NULL,
    [ltf_address1_stateorprovince]                   NVARCHAR (50)  NULL,
    [ltf_contactlookup]                              VARCHAR (36)   NULL,
    [ltf_contactlookupname]                          NVARCHAR (160) NULL,
    [ltf_contactlookupyominame]                      NVARCHAR (160) NULL,
    [ltf_do_not_contact_store_id]                    VARCHAR (36)   NULL,
    [ltf_emailaddress1]                              NVARCHAR (100) NULL,
    [ltf_emailaddress1_dncsource]                    INT            NULL,
    [ltf_emailaddress1_dncsourcename]                NVARCHAR (255) NULL,
    [ltf_emailaddress2]                              NVARCHAR (100) NULL,
    [ltf_emailaddress2_dncsource]                    INT            NULL,
    [ltf_emailaddress2_dncsourcename]                NVARCHAR (255) NULL,
    [ltf_leadlookup]                                 VARCHAR (36)   NULL,
    [ltf_leadlookupname]                             NVARCHAR (160) NULL,
    [ltf_leadlookupyominame]                         NVARCHAR (160) NULL,
    [ltf_mobilephone]                                NVARCHAR (50)  NULL,
    [ltf_mobilephone_dncsource]                      INT            NULL,
    [ltf_mobilephone_dncsourcename]                  NVARCHAR (255) NULL,
    [ltf_name]                                       NVARCHAR (160) NULL,
    [ltf_telephone1]                                 NVARCHAR (50)  NULL,
    [ltf_telephone1_dncsource]                       INT            NULL,
    [ltf_telephone1_dncsourcename]                   NVARCHAR (255) NULL,
    [ltf_telephone2]                                 NVARCHAR (50)  NULL,
    [ltf_telephone2_dncsource]                       INT            NULL,
    [ltf_telephone2_dncsourcename]                   NVARCHAR (255) NULL,
    [ltf_telephone3]                                 NVARCHAR (50)  NULL,
    [ltf_telephone3_dncsource]                       INT            NULL,
    [ltf_telephone3_dncsourcename]                   NVARCHAR (255) NULL,
    [modifiedby]                                     VARCHAR (36)   NULL,
    [modifiedbyname]                                 NVARCHAR (200) NULL,
    [modifiedbyyominame]                             NVARCHAR (200) NULL,
    [modifiedon]                                     DATETIME       NULL,
    [modifiedonbehalfby]                             VARCHAR (36)   NULL,
    [modifiedonbehalfbyname]                         NVARCHAR (200) NULL,
    [modifiedonbehalfbyyominame]                     NVARCHAR (200) NULL,
    [organizationid]                                 VARCHAR (36)   NULL,
    [organizationidname]                             NVARCHAR (160) NULL,
    [overriddencreatedon]                            DATETIME       NULL,
    [statecode]                                      INT            NULL,
    [statecodename]                                  NVARCHAR (255) NULL,
    [statuscode]                                     INT            NULL,
    [statuscodename]                                 NVARCHAR (255) NULL,
    [timezoneruleversionnumber]                      INT            NULL,
    [utcconversiontimezonecode]                      INT            NULL,
    [versionnumber]                                  BIGINT         NULL,
    [InsertedDateTime]                               DATETIME       NULL,
    [InsertUser]                                     VARCHAR (100)  NULL,
    [UpdatedDateTime]                                DATETIME       NULL,
    [UpdateUser]                                     VARCHAR (50)   NULL,
    [dv_batch_id]                                    BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

