CREATE TABLE [dbo].[stage_hybris_pricerows] (
    [stage_hybris_pricerows_id] BIGINT          NOT NULL,
    [hjmpTS]                    BIGINT          NULL,
    [createdTS]                 DATETIME        NULL,
    [modifiedTS]                DATETIME        NULL,
    [TypePkString]              BIGINT          NULL,
    [OwnerPkString]             BIGINT          NULL,
    [PK]                        BIGINT          NULL,
    [p_product]                 BIGINT          NULL,
    [p_pg]                      BIGINT          NULL,
    [p_productmatchqualifier]   BIGINT          NULL,
    [p_starttime]               DATETIME        NULL,
    [p_endtime]                 DATETIME        NULL,
    [p_user]                    BIGINT          NULL,
    [p_ug]                      BIGINT          NULL,
    [p_usermatchqualifier]      BIGINT          NULL,
    [p_productid]               NVARCHAR (255)  NULL,
    [p_catalogversion]          BIGINT          NULL,
    [p_matchvalue]              INT             NULL,
    [p_currency]                BIGINT          NULL,
    [p_minqtd]                  BIGINT          NULL,
    [p_net]                     TINYINT         NULL,
    [p_price]                   DECIMAL (26, 6) NULL,
    [p_unit]                    BIGINT          NULL,
    [p_unitfactor]              INT             NULL,
    [p_giveawayprice]           TINYINT         NULL,
    [p_channel]                 BIGINT          NULL,
    [p_sequenceid]              BIGINT          NULL,
    [aCLTS]                     BIGINT          NULL,
    [propTS]                    BIGINT          NULL,
    [dv_batch_id]               BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

