CREATE TABLE [dbo].[stage_athlinks_api_vw_MasterEvent] (
    [stage_athlinks_api_vw_MasterEvent_id] BIGINT          NOT NULL,
    [MasterID]                             INT             NULL,
    [NAME]                                 NVARCHAR (128)  NULL,
    [ShortUrl]                             VARCHAR (128)   NULL,
    [RaceCount]                            INT             NULL,
    [ResultCount]                          INT             NULL,
    [CompanyID]                            INT             NULL,
    [LogoPath]                             NVARCHAR (512)  NULL,
    [STATUS]                               INT             NULL,
    [ContactName]                          NVARCHAR (256)  NULL,
    [Phone]                                NVARCHAR (100)  NULL,
    [ContactAddress]                       NVARCHAR (1000) NULL,
    [Longitude]                            DECIMAL (26, 6) NULL,
    [Latitude]                             DECIMAL (26, 6) NULL,
    [Geo]                                  VARCHAR (4000)  NULL,
    [Elevation]                            INT             NULL,
    [City]                                 NVARCHAR (128)  NULL,
    [StateProvID]                          NVARCHAR (8)    NULL,
    [CompanyName]                          NVARCHAR (50)   NULL,
    [StateProvAbbrev]                      NVARCHAR (8)    NULL,
    [CountryID]                            CHAR (2)        NULL,
    [NextDate]                             DATETIME        NULL,
    [PrevDate]                             DATETIME        NULL,
    [NextRaceID]                           INT             NULL,
    [PrevRaceID]                           INT             NULL,
    [CuratedDesc]                          NVARCHAR (1000) NULL,
    [Featured]                             BIT             NULL,
    [CreateDate]                           DATETIME        NULL,
    [dv_batch_id]                          BIGINT          NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

