CREATE VIEW [sandbox_ebi].[v_product_master] AS SELECT 'Hybris' AS  source_system,
       Cast(vDimHybrisProduct.code AS VARCHAR(258)) AS source_product_id,
       Cast(vDimHybrisProduct.code AS VARCHAR(258)) AS sku,
       vDimHybrisProduct.name AS product_description,
       vDimHybrisProduct.product_status,
       IsNull(vDimHybrisProduct.reporting_division,'E-Commerce') AS reporting_division,
       IsNull(vDimHybrisProduct.reporting_sub_division,'E-Commerce') AS reporting_subdivision,
       IsNull(vDimHybrisProduct.reporting_department,'E-Commerce') AS reporting_department, 
       IsNull(vDimHybrisProduct.reporting_product_group,'') AS reporting_product_group, 
       vDimHybrisProduct.reporting_region_type,
       NULL AS mms_department,
       NULL AS deferred_revenue_flag,
       NULL AS revenue_allocation_rule_name,
       NULL AS workday_account,
       NULL AS workday_cost_center,
       NULL AS workday_offering,
       NULL AS workday_override_region,
       NULL AS workday_revenue_product_group_account,
       NULL AS workday_refund_gl_account,
       NULL AS workday_discount_gl_account,
       NULL AS workday_revenue_product_group_refund_gl_account,
       NULL AS workday_revenue_product_group_discount_gl_account,
       NULL AS revenue_category,
       NULL AS spend_category,
       NULL AS mms_recurrent_product_type_description,
       NULL AS mms_package_product_flag,
       NULL AS mms_product_tip_allowed_flag,
       vDimHybrisProduct.payroll_region_type,
       vDimHybrisProduct.payroll_description AS payroll_extract_description,   
       vDimHybrisProduct.payroll_standard_product_group_flag,     
       vDimHybrisProduct.payroll_standard_group_description,
       vDimHybrisProduct.payroll_standard_group_sort_order,
       vDimHybrisProduct.payroll_standard_sales_amount_flag,
       vDimHybrisProduct.payroll_standard_service_amount_flag,
       vDimHybrisProduct.payroll_standard_service_quantity_flag,
       vDimHybrisProduct.payroll_lt_bucks_product_group_flag,  
       vDimHybrisProduct.payroll_lt_bucks_group_description,
       vDimHybrisProduct.payroll_lt_bucks_group_sort_order,
       vDimHybrisProduct.payroll_lt_bucks_sales_amount_flag,
       vDimHybrisProduct.payroll_lt_bucks_service_amount_flag,
       vDimHybrisProduct.payroll_lt_bucks_service_quantity_flag, 
       vDimHybrisProduct.payroll_track_sales_flag,       
       vDimHybrisProduct.payroll_track_service_flag,    
       NULL AS junior_dues_flag,
       NULL AS mtd_average_delivered_session_price_flag,
       vDimHybrisProduct.mtd_average_sale_price_flag,
       vDimHybrisProduct.connectivity_primary_lead_generator_flag,
       vDimHybrisProduct.connectivity_lead_generator_flag,
       vDimHybrisProduct.new_business_old_business_flag,
       NULL AS sales_category_description,
       'N' AS dssr_if_admin_fee_flag,      
       'N' AS dssr_downgrade_other_enrollment_fee_flag,    
       'N' AS experience_life_magazine_flag    
  FROM [marketing].[v_dim_hybris_product] vDimHybrisProduct
 WHERE (vDimHybrisProduct.dim_hybris_product_key Is Null 
        OR  vDimHybrisProduct.dim_hybris_product_key > '0' )   ------- removes the "unknown"  (-998) product records from being returned


UNION ALL


SELECT 'HealthCheckUSA' AS  source_system,
       CAST(vDimHealthCheckUSAProduct.product_sku as VARCHAR(258)) AS source_product_id,
       CAST(vDimHealthCheckUSAProduct.product_sku as VARCHAR(258)) AS sku,
       vDimHealthCheckUSAProduct.product_description AS product_description,  
       vDimHealthCheckUSAProduct.product_status,
       IsNull(vDimHealthCheckUSAProduct.reporting_division,'HealthCheckUSA') AS reporting_division,
       IsNull(vDimHealthCheckUSAProduct.reporting_sub_division,'HealthCheckUSA') AS reporting_subdivision,
       IsNULL(vDimHealthCheckUSAProduct.reporting_department,'HealthCheckUSA') AS reporting_department, 
       ISNULL(vDimHealthCheckUSAProduct.reporting_product_group,'') AS reporting_product_group,	    
       vDimHealthCheckUSAProduct.reporting_region_type,
       NULL AS mms_department,
       NULL AS deferred_revenue_flag,
       NULL AS revenue_allocation_rule_name,
       NULL AS workday_account,
       NULL AS workday_cost_center,
       NULL AS workday_offering,
       NULL AS workday_override_region,
       NULL AS workday_revenue_product_group_account,
       NULL AS workday_refund_gl_account,
       NULL AS workday_discount_gl_account,
       NULL AS workday_revenue_product_group_refund_gl_account,
       NULL AS workday_revenue_product_group_discount_gl_account,
	   NULL AS revenue_category,
	   NULL AS spend_category,
       NULL AS mms_recurrent_product_type_description,
       NULL AS mms_package_product_flag,
       NULL AS mms_product_tip_allowed_flag,
       vDimHealthCheckUSAProduct.payroll_region_type,     
       vDimHealthCheckUSAProduct.payroll_description AS payroll_extract_description,   
       vDimHealthCheckUSAProduct.payroll_standard_product_group_flag, 
       vDimHealthCheckUSAProduct.payroll_standard_group_description,
       vDimHealthCheckUSAProduct.payroll_standard_group_sort_order,
       vDimHealthCheckUSAProduct.payroll_standard_sales_amount_flag,
       vDimHealthCheckUSAProduct.payroll_standard_service_amount_flag,
       vDimHealthCheckUSAProduct.payroll_standard_service_quantity_flag,
       vDimHealthCheckUSAProduct.payroll_lt_bucks_product_group_flag, 
       vDimHealthCheckUSAProduct.payroll_lt_bucks_group_description,
       vDimHealthCheckUSAProduct.payroll_lt_bucks_group_sort_order,
       vDimHealthCheckUSAProduct.payroll_lt_bucks_sales_amount_flag,
       vDimHealthCheckUSAProduct.payroll_lt_bucks_service_amount_flag,
       vDimHealthCheckUSAProduct.payroll_lt_bucks_service_quantity_flag,
       vDimHealthCheckUSAProduct.payroll_track_sales_flag,
       vDimHealthCheckUSAProduct.payroll_track_service_flag,
       NULL AS junior_dues_flag,
       NULL AS mtd_average_delivered_session_price_flag,
       vDimHealthCheckUSAProduct.mtd_average_sale_price_flag,
       vDimHealthCheckUSAProduct.connectivity_primary_lead_generator_flag, 
	   vDimHealthCheckUSAProduct.connectivity_lead_generator_flag,
       vDimHealthCheckUSAProduct.new_business_old_business_flag,
       NULL AS sales_category_description,
       'N' AS dssr_if_admin_fee_flag,      
       'N' AS dssr_downgrade_other_enrollment_fee_flag,    
       'N' AS experience_life_magazine_flag    
  FROM [marketing].[v_dim_healthcheckusa_product] vDimHealthCheckUSAProduct
 WHERE (vDimHealthCheckUSAProduct.dim_healthcheckusa_product_key Is Null 
        OR  vDimHealthCheckUSAProduct.dim_healthcheckusa_product_key > '0' )   ------- removes the "unknown" (-998) product records from being returned

UNION ALL

SELECT 'Cafe' AS source_system,
       CAST(vDimCafeProduct.menu_item_id AS VARCHAR(258)) AS source_product_id,
       CAST(vDimCafeProduct.sku_number AS VARCHAR(258)) AS sku,
       vDimCafeProduct.menu_item_name AS product_description,
       CASE WHEN vDimCafeProduct.menu_item_active_flag = 'Y'
	        THEN 'Active'
			ELSE 'Inactive'
			END product_status,
       IsNull(vDimCafeProduct.reporting_division,'LifeCafe') AS reporting_division,
       IsNull(vDimCafeProduct.reporting_sub_division,'LifeCafe')  AS reporting_subdivision,
       IsNull(vDimCafeProduct.reporting_department,'LifeCafe') AS reporting_department,  
       IsNull(vDimCafeProduct.reporting_product_group,'') AS reporting_product_group,
       DimReportingHierarchy.reporting_region_type,
       NULL AS mms_department,
       NULL AS deferred_revenue_flag,
       NULL AS revenue_allocation_rule_name,
       NULL AS workday_account,
       NULL AS workday_cost_center,
       NULL AS workday_offering,
       NULL AS workday_override_region,
       NULL AS workday_revenue_product_group_account,
       NULL AS workday_refund_gl_account,
       NULL AS workday_discount_gl_account,
       NULL AS workday_revenue_product_group_refund_gl_account,
       NULL AS workday_revenue_product_group_discount_gl_account,
       NULL AS revenue_category,
       NULL AS spend_category,
       NULL AS mms_recurrent_product_type_description,
       NULL AS mms_package_product_flag,
       NULL AS mms_product_tip_allowed_flag,
       vDimCafeProduct.payroll_region_type,
       vDimCafeProduct.payroll_description AS payroll_extract_description,  
       vDimCafeProduct.payroll_standard_product_group_flag,   
       vDimCafeProduct.payroll_standard_group_description,    
       vDimCafeProduct.payroll_standard_group_sort_order,
       vDimCafeProduct.payroll_standard_sales_amount_flag,
       vDimCafeProduct.payroll_standard_service_amount_flag,
       vDimCafeProduct.payroll_standard_service_quantity_flag,
       vDimCafeProduct.payroll_lt_bucks_product_group_flag,   
       vDimCafeProduct.payroll_lt_bucks_group_description,
       vDimCafeProduct.payroll_lt_bucks_group_sort_order,
       vDimCafeProduct.payroll_lt_bucks_sales_amount_flag,
       vDimCafeProduct.payroll_lt_bucks_service_amount_flag,
       vDimCafeProduct.payroll_lt_bucks_service_quantity_flag,
       vDimCafeProduct.payroll_track_sales_flag,   
       vDimCafeProduct.payroll_track_service_flag, 
       NULL AS junior_dues_flag,
       NULL AS mtd_average_delivered_session_price_flag,
       vDimCafeProduct.mtd_average_sale_price_flag,
       vDimCafeProduct.connectivity_primary_lead_generator_flag,
       vDimCafeProduct.connectivity_lead_generator_flag, 
       vDimCafeProduct.new_business_old_business_flag, 
       NULL AS sales_category_description,
       'N' AS dssr_if_admin_fee_flag,     
       'N' AS dssr_downgrade_other_enrollment_fee_flag,    
       'N' AS experience_life_magazine_flag   
  FROM [marketing].[v_dim_cafe_product] vDimCafeProduct
  JOIN [marketing].[v_dim_reporting_hierarchy] DimReportingHierarchy
    ON IsNull(vDimCafeProduct.dim_reporting_hierarchy_key,'90FD13C426CD100FF08EA59255903224') = DimReportingHierarchy.dim_reporting_hierarchy_key  ----- '90FD13C426CD100FF08EA59255903224' is the default cafe key
 WHERE (vDimCafeProduct.dim_cafe_product_key Is Null OR  vDimCafeProduct.dim_cafe_product_key > '0' )   ------- removes the "unknown"  (-998) product records from being returned


UNION ALL


SELECT 'MMS' AS source_system,
       CAST(vDimMMSProduct.product_id AS VARCHAR(258)) AS source_product_id,
       CAST(vDimMMSProduct.sku AS VARCHAR(258)) AS sku,
       vDimMMSProduct.product_description AS product_description,
       vDimMMSProduct.product_status, 
       IsNull(vDimMMSProduct.reporting_division,'MMS') AS reporting_division,
       IsNull(vDimMMSProduct.reporting_sub_division,'MMS') AS reporting_subdivision,	       
       IsNull(vDimMMSProduct.reporting_department,'MMS') AS reporting_department,
       IsNull(vDimMMSProduct.reporting_product_group,'') AS reporting_product_group,
       vDimMMSProduct.reporting_region_type,
       vDimMMSProduct.department_description AS mms_department,
       vDimMMSProduct.deferred_revenue_flag,
       vDimMMSProduct.allocation_rule  AS revenue_allocation_rule_name,
       vDimMMSProduct.workday_account,
       vDimMMSProduct.workday_cost_center,
       vDimMMSProduct.workday_offering,
       vDimMMSProduct.workday_over_ride_region AS workday_override_region,
       vDimMMSProduct.workday_revenue_product_group_account,
       vDimMMSProduct.workday_refund_gl_account,
       vDimMMSProduct.workday_discount_gl_account,
       vDimMMSProduct.workday_revenue_product_group_refund_gl_account,
       vDimMMSProduct.workday_revenue_product_group_discount_gl_account,
	   vDimMMSProduct.revenue_category,
	   vDimMMSProduct.spend_category,
       vDimMMSProduct.recurrent_product_type_description  AS mms_recurrent_product_type_description,
       vDimMMSProduct.package_product_flag  AS mms_package_product_flag,
       vDimMMSProduct.tip_allowed_flag AS mms_product_tip_allowed_flag,
       vDimMMSProduct.payroll_region_type,
       vDimMMSProduct.payroll_description AS payroll_extract_description, 
       vDimMMSProduct.payroll_standard_product_group_flag,   
       vDimMMSProduct.payroll_standard_group_description,
       vDimMMSProduct.payroll_standard_group_sort_order,
       vDimMMSProduct.payroll_standard_sales_amount_flag,
       vDimMMSProduct.payroll_standard_service_amount_flag,
       vDimMMSProduct.payroll_standard_service_quantity_flag,	   	   	      
       vDimMMSProduct.payroll_lt_bucks_product_group_flag,    
       vDimMMSProduct.payroll_lt_bucks_group_description,
       vDimMMSProduct.payroll_lt_bucks_group_sort_order,
       vDimMMSProduct.payroll_lt_bucks_sales_amount_flag,
       vDimMMSProduct.payroll_lt_bucks_service_amount_flag,
       vDimMMSProduct.payroll_lt_bucks_service_quantity_flag,
       vDimMMSProduct.payroll_track_sales_flag,     
       vDimMMSProduct.payroll_track_service_flag,    
       vDimMMSProduct.junior_member_dues_flag AS junior_dues_flag,
       vDimMMSProduct.mtd_average_delivered_session_price_flag,
       vDimMMSProduct.mtd_average_sale_price_flag,
       vDimMMSProduct.connectivity_primary_lead_generator_flag, 
       vDimMMSProduct.connectivity_lead_generator_flag,
       vDimMMSProduct.new_business_old_business_flag,
       vDimMMSProduct.sales_category_description,
       vDimMMSProduct.dssr_if_admin_fee_flag,                       
       vDimMMSProduct.dssr_down_grade_other_enrollment_fee_flag,      
       vDimMMSProduct.experience_life_magazine_flag            
  FROM [marketing].[v_dim_mms_product_history] vDimMMSProduct
 WHERE(vDimMMSProduct.dim_mms_product_key Is Null 
      OR  vDimMMSProduct.dim_mms_product_key > '0' )   ------- removes the "unknown"  (-998) product records from being returned

 
 UNION ALL

 
 SELECT 'Magento' AS  source_system,
       CAST(vDimMagentoProduct.product_id AS VARCHAR(258))  AS source_product_id,
       CAST(vDimMagentoProduct.sku AS VARCHAR(258))  AS sku,
       vDimMagentoProduct.product_name AS product_description,  
	   CASE WHEN vDimMagentoProduct.status = 1
	        THEN 'Active'
			WHEN vDimMagentoProduct.status = 2
			THEN 'Inactive'
			END product_status,
       IsNull(vDimMagentoProduct.reporting_division,'Magento') AS reporting_division,
       IsNull(vDimMagentoProduct.reporting_sub_division,'Magento') AS reporting_subdivision,
       IsNull(vDimMagentoProduct.reporting_department,'Magento') AS reporting_department,  
       IsNull(vDimMagentoProduct.reporting_product_group,'') AS reporting_product_group,
       vDimMagentoProduct.reporting_region_type,
       NULL AS mms_department,
       NULL AS deferred_revenue_flag,
       NULL AS revenue_allocation_rule_name,
       NULL AS workday_account,
       vDimMagentoProduct.workday_costcenter_id AS workday_cost_center,
       vDimMagentoProduct.workday_offering_id AS workday_offering,
       NULL AS workday_override_region,
       NULL AS workday_revenue_product_group_account,
       NULL AS workday_refund_gl_account,
       NULL AS workday_discount_gl_account,
       NULL AS workday_revenue_product_group_refund_gl_account,
       NULL AS workday_revenue_product_group_discount_gl_account,
       vDimMagentoProduct.workday_revenue_id AS revenue_category,
	   vDimMagentoProduct.workday_spending_id AS spend_category,
       NULL AS mms_recurrent_product_type_description,
       NULL AS mms_package_product_flag,
       NULL AS mms_product_tip_allowed_flag,
       vDimMagentoProduct.payroll_region_type,
       vDimMagentoProduct.payroll_description AS payroll_extract_description,   
       vDimMagentoProduct.payroll_standard_product_group_flag, 
       vDimMagentoProduct.payroll_standard_group_description,
       vDimMagentoProduct.payroll_standard_group_sort_order,
       vDimMagentoProduct.payroll_standard_sales_amount_flag,
       vDimMagentoProduct.payroll_standard_service_amount_flag,
       vDimMagentoProduct.payroll_standard_service_quantity_flag,
       vDimMagentoProduct.payroll_lt_bucks_product_group_flag, 
       vDimMagentoProduct.payroll_lt_bucks_group_description,
       vDimMagentoProduct.payroll_lt_bucks_group_sort_order,
       vDimMagentoProduct.payroll_lt_bucks_sales_amount_flag,
       vDimMagentoProduct.payroll_lt_bucks_service_amount_flag,
       vDimMagentoProduct.payroll_lt_bucks_service_quantity_flag,
       vDimMagentoProduct.payroll_track_sales_flag,
       vDimMagentoProduct.payroll_track_service_flag,
       NULL AS junior_dues_flag,
       NULL AS mtd_average_delivered_session_price_flag,
       NULL AS mtd_average_sale_price_flag,
       vDimMagentoProduct.connectivity_primary_lead_generator_flag,
       vDimMagentoProduct.connectivity_lead_generator_flag,
       vDimMagentoProduct.new_business_old_business_flag,
       NULL AS sales_category_description,
       'N' AS dssr_if_admin_fee_flag,      
       'N' AS dssr_downgrade_other_enrollment_fee_flag,    
       'N' AS experience_life_magazine_flag    
  FROM [marketing].[v_dim_magento_product] vDimMagentoProduct
 WHERE (vDimMagentoProduct.dim_magento_product_key Is Null 
       OR  vDimMagentoProduct.dim_magento_product_key > '0' );