CREATE TABLE [sandbox_ebi].[fact_exerp_payroll] (
    [fact_exerp_payroll_id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [club_id]                           INT             NULL,
    [delivered_dim_date_key]            VARCHAR (8)     NULL,
    [delivered_dim_time_key]            INT             NULL,
    [dim_club_key]                      VARCHAR (32)    NULL,
    [dim_employee_key]                  VARCHAR (32)    NULL,
    [dim_exerp_booking_key]             VARCHAR (832)   NULL,
    [dim_exerp_product_key]             VARCHAR (32)    NULL,
    [dim_exerp_subscription_key]        VARCHAR (32)    NULL,
    [dim_exerp_subscription_period_key] VARCHAR (32)    NULL,
    [dim_mms_member_key]                VARCHAR (32)    NULL,
    [dim_mms_product_key]               VARCHAR (32)    NULL,
    [employee_id]                       INT             NULL,
    [fact_exerp_participation_key]      VARCHAR (32)    NULL,
    [member_id]                         INT             NULL,
    [participation_id]                  VARCHAR (4000)  NULL,
    [pay_period_first_day_dim_date_key] VARCHAR (8)     NULL,
    [payroll_description]               VARCHAR (500)   NULL,
    [payroll_group_description]         VARCHAR (500)   NULL,
    [payroll_region_type]               VARCHAR (500)   NULL,
    [payroll_service_amount_flag]       CHAR (1)        NULL,
    [payroll_service_quantity_flag]     CHAR (1)        NULL,
    [payroll_unique_key]                VARCHAR (33)    NULL,
    [price_per_booking]                 DECIMAL (26, 6) NULL,
    [price_per_booking_less_lt_bucks]   DECIMAL (26, 6) NULL,
    [product_id]                        INT             NULL,
    [dv_load_date_time]                 DATETIME        NULL,
    [dv_load_end_date_time]             DATETIME        NULL,
    [dv_batch_id]                       BIGINT          NOT NULL,
    [dv_inserted_date_time]             DATETIME        NOT NULL,
    [dv_insert_user]                    VARCHAR (50)    NOT NULL,
    [dv_updated_date_time]              DATETIME        NULL,
    [dv_update_user]                    VARCHAR (50)    NULL,
    [revenue_dim_date_key]              VARCHAR (8)     NULL,
    [refund_amount]                     DECIMAL (26, 6) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);

