CREATE TABLE [sandbox_ebi].[stage_hash_mms_Member] (
    [stage_hash_mms_Member_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                  CHAR (32)     NOT NULL,
    [MemberID]                 INT           NULL,
    [MembershipID]             INT           NULL,
    [EmployerID]               INT           NULL,
    [FirstName]                VARCHAR (50)  NULL,
    [MiddleName]               VARCHAR (25)  NULL,
    [LastName]                 VARCHAR (50)  NULL,
    [DOB]                      DATETIME      NULL,
    [Gender]                   CHAR (1)      NULL,
    [ActiveFlag]               BIT           NULL,
    [HasMessageFlag]           BIT           NULL,
    [JoinDate]                 DATETIME      NULL,
    [Comment]                  VARCHAR (250) NULL,
    [ValMemberTypeID]          INT           NULL,
    [InsertedDateTime]         DATETIME      NULL,
    [ValNamePrefixID]          INT           NULL,
    [ValNameSuffixID]          INT           NULL,
    [EmailAddress]             VARCHAR (140) NULL,
    [CreditCardAccountID]      INT           NULL,
    [ChargeToaccountFlag]      BIT           NULL,
    [CWMedicaNumber]           VARCHAR (16)  NULL,
    [CWEnrollmentDate]         DATETIME      NULL,
    [CWProgramEnrolledFlag]    BIT           NULL,
    [MIPUpdatedDateTime]       DATETIME      NULL,
    [SiebelRow_ID]             VARCHAR (15)  NULL,
    [UpdatedDateTime]          DATETIME      NULL,
    [PhotoDeleteDateTime]      DATETIME      NULL,
    [Salesforce_Prospect_ID]   VARCHAR (18)  NULL,
    [MemberToken]              BINARY (20)   NULL,
    [Party_ID]                 INT           NULL,
    [LastUpdatedEmployeeID]    INT           NULL,
    [Salesforce_Contact_ID]    VARCHAR (18)  NULL,
    [AssessJrMemberDuesFlag]   BIT           NULL,
    [CRMContactID]             VARCHAR (36)  NULL,
    [dv_load_date_time]        DATETIME      NOT NULL,
    [dv_updated_date_time]     DATETIME      NULL,
    [dv_update_user]           VARCHAR (50)  NULL,
    [dv_batch_id]              BIGINT        NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([MemberID]));

