CREATE TABLE [sandbox].[ops_PTrev_PCSD] (
    [SourceSystem]                       VARCHAR (14)    NOT NULL,
    [Workday_Region]                     VARCHAR (4)     NULL,
    [Club_Name]                          VARCHAR (50)    NULL,
    [Club_ID]                            INT             NULL,
    [TranDate]                           DATE            NULL,
    [PostedDate]                         DATE            NULL,
    [SourceProductID]                    VARCHAR (55)    NULL,
    [ProductDescription]                 VARCHAR (500)   NULL,
    [RevenueReportingDepartmentName]     VARCHAR (500)   NULL,
    [RevenueProductGroup]                VARCHAR (500)   NULL,
    [EmployeeID]                         INT             NULL,
    [EmployeeName]                       VARCHAR (200)   NULL,
    [MembershipID]                       INT             NULL,
    [MemberID]                           INT             NULL,
    [MemberName]                         VARCHAR (102)   NULL,
    [RevenueYearMonth]                   CHAR (7)        NULL,
    [RevenueQuantity]                    INT             NULL,
    [RevenueAmount]                      DECIMAL (27, 6) NULL,
    [SaleQuantity]                       INT             NULL,
    [SaleAmount]                         DECIMAL (26, 6) NULL,
    [TotalDiscountAmount]                DECIMAL (26, 6) NULL,
    [CurrencyCode]                       VARCHAR (25)    NULL,
    [TranDimDateKey]                     INT             NULL,
    [DivisionName]                       VARCHAR (500)   NULL,
    [SubdivisionName]                    VARCHAR (500)   NULL,
    [ECommerceShipmentNumber]            VARCHAR (255)   NULL,
    [ECommerceOrderNumber]               INT             NULL,
    [ECommerceAutoshipFlag]              INT             NULL,
    [ECommerceOrderEntryTrackingNumber]  INT             NULL,
    [ECommerceShippingAndHandlingAmount] DECIMAL (12, 2) NULL,
    [ECommerceProductCost]               DECIMAL (26, 6) NULL,
    [MMSTranID]                          INT             NULL,
    [MMSTranItemID]                      INT             NULL,
    [source_fact_table_key]              VARCHAR (4000)  NULL,
    [WorkdayOffering]                    VARCHAR (255)   NULL,
    [WorkdayCostCenter]                  VARCHAR (255)   NULL,
    [participation_id]                   VARCHAR (4000)  NULL,
    [booking_id]                         VARCHAR (4000)  NULL,
    [subscription_id]                    VARCHAR (4000)  NULL,
    [RevType]                            VARCHAR (12)    NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

