CREATE TABLE [sandbox].[UAT_fact_commprefs_user_preferences] (
    [ae_last_sent_date]            DATETIME        NULL,
    [ae_total_sent]                INT             NULL,
    [el_last_sent_date]            DATETIME        NULL,
    [el_total_sent]                INT             NULL,
    [email_address]                NVARCHAR (4000) NULL,
    [first_sent_date]              DATETIME        NULL,
    [flourish_opt_in]              INT             NULL,
    [global_opt_in]                INT             NULL,
    [global_opt_status_from_date]  DATETIME        NULL,
    [invalid_bounce]               INT             NULL,
    [invalid_bounce_date]          INT             NULL,
    [last_bounce_date]             DATETIME        NULL,
    [last_click_date]              DATETIME        NULL,
    [last_engagement_date]         DATETIME        NULL,
    [last_open_date]               DATETIME        NULL,
    [last_sent_date]               DATETIME        NULL,
    [lt_insider_opt_in]            INT             NULL,
    [no_engagement_13_months]      INT             NOT NULL,
    [no_engagement_12_months]      INT             NOT NULL,
    [no_engagement_3_months]       INT             NOT NULL,
    [no_engagement_6_months]       INT             NOT NULL,
    [notifications_opt_in]         INT             NULL,
    [promotional_opt_in]           INT             NULL,
    [total_hard_bounces]           INT             NULL,
    [total_sent]                   INT             NULL,
    [total_sent_after_last_engage] INT             NULL,
    [dv_load_date_time]            DATETIME        NOT NULL,
    [dv_load_end_date_time]        VARCHAR (12)    NOT NULL,
    [dv_batch_id]                  BIGINT          NOT NULL,
    [dv_inserted_date_time]        DATETIME        NOT NULL,
    [dv_insert_user]               NVARCHAR (128)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([email_address]));

