CREATE TABLE [dbo].[l_crmcloudsync_ltf_related_interest] (
    [l_crmcloudsync_ltf_related_interest_id] BIGINT       IDENTITY (1, 1) NOT NULL,
    [bk_hash]                                CHAR (32)    NOT NULL,
    [created_by]                             VARCHAR (36) NULL,
    [created_on_behalf_by]                   VARCHAR (36) NULL,
    [ltf_contact_id]                         VARCHAR (36) NULL,
    [ltf_interest_id]                        VARCHAR (36) NULL,
    [ltf_lead_id]                            VARCHAR (36) NULL,
    [ltf_opportunity_id]                     VARCHAR (36) NULL,
    [ltf_related_interest_id]                VARCHAR (36) NULL,
    [modified_by]                            VARCHAR (36) NULL,
    [modified_on_behalf_by]                  VARCHAR (36) NULL,
    [owner_id]                               VARCHAR (36) NULL,
    [owning_business_unit]                   VARCHAR (36) NULL,
    [owning_team]                            VARCHAR (36) NULL,
    [owning_user]                            VARCHAR (36) NULL,
    [ltf_add_by]                             VARCHAR (36) NULL,
    [ltf_add_source]                         INT          NULL,
    [ltf_remove_by]                          VARCHAR (36) NULL,
    [ltf_remove_source]                      INT          NULL,
    [dv_load_date_time]                      DATETIME     NOT NULL,
    [dv_r_load_source_id]                    BIGINT       NOT NULL,
    [dv_inserted_date_time]                  DATETIME     NOT NULL,
    [dv_insert_user]                         VARCHAR (50) NOT NULL,
    [dv_updated_date_time]                   DATETIME     NULL,
    [dv_update_user]                         VARCHAR (50) NULL,
    [dv_hash]                                CHAR (32)    NOT NULL,
    [dv_deleted]                             BIT          DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                            BIGINT       NOT NULL
)
WITH (CLUSTERED INDEX([bk_hash]), DISTRIBUTION = HASH([bk_hash]));

