CREATE TABLE [dbo].[l_crmcloudsync_ltf_live_chat] (
    [l_crmcloudsync_ltf_live_chat_id] BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                         CHAR (32)      NOT NULL,
    [activity_id]                     VARCHAR (36)   NULL,
    [created_by]                      VARCHAR (36)   NULL,
    [created_on_behalf_by]            VARCHAR (36)   NULL,
    [customers]                       VARCHAR (8000) NULL,
    [delivery_priority_code]          INT            NULL,
    [exchange_item_id]                NVARCHAR (200) NULL,
    [instance_type_code]              INT            NULL,
    [ltf_club]                        VARCHAR (36)   NULL,
    [ltf_employee_id]                 NVARCHAR (50)  NULL,
    [ltf_mms_club_id]                 NVARCHAR (50)  NULL,
    [ltf_original_lead]               VARCHAR (36)   NULL,
    [ltf_recommended_membership]      INT            NULL,
    [ltf_request_id]                  NVARCHAR (100) NULL,
    [ltf_web_team]                    VARCHAR (36)   NULL,
    [modified_by]                     VARCHAR (36)   NULL,
    [modified_on_behalf_by]           VARCHAR (36)   NULL,
    [owner_id]                        VARCHAR (36)   NULL,
    [owning_team]                     VARCHAR (36)   NULL,
    [owning_user]                     VARCHAR (36)   NULL,
    [process_id]                      VARCHAR (36)   NULL,
    [regarding_object_id]             VARCHAR (36)   NULL,
    [sender_mail_box_id]              VARCHAR (36)   NULL,
    [series_id]                       VARCHAR (36)   NULL,
    [service_id]                      VARCHAR (36)   NULL,
    [sla_id]                          VARCHAR (36)   NULL,
    [sla_invoked_id]                  VARCHAR (36)   NULL,
    [stage_id]                        VARCHAR (36)   NULL,
    [transaction_currency_id]         VARCHAR (36)   NULL,
    [dv_load_date_time]               DATETIME       NOT NULL,
    [dv_r_load_source_id]             BIGINT         NOT NULL,
    [dv_inserted_date_time]           DATETIME       NOT NULL,
    [dv_insert_user]                  VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]            DATETIME       NULL,
    [dv_update_user]                  VARCHAR (50)   NULL,
    [dv_hash]                         CHAR (32)      NOT NULL,
    [dv_deleted]                      BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                     BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

