CREATE TABLE [dbo].[l_humanity_employees] (
    [l_humanity_employees_id] BIGINT        IDENTITY (1, 1) NOT NULL,
    [bk_hash]                 CHAR (32)     NOT NULL,
    [employee_id]             BIGINT        NULL,
    [employee_eid]            VARCHAR (255) NULL,
    [employee_name]           VARCHAR (255) NULL,
    [employee_email]          VARCHAR (255) NULL,
    [company_name]            VARCHAR (255) NULL,
    [deleted_flg]             VARCHAR (255) NULL,
    [employee_status]         VARCHAR (255) NULL,
    [employee_role]           VARCHAR (255) NULL,
    [position_name]           VARCHAR (255) NULL,
    [location_name]           VARCHAR (255) NULL,
    [employee_to_see_wages]   VARCHAR (255) NULL,
    [last_active_date_utc]    VARCHAR (255) NULL,
    [user_timezone]           VARCHAR (255) NULL,
    [workday_position_id]     VARCHAR (255) NULL,
    [ltf_file_name]           VARCHAR (255) NULL,
    [company_id]              VARCHAR (255) NULL,
    [dv_load_date_time]       DATETIME      NOT NULL,
    [dv_r_load_source_id]     BIGINT        NOT NULL,
    [dv_inserted_date_time]   DATETIME      NOT NULL,
    [dv_insert_user]          VARCHAR (50)  NOT NULL,
    [dv_updated_date_time]    DATETIME      NULL,
    [dv_update_user]          VARCHAR (50)  NULL,
    [dv_hash]                 CHAR (32)     NOT NULL,
    [dv_deleted]              BIT           DEFAULT ((0)) NOT NULL,
    [dv_batch_id]             BIGINT        NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

