CREATE TABLE [dbo].[l_qtest_jira] (
    [l_qtest_jira_id]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [bk_hash]                        CHAR (32)      NOT NULL,
    [project_id]                     VARCHAR (4000) NULL,
    [project_status_id]              VARCHAR (4000) NULL,
    [project_template_id]            VARCHAR (4000) NULL,
    [release_project_id]             VARCHAR (4000) NULL,
    [release_id]                     VARCHAR (4000) NULL,
    [release_pid]                    VARCHAR (4000) NULL,
    [requirement_project_id]         VARCHAR (4000) NULL,
    [requirement_jira_defect_id]     VARCHAR (4000) NULL,
    [requirement_id]                 VARCHAR (4000) NULL,
    [requirement_pid]                VARCHAR (4000) NULL,
    [requirement_parent_id]          VARCHAR (4000) NULL,
    [test_case_id]                   VARCHAR (4000) NULL,
    [test_case_pid]                  VARCHAR (4000) NULL,
    [test_case_parent_id]            VARCHAR (4000) NULL,
    [test_case_test_case_version_id] VARCHAR (4000) NULL,
    [test_case_creator_id]           VARCHAR (4000) NULL,
    [test_case_project_id]           VARCHAR (4000) NULL,
    [dv_load_date_time]              DATETIME       NOT NULL,
    [dv_r_load_source_id]            BIGINT         NOT NULL,
    [dv_inserted_date_time]          DATETIME       NOT NULL,
    [dv_insert_user]                 VARCHAR (50)   NOT NULL,
    [dv_updated_date_time]           DATETIME       NULL,
    [dv_update_user]                 VARCHAR (50)   NULL,
    [dv_hash]                        CHAR (32)      NOT NULL,
    [dv_deleted]                     BIT            DEFAULT ((0)) NOT NULL,
    [dv_batch_id]                    BIGINT         NOT NULL
)
WITH (HEAP, DISTRIBUTION = HASH([bk_hash]));

