CREATE TABLE [dbo].[ltfdwstg_HybrisAllProducts] (
    [HybrisAllProductsKey]   INT             NOT NULL,
    [CreationTime]           DATETIME        NULL,
    [Code]                   VARCHAR (255)   NOT NULL,
    [Name]                   VARCHAR (255)   NULL,
    [OnlineDateTime]         DATETIME        NULL,
    [OfflineDateTime]        DATETIME        NULL,
    [Summary]                VARCHAR (8000)  NULL,
    [Description]            VARCHAR (8000)  NULL,
    [Weight]                 DECIMAL (30, 8) NULL,
    [ModifiedTime]           DATETIME        NULL,
    [Caption]                VARCHAR (255)   NULL,
    [EAN]                    VARCHAR (255)   NULL,
    [ProductCost]            DECIMAL (30, 8) NULL,
    [ProductHeight]          DECIMAL (30, 8) NULL,
    [ProductWidth]           DECIMAL (30, 8) NULL,
    [ProductLength]          DECIMAL (30, 8) NULL,
    [AutoShipFlag]           TINYINT         NULL,
    [ElectronicShippingFlag] TINYINT         NULL,
    [FulfillmentPartner]     VARCHAR (255)   NULL,
    [LTFOnlyProduct]         TINYINT         NULL,
    [LTFOfferFlag]           TINYINT         NULL,
    [eGiftCardFlag]          TINYINT         NULL,
    [OfferLink]              VARCHAR (255)   NULL,
    [OfferExternalLinkFlag]  TINYINT         NULL,
    [CatalogVersion]         BIGINT          NULL,
    [ActiveCatalogVersion]   BIGINT          NULL,
    [InsertedDateTime]       DATETIME        NOT NULL,
    [InsertUser]             VARCHAR (50)    NOT NULL,
    [UpdatedDateTime]        DATETIME        NULL,
    [UpdateUser]             VARCHAR (50)    NULL,
    [BatchID]                INT             NOT NULL,
    [ETLSourceSystemKey]     INT             NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

