CREATE TABLE [dbo].[ltfdwstg_HybrisSevenDayOrders] (
    [HybrisSevenDayOrdersKey]      INT             NOT NULL,
    [OrderCode]                    VARCHAR (255)   NOT NULL,
    [OrderEntryEntryNumber]        INT             NOT NULL,
    [OrderEntryTrackingNumber]     VARCHAR (255)   NULL,
    [OrderEntrySettlementDatetime] DATETIME        NULL,
    [OrderDatetime]                DATETIME        NULL,
    [OrderEntryShippingCost]       DECIMAL (30, 8) NULL,
    [OrderEntryTotalTax]           DECIMAL (30, 8) NULL,
    [OrderLtfPartyId]              VARCHAR (255)   NULL,
    [OrderCommisionEmployeeId]     VARCHAR (255)   NULL,
    [OrderAutoshipFlag]            TINYINT         NULL,
    [OrderEntryProductCode]        VARCHAR (255)   NULL,
    [OrderEntryProductName]        VARCHAR (255)   NULL,
    [OrderEntryProductDescription] VARCHAR (8000)  NULL,
    [OrderEntryQuantity]           INT             NULL,
    [OrderEntryBasePrice]          DECIMAL (30, 8) NULL,
    [OrderEntryTotalPrice]         DECIMAL (30, 8) NULL,
    [OrderEntryTotalDiscounts]     DECIMAL (30, 8) NULL,
    [OrderEntryRefundStatus]       VARCHAR (255)   NULL,
    [OrderEntryRefundDatetime]     DATETIME        NULL,
    [OrderEntryRefundAmount]       DECIMAL (30, 8) NULL,
    [InsertedDateTime]             DATETIME        NOT NULL,
    [InsertUser]                   VARCHAR (50)    NOT NULL,
    [UpdatedDateTime]              DATETIME        NULL,
    [UpdateUser]                   VARCHAR (50)    NULL,
    [BatchID]                      INT             NOT NULL,
    [ETLSourceSystemKey]           INT             NOT NULL,
    [RefundReason]                 VARCHAR (255)   NULL,
    [CustomerName]                 VARCHAR (255)   NULL,
    [CustomerEmail]                VARCHAR (255)   NULL,
    [CustomerGroup]                VARCHAR (255)   NULL,
    [MethodOfPay]                  VARCHAR (255)   NULL,
    [FulfillmentPartner]           VARCHAR (255)   NULL,
    [AffiliateID]                  VARCHAR (255)   NULL,
    [LTBUCKSearned]                DECIMAL (30, 8) NULL,
    [Capture_LTBUCKS]              DECIMAL (30, 8) NULL,
    [Capture_amex]                 DECIMAL (30, 8) NULL,
    [Capture_discover]             DECIMAL (30, 8) NULL,
    [Capture_master]               DECIMAL (30, 8) NULL,
    [Capture_visa]                 DECIMAL (30, 8) NULL,
    [Refund_LTBUCKS]               DECIMAL (30, 8) NULL,
    [Refund_amex]                  DECIMAL (30, 8) NULL,
    [Refund_discover]              DECIMAL (30, 8) NULL,
    [Refund_master]                DECIMAL (30, 8) NULL,
    [Refund_visa]                  DECIMAL (30, 8) NULL,
    [mmsPackageID]                 INT             NULL,
    [SelectedClub]                 VARCHAR (255)   NULL,
    [mmsTransactionId]             VARCHAR (255)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

