CREATE TABLE [dbo].[MMSMembershipSnapshot] (
    [MMSMembershipSnapshotKey]            INT           NOT NULL,
    [MembershipID]                        INT           NOT NULL,
    [ClubID]                              INT           NULL,
    [PurchaserID]                         INT           NULL,
    [LegacyCode]                          VARCHAR (12)  NULL,
    [AdvisorEmployeeID]                   INT           NULL,
    [ActivationDate]                      DATETIME      NULL,
    [ExpirationDate]                      DATETIME      NULL,
    [TotalContractAmount]                 MONEY         NULL,
    [CompanyID]                           INT           NULL,
    [Comments]                            VARCHAR (255) NULL,
    [MandatoryCommentFlag]                BIT           NULL,
    [ValEFTOptionID]                      TINYINT       NULL,
    [ValEnrollmentTypeID]                 TINYINT       NULL,
    [ValTerminationReasonID]              TINYINT       NULL,
    [MembershipTypeID]                    INT           NULL,
    [ValMembershipStatusID]               TINYINT       NULL,
    [CancellationRequestDate]             DATETIME      NULL,
    [CreatedDateTime]                     DATETIME      NULL,
    [UTCCreatedDateTime]                  DATETIME      NULL,
    [CreatedDateTimeZone]                 VARCHAR (4)   NULL,
    [MMSInsertedDateTime]                 DATETIME      NULL,
    [ValMembershipSourceID]               TINYINT       NULL,
    [AssessJrMemberDuesFlag]              BIT           NULL,
    [MMSUpdatedDateTime]                  DATETIME      NULL,
    [PromotionID]                         INT           NULL,
    [JrMemberDuesProductID]               INT           NULL,
    [Salesforce_Prospect_ID]              VARCHAR (18)  NULL,
    [MoneyBackCancelPolicyDays]           INT           NULL,
    [LastUpdatedEmployeeID]               INT           NULL,
    [QualifiedSalesPromotionID]           INT           NULL,
    [JoinFeePaid]                         MONEY         NULL,
    [Salesforce_Account_ID]               VARCHAR (18)  NULL,
    [Salesforce_Opportunity_ID]           VARCHAR (18)  NULL,
    [ChildCenterUnrestrictedCheckoutFlag] BIT           NULL,
    [InsertedDateTime]                    DATETIME      NOT NULL,
    [InsertUser]                          VARCHAR (50)  NOT NULL,
    [BatchID]                             INT           NOT NULL,
    [ETLSourceSystemKey]                  INT           NOT NULL,
    [UpdatedDateTime]                     DATETIME      NULL,
    [UpdateUser]                          VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

