CREATE TABLE [dbo].[MMSMember] (
    [MMSMemberKey]           INT           NULL,
    [MemberID]               INT           NOT NULL,
    [MembershipID]           INT           NULL,
    [EmployerID]             INT           NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [MiddleName]             VARCHAR (25)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [DOB]                    DATETIME      NULL,
    [Gender]                 CHAR (1)      NULL,
    [ssn]                    VARCHAR (9)   NULL,
    [ActiveFlag]             BIT           NULL,
    [HasMessageFlag]         BIT           NULL,
    [JoinDate]               DATETIME      NULL,
    [Comment]                VARCHAR (250) NULL,
    [ValMemberTypeID]        TINYINT       NULL,
    [MMSInsertedDateTime]    DATETIME      NULL,
    [ValNamePrefixID]        TINYINT       NULL,
    [ValNameSuffixID]        TINYINT       NULL,
    [EmailAddress]           VARCHAR (140) NULL,
    [CreditCardAccountID]    INT           NULL,
    [ChargeToaccountFlag]    BIT           NULL,
    [CWMedicaNumber]         VARCHAR (16)  NULL,
    [CWEnrollmentDate]       DATETIME      NULL,
    [CWProgramEnrolledFlag]  BIT           NULL,
    [MIPUpdatedDateTime]     DATETIME      NULL,
    [SiebelRowID]            VARCHAR (15)  NULL,
    [MMSUpdatedDateTime]     DATETIME      NULL,
    [InsertedDateTime]       DATETIME      NULL,
    [InsertUser]             VARCHAR (50)  NULL,
    [BatchID]                INT           NOT NULL,
    [ETLSourceSystemKey]     INT           NOT NULL,
    [PhotoDeleteDateTime]    DATETIME      NULL,
    [SalesforceProspectID]   VARCHAR (18)  NULL,
    [MemberToken]            BINARY (20)   NULL,
    [PartyID]                INT           NULL,
    [LastUpdatedEmployeeID]  INT           NULL,
    [SalesforceContactID]    VARCHAR (18)  NULL,
    [UpdatedDateTime]        DATETIME      NULL,
    [UpdateUser]             VARCHAR (50)  NULL,
    [AssessJrMemberDuesFlag] BIT           NULL
)
WITH (HEAP, DISTRIBUTION = HASH([MemberID]));

