CREATE TABLE [dbo].[obsolete_fact_boss_reservation] (
    [fact_boss_reservation_id]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [fact_boss_reservation_key]         CHAR (32)    NULL,
    [reservation]                       INT          NULL,
    [age_high]                          INT          NULL,
    [age_low]                           INT          NULL,
    [allow_wait_list]                   CHAR (1)     NULL,
    [billing_count]                     INT          NULL,
    [comment]                           NCHAR (40)   NULL,
    [continuous]                        CHAR (1)     NULL,
    [created_date_time]                 DATETIME     NULL,
    [day_of_week_friday_flag]           VARCHAR (14) NULL,
    [day_of_week_monday_flag]           VARCHAR (14) NULL,
    [day_of_week_saturday_flag]         VARCHAR (14) NULL,
    [day_of_week_sunday_flag]           VARCHAR (14) NULL,
    [day_of_week_thursday_flag]         VARCHAR (14) NULL,
    [day_of_week_tuesday_flag]          VARCHAR (14) NULL,
    [day_of_week_wednesday_flag]        VARCHAR (14) NULL,
    [dim_boss_product_key]              CHAR (32)    NULL,
    [dim_club_key]                      CHAR (32)    NULL,
    [dim_employee_key]                  CHAR (32)    NULL,
    [dim_mms_product_key]               CHAR (32)    NULL,
    [end_date_time]                     DATETIME     NULL,
    [grace_days]                        INT          NULL,
    [link_to_fact_boss_reservation_key] CHAR (32)    NULL,
    [modified_date_time]                DATETIME     NULL,
    [program_id]                        CHAR (25)    NULL,
    [publish_flag]                      CHAR (1)     NULL,
    [reservation_status]                CHAR (1)     NULL,
    [reservation_type]                  CHAR (1)     NULL,
    [start_date_time]                   DATETIME     NULL,
    [use_for_lt_bucks_flag]             CHAR (1)     NULL,
    [waiver_required_flag]              CHAR (1)     NULL,
    [dv_load_date_time]                 DATETIME     NULL,
    [dv_load_end_date_time]             DATETIME     NULL,
    [dv_batch_id]                       BIGINT       NULL,
    [dv_inserted_date_time]             DATETIME     NOT NULL,
    [dv_insert_user]                    VARCHAR (50) NOT NULL,
    [dv_updated_date_time]              DATETIME     NULL,
    [dv_update_user]                    VARCHAR (50) NULL
)
WITH (HEAP, DISTRIBUTION = HASH([fact_boss_reservation_key]));

